### ISSUE TITLE
[Feature Request] Add support for code block inside blockquote

### ISSUE THREAD

**Issue by r-gaia-cs** [yihui/knitr#1022]
knitr supports inline code inside blockquote. For example

    ```{r}
    x <- 1
    ```

    Test `r x`

    > Test `r x`

is converted to

~~~
<pre class="r"><code>x &lt;- 1</code></pre>
<p>Test 1</p>
<blockquote>
<p>Test 1</p>
</blockquote>
~~~

Will be great if code block inside blockquote is also allowed. For example

    > ```{r}
    > x <- 1
    > ```

    Test `r x`

which right now gives

~~~
Error in eval(expr, envir, enclos) : object 'x' not found
Calls: <Anonymous> ... in_dir -> inline_exec -> withVisible -> eval -> eval
~~~

**Comment by yihui** [comment]
Done. Thanks!
