### ISSUE TITLE
Rstudio pdf notebook knitr ggplot2 function issue

### ISSUE THREAD

**Issue by jw5** [yihui/knitr#1024]
When compiling a pdf notebook in Rstudio with knitr I hit a strange one. The ggplot2 calls work outside a function, but have positioning problems inside?

test code---------------------------------------------------------------

```r
require(ggplot2)

data <- data.frame(x=rep(1:100,2), y=rnorm(200), z=c(rep("a",100), rep("b",100)))

lookAt <- function(data, xname="x", yname="y", cname="z")
{
   gp1 <- ggplot(data=data, aes_string(x=xname, y=yname, color=cname)) + ggtitle(yname)
   print( gp1 + geom_point() )
   # the use of facets seems to cause a positioning problem?
   print( gp1 + geom_point() + geom_smooth() + facet_wrap(facets=~z, ncol=1, scale="free_y"))

   gp2 <- ggplot(data=data, aes_string(x=yname, color=cname)) + ggtitle(yname)
   print( gp2 + stat_ecdf())
}

 ## Function has problems with successive plot positions
lookAt(data)

 ## Inlined function works fine?
xname="x"
yname="y"
cname="z"
gp1 <- ggplot(data=data, aes_string(x=xname, y=yname, color=cname)) + ggtitle(yname)
print( gp1 + geom_point() )
print( gp1 + geom_point() + geom_smooth() + facet_wrap(facets=~z, ncol=1, scale="free_y"))

gp2 <- ggplot(data=data, aes_string(x=yname, color=cname)) + ggtitle(yname)
print( gp2 + stat_ecdf())
```

**Comment by yihui** [comment]
Sorry, I don't understand what you were talking about, since I don't see differences (at least within a minute). Please make screenshots and show me what exactly is wrong. Thanks!

**Comment by jw5** [comment]
Works fine to the screen, fails when compiling a notebook to pdf under
RStudio. Here is a pdf of the results on my system. Note that if I increase
the size of the plots via _output.yaml, then the layout/positioning works.

**Comment by yihui** [comment]
This looks like a LaTeX problem. I don't understand why LaTeX failed to move the second figure to the next line. Anyway, increasing the default figure width seems to work, e.g. you can add a chunk option to the beginning of your script:

    #+ fig.width = 8

**Comment by jw5** [comment]
Thanks
Jim
