### ISSUE TITLE
inconsistency in kable_markdown error

### ISSUE THREAD

**Issue by r2evans** [yihui/knitr#1025]
The error from `kable` (ultimately from `mat_pad`) about alignment is a little misleading:

```
knitr::kable(mtcars, align='b')
## Error in pad_width(c(m), rep(width, each = n), rep(side, each = n)) : 
##   'side' must be 'left', 'right', or 'both'
knitr::kable(head(mtcars), align='c')
## |                  | mpg  | cyl | disp | hp  | drat |  wt   | qsec  | vs | am | gear | carb |
## |:-----------------|:----:|:---:|:----:|:---:|:----:|:-----:|:-----:|:--:|:--:|:----:|:----:|
## |Mazda RX4         | 21.0 |  6  | 160  | 110 | 3.90 | 2.620 | 16.46 | 0  | 1  |  4   |  4   |
## |Mazda RX4 Wag     | 21.0 |  6  | 160  | 110 | 3.90 | 2.875 | 17.02 | 0  | 1  |  4   |  4   |
## |Datsun 710        | 22.8 |  4  | 108  | 93  | 3.85 | 2.320 | 18.61 | 1  | 1  |  4   |  1   |
## |Hornet 4 Drive    | 21.4 |  6  | 258  | 110 | 3.08 | 3.215 | 19.44 | 1  | 0  |  3   |  1   |
## |Hornet Sportabout | 18.7 |  8  | 360  | 175 | 3.15 | 3.440 | 17.02 | 0  | 0  |  3   |  2   |
## |Valiant           | 18.1 |  6  | 225  | 105 | 2.76 | 3.460 | 20.22 | 1  | 0  |  3   |  1   |
```

I infer from the error that `'both'` would be matched with `'b'`, whereas it's actually `'c'` (for center, of course).

**Comment by yihui** [comment]
But the documentation did not say you could use `b`, and I have no idea why you tried `align = 'b'`.

**Comment by r2evans** [comment]
Please allow me to clarify: I don't think the behavior is wrong, I think the error string is inconsistent.

I knew going in that the options were `[lrc]`. When I was automating some reports, though, my align variable was incorrectly adjusted, which is when I was given the error. I would never have found this had I been doing this manually.

I'm not suggesting you change the behavior of `kable` (`kable_mark`), I'm suggesting that the error report from `mat_pad` is inconsistent, that's all. It's just a one-liner (a one-worder?), and I thought a PR would be overkill for a 1 word change suggestion.

Clearly it's trivial. Cheers, Yihui, and thanks!

**Comment by yihui** [comment]
Thanks! I have added a one-liner so that the error will occur earlier and you will never see the error on the `side` argument again.
