### ISSUE TITLE
knit_params incorrectly params `y` name

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1027]
Repro:

```
content <- '---
title: "Untitled"
output: html_document
params:
   x: 1
   y: 2
   z: 3
   k: 4
---'

str(knitr::knit_params(content))
```

gives

```
> str(knitr::knit_params(content))
List of 4
 $ :List of 3
  ..$ name : chr "x"
  ..$ type : chr "integer"
  ..$ value: int 1
  ..- attr(*, "class")= chr "knit_param"
 $ :List of 3
  ..$ name : chr "TRUE"
  ..$ type : chr "integer"
  ..$ value: int 2
  ..- attr(*, "class")= chr "knit_param"
 $ :List of 3
  ..$ name : chr "z"
  ..$ type : chr "integer"
  ..$ value: int 3
  ..- attr(*, "class")= chr "knit_param"
 $ :List of 3
  ..$ name : chr "k"
  ..$ type : chr "integer"
  ..$ value: int 4
  ..- attr(*, "class")= chr "knit_param"
```

Note that the name for the `y` parameter has been substituted with `TRUE`.

```R
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_0.6.1     tools_3.2.0    RCurl_1.95-4.5 yaml_2.1.13    knitr_1.10.3  
[6] stringr_0.6.2  bitops_1.0-6   devtools_1.7.0
```

**Comment by kevinushey** [comment]
Looks like this is a bug directly in `yaml::yaml.load`, e.g. I see:

```
Browse[2]> yaml::yaml.load(yaml)
$title
[1] "Untitled"

$output
[1] "html_document"

$params
$params$x
[1] 1

$params$`TRUE`
[1] 2

$params$z
[1] 3

$params$k
[1] 4
```

**Comment by kevinushey** [comment]
It looks like this is intended behaviour from the YAML 1.1 spec: https://github.com/viking/r-yaml/issues/5

Perhaps `knitr` should also define a custom handler that ensures `y` and `n` are not coerced?

**Comment by yihui** [comment]
Yeah, that sounds crazy to me; how could anyone ever expect `y` to be `TRUE` when it is the name instead of the value of a field? A custom handler makes perfect sense to me. If we do this in knitr, I guess we will have to do it in rmarkdown and RStudio IDE as well? @jjallaire

**Comment by jjallaire** [comment]
I don't think we'll need to do anything special in rmarkdown or RStudio IDE as both just call knit_params to determine what the parameters are (or I missing something here?).

**Comment by yihui** [comment]
@jjallaire I was thinking that this behavior might not be desirable in general (not only for knit_params), so we may want to fix yaml.load() instead of only knit_params(). I just thought about it again, and it seems `y`/`n` won't appear in other parts of YAML in R Markdown, so we are probably good with fixing knit_params() only.

**Comment by jjallaire** [comment]
Yup, agreed!

**Comment by yihui** [comment]
I have disabled y/Y/n/N as booleans in the yaml.load handlers.

**Comment by jjallaire** [comment]
Awesome. Glad there was a reasonably straightforward way to do that!
