### ISSUE TITLE
Missing highlight definition in preamble

### ISSUE THREAD

**Issue by coatless** [yihui/knitr#1028]
When using Andre Simon's highlight program on Windows, knitr's (v1.10) generated .tex document lacks the \hlppc sequence definition:

**Error:**
! Undefined control sequence. \hlstd{}\hlppc

**Solution add to preamble:**
\let\hlppc\hlcom

**Used here:**
https://github.com/yihui/knitr-book/blob/master/DDR-Yihui-Xie-Chap1-3.Rnw

**MWE:**

```latex
\documentclass{article} 
\begin{document} 
Example pi program...
<<hi-cpp, engine='Rcpp'>>= 
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double pi_me()
{ 
  
  unsigned int num_steps = 100000;
  double x, pi, sum = 0.0;
  
  double step = 1.0/(double) num_steps;
  
  for (unsigned i = 0; i < num_steps; i++){
    x = (i + 0.5)*step;
    sum = sum + 4.0/(1.0 + x*x);
  }
  pi = step * sum;
  
  return pi;
}
@ 
\end{document}
```

**Comment by yihui** [comment]
Done. Thanks!
