### ISSUE TITLE
error=TRUE by default

### ISSUE THREAD

**Issue by MarcinKosinski** [yihui/knitr#1030]
I've read here [http://yihui.name/knitr/options/](http://yihui.name/knitr/options/) that by default the evaluation will not stop when there is an error

> error: (TRUE; logical) whether to preserve errors (from stop()); by default, the evaluation will not > stop even in case of errors!! if we want R to stop on errors, we need to set this option to FALSE

but my experiences tell me that by default it does stop..
Is this manual actual?

**Comment by krlmlr** [comment]
I've experienced this in RStudio, it seems that RStudio has this on by default. Knitting the file below from the command line via `Rscript -e "knitr::knit('test.Rmd')"` still produces a document where the error is shown:

    ```{r}
    stop("a")
    ```

**Comment by MarcinKosinski** [comment]
Good to know.

**Comment by yihui** [comment]
I think you were talking about R Markdown v2: http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html
