### ISSUE TITLE
quiet option for plot_crop()

### ISSUE THREAD

**Issue by WastlM** [yihui/knitr#1031]
`plot_crop()` should gain a `quiet` argument with `opts_knit$get("progress")` as its default value such that `knit(, quiet = TRUE)` is as quiet as it should be. Specifically, in case `quiet = TRUE`:
* omit `message("cropping ", x)`
* set `ignore.stdout = TRUE` in the system call.

This fixes the question at http://stackoverflow.com/questions/29077093/how-to-suppress-pdfcrop-printing-when-using-r-rmarkdown-render-function

Agreed? If yes, should I submit a pull request?

**Comment by yihui** [comment]
A pull request will be nice. Note you will also need to check on a Windows machine about how to suppress stdout for the `shell()` function: https://github.com/yihui/knitr/blob/master/R/plot.R#L298

Thanks!
