### ISSUE TITLE
Stata engine is not working for knitr v 1.10.5

### ISSUE THREAD

**Issue by nksingh62** [yihui/knitr#1033]
Output of following code
![untitled](https://cloud.githubusercontent.com/assets/7689233/7586818/6f22c794-f8ce-11e4-95f1-793613462f53.png)

shows command only but not the result.

in R markdown window of R studio (0.98), following message is displayed

output file: Preview-17285b1d79f3.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" Preview-17285b1d79f3.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Preview-17285b1d79f3.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\user\Documents\R\win-library\3.1\rmarkdown\rmd\h\default.html" --variable "theme:bootstrap" --include-in-header "C:\Users\user\AppData\Local\Temp\RtmpWEHYhi\rmarkdown-strf987e2d41fa.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\Users\user\Documents\R\win-library\3.1\rmarkdown\rmd\h\highlight" 

Output created: Preview-17285b1d79f3.html

**Comment by yihui** [comment]
See if our Stata ambassadors @Hemken @muschellij2 can help you :)

**Comment by Hemken** [comment]
I do not have the manuals for Stata version 9, so this may be hard to diagnose.

Did version 9 have a /q switch for working in batch mode?  Is Stata producing a log file, and is Stata closing after it has completed loading the data set and producing the frequency table?

**Comment by nksingh62** [comment]
Yes it is producing log file and closing program but command should be like this (if wstata.exe is in PATH)
```
wstata.exe /q /e do temp.do
```
while your program (as shown in R markdown console) is writing

```
wstata.exe /q /e temp.do
```

**Comment by Hemken** [comment]
That is much more clear.  The current documentation, Stata 14, also has "do".  I'll make the change, test, and get back to you.

I wonder when (which version) it became possible to drop "do"?  I think I've used Stata since before version 7!

**Comment by Hemken** [comment]
I've fixed this for both Windows and unix, and tested it on Windows - currently having problems getting to my linux server.  Once the pull request is merged, it should be good to go.
