### ISSUE TITLE
AsciiMath syntax

### ISSUE THREAD

**Issue by MySchizoBuddy** [yihui/knitr#1038]
Knitr uses mathjax as it's math rendering engine and mathjax also supports asciimath syntax. Please enable asciimath syntax in mathjax.

http://asciimath.org/

**Comment by yihui** [comment]
I guess the support of MathJax or AsciiMath is irrelevant to knitr, and it is the Markdown rendering engine that decides whether to support MathJax or AsciiMath, so you may want to file this issue to other repositories, depending on which Markdown rendering package you use (you did not say it, but chances are [rmarkdown](https://github.com/rstudio/rmarkdown)).
