### ISSUE TITLE
Rcpp caching issue

### ISSUE THREAD

**Issue by wrathematics** [yihui/knitr#1040]
I'm having problems re-running blocks with cached compiled code.  Example [here](https://gist.github.com/wrathematics/6ec6c33489573f436ee7).  This has the bonus problem of `cache.path` not working without manually adding a trailing `/`.

Anyway, the document will build once, but never twice, complaining there is no function `foo()` when the R block is re-run.

Edit:  forgot to mention I tried this in the version of knitr on CRAN and the version on GitHub as of 5/19/15.

**Comment by yihui** [comment]
The Rcpp issue is a known one. The compiled .so/.dll files are not saved (if I remember it correctly, Rcpp writes them to the temp dir, which will be removed once the R session exits), so there is no way to reload them the next time unless you stay in the same R session. I mentioned this to Dirk once. I don't quite remember what he said. I can definitely support it whenever Rcpp supports permanent shared libraries that can be re-used across R sessions.

The `cache.path` issue is expected. If you mean a dir, you should add a trailing slash. [Per documentation](http://yihui.name/knitr/options/), it is supposed to be a _prefix_ of the cache files. Sometimes you don't want `cache.path` to be a dir, e.g. `cache.path = 'prefix-for-report-A-'`. If I treat `cache.path` as a dir, users will lose the possibility of using it as a prefix. If I treat it as a prefix, users can still use it as a dir. So hopefully you see the rationale now.
