### ISSUE TITLE
fine-grained verbosity control

### ISSUE THREAD

**Issue by zabbal** [yihui/knitr#1041]
Right now verbosity is boolean - would be nice to make it integer for more fine-grained control. For example even with verbose=FALSE the chunk options are still printed. I'd like to see the progress of compilation but I find little use for chunk options (label is more than enough to find them in a source file).
Would be great to map current boolean to integer as follows:
0 - reserved, even less verbosity somehow
1 - show chunk label, omit chunk options
2 - current verbose=TRUE
3 - current verbose=FALSE

**Comment by yihui** [comment]
That makes sense, but personally I'm not very interested in it, nor do I have much spare time for it, so...
