### ISSUE TITLE
timing comment

### ISSUE THREAD

**Issue by zabbal** [yihui/knitr#1042]
Would be nice to have chunk option which would insert into output comment with the time it took to evaluate particular chunk.

**Comment by yihui** [comment]
You can do that via a chunk hook: http://yihui.name/knitr/hooks/ Just to illustrate the idea:

```r
library(knitr)
local({
  now = Sys.time()
  knit_hooks$set(timeit = function(before) {
    if (before) {
      now <<- Sys.time()
    } else {
      print(Sys.time() - now)
    }
  })  
})
```

**Comment by zabbal** [comment]
That code snippet will print on the screen while rendering. Instead I'd like to see this data added to resulting .tex as a comment.

**Comment by yihui** [comment]
You need to do your own homework :) The first edition has explained how chunk hooks work. Basically you just `paste('%', ...)` instead of `print(...)`.

**Comment by zabbal** [comment]
That doesn't work as well - the result is printed as:
\begin{kframe}
% Chunk rendering time: 12.786 seconds.
\end{kframe}
This litters final document with lots of empty grey boxes.

**Comment by yihui** [comment]
Can you raise the question on StackOverflow? http://stackoverflow.com/questions/tagged/knitr See if more experts can help you. For questions, usually I prefer to be the "backup person". If nobody can give you an answer, you are welcome to come back to me. Thanks!

**Comment by zabbal** [comment]
The \renewenvironment{kframe}{}{} trick mentioned in #154 seems like what I need but I don't understand how to apply it - just adding it before 1st R code in .Rtex seems to have no effect at all.

**Comment by zabbal** [comment]
For the sake of completeness here is the code which has finally worked:
% local({ # trick to measure chunk rendering time
%     now = Sys.time()
%     hook_output = knit_hooks$get('output')
%     knit_hooks$set(timeit = function(before) {
%         if (before) { now <<- Sys.time() }
%         else {
%             paste('\\end{kframe}\n', sprintf("%% Chunk rendering time: %s seconds.", round(Sys.time() - now, digits = 3)), '\n\\begin{kframe}')
%         }
%     })
% })

**Comment by yihui** [comment]
For the sake of real completeness, please link to the SO post: http://stackoverflow.com/q/30530008/559676
