### ISSUE TITLE
comment markup for results

### ISSUE THREAD

**Issue by zabbal** [yihui/knitr#1043]
Would be useful to add to "results" option markup 'comment' (in addition to 'asis' and 'hide') which would automatically comment out output (% in latex for example). This would allow dumping useful intermediate statistics (like output of tables() function for example) without polluting final document.

**Comment by yihui** [comment]
I think you can just do it by yourself by extending the `output` hook function.

```r
library(knitr)
local({
  hook_output = knit_hooks$get('output')
  knit_hooks$set(output = function(x, options) {
    if (options$results != 'comment') return(hook_output(x, options))
    # do whatever you want to `x` below (e.g. prepend %)
  })  
})
```

**Comment by zabbal** [comment]
This doesn't seem to work:

%     knit_hooks$set(output = function(x, options) {
%         if (options$results != 'comment') return(hook_output(x, options))
%         else return(paste("%", x))
%
%     })

and 
%% begin.rcode call-test, results = 'asis', comment = TRUE
...
Produce exactly the same output as before.

**Comment by yihui** [comment]
`results = 'comment'`
