### ISSUE TITLE
Garbled or missing LaTeX math formulas in RMarkdown->PDF knitr-converted document using xelatex (works with pdflatex)

### ISSUE THREAD

**Issue by hasenstein** [yihui/knitr#1045]
I have all the details here:

http://stackoverflow.com/questions/30410302/

I'm not sure if this is a knitr issue.

**Comment by yihui** [comment]
What **knitr** does is to knit the Rmd document to md, then the md document is handed over to other tools such as Pandoc. I cannot reproduce your problem on either Windows or Ubuntu. I'm closing this issue since it seems knitr has done its job correctly.
