### ISSUE TITLE
eval=F in Global option, eval=T in chunk. Then inline expression becomes double question mark.

### ISSUE THREAD

**Issue by Bozh** [yihui/knitr#1046]
Hi Yihui, I searched for a while but did not see the relevant post. Here is a minimal example. Is the following a bug or by design?
In the global options I set `eval` to FALSE because I do not wish to evaluate most of the chunks.
```
<<setup,include=FALSE,cache=FALSE>>=
library(knitr)
opts_chunk$set(eval=F)
@
```
But for some chunks I set them to TRUE, and later on quote the output by inline code.
```
<<x,eval=T>>=
x<-2
@
x=\Sexpr{x}
```
However, the inline code produces `x=??`, and no error is thrown. The same happens to rmd file. What's happening here?
I use `OS X 10.9.5`, `R 3.2.0`, `knitr 1.10`.

**Comment by yihui** [comment]
It was from the very early design of knitr. I just thought a while about it again, and changed the behavior. Now you should see the value of `x` with the development version of knitr here. Thanks for asking.

**Comment by Bozh** [comment]
Thanks for the reply and revision.
