### ISSUE TITLE
unsuppressable note from ggplot

### ISSUE THREAD

**Issue by zabbal** [yihui/knitr#1047]
Whaen attempting to use ggplot()/qplot() family of functions there multiple notes like:

Note: no visible binding for global variable ’.Data’ Note: no visible binding for
global variable ’.Data’ Note: no visible binding for global variable ’.xData’ Note:
no visible global function definition for ’initFields’ Note: no visible binding for
global variable ’.refClassDef’ Note: no visible binding for global variable ’scales’
Note: no visible binding for global variable ’..count..’

There seems to be no way to suppress it.

**Comment by zabbal** [comment]
Note: ugly hack mentioned in http://stackoverflow.com/questions/23475309/in-r-is-it-possible-to-suppress-note-no-visible-binding-for-global-variable could suppress it for variables (not sure about side effects though) but not for functions:

"Note: no visible global function definition for ’initFields’" is still there.

**Comment by yihui** [comment]
Please provide a minimal reproducible example: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md It may well be a ggplot2 issue.

**Comment by zabbal** [comment]
It turns out that enableJIT(n), where n > 1 from compiler package is to be blamed for those messages.
