### ISSUE TITLE
pandoc with custom --from overrides it with default "markdown"

### ISSUE THREAD

**Issue by anoeee** [yihui/knitr#1048]
Hi,
     My embedded configurations specify the from attribute and I noticed that the command generated with pandoc() repeats the "-f" option. I saw that you hardcoded "-f markdown" in pandoc.R. In my case this means that the option  autolink_bare_uris is not set. I believe this is due to the fact that the second -f overrides the first.

Here is my configuration:

```
<!--pandoc
t: latex 
latex-engine: xelatex 
f: autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures 
template: "default.tex"
highlight-style: tango
o: "report201506021033.pdf"
-->
```

And pandoc() outputs (I've cleared unnecessary paths to files):

```
> pandoc("report201506021033.md"), format="latex") # LaTeX/PDF
executing pandoc --latex-engine=xelatex -f autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --template="default.tex" --highlight-style=tango  -f markdown -t latex -o "report201506021033.pdf" "report201506021033.utf8md"
[1] "\"report201506021033.pdf\""
```

Thanks and congrats for a great library!

André Morais

**Comment by yihui** [comment]
Pull requests are welcome: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md :) Personally I'm not quite interested in this issue since our focus has been moved to **rmarkdown**: http://rmarkdown.rstudio.com

**Comment by anoeee** [comment]
Thanks for your reply. I've also moved to rmarkdown and am currently having no problems with it.
