### ISSUE TITLE
When `eval=FALSE` tidy is not applied.

### ISSUE THREAD

**Issue by Thell** [yihui/knitr#1052]
While looking into [an SO post][1] I noticed tidy isn't getting applied when `eval=FALSE`. Shouldn't it be?

    ```{r, code=lm, eval=FALSE, tidy.opts=list(width.cutoff=68)}
    ```

    ```{r, code=lm, results="hide", tidy.opts=list(width.cutoff=68)}
    ```

[1]:http://stackoverflow.com/q/30601602/173985

**Comment by yihui** [comment]
You can easily verify if `eval=FALSE` is the problem (it is not).

    ```{r eval=TRUE, tidy=TRUE}
    1+1
    ```
    
    ```{r eval=FALSE, tidy=TRUE}
    1+1
    ```

I'm quite surprised that `code = lm` seems to work. The chunk option `code` is supposed to take a character vector of source code, and a function object is not supposed to work here.
