### ISSUE TITLE
Generating tikz graphics fails with chunk before preamble

### ISSUE THREAD

**Issue by ClaudiusL** [yihui/knitr#1055]
The following MWE runs without problems:

```
\documentclass{article}

<<knitr-setup, echo=FALSE, cache=FALSE, message=FALSE>>=
library(knitr)

opts_chunk$set(
  echo = FALSE,
  dev = "tikz"
)
@

\begin{document}
<<test>>=
plot(1)
@
\end{document}
```
As soon as the chunk `knitr-setup` is moved *before* the preamble, compilation fails with the following error: `Error in getMetricsFromLatex(TeXMetrics)`.

The following code can be used to reproduce the issue:

```
<<knitr-setup, echo=FALSE, cache=FALSE, message=FALSE>>=
library(knitr)

opts_chunk$set(
  echo = FALSE,
  dev = "tikz"
)
@

\documentclass{article}

\begin{document}
<<test>>=
plot(1)
@
\end{document}
```

The problem seems to be that the knitr copies whole chunk `knitr-setup` to `test-1.tikz` which is invalid TEX code. Therefore I suppose this is a bug in knitr.

**Comment by yihui** [comment]
Yes, it may be a bug. Forgive my laziness, but perhaps it is easier for you to move the code chunk after `\documentclass{article}`? :)

**Comment by ClaudiusL** [comment]
I would not say that you are lazy – after all you developed knitr. ;) (That's a hidden "thank you").

Of course, moving the code after `\documentclass` is easy and works. But maybe it would be usefull to mention this somewhere in the documentation. Is the graphics manual the right place for such things? As soon as I have time I could propose an amendment (and as soon as I found out how to make pull requests). 
I would also recommend to mention that windows users need to [update filehash](https://github.com/Sharpie/RTikZDevice/issues/66#issuecomment-61311300) when using tikz. These two problems drove me crazy before I found out how to easily fix them and it would be a pitty if people didn't use tikz just because of them.

**Comment by yihui** [comment]
It should not be too difficult to fix the bug. I just don't have the time at the moment and it does not sound like a terrible bug.

Re: filehash, I guess the easiest way is to ask @rdpeng to release a new version of filehash to CRAN, and we update the version requirement in tikzDevice.

**Comment by yihui** [comment]
Should be fixed now. Thanks!
