### ISSUE TITLE
"keep_md: true" doesn't process 'r' code in header

### ISSUE THREAD

**Issue by nometus** [yihui/knitr#1056]
An example is the file below.  While the "knit HTML" button viewer displays the correct html output, the "test.md" file has the header "R" code ``"`r Sys.Date()`"`` unprocessed.  The rest of the "test.md" file looks fine.

test.Rmd 

    ---
    title: "BB Test"
    author: "BB"
    date: "`r Sys.Date()`"
    output: 
      html_document:
        keep_md: true
    ---

    This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

    When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

    ```{r}
    summary(cars)
    ```

the last `R` code block directly above DOES end with three backquotes.  I just can't figure out how to put them in...

**Comment by nometus** [comment]
hmm.  I hope you get the idea.  My paste of the original file got "processed".

**Comment by uribo** [comment]
@nometus 

> You can also evaluate R expressions inline by enclosing the expression within a single back-tick qualified with ‘r’ http://rmarkdown.rstudio.com

the same is true for YAML header.  i.e., 

```r
title: "BB Test"
author: "BB"
date: "`r Sys.Date()`"
output: html_document
```

**Comment by nometus** [comment]
That's the way my original file looks.  It didn't come through in the paste.  The html file renders correctly but the "test.md" file DOES NOT have the proper date. (It has the UNPROCESSED "R" code).

**Comment by yihui** [comment]
1. Please read the contributing guide regarding the format: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md I have edited your post.
2. I think this is an rmarkdown issue: https://github.com/rstudio/rmarkdown I don't know why `` `r Sys.Date()` `` was not processed, though.

**Comment by nometus** [comment]
Thanks!  I wasn't sure where in the rendering process the error is.

I'm new to this github issue tracker.  Is there an easy way to "move/re-assign" this issue to rmarkdown?  Or should I just open an issue there and reference this one?

**Comment by yihui** [comment]
@nometus No, there is no way to move an issue. You have to open a new one there. Sorry.
