### ISSUE TITLE
Add option to silently knit a child document

### ISSUE THREAD

**Issue by khughitt** [yihui/knitr#1059]
Would it be possible to add an option to silently knit a child document? E.g. something like:

    ```{r child='example.Rmd', silent=TRUE}
    ```
It is already possible to hide all of the R code and results by setting `include=FALSE`, however Markdown/ `LaTeX` from the child document will still be included in the final output.

This could be very useful, for example, for generating two different types of output -- one that is verbose (including analysis text, code, etc.) and another that is more sparse and perhaps just includes a smaller number of figures and text that is in the parent document.

A work-around for now might be to create a `verbose` variable, and then move all of the Markdown, etc. into chunks that are only rendered when `verbose=TRUE`:

    ```{r example_child_markdown, results='asis', eval=verbose}
     cat('Heading\n')
     cat('=======\n')
     cat('More text, markdown, etc...')
    ````

However, while this is functional, it is not very elegant and reduces the overall simplicity and readability of the child documents.

**Comment by yihui** [comment]
Perhaps you can put it inline, e.g. `` `r knit_child('example.Rmd', quiet=T)` ``

**Comment by khughitt** [comment]
That works perfect. Thanks! I tend to use the `child` chunk option so much that I forget about the `knit_child` function.

Thanks for the solution.
