### ISSUE TITLE
How to run Python code in virtual environment?

### ISSUE THREAD

**Issue by zhuzelong** [yihui/knitr#1062]
I use Python 3 with `venv` module. I did not find documentation about how to tell knitr to activate a virtual environment and then evaluate the Python code.

Besides, I wrote a Rmd document as:

    Test document.
    
    ```{r, setup}
    library(knitr)
    opts_chunk$set(engine='python')
    ```

    ```{python}
    import numpy as np
    import pandas as pd
    ```

    A Python code block.

    ```{python}
    # Create a data frame in Python
    df = pd.DataFrame(
             {
                 'A': [1, 2, 3, 4],
                 'B': [10, 20, 30, 40],
                 'C': [100, 50, -30, -50]
             }
         )

     print(df)
     ```

But RStudio raised an error: `Error in engine(options): ImportError: No module named pandas Calls`.

---
The example document is simple, importing a system package `time`, but how to import other packages? And do I have to specify `import numpy` in each Python block if I need it?

Thank you for anticipation.

**Comment by yihui** [comment]
Please see http://yihui.name/knitr/demo/engines for why it does not work and https://github.com/yihui/runr for how it may work.
