### ISSUE TITLE
Cache compiled stan model using stan engine?

### ISSUE THREAD

**Issue by dalewsteele** [yihui/knitr#1064]
I successfully ran the example from knitr book  using the **stan** engine to compile and save a simple model.  I defined the chunk as:

{r, engine='stan', engine.opts= list(x = 'ex1')} 

I naively tried adding the option 'cache=TRUE'  in attempt to save time recompiling
 the  'ex1' model:

{r, engine='stan', engine.opts= list(x = 'ex1'), cache=TRUE} 

This fails with an error.  Is there a mechanism to save the compiled **stan** model?

Working example pasted below. Thanks.

```{r, engine='stan', engine.opts= list(x = 'ex1')}

data {
  int<lower=0, upper=1> X[100];
}
parameters {
  real<lower=0, upper=1> p;
}
model {
  X ~ bernoulli(p);
}
```

The engine.opts = list(x = 'ex1'), passes the stan model as 'ex1' to rstan stan_model(), allowing it to be used in the next chunk.

```{r}
library(rstan)
fit <- sampling(ex1, data=list(X = rbinom(100, 1, 0.3)))
print(fit)
```

**Comment by yihui** [comment]
Should be fixed now. Thanks!
