### ISSUE TITLE
Latex macros produce incorrect spacing in tikz device output

### ISSUE THREAD

**Issue by jremmons** [yihui/knitr#1066]
When I try to compile figures with latex math symbols (e.g. \times), it looks like knitr creates space for the word "\times" instead of for the symbol "x" which leaves a lot of ugly whitespace. Here are a few simple pictures illustrating what I see.

When I use "1 x 2"
![selection_001](https://cloud.githubusercontent.com/assets/5061059/8553400/13d7f238-2498-11e5-9128-ab30b043ad4f.png)

When I use "1 $\\times$ 2"
![selection_002](https://cloud.githubusercontent.com/assets/5061059/8553445/49793b7c-2498-11e5-9653-127a7dc2a50d.png)

When I use "1 $\\times \\Sigma \\vartheta$ 2"
![selection_003](https://cloud.githubusercontent.com/assets/5061059/8553512/c02d97d6-2498-11e5-8a46-153c0c47853d.png)

Here is a minimal example reproducing the results in the pictures above. https://drive.google.com/open?id=0BxYcpdRpKOV2X2xGbUtnMTVqa0E

**Comment by yihui** [comment]
Sorry I don't have access to your example. I believe it is just a few lines of R and LaTeX code, so why not just post them directly here?

**Comment by jremmons** [comment]
\documentclass{standalone}

<<setup, echo=FALSE, cache=FALSE>>= 
opts_chunk$set(dev='tikz', echo=FALSE, cache=TRUE)
@

\begin{document}

<<volcano>>=
plot(volcano)

legend('topleft', 
c('1 $\\times \\Sigma \\vartheta$ 2'),
#c('1 x 2'), 
pch=c(1) )
@

\end{document}

**Comment by yihui** [comment]
What is the document class `standalone`?

**Comment by jremmons** [comment]
It is just a simplified document class [https://www.ctan.org/pkg/standalone?lang=en]. This issue exists for the more common article document class too. When I ran into this issue, I was using elsarticle.

**Comment by yihui** [comment]
Okay. I tested the `article` class:

```tex
\documentclass{article}

\begin{document}

<<volcano,dev='tikz'>>=
plot(volcano)

legend('topleft',
c('1 $\\times \\Sigma \\vartheta$ 2'),
pch=c(1) )
@

1 $\times \Sigma \vartheta$ 2

\end{document}
```

![screenshot from 2015-07-08 21 43 39](https://cloud.githubusercontent.com/assets/163582/8586923/6c23bcc4-25ba-11e5-8730-b0c5f3881ff8.png)

I don't see any difference between the math expression in the plot and the one in the LaTeX document; the latter one also has the "ugly space" you mentioned. The space is gone if I just remove the space after `1`, i.e. `'1$\\times \\Sigma \\vartheta$ 2'`. So I don't think this is a knitr-specific issue.

**Comment by jremmons** [comment]
I am referring to the whitespace after the equation. Is that what you are talking about? 
![c02d97d6-2498-11e5-8a46-153c0c47853d](https://cloud.githubusercontent.com/assets/5061059/8587069/fda06440-25ab-11e5-934e-47c47e4598a8.png)

**Comment by yihui** [comment]
Ah, I see. I thought you meant the space before x. Sorry.

In this case, I guess it is a tizkDevice issue: https://github.com/yihui/tikzDevice/issues

**Comment by jremmons** [comment]
Okay, I will submit an issue there.

**Comment by jremmons** [comment]
When I ran a similar code to try to generate the error with just tikzDevice, I don't get the same issue. 
```R
require(tikzDevice) 

tikz( 'tikz-example.tex' ) 
plot(volcano)
legend( 'topleft', c('1 $\\times \\Sigma \\vartheta$ 2'), pch=c(1) )

dev.off()
```
When I compile the output with pdflatex and the simple latex code below
```latex
\documentclass{elsarticle}
\usepackage{tikz}

\begin{document}

\input{tikz-example}

\end{document}
```
I get the following output (which is what I wanted when I used knitr)
![selection_001](https://cloud.githubusercontent.com/assets/5061059/8603817/66528e9a-262f-11e5-8cfd-a3fe418f85c9.png)

I can't seem to reproduce the error unless I use knitr and tikzDevice.

**Comment by krlmlr** [comment]
It looks like different `tikzDevice` options are used for measuring and for actually rendering the output:

```r
\documentclass{article}

\begin{document}

<<volcano,dev='tikz'>>=
plot(volcano)

legend('topleft',
c('\\newcommand{\\qqqqqqqq}{1 $\\times \\Sigma \\vartheta$ 2}\\qqqqqqqq'),
pch=c(1) )
@

\end{document}
```

My guess is, that the text `\newcommand{\qqqqqqqq}{1 $\times \Sigma \vartheta$ 2}\qqqqqqqq` is used for measurement (passed to LaTeX in escaped form). Does that make sense?

**Comment by jremmons** [comment]
Yes, this is exactly what I was trying to say in my original post; thanks for clarifying.

**Comment by krlmlr** [comment]
@yihui: I'm taking a closer look.

**Comment by krlmlr** [comment]
What a mess...

`legend` measures the width of the text [in "user" units](https://github.com/wch/r-source/blob/e0104656589073490591cefb12997178362feb7a/src/library/graphics/R/legend.R#L93-L95).

Measuring dimensions always seems to be done in the same units by the device. (Are these the "device" units?) On the tikzDevice side, measurement is done with cex=1.0 when called from the R script, and with cex=1.2 from knitr. The returned values are 37.57703 and 45.09232, respectively -- this ratio is exactly 1.2, there seems to be nothing wrong on the tikzDevice end. If I understand correctly, the computation is triggered [here](https://github.com/wch/r-source/blob/e0104656589073490591cefb12997178362feb7a/src/library/graphics/src/graphics.c#L2991-L2999). The subsequent [conversion between units](https://github.com/wch/r-source/blob/e0104656589073490591cefb12997178362feb7a/src/library/graphics/src/graphics.c#L303) could be different between knitr and "plain" R. I don't see why, though.

@yihui: Does this ring a bell? Where could the observed difference come from? Measurement seems to work just fine with the axis labels.

**Comment by yihui** [comment]
It is likely to be due to the fact that plots are first recorded using the pdf device, and redrawn in tikzDevice. The pdf device does not understand the LaTeX commands, so the width was calculated by treating the LaTeX expression as plain text.

I'm afraid this will be difficult to fix. One workaround is get rid of the box by `legend(..., bty = 'n')`.

**Comment by krlmlr** [comment]
Is there no way to use tikzDevice for recording? What needs to be done besides enhancing the [`chunk_device` function](https://github.com/yihui/knitr/blob/6affd5daa9dc99c38f37194f0ba3d9304bb707b5/R/block.R#L266)?

**Comment by yihui** [comment]
If `tikz()` supports `recordPlot()`, you can set `option(device = function(...) tikz(tempfile(), ...))`.

**Comment by krlmlr** [comment]
Splendid! The following works for me, the width is measured correctly:

```
\documentclass{article}

\begin{document}

<<init,dev='tikz'>>=
library(tikzDevice)
options(device = function(...) tikz(tempfile(), ...))
@

<<volcano,dev='tikz'>>=
plot(volcano)

legend('topleft',
c('\\newcommand{\\qqqqqqqq}{1 $\\times \\Sigma \\vartheta$ 2}\\qqqqqqqq'),
pch=c(1) )
@

\end{document}
```

Would you consider adapting `chunk_device`?

**Comment by yihui** [comment]
Well, if that works, I'd just go with it for now. I was aware of this kind of problems: https://github.com/yihui/knitr/blob/6affd5daa9/R/block.R#L268-L269 I only considered the png case so far. There a few reasons that I have not considered other devices: 1) recording with pdf(NULL) should be faster; 2) I have not tested if all other devices support recording as well; 3) it is fairly rare that this can be problematic (this is probably the second time I have seen users run into such problems over the three years).

**Comment by jremmons** [comment]
@krlmlr when I run your example, I got a segmentation fault. I copied your code exactly to a file called test.Rnw and tried to generate a .tex file. 

```
> library("knitr")
> knit("test.Rnw", "test.tex")


processing file: test.Rnw
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: init
  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: volcano (with options) 
List of 1
 $ dev: chr "tikz"

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(TikZ_StartDevice, file, width, height, onefile, bg,     fg, baseSize, lwdUnit, st
andAlone, bareBones, documentDeclaration,     packages, footer, console, sanitize, engine, symb
olicColors,     colorFileName, maxSymbolicColors, timestamp)
 2: tikzDevice::tikz(tempfile(), ...)
 3: (function (...) tikzDevice::tikz(tempfile(), ...))()
 4: do.call(dev, a)
 5: dev.new(width = width, height = height)
 6: dev_new()
 7: chunk_device(options$fig.width[1L], options$fig.height[1L], keep !=     "none", options$dev
, options$dev.args, options$dpi)
 8: block_exec(params)
 9: call_block(x)
10: process_group.block(group)
11: process_group(group)
12: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),     error 
= function(e) {        setwd(wd)        cat(res, sep = "\n", file = output %n% "")        messa
ge("Quitting from lines ", paste(current_lines(i),             collapse = "-"), " (", knit_conc
ord$get("infile"),             ") ")    })
13: process_file(text, output)
14: knit("test.Rnw", "test.tex")
```

**Comment by yihui** [comment]
That sounds like https://github.com/yihui/tikzDevice/issues/113

**Comment by krlmlr** [comment]
Thanks. 1) Recording with PDF is faster 3) but wrong in the case of tikzDevice (measurement results are probably very similar between all other devices except tikzDevice) 2) which means we might want to consider explicit support for tikzDevice at some point (but not necessarily for all other devices).

@jremmons: If you write

```
options(device = function(...) tikzDevice::tikz(paste0(tempfile(), ".tex"), ...))
```

instead, does it work then with the CRAN version of tikzDevice?

**Comment by jremmons** [comment]
@krlmlr yes, ```options(device = function(...) tikzDevice::tikz(paste0(tempfile(), ".tex"), ...))``` works with the CRAN version of tikzDevice. Thanks for the help with the work around.

**Comment by yihui** [comment]
@krlmlr Do you mind putting together a pull request? Should be simple. Thanks!
