### ISSUE TITLE
R Markdown and Animation - Animated Plot Cuts Trail of Document

### ISSUE THREAD

**Issue by s-fiebig** [yihui/knitr#1067]
Using R Markdown to include animations cuts all content after the animation.

First of all, I'm not entirely sure if the fault is with knitr or another part of the R Markdown Toolchain, but as I've solved it temporarily in knitr, I'm posting here.

OSX
R Version 3.2.1
knitr 1.10.5
R Markdown 0.7

Using the sample from the knitr docu about animation or from stackexchange (http://stackoverflow.com/questions/12038893/combining-r-markdown-and-animation-package) with additional content results in a html with all content missing after the animated plot. E.g.:
  
    ```{r clock, fig.width=7, fig.height=6, fig.show='animate'}
    par(mar = rep(3, 4))
    for (i in seq(pi/2, -4/3 * pi, length = 12)) {
        plot(0, 0, pch = 20, ann = FALSE, axes = FALSE)
        arrows(0, 0, cos(i), sin(i))
        axis(1, 0, "VI"); axis(2, 0, "IX")
        axis(3, 0, "XII"); axis(4, 0, "III"); box()
    }
    ```
    Everything from here on is missing.

Reason is the wrong html that is created:
``` 
...
<source src="bob" /><p>video of chunk clock</video></p>
...
```
The video and p tag are disordered. I haven't found (didn't look extensively) the code part introducing the paragraph tags and solved it by adding p tags myself in https://github.com/yihui/knitr/blob/fda78251de5ca3f43aab2808ccbb5442a0e4f090/R/hooks-html.R#L90
```
sprintf('<video %s><source src="%s" /><p>video of chunk %s</p></video>',
```

**Comment by yihui** [comment]
Thanks for the report. I can reproduce it. I think it is a Pandoc issue. Here is a minimal repro:

test.md

```html
<video ><source src="foo"/>asdf</video>
```

Run `pandoc test.md -o test.html` and you get:

```html
<video >
<source src="foo"/>
<p>asdf</video></p>
```

I have verified that the current latest version of Pandoc (1.15.0.4) still has the problem. I guess you can move it to https://github.com/jgm/pandoc/issues

**Comment by s-fiebig** [comment]
Thanks for checking this! Will move the issue.

**Comment by s-fiebig** [comment]
jgm did "not" accept this as a bug for the time being. He suggested introducing a paragraph (https://github.com/jgm/pandoc/issues/2290), what is as good as writing the p tags (what I did). 
I'm leaving this to you and don't do a pull request, unless otherwise told.
You can close the issue at your discretion.

**Comment by yihui** [comment]
Thanks a lot! A simple pull request adding `<p></p>` will be welcome :)
