### ISSUE TITLE
xcolor and knitr -> "incompatible color definition"

### ISSUE THREAD

**Issue by maxheld83** [yihui/knitr#1068]
This problem has previously been raised on [StackExchange](http://tex.stackexchange.com/questions/148188/knitr-xcolor-incompatible-color-definition) and I'm just adding an issue about this now.

A temporary [fix](https://groups.google.com/forum/#!msg/knitr/PQG2SnKe_eo/0S_n_Bfm3ZEJ) from @yihui solves the problem:

```r
knit_hooks$set(document = function(x) {sub('\\usepackage[]{color}', '\\usepackage{xcolor}', x, fixed = TRUE)})
```

**Comment by yihui** [comment]
Thanks. Hopefully Google searches can find this :)

**Comment by maxheld83** [comment]
I'm now using `knitr_1.11` off of CRAN, and I understand this was fixed in `v1.11` – but the problem still persists, unless fixed with the above hack ...

**Comment by yihui** [comment]
It is not fixed in knitr. This is not of top priority to me, and you still have to use the temporary fix above. Sorry.

**Comment by maxheld83** [comment]
Uh ok, thanks for clarifying I was just confused because of the milestone. 
Thank you for your fantastic work and support!

**Comment by johnbaums** [comment]
The suggested fix isn't work for me. The warning (`Package xcolor Warning: Incompatible color definition on input line 67.`) still appears for me despite the .tex file showing `\usepackage{xcolor}`. I'm compiling with XeLaTeX (Miktex), using `knitr 1.12.3`.

**Comment by bnicenboim** [comment]
any solution? It also appears for me, I'm using pdflatex

**Comment by mathuin** [comment]
This workaround does not appear to be compatible with `opts_knit$set(self.contained = FALSE)` -- when I run them both, the resulting `knitr.sty` file starts with `\usepackage[]{graphicx}\usepackage[]{color}`.
