### ISSUE TITLE
knit_params gives type as integer for list value

### ISSUE THREAD

**Issue by aronatkins** [yihui/knitr#1071]
Given an R markdown document containing the preamble:

    ---
    params:
        lst: [ 1,2,3 ]
    ---

```
> knitr::knit_params(readLines("lst.Rmd"))
[[1]]
$name
[1] "lst"

$type
[1] "integer"

$value
[1] 1 2 3

attr(,"class")
[1] "knit_param"
```

This isn't an immediate problem, but I wanted to file this if/when we support richer data types as parameter values.

**Comment by yihui** [comment]
That is obtained from `class()`: https://github.com/yihui/knitr/blob/f38d03856/R/params.R#L248-L251 What do you expect the type to be?

**Comment by aronatkins** [comment]
See #1070 for more context. I'm trying to determine if variables in a YAML block are scalars or other more complex types.

**Comment by aronatkins** [comment]
I think this is the best we can do for now. There is not enough information passed along saying if the YAML specifies a scalar value or a single-element list.
