### ISSUE TITLE
produce a named list from `knit_params`

### ISSUE THREAD

**Issue by aronatkins** [yihui/knitr#1075]
It seems that it is very common to transform from the list returned by `knit_params` to a named list for lookup from name-to-configuration.

Could this be returned as a named list? Do we lose anything over the current list?

**Comment by yihui** [comment]
I don't see any disadvantages with applying names to the list. The change looks trivial: https://github.com/yihui/knitr/blob/master/R/params.R#L258 (use `resolved_params[[name]]`). I'm wondering what @jjallaire thinks.

**Comment by aronatkins** [comment]
The only think I could think of is if traversal order would change. I would prefer a traversal order that matches the YAML order. I'm not sure how that is different for a list indexed by position versus a named list.

**Comment by jjallaire** [comment]
I see no disadvantages either and I don't believe that list traversal order
would change by adding names. @yihui, is that correct?

**Comment by yihui** [comment]
@jjallaire I think you are right.
