### ISSUE TITLE
Knitr / HTML fails using ggplot2 or base plot .using rstudio v3.2.1 

### ISSUE THREAD

**Issue by alfredaita** [yihui/knitr#1077]
the following code works fine in rstudio/console but fails in knitr/HTML:

library(ggplot2)
p1<-ggplot(x3a, aes(x=intervale,y=avg_steps)) +  geom_line(color="orange",size =1)+labs(title="Avg daily activity pattern") +
   theme_bw()
print(p1)

the message in output HTML:
 ## geom_path: Each group consist of only one observation. Do you need to adjust the group aesthetic?
It works fine in console.

**Comment by yihui** [comment]
It seems you didn't read the contributing guide: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by alfredaita** [comment]
Not very good with github . I found the correct approach
