### ISSUE TITLE
Using a single function (kable) from knitr in a package.

### ISSUE THREAD

**Issue by sahilseth** [yihui/knitr#1079]
I have a package flowr, located here: https://github.com/sahilseth/flowr.

I extensively used the kable function from knitr but no other functions. Adding knitr in the import fields leads to a extended dependency structure. 

Is there a way I could use kable, without putting knitr in the depends or imports field?

**Comment by yihui** [comment]
Sorry for the late response. I have been mostly on vacation. I understand your situation, but I don't have a plan to make a separate package for `kable()`. That said, I don't mind if you just copy my code in table.R and use it in your package (you may add me as a contributor or author of your package). Note there are a couple of other internal functions/objects in knitr (i.e. table.R is not completely self-contained). Of course, this will be a little difficult to maintain, but it is the only way I can think of if you don't want to import knitr.

**Comment by sahilseth** [comment]
Alright, have included kable as part of params now !

https://github.com/sahilseth/params/commit/8e522b1ae59a90a9ba796ada2c0abcd6c76bf5a1
