### ISSUE TITLE
Lyx knitr ggplot2 with data containing NAs

### ISSUE THREAD

**Issue by RegAllenCACSA** [yihui/knitr#1084]
Apologies if this is more a Lyx question. Thank you for your work on knitr
I have a mwe: a Lyx file that leads to an error
: 
"Something's wrong--perhaps a missing \item.
 ...                                                    
l.72 ...issing values (geom\_point).}}\end{kframe}" when the figure is produced (correctly) by ggplot +geom_point with data containing NAs 

The file but processes correctly when the data is subsetted to remove the NAs before calling ggplot
the Lyx file calls a child to set up the data and create a chunk as below

```
<<study.setup,echo=FALSE,eval=TRUE,include=FALSE>>=
require(ggplot2)
x=sample(c(0:100),size=30)
y=rnorm(length(x))
x[sample(1:length(x),size=10)]=NA
dat=cbind.data.frame(X=x,Y=y,Index = sample(1:5,replace=TRUE,size=30))
@

<<figure1, include = FALSE,warning=FALSE,echo=FALSE,eval=TRUE,fig.width=5,fig.height=5,results='hold' >>=
temp=subset(dat,!is.na(X))
res=ggplot(data=subset(temp), aes(y=Y, x=X,colour=factor(Index))) +geom_point()
print(res)
@
```

it then inserts a figure as follows (within a Tex code box)

```
\begin{figure} 
\begin{center} 
<<chunk1,ref.label="figure1",eval=TRUE,echo=FALSE,fig.show='asis'>>= 
@ 
\end{center} 
\caption{\label{fig:demo}use of geom\_point()}
\end{figure}
```

If the chunk creating the figure is, however,

```
<<figure1, include = FALSE,warning=FALSE,echo=FALSE,eval=TRUE,fig.width=5,fig.height=5,results='hold' >>=
res=ggplot(data=dat, aes(y=Y, x=X,colour=factor(Index))) +geom_point()
print(res)
@
```

Lyx stops with an error 
TIA

**Comment by yihui** [comment]
Two solutions. Add `warning = FALSE` to `chunk1`:

	\begin{figure} 
	\begin{center} 
	<<chunk1,ref.label="figure1",eval=TRUE,echo=FALSE,fig.show='asis',warning=FALSE>>= 
	@ 
	\end{center} 
	\caption{\label{fig:demo}use of geom\_point()}
	\end{figure}

Or use `\centering` instead of the `center` environment:

    \begin{figure}
    {\centering
    <<chunk1,ref.label="figure1",eval=TRUE,echo=FALSE,fig.show='asis'>>=
    @
    }
    \caption{\label{fig:demo}use of geom\_point()}
    \end{figure}
