### ISSUE TITLE
decimal point and decimal separator in kable

### ISSUE THREAD

**Issue by neuwirthe** [yihui/knitr#1086]
When working multilingually the locale of the R process might not match the local required for the produce files (html, latex, ...).
knitr::kable formats tables dor such documents.
In the multilingual case, additional parameters decimal.point and decimal.separator would make working easier.

**Comment by yihui** [comment]
Done. An example:

```r
x = as.data.frame(matrix(rnorm(60, 1e6, 1e4), 10))
knitr::kable(x, format.args = list(decimal.mark = ',', big.mark = "'"))
```

**Comment by ClaraRC** [comment]
Is posible to set the options decimal.mark and big.mark for the whole document? Like this writting reports will be faster.

**Comment by yihui** [comment]
It is not possible to set the options globally, but you can write a wrapper function by yourself:

```r
kable2 = function(...) {
  knitr::kable(..., format.args = list(decimal.mark = ',', big.mark = "'"))
}
```

**Comment by PabloSerrati** [comment]
For decimal mark, you can try whith this general option: 
options(OutDec= ",")
It works good for me.

**Comment by AnderAbc** [comment]
> options(OutDec= ",")
Hi, What u mean OutDec option ?   where and how to use it ?  :)

**Comment by cderv** [comment]
@AnderAbc it is as R options. See [`?options`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html)

```r
options(OutDec = ",")
knitr::kable(data.frame(x = seq(1, 2, 0.1)))
```
