### ISSUE TITLE
syntax highlighting for SQL?

### ISSUE THREAD

**Issue by beanumber** [yihui/knitr#1087]
In Markdown, syntax highlighting for SQL is present in `ioslides_presentation` output, but not `html_document`:

    ---
    title: "MWE: no SQL syntax highlighting"
    output: html_document
    ---
    
    ```{r, echo=FALSE, eval=TRUE, message=FALSE}
    require(knitr)
    opts_chunk$set(engine.opts = "-u root -pyourpass -t mysql")
    ```
    
    ## slide
    
    ```{mysql}
    select user, host, password as pwd
    from user u
    where user = 'root'
    order by user, host;
    ```

Change the `output: ioslides_presentation` and *get* syntax highlighting. 

Could syntax highlighting for SQL be added to the HTML output?

**Comment by yihui** [comment]
`html_document` uses highlight.js for syntax highlighting by default, and rmarkdown only supports C++ and R syntax highlighting. To syntax highlight code of other languages, you have to use different syntax highlighting engines, e.g. `pygments`

    ---
    title: "MWE: no SQL syntax highlighting"
    output: 
      html_document: 
        highlight: pygments
    ---

**Comment by beanumber** [comment]
How can I do this in an `.Rnw` file? 

I understand that I can do this:
```
<<>>=
highr::hi_andre("SELECT * FROM table;", language = 'SQL', format = 'latex')
@
```
But is there a way to do something like this:
```
<<engine='mysql', highlight='andre'>>=
SELECT * FROM table;
@
```

**Comment by yihui** [comment]
You can do this:

```latex
\documentclass{article}
\begin{document}
<<engine='highlight', engine.opts='-S sql -O latex'>>=
SELECT * FROM table;
@
\end{document}
```

For future questions, please use StackOverflow: http://stackoverflow.com/questions/tagged/knitr

**Comment by beanumber** [comment]
Cool, but that won't actually evaluate the code in MySQL.

(http://stackoverflow.com/questions/35246927/syntax-highlighting-while-rendering-sql-using-knitr)
