### ISSUE TITLE
split=TRUE does not cause use of iframe or \input{}

### ISSUE THREAD

**Issue by rbirkelbach** [yihui/knitr#1091]
Hello,

I use the chunk you see below. However, it neither uses iframes in the html code, nor \input{} in the LaTeX code. Also, no file of the output is created. Have I done anything wrong?

```r

 ```{r cars-summary,cache=TRUE,split=TRUE,echo=TRUE}
summary(cars)
```

```

Thanks, 
Robert


ps: The code is not completely shown. I hope you can see the raw code though.

**Comment by yihui** [comment]
Please read the contributing guide to know how to format your post: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

split=TRUE only works for .Rnw and .Rhtml documents; it doesn't work with R Markdown since there is no such concept of \input{} or iframe in Markdown.
