### ISSUE TITLE
Some non-ASCII characters disappear when knit()-ing

### ISSUE THREAD

**Issue by huftis** [yihui/knitr#1094]
When `knit()` a UTF-8 file (at least under Windows), some characters disappear under some circumstances. Here’s an example document:

    \documentclass{article}
    \begin{document}
    æ, ø, å
    1–2
    \end{document}

Note that the charcater between 1 and 2 is an en-dash (U+2013). If I run `knit("knitrtest.Rnw", encoding="UTF-8")` on the file, the relevant part of the resulting `.tex` document contains:

    \begin{document}
    æ, ø, å
    12
    \end{document}

That is, the non-ASCII characters are correctly copied to the document (as UTF-8 byte sequences), but the en-dash disappears. (*All* en-dashes in the documents seem to disappear.)

This is the bug. But a strange thing happens if I add, for example, a θ character:

    \documentclass{article}
    \begin{document}
    æ, ø, å
    1–2
    θ
    \end{document}

Running the same command, the en-dash appears, along with the θ character:

    \documentclass{article}
    \begin{document}
    æ, ø, å
    1–2
    θ
    \end{document}

So just adding a θ character somewhere in the document magically makes the bug disappear.

Things to note: This bug happens on Windows under Windows-1252 locale. The various characters have these properties (though all are stored as proper UTF-8 in the source file), which may perhaps be relevant(?):

\documentclass etc.: ASCII
æøå: non-ASCII, but available in ISO-8859-1 *and* Windows-1252
–: non-ASCII, not available in ISO-8859-1 but available in Windows-1252
θ: non-ASCII, not available in either ISO-8859-1 or Windows-1252, but available in Unicode

Also, when  I run the original file, which gives wrong output, no warnings are given. But if I run the file with a θ character, which gives the *correct* output, the following warning is given:

    Warning message:
    In native_encode(text) :
      some characters may not work under the current locale

So if only `knitr()` would work like it does when an ‘exotic’ character like θ is included, everything would work fine!

System information:

    Package: knitr
     Version: 1.11
     Maintainer: Yihui Xie <xie@yihui.name>
     Built: R 3.2.2; ; 2015-08-25 03:50:48 UTC; windows
    
    R Version:
     platform = x86_64-w64-mingw32
     arch = x86_64
     os = mingw32
     system = x86_64, mingw32
     status = 
     major = 3
     minor = 2.1
     year = 2015
     month = 06
     day = 18
     svn rev = 68531
     language = R
     version.string = R version 3.2.1 (2015-06-18)
     nickname = World-Famous Astronaut
    
    Windows 7 x64 (build 7601) Service Pack 1
    
    Locale:
     LC_COLLATE=Norwegian-Nynorsk_Norway.1252;LC_CTYPE=Norwegian-Nynorsk_Norway.1252;LC_MONETARY=Norwegian-Nynorsk_Norway.1252;LC_NUMERIC=C;LC_TIME=Norwegian-Nynorsk_Norway.1252

    Search Path:
     .GlobalEnv, package:knitr, package:stats, package:graphics, package:grDevices, package:utils, package:datasets,
     package:methods, Autoloads, package:base

**Comment by huftis** [comment]
Some additional information:

I *thought* the character was disappeared. But looking at the output here at GitHub, it looks like the `–` character is *mangled*, not completely gone. (When copying and pasting the character from the output, it looks like it’s disappeared in in the *edit field* at GitHub (and in my text editor), but as an ‘unknown character’ glyph in the ‘Preview’ tab and submitted comment.) So it’s some sort of reencoding bug, which for some strange reason affects the en-dash but not æ, ø and å.

Could it be related to the way R stores strings by default? It looks like `Encoding("–")` is automatically set to ‘latin1’ even though the `–` character is *not* part of latin1 (aka ISO-8859-1), only Windows-1252 (which is similar, but has a few extra characters)? If you add `θ` to the string, `Encoding()` returns UTF-8 instead.

**Comment by yihui** [comment]
Can you check if the en-dash is mangled below?

```r
x = readLines(file("knitrtest.Rnw", encoding="UTF-8"))
x
knitr:::native_encode(x)
```

**Comment by huftis** [comment]
When I run your code, everything looks fine (in RStudio):

    > x = readLines(file("knitrtest.Rnw", encoding="UTF-8"))
    > x
    [1] "\\documentclass{article}"
    [2] "\\begin{document}"       
    [3] "æ, ø, å"                 
    [4] "1–2"                     
    [5] "\\end{document}"         
    > knitr:::native_encode(x)
    [1] "\\documentclass{article}"
    [2] "\\begin{document}"       
    [3] "æ, ø, å"                 
    [4] "1–2"                     
    [5] "\\end{document}"

And all non-ASCII strings are encoded as UTF-8:

    > Encoding(x)
    [1] "unknown" "unknown" "UTF-8"   "UTF-8"   "unknown"

**Comment by huftis** [comment]
An addendum to my last comment: All non-ASCII strings in `x` are encoded as UTF-8, but when run through `native_encode()`, they’re **not**:

    > Encoding(knitr:::native_encode(x))
    [1] "unknown" "unknown" "latin1"  "latin1"  "unknown"

**Comment by yihui** [comment]
This should be fixed now. You may need to install the development version of a few other packages, though:

```r
devtools::install_github(c('yihui/evaluate', 'yihui/highr', 'yihui/knitr'))
```
