### ISSUE TITLE
Plot resolution is double than expected

### ISSUE THREAD

**Issue by Keyeoh** [yihui/knitr#1098]
I have found what I think is a strange behaviour. If I use knitr to process the following minimal example using RStudio,

    ```{r myplot, fig.width = 4, fig.height = 3, dpi = 300, fig.path = 'figures/'}
    plot(1:10, 1:10)
    ```
    ```{r}
    png('figures/myplot2.png', width = 4, height = 3, units = 'in', res = 300)
    plot(1:10, 1:10) 
    dev.off()
    ```
two images are generated in the figures folder: myplot-1.png (2400x1800px) and myplot2.png (1200x900px). The image generated by calling directly the png() function has the correct output resolution, while the one generated as a plot chunk has double the resolution, just as if it had been called using dpi=600. 

If I run knit2html() from an R command line, then everything works fine, and the two images are the same resolution. So I guess it might have something to be with the pandoc or knitr version included with RStudio. 

I have found a related issue, #901, but that was related to rgl, and I cannot seem to find a relationship between them.

I am using RStudio 0.99.473. My sessionInfo() (inside RStudio):

    R version 3.2.1 (2015-06-18)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.2 LTS

    locale:
     [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8            LC_COLLATE=es_ES.UTF-8    
     [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=es_ES.UTF-8    LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] htmltools_0.2.6 tools_3.2.1     yaml_2.1.13     rmarkdown_0.7   knitr_1.11      digest_0.6.8   

Any hint/help would be much appreciated.

**Comment by yihui** [comment]
This is because R Markdown v2 uses `fig.retina = 2` for HTML output by default http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html

> There are some other subtle changes, such as fig.retina (from NULL to 2 for the HTML output), ...

That is for better image quality on Retina displays. If you don't want it, you can set `fig.retina = NULL` or `1`.

**Comment by Keyeoh** [comment]
Thank you very much, Yihui. It seems I overlooked that doc section since I read the word Retina, as I was not playing with such an interface. Everything makes sense now.

**Comment by yihui** [comment]
Great. I agree it is pretty subtle and users may not notice it easily.
