### ISSUE TITLE
Cropping PDF fails with knitr > 1.10.5 under Windows.

### ISSUE THREAD

**Issue by ClaudiusL** [yihui/knitr#1099]
There seems to be a bug in knitr > 1.10.5 with cropping of PDFs under Windows.
Minimal example:

    \documentclass{article}
    \begin{document}
    <<setup>>=
    library(knitr)
    knit_hooks$set(crop = hook_pdfcrop)
    @
    
    <<makeAPlot, crop = TRUE>>=
    plot(1)
    @
    \end{document}

This works as expected (no warnings, plot is cropped) with knitr <= 1.10.5. 
It fails with knitr 1.11 and 1.11.2 (this is the version `install_github` installs, although according to the changelog there should be a version 1.12).
By "it fails" I mean that the PDF is not cropped and I get the following log (where I replaced German messages by a translation in []):

    [Loading required package]: knitr
    
    
    processing file: doc.Rnw
      |.............                                                    |  20%
      ordinary text without R code
    
      |..........................                                       |  40%
    label: setup
      |.......................................                          |  60%
      ordinary text without R code
    
      |....................................................             |  80%
    label: makeAPlot (with options) 
    List of 1
     $ crop: logi TRUE
    
    cropping figure/makeAPlot-1.pdf
    pdfcrop.exe: Invalid argument.
    pdfcrop.exe: Data: 4294967295
      |.................................................................| 100%
      ordinary text without R code
    
    
    output file: doc.tex
    
    [1] "doc.tex"
    [Warning]:
    [The command] '"pdfcrop" "figure/makeAPlot-1.pdf" "figure/makeAPlot-1.pdf"' [returned status] 1 
    Running pdflatex.exe on doc.tex...completed
    
    Created PDF: T:/kntirmwe/doc.pdf
    
    Issues: 1 badbox

I suppose this is an unexpected side-effect of the recent changes in `hook_pdfcrop()` and `plot_crop()`.

Environment: Windows 7, R 3.2.2.

**Comment by yihui** [comment]
Sorry about that. Should be fixed now in the development version.

**Comment by ClaudiusL** [comment]
Thank you for the quick fix! I can confirm that it solved the problem.
