### ISSUE TITLE
hook_pdfcrop applies regardles of chunk option "crop" (all figures cropped)

### ISSUE THREAD

**Issue by ClaudiusL** [yihui/knitr#1102]
As far as I understand and as far as I remember, the following should/did work:

    \documentclass{article}
    \begin{document}
    
    <<setup>>=
    library(knitr)
    knit_hooks$set(crop = hook_pdfcrop)
    @
    
    <<with-crop, crop = TRUE>>=
    plot(1)
    @
    
    <<no-crop, crop = FALSE>>=
    plot(1)
    @
    
    \end{document}

`hook_pdfcrop` is associated with the chunk option `crop` and only plots in chunks with `crop = TRUE` are cropped. However, this is not the case: *Both* plots are cropped.

I think this is a bug, but I am not sure if I'm mistaken because even "ancient" versions of R (3.1.0) and knitr (1.6) behave exactly as the current knitr versions (1.9, 1.10, 1.10.5, 1.11.3) with R 3.2.2.

All tests conducted with Windows 7.

**Comment by yihui** [comment]
I think you misunderstood chunk hooks. Here is the documentation: http://yihui.name/knitr/hooks/

> Chunk hooks are functions to be called before or after a code chunk when the chunk option is not `NULL` (it basically means as long as you set a option, the hook will be run)

`FALSE` is not `NULL`, so the chunk hook will be applied.

**Comment by ClaudiusL** [comment]
Oh, I'm sorry; my fault. I actually looked it up in the documentation but I was too sloppy: As soon as I saw that `TRUE` does the trick I concluded that `FALSE` must be the opposite.
 
Is there a reason that "any non-null value" must enable the hook instead of just `TRUE`/`FALSE`? 

Of course, changing this would be difficult due to backwards compatibility, I guess.

**Comment by yihui** [comment]
The reason is that I don't want to tie chunk option values to `TRUE`/`FALSE` only. Sometimes other values can be very useful, e.g.

```r
knit_hooks$set(pars = function(before, options) {
  if (before) par(options$pars)
})
```

Then 

    ```{r, pars = list(cex = 2, mar = c(4, 4, 1, 1))}

Normally I want to leave the design open if possible.

**Comment by ClaudiusL** [comment]
I see; didn't consider that the value of the chunk option is also used inside the hook. Then I must agree, the current system is good. Sorry again for the wrong issue report.

**Comment by yihui** [comment]
No worries! :)

**Comment by jtr13** [comment]
Thank you for posting this. I made the same mistake and feared that my computer was in an unstoppable cropping frenzy! And thank you Yihui for this feature -- the extra white space is horrible!
