### ISSUE TITLE
Knitr  stopped working on my Mac

### ISSUE THREAD

**Issue by rmbaskin** [yihui/knitr#1105]
Thanks for knitr - I have been using it for some time.  Now for the whining:  I can no longer knit any file including your knitr-minimal.Rnw example file.  Session output from a fresh session below:

R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.1.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.65 (6784) x86_64-apple-darwin13.1.0]

[History restored from /Users/rmbaskin/.Rapp.history]

> library(knitr)
Warning message:
package ‘knitr’ was built under R version 3.1.3 
> 
> knitpath <- "/Users/rmbaskin/technical/R.Projects/ZZZZ/Rnw"
> infile   <- "knitr-minimal.Rnw"
> outfile   <- "knitr-minimal.tex"
> 
> knit( input = file.path(knitpath, infile, fsep = "/"),  output = file.path(knitpath, outfile, fsep = "/") )

processing file: /Users/rmbaskin/technical/R.Projects/ZZZZ/Rnw/knitr-minimal.Rnw
  |.........                                                        |  14%
  |...................                                              |  29%
label: setup (with options) 
List of 2
 $ include: logi FALSE
 $ cache  : logi FALSE

Quitting from lines 19-23 (/Users/rmbaskin/technical/R.Projects/ZZZZ/Rnw/knitr-minimal.Rnw) 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 31, 0
In addition: Warning messages:
1: In is.na(res[, 1]) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(res) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by rmbaskin** [comment]
I forgot to mention that knitr created the first 17 lines of the knitr-minimal.tex file up through the line \begin{document}

**Comment by yihui** [comment]
Please read FAQ 1 if you have not: http://bit.ly/knitr-faq
