### ISSUE TITLE
hooks to decorate/modify chunk code?

### ISSUE THREAD

**Issue by bbolker** [yihui/knitr#1106]
I've been trying to think of a way that Python chunks could pickle/unpickle results, leading to the appearance (if not the performance) of a Python session that persisted across chunks.  Basically, if it were possible to write hooks that called R code (natch) to add lines at the beginning and end of the chunk code, they could be used to check for/update a persistent file that contained the local variables defined in the code chunk ...

Is there already a way to do this that I'm not aware of, or is it something that would be reasonably straightforward ... (I'm enough of a non-python expert that even the unpickling/pickling stuff could be a bit of work for me, but I think I could figure out how to do it ...)

**Comment by yihui** [comment]
I'm not sure if I understand your question, but if you are looking for a way to use a persistent Python session, you may take a look at https://github.com/yihui/runr

**Comment by bbolker** [comment]
OK, thanks, I'll take a look.

The end goal is to be able to use Python chunks in a knitr file as follows:

chunk 1 (not trying to get this right in Github markdown):

a = 1 + 1

... text ...

chunk 2 

print(a)

**Comment by yihui** [comment]
Okay I see. I think the `python` engine in the **runr** package should just work.
