### ISSUE TITLE
`quiet = TRUE` does not suppress output for `knit2pdf`

### ISSUE THREAD

**Issue by NattyE** [yihui/knitr#1108]
When running `knit2pdf()`, it does not suppress the LaTeX output when using `quiet = TRUE`. I am running `knitr v1.11`. The example I am running is:

## test.Rnw file
    \documentclass[a4paper,12pt]{article}
    
    \begin{document}
    some stuff
    \end{document}

## R Code
    knitr::knit2pdf(input = "./test.Rnw", quiet = TRUE)

## Output to R console:
    This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit)
    entering extended mode
    (test.tex
    LaTeX2e <2015/01/01> patch level 2
    Babel <3.9m> and hyphenation patterns for 69 languages loaded.
    (C:\MiKTeX\tex\latex\base\article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (C:\MiKTeX\tex\latex\base\size12.clo))
    (C:\MiKTeX\tex\latex\graphics\graphicx.sty
    (C:\MiKTeX\tex\latex\graphics\keyval.sty)
    (C:\MiKTeX\tex\latex\graphics\graphics.sty
    (C:\MiKTeX\tex\latex\graphics\trig.sty)
    (C:\MiKTeX\tex\latex\00miktex\graphics.cfg)
    (C:\MiKTeX\tex\latex\pdftex-def\pdftex.def
    (C:\MiKTeX\tex\generic\oberdiek\infwarerr.sty)
    (C:\MiKTeX\tex\generic\oberdiek\ltxcmds.sty))))
    (C:\MiKTeX\tex\latex\graphics\color.sty (C:\MiKTeX\tex\latex\00miktex\color.cfg
    )) (C:\MiKTeX\tex\latex\framed\framed.sty) (C:\MiKTeX\tex\latex\base\alltt.sty)
     (C:\MiKTeX\tex\latex\upquote\upquote.sty) (test.aux)
    (C:\MiKTeX\tex\context\base\supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) [1{C:/Users/neastwood1/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
    (test.aux) )<C:/MiKTeX/fonts/type1/public/amsfonts/cm/cmr12.pfb>
    Output written on test.pdf (1 page, 10374 bytes).
    Transcript written on test.log.
    This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit)
    entering extended mode
    (test.tex
    LaTeX2e <2015/01/01> patch level 2
    Babel <3.9m> and hyphenation patterns for 69 languages loaded.
    (C:\MiKTeX\tex\latex\base\article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (C:\MiKTeX\tex\latex\base\size12.clo))
    (C:\MiKTeX\tex\latex\graphics\graphicx.sty
    (C:\MiKTeX\tex\latex\graphics\keyval.sty)
    (C:\MiKTeX\tex\latex\graphics\graphics.sty
    (C:\MiKTeX\tex\latex\graphics\trig.sty)
    (C:\MiKTeX\tex\latex\00miktex\graphics.cfg)
    (C:\MiKTeX\tex\latex\pdftex-def\pdftex.def
    (C:\MiKTeX\tex\generic\oberdiek\infwarerr.sty)
    (C:\MiKTeX\tex\generic\oberdiek\ltxcmds.sty))))
    (C:\MiKTeX\tex\latex\graphics\color.sty (C:\MiKTeX\tex\latex\00miktex\color.cfg
    )) (C:\MiKTeX\tex\latex\framed\framed.sty) (C:\MiKTeX\tex\latex\base\alltt.sty)
     (C:\MiKTeX\tex\latex\upquote\upquote.sty) (test.aux)
    (C:\MiKTeX\tex\context\base\supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) [1{C:/Users/neastwood1/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
    (test.aux) )<C:/MiKTeX/fonts/type1/public/amsfonts/cm/cmr12.pfb>
    Output written on test.pdf (1 page, 10374 bytes).
    Transcript written on test.log.
    [1] "test.pdf"

## Session Info:
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
    [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] knitr_1.11
    
    loaded via a namespace (and not attached):
    [1] tools_3.2.2  RODBC_1.3-12

**Comment by yihui** [comment]
I just checked it on Windows, and I see texi2dvi is missing in MikTeX for some reason (`Sys.which('texi2dvi')` is `NULL`), in which case I guess R cannot suppress the LaTeX log. See `?tools::texi2dvi`. I don't know how to install texi2dvi in MikTeX.

**Comment by NattyE** [comment]
It looks as though the `texi2dvi.exe` file has been removed from the latest version of MiKTeX 2.9.

http://sourceforge.net/p/miktex/bugs/2400/

I can confirm that I do not have the file on my machine which may well be where the issue has come from as I am sure `quiet = TRUE` used to work...

**Comment by yihui** [comment]
Then you may report this to R core and see what they can do. I'm just calling `tools::texi2dvi()` in `knitr::knit2pdf()` and I guess there isn't much I can do on my side.

**Comment by NattyE** [comment]
Hi Yinhui, I posted a message to the R Core team and I received the following reply:

> We know texi2dvi.exe has been removed.  However, the MiKTeX author has broken his updater (and it has been broken for weeks), so we cannot update MiKTeX ....

> This has already been worked around in the doc/manuals/Makefile.win usage.

> The behaviour is documented in the help file for tools::texi2dvi. 
Please insist the knitr author fixes his own error.

> -Brian Ripley

I will continue to look into this and I will let you know what I find.

**Comment by yihui** [comment]
Oh Ripley... Lovely. I'm wondering what error I have -- I'm simply calling `tools::texi2dvi()`. I have read the documentation and told you the limitation of it. I'm not sure what else he expects me to do, or if you have paraphrased what I said correctly. Anyway, I don't want to argue anything when he is on board. I'll just lose by definition :)

Personally I'd just call something like `latexmk -quiet` to compile .tex to .pdf. I guess that will be much easier than the annoying business of texi2dvi/texi2pdf.

**Comment by NattyE** [comment]
Haha I had the exact same thoughts! Brian...has a way with words, doesn't he?

I will use latexmk for the time being, I'm using it for my Sweave documents anyway. I will try to look into the issue a little more and if I come up with anything then I shall let you know. Thanks Yinhui!
