### ISSUE TITLE
No tables in output when using if-condition

### ISSUE THREAD

**Issue by Toobias** [yihui/knitr#1109]
Hi,

I've tried to produce tables with knitr::kable within an if-condition. But all tables but the last one are just ignored and not in the output. Furthermore, if I have no caption-argument for the first table, the first table gets the caption of the next table from the output. Here is the example:

```{r Tables, echo=FALSE}
n <- 100
p <- 0.1
r <- 0.2
omega <- 0.5
alpha <- 0.7
beta <- 0.2

Table1 <- matrix(NA,1,6)
Table1[1,] <- c(n,p,r,omega,alpha,beta)
colnames(Table1) <- c("n","$\\pi$","r","$\\omega$","$\\alpha$","$\\beta$")
knitr::kable(Table1)

if(1>0){

Table2 <- matrix(NA,1,3)
Table2[1,] <- c(n,p,r)
colnames(Table2) <- c("n","p","r")
knitr::kable(Table2,caption="Table 2")

Table3 <- matrix(NA,1,5)
Table3[1,] <- c(3,n,p,r,omega)
colnames(Table3) <- c("Table","n","p","r","omega")
knitr::kable(Table3,caption="Table 3")

TableX <- matrix(NA,1,5)
TableX[1,] <- c(n,omega,p,r,alpha)
colnames(TableX) <- c("n","omega","p","r","alpha")
knitr::kable(TableX, caption="Last Table")

}
```

Session-Info:
> library(knitr); sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.11

loaded via a namespace (and not attached):
 [1] magrittr_1.5    formatR_1.2.1   htmltools_0.2.6 tools_3.2.2     yaml_2.1.13     stringi_0.5-5   rmarkdown_0.8   highr_0.5.1     stringr_1.0.0  
[10] digest_0.6.8    evaluate_0.8

**Comment by yihui** [comment]
For the caption, see #895.

For the tables, they won't appear by default when they are not generated from _top-level_ R expressions, and those inside an if clause are not top-level expressions. You will need to explicitly print() them, and use the chunk option `results = 'asis'`.
