### ISSUE TITLE
auto overwrite existing file

### ISSUE THREAD

**Issue by englianhu** [yihui/knitr#1110]
Is it possible to auto overwrite existing file when we **knit** xxx.Rmd files?
```diff
- Error: The name of the input file cannot contain the special shell characters: [ <>()|\:&;#?*] (attempted - to copy to a version without those characters 'Natural_Language_Analysis.Rmd' however that file  already exists)
- Execution halted
```

**Comment by yihui** [comment]
Silently overwriting files is almost always a bad idea. We'd rather bother you with an error message than letting you regret after you carelessly overwrote a file that you didn't mean to.
