### ISSUE TITLE
knitr loading the .RData workspace intended?

### ISSUE THREAD

**Issue by felasa** [yihui/knitr#1111]
It caused me tremendous headache because it was loading outdated functions, I didnt understand what was happening and how could knitr travel in time.

**Comment by yihui** [comment]
That is simply the behavior of R. I don't do anything about it on my side. You can just tell R not to load `.RData`, or even better, just don't save the workspace when you quit R. If you work in RStudio, you can set such options from `Tools -> Options`.

**Comment by felasa** [comment]
I do that, but I had an older .RData file lying around from before I set the option in RStudio. In the RStudio session the workspace isn't loaded or saved. But when I knit the file it was. took me a while to figure out that a function was being masked in .GlobalEnv. I guess RStudio (0.98) is at fault for not passing on the preference to the knitr R session. Writing this for reference.

**Comment by yihui** [comment]
Okay I see. Thanks for the reference!
