### ISSUE TITLE
knit error with opts_chunk$set(eval=FALSE)

### ISSUE THREAD

**Issue by vladchimescu** [yihui/knitr#1112]
Hey,
I want to knit Rnw files with `eval = FALSE` (and `results = "hide", highlight = FALSE`). However, the first time I knit  with `eval = FALSE`, it gives me an error in eval(...) in line [some line number], even though I explicitly set in `opts_chunk$set(...)` not to evaluate.

 However, if I knit the first time with `eval = TRUE` and subsequently with `eval = FALSE`, the output .tex file is produced without any errors. Is this behavior intended? Does one have to knit twice in order to get a TeX file without R code output?

**Comment by yihui** [comment]
Sorry I don't quite understand what you described. A minimal reproducible example is better than any description. If you set `opts_chunk` in a code chunk, you should make sure this code chunk is evaluated, e.g.

```
<<<eval=TRUE>>=
knitr::opts_chunk$set(eval = FALSE)
@
```

When you knit the file, I'd recommend you to do it in a new R session (to avoid side-effects generated from the previous run), which is what RStudio does when you click the Knit button.

**Comment by vladchimescu** [comment]
I tried to set `eval = FALSE` globally for the whole document both within the first code chunk and in the RStudio prompt prior to knitting, but the knit process breaks off somewhere halfway through, if I don't knit the vignette with `opts_chunk$set(eval = TRUE)` first and then again  but with `opts_chunk$set(eval = FALSE)`. 
The example would be DESeq2.Rnw vignette from the [DESeq2](http://bioconductor.org/packages/release/bioc/html/DESeq2.html) Bioconductor package. I haven't found anything particular in this vignette, but it keeps crashing with `eval = FALSE` giving me "error in eval(...) expression line ...". Doesn't the global `opts_chunk$set(eval = FALSE)` tell knitr to just convert code chunks into listings enclosed code snippets?

**Comment by yihui** [comment]
Even if you set the global option `eval = FALSE`, there might be code chunks that have local chunk options `eval = TRUE`. Local options override global options.

Please feel free to re-open the issue after you are able to provide a minimal reproducible example and tell me the exact steps to reproduce the problem.
