### ISSUE TITLE
ggvis and spin don't work together

### ISSUE THREAD

**Issue by zslastman** [yihui/knitr#1114]
Sorry if this is an issue for the ggvis guys rather than you...

This works fine and results in a plot on the html report outputted by running spin() on the document.

```r
mtcars%>%qplot(data=.,x=wt,y=mpg)
```

This:

```r
mtcars%>%ggvis(x=~wt,y=~mpg)
```

Does not work, and instead, on the report, I get 

```html
<!--html_preserve-->

Renderer: SVG | Canvas
Download
<!--/html_preserve-->
```

**Comment by yihui** [comment]
You should not use `spin()` in this case, but use `rmarkdown::render()` instead. `spin()` is for R Markdown v1, and only R Markdown v2 understands ggvis objects.
