### ISSUE TITLE
Can I specify the font size when I specify the chunk option `results = "asis"`

### ISSUE THREAD

**Issue by fountainer** [yihui/knitr#1116]
I want to use `xtable`. So I have to specify `results = "asis"`. It seems I can't specify `size = "footnotesize"`. The font size of code does not change.

**Comment by yihui** [comment]
You can either manually type `\begin{footnotesize}` and `\end{footnotesize}` around your chunk, or set up a chunk hook to do that automatically.

When `results = 'asis'`, I tend not to add anything to the output of the code chunk.
