### ISSUE TITLE
knitr:: kable changes chron dates

### ISSUE THREAD

**Issue by liesb** [yihui/knitr#1118]
Not sure whether this is related to https://github.com/yihui/knitr/issues/806.
Dates (and differences, ie time between, between dates) in dataframes change once they are printed using kable.

Reproducible ( I hope :) ) example:
```{r}
x <- chron(dates = c("02/27/92", "02/27/92", "01/14/92", "02/28/92"))
y <- x + c(1,2,3,4)
df <- data.frame(x=x, y=y)
df$diff <- y - x
df
knitr::kable(df)
```

will give

df
         x        y            diff
1 02/27/92 02/28/92    1
2 02/27/92 02/29/92    2
3 01/14/92 01/17/92    3
4 02/28/92 03/03/92    4

kable(df)

|        x|        y| diff|
|--------:|--------:|----:|
| 02/27/92| 02/27/92|    0|
| 02/27/92| 02/27/92|    0|
| 01/16/92| 01/16/92|    0|
| 02/27/92| 03/05/92|    7|

**Comment by aniruhil** [comment]
I don't see this if I execute the following:

`x <- as.Date(c("1992-02-27", "1992-02-27", "1992-01-14", "1992-02-28"))`
`y <- x + c(1,2,3,4)`
`df <- data.frame(x=x, y=y)` 
`df$diff <- y - x`
`df`
`knitr::kable(df)`

which yields:

> df
           x          y   diff
1 1992-02-27 1992-02-28 1 days
2 1992-02-27 1992-02-29 2 days
3 1992-01-14 1992-01-17 3 days
4 1992-02-28 1992-03-03 4 days
> knitr::kable(df)


|x          |y          |diff   |
|:----------|:----------|:------|
|1992-02-27 |1992-02-28 |1 days |
|1992-02-27 |1992-02-29 |2 days |
|1992-01-14 |1992-01-17 |3 days |
|1992-02-28 |1992-03-03 |4 days |

**Comment by aniruhil** [comment]
What about using 

`df$diff = difftime(y, x, units = "days")`
> df
         x        y   diff
1 02/27/92 02/28/92 1 days
2 02/27/92 02/29/92 2 days
3 01/14/92 01/17/92 3 days
4 02/28/92 03/03/92 4 days

`knitr::kable(df)`
> knitr::kable(df)


|        x|        y|diff   |
|--------:|--------:|:------|
| 02/27/92| 02/27/92|1 days |
| 02/27/92| 02/27/92|2 days |
| 01/16/92| 01/16/92|3 days |
| 02/27/92| 03/05/92|4 days |

**Comment by liesb** [comment]
Thank you! I don't really need the workaround at the moment, but I thought I'd report the original issue.

**Comment by yihui** [comment]
Yes, that is a similar issue as #806. I just fixed it. Thanks!
