### ISSUE TITLE
Font sizes with non-R engines are not respected for output

### ISSUE THREAD

**Issue by cysouw** [yihui/knitr#1119]
When using non-R engines (I'm using bash and python) the Latex output does not respond to the option "size".

Minimal example: try knitting the following, and in the bash example there will be tags \normalfont and \normalsize that seem to be superfluous (or should occur after the \verbatim block)

best
michael

```
<<setup, include=FALSE, cache=FALSE>>=
opts_chunk$set(size="scriptsize")
@
<<bash-test, engine='bash'>>=
echo 'this is a simple bash example'
@
<<R-test>>=
'this is a simple R example'
@
```

**Comment by cysouw** [comment]
I have been looking some more into the non-R engine chunks, and I would like to propose to clean up those chunks some more, and bring them in the same format as the R-engine chunks. Then the output is much more consistent (BTW: I'm talking about the latex code produced, I have not looked at the other outputs).

basically:
- remove \noindent \ttfamily and replace with \begin{alltt}
- remove \hspace*{\fill}\\  at the end of lines
- remove \mbox{} \normalfont \normalsize and replace with \end{alltt}

example:

# ======== KNITR INPUT ========

<<bash-test, engine='bash', size = 'tiny'>>=
echo 'this is a simple bash example'
ls | wc
@

# ======= LATEX OUTPUT NOW ======

\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.933, 0.933, 0.933}\color{fgcolor}\begin{kframe}
\noindent
\ttfamily
\hlstd{}\hlkwb{echo\ }\hlstd{}\hlstr{'this\ is\ a\ simple\ bash\ example'}\hlstd{}\hspace*{\fill}\\
\hlkwc{ls\ }\hlstd{\textbar \ }\hlkwc{wc}\hlstd{}\hspace*{\fill}
\mbox{}
\normalfont
\normalsize

\begin{verbatim}
## this is a simple bash example
##        5       5      72
\end{verbatim}
\end{kframe}
\end{knitrout}


# ========== POSSIBLE SIMPLIFICATION IN LINE WITH R ==========

\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.933, 0.933, 0.933}\color{fgcolor}\begin{kframe}

\begin{alltt}
\hlstd{}\hlkwb{echo\ }\hlstd{}\hlstr{'this\ is\ a\ simple\ bash\ example'}\hlstd{}
\hlkwc{ls\ }\hlstd{\textbar \ }\hlkwc{wc}\hlstd{}
\end{alltt}

\begin{verbatim}
## this is a simple bash example
##        5       5      72
\end{verbatim}
\end{kframe}
\end{knitrout}

**Comment by cysouw** [comment]
I found the culprit: it is not the knitr code (I couldn't find anything wrong), it turns out to the "Highlight" code from www.andre-simon.de. I have no idea what goes wrong, but when I uninstall it, the latex output of knitr looks good (although of course the colouring is missing).

Try this:

`echo "test" | highlight --syntax bash --out-format=latex --fragment`

Result:

```
\noindent
\ttfamily
\hlstd{}\hlkwb{test}\hlstd{}\hspace*{\fill}\\
\mbox{}
\normalfont
\normalsize
```

**Comment by yihui** [comment]
Should be fixed now. Thanks!
