### ISSUE TITLE
Adding Greek symbols to fig.cap doesn't include them in the caption label

### ISSUE THREAD

**Issue by NattyE** [yihui/knitr#1120]
## Problem:
It seems that when using greek symbols in `fig.cap`, knitr will add them to the actual caption but it won't add them to the caption label and they therefore do not get properly referenced in `\listoffigures`.
## .Rnw file:
    \documentclass{article}
    
    \begin{document}
    
    \listoffigures
    
    <<plot1, echo = TRUE, fig.cap = "Issue when using $\\beta$ in a caption">>=
    tmp <- rnorm(100)
    plot(tmp)
    @
    
    <<plot2, echo = TRUE, fig.cap = "a nice caption">>=
    tmp2 <- rnorm(50)
    plot(tmp2)
    @
    
    \end{document}
## .tex file caption output:
The first figure caption looks like this:

    \caption[Issue when using ]{Issue when using $\beta$ in a caption}

The second figure caption is of course ok:

    \caption[a nice caption]{a nice caption}

**Comment by yihui** [comment]
That is due to the automatic generation of short captions (i.e. the captions in `[]` after `\caption`). You can disable it by `fig.scap = NA`.

**Comment by NattyE** [comment]
Sorry dude. Yesterday was a very, very long day and I completely forgot about this option. Thanks a million.

**Comment by yihui** [comment]
No worries :)
