### ISSUE TITLE
latex output should not re-define shadecolor within each \begin{knitrout} block

### ISSUE THREAD

**Issue by friendly** [yihui/knitr#1122]
I'm trying to tweak a knitr theme ("seashell") for the knitr output for a book done with Rnw/latex.  I can do this for all the highlighting color elements used in a chunk output block, e.g., by including lines like
the following in my preamble

    \usepackage{xcolor}
      \renewcommand{\hlkwc}[1]{\textcolor{teal!70!black}{#1}}%               function args
      \renewcommand{\hlkwd}[1]{\textcolor{blue}{\textbf{#1}}}%                function calls
     ...

knitr automatically produces the following color definitions in the preamble

    \definecolor{shadecolor}{rgb}{.97, .97, .97}
    \definecolor{messagecolor}{rgb}{0, 0, 0}
    \definecolor{warningcolor}{rgb}{1, 0, 1}
    \definecolor{errorcolor}{rgb}{1, 0, 0}

However, in *every* `\begin{knitrout} ... \end{knitrout}` block, `shadecolor` is redefined, which makes it impossible to change the background color globally.

**Comment by yihui** [comment]
That makes sense. I'll fix it.

**Comment by yihui** [comment]
Now you can set the chunk option `background = NA` to prevent knitr from redefining `shadecolor` for every single code chunk.

**Comment by friendly** [comment]
Thanks for this, Yihui.  From this, I realized that I could override the background for a theme directly in R rather than in LaTeX, e.g., via

       opts_chunk$set(background = rgb(0.97,0.97,0.97))

However, that requires working in RBG, whereas in LaTeX (with the xcolor package) it is much easier to think in terms of named colors or color blends.

**Comment by EugChem** [comment]
Good evening!
I have a same problem with the color: knitr automatically produces the following color definition in the preamble: 
`\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}`
A table, what I did, had an grey color. How I can do the black table?

> <<Central, echo=FALSE, background = NA, color = 'black'>>=
> MeanTable <- round(data.frame("Н" = mean(ResTable[,1]), "кг" = mean(ResTable[,2]), "кг/см^2" = mean(ResTable[,3]), "кг/мм" = mean(ResTable[,4]), stringsAsFactors=FALSE), digits = 1)
> MedianTable <- round(data.frame("Н" = median(ResTable[,1]), "кг" = median(ResTable[,2]), "кг/см^2" = median(ResTable[,3]), "кг/мм" = median(ResTable[,4]), stringsAsFactors=FALSE), digits = 1)
> CentralTab <- rbind(MeanTable, MedianTable)
> colnames(CentralTab) <- c("Н", "кг", "кг/см^2", "кг/мм")
> row.names(CentralTab) <- c("Среднее (Mean)", "Медиана (Median)")
> kable(CentralTab, "latex", booktabs = TRUE)

Thanks in advance

**Comment by yihui** [comment]
@EugChem I think you can add the chunk option `results='asis'`.

**Comment by friendly** [comment]
To supplement what Yihui said, this thread had to do with defining/overriding the background colors for **all** chunks.  I don't think that `background` and `color` are defined as chunk options, but you might be able to define chunk hooks to implement them.

**Comment by EugChem** [comment]
@yihui , thank you very much. `results='asis'` works well. 
@friendly , Where I can define that option besides chunks? How I can use and where I can whrite `opts_chunk$set(results='asis')`?

**Comment by mhofert** [comment]
`results='asis'` has a side effect for me. I know simply put `\definecolor{fgcolor}{rgb}{0,0,0}` in the preamble (of the `.Rnw`) to get black text. Would be nice to have an option via `opts_chunk$set` as one can set the `background` color there.
