### ISSUE TITLE
fig.env = "marginfigure" produces normal figure environment in tufte_handout

### ISSUE THREAD

**Issue by TomHarrop** [yihui/knitr#1125]
I'm trying to render an `Rmd` document to tufte_handout using the Knit button in `Rstudio 0.99.486`, but I can't get `marginfigure` to work. My document is called `test.Rmd`:

	---
	output:
	  rmarkdown::tufte_handout:
	    keep_tex: TRUE
	---

	```{r plot, fig.cap = "My caption", fig.env = "marginfigure"}
	library(ggplot2)
	qplot(rnorm(10), rnorm(10))
	```

	```{r sinf, echo = FALSE, results = 'hide'}
	writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
	```

When I knit, I get a figure in the normal `figure` environment in the `test.pdf`. In `test.tex`, I see:

```latex
\begin{figure}
 \includegraphics{test_files/figure-latex/plot-1.pdf}
\caption{My caption}
\end{figure}
```

My understanding from the `Plots` section of the `knitr` manual is that if I include `fig.cap` I should get a figure environment, and  `fig.env` allows me to specify what that environment should be. Have I misunderstood?

The contents of `sessionInfo.txt` follow.

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8   
 [6] LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1.9003

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8    
 [3] plyr_1.8.3       grid_3.2.2      
 [5] gtable_0.1.2     formatR_1.2.1   
 [7] magrittr_1.5     evaluate_0.8    
 [9] scales_0.3.0     stringi_1.0-1   
[11] rmarkdown_0.8.1  labeling_0.3    
[13] tools_3.2.2      stringr_1.0.0   
[15] munsell_0.4.2    yaml_2.1.13     
[17] colorspace_1.2-6 htmltools_0.2.6 
[19] knitr_1.11      
```

**Comment by yihui** [comment]
`rmarkdown::tufte_handout` is different; it has its own special chunk options. Please read the documentation http://rmarkdown.rstudio.com/tufte_handout_format.html and in particular, its own example: https://raw.githubusercontent.com/rstudio/rmarkdown/master/inst/rmarkdown/templates/tufte_handout/skeleton/skeleton.Rmd

That said, you can probably use

    ```{r fig.env='marginfigure', fig.cap='Your figure caption.', out.extra=''}

to trigger the LaTeX mode in knitr.

**Comment by TomHarrop** [comment]
Thanks! This is fixed with:

    ```{r plot, fig.margin = TRUE}
    library(ggplot2)
    qplot(rnorm(10), rnorm(10))
    ```

Thanks to your comment I found the `fig.margin = TRUE` option  in the [Tufte Handout Example](http://rmarkdown.rstudio.com/examples/tufte-handout.pdf) which works great for this. However, adding `out.extra=''` didn't seem to change anything in the `.tex` or `.pdf`, so I'm not sure about other uses e.g. if you wanted `sideways` or something.

**Comment by yihui** [comment]
Thanks for bringing this issue to my attention. I have not really thought about it carefully. I just realized the chunk options `fig.margin` and `fig.fullwidth` are unnecessary inventions. `rmarkdown::tufte_handout()` modified knitr's plot hook internally, and you can restore it by a code chunk like this in the beginning of your document:

    ```{r setup, include=FALSE}
    knitr::knit_hooks$set(plot = knitr::hook_plot_tex)
    ```

Then you will be able to do things like

    ```{r, fig.env = 'marginfigure', fig.cap = "Sepal length vs. petal length, colored by species", out.extra=''}
    library(ggplot2)
    qplot(Sepal.Length, Petal.Length, data = iris, color = Species)
    ```

    ```{r, fig.width = 10, fig.height = 2, fig.env = 'figure*', fig.cap = "Full width figure", out.extra=''}
    qplot(wt, mpg, data=mtcars, colour=factor(cyl))
    ```

**Comment by TomHarrop** [comment]
Nice, this works too (it's working for me without `out.extra`, by the way). Using this and the `floating.environment` argument to `xtable` we can choose the LaTeX environment for figures and tables as we wish, which is perfect.

I will leave this issue open in case you need it but from my point of view it's fixed. Thanks again!

**Comment by yihui** [comment]
The `tufte_handout()` format will be moved to a separate package named **tufte** in the future: https://github.com/rstudio/tufte I have improved this format in that package, and there are a lot more chunk options that you may use (such as `out.width`).

**Comment by TomHarrop** [comment]
The new HTML example at https://rstudio.github.io/tufte/ looks amazing. Thank you.

**Comment by yihui** [comment]
No problem. Glad you like it :)
