### ISSUE TITLE
行内代码不使用科学计数法

### ISSUE THREAD

**Issue by lixinyao** [yihui/knitr#1127]
1. 用rticles里面的ctex模板输出PDF文档，发生错误，应该是文档中出现了latex无法直接编译的字符
2. 换用html的方式输出，原来`mydata[nrow(mydata),1]`值为14954，采用`r mydata[nrow(mydata),1]`输出的值却是`1.495410^{4}`，这个应该就是latex无法编译的值
3. 应该怎么调整呢？谢谢啦

**Comment by yihui** [comment]
凡是行内代码有数字输出时，外面都加上美元符号，例如 `` $`r 1.23*10^8`$ ``
