### ISSUE TITLE
Write_bib package version field beamer

### ISSUE THREAD

**Issue by jsta** [yihui/knitr#1128]
The default `citation ()` command prints package version information to the _notes_ field. Beamer documents do not print the notes field. Add option for `write_bib()` to print version information to the _version_ field?

See: http://stackoverflow.com/questions/31501388/how-do-i-get-r-package-versions-to-print-in-an-r-markdown-beamer-bibliography

**Comment by yihui** [comment]
I believe it is up to your bibliography package and style how to display the bib entries. For example, the natbib package and the plainnat style work fine for me in beamer.

```latex
\usepackage{natbib}
\bibliographystyle{plainnat}
```

![image](https://cloud.githubusercontent.com/assets/163582/11047901/6bfae9c4-86fa-11e5-8a51-97ab2e2a3062.png)

**Comment by jsta** [comment]
I tried adding the call to natbib and and plainnat in my beamer header but I am still not getting package version printing. My current solution is to append the package version to the title field.

**Comment by yihui** [comment]
In that case, I need a minimal reproducible self-contained example as the contributing guide stated.
