### ISSUE TITLE
can knitr support svglite?

### ISSUE THREAD

**Issue by tierneyn** [yihui/knitr#1129]
Hi there, just requesting for knitr to support svglite, as per the discussion on SO [here](http://stackoverflow.com/questions/33684514/knitr-jekyll-servrjekyll-images-are-enormous-or-not-good-resolution/33686011#33686011).

**Comment by yihui** [comment]
Done. You can just use `dev = 'svglite'`.

**Comment by tierneyn** [comment]
Wonderful! Thank you so much for being awesome.
