### ISSUE TITLE
knitr base.dir

### ISSUE THREAD

**Issue by kecal** [yihui/knitr#1131]
I am using the **opts_knit$set(base.dir = baseDir)** inside of Rserve in Java. The Rserve session home directory looks something like **/tmp/Rserv/conn2362**. But the opts_knit$set has no effect and knitr complains in html like
`## Error in plot.new(): could not open file '/tmp/RtmpjyULEI/file93ab1d83c4'`
This directory and file does not exist.

Unfortunately I am the Java programmer and might be doing something stupid in R...

**Comment by yihui** [comment]
I strongly recommend you not to touch this option if you do not know what it really means. In most cases you do not need to set it, and I don't know why you have to. There is too little information in your description for me to figure out what the problem is. Sorry.

**Comment by kecal** [comment]
I stand corrected. The problem was that I had somehow multiple Rserve sessions left opened. Nothing to do with knitr.

**Comment by yihui** [comment]
Okay, thanks for letting me know.
