### ISSUE TITLE
Can kable read format data from rmarkdown metadata?

### ISSUE THREAD

**Issue by haozhu233** [yihui/knitr#1132]
Hello, Yihui, do you think if it might be a useful feature for `kable` to obtain format info from `rmarkdown` metadata (https://github.com/rstudio/rmarkdown/commit/61887a8cd9bd53258b3fd35c9df0f14f851e6ca3 )when the global option `knitr.table.format` is not available, at least for those common and official rmarkdown formats? 

I'm debating as well because it kind of goes against the idea of letting pandoc deal with all the formatting things if user doesn't specify. However, if we do get some formatted table outputs from `kable`, it will be easier for people to customize the results (like this [one](https://github.com/haozhu233/kableExtra) I'm currently working on).

```r
#' Rmarkdown Format
#' @importFrom rmarkdown metadata
#' @export

rmd_format <- function(){
  rmd_output_metadata <- metadata$output
  rmd_fmt <- ifelse(
    is.null(rmd_output_metadata),
    "markdown", ifelse(
    rmd_output_metadata %in% c("html_document", "rmarkdown::html_vignette"),
    "html",ifelse(
      rmd_output_metadata %in% c("pdf_document", "rmarkdown::tufte_handout"),
      "latex", "pandoc"
    )))
  return(rmd_fmt)
}
```

**Comment by yihui** [comment]
I'm not sure if that is a good idea. I think the `pandoc` format should work reasonably well, and I don't quite see the point of using `html` or `latex`. That said, I have added a change that allows you to set `options(knitr.table.format = rmd_format)`.

**Comment by haozhu233** [comment]
Hello, Yihui, thanks for your reply and solution. That is very helpful. 

Also, if you have some extra time, you may want to review this [kableExtra](https://github.com/haozhu233/kableExtra) package and you will know why I asked this question. It's still in a very early stage and I only finished the add_footnote function. If you like the concept, I'm actually more than willing to see if this package can be integrated into `knitr`.

**Comment by yihui** [comment]
The package looks interesting. It will be more convenient for me to learn it if you can show some examples on an HTML page, e.g. publish it to rpubs.com Thanks!

**Comment by haozhu233** [comment]
Here they are. :)

HTML demo: http://rpubs.com/haozhu233/kableExtra_footnote_html
PDF demo: https://www.dropbox.com/s/qk7msi64mndn67y/brief_demo_pdf.pdf?dl=0

**Comment by yihui** [comment]
I see. Usually I tend to say no when users want more features in `kable()`, since I want to keep this function simple. I know there are a lot of things you can do with tables, but personally I'm not very interested in tables. That said, you are very welcome to extend it in a separate package, and I'm happy to help when you need me to change anything in `kable()` to support your new features. Thanks and good luck!

**Comment by haozhu233** [comment]
Thank you, Yihui, for checking on that and thanks for your wishes! Keeping `kable` simple is important and that's why everyone loves it. :)

My goal is that people can keep using `kable` in this kind of simple and easy way. When they need some medium-advanced features, they don't need to turn away to other packages using different syntax. I will see what I can do with that package.
