### ISSUE TITLE
winows metafile on Linux

### ISSUE THREAD

**Issue by nickytong** [yihui/knitr#1135]
Hi Yihui,
This is related to the dev option. On windows system, we can use dev='win.metafile'. However, this would not work on Linux system.
Currently there is devEMF package that can produce windows metafile even on Linux system. It works with both base graphics and grid graphics (e.g. ggplot2 figures). Could you add this as part of the dev option, e.g. through dev='devEMF'?

An example of using devEMF is following:
library(devEMF)
emf(file="Figure.emf", bg="white", width=10, height=10, family="Calibri", pointsize=18)
plot(rnorm(100))
dev.off()

Please let me know if you need further clarification.

Regards,

Pan

**Comment by yihui** [comment]
I think you can just set the chunk options `dev = 'emf', fig.ext = 'emf'` after you `library(devEMF)`.

**Comment by nickytong** [comment]
Yes. this works! Thanks a bunch.
