### ISSUE TITLE
asis_output does not work in loop

### ISSUE THREAD

**Issue by renkun-ken** [yihui/knitr#1137]
In a normal Rmd document, the following code works:

```r
asis_output("## hello\n")  
```

but this does not work:

```r
for (i in 1:3) {
  asis_output("## hello\n\n")  
}
```

When I try to create a group of `knit_print`able objects in a for-loop, it can be very unnatural to print every object. Is it possible to make it easier to do so?

**Comment by yihui** [comment]
Unfortunately no, it is not possible. `asis_output()` only works in top-level R expressions. To create as-is output from a loop, you have to either use the chunk option `results = 'asis'` (but this option applies to all output in this code chunk, i.e. you cannot have both as-is output and verbatim output in the same chunk), or collect the character results in a loop, and write them out using `asis_output()` _after_ the loop.

**Comment by renkun-ken** [comment]
Thanks for the explanation!

**Comment by 1beb** [comment]
knit_expand is also a good solution to this type of expansion problem. You can use a template and cycle your code through over and over.
