### ISSUE TITLE
knit(.Rnw) -> .tex does not use consistent line breaks

### ISSUE THREAD

**Issue by friendly** [yihui/knitr#1138]
Knitting a `.Rnw` file to `.tex` often fails to insert `\n` where they would normally occur in a LaTeX file,
starting in the header lines produced, that often look like this:

    \documentclass{article}
    \usepackage[]{graphicx}\usepackage[]{color}

It is especially bad for the `.tex` rendering of code chunks with figures, like this, where `\begin{kframe}` and `\begin{figure}` are appended to the current line with no `\n`.

    \begin{knitrout}
    \definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{alltt}
    \hlcom{# fit a simple tree, using only pclass and age}
    \hlkwd{library}\hlstd{(rpart)}
    \hlkwd{library}\hlstd{(rpart.plot)}
    \hlkwd{data}\hlstd{(Titanicp,} \hlkwc{package}\hlstd{=}\hlstr{"vcdExtra"}\hlstd{)}
    \hlstd{rp0} \hlkwb{<-} \hlkwd{rpart}\hlstd{(survived} \hlopt{~} \hlstd{pclass} \hlopt{+} \hlstd{age,} \hlkwc{data}\hlstd{=Titanicp)}
    \hlkwd{rpart.plot}\hlstd{(rp0,} \hlkwc{type}\hlstd{=}\hlnum{0}\hlstd{,} \hlkwc{extra}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{cex}\hlstd{=}\hlnum{1.5}\hlstd{)}
    \end{alltt}
    \end{kframe}\begin{figure}[hbt!]

    {\centering \includegraphics[width=0.55\linewidth]{figure/rp0-1} 

    }

This may seem a small issue, and the LaTeX output is certainly legal, but it creates problems if I need or want to do some analysis of the resulting `.tex` file.

For example, I have a Perl tool, `texdepend`, https://www.ctan.org/pkg/texdepend,  designed to find all dependencies in a latex file to help create a `Makefile`, or create a FIGLIST for journal submission.  The lack of newlines confuses it.  

I have also tried to use `grep` on a book .tex file to tally figure placements, but lack of newlines
makes this harder.

**Comment by yihui** [comment]
Sorry I don't want to change this since they have been there almost since day one. The best I could do is to tell you there is a hook function that you can set up to post-process the full tex output:

```r
library(knitr)
knit_hooks$set(document = function(x) {
  # x is the character vector of the tex output, e.g. you can
  x = knitr:::split_lines(x)
  # replace \begin{ with \n\begin{
  # ...
  paste(x, collapse = '\n')
})
```

**Comment by friendly** [comment]
That's useful to know, but in my case book.tex is ~ 1.6Mb.
Thanks for considering it for the future.
