### ISSUE TITLE
add a reference to pander (and other useful packages?) in the readme

### ISSUE THREAD

**Issue by jcolomb** [yihui/knitr#1139]
Dear Yihui,

I have been striking a lot to use knitr with my tables for months, but I got into the pander package today: all my problems are gone.
You may think about getting a list of such tools, which are making knitr even better/easier!

Thank you for your work.

**Comment by yihui** [comment]
It is in the **See Also** section on the help page `?kable`. Personally I'm not very interested in complicated tables, although I know many people are interested in them. Thanks for the suggestions!
