### ISSUE TITLE
I updated R and now Lyx documents no longer recognizing embedded R Code

### ISSUE THREAD

**Issue by thedavidsons01** [yihui/knitr#1143]
Wondering if anyone can help.  I updated R to 3.2.3 (wooden Christmas-Tree) this evening and now the code inside of my LyX documents are no longer compiling.  I went in and manually changed the path in Lyx to the following location:  C:\Program Files\R\R-3.2.3\bin\x64, however when the output PDF file is not compiling the R results.  The code chunk I am using as a test is:

\begin{description}
\item [{<<>>=
1 + 1
@}]~

\end{description}

The output I am getting after viewing it as a PDF is the following:

!!??= 1+1@
Note that the exclamation and question marks are printed upside down in the actual PDF document.

Prior to updating R, everything was working fine.

Any help is appreciated.

**Comment by yihui** [comment]
That is not valid Rnw syntax. `<<>>=` must start in the beginning of a line, and you had `\item [{` before `<<>>=`.
