### ISSUE TITLE
Knitr PDF shifts a plot to the right

### ISSUE THREAD

**Issue by ElenaSophiaDesign** [yihui/knitr#1144]
A knitr PDF shifted a plot all the way to the right, outside of the page - I could see only the leftmost sliver of it.  I found what's causing it; looks like a bug:

I had some text before the code chunks.  The text began with #### , the markdown way to create a title (large bold font).  Then there was a chunk with some code, and immediately after it a separate chunk just calling the plot.  So, these #### (four # signs) two chinks above caused the plot to shift to the right.  What is interesting, ### (three # signs) do not cause any troubles.

Also, this shift happened only with knitr PDF.  Neither knitr HTML nor knitr Word had this problem. 

For what it's worth...

**Comment by yihui** [comment]
Please read the contributing guide before opening an issue: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by ElenaSophiaDesign** [comment]
Here's the Rmd file and PDF file it produces.  Hope this helps.  Please let
me know if there is anything else I can do.

Regards,

Elena Karzhitsky

**Comment by yihui** [comment]
Github issues do not allow email attachments. Please email it to me: https://github.com/yihui/knitr/blob/master/DESCRIPTION#L77 Thanks!

**Comment by ElenaSophiaDesign** [comment]
Actually I've just realized that in the last example the text shifted
 too: now it's printed between the code chunk and the plot.

**Comment by ElenaSophiaDesign** [comment]
This looks like GitHub file.  I am not sure I understand what you want me
to do.

**Comment by yihui** [comment]
I was pointing you to my email address.

**Comment by ElenaSophiaDesign** [comment]
Hope this will work

**Comment by ElenaSophiaDesign** [comment]
Yihui,

Please let me know if you received the attachments.

Thank you,

Elena

**Comment by yihui** [comment]
Yes, I did. With the latest version of knitr (1.12) and rmarkdown (0.9.2) from CRAN, you will need to add at least one more blank line before `####`.

**Comment by ElenaSophiaDesign** [comment]
I am not particular about using four or more "#" symbols in Knit PDF - just
found this behavior really peculiar.

Have a great one !

**Comment by yihui** [comment]
Thanks for the report!
