### ISSUE TITLE
include_graphics should use max-width css

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1145]
Could

    ```{r, out.width = "100%"}
    knitr::include_graphics("diagrams/transform-joins.png")
    ```

generate an image with `style="max-width: 100%"`? This shrinks the image if you narrow the browser, making the output more "responsive".

**Comment by yihui** [comment]
Do you only need this for images in certain code chunks? I mean usually I'd just define `img { max-width: 100%; }` in a separate CSS file and it affects all images. I'm not sure it is common enough to set max-width for individual images.

**Comment by hadley** [comment]
Yeah, because it needs to respect `out.width` so you can have (e.g.) two images in a column.

**Comment by yihui** [comment]
With the new `opts_hooks`, you can implement this easily by yourself using the `out.extra` option:

```r
knitr::opts_hooks$set(out.maxwidth = function(options) {
  if (!knitr:::is_html_output()) return(options)
  options$out.extra <- sprintf('style="max-width: %s;"', options$out.maxwidth)
  options
})
```

Then

    ```{r out.maxwidth='100%'}
    ```
