### ISSUE TITLE
Output Devices and Output Document Type

### ISSUE THREAD

**Issue by DarioS** [yihui/knitr#1147]
The following chunk doesn't show a plot if the output document is HTML

    ```{r dev = "pdf"}
    plot(cars)
    ```

The knitr website mentions it supports over 20 output devices. Perhaps a matrix of devices and output formats with ticks in the matrix for a particular device being supported by a particular output format would be helpful.

**Comment by yihui** [comment]
For HTML output, the device is automatically set to PNG. For LaTeX, the default device is PDF. I don't see why you need to set `dev = "pdf"` for HTML output. You either do not set it, or understand the consequence of setting it to a non-default device. I'm not sure what more I could do on my side. It is kind of obvious that PDF figures won't work in most web browsers (you probably have never seen PDF images displayed in web browsers). They may eventually work some day, but at least not now.
