### ISSUE TITLE
knitr failing with tikzDevice and sanitize=TRUE

### ISSUE THREAD

**Issue by O-T** [yihui/knitr#1149]
Hi,

the following MWE fails for me, running on Arch Linux, tikzDevice 0.9 and knitr 1.12

test.Rnw:
```
\documentclass[12pt]{article}
\begin{document}
<<testfig, dev='tikz', echo=FALSE, sanitize=FALSE>>=
require(ggplot2)
ggplot(cars) + geom_histogram(aes(speed), binwidth=1) + labs(title=("5%"))
@
\end{document}
``` 

Running `knit("test.Rnw")` produces the .tex file attached here as a .txt - apparently, the metrics calculation fails, and the whole error log is inserted into the .tex, which results in an uncompilable file. However, this does not appear to be an issue with tikzDevice's metrics calculations itself, because I can render the same figure just fine using the `tikz()` function and `sanitize=TRUE`.

[test.txt](https://github.com/yihui/knitr/files/89810/test.txt)

**Comment by yihui** [comment]
Thanks for the report! I think this bug was introduced by the PR #1073. I just fixed it.
