### ISSUE TITLE
diagnosing cache triggering?

### ISSUE THREAD

**Issue by bbolker** [yihui/knitr#1151]
I'm using `rmarkdown::render()` to build HTML files and finding that rebuilding the caches is being triggered more often than I would have expected.  I understand that any change that affects the MD5 hash (comments, whitespace, etc.) will trigger rebuilding, as well as any change to the chunk options, but I don't *think* those things are changing. I'm wondering whether there is some other condition I've missed (also, not your problem, but maybe there's something special about `rmarkdown::render`?  I looked at the code and don't see anything cache-specific other than setting the cache directory ...)

Sorry I haven't yet been able to replicate this clearly/reproducibly enough to provide a MWE.

The chunks take long enough to run and the document is complex enough that perhaps I should just suck it up and build a Makefile, but I'm stubborn.  Any ideas, or suggested directions for diagnosis?

**Comment by yihui** [comment]
I guess the only way to diagnose this issue is to inspect the code here: https://github.com/yihui/knitr/blob/master/R/block.R#L61-L75 You may save the `content` object somewhere between two runs, and figure out what changed in this object.

**Comment by bbolker** [comment]
thanks!  I will go ahead and close this, since it's really not your problem. (Do let me know if you'd prefer that questions like this go elsewhere, e.g. some knitr forum/mailing list ...)

**Comment by bbolker** [comment]
by the way, is `fix.ext` a typo for `fig.ext` here ... ? https://github.com/yihui/knitr/blob/master/R/block.R#L96

**Comment by yihui** [comment]
Nice catch. It is indeed a typo. I'll fix it. Thanks!
