### ISSUE TITLE
Pandoc memory issue on Windows when running Knit HTML in RStudio

### ISSUE THREAD

**Issue by bdelaney** [yihui/knitr#1152]
I'm running the latest version of RStudio on Windows 10. Knitr is 1.12 and Data.Table is 1.96
I added a single line of data.table code to my Rmd file at the end. Looks like this:
`datatable[variable=="M", variable:=variable*1000]`
Pretty basic, just multiplying some values in the column 'variable' by 1000. This in-place syntax is very low resource and when run in the console it takes almost zero memory. The row selector may only bring between 5 and 50 observations and the row is only 5 cols wide.  
But as soon as I add this innocent piece of code, Knitr goes crazy and pandoc.exe explodes after spinning its wheels for an additional minute beyond what the file used to compile in. This error is displayed:
`pandoc.exe: out of memory
Error: pandoc document conversion failed with error 1`
I believe pandoc is stopping when it reaches about 2gb of memory. I used the developer commandline to set the limit up to 4gb. http://jonathanchang.org/coding/fixing-pandoc-out-of-memory-errors-on-windows and it made no difference. But if I comment out that one line, knitr works fine again.  
This included bit of R code is so inconsequential and prior to that one line being added knitr would finish compiling in about 5 seconds (and that is with a large data file loading).
I do show additional warning messages in the RStudio Markdown output window that displays as Knitr HTML is running on the Rmd file. But they do not seem to be relevant.  
When I can get to a Mac, I may try and run my Rmd file through Knitr HTML in RStudio there.

**Comment by yihui** [comment]
Could you provide a minimal self-contained example plus the following info?

```r
RStudio.Version()
library(knitr)
library(rmarkdown)
sessionInfo()
```

**Comment by bdelaney** [comment]
I can put the whole project on GitHub if you like. Oh, the data file is big though.
You are right, I should attempt to make a very small reproducible example.
BTW, I took the whole project over to a Mac. Got a brand new install of RStudio, R, Knitr, and all the rest. Ran it with lines commented out, ran fine and produce html doc. Uncommented the one offending line and also crashed the Mac version of the build. I'm actually glad to see that.  
I'll do my best to reproduce tonight with an example.

**Comment by yihui** [comment]
You may generate some random data with a script without really using the big data file (I only need the sript).

**Comment by bdelaney** [comment]
yes, I understand. I'll be busy the rest of the afternoon but I will get a good example done by later tonight.  
Meantime, I did substitute the dataframe way and that runs just fine in knitr. This is helpful to know and I will try and make it part of my example.

**Comment by yihui** [comment]
I'm planning a new release of knitr to CRAN, and I'd like to fix this issue if it turns out to be a bug of knitr, otherwise I'll just go ahead and investigate this issue after the release.

**Comment by bdelaney** [comment]
Sorry yihui, I really do want to try and reproduce, but do not want to hold you up. Please publish to CRAN and I will get back on this before end of the week. I appreciate all of the work on knitr. It is incredibly useful.

**Comment by yihui** [comment]
Okay, I was asking because package authors do not have many chances to update their packages on CRAN. Normally we have to wait for a while because CRAN is happy to take the next submission. I can always fix the issue here on Github, though.

No worries. Just take your time.

**Comment by bdelaney** [comment]
I gave it a good shot this evening but did not come up with a simple reproducible example. I'm really new to R so maybe I should just post my code to a gist here and let you look at it. There may be some glaring error in my Rmd file or something. I did take out the old code too and enable a single data.table column transform and it is still hanging the same way.
...
Eureka! I found it. I was using your printr in my Rmd file. As soon as I comment that out, knitr runs normally. Uncomment, and it leads to Pandoc running amok and eventually crashing as it consumes Gbs of memory.
Now I will look at making it reproducible. But I think this is it. Combination of data.table column transform and printr being called.

**Comment by bdelaney** [comment]
It's more complicated than I thought. But I definitely was able to complete the data.table operations once I removed printr library from Rmd. This may take a little time.

**Comment by yihui** [comment]
Yeah, tables in Markdown can consume a lot of memory, depending on the size of tables.

**Comment by bdelaney** [comment]
I removed all the extraneous markdown and code, then just ran two chunks in my Rmd file. One chunk loads libraries and the data file. The second chunk massages the data, including a line of offending data.table code. The end of that chunk is a ggplot. That is all. There is no call to printr.

With this stripped down code, I'm able to reproduce the following when running knitr on the Rmd. And I'm running it both in the main Rstudio instance, and using the Rstudio Knit HTML button which spins up a new process.
 * comment out printr and knitr runs to completion producing my html file
 * add chunk option results='hide' to my second block and knitr runs to completion again  

So, EITHER one of these two changes allows the knitr process to finish successfully in my stripped down code.
But I'm still unable to create a small reproducible example because it only seems to happen if I read in a very large (500mb) file. I will take a further look at this next Monday when I'm back to work.

**Comment by yihui** [comment]
That sounds like a similar issue as http://stackoverflow.com/questions/15267018/knitr-gets-tricked-by-data-table-assignment i.e. the data.table object is printed and renders huge output. You don't really need the 500mb file to verify this. Just use the first couple of rows and see if the object is printed when it is not supposed to be.

**Comment by yihui** [comment]
Please feel free to re-open this issue or email me with a reproducible example when you have got a chance. Thanks!
