### ISSUE TITLE
hide results in ggplot list

### ISSUE THREAD

**Issue by ajay-d** [yihui/knitr#1153]
In version 1.11, I used to be able to print out a list of ggplot plots, but hide the results output, but that functionality seems lost in 1.12.  At least for pdf and word documents, it seems to work fine with html:

    ```{r plots, results='hide', fig.keep='all'}
    library(ggplot2)
    
    gg <- list()
    gg[[1]] <- ggplot(data=mtcars, aes(x=hp, y=mpg, color= carb)) + geom_point()
    gg[[2]] <- ggplot(data=mtcars, aes(x=cyl, y=disp, color= am)) + geom_point()
    
    gg
    ```

**Comment by yihui** [comment]
Same issue as http://stackoverflow.com/q/34768660/559676 I'll release a patch version of knitr to CRAN this week. Sorry about that.
