### ISSUE TITLE
Default Figure Sizes Contradiction

### ISSUE THREAD

**Issue by DarioS** [yihui/knitr#1154]
At http://yihui.name/knitr/options/ the sizes are 7 wide and 7 high. But, with RStudio, I see 7 and 5 for HTML and 6 and 4.5 for PDF and Word, when I click the cog icon next to the Knit button. It means that the document looks different depending on if the Knit HTML button is clicked or the document is compiled using `knit("aReport.Rmd", "aReport.md")` then `markdownToHTML`.

**Comment by yihui** [comment]
That is the default in **knitr**. **rmarkdown** changed the defaults and documented them http://rmarkdown.rstudio.com
