### ISSUE TITLE
knit_rd could accept source packages

### ISSUE THREAD

**Issue by jangorecki** [yihui/knitr#1156]
the `pkg_1.0.0.tar.gz` files generally

**Comment by yihui** [comment]
I'm not very interested in that. You may submit a pull request if you want this feature. I guess you can install the package to a temp dir, build the documentation via `knit_rd()`, and remove the package.

**Comment by jangorecki** [comment]
I understand. When installing pkg it doesn't need to use `knit_rd` as there is `R CMD INSTALL --html` switch.
The use case where I could benefit from that feature is described in [this comment](https://github.com/r-hub/proposal/issues/6#issuecomment-174784972). It may be interesting to you as it allows to use knit or other renderers to render gl-pages (gh-pages like), no need for jekyll any more.
