### ISSUE TITLE
HTML dependencies are probably cacheable

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#1158]
Certainly not for `cache = TRUE`, but should work for `cache = 1` or `2`.

We should change this: https://github.com/ramnathv/htmlwidgets/blob/0606dc09/R/utils.R#L52-L55 (It came from https://github.com/ramnathv/htmlwidgets/pull/136) because the temp dir changes by different R sessions. To solve the problem, `htmlDependency()` should have an option to make it possible to copy exactly the files specified instead of the whole directory.

**Comment by krlmlr** [comment]
I haven't found a NEWS item for the change of the default value for the `cacheable` argument to `asis_output()`.

**Comment by yihui** [comment]
Did you run into a trouble because of the change?

**Comment by yihui** [comment]
@krlmlr Just got an email from Uwe Ligges and I guess I know what the problem is now. I don't know why you need to test the class `knit_asis` and `knit_cacheable` attribute of `asis_output()` in **tibble**. `asis_output()` is the public API, and the class name and the attribute name `knit_cacheable` can be arbitrary. These are internal implementation details, and I don't expect anyone to treat them as fixed. If you do not use them directly in your package, I'd suggest you not test them.
