### ISSUE TITLE
Figure caption rendered as HTML in Markdown, not as image link text

### ISSUE THREAD

**Issue by psychemedia** [yihui/knitr#1160]
I am using RStudio/Rmd to generate Markdown for use with the Leanpub publishing system and after updating my R setup I have encountered a breaking change in the generation of Markdown, specifically:

    ---
    output:
      html_document:
        keep_md: yes
    ---
    ```{r myimg, fig.cap="My caption"}
    library(ggplot2)
    qplot(Sepal.Length, Petal.Length, data = iris, color = Species)
    ```
that used to render something of the form:

    ![My caption](myimg.png)

now gets rendered in the markdown as:

    <div class="figure">
    <img src="myimg.png" alt="My caption"  />
    <p class="caption">My caption</p>
    </div>

How do I get the original, vanilla markdown formatting back?

**Comment by psychemedia** [comment]
Thinking about this a bit more, the current HTML output has both alt text and a caption, which suggests that maybe there should be fig.alt as well as fig.cap.

Just providing fig.alt could by default render to ![]() format?

Or is there are need to have something to force md output? fig.type== md | html ?

**Comment by yihui** [comment]
Thanks for the report! Should be fixed now. Just FYI, I have been working on a much better tool than Leanpub. It appears you are writing a book, and I think you will like it when it is released.

**Comment by psychemedia** [comment]
@yihui I think I spotted it - [bookdown](http://rstudio.github.io/bookdown/)? Looks interesting - though Leanpub has the advantage of managing host, different format generation, and billing...

Thanks for the fix, btw - though I notice that there is still an  output, which clutters the md?

**Comment by yihui** [comment]
Yes, it is bookdown.

For the HTML comment, there are two ways to get rid of it: either use `fig_caption: yes` for `html_document`, or set the output format to be `md_document`.

**Comment by psychemedia** [comment]
This problem seems to have returned?  (I'm using knitr 1.1.23)

With settings:

    output:
      html_document:
         keep_md: yes

I would not expect to see _div_s wrapping images... I just want my md format back!
