### ISSUE TITLE
Rendering Fenced Code Blocks as ~~~ when Rmarkdown -> Markdown

### ISSUE THREAD

**Issue by tinyheero** [yihui/knitr#1161]
I was wondering if there was a way for the rendering of rmarkdown to markdown files to produce fenced code blocks that use ~~~ instead of ````?

The reason I ask is because for some of my blog posts, I will write it in rmarkdown, convert it into markdown (using knitr) and then upload this to Github pages (in principle following the steps listed here - http://nicolewhite.github.io/2015/02/07/r-blogging-with-rmarkdown-knitr-jekyll.html). This was all fine when the markdown parser is set to redcarpet. 

Recently [Github Pages announced that starting on May 1st, 2016 it will only support kmarkdown as the markdown parser](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0). Switching to this parser results in all coding blocks no longer rendering due to the fact that kmarkdown doesn't support fenced coding blocks using ```:

I've been reading numerous posts online about kmarkdown's support for fenced coding blocks using ```:

* https://github.com/jekyll/jekyll/issues/2709
* https://github.com/jekyll/jekyll/issues/2711

It seems like it should work with a simple change to your `_config.yml`:

```
kmarkdown:
  input: GFM
```

This doesn't appear to work for me. But when changing the blocks to ~~~, it works fine. 

Thanks,

**Comment by yihui** [comment]
I think you can call `render_markdown(fence_char = '~')` with the current dev version of knitr.

**Comment by KingScooty** [comment]
+1 Having exactly the same issue. ~~~ works fine, but ``` doesn't.

**Comment by tinyheero** [comment]
Thanks works perfectly.
