### ISSUE TITLE
Figure Dimensions Double if Document is Compiled in RStudio

### ISSUE THREAD

**Issue by DarioS** [yihui/knitr#1163]
If you right-click on a PNG image after an Rmd was compiled by clicking Knit HTML in RStudio and viewed in Firefox and click View Image Info ..., the height and width is double what it should be (3000 x 3000). If you compile the same document using `knit2html` at the R command line, the image's dimensions are correct (1500 x 1500). I use knitr 1.12.3 and I tried the release and daily versions of RStudio. I knitted the default markdown document that's generated when you click `File -> New File -> R Markdown`, but with the yaml header removed and `fig.height = 5`, `fig.width = 5`, and `dpi = 300` specified to the figure chunk.

**Comment by yihui** [comment]
This is documented in **rmarkdown** at http://rmarkdown.rstudio.com/html_document_format.html (see `fig_retina`), and `knit2html` is also documented in **knitr** saying that it is for R Markdown v1 only.

**Comment by DarioS** [comment]
I have a DELL monitor connected to a Windows 7 computer and am accessing a Debian Linux server with Xming. `fig_retina` should not be relevant to me.

**Comment by yihui** [comment]
You are probably right that it is not relevant to you since you do not have a retina display, but `fig_retina = 2` is just the default setting. You may turn it off by `fig_retina = NULL` as documented.
