### ISSUE TITLE
Add Check to knit2pdf to Ensure Rnw File Provided

### ISSUE THREAD

**Issue by DarioS** [yihui/knitr#1164]
The caught me out, [as well as Ben Bolker](http://stackoverflow.com/a/14589045). Could you add a check to the top of the function to give an error if users provide an Rmd file ?

**Comment by yihui** [comment]
It didn't catch Ben Bolker. He was only copying the deleted answer to the comment. It caught the person who posted the deleted answer.

I guess this is not the first time that I have had to say "it is documented". True, I can add a warning or error message, but if you don't care about reading the documentation, I will be spending too much time on these checks. In particular, the title of the help page says "**Convert Rnw or Rrst files to PDF**", and if you ever open the help page at all, it will take you at most 5 seconds to realize your mistake.

![screen shot 2016-02-06 at 6 07 26 pm](https://cloud.githubusercontent.com/assets/163582/12870141/8fc6ed9c-ccfc-11e5-935f-985064283bb3.png)
