### ISSUE TITLE
Set `eval.after='fig.cap'` by default.

### ISSUE THREAD

**Issue by JoshOBrien** [yihui/knitr#1165]
This would allow figure captions to include inline expressions that use values computed within the current chunk ([as wished for here](http://stackoverflow.com/q/15708231/980833)), and would somewhat facilitate setting caption contents within a chunk, rather than in the header ([as wished for here](http://stackoverflow.com/q/35207272/980833)). I can't think of a downside, except perhaps that by "just working" as users expect, it won't be teaching them the lesson that chunk headers are evaluated first ;).

**Comment by yihui** [comment]
Done. Thanks!

**Comment by JoshOBrien** [comment]
Terrific, thanks.
