### ISSUE TITLE
include_graphics() does not work as inline R code

### ISSUE THREAD

**Issue by WastlM** [yihui/knitr#1166]
The note in `help("include_graphics")` says:

> This function is supposed to be used in R code chunks or inline R code expressions.

Try

    knit(text = "\\Sexpr{include_graphics('myfigure.pdf')}")

to get

    Error in options$fig.num = length(x) : 
      argument "options" is missing, with no default

which comes from `knitr:::inline_exec` executing `wrap(res, inline = TRUE)`, i.e., calling `knitr:::wrap.knit_image_paths` with a missing `options` argument.

**Comment by yihui** [comment]
Should be fixed now. Thanks!
