### ISSUE TITLE
.Rnw files cannot include or input .tex files

### ISSUE THREAD

**Issue by mathuin** [yihui/knitr#1167]
What I did:

I have been using LaTeX for years, and have developed header files which contain the preambles for various types of documents.  I am new to R and wanted to use knitr with my homework, so I attempted to make an .Rnw file which included my header file.  

I compiled the .Rnw file into a .tex file with the following command:

```
$ Rscript -e "library(knitr); knit('test.Rnw')"
```

I then ran pdflatex on the resulting output.

What I expected:

I expected knitr to import the header file before adding its own information to the preamble and generating the .tex file.

What actually happened:

knitr did not add any information to the preamble, which caused pdflatex to generate an error message about the knitrout environment being undefined.

Session information:
```
> library(knitr)
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.12.3

loaded via a namespace (and not attached):
[1] tools_3.0.2
```

test.Rnw
```
\input{testheader}
\begin{document}
<<>>=
K <- 8
n <- 18
z <- (K-n/2)/sqrt(n/4)
@
\end{document}
```

testheader.tex
```
\documentclass{article}
```

**Comment by yihui** [comment]
You have to keep at least the line `\documentclass` in your .Rnw, otherwise knitr does not know where to add the extra information to the preamble. It is not smart enough to detect `\input` and figure out where the document really starts.
