### ISSUE TITLE
pandoc function

### ISSUE THREAD

**Issue by scls19fr** [yihui/knitr#1170]
Hello,

I'd like to use pandoc in R to convert an HTML file to Markdown or reStructuredText.

but

    pandoc('AirPassengers.html', format='rst')

doesn't convert this file correctly.

I think that's because your pandoc function assume that input file is a Markdown file (not an HTML file)

It will be nice if this function could support (like pandoc tool) several input format.

Kind regards

**Comment by yihui** [comment]
I'll get rid of the assumption soon. Thanks!

**Comment by scls19fr** [comment]
Thanks. That's maybe a little bit out of the scope of knitr but a Rpandoc package could be interesting. knitr could depend on such a package.

**Comment by scls19fr** [comment]
Thanks @yihui
