### ISSUE TITLE
Issue with customizing highlighting theme of knitr

### ISSUE THREAD

**Issue by karagawa** [yihui/knitr#1172]
Hi, Yihui:

I try to change the highlighting theme of knitr following [your instruction](https://github.com/yihui/knitr/blob/master/inst/examples/knitr-themes.Rnw). 

I can successfully download the theme using `css <- eclipse_theme(1885)` , but error appears when I try to execute `thm <- knit_theme$get(css)` :

`Error in if (format == "latex") { : argument is of length zero`

All packages are in the most latest version. I even try the basic theme embedded in knitr (e.g., `knit_theme$get("acid")`, same error comes up. Do you have any thoughts about what happen here? Thank you!

**Comment by yihui** [comment]
This function is supposed to be called within an input document, and it only works when the input document is compiled. You cannot use it outside, and it does not make much sense to call it outside, either.
