### ISSUE TITLE
set chinese character in linux

### ISSUE THREAD

**Issue by weijy026a** [yihui/knitr#1173]
I defined a "header.tex" file and set chinese character as below in Linux platform:
```
\setCJKmainfont[ItalicFont={AR PL UKai CN}]{AR PL UMing CN} 
\setCJKsansfont{WenQuanYi Zen Hei} 
\setCJKmonofont{WenQuanYi Zen Hei Mono} 
```
However when I compile a “rmd” file with RStudio， It will report this error：

```
! fontspec error: "font-not-found"
! 
! The font "WenQuanYi Zen Hei" cannot be found.
! 
! See the fontspec documentation for further information.
```
the fonts can be compiled with command `xelatex *.tex`. How should I config the system?

**Comment by yihui** [comment]
Please provide a minimal reproducible example.
