### ISSUE TITLE
fig.align = 'center' documentation incomplete

### ISSUE THREAD

**Issue by dhicks** [yihui/knitr#1175]
Per #960, with Markdown/LaTeX output the chunk option `fig.align = 'center'` requires `graphics: yes` in the YAML headers.  This is not noted in the [chunk options documentation](http://yihui.name/knitr/options/) for `fig.align`.  (The issue link there doesn't explain the need to do this, either.)  The documentation should indicate the need to include `graphics: yes` in the YAML.

**Comment by yihui** [comment]
This has been automatically added long time ago: https://github.com/rstudio/rmarkdown/pull/538 You just need the latest version of rmarkdown.
