### ISSUE TITLE
Vertical space between calls to (different) plotting functions despite fig.show = "hide"

### ISSUE THREAD

**Issue by ClaudiusL** [yihui/knitr#1178]
The following chunk/minimal document produces two separete code blocks instead of one code block:

    ```{r, fig.show='hide'}
    hist(1)
    plot(1)
    ```

As the figures are suppressed, I expect one code block without any figure output. However, the expressions are wrapped in different code blocks, just like there was some "invisible output" between `hist` and `plot`.

This seems to be related to the fact that two different plotting functions are used. Using twice `hist`, or twice `plot`, or twice `barplot` doesn't reproduce the error, but any combination of two different plotting functions does.

Versions: R 3.2.3; knitr 1.12.17

**Comment by yihui** [comment]
You can use the chunk option `collapse = TRUE` to collapse the two code blocks, e.g.

    ```{r, fig.show='hide', collapse=TRUE}
    hist(1)
    plot(1)
    ```

**Comment by ClaudiusL** [comment]
Yup, this solves the issue. So there is nothing weird/buggy going on that is responsible for a chunk with two `plot` calls being rendered differently than a chunk with a `plot` and a `hist` call?

**Comment by yihui** [comment]
I could fix it. It is just that the workaround is simple enough, whereas the fix will take much longer (in other words, I'm lazy...).

When you have two identical calls `plot(1)`, the first plot will actually be removed. **knitr** does not allow identical plots to appear consecutively in the same chunk.
