### ISSUE TITLE
Problem with kable() and dollar signs and markdown

### ISSUE THREAD

**Issue by jennybc** [yihui/knitr#1182]
I have created a Perfect Storm of dollar signs that confuses `kable()` greatly. But if and only if you set `options(knitr.table.format = 'markdown')` 😬.

Here's the gist with Rmd and html:

https://gist.github.com/jennybc/d2498b3b21e6f3d10c9c

And here's a link to rendered html:

https://rawgit.com/jennybc/d2498b3b21e6f3d10c9c/raw/041f25a105c4c678ae6a96765464fcc6bed36b31/kable-reprex.html

**Comment by jennybc** [comment]
This is stripped out of a larger example that has many cells = rows between B6 and E5 (the two included here). The garbling in my reprex happens in the larger example AND all the rows in between fail to appear in the rendered table.

**Comment by yihui** [comment]
Cool, so MathJax treated them as math expressions. Sounds like we need to escape the dollar signs to `\$`. The question is whether you do it in the data (something like `grep('$', '\\$', x, fixed = TRUE)`), or I provide an option to do it in `kable()`...

**Comment by jennybc** [comment]
OK I will escape them myself for now! But with `gsub()` instead ;)

**Comment by yihui** [comment]
Oh right. That was a typo. I blame DST and Solaris for that!

**Comment by jennybc** [comment]
I'm having another problem now but with square brackets. It's sort of the opposite: I want to keep `knitr` from escaping the `[`.

Let this be `foo.Rmd`:

<pre><code>
---
output: github_document
---

```{r}
df <- data.frame(A1 = c("$B$4", "B4"),
                 R1C1 = c("R4C2", "R[4]C[2]"),
                 row.names = c("abs", "rel"))
```

```{r results = "as.is", echo = FALSE}
knitr::kable(df)
```
</code></pre>

Here is the table in the resulting `foo.md`:

```
|     | A1   | R1C1         |
|-----|:-----|:-------------|
| abs | $B$4 | R4C2         |
| rel | B4   | R\[4\]C\[2\] |
```

and local preview looks like so:

<img width="201" alt="square-bracket-problem" src="https://cloud.githubusercontent.com/assets/599454/14359475/6e06eff2-fca6-11e5-8b40-33ffa1569fa9.png">

But if I had this markdown table instead (note the lack of backslashes escaping the square brackets0:

```
|     | A1   | R1C1         |
|-----|:-----|:-------------|
| abs | $B$4 | R4C2         |
| rel | B4   | R[4]C[2] |
```

I get the table I want:

|     | A1   | R1C1         |
|-----|:-----|:-------------|
| abs | $B$4 | R4C2         |
| rel | B4   | R[4]C[2] |

Do you have any advice for me? Even if I enter the markdown table literally (i.e. skip creating a df and using `knitr::kable()` entirely), these backslashes are inserted during Rmd --> md.

**Comment by jennybc** [comment]
This has nothing to do with tables actually. Just try to put something like `R[1]C[-3]` into an Rmd w/o protecting with backticks and you get problems. I half believe I'm missing something obvious and well-known and half believe I should open a new issue.

**Comment by yihui** [comment]
Sounds like a Pandoc issue... The square brackets are not escaped when I use `html_document`. `\[ \]` means math expressions, but I don't know who escaped them (I don't do it in `kable()`).

**Comment by jennybc** [comment]
It's starts to seem like an issue with `github_document` specifically? Because the backslashes appear in the md and I thought that Rmd --> md conversion happened prior to anything involving Pandoc.
