### ISSUE TITLE
Knit HTML - Recover from Error? {Feature Request}

### ISSUE THREAD

**Issue by myloginid** [yihui/knitr#1183]
Hi,

Referring to the question on SO - http://stackoverflow.com/questions/36026131/knit-html-recover-from-error

Currently in case there is any error in the R code, Knitr aborts. Its a pain especially for large analysis jobs to lose 2-3 hours of output. Can we add a feature in Knitr that - 

Option 1 - Recovers the partially created HTML from tmp directories or anywhere else
Option 2 - Get Knit HTML to continue on errors and not halt the code.
Option 3 - Atleast save the already Knit HTML and then stop. 

Staying True to "faithful output" principle, because the code was wrong, the offending code and error must go to the Knitted HTML and then execution can either stop or continue depending on the programmer's preference.

Is there anyway that we can add this as a feature?

Thanks, Manish

**Comment by yihui** [comment]
Yes, answered on SO.
