### ISSUE TITLE
SAS Highlighting

### ISSUE THREAD

**Issue by curtisalexander** [yihui/knitr#1185]
I cannot seem to get highlighting of SAS source code working.  If I use code similar to Yihui's [SAS example](https://github.com/yihui/knitr-examples/blob/master/060-engine-sas.Rmd), I don't get any highlighting of SAS code.  Instead, it appears the code is simply formatted as a code block.

Below is the Rmd file that I am testing with.

    ---
    title: "SAS Highlight Testing"
    author: "Curtis Alexander"
    date: "March 29, 2016"
    output: html_document
    ---

    The below is an example of using SAS highlighting.

    ```{r engine='sas', eval=FALSE}
    data _null_;
      x = 1;
      /* comment */
    run;
    ```

I assume that I don't need the path to a SAS executable in order to get the needed highlighting.  I have tried running the SAS code through the `highr` package by running

```{r}
highr::hi_andre("data _null_; x = 1; /* comment */ run;", language = "sas", format = "html")
```
which produces the following output.
```
<span class=\"hl kwb\">data</span> _null_<span class=\"hl opt\">;</span> x <span class=\"hl opt\">=</span> <span class=\"hl num\">1</span><span class=\"hl opt\">;</span> <span class=\"hl com\">/* comment */</span> <span class=\"hl kwb\">run</span><span class=\"hl opt\">;</span>
```

Is there a way to use the `hi_andre` function to get the SAS code to be highlighted?  Or is this truly an issue in `knitr` requiring a pull request?  If it is an issue, I would be glad to work through a pull request with a little direction.  I spent some time in the code base yesterday but was having a difficult time figuring out exactly where I needed to get started -- `engine.R`, `highlight.R`, or `hooks-html.R`.  Again, if I could get pointed in a direction then I'll try to work through.

Thanks.

**Comment by yihui** [comment]
R Markdown v2 does not use highr. Syntax highlighting is handled through Pandoc, so it is up to Pandoc if SAS code is supported. If you want Pandoc to include syntax highlighting support for SAS, you may submit a pull request to https://github.com/jgm/highlighting-kate Thanks!

**Comment by curtisalexander** [comment]
If interested, I figured out how to make use of a source hook with the `highr` package to get SAS syntax highlighting working using `knitr`.  I wrote it up at

http://curtisalexander.github.io/rmarkdown-syntax-highlighting/

**Comment by yihui** [comment]
Cool. Thanks for sharing!
