### ISSUE TITLE
fig.env chunk option ignored?

### ISSUE THREAD

**Issue by crsh** [yihui/knitr#1186]
I'm having a little trouble with the `fig.env` chunk option. For the LaTeX apa6 document class it is important that all figures are in `figure` environments. By default `knitr` doesn't seem to add an environment.

    ---
    title: "Untitled"
    output:
      pdf_document:
        keep_tex: true
    ---
    
    ```{r fig.env = "figure"}
    plot(cars)
    ```

This document produces `\includegraphics{test_files/figure-latex/unnamed-chunk-1-1.pdf}`; no environment is added. Only if I set `fig_caption: true` and add a caption the `figure` environment is added. Following a [previous discussion](https://github.com/yihui/knitr/issues/1125) I tried setting `out.extra = ''` but to no avail.

I have, by default, set `fig.cap = " "` to resolve this issue for me but it feels a little hacky. Is there a particular reason why `fig.env = "figure"` is ignored?

**Comment by yihui** [comment]
As you have discovered, `fig.env` is only used when there is a figure caption. `fig.cap = ""` is the correct solution. It is rare to see a figure without a caption anyway.
