### ISSUE TITLE
no sci format of very small numbers

### ISSUE THREAD

**Issue by mkapplebee** [yihui/knitr#1187]
I am very new to R markdown, but I am trying to write a report with it in HTML format with tables.  Some of my tables include pvalues, some of which are very small - so the exponent associated with them is important.  I would like to use knitr/kable, but my padj values are only showing as "0".  Here is some code with a modified 'iris' table that shows the problem - compare column 'sml' between the kable version and regular "print" version - 

```{r}
library(knitr)
options(scipen=-20)
sml<-iris[,1]*10^-12  #these are very small, but not 0
lrg<-iris[,2]*10^12  # these are analogously large
y<-cbind(sml,lrg,iris[,3:5])

kable(y[1:10,])    #sml is converted to 0, in scientific format, but lrg retains its correct reported value
y[1:10,]              # sml is correctly reported in scientific format
```

screenshot of the output I get:
![test1-screenshot](https://cloud.githubusercontent.com/assets/10427352/14224432/3cc40a50-f851-11e5-8b92-d6cee15da4c1.png)

I am using R 3.2.3, Rstudio Version 0.99.451, and I just checked that I have the latest update to knitr - but I still get this problem.

**Comment by yihui** [comment]
That is because the numbers are rounded to 7 decimal places by default. You can use a larger `digits` value, e.g.

```r
kable(y[1:10,], digits = 20)
```

But I think a P-value as small as 10^-12 is basically 0.
