### ISSUE TITLE
Figure caption rendering in md broken again?

### ISSUE THREAD

**Issue by psychemedia** [yihui/knitr#1188]
The issue https://github.com/yihui/knitr/issues/1160 appears to have reappeared?

**Comment by yihui** [comment]
If the current development version does not work, could you provide a minimal, self-contained, and reproducible example?

**Comment by psychemedia** [comment]
````
   ---
   output:
     html_document:
       keep_md: yes
   ---
    ```{r}
    packageVersion("knitr")
    ```

    ```{r, fig.cap='My plot',echo=FALSE}
    plot(cars)
    ```
````

produces:


    ```r
    packageVersion("knitr")
    ```

    ```
    ## [1] '1.12.3'
    ```
    <div class="figure">
    <img src="example_knitr_files/figure-html/unnamed-chunk-1-1.png" alt="My plot"  />
    <p class="caption">My plot</p>
    </div>

**Comment by yihui** [comment]
Glad to know that!
