### ISSUE TITLE
object 'complete' not found in R studio

### ISSUE THREAD

**Issue by gitagowda** [yihui/knitr#1190]

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example?

**Comment by gitagowda** [comment]
Hi,
I was in the process of completing an assignment in R and I wanted to submit the following query:

C <- complete(“data”, 54)

But it gave me an error saying: object ‘complete’ not found. I could get complete.cases and other options but not ‘complete’. Can you please help?

Thanks!
Geetha

**Comment by yihui** [comment]
I don't know what `complete` is (it is not a base R function) or where it comes from.
