### ISSUE TITLE
Plots and Data from different chunks

### ISSUE THREAD

**Issue by susana1712** [yihui/knitr#1191]
I am creating my first Word report with R studio, markdown and knitr and I am having some troubles.

My r code includes several chunks, because between chunks, I want to include the text my report should include. The chunks I have are: first one to load the data, second to format date, third to create ggplots, fourth do some regression analysis, etc.

The problem I have is that: if use a single chunk, then the report is ok, but I can't include text/comments to be written in the report, unless I print also the code. But if I use multiple chunks, when compiling, plots are not included in the report and a warning message appears:

    pandoc.exe: Could not find image `Scriptv01_files/figure-docx/4.PLOTS-1.png', skipping...
    pandoc.exe: Could not find image `Scriptv01_files/figure-docx/4.PLOTS-2.png', skipping...

I have to say also that with HTML output it works properly: report includes all plots, but not with DOC output.

How can this be fixed? What's the problem?
Many thanks!

Here I provide a code example:

    ---
    output: word_document
    ---
        # PROJECT: IRIS STUDY
    #### Statistical Analysis
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, comment='')
    ```
    
    ```{r 1.INITIALIZATIONS}
    #Data file name - Fisher's Iris data set in external CSV file
      dfn<-"iris.csv"
    ```  
    
    ```{r 2.SET DIRECTORIES}
    
    #Set working directory
      setwd("C:/Users/SPerez/Desktop")
    ```  
       
    ```{r 3. READ DATA}
    #Read Data
      dataset<-read.csv2(dfn)
    #Format Variables
      dataset$Sepal.Length<-as.numeric(as.character(dataset$Sepal.Length))
      dataset$Sepal.Width<-as.numeric(as.character(dataset$Sepal.Width))
      dataset$Petal.Length<-as.numeric(as.character(dataset$Petal.Length))
      dataset$Petal.Width<-as.numeric(as.character(dataset$Petal.Width))
    ```
      
    ### Data Descriptive by Iris Specie   
    ```{r 4. ANALYSE DATA -  DATA DESCRIPTION BY SPECIE}
      require(gmodels)
      require(ggplot2)
      CrossTable(dataset$Species,digits=4,prop.t=TRUE, prop.r=TRUE, prop.c=TRUE,dnn=c("","Species"))
      ggplot(dataset, aes(Species)) + geom_bar(aes(fill=Species))+
          labs(x = "Species", y = "Number of Flowers")+ ggtitle("Fisher's Iris data set")
    ```
    
    ### Data Boxplot by Iris Specie and Sepal
    ```{r 4. ANALYSE DATA -  DATA DESCRIPTION}
      require(ggplot2)
    	ggplot(dataset,aes(y=Sepal.Length,x=Species,colour=Species)) + stat_boxplot() + 
          labs(x = "Species", y = "Number of Flowers")+ ggtitle("Fisher's Iris data set")	
    ```

**Comment by yihui** [comment]
Please provide a minimal, self-contained, and reproducible example. The above example does not appear to qualify. And please read the contributing guide before posting an issue: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by susana1712** [comment]
I have updated the example following your suggestions. Any clue will be welcome. Thanks.
