### ISSUE TITLE
! LaTeX Error: Missing \begin{document}.

### ISSUE THREAD

**Issue by Norwich** [yihui/knitr#1194]
R version 3.2.4 (2016-03-10), when knitting to PDF  hitting an error: 

/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS analysis.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output analysis.pdf --template /usr/local/lib64/R/site-library/rmarkdown/rmd/latex/default-1.15.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 <

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted

While knitting, the process generates tmp files with graphs, runs completely but errors out by the end with the message above. Adding  \begin{document} didn't resolve the situation.
I'd appreciate any suggestion or insight on functionality between knitr and latex when it is converting to pdf.
Earlier, the error message of  missing ifxetex.sty, was happening that was resolved with adding file to R/site-library/rmarkdown/rmd/latex. 

Converting to MS Word resulted in output with no graphs supported.

Thanks.

**Comment by yihui** [comment]
It looks like you didn't read the guide before posting the issue: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by gsaray101** [comment]
I'm getting the same error. How do you address this issue?

! LaTeX Error: Missing \begin{document}

**Comment by yihui** [comment]
@gsaray101 Similarly, please read the guide before asking questions: https://github.com/yihui/knitr/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by gsaray101** [comment]
@yihui, I am stuck. I cannot figure this out. I am trying to colour code the cells in xtable output, but I get this error:

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 <

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: There were 20 warnings (use warnings() to see them)
Execution halted

If I take out this line from my rmd file "header-includes:
   - \usepackage{colortbl}", I can produce the pdf file but no colors in the xtable cells. 

This is my stackoverflow post link: 

https://stackoverflow.com/questions/44373073/unable-to-change-the-colors-of-the-xtable-cells-in-rmarkdown-output-to-pdf?noredirect=1#comment76260017_44373073
