### ISSUE TITLE
Knitr-produced HTML files not loading hypothes.is correctly

### ISSUE THREAD

**Issue by RaoOfPhysics** [yihui/knitr#1196]
I'm using Knitr as part of RStudio to produce HTML files with my analyses in them. I would like to use [hypothes.is](https://hypothes.is) to allow people to annotate the content, but the annotation window doesn't appear in these files (both with and without using `reveal.js`).

**Comment by yihui** [comment]
Where is your minimal reproducible example? https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by RaoOfPhysics** [comment]
Tried to reproduce the issue a third time to write up the example and it seems like it's working fine now. My apologies for having disturbed you and for not having provided adequate information when creating the issue.

**Comment by yihui** [comment]
No worries.
