### ISSUE TITLE
prompts for python code

### ISSUE THREAD

**Issue by NattyE** [yihui/knitr#1197]
I may be missing something obvious here, but this feels like a bug to me.  I was running the latest version of `knitr` from CRAN (`v1.12.3`). I have a simple `rmarkdown` document (please ignore any poor syntax - that's the point of this document):

    ---
    title: "knitrtest"
    author: "Nathan Eastwood"
    date: "19 April 2016"
    output: word_document
    ---
    
    Testing knitr python engine
    
    ```{r test-r, engine='R'}
    library(knitr)
    knitr::opts_chunk$set(prompt = FALSE)
    ```
    
    ```{r}
    rnorm(10)
    ```
        
    ```{r my-test-python, engine='python', eval=FALSE}
    import numpy as np
    import pandas as pd
    
    def read_airquality_data():
        """Read in airquality dataset from R"""
        url = 'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/airquality.csv'
        names = ["Ozone","Solar.R","Wind","Temp","Month","Day"]
        return pd.read_csv(url, names=names, index_col= 0, skiprows=1)
    ```

The issue I am having is if I want to set `prompt = TRUE` when `eval = FALSE` - it doesn't run! I get the following error:

    Quitting from lines 16-24 (knitrtest.Rmd) 
    Error in parse(text = piece) : <text>:1:8: unexpected symbol
    1: import numpy
               ^
    Calls: <Anonymous> ... <Anonymous> -> hilight_source -> vapply -> <Anonymous> -> parse
    Execution halted

For all other combinations of `prompt` and `eval`, it works however. 

Installing the latest version from GitHub (`v1.12.22`) does in fact fix the issue - sort of. The code now runs, however it does not render a prompt in the resulting Word doc. I know you are [not a fan of prompts](https://github.com/yihui/knitr/blob/master/FAQ.md), Yihui, so I apologise for using them ;)

My current session information:

    > sessionInfo()
    R version 3.2.4 (2016-03-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
    [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
    [5] LC_TIME=English_United Kingdom.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] knitr_1.12.22
    
    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.4       digest_0.6.9      withr_1.0.1       R6_2.1.2         
     [5] git2r_0.14.0      formatR_1.3       magrittr_1.5      evaluate_0.8.3   
     [9] highr_0.5.1       httr_1.1.0        stringi_1.0-1     curl_0.9.6       
    [13] rmarkdown_0.9.5.9 devtools_1.10.0   tools_3.2.4       stringr_1.0.0    
    [17] yaml_2.1.13       memoise_1.0.0     htmltools_0.3.5

**Comment by yihui** [comment]
Thanks! Should be fixed now. Note other languages, including Python, are not well supported in knitr, so the prompts may not be really what you get from the Python console, e.g. it is currently not possible to add `+++` as the continuation prompt. You can only add `>>>`, e.g.

    ```{r my-test-python, engine='python', eval=FALSE, prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
    import numpy as np
    import pandas as pd
    
    def read_airquality_data():
        """Read in airquality dataset from R"""
        url = 'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/airquality.csv'
        names = ["Ozone","Solar.R","Wind","Temp","Month","Day"]
        return pd.read_csv(url, names=names, index_col= 0, skiprows=1)
    ```

**Comment by NattyE** [comment]
Thanks Yihui :+1:  great work! I can confirm that this is working now.
No problem about the python prompt support - we will work with what we've got. :)
