### ISSUE TITLE
DT with bootstrap styling to pdf/word

### ISSUE THREAD

**Issue by vnijs** [yihui/knitr#1198]
FYI It seems bootstrap styling does not show up in pdf/word files. 

---
title: "DT"
output: pdf_document
---

```{r}
library(DT)
datatable(iris, style = 'bootstrap')
```

[Untitled.pdf](https://github.com/yihui/knitr/files/227110/Untitled.pdf)

**Comment by yihui** [comment]
That is kind of expected (well, to me). For DT, all non-default styles require you to prepare the style dependencies. Bootstrap dependencies are ready in R Markdown documents by default, but not provided when you render a DT widget as a standalone page.

With the latest version of rmarkdown, you can add the Bootstrap dependencies via `html_dependency_bootstrap()`, e.g.

```r
library(DT)
res = datatable(iris, style = 'bootstrap')
res$dependencies = c(
  list(rmarkdown::html_dependency_bootstrap('bootstrap')), res$dependencies
)
res
```

BTW, you may indent the Rmd source by 4 spaces in the future for format it correctly. See the contributing guide: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by vnijs** [comment]
Thanks @yihui. Works great
