### ISSUE TITLE
Different table caption in List of Tables using `kable`

### ISSUE THREAD

**Issue by ismayc** [yihui/knitr#1199]
Is there a way to add an alternative caption like `fig.scap` does for figures when using `kable`?  I'd like shorter text to appear in a List of Tables instead of the longer text I've provided for the `caption` argument to `kable`.

**Comment by yihui** [comment]
Implemented via 23e25c51cd41fa328e453e39e5a84724c7f20ddc. Thanks!

**Comment by ismayc** [comment]
I'm still having the main caption override the `caption.short` I specify:  https://gist.github.com/ismayc/5677d9959ffbf2f71358642b64cc87cb .  Any idea why?

**Comment by yihui** [comment]
Markdown tables do not support short captions, which is only a concept in LaTeX. You have to generate LaTeX tables, and you can force LaTeX tables in Markdown by setting

```r
knitr::opts_knit$set(kable.force.latex = TRUE)
```

**Comment by ismayc** [comment]
I've added that line to a chunk in the gist and after running it, it still is not working.

Maybe my `sessionInfo` would be helpful?

```
## R version 3.2.5 Patched (2016-04-17 r70499)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: OS X 10.11.4 (El Capitan)
##
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
##
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base
##
## other attached packages:
## [1] knitr_1.12.23    ggplot2_2.1.0    dplyr_0.4.3.9001
##
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.3
##  [4] munsell_0.4.3
##  [7] highr_0.5.1
## [10] plyr_1.8.3
## [13] gtable_0.2.0
## [16] htmltools_0.3
## [19] assertthat_0.1
## [22] formatR_1.3
## [25] evaluate_0.8.3
## [28] stringi_1.0-1
magrittr_1.5       devtools_1.10.0
colorspace_1.2-6   R6_2.1.2
stringr_1.0.0.9000 httr_1.1.0
tools_3.2.5
DBI_0.3.1
lazyeval_0.1.10
digest_0.6.9
curl_0.9.6
rmarkdown_0.9.5.9  labeling_0.3
scales_0.4.0
```

**Comment by yihui** [comment]
The latest version is 1.12.24: https://github.com/yihui/knitr/blob/master/DESCRIPTION so you have to reinstall.

**Comment by ismayc** [comment]
Ah!  It works now when I run:  `devtools::install_github("yihui/knitr", force = TRUE` but I don't understand why referencing didn't also work? `devtools::install_github("yihui/knitr", ref = "23e25c51cd41fa328e453e39e5a84724c7f20ddc", force = TRUE)`

**Comment by ismayc** [comment]
Thanks!!!!

**Comment by yihui** [comment]
That is because I made a change 9b5bcb1d36de30188e63fc1a1bc3fb68c382af77 after that commit.

**Comment by ismayc** [comment]
Gotcha.  Thanks again!
