### ISSUE TITLE
Rscript - knitr: substr function not working correctly inside knitr code chunk

### ISSUE THREAD

**Issue by kkruups** [yihui/knitr#1201]
The substr function does not appear to extract the substring in a shiny knitr Rmd document.

Details are in the following stackflow link:

http://stackoverflow.com/questions/36904010/rscript-knitr-substr-function-not-working-correctly-inside-knitr-code-chunk

BR/KK

**Comment by yihui** [comment]
Please read the contributing guide and revise your SO post to add a minimal reproducible example: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by kkruups** [comment]
Updated SO, as per your request.
