### ISSUE TITLE
Rscript - knitr: substr function not working correctly inside knitr code chunk 

### ISSUE THREAD

**Issue by kkruups** [yihui/knitr#1202]
SO updated with minimal reproducible example.

Please put a reason why your closing issue, when you close issue.
.

http://stackoverflow.com/questions/36904010/rscript-knitr-substr-function-not-working-correctly-inside-knitr-code-chunk

**Comment by yihui** [comment]
I closed #1201 because you have already posted a question on SO. There is no need to duplicate it here.  Besides, you didn't provide a minimal self-contained reproducible example as requested by the contributing guide.

**Comment by kkruups** [comment]
Understood. thanks for the update.
