### ISSUE TITLE
knitr should interact better with `system` (R)

### ISSUE THREAD

**Issue by MichaelChirico** [yihui/knitr#1203]
As highlighted by [this question](http://stackoverflow.com/questions/27388964/rmarkdown-not-outputting-results-of-system-command-to-html-file), we sort of have to jump through hoops to get the output from a `system` call to print its output to HTML.

Consider the following simple .Rmd file:

    ---
    output: html_document
    ---
  
    ```{r test, echo = TRUE}
    system("ls")
    ```

The output of which is simply:

    system("ls")

We can force the output to show up by hiding things from viewers:

    ---
    output: html_document
    ---
  
    ```{r test, echo = TRUE, eval = FALSE}
    system("ls")
    ```
    ```{r test_eval, echo = FALSE, eval = TRUE}
    cat(system("ls", intern = TRUE), collapse = "\n")
    ```

Which produces the output one would expect from simply running the first chunk.

But this seems like a sub-optimal solution and I think runs antithetical to the spirit of `knitr`.

I'm not 100% sure this is a `knitr` problem (as opposed to an `rmarkdown` problem); please advise if so.

**Comment by yihui** [comment]
I'm aware of this issue but I don't know a good answer. I posted a question on SO http://stackoverflow.com/q/36928322/559676

**Comment by MichaelChirico** [comment]
Great! A strange issue indeed. Seems `capture.output` is not doing exactly what we think it is.

**Comment by MichaelChirico** [comment]
Could `knitr` perhaps overload `system` so that a call to `system` within a `knitr` chunk gets sent to `knitr::system` which is a wrap to the `cat(system(..., intern = TRUE), collapse = "\n")` approach?

My instincts tell me that's a terrible idea, but worth a suggestion.

**Comment by yihui** [comment]
That is a natural thing to think about, but as you said, I'd not do it if we can find another way.

**Comment by MichaelChirico** [comment]
It's just so strange how `system` behaves. If we get an error code returned when `intern = FALSE`, why should it _also_ print the output to the console (but apparently not to `stdout`)?

Hopefully there's a better way.

**Comment by yihui** [comment]
You can install the development version of **evaluate** via

```r
devtools::install_github('hadley/evaluate')
```

Then you can use this hack:

```r
evaluate::inject_funs(
  system = function(...) cat(base::system(..., intern = TRUE), sep = "\n")
)
```

and **knitr** will be able to capture the output of `system()`. Remember it is a hack. It basically replaced `system` in the global environment, so if you want the real `system`, you have to add the qualifier `base::`.

**Comment by MichaelChirico** [comment]
Neat trick. What's the benefit of using `inject_funs` over just writing `system = function(...) cat(base::system(..., intern = TRUE), sep = "\n")`?

**Comment by yihui** [comment]
@MichaelChirico Well, no obvious advantages :)
