### ISSUE TITLE
mechanism to ensure 'chunk' hook always run (even when no output)?

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1204]
E.g. as in

https://github.com/yihui/knitr/blob/master/R/block.R#L108
https://github.com/yihui/knitr/blob/master/R/block.R#L246

Any reason for this in particular? (I'd like to have a custom chunk hook that gets run for each logical chunk, regardless of whether execution of the code within produced any output or not.)

This is effectively so that I can annotate all chunks executed, e.g. with the chunk hook I can do something like:

```
knitHooks <- knitr::knit_hooks$get()
knitr::knit_hooks$set(
         chunk = function(...) {
            output <- knitHooks$chunk(...)
            annotate(output)
         }
)
```

where `annotate` produces some HTML comments that provide additional metadata (used to support the R notebook).

Any reason why the chunk hooks don't run when there is no output? Would it be possible to configure knitr to always run chunk hooks? Alternatively, is there a separate hook that I can / should be using here?

**Comment by yihui** [comment]
I think that was to avoid generating empty blocks like

    ```
    ```

but I can certainly move the test logic `is_blank()` into specific chunk hooks for all output formats.

**Comment by yihui** [comment]
Okay it seems safe enough to remove the `if (is_blank())` statement. All tests can still pass.

**Comment by kevinushey** [comment]
Awesome, thanks Yihui!
