### ISSUE TITLE
Widget screenshot is empty on Windows

### ISSUE THREAD

**Issue by bergant** [yihui/knitr#1205]
Using html widgets "automagically" with PDF and Word output is huge win! But ... it does not work on my windows machine.

I think the problem is in how temporary file name is created when saving a widget to a html
(see [plot.R](https://github.com/yihui/knitr/blob/d8ae33df4f05177567f0f172043d03b5afdb9a4e/R/plot.R#L483)). This minimal example works fine on Ubuntu and fails on Windows:

    widget <- DT::datatable(iris)
    
    f1 <- tempfile("widget", ".", fileext = ".html")
    f2 <- tempfile("webshot", ".", fileext = ".png")
    
    htmlwidgets::saveWidget(widget, f1)
    webshot::webshot(f1, f2)
    
    img <- png::readPNG(f2)
    grid::grid.raster(img)

On Windows it runs without any error messages but returns image with all zeros (I think webshot always returns empty image when it can't find the source file).

If I only change `f1` to...
 
    f1 <- basename(f1)

... then it works on Windows too.

Tested with 
knitr_1.12.27 and webshot_0.3.0.9000, 
on Windows 8.1 and Ubuntu 15.10

**Comment by yihui** [comment]
Thanks a lot for the report and investigation! I added `basename()` as you suggested.

**Comment by bergant** [comment]
Yes! It's working now! Thank you so much for fixing this so quickly! :+1:
