### ISSUE TITLE
stitch_rhtml fumbles method resolution

### ISSUE THREAD

**Issue by Hughan** [yihui/knitr#1207]
# Summary
When using stitch_rhtml I get an error running a simple script:
```
library(dplyr)

df = data_frame(id = seq_len(10), value = rnorm(n = 10))

identical(filter, dplyr::filter)
identical(filter, stats::filter)

df %>% filter(value > 0)
```
due to the `filter` function resolving to `stats::filter` rather than `dplyr::filter`. 

Running stitch produces the correct method resolution.

# Details
Save script above as test_stitch.R and run `stitch_rhtml('test_stitch.R')` to get:
![test_stitch html](https://cloud.githubusercontent.com/assets/4338462/15001812/d4ad5fb8-11ee-11e6-8ce3-95085a07af4d.png)

but simple `stitch('test_stitch.R')` yields
[test_stitch.pdf](https://github.com/yihui/knitr/files/247973/test_stitch.pdf)

**Comment by yihui** [comment]
Thanks for the report! Should be fixed in the devel version here now.

**Comment by Hughan** [comment]
Brilliant response time - Thanks Yihui!
