### ISSUE TITLE
Error: pandoc document conversion failed with error 1

### ISSUE THREAD

**Issue by pkgandhi** [yihui/knitr#1209]
Hello,

I am wondering what is going here with my Rmd document. I am getting the following error:

pandoc.exe: Udacity_DescriptiveStats_Project.pdf: openBinaryFile: permission denied (Permission denied)
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Udacity_DescriptiveStats_Project.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Udacity_DescriptiveStats_Project.pdf --template "C:\Users\PRATIK~1\DOCUME~1\R\WIN-LI~1\3.2\RMARKD~1\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 1 
Execution halted

I am not able to convert to pdf with this specific project. The other projects look and work fine! Is there anything I need to load or change. 

Thank you!

**Comment by yihui** [comment]
Sorry I have no idea. The error message is too vague to me.

**Comment by Auburngrads** [comment]
In my experience, this error message means that Pandoc cannot write to the file 'Udacity_DescriptiveStats_Project.pdf' because it is currently open.  

Solution = Close the file Udacity_DescriptiveStats_Project.pdf'  and try to render the document again

**Comment by fabio-a-oliveira** [comment]
Just had the same error. Resolved by adding pandoc.exe to the antivirus whitelist (BitDefender, in my case).
