### ISSUE TITLE
\maxwidth vs \linewidth

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#1210]
Hi,
Is it on purpose that the default `out.width` is `\maxwidth` whereas `out.width="x%"` generates a percentage of `\linewidth`?

**Comment by yihui** [comment]
Yes, `\maxwidth` makes sure the plots will not exceed the page margin, and it does not scale plots that are narrower than the line width. `x\linewidth` always scales plots. They are totally different, and I don't feel the width `x%` should be translated to `x\maxwidth`.

**Comment by knokknok** [comment]
Got it, thanks!
