### ISSUE TITLE
Errors with knitr 1.13 and R 3.3.0

### ISSUE THREAD

**Issue by stevenranney** [yihui/knitr#1214]
On a brand new machine with a fresh install of Windows 7, `R 3.3.0`, `knitr 1.13`, and Rstudio 0.99.902, I was receiving the following error when running the `knit()` function:

    Error in evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), : could not find function "parse_all"

[Some digging on StackOverflow](http://stackoverflow.com/questions/37241578/getting-a-parser-all-error-in-r-when-using-knitr-for-converting-a-basic-rmd-file) suggested that there was a potential mismatch between the `knitr` version and my `R` version, but as both were, essentially, the most updated versions possible, this surprised me.  

However, to see if I could get my code to work (which worked without error on a previous machine with older versions of `R` and `knitr` (which versions I don't recall)), I reverted to `knitr 1.12` which a user suggested was a potential solution in the SO question above.  After reversion to the previous `knitr`, my code ran without errors.

```
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.0                         
year           2016                        
month          05                          
day            03                          
svn rev        70573                       
language       R                           
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational 
```

```
> packageVersion("knitr")
[1] ‘1.12’
```

This behavior was quite unexpected and although I don't know if it's a *bug*, others may have similar issues in the future.

**Comment by yihui** [comment]
I have posted a comment on SO.
