### ISSUE TITLE
global.par error when graphics window is partitioned

### ISSUE THREAD

**Issue by jrwishart** [yihui/knitr#1215]
I believe I have found an error in the global.par setting with base graphics. The error occurs when the graphics window is partitioned and a later chunk use a plot command. The error message thrown is

> Error in par(x) : parameter "j" in "mfg" is out of range
> Calls: <Anonymous> ... process_group.block -> call_block -> block_exec -> par2 -> par

minimal example below

    ```{r setup, include=FALSE}
    library(knitr)
    opts_knit$set(global.par = TRUE)
    ```
    
    This is a test of the global.par command
    
    ```{r a}
    par(mar = c(3, 3, 2, 1), mgp = c(2, 1, 0))
    ```
    
    Change the `par` settings
    
    ```{r b}
    x = rnorm(10)
    qqnorm(x)
    ```
    
    Plot renders fine with appropriate margin changes
    
    ```{r c}
    y = x
    y
    ```
    
    Chunk without plot executes and renders fine.
    
    ```{r d}
    par(mfrow = c(1, 2))
    plot(x)
    qqnorm(x)
    ```
    
    Graphics window partitioned and plots made without error
    
    ```{r e}
    z = x^2
    z
    ```

This chunk causes an error based on the partition commands the global settings. The error is localised to this last chunk (the other chunks parse and render fine).

Error message is

> Error in par(x) : parameter "j" in "mfg" is out of range
> Calls: <Anonymous> ... process_group.block -> call_block -> block_exec -> par2 -> par
> In addition: Warning message:
> In par(x) : calling par(new=TRUE) with no plot
> Execution halted

If a `dev.off()` command is put in the second last chunk (the last chunk that uses a plot command with the partitioned setup), the error disappears and the last chunk works.

I'm currently using knitr 1.13, R 3.3.0 and RStudio 0.99.902, the latest versions available  (reproduced in both RStudio 0.99.982 and R 3.2.5). The error persists in R GUI, so I don't believe RStudio is involved in the error, error is at the knitr level. The error is not localised to one machine. I have a desktop machine, laptop and surface, all produce the same error. 

Thanks for writing the knitr package. It has changed my workflow dramatically and I love this package.

**Comment by jrwishart** [comment]
After further diagnosing, putting any code that produces numerical output inbetween the plot commands and the end of the chunk will produce another error saying the figure margins are too large.

In the meantime, I have downgraded to knitr 1.12 and the error has disappeared.

**Comment by jmichaelgilbert** [comment]
I too just experienced an error relating to `par()` settings. 
```
Quitting from lines 108-114 (422_Programming_Assignment_02.Rmd) 
Error in par(x) : invalid value specified for graphical parameter "fig"
Calls: <Anonymous> ... process_group.block -> call_block -> block_exec -> par2 -> par
In addition: Warning message:
In par(x) : calling par(new=TRUE) with no plot
Execution halted
```
Reproducible example is [here](https://raw.githubusercontent.com/jmichaelgilbert/mspaScripts/master/422_Programming_Assignment_02.Rmd) (apologies for the long length). This worked fine the last time I knit the document on 2016/04/13. This specifically seems to only happen with `corrplot()`. Previously I had to store the old par settings ex-ante with `par.old <- par()` and reload them ex-post with `par(par.old)`, which worked fine. No clue what's going on here - apologies is this is unrelated to {knitr} and/or this should be opened as a separate issue.

Michael

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
