### ISSUE TITLE
undefined highlight macro in python to (beamer) latex

### ISSUE THREAD

**Issue by conjugateprior** [yihui/knitr#1217]
I was trying to use knitr in the latest RStudio to compile an `.Rnw` file with
```
<<engine='python'>>=
print("%s" % ("a"))
@
```
in it. This generates latex containing 
```
\hlipl{\%s}
```
which will not then compile because `\hlipl` is not defined in the latex headers.  This expression *is* defined by the `highlight.sty` file that (latest version of) the python `highlight` package generates when it runs.  By default that file contains a line
```
\newcommand{\hlipl}[1]{\textcolor[rgb]{0.45,0.46,0.77}{#1}}
``` 
So a quick fix is to include that line in the header of the `.Rnw`. 

But it would be good not to have to do that.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
