### ISSUE TITLE
Options set in child document scope are not preserved

### ISSUE THREAD

**Issue by khughitt** [yihui/knitr#1219]
### Overview

`opts_chunk` settings specified in child knitr documents are not preserved when execution continues in the parent document.

### To reproduce

**parent.R**

```r
library(knitr)
knit('knitr_opts.Rmd')
opts_chunk$get('error')
```

**knit_opts.Rmd**

    ```{r}
    opts_chunk$set(error=FALSE)
    ```

**output**:

```sh
Rscript parent.R

processing file: knitr_opts.Rmd
  |.................................................................| 100%
label: unnamed-chunk-1

output file: knitr_opts.md

[1] "knitr_opts.md"
[1] TRUE
```
**Expected output**:

```sh
...
[1] FALSE
```

### System info

Using the latest version of knitr from Github.

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] knitr_1.13.1

loaded via a namespace (and not attached):
[1] magrittr_1.5  tools_3.3.0   stringi_1.1.1 methods_3.3.0 stringr_1.0.0
[6] evaluate_0.9 
```

### Related

1. https://groups.google.com/forum/#!topic/knitr/_I5rlo9tOeA (appears to be regression bug)

**Comment by yihui** [comment]
It seems you were not knitting knit_opts.Rmd as a child document of another Rmd document, e.g. you should have a parent.Rmd that sets the `child` option:

    ```{r child='knit_opts.Rmd'}

**Comment by khughitt** [comment]
Ah okay. I had assumed that because knitted documents were executes in the same environment as the parent script (i.e. variables set in `child.Rmd` above could be references in `parent.R` after knitting), that options would behave the same.

Thanks for the clarification!

**Comment by khughitt** [comment]
@yihui Sorry to rehash this old issue, but do you know if there is any way I might be able to call `knit_child` interactively, or achieve a similar effect?

Nvim-R currently uses [knit instead of knit_child](https://github.com/khughitt/Nvim-R/blob/master/R/common_global.vim#L1680) when executing a child document interactively, so the behavior is not consistent compared to knitting the entire document.

I tried just dropping in `knit_child` directly, but since it's [not actually meant to be called interactively](https://stackoverflow.com/questions/16827788/knitr-child-throws-error-after-upgrade-to-r-3-0), that didn't work, either.

Any thoughts?
