### ISSUE TITLE
knitr does not handle UTF-16

### ISSUE THREAD

**Issue by andrechalom** [yihui/knitr#1220]
Hi!

I'm working on a R package named [Rsampling](https://github.com/lageIBUSP/Rsampling), and one of our vignettes was not being built by knitr 1.13 (R 3.3.0, Linux Ubuntu 14). 

Invocating knitr explicitly seems to work:

```r
> knit(input='vignettes/RRRe.Rmd', output='inst/doc/RRRe.md')


processing file: vignettes/RRRe.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: inst/doc/RRRe.md
```
But the output file is just garbage.

Trying to build the vignettes from devtools gave this non-related error:

```r
> devtools::buildvignettes()
(...) # other vignettes build just fine!
Warning message:
In tools::buildVignettes(dir = pkg$path, tangle = TRUE) :
  Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/RRRe.Rmd’
(Is a VignetteBuilder field missing?)
```

Turns out this file was encoded as UTF-16. I don't know if knitr *should* accept UTF-16, but maybe it could check for a non-supported encoding instead of just failing?

**Comment by yihui** [comment]
Is there a particular reason that you want to use UTF-16 instead of UTF-8?

I see you declared the encoding as UTF-8 by using `\usepackage[utf8]{inputenc}` in `vignettes/RRRe.Rmd`. If you must use UTF-16, you should use this instead:

```
  %\VignetteEncoding{UTF-16}
```

**Comment by andrechalom** [comment]
No, the file was encoded in UTF-16 by accident. The problem here is that it
took me a handful of hours to notice that the file encoding was causing
this seemingly unrelated error. I believe that the knitr package might
check the encoding of the incoming files to prevent this problem.

**Comment by yihui** [comment]
Unfortunately there is no reliable way to detect the file encoding, otherwise there is no need for users to specify the encoding.
