### ISSUE TITLE
R package structure block chunk cache functionnality

### ISSUE THREAD

**Issue by sylvainschmitt** [yihui/knitr#1226]
Hello,

I discover an issue that I can't explain with `knitr` cache for chunks. If I compile your cache example [https://raw.githubusercontent.com/yihui/knitr-examples/master/056-huge-plot.Rmd](url) in any classic folder it works perfectly. But as soon as I compile the example in a *vignettes* folder inside a R package project, the cache is updated at each run even if the code doesn't change. So in conclusion it render the cache option unusable inside a package. 

The only solution I got for the moment is to work on my vignette outside from the package structure, and to copy paste the new vignette inside the package whenever I want to save my changes.

I think it may be linked to some automatic procedure affecting the files inside a package structure due to R-studio. I tried both in a package with a git repository or without git and the conclusion is git is not responsible for this. Last thing I noticed that outside from a package a folder *Example_files* is created in addition of *Example_cache* but not inside a package structure. So does that mean that the package structure is blocking the file cache, and that's why the cache option doesn't work ?

Thanks for your time and your great package

**Comment by yihui** [comment]
This might have something to do with RStudio, since RStudio does have certain different treatment to vignettes. I just tried `cache=TRUE` to a random vignette in my package, and it worked fine -- the Example_cache folder was not deleted. If your version of RStudio is not the latest, you can probably try to upgrade.

**Comment by sylvainschmitt** [comment]
Hello,

I was effectively with R-studio version 0.99.896 and I updated with the 0.99.902 (released yesterday), and now the cache of your example is working. I just have to struggle to update my old package and it should be okay.

Thank you for having looked at it,

Sylvain

**Comment by dhagmann** [comment]
I have the same problem with RStudio  0.99.902. The folder "Example_cache" does not get deleted irrespective of where I compile the html document, but "Example_files" and "Example.html" are not created in the vignettes folder. 

When I first compile outside of vignettes, then move all the files into the vignettes folder, they do not get deleted -- but knitr still doesn't load the cache.

**Comment by tdsmith** [comment]
I'm having trouble making this work. https://support.rstudio.com/hc/en-us/community/posts/213681008-Vignette-chunks-can-t-be-cached-

I have current versions of everything; session_info() follows:

```
Session info ----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-08-21                  
```

<details>
<summary>Packages</summary>
```
 package    * version date       source        
 assertthat   0.1     2013-12-06 CRAN (R 3.3.0)
 colorspace   1.2-6   2015-03-11 CRAN (R 3.3.0)
 curl         1.2     2016-08-13 CRAN (R 3.3.1)
 DBI          0.5     2016-08-11 CRAN (R 3.3.1)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 dplyr      * 0.5.0   2016-06-24 CRAN (R 3.3.1)
 evaluate     0.9     2016-04-29 CRAN (R 3.3.0)
 ggplot2    * 2.1.0   2016-03-01 CRAN (R 3.3.0)
 gridExtra    2.2.1   2016-02-29 CRAN (R 3.3.0)
 gtable       0.2.0   2016-02-26 CRAN (R 3.3.0)
 HomebrewGA * 0.1.0   2016-08-21 local         
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.0)
 httr         1.2.1   2016-07-03 CRAN (R 3.3.1)
 jsonlite     1.0     2016-07-01 CRAN (R 3.3.1)
 knitr        1.14    2016-08-13 CRAN (R 3.3.1)
 lazyeval     0.2.0   2016-06-12 CRAN (R 3.3.1)
 lubridate    1.5.6   2016-04-06 CRAN (R 3.3.1)
 magrittr   * 1.5     2014-11-22 CRAN (R 3.3.0)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.0)
 munsell      0.4.3   2016-02-13 CRAN (R 3.3.0)
 openssl      0.9.4   2016-05-25 CRAN (R 3.3.1)
 plyr         1.8.4   2016-06-08 CRAN (R 3.3.1)
 R6           2.1.3   2016-08-19 CRAN (R 3.3.1)
 Rcpp         0.12.6  2016-07-19 CRAN (R 3.3.1)
 reshape2   * 1.4.1   2014-12-06 CRAN (R 3.3.0)
 RGA          0.4.2   2016-04-08 CRAN (R 3.3.1)
 rmarkdown    1.0     2016-07-08 CRAN (R 3.3.1)
 rsconnect    0.4.3   2016-05-02 CRAN (R 3.3.1)
 scales       0.4.0   2016-02-26 CRAN (R 3.3.0)
 stringi      1.1.1   2016-05-27 CRAN (R 3.3.1)
 stringr      1.1.0   2016-08-19 CRAN (R 3.3.1)
 tibble       1.1     2016-07-04 CRAN (R 3.3.1)
 viridis    * 0.3.4   2016-03-12 CRAN (R 3.3.0)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)
 yaml         2.1.13  2014-06-12 CRAN (R 3.3.0)
```
</details>

**Comment by callum-webb** [comment]
Hi there,

I also appear to be having this issue, cached chunks are always rebuilt when the .Rmd file is placed in the vignettes folder of a package and I use the Knit button in Rstudio. 

I create a new package `devtools::create("foo")`, then after opening the project, create a new vignette `devtools::use_vignette("bar")`.

Then I make bar.Rmd look like:

    ---
    title: "Vignette Title"
    author: "Vignette Author"
    date: "`r Sys.Date()`"
    output: rmarkdown::html_vignette
    vignette: >
      %\VignetteIndexEntry{Vignette Title}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}
    ---

    ```{r foobar, cache = TRUE}
    woop <- 1
    ```

Whenever I use the Knit button above the code pane, I can see the cache for the foobar chunk, but the hash changes every time.

I suspect this is an Rstudio thing, because I get the correct behaviour if I:

-  Use `rmarkdown::render("vignettes/bar.Rmd")`, or;
-  Use the Knit button, but not have the *foo* project open.

I'm using Rstudio Version 1.0.136, and my sessionInfo() looks like

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] backports_1.0.4  magrittr_1.5     rprojroot_1.1    htmltools_0.3.5  tools_3.3.2      withr_1.0.2     
 [7] yaml_2.1.14      memoise_1.0.0    Rcpp_0.12.8      codetools_0.2-15 stringi_1.1.2    rmarkdown_1.3   
[13] knitr_1.15.1     stringr_1.1.0    digest_0.6.10    devtools_1.12.0  evaluate_0.10 
```

This is my first post on an issue, please let me know if you require any additional information.

**Comment by olangfor** [comment]
Hi,

I've been searching for the same issue.  Was there a conclusion to this?

**Comment by leerichardson** [comment]
I still have this issue, even after upgrading to R studio, version: 1.2.1335

**Comment by rasenior** [comment]
I'm also having this issue on Version 1.2.1335

**Comment by yihui** [comment]
As I said in the beginning, this is very likely to be an RStudio IDE issue. If it is still present in the current version of RStudio, please file an issue to https://github.com/rstudio/rstudio/issues (with a minimal reproducible example, ideally as a zip archive of a minimal R package). Thanks!
