### ISSUE TITLE
render_jekyll() turns leaflet widgets into png files

### ISSUE THREAD

**Issue by cigrainger** [yihui/knitr#1228]
I'm not sure I understand what's going on with this one. Some htmlwidgets still work but Leaflet will automatically output as a screenshot using webshot. This seems to be new, as this is a working example where render_jekyll() produced the correct output for leaflet: https://github.com/brendan-r/knitr-jekyll.

**Comment by yihui** [comment]
You can set the chunk option `screenshot.force = FALSE` to disable the automatic screenshots. This is a new feature in knitr 1.13: https://github.com/yihui/knitr/blob/master/NEWS.md

**Comment by cigrainger** [comment]
This was it! Thanks!
