### ISSUE TITLE
knitr doesn't always handle % properly

### ISSUE THREAD

**Issue by dmurdoch** [yihui/knitr#1229]
I'm writing a solutions manual for a text.  Some parts of it should only be visible to the instructor, so I define a macro to hide those parts when I'm building the student version.  However, if those parts contain code chunks that use %, it fails.  For example:

    \documentclass{article}
    \newcommand{\instructor}[1]{}
    \begin{document}
    Everyone sees this:
    <<eval = FALSE>>=
    1 %% 2
    @
    \instructor{
    Only the instructor sees this.
    <<eval = FALSE>>=
    1 %% 2  # 1 + 2 would be okay
    @
    }
    \end{document}

Running this through knitr then trying to Latex it gives this error:

    Runaway argument?
    { Only the instructor sees this. \begin {knitrout} \definecolor {shad\ETC.
    ! File ended while scanning use of \instructor.

Here's what knitr generated:

    \instructor{
    Only the instructor sees this.
    \begin{knitrout}
    \definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{alltt}
    \hlnum{1} \hlopt{%%} \hlnum{2} \hlcom{# 1 + 2 would be okay}
    \end{alltt}
    \end{kframe}
    \end{knitrout}
    }

As the comment says, this depends on having a % sign in the code.  Is this a bug in the code generated by knitr, or is it a problem with the way I'm hiding that text?  Is there a better way to hide text?

**Comment by dmurdoch** [comment]
I think this is more of a LaTeX issue than a knitr issue.  I have a workaround (described here:  http://tex.stackexchange.com/questions/315835/a-macro-that-processes-and-hides-text), but no very clean solution yet.

**Comment by yihui** [comment]
Yeah that does sound like a LaTeX question.
