### ISSUE TITLE
Figure labels and figure environment not working in Rmarkdown -> pdf

### ISSUE THREAD

**Issue by hughjonesd** [yihui/knitr#1230]
Using knitr version 1.13.1, installed from github, the following document fails to create a figure environment with caption and label:

    ---
    title: "Untitled"
    output: 
      pdf_document:
        fig_caption: yes
    ---
    
    Figure \ref{fig:pressure}.
    
    
    ```{r pressure, echo=FALSE, fig.caption='CAPTION',  fig.env='figure'}
    
    plot(pressure)
    
    ```
    
    
    Some more text.

pandoc version:
1.15.2
Compiled with texmath 0.8.4, highlighting-kate 0.6.
R version 3.2.1

**Comment by hughjonesd** [comment]
Pandoc version:
pandoc 1.15.2
Compiled with texmath 0.8.4, highlighting-kate 0.6.

**Comment by yihui** [comment]
I don't think this ever worked for R Markdown before. You may try the bookdown package (https://bookdown.org), and the output format `bookdown::pdf_document2`. Also change `\ref{fig:pressure}` to `\@ref(fig:pressure)`.

**Comment by hughjonesd** [comment]
Hmm, but surely the figure caption should work even if the label does not? It seems quite standard, or am I misunderstanding something?

**Comment by yihui** [comment]
The figure caption should work, but the chunk option is `fig.cap` instead of `fig.caption`.
