### ISSUE TITLE
knitr/pandoc: Can't change the template in markdown YAML header

### ISSUE THREAD

**Issue by friendly** [yihui/knitr#1231]
This was filed as a `pandoc` issue, https://github.com/jgm/pandoc/issues/2997, and I was requested to move it to `knitr`. The problem is described in detail in http://stackoverflow.com/questions/37978637/knitr-pandoc-article-template-supporting-keywords-and-linespacing/

Briefly, I get latex errors if I try to use a latex template other than the version provided in the `rmarkdown` package, even if I try to specify an exact local copy of the `default-1.15.2.tex` file.

Is there some way I can track this down further? I think I am unable to upgrade to a later version of pandoc, because R Studio and rmarkdown are set up to use their own copy of pandoc.exe.

**Comment by yihui** [comment]
For the error message

```
! Undefined control sequence.
l.527 {\centering \includegraphics
```

you can probably add `graphics: yes` to YAML.

For the Pandoc version, you can either upgrade RStudio http://www.rstudio.com/products/rstudio/download/preview/, or install your own version of Pandoc. RStudio will just pick the highest version of Pandoc that it can find.

It seems you didn't provide the error message from using default-1.15.2.tex.

**Comment by friendly** [comment]
Thanks, Yihui -- good suggestions.
The error message was exactly the same.
