### ISSUE TITLE
Hardcoded dependency version for libicui18n (and others)?

### ISSUE THREAD

**Issue by NathanDeckinga** [yihui/knitr#1232]
I had R Studio all up and working properly including being able to knit output files and then I went ahead and upgraded to Fedora 24. Apparently that upgraded 3 files from version 54 to version 56 that knitr required. It looks like it wasn't universally required at version 54 as other shared libraries were also upgraded to version 56 and that worked perfectly. As it stands right now, when I run

    install.packages("knitr")
I get an output of:

    * installing *source* package ‘knitr’ ...
    ** package ‘knitr’ successfully unpacked and MD5 sums checked
    ** R
    ** demo
    ** inst
    ** preparing package for lazy loading
    Error in dyn.load(file, DLLpath = DLLpath, ...) : 
      unable to load shared object '/home/nathan/R/x86_64-redhat-linux-gnu-        library/3.3/stringi/libs/stringi.so':
      libicui18n.so.54: cannot open shared object file: No such file or directory
    Error : unable to load R code in package ‘knitr’
    ERROR: lazy loading failed for package ‘knitr’
    * removing ‘/home/nathan/R/x86_64-redhat-linux-gnu-library/3.3/knitr’
    Warning in install.packages :
      installation of package ‘knitr’ had non-zero exit status
Checking a bit deeper and running:

    R CMD ldd /home/nathan/R/x86_64-redhat-linux-gnu-library/3.3/stringi/libs/stringi.so
Leaves me with just 3 libraries that it can't find.

    libicui18n.so.54 => not found
    libicuuc.so.54 => not found
    libicudata.so.54 => not found
Version 56 of all 3 of those live in /usr/lib64 and that's where R expects them to be. It just hard coded the .54 on there instead of accepting anything and linking to the plain .so

Now for my question. Ideally, knitr would be able to use the updated versions. Is there any way to force that? Or do I need an update to the knitr package on cran first? What other options do I have?

I have removed and attempted to reinstall knitr.  I have updated all packages.

Thanks!

**Comment by yihui** [comment]
I think you need to reinstall the stringi package.

**Comment by NathanDeckinga** [comment]
You were absolutely right.  Thank you for the help and I'm sorry for the false alarm.

**Comment by thomasWeise** [comment]
Reinstalling `stringi` just helped me when I tried to install `roxygen2` on `R` 3.4 after I got `libicui18n.so.57` not found error:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/stringi/libs/stringi.so':
  libicui18n.so.57: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘roxygen2’
```
