### ISSUE TITLE
knitr issue

### ISSUE THREAD

**Issue by fischm67** [yihui/knitr#1233]
Hello.  This is my first time posting on this board.  Please let me know if I don't follow the protocols for posting a question.  I have been using Rstudio and knitr for at least 1.5 years and have never encountered this issue previously.  I was creating a Rmd file to knitr to html.  The code in included below in my GitHub repository.

https://github.com/fischm67/machine_learning/blob/gh-pages/final_project.Rmd

Up to code chunk 3 everything processes through.  At line 73, I get the following error:

Quitting from lines 56-80 (final_project.Rmd) 
Error in subset.default(training, select = names(training)[1:52]) : 
argument "subset" is missing, with no default
Calls: <Anonymous> ... withVisible -> eval -> eval -> subset -> subset.default
Execution halted

I can get this same piece of code to work within the console.  Throughout the evening I also was dealing with an issue where I would call the following code:

training   <- training[, -(1:7)]

Training is a data.frame, and instead of just removing the first seven columns of the data frame, it would turn training into a integer vector with 1 thru 7.  I would then restart R within the session and the same piece of code would work as expected.  I also recently updated to the latest versions of Rstudio and R.  If there is anything you can suggest to help fix this issue please let me know.  I was working on this issue instead of my project all day and night.  I have included my session information below.

               Regards, Mark Fischer

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] htmltools_0.3.5 tools_3.3.1 yaml_2.1.13 Rcpp_0.12.5 rmarkdown_0.9.6 digest_0.6.9 
>

**Comment by fischm67** [comment]
When commenting out the aforementioned lines above:
cor_train <- subset(training, select = names(training)[1:52])
cols_cor  <- findCorrelation(abs(cor(cor_train)),0.90)

You would then get to line 
training  <- training[, -c(1,8,9,10,18)]
with error:
Quitting from lines 56-80 (final_project.Rmd) 
Error in training[, -c(1, 8, 9, 10, 18)] : incorrect number of dimensions
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted

It seems like my installation of Rstudio, knitr, and R has been corrupted.  I'm able to get all of the code to execute correctly in the console window.

**Comment by yihui** [comment]
I don't think this is a knitr issue (I can reproduce it without using knitr). It looks like your misuse of data.table. This line

```r
training   <- training[, -(1:7)]
```

turned `training` into an integer vector (-1 to -7). A data.table object is very different with a normal data frame in terms of indexing in the square bracket.

**Comment by fischm67** [comment]
Yihui,
    I wanted to thank you for taking the time to answer my question. I know you probably receive too many questions like this and I really appreciate your effort to answer it. I was using fread to read in my data which will coerce it to a data.table. My code is working now.
           Thanks and Regards,
            Mark Fischer
