### ISSUE TITLE
Editing R code from *.lyx files in RStudio

### ISSUE THREAD

**Issue by sebastiangerdes** [yihui/knitr#1234]
Dear Yihui,
I greatly enjoy your knitr package, I think it is awesome. In the earlier stages of a project, I use a markdown document in RStudio. When the work becomes more collaborative, we switch to lyx. However, editing of R code in lyx is not as convenient as it is in RStudio.
If the chunks were stored in lyx using the former sweave syntax (example below), it would be possible to conveniently edit the R code within RStudio by opening the *.lyx file in RStudio and setting the file type to R Sweave.

<<Chunkname>>=
x <- 1
@

If the coding, for which RStudio is more convenient, is finished the writing of text passages could be continued in lyx.

What do you think about this idea? 

Another option might be to introduce a *.lyx file type in RStudio that recognizes chunks in *.lyx files and treats the rest of the lyx document as plain text, so that it can be edited in lyx again afterwards. 

I hope, I made myself understandable!
Thanks and best greetings,
Sebastian

**Comment by yihui** [comment]
Hi Sebastian, I don't think it is possible for RStudio to be able to edit LyX files directly, but you may take a look at this page for another idea: http://yihui.name/knitr/demo/externalization/
