### ISSUE TITLE
dev.args have no effect if cairo_pdf is used as recording device

### ISSUE THREAD

**Issue by ilia-kats** [yihui/knitr#1235]
If I set
```
options(device = function(file, width = 7, height = 7, ...) {
        cairo_pdf(tempfile(), width = width, height = height, ...)
    })
```
in the setup chunk, dev.args have no effect on any plots. As far as I understand, this is because dev.args are only passed to a couple of selected devices in ```chunk_device```, however, according to the R manual for ```dev.control```, things like background color (and presumably point size, as this is also not working for me) are part of what's copied. Therefore, the actual plot in ```plot2dev``` will have the default dev.args instead of user-specified ones.

**Comment by yihui** [comment]
I think you are correct, but why not simply `dev = 'cairo_pdf'`?

**Comment by ilia-kats** [comment]
This I also do, but I have unicode symbols in plot labels and if I use the default PDF device for plot recurding, my chunk output is full of
```
Warning in title(ylab=...): conversion failure on '...' in 'mbcsToSbcs': dot substituted for <ce>
```

**Comment by yihui** [comment]
Yes, if you use the default `dev = 'pdf'`, you will see these warnings, but I was saying `dev = 'cairo_pdf'`. Does that also trigger these warnings?

**Comment by ilia-kats** [comment]
Yes, it does, that's what I was trying to say. Here's a minimal example:
```
\documentclass[a4paper,12pt,notitlepage]{report}

\begin{document}
test plot:
<<results='markup', dev='cairo_pdf', fig.path='plots/', cache.path='cache/'>>=
    plot(1:10, xlab="Δ")
@

\end{document}
```

**Comment by yihui** [comment]
You should be able to use `dev = 'cairo_pdf'` now.
