### ISSUE TITLE
Method to display verbatim knitr/R Markdown chunks with syntax highlighting?

### ISSUE THREAD

**Issue by garrettgman** [yihui/knitr#1237]
Yihui,

@jennybc and I are looking for a way to insert verbatim knitr or rmarkdown chunks into a document for teaching purposes. The chunks should appear verbatim in the final output without being run, along with their surrounding back ticks and chunk options. And, most importantly, the chunks should appear with knitr or rmarkdown specific syntax highlighting.

We've worked out a few hacks to get chunks into a document, but we can't yet get syntax highlighting. Here's my latest attempt as an almost reproducible example:

Step 1. Save a chunk as its own .Rmd file, e.g. save the below as `example-chunk.Rmd`

````
    ```{r cars}
    summary(cars)
    ```
````

Step 2. Insert it into another .Rmd file with `cat(htmltools::includeText())`

````
    ---
    title: "My new document"
    ---
    
    An R Markdown chunk looks like this:
    
    ```{r echo = FALSE, comment = ""}
    cat(htmltools::includeText("example-chunk.Rmd"))
    ```
````

<img width="578" alt="screen shot 2016-07-06 at 10 54 03 am" src="https://cloud.githubusercontent.com/assets/85014/16622511/6e8ea5a6-4368-11e6-9f40-4da0964ee1fe.png">

**Comment by yihui** [comment]
Syntax highlighting is unlikely to work very well for a raw code chunk, since it is not valid R code (I mean the chunk header and footer). FAQ 8 (http://bit.ly/knitr-faq) showed how to write verbatim code chunks, and if you want syntax highlighting, you can wrap the verbatim chunk in another code block, e.g.

    ````r
    `r ''````{r cars}
    x = 1:12
    summary(cars)
    "A string."
    ```
    ````

Syntax highlighting won't work for ````` ````r `````, since a pair of backticks means a variable name in R (the whole chunk will simply be black). You can randomly try other language names, e.g.

    ````python
    `r ''````{r cars}
    x = 1:12
    summary(cars)
    "A string."
    ```
    ````

I don't know what backticks mean in python, but it seems at least the numbers and strings are highlighted in HTML output.

**Comment by garrettgman** [comment]
Thank you Yihui. FAQ 8 is very helpful.
