### ISSUE TITLE
rstudio preview .99.1246 and knitr 

### ISSUE THREAD

**Issue by dschneiderch** [yihui/knitr#1238]
It seems that kniting a document in the latest rstudio preview doesn't respect root.dir- I have the following in a setup chunk:
    
    knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

I installed knitr 1.12, 1.12.3 and 1.13 and I always have this problem with the 0.99.1246 preview of rstudio.  I downgraded rstudio to the latest stable and rmarkdown files work fine with all 3 versions of knitr so I suspect this is an rstudio problem but thought i'd post here too.

i'm on osx 10.11.5, using MRAN 3.2.4

**Comment by yihui** [comment]
I cannot reproduce this issue. Could you provide a minimal, self-contained, and reproducible example? (Ideally a Github repo or a zip file of your RStudio project)

**Comment by dschneiderch** [comment]
hmmm, I think I was confusing "knitting" with "run all chunks".

knitting works fine, but with run all chunks, the working directory defaults to the script location

here is an example project: https://www.odrive.com/s/ee6c4923-a6d0-47af-b094-e113b354cc11-577e74c6

**Comment by yihui** [comment]
Unfortunately "running all chunks" is indeed different with "knitting" here. It is simply a call to `source()`, which ignores all knitr options.
