### ISSUE TITLE
knitr claims error reading/processing Rmarkdown, but output is OK

### ISSUE THREAD

**Issue by rgayler** [yihui/knitr#1245]
I am processing an Rmarkdown document in RStudio (V 0.99.1246).

The document is knitted OK and the output is as I expect it, but I get error messages like the following in the console window:

    Quitting from lines 113-118 (some_file.Rmd) 
    Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
      non-numeric argument to binary operator
    In addition: Warning message:
    In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
      EOF within quoted string

The fact that I always got the expected outcome means that whatever was `quitting` didn't affect the overall process.

I tried inserting a `knitr_exit()` code chunk at various places in my code and the line numbers of the error message changed - so it doesn't appear to be objecting to any specific piece of my code.

Also, I am not directly calling `scan` - I wonder whether this is from knitr trying to read the code chunk.

This Rmd file has been used as a source for the new RStudio notebook feature. Perhaps the error comes from an interaction with that.

My output is OK, but I don't like seeing error messages because it makes me wonder whether there is something broken that I don't see

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example?

**Comment by rgayler** [comment]
Sorry, I can't. The error message has gone away without me touching
anything near the line numbers appearing in the error message.

I spent some time trying to pin down the problem before I submitted the
issue - but whenever I commented out some lines of my code or inserted a
knitr_exit() chunk, the line numbers referenced in the error message would
change. I got the impression that the problem wasn't any specific lines in
my code but something in the way knitr was reading the whole file that was
sensitive to the entire input file.

As I said, the weird thing was that the error message said something was
quitting, but the output was exactly as expected - so I have no idea what,
if anything, quit.

Ross

**Comment by yihui** [comment]
Yeah that is really weird. One thing you can try next time is to knit the document in an interactive R session, so you can check `traceback()` to see where the error really comes from:

```r
knitr::knit('some_file.Rmd')
traceback()  # if error occurred during knit()
```

**Comment by rgayler** [comment]
Thanks. I'll do that if anything like that ever happens again.
