### ISSUE TITLE
opts_knit() to change self.contained

### ISSUE THREAD

**Issue by filipsch** [yihui/knitr#1246]
The following R Markdown file

    ---
    title: "Example Document"
    author: "Your name here"
    output: html_document
    ---
    
    ```{r}
    knitr::opts_knit$set(self.contained = FALSE)
    ```
    
    This is my doc
    
    ```{r}
    a <- 2
    ```
    
renders an HTML file when knitting that is self contained:

  <!DOCTYPE html>
    
    <html xmlns="http://www.w3.org/1999/xhtml">
    
    <head>
    
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />
    
    
    <meta name="author" content="Your name here" />
    
    
    <title>Example Document</title>
    
    <script src="data:application/x-javascript;base64,LyohIGpRdW...

However, I'd expect a HTML file where the script tags simply refer to external resources.

Thanks!

**Comment by yihui** [comment]
This option does not apply to R Markdown documents. It is for Rnw and Rhtml documents only. For Rmd documents, please see documentation at http://rmarkdown.rstudio.com/html_document_format.html
