### ISSUE TITLE
pandoc.exe openBinaryFile: permission denied

### ISSUE THREAD

**Issue by adeldaoud** [yihui/knitr#1248]
Hi

I am trying to run the following Rmarkdown code via knitr in Rstudio:

``````

---
title: "Regression table test"
output: pdf_document
header-includes:
   - \usepackage{longtable}

---

```{r, results='asis'}
library("texreg")
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl", "Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
texreg(lm.D9, use.packages = FALSE, longtable = TRUE)
```
``````

But I am getting the following error:

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS RegressionTest.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output RegressionTest.pdf --template "C:\Users\ADELDA~1\DOCUME~1\R\WIN-LI~1\3.3\RMARKD~1\rmd\latex\DEFAUL~2.TEX" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" 
pandoc.exe: RegressionTest.pdf: openBinaryFile: permission denied (Permission denied)
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS RegressionTest.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output RegressionTest.pdf --template "C:\Users\ADELDA~1\DOCUME~1\R\WIN-LI~1\3.3\RMARKD~1\rmd\latex\DEFAUL~2.TEX" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 1 
Execution halted

Any ideas what is going on? I am able to run the same code in Latex with Knitr. Not sure what is going on.

Thanks for the input

**Comment by yihui** [comment]
Sorry I have no idea. Are you using the latest version of RStudio? Are you compiling the document on a network drive?

**Comment by adeldaoud** [comment]
Thanks for the hint; I am working on a network drive (OneDrive). It works when I moved it to the local drive. 

Do you know if I can give the R-markdown mechanism permission to work on a network drive? I do not get the same permission error when processing the same document but in Latex.

**Comment by yihui** [comment]
I have see a few issues like this due to network drives in the past, but I have no idea whether this is a Pandoc issue or an R Markdown issue (unlikely to be relevant to knitr, though). Not sure if @jjallaire or @jmcphers has any ideas.

**Comment by jmcphers** [comment]
It sounds like Pandoc is not able to open the output pdf. This could happen for a variety of reasons but my guess is it's one of these:

1. Permissions issue on the OneDrive folder
2. OneDrive itself locking the file (for instance, to sync it) 

Anecdotally, I use OneDrive occasionally myself and have often had permissions problems (wherein ordinary user programs claim they can't write files into OneDrive folders) so I'd suspect the first.

**Comment by adeldaoud** [comment]
Thanks for the reply. It is probably alternative one since I can compile a latex version of the document (but not a R markdown version).

 Is there a workaround that would still allow me to work in OneDrive?  We have an organization license which we use in our research team.

**Comment by yihui** [comment]
I'm closing this issue since it is not directly related to knitr, and I don't know a solution, either. Sorry.

**Comment by pelld** [comment]
I just got this issue which was resolved by closing the document.
