### ISSUE TITLE
Latex "small" captions with math

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#1249]
In https://github.com/yihui/knitr/blob/c3085229f5a02506e40f21c1cecf6d8448f5caaa/R/hooks-latex.R#L120, "list of figures" captions are generated from captions by removing everything that follows one of the `$`, `:`, `.`, `;` characters.
Is there a reason for the presence of `$` in that list?
I have a caption with `log$_2$` which gets cut in the middle of the sentence...
(I know I could use `fig.scap` but I'd rather not ;-) )

**Comment by knokknok** [comment]
Also, if `$` gets removed, what about requiring a space after the symbol?
```
scap = strsplit(cap, '[:.;] ')[[1L]][1L]
```

**Comment by yihui** [comment]
I don't remember the reason about `$`, but I agree requiring a space is more reasonable.

**Comment by knokknok** [comment]
In https://github.com/yihui/knitr/commit/8094932c5b504ae2edf4c21e7a9f09ba9a593723 you wrote "added $ as a new possible separator for short captions, because of $1.23$".
But I'm not sure what the issue is...
May be it was because the number was cut after `1`which would be fixed by requiring the space?

**Comment by yihui** [comment]
Yes, you are right.
