### ISSUE TITLE
Entering % in fig.cap causes LaTeX error when Knitting

### ISSUE THREAD

**Issue by ismayc** [yihui/knitr#1251]
With % corresponding to a comment in LaTeX when users enter a % in the `fig.cap` string, a LaTeX compilation error is created when Knitting to PDF and this is often difficult for students to decipher when they don't have LaTeX experience.  If there a way that I could create a check on the values entered after `fig.cap =` to ensure that no % or other LaTeX symbols are entered there.  I'm happy to create my own knitr option as well, but I'm not quite sure where to start.

**Comment by yihui** [comment]
You could pass the caption to ` knitr:::escape_latex()` to make sure all special characters are escaped.

**Comment by ismayc** [comment]
Thanks!  I completely overlooked that when I was reading through your Dynamic Documents book.

**Comment by yihui** [comment]
I didn't export this function, and that why the triple colons `:::`. I guess I mentioned this function only once in the book, so I'm not surprised that you didn't notice it.
