### ISSUE TITLE
multiple captions for multiple tables per chunk

### ISSUE THREAD

**Issue by luccapavan** [yihui/knitr#1253]
With just one kable command, knitr generates 3 tables, so i need 3 captions in the same kable argument. How I can do this?

**Comment by yihui** [comment]
Could you provide a minimal example?

**Comment by luccapavan** [comment]
I use the chunk...

```{r stat}
library(BMR)
library(knitr)
stat <- stationarity(rdatapk2[,2:5], 4, 8)
kable(stat, caption = "Stationarity", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2, )
```
and the output is one table for KPSS test, another table for ADF test, and the last for Bayesian Information Criterion. Unfortunately, kable only do one caption. I need three captions for these tables.

**Comment by yihui** [comment]
The example is not minimal. What is BMR? It is not a package on CRAN. I don't know the data structure of `stat`, but the worst case is you call `kable()` three times with different input and captions.

**Comment by luccapavan** [comment]
Thanks, I use three times kable() for stas$KPSS, stats$ADF, stats$ADFlags ans works...
