### ISSUE TITLE
Figure width in %

### ISSUE THREAD

**Issue by ikashnitsky** [yihui/knitr#1255]
I'd like to set the width of the figures in html output in %, relative to the page/screen width. The height should then be adjusted in line with the `aspect.ratio` (`ggplot2`) parameter. Is it possible to implement the feature in `fig.width` parameter?

Currenly, according to the [options manual](http://yihui.name/knitr/options/), inches is the only option: "fig.width, fig.height: (both are 7; numeric) width and height of the plot, to be used in the graphics device (in inches) and have to be numeric".

**Comment by yihui** [comment]
fig.width/fig.height are for the physical size of figures (passed to graphical devices), and you can use `out.width = 'x%'` if you want to set the width in the output.

**Comment by ikashnitsky** [comment]
Ah, that's interesting. I could not find a relevant explanation elsewhere. Thanks a lot!

**Comment by yihui** [comment]
It was not documented on the knitr website, and I just added the documentation.
