### ISSUE TITLE
knitr include_graphics doesn't work in loop

### ISSUE THREAD

**Issue by mlayton20** [yihui/knitr#1260]
Hi,

I'm trying to add images and tables in a for loop. I found the fix for kable by surrounding command with print(), but this doesn't work on images. For images, it just outputs the below.

**Output**
```
[image is correctly shown here]
[1] “path\\to\\image\\map-legend.jpg” attr(,“class”) [1] “knit_image_paths” “knit_asis”
```

You can replicate the issue by creating a .Rmd file that has the following code. All you need to do is replace the image variable from "path\\to\\image\\map-legend.jpg" to the path to any image on your machine. You also need to add the back ticks where I've put £.

**markdown.Rmd**

```
£££{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
£££
```

```
£££{r, results='asis', echo=FALSE}
#This works
image <- "path\\to\\image\\map-legend.jpg"
knitr::include_graphics(image)
cat("\n\n")
for (i in 1:1){
    #This doesnt work.
    print(knitr::include_graphics(image))
}
£££
```

**Comment by mlayton20** [comment]
This is still a knitr issue. But I've found a workaround to this issue. 

You essentially need to build the markdown image syntax manually, and not use the knitr package.

So replace:
`print(knitr::include_graphics(image))`

With:
`cat("![](",image,")")`

Full code:
```
£££{r, results='asis', echo=FALSE}
#This works
image <- "path\\to\\image\\map-legend.jpg"
knitr::include_graphics(image)
cat("\n\n")
for (i in 1:1){
    #This doesnt work.
    print(knitr::include_graphics(image))
    #This does work!
    cat("![](",image,")")
}
£££
```

**Comment by yihui** [comment]
If you don't need to control the size of images, yes, `![]()` is totally fine.

**Comment by majerus** [comment]
Yihui, any way to do this with include_graphics( )? I would like to control the image size.

**Comment by yihui** [comment]
@majerus Sorry but no: `include_graphics()` has to be used in top-level R expressions.

**Comment by anatolix** [comment]
@yihui why is the limitation like this and what is the best workaround in case I don't have file to include?

I currently trying to add several diagrams in cycle, code like this is works
`  images = list()

  for (gggg in 1:2) 
  { 
      diagram = "strict digraph rmarkdown{
        graph [layout = dot, rankdir = LR]
        
        node [shape = rectangle]
        
        A[label='A']
        B[label='B']
        A->B
      }
      "
      
      images[[length(images)+1]]=grViz(diagram=diagram)
  }

  images[[1]]
  images[[2]]
`
and like this is not 
`  images = list()

  for (gggg in 1:2) 
  { 
      diagram = "strict digraph rmarkdown{
        graph [layout = dot, rankdir = LR]
        
        node [shape = rectangle]
        
        A[label='A']
        B[label='B']
        A->B
      }
      "
      
      images[[length(images)+1]]=grViz(diagram=diagram)
  }

  images
`
