### ISSUE TITLE
a plain knit vignette engine?

### ISSUE THREAD

**Issue by eborgnine** [yihui/knitr#1263]
Hello.  I've created a 'plain' vignette engine which only calls knit, and leaves the rest of the creation of .html's and .pdf's to the Makefile.  A few things (beamer slides, biblatex+biber) are tidier in a Makefile than they would be compiling within R.  Would this warrant inclusion in the knitr package?

```
tools::vignetteEngine(
        'plainKnit', 
        weave=  function(file, ...) {
            # create a dummy .tex file so R CMD doesn't complain
            # make will discover that the .md file is newer and overwrite
            texFile = gsub("\\.[Rr](md|nw)$", ".tex", file)
            file.create(texFile)
            knitr::knit(input=file, ...)
        },
        tangle = knitr::purl, 
        pattern = '\\.[Rr](md|nw)$',
        aspell = list(
                filter = knitr::knit_filter
        )
    )
```

the Makefile:

```
all: slides.pdf document.html

clean:
    rm -rf *.tex *.toc *.bbl *.blg *.aux *.out *.log *.spl *tikzDictionary *.md figure/ cache/ *.dvi *.4* *.css *.idv *.lg *.tmp *.xref *.gz my*.bib *.nav *.xml *.vrb *.snm 

%.md: %.Rmd
    R -e "knitr::knit('$<', '$@', encoding='UTF-8')" 

%.tex: %.md
    pandoc --standalone --smart --to=beamer --output=$@ $<

%.bcf: %.tex
    xelatex $<

%.bbl: %.bcf
    biber $<    

%.pdf: %.tex %.bbl
    xelatex -interaction=nonstopmode $<;
    xelatex -interaction=nonstopmode $<

%.html: %.md
    pandoc --standalone --filter=pandoc-citeproc --self-contained --output=$@ $<
```

**Comment by yihui** [comment]
I don't understand the point of `file.create()` creating the .tex file (sounds hackish to me), but I'm not against including a plain engine in this package.

**Comment by eborgnine** [comment]
R's expecting the vignette builder to create a .pdf or .html or .tex file, and complains if it doesn't find one.  This is done by `tools:::find_vignette_product`, part of which is below.  A better solution would be to specify `output='md'` with `tools::vignetteEngine`, I'll submit a request to R's bugzilla.


```
exts <- 	switch(by,
	       "weave" = if (final) c("pdf", "html") else c("pdf", "html", "tex"),
	       "tangle" = c("r", "s"),
	       "texi2pdf" = "pdf")
```

**Comment by eborgnine** [comment]
I'm creating a patch for R that will allow specifying output file extensions for vignette engines.  having output='md' allows the vignette engine to produce a .md file, and the Makefile does the conversion from md to either html or pdf.

Would you consider adding the following vignette engines to knitr?

```
	# basic knitr builder
	tools::vignetteEngine(
			'barebones', 
			weave= knitr::knit,
			tangle = knitr::purl, 
			pattern = "[.]([rRsS](nw|tex)|[Rr](md|html|rst))$",
			output = c('tex','md','html','rst'),
			aspell = list(
    	filter = knitr::knit_filter
			)
	)
	# spin goat's hair
	tools::vignetteEngine(
			'spin', 
			weave =	knitr::spin,
			tangle = invisible, 
			pattern = '[.][Rr]$'
	)
```

**Comment by yihui** [comment]
I'm not sure what the status is on this, but I think you probably do not really need my support, since any R package can register vignette engines. Closing now. Feel free to let me know if there are any functions you need me to export.
