### ISSUE TITLE
installing knitr from CRAN in R 3.0.3 failed

### ISSUE THREAD

**Issue by rnuske** [yihui/knitr#1269]
Installing knitr from CRAN failed in R 3.0.3, but the DESCRIPTION states knitr depends on R > 3.0.2 (see below for error message and seesionInfo)

BTW, Installing the release knitr_1.12.3 worked.

```
> install.packages('knitr')
Installing package into '/home/rnuske/R/x86_64-unknown-linux-gnu-library/3.0'
(as 'lib' is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'http://cloud.r-project.org/src/contrib/knitr_1.13.tar.gz'
Content type 'application/x-gzip' length 886610 bytes (865 Kb)
opened URL
==================================================
downloaded 865 Kb

* installing *source* package 'knitr' ...
** package 'knitr' successfully unpacked and MD5 sums checked
** R
** demo
** inst
** preparing package for lazy loading
** help
Error : /tmp/RtmpKnDFw1/R.INSTALL2e1b57780ba/knitr/man/knit_engines.Rd:35: .onLoad failed in loadNamespace() for 'knitr', details:
  call: tools::vignetteEngine(..., tangle = tangle, package = "knitr", 
  error: unused argument (aspell = list(filter = knit_filter))
ERROR: installing Rd objects failed for package 'knitr'
* removing '/home/rnuske/R/x86_64-unknown-linux-gnu-library/3.0/knitr'
* restoring previous '/home/rnuske/R/x86_64-unknown-linux-gnu-library/3.0/knitr'

The downloaded source packages are in
        '/tmp/RtmpUKB9bm/downloaded_packages'
Warning message:
In install.packages("knitr") :
  installation of package 'knitr' had non-zero exit status
```

```
> sessionInfo()
R version 3.0.3 (2014-03-06)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tcltk_3.0.3 tools_3.0.3
```

**Comment by yihui** [comment]
Thanks for the report. This is indeed a bug, but I don't remember which version of R added the `aspell` argument to `tools:: vignetteEngine` (didn't find it in R NEWS). I wonder if you have a particular reason for using a version of R that is more than two years old, though. If not, I'd strongly recommend you to upgrade.

**Comment by rnuske** [comment]
As far as I understood aspell was added tools::vignetteEngine in this [commit](https://github.com/wch/r-source/commit/7e0b44b8e27f5ba5748859a13409255dcf1aafcc) on 2013-07-06. So I guess it should have landed in R-3.0.2. Hence I did not understand why installation of knitr failed in R-3.0.3.

For weird reasons I offer packages in a local repository for the entire R 3.x series ....

**Comment by rnuske** [comment]
sorry, I don't understand your link to StackOverflow

**Comment by yihui** [comment]
Sorry I posted the StackOverflow link under a wrong issue. Please ignore that.

You are right that the commit was before R 3.0.2, but that does not mean it will definitely go to 3.0.2. Sometimes R core make changes in R-devel, but won't port them into the next R-release.

If you must work with R 3.0.2, you can manually patch this function: https://github.com/yihui/knitr/blob/master/R/utils-vignettes.R#L115-L117

```r
if ('aspell' %in% names(formals(tools::vignetteEngine))) {
  tools::vignetteEngine(..., tangle = tangle, package = 'knitr', aspell = list(
    filter = knit_filter
  ))  
} else {
  tools::vignetteEngine(..., tangle = tangle, package = 'knitr')
}
```

**Comment by rnuske** [comment]
Ahh, okay that assumption was too naive.

I want to work with R-3.0.3 and checked the source of tools/R/Vignettes.R of R-3.0.3 and to my surprise it does not contain any `aspell`. 

The [github mirror of r-source by SurajGupta](https://github.com/SurajGupta/r-source/blame/master/src/library/tools/R/Vignettes.R) helped to find the R version in which 'aspell' was added to vignetteEngine: **3.1**. So I guess, the Depends of knitr need to be raised.

**Comment by yihui** [comment]
Okay I'll raise the R version to 3.1.0.

**Comment by rnuske** [comment]
Thanks for fast responses and respectfull treatment of a newbee.

**Comment by ayatawfik** [comment]
i downloaded R 3.0.3 and did not work, why?
i am a beginner and i do not what i do

**Comment by yihui** [comment]
@ayatawfik You'd better use the latest version of R.

**Comment by twelvesummer** [comment]
i downloaded R 3.1.2 and install failed.
> install.packages('knitr', repos = c('https://xran.yihui.name', 'https://cran.r-project.org'))
Warning: unable to access index for repository https://xran.yihui.name/src/contrib
Warning: unable to access index for repository https://cran.r-project.org/src/contrib
Warning message:
package 'knitr' is not available (for R version 3.1.2)

**Comment by yihui** [comment]
@twelvesummer Unless you have a particular reason, I don't recommend using such an old version of R.

**Comment by yutannihilation** [comment]
> Warning: unable to access index for repository

This inditates this is a network issue. Probably, your R is too old to access to https:// URLs? (I don't remember when R got support for HTTPS...)
