### ISSUE TITLE
Provide a chunk option to specify output file for purl

### ISSUE THREAD

**Issue by hhoeflin** [yihui/knitr#1270]
Would it be possible to implement a chunk option that specifies an output file to be used? This way, each chunk code determine separately into which output file it should be written with purl. A similar option is available in org-mode, and I have found it very useful when it comes to structuring my projects this way.

**Comment by yihui** [comment]
Sorry, but that is not possible for now.

**Comment by yihui** [comment]
I don't have plans to implement this, either, but if you want to do it, a pull request will be welcome. The relevant lines are here https://github.com/yihui/knitr/blob/56faff4cfff8/R/block.R#L441-L459
