### ISSUE TITLE
suggestion: offer rescaling / compression option to `include_graphics()` for external images

### ISSUE THREAD

**Issue by maxheld83** [yihui/knitr#1273]
it would be really nice if `knitr::include_graphics()` (which is used heavily, and elegantly in `bookdown()` would allow me to specify a DPI and size, and then **rescale** the external image accordingly, as per [this stack-exchange question](http://stackoverflow.com/questions/39053478/how-do-i-rescale-local-images-for-bookdown-rmarkdown-website).

Note: I mean _external_ image, like some JPEG from a camera or something, _not_ plot images generated by R.

It would be neat especially for any kind of website output, if `knitr`  (or some other element of the toolchain) could take care of the resizing, so that users don't end up deploying _huge_ images when bookdown is rendered to a website, etc.

(I guess, in principal, the same concern applies to PDFs, though file size is usually less of a concern there).

**Comment by yihui** [comment]
If anybody is able to implement it, I'll be happy to take a look at the pull request, otherwise I'm afraid I won't have the time to implement it in the near future.

**Comment by maxheld83** [comment]
Just two more thoughts on this in light of related `blogdown` [issue](https://github.com/rstudio/blogdown/issues/469) and `bookdown` [issue](https://github.com/rstudio/bookdown/issues/316).

On the one hand (automatic) rescaling/resizing/cropping is on the [roadmap](https://github.com/spf13/hugo/issues/1014) for HUGO anyway. That'll probably be easier and/or more specialised than it could be in R. For `blogdown` related issues, this might be a better way.

On the other hand, *it's not available yet*, and the HUGO support wouldn't fix this for other knitr use cases.

**Comment by maxheld83** [comment]
I have now implemented this for my own purposes (inside `blogdown`), and it *does* work:

```
# resize and compress images ===

library(jpeg)
library(imager)

resize_n_compress <- function(file_in, file_out, xmax = 1920, quality = 0.7, cutoff = 100000) {
  # xmax <- 1920  # y pixel max
  # quality <- 0.7  # passed on to jpeg::writeJPEG()
  # cutoff <- 100000  # files smaller than this will not be touched
  # file_out <- "test.jpg"
  if (file.size(file_in) < cutoff) {  # in this case, just copy file
    if (!(file_in == file_out)) {
      file.copy(from = file_in, to = file_out, overwrite = TRUE)
    }
  } else {# if larger than cutoff
    image_raw <- imager::load.image(file = file_in)
    if (dim(image_raw)[1] > xmax) {  # resize only when larger
      x_pix <- xmax  # just in case we want to calculate this, too at some point
      x_factor <- xmax/dim(image_raw)[1]
      y_pix <- round(dim(image_raw)[2] * x_factor)
      image_resized <- imager::resize(im = image_raw, size_x = x_pix, size_y = y_pix)
    } else {# otherwise take raw
      image_resized <- image_raw
    }
    saveme <- imager:::convert.im.toPNG(A = image_resized)
    jpeg::writeJPEG(image = saveme, target = file_out, quality = quality)  # this overwrites by default
  }
}
```

This is a bit clumsy, but it works.

This *both* increases the compression, *and* downscales the image.

While this works, it's pretty darn slow (at least on OS X for some reason, Travis CI was much faster ...), and I'm guessing this is because R isn't really meant/optimised for this kind of thing.
Handling huge, uncompressed images in RAM in R feels a bit painful, but it *does* work.

@yihui is this a direction you think might be worthwhile for me to pursue in a pull request?

I'm a bit confused as to where in the `knitr`, `rmarkdown`, `blogdown`/`bookdown` stack this is best included.

**Comment by yihui** [comment]
I suggest you write your own wrapper function like

```r
include_image = function(x, ...) {
  # first process x by yourself
  magic::whatever....
  # return
  knitr::include_graphics(x, ...)
}
```

I don't have much interest in provide built-in support for this.
