### ISSUE TITLE
Problem with prompt when using other engines

### ISSUE THREAD

**Issue by stla** [yihui/knitr#1274]
Hello, 
The chunk

        ```{r engine='haskell', engine.path='ghc', prompt=TRUE}
        let x = 1
        let y=2
        ```
generates

```
> let x = 1
+ let y=2
```

By the way, could you remove the automatic set to the option `:set +m` with the Haskell engine? This is not a default option in ghci and this is annoying. We can set it manually in a chunk anyway.

**Comment by yihui** [comment]
Without a Haskell syntax parser in R, it is not possible to add prompts correctly, so I'll just document this limitation.

I have removed `:set :m`. I don't know anything about Haskell, and it was from a user contribution.

**Comment by stla** [comment]
Thank you.
I use my own Haskell engine now: http://stla.github.io/stlapblog/posts/ghcscriptrender.html
