### ISSUE TITLE
include_file

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1275]
For writing about Rmarkdown, it would be useful to have `knitr::include_file()` which would just insert the contents of the file into the text. It would also be useful if you could set the syntax highlighting.

**Comment by yihui** [comment]
It is easy to show the verbatim content of a file (read it and indent by four spaces), but I feel syntax highlighting is not easy.

**Comment by cderv** [comment]
This seems something like we have used in the Cookbook: https://github.com/yihui/rmarkdown-cookbook/blob/master/utils.R

````r
import_example <- function(file, lang = xfun::file_ext(file)) {
  x = xfun::read_utf8(file.path("examples", file))
  lang = tolower(lang)
  if (nchar(lang) > 1) {
    lang = sub('^r', '', lang)
    if (lang == 'nw') lang = 'tex'
  }
  knitr::asis_output(paste(c(sprintf("````%s", lang), x, "````"), collapse = '\n'))
}
````
and that others are using elsewhere in their project.

Directly related to https://github.com/yihui/knitr/issues/1931, opened after several others use cases.
