### ISSUE TITLE
knitr engine?

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1276]
It's still frustrating to embed knitr chunks inside a knitr document which you need when you're teaching knitr.  What if there was a knitr engine that would do syntax highlighting for you?

You'd still also need a way to embed knitr chunks in knitr chunks. I'm currently using this technique:

    ```{r setup, include = FALSE}
    chunk <- "```"
    ```

And then using `r chunk` instead of ```` ``` ````. It would be useful to have some way to make this standard.

**Comment by hadley** [comment]
Another option would be to allow knitr chunks to "nest" in the same way C++ & css allow you to nest comments: `/* /* */ */`.   That would require a more sophisticated parser.

**Comment by yihui** [comment]
This is FAQ 8 (https://bit.ly/knitr-faq). I often use ````` `r ""````{r} ````` myself.
