### ISSUE TITLE
include=FALSE and environments

### ISSUE THREAD

**Issue by petrelharp** [yihui/knitr#1277]
I've found that toggling `knit( ... , include=FALSE)` can do unexpected (to me) things to the environments that things are being evaluated in.  

To reproduce, do something like:

1. evaluate `knit( )` within a function
2. have a chunk in the document with `include=FALSE`
3. within that chunk `source()` a file that expects things already defined in the Rmarkdown file to exist.

This is with the CRAN version of knitr in R 3.3.1, on Debian sid.

Here's two variants on the problem.  First, here are the contents of three files:

`included.R`:
```
if (!exists("x")) { stop("included")}
```
and `not_included.R`:
```
if (!exists("x")) {  stop("not included")}
```
and `eval.Rmd`:
 
    ```{r setup}
    x <- 3
    prerequisites <- c("x")
    ```
    ```{r included, include=TRUE}
    source("included.R")
    ```
    ```{r not_included, include=FALSE}
    source("not_included.R")
    ```

Then to see the error, run e.g.
```
> Rscript -e "f <- function (x) knitr::knit(x); f('eval.Rmd')"
[ output truncated ]
Error in eval(expr, envir, enclos) : not included
Calls: f ... eval -> eval -> source -> withVisible -> eval -> eval
```

Here's the other variant, that doesn't require `source()`ing:

If this is the file `eval2.Rmd`:

    ```{r setup}
    x <- 3
    prerequisites <- c("x")
    ```

    ```{r included, include=TRUE}
    if (!exists("x")) {
        stop("included, error without sapply")
    }
    if (!all(sapply(prerequisites,exists))) {
        stop("included, error with sapply")
    } 
    y <- x
    ```

    ```{r not_included, include=FALSE}
    if (!exists("x")) {
        stop("not included, error without sapply")
    }
    if (!all(sapply(prerequisites,exists))) {
        stop("not included, error with sapply")
    } 
    y <- x
    ```

then I get:

    > Rscript -e "f <- function (x) knitr::knit(x); f('eval.Rmd')"
    [truncated]
    Error in eval(expr, envir, enclos) : not included, error with sapply
    Calls: f ... handle -> withCallingHandlers -> withVisible -> eval -> eval

Help!  I am confused.

**Comment by yihui** [comment]
Two problems in this issue:

1. `include=FALSE` implies `error=FALSE`, while knitr's default is `error=TRUE`; that is why the errors were signaled only for those chunks with `include=FALSE`;
2. There is a subtle issue with `sapply(prerequisites, exists)`; you should use `sapply(prerequisites, function(x) exists(x))` instead, or `sapply(prerequisites, exists, where = environment())`. I don't think knitr is the culprit here.
