### ISSUE TITLE
cache.vars option not working properly

### ISSUE THREAD

**Issue by simonkth** [yihui/knitr#1280]
The option `cache.vars` seems to only work properly when `envir = new.env()` is specified in the `knit()` call.

Example code: 

```
# ```{r sample_chunk, cache=TRUE, cache.vars='test_cache'}
# test_cache <- rnorm(1)
# test_cache
# test_nocache <- rnorm(1)
# test_nocache
# ```
# 
# ```{r print}
# rm(list = ls())
# library(tools)
# lazyLoad(file_path_sans_ext(list.files(getwd(), recursive = TRUE, pattern = "sample_chunk"))[1])
# ls()
# ```
```

If we don't specify `envir = new.env()`, `test_nocache` might be included in the cache. Indeed, if the object does not exists in the global environment when falling the function, it will be included. However strangely if `test_nocache` exists when calling `knit()`, it will not be included in the cache...
When using something like `knit("test.Rmd", envir = new.env())`, `test_nocache` will never be included.

I came to this problem when using RStudio. I have very large objects that I don't want to include in the cache, but store in .RDS files at specific locations. I'm then using code like `if (!exists(obj)) obj <- readRDS("obj.RDS")` in the following chunks. I want to cache all other objects in the chunk though. When using the RStudio button "Knit PDF", you can't specify the environment, and even if I use `cache.vars` it will try to save the file in cache.

**Comment by yihui** [comment]
Fixed. Thanks!

**Comment by simonkth** [comment]
Thanks for the fix :)
