### ISSUE TITLE
knitr.rdb is corrupt

### ISSUE THREAD

**Issue by zhangyan715** [yihui/knitr#1281]
I tried to run my rmd documents with shinysever.

All is fine except one that it got error for **knitr.rdb corruption.**

I guess maybe that rmd document contrains so many components

looking forward to solution

**Comment by yihui** [comment]
I think you just need to restart your R session, and perhaps reinstall knitr. Let me know if it still does not work.

**Comment by zhangyan715** [comment]
it turned out to be fine. but I don't know why. on Monday  I run those rmd documents again on linux with shinysever ,just input the url in chrome and then it showed up. but last Friday, it failed again and again no matter what I did about it. Maybe it boils down to linux platform? sorry for my poor English

**Comment by kofiewudzi** [comment]
I am having the same issue. However, restarting the session doesn't seem to help. Any thoughts?
> library(knitr)
Error in get(Info[i, 1], envir = env) : 
  lazy-load database 'C:/Users/kofia/OneDrive/Documents/R/win-library/3.3/knitr/R/knitr.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘knitr’
