### ISSUE TITLE
SQL code execution: how to avoid "NA" display?

### ISSUE THREAD

**Issue by ced75** [yihui/knitr#1283]
Hi,

I am using RMarkdown and knitr to display queries and associated results.
I did not find any option to avoid "NA" character string when a value is NULL.
Is there any way to replace "NA" by a white character, or any other characters string like "<NULL>", for example?

Thanks in advance for your help.
Regards,

Cedric

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
devtools::session_info('knitr')
```

**Comment by ced75** [comment]
Thanks for reply,

Here are my session informations:
`## Session info --------------------------------------------------------------
##  setting  value                       
##  version  R version 3.3.1 (2016-06-21)
##  system   x86_64, linux-gnu           
##  ui       X11                         
##  language (EN)                        
##  collate  fr_FR.UTF-8                 
##  tz       <NA>                        
##  date     2016-09-07
## Packages ------------------------------------------------------------------
##  package  * version date       source        
##  digest     0.6.10  2016-08-02 CRAN (R 3.3.1)
##  evaluate   0.9     2016-04-29 CRAN (R 3.3.0)
##  formatR    1.4     2016-05-09 CRAN (R 3.3.0)
##  highr      0.6     2016-05-09 CRAN (R 3.3.0)
##  knitr      1.14    2016-08-13 CRAN (R 3.3.1)
##  magrittr   1.5     2014-11-22 CRAN (R 3.2.0)
##  markdown   0.7.7   2015-04-22 CRAN (R 3.2.2)
##  mime       0.5     2016-07-07 CRAN (R 3.3.1)
##  stringi    1.1.1   2016-05-27 CRAN (R 3.3.0)
##  stringr    1.1.0   2016-08-19 CRAN (R 3.3.1)
##  yaml       2.1.13  2014-06-12 CRAN (R 3.2.2)`

A chunk example:
````{sql test1, connection=my_conn, tab.cap="Results"}
SELECT n, NULL as test
FROM generate_series(1,10) n;
```
`
The "test" column is filled with NA. Could it be possible to fill it with "NULL", or "<NULL>", or no character at all?

**Comment by yihui** [comment]
Thanks, but it is not self-contained: what is `my_conn`?

**Comment by ced75** [comment]
my_conn is a PostgreSQL database connection through RPostgreSQL dbDriver, defined like this:
`library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
# creates a connection to the postgres database
my_con <- dbConnect(drv, dbname = "mydatabase",
                 host = "192.168.0.1", port = 5432,
                 user = "myuser", password = "mypassword")
`

**Comment by yihui** [comment]
Well, that is still not self-contained, since I don't have this database, so I cannot compile your example. This would be a self-contained example:

    ---
    title: "Knit SQL NA issue"
    ---
    
    ```{r message=FALSE}
    library(DBI)
    db <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")
    ```
    
    ```{sql, connection=db}
    DROP TABLE IF EXISTS packages
    ```
    
    ```{sql, connection=db}
    CREATE TABLE packages (id INTEGER, name TEXT)
    ```
    
    ```{sql, connection=db}
    INSERT INTO packages VALUES (1, 'readr'), (2, 'readxl'), (3, 'haven')
    ```
    
    ````{sql test1, connection=db, tab.cap="Results"}
    SELECT name, NULL as test FROM packages;
    ```

This is essentially a question about `knitr::kable()`, and the answer for now is no: there is not an option to display NA as an empty string. You can manually replace NA and apply `kable()`, though. For example:

    ---
    title: "Knit SQL NA issue"
    ---
    
    ```{r message=FALSE}
    library(DBI)
    db <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")
    ```
    
    ```{sql, connection=db}
    DROP TABLE IF EXISTS packages
    ```
    
    ```{sql, connection=db}
    CREATE TABLE packages (id INTEGER, name TEXT)
    ```
    
    ```{sql, connection=db}
    INSERT INTO packages VALUES (1, 'readr'), (2, 'readxl'), (3, 'haven')
    ```
    
    ````{sql test1, connection=db, tab.cap="Results", output.var='testData'}
    SELECT name, NULL as test FROM packages;
    ```
    
    ```{r echo=FALSE}
    testData2 = testData
    testData2$test[is.na(testData2$test)] = ''
    knitr::kable(testData2, caption = 'Results')
    rm(testData2)
    ```

**Comment by ced75** [comment]
It works fine.
I don't know if you plan to add a parameter to the SQL code chunk, but this way is OK for the moment.

Thanks for your help.

**Comment by yihui** [comment]
Done. Set `options(knitr.kable.NA = '')`, and `kable()` will display NA as empty strings.

**Comment by ced75** [comment]
Thanks!
