### ISSUE TITLE
Cannot place ggvis plots side by side in HTML

### ISSUE THREAD

**Issue by cigrainger** [yihui/knitr#1284]
I've tried just about everything. For all other output types, `{r fig.show= = 'hold', out.width = '50%'}` works fine. But no matter what I do, I can't get ggvis output to be displayed side by side in HTML output. I've also noticed that `out.height` has no effect on ggvis output...

Reproducible example:

    ---
    title: "Test"
    output: html_document
    ---
    
    ```{r out.width = '50%', echo = F, message = F}
    library(ggvis)
    df <- data.frame(x = runif(10), 
                     y = runif(10))
    df %>% 
      ggvis(~x) %>% 
      layer_histograms()
    
    df %>% 
      ggvis(~x, ~y) %>% 
      layer_points()
    ```

**Comment by yihui** [comment]
ggvis output is not normal R graphics output, so the normal figure options do not apply. I do not have a solution in this case. Sorry.
