### ISSUE TITLE
It seems you should call rmarkdown::render() instead of knitr::knit2html() ...

### ISSUE THREAD

**Issue by jeroenooms** [yihui/knitr#1286]
This error keeps appearing for markdown vignettes without making it obvious what the underlying problem is. It needs better wording explaining what causes this problem, because `knitr::knit2html` is not called by the user but by the vignette engine.

Some examples:
  - https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/brotli-00check.html
  - https://builder.r-hub.io/status/magick_0.3.tar.gz-12769ec3c1339f46527af5bad4b3f1ca

People have speculated that this might be caused by `rmarkdown` missing from `Suggests` or that `pandoc-citeproc` is not available from the system. However neither seems to be the problem in my case. A more informative diagnostic message would be really helpful.

**Comment by yihui** [comment]
It is a warning instead of error due to the lack of pandoc/pandoc-citeproc (the actual error came from elsewhere). I removed it anyway.

Long live Solaris! :)

**Comment by jeroenooms** [comment]
I think it's still good to warn the user if `pandoc` is missing and you are falling back on some sub-optimal rendering engine. But the warning should be more descriptive if this is the problem :)

**Comment by jeroenooms** [comment]
I think it's still good to warn the user if `pandoc` is missing and you are falling back on some sub-optimal rendering engine. But the warning should be more descriptive if this is the problem :)

**Comment by jeroenooms** [comment]
I think it's still good to warn the user if `pandoc` is missing and you are falling back on some sub-optimal rendering engine. But the warning should be more descriptive if this is the problem :)

**Comment by jeroenooms** [comment]
I think it's still good to warn the user if `pandoc` is missing and you are falling back on some sub-optimal rendering engine. But the warning should be more descriptive if this is the problem :)

**Comment by yihui** [comment]
I agree. I do have a warning about Pandoc, but it seems it was muffled by `R CMD build`.
