### ISSUE TITLE
Tables inside of fullwidth environment with tufte book fail to render or render ugly

### ISSUE THREAD

**Issue by elbamos** [yihui/knitr#1288]
The tufte book latex class (and many derived classes) have a `fullwidth` environment.  If the table function is `pander`, the latex typesetting engine will fail to parse the file.  If its `kable`, the table will print as unformatted text, as though `kable` wasn't aware that it was supposed to produce latex, unless it is given the `format="latex"` parameter.  If the parameter is given, `kable` will produce the table, but without proper formatting - it will have grid lines for every row and column all of the same weight instead of the nice pretty tables `kable` usually produces. 

I'm not sure to what extent this is a `knitr` issue vs. a `pander` issue vs. a `tufte-book` issue.

**Comment by yihui** [comment]
Does `kable(booktabs = TRUE)` give you what you want? Note you may need `tables: yes` in YAML (as a _top-level_ option) so that Pandoc knows to load the booktabs package.

**Comment by elbamos** [comment]
Thanks! `kable` with booktabs won't let me use the full set of alignment options, so I can't get text wrapping within cells.  `pander` ignores bookdown even when `tables: yes`.  `xtable` **mostly** works, unless a table caption is added.  

Any suggestions on a strategy for modifying either the tex, or something else, and I'll try to get everything working?

**Comment by yihui** [comment]
What is the problem with xtable's caption?
