### ISSUE TITLE
global.par=TRUE forces all plots to be the same size

### ISSUE THREAD

**Issue by ilia-kats** [yihui/knitr#1290]
Here's a minimal example:
```
\documentclass[a4paper,10pt]{article}
\usepackage[utf8]{inputenc}

<<setup, include=FALSE, cache=FALSE>>=
opts_chunk$set(results='markup', cache=TRUE, dev='cairo_pdf', fig.path='plots/', cache.path='cache/', fig.keep='high', fig.show='hold', fig.width=2, fig.height=2, tidy=FALSE, dev.args=list(pointsize=8))
opts_knit$set(global.par=TRUE)
@
\begin{document}
<<test1, fig.width=2.5, fig.height=2.5>>=
plot(1:10)
@
<<test2, fig.width=5, fig.height=5>>=
plot(1:10)
@
\end{document}
```

Basically what happens is that while graphics device of the second plot has the specified size, the plot itself has the same size as the first one. My guess is that this is because block_exec indiscriminantly saves all parameters, including pin, fin, and so on. Perhaps there should be a blacklist of parameters that are not cached.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
