### ISSUE TITLE
Any way to collaborate and comment on a knitr document?

### ISSUE THREAD

**Issue by jeffwong** [yihui/knitr#1293]
Is there any way to write comments with others on a knitted research document in the style of Google Doc comments?

**Comment by yihui** [comment]
I'm not aware of easy solutions. Collaboration is possible with RStudio Server Pro (several users can edit the same document at the same time), but I guess commenting is not available.

If everybody in your team is familiar with GIT, you can certainly consider collaboration on Github or other GIT platforms. It will not be real-time, though. Comments will be possible in any commits or pull requests.
