### ISSUE TITLE
control svg size in pdf

### ISSUE THREAD

**Issue by vnijs** [yihui/knitr#1294]
When creating an svg image, e.g., using DiagrammeR, the size of the image is fine on mac but can be extremely small on windows. An example Rmd file is shown below as is output from Rstudio's `Knit to pdf` on mac and windows.

knitr use `webshot` to generate the image for the pdf and it would be great if something like `fig.width` could be used to set the size of the image. Perhaps related to https://github.com/wch/webshot/issues/26

cc: @rich-iannone, @wch, @timelyportfolio

		---
		title: "svg"
		output: pdf_document
		---

		```{r cars}
		DiagrammeR::mermaid("
		graph LR
		  A-->B
		  A-->C
		  C-->E
		  B-->D
		  C-->D
		  D-->F
		  E-->F
		")
		```

SVG on Mac:
[svg.pdf](https://github.com/yihui/knitr/files/504628/svg.pdf)

SVG on Windows:
[svg_win.pdf](https://github.com/yihui/knitr/files/504632/svg_win.pdf)

**Comment by yihui** [comment]
You can try PNG screenshots instead. PDF screenshots do not always work as you'd expect. See the last paragraph: https://bookdown.org/yihui/bookdown/html-widgets.html

BTW, `fig.width`/`fig.height` do set the image size.
