### ISSUE TITLE
Feature request: longfigure support?

### ISSUE THREAD

**Issue by parate** [yihui/knitr#1295]
I am generating a document (to pdf through latex) with subfigures. Depending on the data, many plots can be generated that would need to span several pages. I have searched around and came across the longfigure package. How could this be integrated as a drop-in replacement for the figure environment? (I hope I am reporting this in the right place...)

**Comment by yihui** [comment]
What is the syntax of longfigure? What is the format of your source document? Rnw, Rmd, or ...? You probably only use the chunk option `fig.env = 'longfigure'`, depending on the syntax of longfigure, which I don't know.

**Comment by parate** [comment]
It's a .Rmd file. I tried the fig.env, but R chokes on that without any error messages.

The syntax is:
`\documentclass{book}
\usepackage{graphicx}
\usepackage{longfigure}
\begin{document}
\begin{longfigure}{c}
\caption{My Long Figure}\label{mlfig}\\
\includegraphics[width=3in]{myfig1}\\
\includegraphics[width=3in]{myfig2}\\
\includegraphics[width=3in]{myfig3}\\
\begin{tabular}{ll}
one & two \\
three & four\\
\end{tabular}
2
\end{longfigure}
\end{document}`

**Comment by yihui** [comment]
You need to include `\usepackage{longfigure}` in the preamble. See `in_header` at http://rmarkdown.rstudio.com/pdf_document_format.html#includes

**Comment by parate** [comment]
I am still not successful. I added `\usepackage{longifgure}` to my `.tex` template, which results in the following error if I add `fig.env='longfigure'` to the chunk that generates the figures:

pandoc" +RTS -K512m -RTS default_report_template.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output pandoc156021aa655b.pdf --template pandoc.tex --highlight-style tango --latex-engine xelatex 
! Paragraph ended before \LF@array was complete.
<to be read again> 
                   \par 
l.275 

pandoc.exe: Error producing PDF
Error: pandoc document conversion failed with error 43

**Comment by yihui** [comment]
Sorry I cannot help in this case. I experimented with the longfigure package a bit but I had a hard time understanding how it works. It seems the caption must be written in the beginning of the figure environment instead of the end. The documentation is also so brief, and I cannot afford more time on it. If you can figure out how to make knitr work with it, please feel free to submit a pull request. Thanks!
