### ISSUE TITLE
Definition of a chunk hook 'size' completely replaces figure environment for R markdown -> pdf

### ISSUE THREAD

**Issue by jranke** [yihui/knitr#1296]
When I set a chunk hook `size` in a rmarkdown format like this

```
my_report_1 <- function(...) {

  fmt <- rmarkdown::pdf_document(keep_tex = TRUE, ...)

  fmt$knitr$knit_hooks$size = function(before, options, envir) {
    if (before) return(paste0("\n \\", options$size, "\n"))
    else return("\n \\normalsize \n")
  }

  return(fmt)
}
```

and process a document like this

    ---
    output: my_report_1
    ---

    The following code chunk has `size = 'small'` in the chunk options.

    ```{r, size = 'small'}
    print(1)
    ```

    And this is Figure \ref{fig:test}

    ```{r test, fig.cap = 'Test caption\\label{fig:test}'}
    plot(1)
    ```

the font size of the first code chunk and its output is adapted as expected. However, instead of a `figure` environment, I get the following latex for the second code chunk:

    \includegraphics{knitr_code_font_size_files/figure-latex/test-1.pdf}
    \normalsize

If the chunk hook is adapted not to work on figures with captions specified:

    fmt$knitr$knit_hooks$size = function(before, options, envir) {
      if (is.null(options$fig.cap)) {
        if (before) return(paste0("\n \\", options$size, "\n"))
        else return("\n \\normalsize \n")
      }
    }

I get the expected latex code:

    \begin{figure}[htbp]
    \centering
    \includegraphics{knitr_code_font_size_files/figure-latex/test-1.pdf}
    \caption{Test caption\label{fig:test}}
    \end{figure}

Did I maybe overlook something in the documentation?

OK, now after formulating this issue, I tried again with using a different name for the code hook, and this does not have the side effect on the figures, so you can close the issue I believe, but I will post it as reference for people how try to solve the same problem. The solution is:

    fmt$knitr$knit_hooks$codesize = function(before, options, envir) {
      if (is.null(options$fig.cap)) {
        if (before) return(paste0("\n \\", options$codesize, "\n"))
        else return("\n \\normalsize \n")
      }
    }

and 

    ---
    output: my_report_1
    ---

    The following code chunk has `codesize = 'small'` in the chunk options.

    ```{r, codesize = 'small'}
    print(1)
    ```

    And this is Figure \ref{fig:test}

    ```{r test, fig.cap = 'Test caption\\label{fig:test}'}
    plot(1)
    ```

I think it would be nice to have such a chunk hook defined by default for pdf_document. But then I believe to stick with 'size' would be preferable, so the problem with the figure environment would need to be solved in a more general way than shown above.

**Comment by yihui** [comment]
You need more blank lines before/after the figure. Pandoc's Markdown syntax requires the image (`![]()`) to be in its own paragraph so it can be identified as a figure environment. Adding one more blank line before and after the chunk should give you what you want, e.g.

```r
  fmt$knitr$knit_hooks$size = function(before, options, envir) {
    if (before) return(paste0("\n \\", options$size, "\n\n"))
    else return("\n\n \\normalsize \n")
  }
```

**Comment by jranke** [comment]
Great, this works, thanks a lot!

**Comment by jranke** [comment]
@yihui I believe it would be difficult to implement an equivalent 'size' hook for html or other output, so I understand this should remain a local solution, right?

**Comment by yihui** [comment]
Yes, there is no general solution to this problem. It is possible to adjust the font size for HTML, but it is not possible for other output formats.

**Comment by rickhg12hs** [comment]
So, what is the recommended procedure to set the fontsize of chunks for PDF output?

[rstudio, knitr, pdf_document]
