### ISSUE TITLE
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose)

### ISSUE THREAD

**Issue by dlindelof** [yihui/knitr#1298]
When trying to knit the attached document, I get the following error:

```
Quitting from lines 13-14 (inference_minimal.Rnw) 
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for the following string
or character:

	count

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The contents of the LaTeX log of the aborted run have been printed above,
it may contain additional details as to why the metric calculation failed.
```

Commenting out either line 3 (the call to `\journal`) or line 13 (the call to `qplot()`) makes the error message go away.

[inference_minimal.Rnw.zip](https://github.com/yihui/knitr/files/522577/inference_minimal.Rnw.zip)

**Comment by yihui** [comment]
`\journal{}` is not a standard LaTeX command. Please define it or use a LaTeX package/class that defined it.

```
! Undefined control sequence.
l.53 \journal
             {Energy and Buildings}
```

Even without the tikz device, your document won't compile anyway.

**Comment by dlindelof** [comment]
Sorry for the error in the test case. I've checked it again and here is what I believe is a correct test case. The error happens when I use the `elsarticle` class with the `hyperref` package.

(I usually work with LyX and tried to reduce the generated .Rnw file to the smallest case that would still exhibit the problem.)

[inference_minimal.Rnw.zip](https://github.com/yihui/knitr/files/523577/inference_minimal.Rnw.zip)

**Comment by yihui** [comment]
Thanks for the update, but it is easy to show that the issue is irrelevant to **knitr** with the following minimal _LaTeX_ document:

```latex
\documentclass{elsarticle}

\usepackage[unicode=true,pdfusetitle,
 bookmarks=false,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}

\begin{document}

foo bar

\end{document}
```

There might be certain conflicts between elsarticle and hyperref.
