### ISSUE TITLE
\only option in beamer crash with code chunk

### ISSUE THREAD

**Issue by clemlaflemme** [yihui/knitr#1299]
It seems like the \only command cannot be used to show/hide a R chunk. Here is a MWE producing the error:

```tex
\documentclass[11pt]{beamer}
\usetheme{Warsaw}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}

<<setup, include=FALSE>>=
library(knitr)
@

\title{Title}

\begin{document}
\section{Section name}
\begin{frame}[fragile]
\frametitle{\insertsection}

Add \verb!\only<1>{ ... }! around the code chunk to produce crash
<<>>=
2+2
@

\end{frame}

\end{document}
```

I got this error message

> Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet, : Running 'texi2dvi' on 'KnitrOnly.tex' failed. LaTeX errors: ! Paragraph ended before \@xverbatim was complete. <to be read again> \par l.16 } ! LaTeX Error: \begin{kframe} on input line 16 ended by \end{beamer@framepauses }. See the LaTeX manual or LaTeX Companion for explanation. Type H <return> for immediate help. ! Missing } inserted. <inserted text> } l.85 \end{frame}

> ! Extra }, or forgotten \endgroup. \endbeamer@frameslide ...amer@framepauses}\egroup \ifx \beamer@frametitle \@... l.85 \end{frame} ! LaTeX Error: \begin{knitrout} on input line 16 ended by \end{beamer@frameslid e}. See the LaTeX manual or LaTeX Companion for explanation. Type H <return> for immediate help. ! LaTeX Error: \begin{beamer@framepauses} on input line 85 ended by \end{docume nt}. See the LaTeX manual or LaTeX Companion

**Comment by yihui** [comment]
This example works fine for me: [output.pdf](https://github.com/yihui/knitr/files/524930/Untitled.pdf)


```
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04
```

Not sure why texi2dvi was involved. How did you compile this Rnw to PDF?

**Comment by clemlaflemme** [comment]
thanks for the quick look around. Yes the MWE does not crash, but if you instead try to compile 

\documentclass[11pt]{beamer}
\usetheme{Warsaw}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}

<<setup, include=FALSE>>=
library(knitr)
@

\title{Title}

\begin{document}
\section{Section name}
\begin{frame}[fragile]
\frametitle{\insertsection}

Add \verb!\only<1>{ ... }! around the code chunk to produce crash
\only<1>{
<<>>=
2+2
@
}
\end{frame}

\end{document}

then you get the error I mentioned. I guess my comment was ill formulated

And to answer fully your question, with the \only as above I got the following log (attached). The problem comes from the pdfLatex part, the Rnw produces a clean .tex file (see attached too; and same thing, if you comment the \only{ … } it works but if you don’t, it crashes). I don’t know Tex enough to say more about this error.

thanks for your help

Clément Walter
clementwalter@icloud.com
linkedin.com/in/clementwalter
+336.65.16.53.97

**Comment by yihui** [comment]
I see. I'm not a LaTeX expert, but it is rare that someone puts an environment inside a command. Sorry I'm not able to offer any help here, but you can read this post for more information: http://tex.stackexchange.com/q/140290/9128
