### ISSUE TITLE
Question: is it possible to make knitted documents commentable?

### ISSUE THREAD

**Issue by jeffwong-nflx** [yihui/knitr#1303]
Is there a way to knit a .Rmd file and share the result in a way that allows others to write comments? I was thinking of knitting to .HTML, then uploading the HTML to google drive, but in the process a lot of formatting was lost (can't hide code chunks, can't use DT::datatable, no table of contents).

**Comment by yihui** [comment]
There are many services that allow you to annotate HTML pages, e.g. https://hypothes.is You can host the HTML pages on any web servers, including Github Pages.
