### ISSUE TITLE
How to control space between text ,code chunk and the output

### ISSUE THREAD

**Issue by shenhanson** [yihui/knitr#1306]
I am new user of R markdown. It's very useful and powerful for me. For my homework,  I use knitr in R studio and generate a PDF report. 

In order to make my homework looks better. I'd like to decrease the line space between text content, chunk code and output. 

I try to use below code at the beginning of Rmd file to achieve that, but it doesn't work. 

```{r setup, include=FALSE}
knitr::knit_hooks$set(small.mar = function(before, options, envir) {
    if (before) {
       gsub("```\n*```r*\n*", "", before)
    } else {
       gsub("```\n+```\n", "", before)
    }
})
knitr::opts_chunk$set(echo = TRUE,strip.white = TRUE,tidy=TRUE,tidy.opts=list(width.cutoff=60,blank=FALSE,highlight=FALSE),small.mar=T)
```
Thank you very much for help in advance.

**Comment by yihui** [comment]
Please ask this kind of general questions on StackOverflow first: http://stackoverflow.com/questions/tagged/knitr I recommend you to  provide a minimal, self-contained, and reproducible example, along with a screenshot illustrating your problem.

**Comment by shenhanson** [comment]
Thank you for your advise and Knitr you developed~
感谢你的Knitr
好棒~~~！！！！


Best Regards,
 
Hanzhong Shen


Technische Universität Berlin
Department Assembly Technology and Factory Management
Pascalstr. 8-9,D - 10587 Berlin

Handy: +49 (0)176 / 3152 - 7787
Email:  shenhanson@gmail.com
Internet: www.gpe.tu-berlin.de <http://www.gpe.tu-berlin.de/>

**Comment by yihui** [comment]
谢谢理解！
