### ISSUE TITLE
kable(caption = ...) bug:  no label set in latex output.

### ISSUE THREAD

**Issue by dmurdoch** [yihui/knitr#1309]
If you do something like

    <<ident>>=
    kable(diag(3), caption = "The identity matrix")
    @

in a `knitr` document targeting LaTeX output, it looks as though the intention is that you should be able to reference that table using `\ref{tab:ident}`.  However, this is done using a function `create_label` in the `R/utils.R` file, and that function has an argument `latex = FALSE`.  In order to get the label set, it needs to be called with `latex = TRUE`.  `kable()` doesn't do this. 

I think the fix is to change

    # create a label for bookdown if applicable
    if (!is.null(caption) && !is.na(caption)) caption = paste0(
      create_label('tab:', opts_current$get('label')), caption
    )

to

    # create a label for bookdown if applicable
    if (!is.null(caption) && !is.na(caption)) caption = paste0(
      create_label('tab:', opts_current$get('label')), caption, latex = format == 'latex'
    )

**Comment by yihui** [comment]
That makes sense. Do you want to create a pull request?

**Comment by dmurdoch** [comment]
On 25/10/2016 3:54 PM, Yihui Xie wrote:
>
> That makes sense. Do you want to create a pull request?
>

I don't remember how :-).  I haven't really been using Git for a few months.

I don't think this is urgent, so if you're willing to wait a while, I'll 
do it.

Duncan

**Comment by yihui** [comment]
For this kind of simple changes, no knowledge of GIT is required. You can click the edit button on the page (the second from the right) https://github.com/yihui/knitr/blob/master/R/table.R

![image](https://cloud.githubusercontent.com/assets/163582/19706096/c1347cbc-9ad5-11e6-85cf-1252d0090d71.png)

then make the change, and Github will guide you to create the pull request.
