### ISSUE TITLE
results='hold' drops classes on generated output

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1310]
Given this document:

    ---
    title: "Untitled"
    output: html_document
    ---
    
    ```{r, results='hold'}
    knitr::asis_output("<h1>Hello!</h1>")
    ```

The resulting HTML is escaped in the rendered document (after an `rmarkdown::render()`):

![screen shot 2016-10-25 at 1 05 08 pm](https://cloud.githubusercontent.com/assets/1976582/19702276/ad56e0e4-9ab3-11e6-9066-5531799401df.png)

However, the HTML is rendered verbatim / as expected with the other output types.

I believe the cause is here: https://github.com/yihui/knitr/blob/9fc0c6143605612ad32e04da0d34708d02747817/R/block.R#L205-L208

`knitr` collects and pastes all character outputs at the end with `results = "hold"`; unfortunately this will drop classes on generated outputs and so cause differences in rendering.

Would it be possible for `knitr` to re-arrange outputs without dropping classes / using `paste`?

**Comment by yihui** [comment]
That makes sense. I'll fix it.
