### ISSUE TITLE
help page with results='hold'

### ISSUE THREAD

**Issue by dhjones1** [yihui/knitr#1315]
Hi Yihui,

My issue is that the help page is not rendered to HTML in certain situations.
I have narrowed my issue to one chunk option: results='hold'
Also the rendering issue is only for HTML - PDF and Word rendering are not defective.
Here is my minimal example with attached zip file.
Thanks for helping already with your example and thinks in advance for any insight.

    ---
    title: "help page with results='hold'"
    output: html_document
    ---

    ```{r}
    library(printr)
    ```
    
    ```{r, results='hold'}
    ?c
    ```
    
    ```{r}
    sessionInfo()
    ```

[printr_issue.zip](https://github.com/yihui/knitr/files/569473/printr_issue.zip)

**Comment by yihui** [comment]
Thanks! This is what I call a _minimal reproducible example_. This bug has been fixed a week ago. You can install the development version via

```r
devtools::install_github('yihui/knitr')
```

**Comment by dhjones1** [comment]
Thank you!

Douglas H. Jones, PhD
Professor
Management Science and Information Systems
Director of MBA in Analytics and Information Systems (AIM)
Rutgers Business School
*Please use this email in all correspondences*: douglas.h.jones@gmail.com
http://www.linkedin.com/in/douglashjones
http://twitter.com/dhjones1
