### ISSUE TITLE
Coming together with ``\Sexpr{}'' from knitr package, Chinese character garbled

### ISSUE THREAD

**Issue by likanzhan** [yihui/knitr#1317]
I've asked the questions several days ago on [stackoverflow](http://stackoverflow.com/questions/40357408/coming-together-with-sexpr-from-knitr-package-chinese-character-garbled),  and didn't get an answer. so I reposed my questions here, sorry for the reposting.

I created a dynamic ".rnw" file with knitr package. The file contains some Chinese characters. The document works fine when the inline output function ``\Sexpr{}'' is not included in the script.

```
\documentclass[11pt]{article}
\usepackage{ctex}
\begin{document}
<<>>=
sessionInfo()
mp <- mean(pressure$pressure)
@
平均值
\end{document}
```
And the output of the script is:
```
## R version 3.3.1 (2016-06-21)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: OS X 10.12.1 (Sierra)
##
## locale:
## [1] C
##
## attached base packages:
## [1] stats graphics grDevices utils datasets methods base
##
## other attached packages:
## [1] knitr_1.14
##
## loaded via a namespace (and not attached):
## [1] magrittr_1.5 tools_3.3.1 stringi_1.1.2 stringr_1.1.0 evaluate_0.10

平均值
```

But if I used the inline output function ``\Sexpr{}'' to print out the results, the Chinese characters become garbled. Any suggestions?

```
\documentclass[11pt]{article}
\usepackage{ctex}
\begin{document}
<<>>=
mp <- mean(pressure$pressure)
@
平均值=\Sexpr{mp}
\end{document}
```
And the output becomes: < U+5E73>< U+5747>< U+503C>=124.3367053

**Comment by yihui** [comment]
The `C` locale is the culprit. Please see http://stackoverflow.com/q/9689104/559676

**Comment by likanzhan** [comment]
Soory to bother you again, my previous problem reoccurred.
The problem is that when I run the `sessionInfo()` in R Console, I got the `locale` as expected.
And when I run the function in a `Rmd` file, I also got the `locale` as expected.
But when I run  `sessionInfo()` in a Rnw file, I got the `locale` as `C`.
Any suggestions? Thanks

Appendixes: 

a. Out from r console and an `Rmd` file
```r
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.17.2

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1 
```

b. Out from `Rnw` file

```r
## R version 3.4.1 (2017-06-30)
## Platform: x86_64-apple-darwin15.6.0 (64-bit)
## Running under: macOS Sierra 10.12.6
## 
## Matrix products: default
## BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] C
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] knitr_1.17.2
## 
## loaded via a namespace (and not attached):
## [1] compiler_3.4.1  magrittr_1.5    tools_3.4.1     stringi_1.1.5  
## [5] stringr_1.2.0   evaluate_0.10.1
```

**Comment by yihui** [comment]
I don't have time to explain this issue. It is a fairly annoying issue specific to macOS (the environment variable `LANG` is not inherited when you start an app from the Spotlight or Dock, so R does not know which locale to use).

A quick and dirty fix is `Sys.setlocale(, "English")` in your `~/.Rprofile`.

**Comment by likanzhan** [comment]
This solves the problem. Thanks.
