### ISSUE TITLE
insert R code chunk in a *.Rnw file via menu button in rstudio 1.0.44

### ISSUE THREAD

**Issue by tfran71** [yihui/knitr#1318]
Until rstudio v 0.99 I could easily include an R code chunk in a latex-knitr document via a specific button in the menu. With the new rstudio 1.0.44 I can insert (with this obviously slightly modified button) R, bash, python, sql, stan, ... but not the former <<...>>= ....@ chunk. Any idea how to achieve that or do I have to live with the manual insertion of such a code chunk?

**Comment by yihui** [comment]
Thanks for the report! I think this is a bug of the RStudio IDE.

Cc @jjallaire Inserting R code chunks should take the file type into consideration. Currently it inserts ```` ```{r} ```` into Rnw documents.

**Comment by jjallaire** [comment]
@jmcphers and @kevinushey Perhaps something we should fix for the patch release?

**Comment by kevinushey** [comment]
Yes, definitely!

The behavior here is really funky -- if you use the shortcut (Ctrl + Alt + I) to insert a chunk, you get the correct behavior; however, if you insert from the menu item you get an R Markdown chunk entry -- and then following that the Ctrl + Alt + I shortcut no longer produces the expected chunk.

**Comment by jmcphers** [comment]
Did this already get taken care of? I've filed a bug on the IDE side to track it (will take a crack at it tomorrow unless @kevinushey wants first shot; pretty sure this is a regression from a change made in 1.0)

**Comment by jmcphers** [comment]
Fixed now in the IDE (version 1.0.128 or later)
