### ISSUE TITLE
kable does not respect newlines in table cells

### ISSUE THREAD

**Issue by mschubert** [yihui/knitr#1319]
Consider the following to `data.frame`s that I want to print using `kable`:

    ```{r}
    knitr::kable(data.frame(a=1:2,b=c('a','b')))
    knitr::kable(data.frame(a=1:2,b=c('a\nb','c')))
    ```

The first works file, but in the second the the value `b` is placed in column `a` instead of column `b`.

I assume this is because of the way the newline is handled in the Latex source. The [solution](http://stackoverflow.com/questions/3068555/how-to-insert-manual-line-breaks-inside-latex-tables) to handle this should be to add `\newline` in the Latex source instead of an actual new line. [Pander](http://stackoverflow.com/questions/25857538/tables-in-pander-style-multiline) already seems to do this, it would be nice if `knitr` could do it as well.

**Comment by yihui** [comment]
Thanks for the report. It should be simple enough to make the change for LaTeX output, but it does not sound trivial to me to make it work for all output formats, and I don't have time to work on this for now. Sorry. If pander works for you, you are welcome to use pander instead.

**Comment by triceraflops** [comment]
Although it's another package, this is related to the following in the kableExtra package.
[https://github.com/haozhu233/kableExtra/issues/157](url)

**Comment by yihui** [comment]
Okay. Please feel free to use ** kableExtra** or **pander**. I don't think I'll ever have time for this task in **knitr**. Thanks!
