### ISSUE TITLE
Feature request: Warn on <<<<<<< HEAD

### ISSUE THREAD

**Issue by AmeliaMN** [yihui/knitr#1322]
Since I use git and GitHub to manage my work, I often end up with merge conflicts, some of which I forget to clean up fully. This often means ugly things like `<<<<<<< HEAD` and `>>>>>>> [commit hash]` get left behind and end up on my course website. I wish knitr would throw a warning when it saw these things.

**Comment by yihui** [comment]
When there are merge conflicts, git will warn you, and you can also easily see them in a GUI (e.g. gitx or RStudio's git panel). I cannot imagine how merge conflicts could be overlooked. Sounds like Yihui's warnings are often like this

![dozz-off](https://cloud.githubusercontent.com/assets/163582/20536402/83912ca4-b0ae-11e6-8848-aeec70c437c8.gif)

whereas git's warnings are like this?

![demo-fail](https://cloud.githubusercontent.com/assets/163582/20536419/98938b1a-b0ae-11e6-94ee-05fbdccd956b.gif)

**Comment by AmeliaMN** [comment]
As always, I love the gifs. 

Jenny Bryan has heard on numerous occasions how inept I am with git, and I'm trying to train myself to use a GUI rather than just the command-line. But I frequently manage to leave in scraps of these things, maybe because I do a pull or upstream fetch, fail to fully fix all the conflicts, then have to head off to class so I just sync changes to my course site and don't notice. (Not to pick on @beanumber but I know he does it too.)

**Comment by yihui** [comment]
I feel this is too much for knitr to do, and it is not easy to do it well only by text matching (e.g. there could be literally a line `<<<<<HEAD`).

You can use a helper function to warn yourself, though:

```r
check_git_conflicts = function() {
  if (length(grep('conflicts', system('git status', intern = TRUE))))
    stop('Please resolve git conflicts')
}
```

**Comment by jimhester** [comment]
I mentioned this on [twitter](https://twitter.com/jimhester_/status/806129818228113409), but the sample pre commit hook run `git diff-index --check`, which will throw an error and not let you commit if there are merge markers e.g. 

```shell
R/as_list.R:32: leftover conflict marker
```
Simply mv `.git/hooks/pre-commit.sample .git/hooks/pre-commit` on every repository you want this check for.

The script does more than just this of course, so if the rest is causing you grief you can comment out all but the last line.
