### ISSUE TITLE
Vectorized webshot::webshot

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#1326]
See https://github.com/wch/webshot/pull/33 `include_url()` should be vectorized accordingly.

**Comment by bschneidr** [comment]
I believe this can now be closed thanks to the latest update to webshot:  [wch/webshot#33](https://github.com/wch/webshot/pull/33)

**Comment by yihui** [comment]
I don't think so. I was assuming `include_url()` takes a single URL. When multiple URLs are passed to it, I think I need to vectorize some internal code (e.g. `knitr:::wrap.html_screenshot`).

At least the following minimal example does not work for now:

    ---
    output:
      pdf_document: default
    ---
    
    ```{r}
    knitr::include_url(c('https://google.com', 'https://www.r-project.org'))
    ```

You probably meant

    webshot::webshot(c('https://google.com', 'https://www.r-project.org'))
