### ISSUE TITLE
Embedding knitr  generated tex files into a bigger latex.

### ISSUE THREAD

**Issue by skanskan** [yihui/knitr#1331]
Hello.
I've already asked at https://tex.stackexchange.com/questions/342360/embedding-knitr-tex-files-on-a-bigger-latex-file but I'm getting no answers.

There are already some question about about how to use Knitr's latex output within a new knitr document, using Rstudio and include or input and declaring some chunks as child.

But what if I want to use a simple knitr output (such as an R xtable) from within an external LaTeX program, such as TeXStudio to build a larger project?

For example, I could create a mytable.rnw file and generate this simple table,

```
\documentclass{article}
\begin{document}

<<r table2, results='asis', message=T, echo=F>>=

library(xtable) 
print(
  xtable(
    head(iris),
    caption = 'Iris data'
  ),
  comment = FALSE,
  type = 'latex'
)

@

\end{document}
```

![](https://i.stack.imgur.com/eFzF0.png)

And now I want to grab the generated mytable.tex file and use it in a bigger document from TexStudio, in the same folder.

```
\documentclass{article}
\begin{document}
 First table:
 \include{mytable}
 Second table:
 \include{mytable}
\end{document}
```

When I try to compile it I get many errors:

```
Can be used only in preamble. \documentclass
Can be used only in preamble. \documentclass{article}\usepackage
```

I guess the problem arises because knitr ouput includes a lot of preamble information that can't be included within the document body, not only usepackage directives but also a lot of fie-tune information about colors, tables...

What's the proper way do it? How to force Rstudio's knitr to output only the proper information?
Or how to force my main latex document (from TexStudio) to correct the problem?

If we have to do it many times is there any easy way to include that preamble in the main tex document without going manually one by one.
Or even worse, some genetared outputs may contain incompatible preambles.

**Comment by yihui** [comment]
Sorry I don't have time to investigate your issue, but I recommend you to always post knitr-related questions on StackOverflow with the tag `r` instead of TeX.SX. The former is a much bigger community, and you are more likely to get answers there. TeX.SX is a much smaller world, and even smaller when you intersect it with knitr.

**Comment by adibender** [comment]
I gave some possible answers here: http://tex.stackexchange.com/questions/342360/embedding-knitr-tex-files-on-a-bigger-latex-file/343096#343096

I think this can be closed.
