### ISSUE TITLE
Calling all_labels() with conditions causes stringr::str_split error or other unexpected behavior

### ISSUE THREAD

**Issue by dgJacks0n** [yihui/knitr#1332]
I'm printing the R code for my knitr reports at the end using an example provided by Yihui:

    ```{r show_all, ref.label = all_labels(), echo = TRUE, eval = FALSE}
    ```

This works fine - but I have cases where I don't want to echo all the chunks:

+ I have conditionally displayed text  in 'asis' chunks, and I don't want these echoed with the R code
+ If a chunk is not evaluated I don't want it included in the code section

I tried calling `all_labels()` with a condition but am getting errors in some cases and strange behavior with others.

Calling all_labels with engine=="R" gives an error from stringr::str_split:

    ```{r only_rcode, ref.label = all_labels(expression(engine == 'R')), eval = FALSE, echo = TRUE}
    ```

Error message when I knit:

    Error in stringr::str_split(string, ";|,")[[1]] : subscript out of bounds
    Calls: <Anonymous> ... call_block -> sc_split -> <Anonymous> -> stri_trim_both

However, specifying engine =='asis' works (no error and only echos asis chunks).

Specifying eval == TRUE does not give an error but only echos chunks where eval=TRUE is set in the chunk options, not those that are evaluated based on a document or global setting.  I'd like to be able to echo all chunks where eval is not explicitly set to FALSE.

The attached zip archive contians a full set of examples (including some that work as well as output from devtools::session_info(knitr).
[all_labels_test.zip](https://github.com/yihui/knitr/files/632823/all_labels_test.zip)

**Comment by yihui** [comment]
The error has been fixed. Thanks!

For `engine == 'R'`, you can test the condition `!exists('engine')` instead, e.g. `all_labels(!exists('engine'))`. It feels a little hacky but should work.

**Comment by dgJacks0n** [comment]
Thanks!

**Comment by dgJacks0n** [comment]
Using `all_labels(!exists('engine'))` with knitr 1.15.1.  It gets all the code chunks as long as one chunk has `eval = TRUE` in the chunk options.

**Comment by yihui** [comment]
I cannot reproduce what you said:

![image](https://cloud.githubusercontent.com/assets/163582/20938041/04ee6ed2-bbaf-11e6-93fb-98ad7a54ecac.png)

**Comment by dgJacks0n** [comment]
Updated test document attached reproduces the behavior on my system.  The .Rmd file knits on my system when chunk dummy_chunk has eval = TRUE but causes the stringr::str_split error when eval = FALSE.
[all_labels_tests_v2.zip](https://github.com/yihui/knitr/files/636870/all_labels_tests_v2.zip)

**Comment by yihui** [comment]
I still cannot reproduce it. Did you install the development version? Next time could you post `devtools::session_info('knitr')` along with your reproducible example? Thanks!
