### ISSUE TITLE
Underscores not converted to italics

### ISSUE THREAD

**Issue by mdlincoln** [yihui/knitr#1334]
Well this is a highly-specific bug, and I'm not %100 sure if it rests with knitr or rmarkdown.

When using `rmarkdown::render(output_type = pdf_document())`, figure captions with any italics marked with underscores cause a LaTeX error, but _only_ when the figure is generated using `knitr::include_graphics()`

Example:

    ---
    title: "Caption Test"
    ---

    ```{r formatted-plot, fig.cap="This caption has _italics_."}
    plot(iris)
    ```

    ```{r formatted-graphic, fig.cap="This caption has _italics_."}
    knitr::include_graphics("knit-logo.png")
    ```

This renders to a TeX file containing, among other elements:

``` tex
...
\begin{figure}
\centering
\includegraphics{try_caption_files/figure-latex/formatted-plot-1.pdf}
\caption{This caption has \emph{italics}.}
\end{figure}

...

\begin{figure}
\includegraphics[width=3.33in]{knit-logo} \caption{This caption has _italics_.}\label{fig:formatted-graphic}
\end{figure}
```

While the chunk using `plot()` correctly converted those caption underscores into `\emph{}`, the chunk with `knitr::include_graphics()` does not. This tex file creates the following error:

```
! Missing $ inserted.
<inserted text> 
                $
l.146 ...go} \caption{This caption has _italics_.}

pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
```

Interestingly, if instead I create an html doc with `render(output_type = html_document())`, the italics render fine:

``` html
...... alt="This caption has _italics_." width="240" />
<p class="caption">
This caption has <em>italics</em>.
</p>
</div>
```

![screen shot 2016-12-10 at 10 36 51 pm](https://cloud.githubusercontent.com/assets/4392604/21078565/2ab37608-bf29-11e6-98e9-9884a055179f.png)

**Comment by yihui** [comment]
What you reported here is the motivation of this feature in bookdown: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references So instead of `pdf_document`, please use `bookdown::pdf_document2` with text references.

**Comment by mdlincoln** [comment]
Thanks! I didn't know to look at that section of the bookdown docs - I kept looking in the section on Figures for relevant advice. I'll suggest an edit to the bookdown docs to see if we can clarify the connection between text references and figure captions.

**Comment by yihui** [comment]
That is a good idea, and pull requests for bookdown are welcome :)
