### ISSUE TITLE
Rstudio 1.0 version of knitr always prints data.tables

### ISSUE THREAD

**Issue by jeffwong-nflx** [yihui/knitr#1336]
I am using knitr from the recent Rstudio 1.0 release.

I have found if you are using the data.table package, every modification to a data.table is printed to the final output. This did not happen before, and a data.table would only print if you explicitly triggered a print via print(dt), head(dt), etc.  This is annoying because every new column definition generates a flood of text in the final output. Is there a way around this? Note that entering a new column definition into the R console would normally not print anything

Example 

    ---
    title: "foo"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    require(data.table)
    ```
    
    ```{r}
    foo = data.table(x = 1:10)
    foo[, y := x^2]
    foo[, z := y^2]
    ```

**Comment by Deleetdk** [comment]
Perhaps a hack solution is to use `invisible()` when setting columns.

**Comment by yihui** [comment]
Perhaps a7208ea23c8c9164dabcfa46eb1474bd08f36b16 is the culprit, but I don't have time to investigate this at the moment, and I don't fully understand the data.table magic to avoid printing in knitr documents.

**Comment by DaveRGP** [comment]
This is potentially related to https://github.com/rstudio/rmarkdown/issues/829

**Comment by yihui** [comment]
I just tested the above example and it seems the problem is no longer reproducible, although I'm not sure if it was data.table or rmarkdown that fixed it.
