### ISSUE TITLE
bug: improper placement of dynamic figures when fig_caption=true in pdf_document

### ISSUE THREAD

**Issue by faridcher** [yihui/knitr#1339]
reproducible example:

```
---
title: "Untitled"
author: "xxx"
date: "December 19, 2016"
output: 
    pdf_document:
        fig_caption: true
---

# section 1

## sub 1
some text

\```{r, fig.cap="caption2"}
plot(10:1)
\```

# section 2
```

the plot draws under section 2.

**Comment by faridcher** [comment]
Any updates? This is a serious bug! I can't use knitr anymore to create my dynamic pdf reports!!

**Comment by faridcher** [comment]
@yihui any updates?

**Comment by yihui** [comment]
Sorry I'm on vacation this week.

This is not a knitr bug, but a common LaTeX issue. In LaTeX, figures float by default: https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions

**Comment by faridcher** [comment]
I hope you enjoy your holidays. Is there any workaround?
