### ISSUE TITLE
Modify the or add a new vignette engine to build rst vignettes with pandoc instead of rst2pdf?

### ISSUE THREAD

**Issue by trevorld** [yihui/knitr#1341]
If desired I can probably write a patch but I'd like to know your implementation preferences (see below), CRAN/hadley has had issues with getting rst2pdf on some of their testing machines and I wonder if they are widely supporting pandoc now (are they?) then perhaps this would be more convenient all around.

1) Should this be done as the default rst vignette engine instead of rst2pdf and hence should I add a new rst2pdf engine for those who want it or keep the existing behavior and add this as a new engine?   Although the former would break reverse compatibility it might be the better default for CRAN and I'm not sure how many people besides me would be affected and I don't care as long as a nice document is produced in the end.

2) Would it be better to use knitr's pandoc utility conversion function or rmarkdown's pandoc utility conversion function to do the rst to html or pdf conversion?  Doing the latter would make the package author's need to suggest rmarkdown for a non-markdown vignette but would reinforce the pandoc dependency.

3) Would it make sense to generalize the knit2html function to handle non markdown files or easier to add a new function just for rst files that would be called when it detects an rst file (like it does now)?

**Comment by yihui** [comment]
I don't like rst2pdf, and I'd be very happy to get rid of it and use Pandoc if possible (someone else introduced it in knitr long time ago). So for 1, I'd say yes; for 2, let's use rmarkdown instead of `knitr::pandoc()` (the latter is also something I don't like); for 3, I don't like `knit2html`, either. I think rmarkdown has done an excellent job, and it should be very rare that users would need `knit2html` at all.

**Comment by trevorld** [comment]
I don't think ``rmarkdown`` has a function to directly support conversion of `rrst` to `html/pdf`.  I looked at ``rmarkdown::render`` and it has a bunch of markdown specific code.  So we'd need to update knitr's existing functions or write new functions that first converts `rrst` to `rst` with ``knitr::knit`` and then calls ``rmarkdown::pandoc_convert`` to convert the ``rst`` to either an ``html`` or ``pdf`` file.

**Comment by yihui** [comment]
Good point!

I probably won't have time for this in the next couple of weeks, but if your pull request looks simple enough, I may be able to merge it soon. Thanks!
