### ISSUE TITLE
how to automatically get  #+ in my R script?

### ISSUE THREAD

**Issue by randomgambit** [yihui/knitr#1342]
Hello there!

My understanding is that `knitr` allows me to work on my R script, while keeping the ability to generate a full document that understand markdown syntax

It looks like the following:

#' This is a special R script which can be used to generate a report. You can
#' write normal text in roxygen comments.
#'
#' First we set up some options (you do not have to do this):

#+ setup, include=FALSE
library(knitr)

My only problem here is that it is super inefficient to add `#'` after each line of text. Is there a way to do so automatically? Am I missing something?

Thanks!

**Comment by randomgambit** [comment]
follow up here https://stackoverflow.com/questions/41538022/knitrspin-how-to-add-text-without-manually-adding-every-line

**Comment by yihui** [comment]
Trying StackOverflow is definitely the right thing to do before posting a question here 👍
