### ISSUE TITLE
purl does not output inline code

### ISSUE THREAD

**Issue by kforner** [yihui/knitr#1344]
Hi,

I noticed that purl() does not seem to extract the inline R expressions. 
It would be extremely useful, at least for me, to have access to all R code included in a document, at least as knitr recognize it. The use case is code analysis for instance. 

With documentation == 2, the inline code is found, but commented out, so it is difficult to distinguish it from other comments.

From what I understood from the code, it seems that it could be done by modifying a bit this function https://github.com/yihui/knitr/blob/115e994b332c2d36a598a6ea12ddb639478c266b/R/block.R#L462 

```
process_tangle.inline = function(x) {
  if (opts_knit$get('documentation') == 2L) {
    return(paste(line_prompt(x$input.src, "#' ", "#' "), collapse = '\n'))
  }
  code = x$code
  if (length(code) == 0L || !any(idx <- grepl('knit_child\\(.+\\)', code)))
    return('')
  paste(c(sapply(code[idx], function(z) eval(parse_only(z))), ''), collapse = '\n')
}
```

and more particularly this line: 
```
  if (length(code) == 0L || !any(idx <- grepl('knit_child\\(.+\\)', code)))
    return('')
```
Changing it to something like "`return(as.character(code))`"  should probably do the trick. 
Would you accept a Pull Request ? 

Thanks.

**Comment by yihui** [comment]
I don't remember why I excluded inline code, but if I were to make this change, I will have to do a reverse dependency check first to make sure no CRAN packages will be broken. This is a rather tedious job, and I die a little inside every time I do it.

In general, inline code is supposed to be a single variable or simple expression writing out a single value. I'm not sure how important it is to your code analysis.

**Comment by kforner** [comment]
> I don't remember why I excluded inline code, but if I were to make this change, I will have to do a > reverse dependency check first to make sure no CRAN packages will be broken. This is a rather tedious job, and I die a little inside every time I do it.

I perfectly understand the problem. Could we implement the new behaviour via an option ? Either adding a value to documentation (but that is a little hacky), or adding a new option/param in purl ? 

> In general, inline code is supposed to be a single variable or simple expression writing out a single value. I'm not sure how important it is to your code analysis.

The problem is that you can have calls to knit_child(), that are critical to know that the document has children, and you can also have calls to functions in other packages, that one could need to track.

 I could work-around it, but I suppose that if I need this, it could also benefit to other people. It is nice to be able to reuse the exact knitr parsing engine.

**Comment by yihui** [comment]
A new option sounds like a good idea to me (something like `options(knitr.purl.inline = TRUE)`).
