### ISSUE TITLE
knitr or Markdown issue... kable() in beamer slides does not produce latex table unless explicitly told...

### ISSUE THREAD

**Issue by JeffreyRacine** [yihui/knitr#1347]
Greetings,

Using beamer/markdown tables are sprawling off of the right of the slide and only show properly with the option format="latex" hard coded... I presume it ought to be automatic? Minimal example follows (requires the forecast package be installed)... 

Thanks!

    ---
    output: beamer_presentation
    ---
    
    ```{r,warning=FALSE,echo=FALSE,message=FALSE}
    require(forecast)
    data(lynx)
    ## Create training and testing series using the window() function
    lynx.train <- window(lynx,end=1928)
    lynx.test <- window(lynx,start=1929)
    ## Fit an arbitrary model on the training series
    model <- arima(lynx.train,order=c(1,0,0))
    ## Compute forecasts
    fit <- forecast(model,h=6)
    ## Assess the model's forecast performance on the test series
    ## using the accuracy() function
    knitr::kable(accuracy(fit,lynx.test)[,c(2,3),drop=FALSE],caption="$\\operatorname{ARIMA}(1,0,0)$ (no format=)",escape=FALSE)
    ```
    
    ```{r,warning=FALSE,echo=FALSE,message=FALSE}
    require(forecast)
    data(lynx)
    ## Create training and testing series using the window() function
    lynx.train <- window(lynx,end=1928)
    lynx.test <- window(lynx,start=1929)
    ## Fit an arbitrary model on the training series
    model <- arima(lynx.train,order=c(1,0,0))
    ## Compute forecasts
    fit <- forecast(model,h=6)
    ## Assess the model's forecast performance on the test series
    ## using the accuracy() function
    knitr::kable(accuracy(fit,lynx.test)[,c(2,3),drop=FALSE],caption="$\\operatorname{ARIMA}(1,0,0)$ (format=latex)",escape=FALSE,format="latex")
    ```

**Comment by yihui** [comment]
This is what I see from your example:

![image](https://cloud.githubusercontent.com/assets/163582/22093746/ad9f3008-ddcd-11e6-9d79-0d59e8d4e763.png)

**Comment by JeffreyRacine** [comment]
Yes indeed… the top is HTML, the bottom LaTeX… since Beamer is producing a PDF via LaTeX, should not the default table be for LaTeX? This would be consistent with creating a standard R
 Markdown document which, when rendered in PDF uses \begin{table}… for the table?
 
Thanks! You are doing truly great work.
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: yihui/knitr <reply@reply.github.com>
Date: Wednesday, January 18, 2017 at 23:30
To: yihui/knitr <knitr@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [yihui/knitr] knitr or Markdown issue... kable() in beamer slides does not produce latex table unless explicitly told... (#1347)


 

This is what I see from your example:

—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by yihui** [comment]
Sorry, I read your post and reply a couple of times and still didn't get it. Without `format='latex'`, you do get a table in the beamer PDF output, as I showed in my screenshot above. What exactly is the problem you were trying to report? Could you show your output and highlight the part that is wrong?

BTW, could you do me a favor to reply on Github in the future instead of by email? Because every time you reply by email, there is some garbage CSS code, which seems to be generated from a certain Microsoft product (I had to delete it every time):

```
<!-- 
/* Font Definitions */ 
@font-face 
{font-family:"Cambria Math"; 
panose-1:2 4 5 3 5 4 6 3 2 4;} 
@font-face 
{font-family:Calibri; 
panose-1:2 15 5 2 2 2 4 3 2 4;} 
/* Style Definitions */ 
p.MsoNormal, li.MsoNormal, div.MsoNormal 
{margin:0cm; 
margin-bottom:.0001pt; 
font-size:12.0pt; 
font-family:"Times New Roman";} 
a:link, span.MsoHyperlink 
{mso-style-priority:99; 
color:blue; 
text-decoration:underline;} 
a:visited, span.MsoHyperlinkFollowed 
{mso-style-priority:99; 
color:purple; 
text-decoration:underline;} 
p 
{mso-style-priority:99; 
mso-margin-top-alt:auto; 
margin-right:0cm; 
mso-margin-bottom-alt:auto; 
margin-left:0cm; 
font-size:12.0pt; 
font-family:"Times New Roman";} 
span.EmailStyle18 
{mso-style-type:personal-reply; 
font-family:Calibri; 
color:windowtext;} 
span.msoIns 
{mso-style-type:export-only; 
mso-style-name:""; 
text-decoration:underline; 
color:teal;} 
.MsoChpDefault 
{mso-style-type:export-only; 
font-size:10.0pt;} 
@page WordSection1 
{size:612.1pt 792.1pt; 
margin:36.0pt 50.45pt 36.0pt 50.45pt;} 
div.WordSection1 
{page:WordSection1;} 
--> 
```

**Comment by JeffreyRacine** [comment]
Apologies for not being clearer.

As I understand things, if I create an R Markdown document with tables and render it in PDF, it creates latex tables using \begin{table} etc. This is confirmed by setting keep_tex: true and examining the tex file. The same markdown document rendered in HTML produces HTML tables etc.

Now, if I create Beamer slides, which are output in PDF by default and are rendered in latex, tables get rendered in HTML as you realize in your screenshot.

My point was that this is inconsistent and undesirable from my point of view. The beauty of your framework is that you don't need to use format="latex" explicitly because when you render a document in PDF things like your beautiful kable() function automatically detect the PDF output and render the table in latex. Beamer does not and having to explicitly type format="latex" when using kable() to produce beamer slides strikes me as unwanted and undesirable.

Thanks!

**Comment by yihui** [comment]
> Now, if I create Beamer slides, which are output in PDF by default and are rendered in latex, **tables get rendered in HTML** as you realize in your screenshot.

I don't know what you mean by "tables get rendered in HTML". When the output format is beamer, you do get a LaTeX table instead of an HTML table.

Perhaps you are talking about the appearance of the LaTeX table? My screenshot above was produced by Pandoc 1.17.2, and I just tested Pandoc 1.19.1, the LaTeX table looks a little bit different in style -- its width becomes 100%:

![image](https://cloud.githubusercontent.com/assets/163582/22117738/bbb48ba8-de3a-11e6-9399-9a046f3fb1fa.png)

There is certainly a change from Pandoc 1.17.2 to 1.19.1, but I don't have control over Pandoc. The only thing I can tell you is you can set this option to force LaTeX table output when the document output format is LaTeX:

```r
knitr::opts_knit$get(kable.force.latex = TRUE)
```

**Comment by JeffreyRacine** [comment]
My bad!

Thanks, this was exactly the problem I encountered... and apologies yes they both get rendered using latex... but why are they so different is what bothered me... I will use the force.latex=TRUE... 

keep_tex: true produces quite different tables as you see below....

Appreciate your time!

```
\begin{frame}

\begin{longtable}[]{@{}lrr@{}}
\caption{\(\operatorname{ARIMA}(1,0,0)\) (no format=)}\tabularnewline
\toprule
\begin{minipage}[b]{0.32\columnwidth}\raggedright\strut
\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\raggedleft\strut
RMSE\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\raggedleft\strut
MAE\strut
\end{minipage}\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.32\columnwidth}\raggedright\strut
\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\raggedleft\strut
RMSE\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\raggedleft\strut
MAE\strut
\end{minipage}\tabularnewline
\midrule
\endhead
Training set & 1119.604 & 812.8895\tabularnewline
Test set & 1027.052 & 755.4432\tabularnewline
\bottomrule
\end{longtable}

\begin{table}

\caption{\label{tab:unnamed-chunk-2}$\operatorname{ARIMA}(1,0,0)$ (format=latex)}
\centering
\begin{tabular}[t]{l|r|r}
\hline
  & RMSE & MAE\\
\hline
Training set & 1119.604 & 812.8895\\
\hline
Test set & 1027.052 & 755.4432\\
\hline
\end{tabular}
\end{table}

\end{frame}
```

**Comment by yihui** [comment]
No worries. As I said, the table produced by Pandoc 1.17.2 seems to be fine. I'm still reading the Pandoc release notes to figure out what happened in the last few months.
