### ISSUE TITLE
Kable produces longtable that is not compatible with "\twocolumn" documentclass option

### ISSUE THREAD

**Issue by junchenfeng** [yihui/knitr#1348]
I want to produce a table in a two-column article. However I tweaked it (such as result="asis"), knitr still reports the following error when converting to pdf.

     ! Package longtable Error: longtable not in 1-column mode.

**Comment by junchenfeng** [comment]
Ok, I found [this thread](https://github.com/jgm/pandoc/issues/1023) on the pandoc project. It is an issue with pandoc and there is no good workaround. I close this issue because it is unrelated to knitr

**Comment by JosiahParry** [comment]
I just encountered this issue while setting `classoption: - twocolumn` in the YAML header. Has this been resolved?

**Comment by cderv** [comment]
Have you look at the thread in pandoc linked from above https://github.com/yihui/knitr/issues/1348#issuecomment-272724121 ? 

`longtable` and two column mode don't play well together in Latex. Pandoc use `longtable` for table environment. I don't think there is anything to do in knitr. Look at answers in Pandoc thread discussions. There is not generic answer but maybe some specific workaround that may work for you.
