### ISSUE TITLE
knitr::kable renders messed up table if following a bullet or using centered alignment

### ISSUE THREAD

**Issue by jar1karp** [yihui/knitr#1349]
Knitted pdf attached.

[asdasd.pdf](https://github.com/yihui/knitr/files/708150/asdasd.pdf)

This is reproducible also if knitting to html slides (e.g. slidy_presentation). The bug seems to be related to the bullet point preceding the table: if you remove the `-` the table will render correctly. Also, if you change the first column alignment to 'l' it seems to work. But changing it to 'r' messes the table up.

Here is a minimal example to reproduce the problem:

```
---
output: pdf_document
---

## Buggy table

- From 1972 to 2011, momentum strategies that buy winners and sell losers, and which are formed based on the past twelve month returns, generate significant momentum premia:

```{r, echo=FALSE}
df <- tibble::data_frame(`Market`=c('U.S. Stocks', 'UK Stocks', 'Europe Stocks', 'Japan Stocks'),
                         `Average returns (%)`=c(7.7, 7.2, 9.8, 2.2),
                         `Sharpe ratio`=c(0.45, 0.48, 0.75, 0.13))
knitr::kable(df, align=c('c','c','c'))
```
```

**Comment by yihui** [comment]
I have filed an issue to pandoc https://github.com/jgm/pandoc/issues/3364 Before I receive a response, you can use the pipe tables instead of the default simple tables:

```r
knitr::kable(df, format='markdown', align=c('c','c','c'))
```

**Comment by yihui** [comment]
The Pandoc author provided another solution, which is to add an HTML comment after the bullet:

    ---
    output: pdf_document
    ---
    
    - From 1972 to 2011, momentum strategies that buy winners and sell losers, and which are formed based on the past twelve month returns, generate significant momentum premia:
    
    
    
    ```{r, echo=FALSE}
    df <- tibble::data_frame(`Market`=c('U.S. Stocks', 'UK Stocks', 'Europe Stocks', 'Japan Stocks'),
                             `Average returns (%)`=c(7.7, 7.2, 9.8, 2.2),
                             `Sharpe ratio`=c(0.45, 0.48, 0.75, 0.13))
    knitr::kable(df, align=c('c','c','c'))
    ```
