### ISSUE TITLE
How can I create/use a PHP engine

### ISSUE THREAD

**Issue by ricpelo** [yihui/knitr#1350]
I know there're some engines for languages like sql, perl, python and so. I wonder if there's a way to create and use a PHP engine.

(Posted in http://stackoverflow.com/questions/41681630/how-can-i-create-use-a-php-engine)

**Comment by yihui** [comment]
I don't know how to run PHP code via command line from R, but this is definitely where you should get started if you want to work on it: https://github.com/yihui/knitr/blob/master/R/engine.R

**Comment by ricpelo** [comment]
Hi, @yihui,

The PHP interpreter works the same as Python, Perl or Ruby: there's a `/usr/bin/php` interpreter which you can use like `/usr/bin/php script.php`. Sorry about not looking at `engine.R` file because I don't have the knowledge to modify a R script :(.

**Comment by yihui** [comment]
You are welcome to submit a pull request when you figure out how to run php like other engines (python, perl, ruby, ...). I'm closing this issue for now since I probably will not add this engine myself. Thanks!
