### ISSUE TITLE
out.width= chunk option and escaped character in include_graphics filepath generate broken .tex file

### ISSUE THREAD

**Issue by ajdamico** [yihui/knitr#1351]
hi, it looks like the escaping a folderpath combined with `out.width=` triggers some illegal latex code?  here's a minimal reproducible example of an Rmd file.

when i run this in bookdown and look at the `.tex` file, the graphics path has chopped off the `.png`.  thanks yihui!

	---
	output:
	  pdf_document: default
	  html_document: default
	---

	```{r echo = FALSE}
	dir.create( "C:/My Dir")
	dir.create( "C:/My Dir)")
	download.file( "https://www.r-project.org/logo/Rlogo.png" , "C:/My Dir/exhibit.png", mode='wb')
	file.copy( "C:/My Dir/exhibit.png" , "C:/My Dir)/exhibit.png")

	```

	this works

	```{r chunk0-fig, fig.cap='Figure 1.9'}
	knitr::include_graphics( "C:/My Dir\\)/exhibit.png" )
	```

	this works

	```{r chunk1-fig, out.width="80%" , fig.cap="Figure 2.0" }
	knitr::include_graphics( "C:/My Dir/exhibit.png" )
	```

	this fails

	```{r chunk2-fig, out.width="80%" , fig.cap="Figure 2.1" }
	knitr::include_graphics( "C:/My Dir\\)/exhibit.png" )
	```

	
		
sessionInfo()

	R version 3.3.2 (2016-10-31)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows Server >= 2012 x64 (build 9200)

	locale:
	[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
	[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	loaded via a namespace (and not attached):
	 [1] backports_1.0.4 magrittr_1.5    rprojroot_1.1   htmltools_0.3.5 tools_3.3.2     yaml_2.1.14     Rcpp_0.12.8    
	 [8] stringi_1.1.2   rmarkdown_1.2   knitr_1.15.1    stringr_1.1.0   digest_0.6.11   evaluate_0.10

**Comment by yihui** [comment]
In general, I'd suggest you avoid full paths like `C:/...` and special characters in file paths. While I might be able to get this fixed at some point, I definitely don't enjoy fixing issues like this one :)

**Comment by schuemie** [comment]
I think this is a related problem, but now with emphasis in the caption instead of escaping paths:
~~~
---
title: "Untitled"
output: pdf_document
---

This works:

```{r, fig.cap="Data from Jones _et al_."}
df <- data.frame(
  x = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ggplot2::ggplot(df, ggplot2::aes(x=x, y=y)) +
  ggplot2::geom_point() 
```


This works:

```{r, out.width="8.7cm", fig.cap="Data from Jones et al."}
df <- data.frame(
  x = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ggplot2::ggplot(df, ggplot2::aes(x=x, y=y)) +
  ggplot2::geom_point() 
```

This fails:

```{r, out.width="8.7cm", fig.cap="Data from Jones _et al_."}
df <- data.frame(
  x = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ggplot2::ggplot(df, ggplot2::aes(x=x, y=y)) +
  ggplot2::geom_point() 
```
~~~

The error message is:
```
! Missing $ inserted.
<inserted text> 
                $
l.171 ...k-3-1} \caption{Data from Jones _et al_.}

pandoc.exe: Error producing PDF
Error: pandoc document conversion failed with error 43
```

sessionInfo()
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] backports_1.0.5 magrittr_1.5    rprojroot_1.2   rsconnect_0.6   htmltools_0.3.6 tools_3.3.1     yaml_2.1.14     Rcpp_0.12.9    
 [9] stringi_1.1.5   rmarkdown_1.5   knitr_1.15.1    stringr_1.2.0   digest_0.6.12   evaluate_0.10  
```

**Comment by yihui** [comment]
@schuemie Markdown syntax is not supported in figure captions. Your only choice at the moment is to use the output format `bookdown::pdf_document2` and the text reference syntax: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references

**Comment by schuemie** [comment]
Thanks! Someone else also pointed out to me that this works:
```
fig.cap="Data from Jones \\textit{et al}"
```

**Comment by yihui** [comment]
That works if your only possible output format is LaTeX. The solution I mentioned is portable, but you probably don't care.

**Comment by schuemie** [comment]
You're right, I'm already happy with the non-portable solution ;-)

Just to have it documented somewhere, one more unexpected side-effect of using `out.width`: This code for generating the pdf no longer works:
```r
rmarkdown::render("Rmd/Manuscript.Rmd",
                  output_file = "../Pdf/Manuscript.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex"))
```
because of the '../'. I've now worked around it by using:
```r
rmarkdown::render("Rmd/Manuscript.Rmd",
                  rmarkdown::pdf_document(latex_engine = "pdflatex"))
shell("mv rmd/Manuscript.pdf pdf/Manuscript.pdf")
```
