### ISSUE TITLE
Issue with tikzDevice for figures generated in a knitr chunk and running LuaTeX

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [yihui/knitr#1353]
I might have found a corner case : a figure created in a knitr chunk using tikzDevice and compiled by LuaLaTeX is shifted to the top almost off the "figure page" (only a small part of the bottom o the figuue is shown), whereas : 
* The same image directly created "by hand" on the tikzDevice is correct
* The same file (modulo the support packages), compiled with PDFTeX, is entierely correct.

The examination of the log files did not reveal anything to my (admittedly profane) eyes... The fact that the figure manually generated is correct let me think that the problem is in the handling of the figure by knitr.

I have attached a complete tree of the demonstration of the problem.

[ChkTikz.zip](https://github.com/yihui/knitr/files/721799/ChkTikz.zip)

**Comment by yihui** [comment]
Thanks for the report! Unfortunately I'm not familiar with LuaTeX, and I don't know what happened in this case after I tried your example.

**Comment by EmmanuelCharpentier** [comment]
Le mardi 24 janvier 2017 à 12:10 -0800, Yihui Xie a écrit :
> Thanks for the report! Unfortunately I'm not familiar with LuaTeX,
> and I don't know what happened in this case after I tried your
> example.

1) Were you able to reproduce the problem ?
2) Where do you think I could get expertise on this aspect of LuaTeX ?
Sincerely yours,

**Comment by yihui** [comment]
Yes, I think I was able to reproduce the problem, although I had to delete the font specs (`\setmainfont`) and install a few missing LaTeX packages.

If you want to help, here is the line where the tikz file is compiled to PDF: https://github.com/yihui/knitr/blob/b936c1e2e/R/plot.R#L142 You can put a `browser()` there, inspect the .tikz file to see if there is anything wrong, and try to compile it to PDF manually.

**Comment by EmmanuelCharpentier** [comment]
Le mardi 24 janvier 2017 à 14:19 -0800, Yihui Xie a écrit :
> Yes, I think I was able to reproduce the problem, although I had to
> delete the font specs (\setmainfont) and install a few missing LaTeX
> packages.
> 
> If you want to help, here is the line where the tikz file is compiled
> to PDF: https://github.com/yihui/knitr/blob/b936c1e2e/R/plot.R#L142
> You can put a browser() there, inspect the .tikz file to see if there
> is anything wrong, and try to compile it to PDF manually.

Thanjk you very much ! I'll try to look at this (not on the next few
days, alas...
I also mailed the luatex list for ideas (and gave the Google drive
adresst of a copy of the tarball). Do you care for a copy of their
answers ?
Sincerely,
> 
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/yihui/kni
> tr","title":"yihui/knitr","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/yihui/knitr"}},"updates":{"snippets
> ":[{"icon":"PERSON","message":"@yihui in #1353: Yes, I think I was
> able to reproduce the problem, although I had to delete the font
> specs (`\\setmainfont`) and install a few missing LaTeX
> packages.\r\n\r\nIf you want to help, here is the line where the tikz
> file is compiled to PDF:
> https://github.com/yihui/knitr/blob/b936c1e2e/R/plot.R#L142 You can
> put a `browser()` there, inspect the .tikz file to see if there is
> anything wrong, and try to compile it to PDF
> manually."}],"action":{"name":"View
> Issue","url":"https://github.com/yihui/knitr/issues/1353#issuecomment
> -274957745"}}}

**Comment by yihui** [comment]
I can take a look, but I'm afraid I don't have much time for this issue before someone pins down the root problem and it becomes clear to me what I should fix.

**Comment by EmmanuelCharpentier** [comment]
I think that this simplified example  pinpoints the problem in the LuaLatEx/tikz camp : (almost) identical .tex and .tikz files, wildly different .pdf results...

HTH.

[tikz-LuaTeX-vs-PDFLaTeX.zip](https://github.com/yihui/knitr/files/735352/tikz-LuaTeX-vs-PDFLaTeX.zip)

**Comment by EmmanuelCharpentier** [comment]
To my surprise, XeLaTeX works well for knitr-generated figures. This le me to explore a bit what preview.sty does. It has a XeTeX-specific option, which generates a different type of image (which I do not pretend to understand...).

This led me to think that a possible fix might be to remove the "psfixbb" option passed to preview. The enclosed tree let me think that it might at least have the right side effect : withut my workaround, I get a garbled image, misplaced in the doc. With it, the image and the dociment are correct. However, "psbbfix" is *still* passed to preview...

Maybe this will lead to the real problem ?

HTH,

[PossibleFix.zip](https://github.com/yihui/knitr/files/736479/PossibleFix.zip)

**Comment by yihui** [comment]
It sounds like the problem needs to be fixed in tikzDevice? https://github.com/yihui/tikzDevice/

**Comment by EmmanuelCharpentier** [comment]
> It sounds like the problem needs to be fixed in tikzDevice? 

Possibly. But the workaround may be useful in interim.

Do you care for an issue formally filed against tikzDevice ?

**Comment by yihui** [comment]
I don't know, unless someone can figure out a fix.

**Comment by EmmanuelCharpentier** [comment]
I got an [answer](https://groups.google.com/d/msg/comp.text.tex/umzerAdDkX0/Q2j70LwNBwAJ) from com.text.tex : 

> You should add \usepackage{luatex85} to Graph1-1.tikz **before**
loading the preview package.

> But be aware that preview hasn't been updated for years, and that
there is no garanty that it works with luatex.

> Btw: Don't load xunicode. It is not necessary and will give errors
with the newest fontspec.

I'll try that and adapt it.

**Comment by EmmanuelCharpentier** [comment]
The following workaround seems to work : 
```
<<Graphe1, dev="tikz", echo=FALSE>>=
options(tikzDefaultEngine="luatex")
setTikzDefaults()
local({
    foo <- options("tikzLualatexPackages")
    bar <- gsub(",xunicode","",foo[[1]])
    foo <- c(bar[1], "\\usepackage{luatex85}\n",bar[-1])
    options(tikzLualatexPackages=foo)
})
curve(sin(x),from=-pi, to=pi, main="En provenance de Lua\\LaTeX\\dots")
@ 
```

It needs to be tested and polished a bit more : 

1. I think that the `\\usepackage{liatex85}` should be the first line, not the second (or possibly even higher in the file).
2. it should be conditional on `LuaLaTeX` version.
2. Something probably needs to be done to set a default font.
3. The elimination of `xunicode` probably also applies to `XeLaTeX` but should be conditional on `fontspec` version.

But that seems to be (part of) the solution.

This may be important, since, as far as I understand, \LuaTeX is bound to become the default \TeX engine someday...

HTH,

**Comment by onnokleen** [comment]
Hey,

I just ran into the same problem. For me the following combination of the standalone documentclass and lualatex (v0.95.0) worked fine. Using standalone, one can leave the preview-package behind. However, make sure to choose crop=true. The luatex85-package seems to be necessary as well, at least in my setup.

```R
library(tikzDevice)
library(ggplot2)
options(tikzDocumentDeclaration = "\\documentclass[tikz,crop=true]{standalone}")

options(tikzLatexPackages = c(
  "\\usepackage{amsmath}",
  "\\usetikzlibrary{calc}",
  "\\usepackage{luatex85}") # plus your other packages)

tikz(standAlone = TRUE)
ggplot() + 
  geom_line(aes(x = c(1:3), y = c(4:6)))
dev.off()
system("lualatex Rplots.tex", wait = FALSE)
``` 

Btw: Thank for knitr!

**Comment by krlmlr** [comment]
Can you please try the dev version of tikzDevice?

**Comment by onnokleen** [comment]
@krlmlr Do you mean trying my version or inside a knitr chunk? At least the former is working fine for me. (sorry, there was a closing bracket missing in my minimal example above - I corrected it)

```R
library(devtools)
dev_mode(on = TRUE)

install_github("yihui/knitr")
install_github( 'yihui/tikzDevice' )

library(tikzDevice)
library(ggplot2)
options(tikzDocumentDeclaration = "\\documentclass[tikz,crop=true]{standalone}")

options(tikzLatexPackages = c(
  "\\usepackage{amsmath}",
  "\\usetikzlibrary{calc}",
  "\\usepackage{luatex85}")) # plus your other packages))
  
tikz(standAlone = TRUE)
  ggplot() + 
    geom_line(aes(x = c(1:3), y = c(4:6)))
dev.off()
system("lualatex Rplots.tex", wait = FALSE)

dev_mode(on = FALSE)
```

**Comment by krlmlr** [comment]
The dev version of tikzDevice now loads the luatex85 LaTeX package by default if it is available and if you use `engine = "luatex"`: https://github.com/yihui/tikzDevice/commit/44a8ca11d3bc1ecb46a31e2436f0b7e1e50c61a1.

**Comment by onnokleen** [comment]
Good to know - however, I explicitly did not choose ```engine = "luatex"``` because I sometimes had problems with calculating metrics for a figure when changing the LaTeX-engine but I'll give it a try with the next stable release of tikzDevice. Unfortunately, I never found out what the problem with those figures were.

**Comment by EmmanuelCharpentier** [comment]
One year after : the issue seems to have been solved by tikzDevice and luatex updates. I close this issue, but feel free to reopen if you think that it is not completely solved.
