### ISSUE TITLE
render multiple resolutions for bitmap engines

### ISSUE THREAD

**Issue by maxheld83** [yihui/knitr#1354]
It appears to me that upstream uses of `knitr`, especially when they are outputting to HTML such as `bookdown` ([this issue](https://github.com/rstudio/bookdown/issues/316)) and `blogdown`([this issue](https://github.com/rstudio/blogdown/issues/46) might require *several* resolution versions of bitmap assets, for example to support responsive images (say, download a different filesize depending on the viewport).

I think this is not presently possible, hope I am not wrong.
Unfortunately, I am a little bit confused of how or where (in `knitr`?) this could be implemented, but I hope it's at least a worthwhile thought.

Perhaps, `knitr` could learn to accept a *vector* of resolutions for `dpi`, and then upstream functions such as `blogdown` or `bookdown` could supply reasonable default sets of DPIs, to which `knitr` could render?

Ps.: There is also a more limited use case for this when non-R raster images are included via `include_graphics()`. When the bitmap is large, we might want quite *different* resolutions for a PDF output, and an HTML output, where load times matter more. This would require re-sizing in R as per [this issue](https://github.com/yihui/knitr/issues/1273), and is probably a really *niche* use case.

**Comment by yihui** [comment]
As mentioned in https://github.com/rstudio/bookdown/issues/316, I don't think I'll ever have the time to implement this and personally I don't have much interest in it, so I'd say you have to do it by yourself if you really want it. The knitr hook system is fairly open. Thanks for the suggestion, though.
