### ISSUE TITLE
knitr::include_graphics cannot yield sub-figures

### ISSUE THREAD

**Issue by Selbosh** [yihui/knitr#1355]
I cannot get sub-captions/sub-figures to work with `knitr::include_graphics()`, even though it works with other R-generated plots.

The following just produces two separate figures with the main caption (the subcaps being ignored).

``````r
```{r fig.cap = 'Main caption', fig.subcap = c('First sub-figure', 'Second sub-figure')}
knitr::include_graphics('foo.png')
knitr::include_graphics('bar.png')
```
``````

whereas this correctly produces sub-figures:

``````r
```{r fig.cap = 'Main caption', fig.subcap = c('First sub-figure', 'Second sub-figure')}
plot(rnorm(10)) # arbitrary plot generated in R
plot(rnorm(10)) # ditto
```
``````

In both cases I have the following in the YAML header:

```yaml
---
# ...
output: pdf_document
header-includes: \usepackage{subfig}
---
```

**Comment by RichardJActon** [comment]
I am having a similar problem:

```{r label, fig.cap='(ref:caption)', out.width='50%', fig.show='hold', echo=FALSE}
knitr::include_graphics("figs/foo.png")
knitr::include_graphics("figs/bar.png")
```

produces two separate figures with the caption duplicated rather than 2 figures side by side

**Comment by fleharty** [comment]
I also have the same exact issue.

**Comment by mathematicalcoffee** [comment]
Try doing

```
knitr::include_graphics(c("figs/foo.png", "figs/bar.png"))
```

**Comment by yihui** [comment]
Thanks @mathematicalcoffee. That should work with the current development version of **knitr**.

To all, the same question was asked and answered here: https://github.com/yihui/knitr/pull/1444#issuecomment-346459014
