### ISSUE TITLE
Segfault in replayPlot with grdevices::cairo_pdf when mixing grid and base graphics

### ISSUE THREAD

**Issue by dondelelcaro** [yihui/knitr#1356]
With cairo_pdf output, mixing grid and base graphics fails in replayPlot with a segfault because `dd->deviceSpecific` is not initialized properly. Switching to CairoPDF or a different output device seems to fix the issue. I'm not sure if this is a bug in replayPlot or something wrong in grDevices::cairo_pdf.

## Failing example
```{r}
<<load.libraries,echo=FALSE,results="hide",warning=FALSE,message=FALSE,error=FALSE>>=
opts_chunk$set(dev="cairo_pdf")
@ 
<<simple_failing_example>>=
library("grid")
plot(1)
grid.text("A")
@ 
```

## Working example
```{r}
<<load.libraries,echo=FALSE,results="hide",warning=FALSE,message=FALSE,error=FALSE>>=
opts_chunk$set(dev="CairoPDF")
@ 
<<simple_working_example>>=
library("grid")
plot(1)
grid.text("A")
@ 
```

**Comment by yihui** [comment]
Thanks! I just reported it to R core: https://stat.ethz.ch/pipermail/r-devel/2017-February/073770.html
