### ISSUE TITLE
Kable does not render correctly in latex

### ISSUE THREAD

**Issue by junchenfeng** [yihui/knitr#1358]
I inserted a table in bookdown with the following code:

`
```{r, echo=FALSE,message=FALSE,warning=FALSE}
kable(
  ans_composition %>% arrange(qtype,group) %>% select(-blank,-nonblank), 
  col.names=c('Group','Task','Wrong Shape', 'Wrong Area', 'Wrong Circumference', 'Slip'),
  align='c', booktabs = TRUE,
  caption = 'Answer Composition (%) - Partial Correct'
)
```
`

The resulting latex rendering is 

\begin{table}
\caption{Answer Composition (%) - Partial Correct}
Group Task Wrong Shape Wrong Area Wrong Circumference Slip
Control pre 8.80 8.84 11.23 1.095
Treatment pre 7.70 8.89 11.00 0.733
Control train 5.07 5.35 12.16 0.324
Treatment train 3.53 4.90 12.47 0.367
Control post 1.91 7.54 6.49 4.420
Treatment post 1.60 7.10 7.47 4.812
\end{table}

It actually prints "\begin{table}" and "\end{table}" onto the page. The preceding and the following table are rendered correctly.

I guess there must be something funny in my table content/code that bugs the kable function.

PS:
This is the knitr latex output

```
\textbackslash{}begin\{table\}

\textbackslash{}caption\{\label{tab:unnamed-chunk-73}Answer Composition (\%)
- Partial Correct\} \centering

\begin{tabular}[t]{cccccc}
\toprule
Group & Task & Wrong Shape & Wrong Area & Wrong Circumference & Slip\\
\midrule
Control & pre & 8.80 & 8.84 & 11.23 & 1.095\\
Treatment & pre & 7.70 & 8.89 & 11.00 & 0.733\\
Control & train & 5.07 & 5.35 & 12.16 & 0.324\\
Treatment & train & 3.53 & 4.90 & 12.47 & 0.367\\
Control & post & 1.91 & 7.54 & 6.49 & 4.420\\
Treatment & post & 1.60 & 7.10 & 7.47 & 4.812\\
\bottomrule
\end{tabular}

\textbackslash{}end\{table\}
```

**Comment by junchenfeng** [comment]
I believe it has something to do with "%" in caption

**Comment by yihui** [comment]
I think you are right. Does `\\%` work?

**Comment by yihui** [comment]
Actually I recommend you to use text references instead of escaping the special characters: https://github.com/rstudio/bookdown/issues/350
