### ISSUE TITLE
knitr::include_graphics page numbers

### ISSUE THREAD

**Issue by sheltonmath** [yihui/knitr#1361]
It would be very helpful if we could add page numbers within the knit::include_graphics command or as a chunk option. For example, I would like to include pages of a pdf as a figure in my documents.

This works, but only for pdf output:
\includegraphics[page=1]{images/alignment.pdf}
\includegraphics[page=2]{images/alignment.pdf}

I would prefer to do something like this with knit::include_graphics:

    ```{r, page = 1}
    include_graphics("images/alignment.pdf")
    ```

I read through the knitr::include_graphics documentation and unfortunately could not find an option for indicating page number.

**Comment by yihui** [comment]
You can use the chunk option `out.extra`, e.g.

    ```{r out.extra='page=1'}
    knitr::include_graphics('images/alignment.pdf')
    ```

    ```{r out.extra='page=2'}
    knitr::include_graphics('images/alignment.pdf')
    ```

You can probably use vectors as well (not tested):

    ```{r out.extra=c('page=1', 'page=2')}
    knitr::include_graphics(c('images/alignment.pdf', 'images/alignment.pdf'))
    ```

But please note that `page=n` probably does not make sense for non-LaTeX output. Since you are including a PDF figure, it won't work for most output formats except for LaTeX anyway.

**Comment by sheltonmath** [comment]
Excellent. Thank you for all of your amazing work.
