### ISSUE TITLE
Commented chunks in R Markdown documents are still executed

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1363]
Given the document:

    ---
    title: "Untitled"
    output: html_notebook
    ---

    

    ```{r}
    print(1)
    ```

Attempting to knit this document will actually process and render the chunk, e.g.

```R
knitr::knit("comment.Rmd")
cat(readLines("comment.md"), sep = "\n")
```

giving

    > cat(readLines("comment.md"), sep = "\n")
    ---
    title: "Untitled"
    output: html_notebook
    editor_options:
      chunk_output_type: inline
    ---

    

Is this expected behavior? Is there a chance that `knitr` could try ignoring chunks within HTML comments?

**Comment by yihui** [comment]
Unfortunately it is expected, because knitr does not really understand HTML comments. You are definitely not the first one who has raised this issue, so it may make sense to support HTML comments. The problem is that the knitr parser is completely based on regular expressions, and you know, not bulletproof...

**Comment by kevinushey** [comment]
One possibility -- a pre-processor of some form could replace each HTML comment with a unique placeholder (something that can effectively just 'pass through' knitr's rendering), and then restore those after the whole `knit` process is done. Something similar in spirit to the '' comments used for HTML widgets and the like.

I'm not sure whether something like this would fit better in `rmarkdown` or `knitr`, however.

**Comment by yihui** [comment]
I tend to do this in rmarkdown using the approach you outlined: https://github.com/rstudio/rmarkdown/issues/974

**Comment by kevinushey** [comment]
Sounds good -- let's see if we can accommodate this upstream in `rmarkdown` then.

**Comment by baptiste** [comment]
Just for the record, here's another possible strategy: move the knit step further down in the toolchain, after pandoc (or perhaps commonmark) has parsed the input into an AST. Pandoc will automatically tag comments, code blocks, inline code, etc. as such, and so there would be no need for fragile regex matching: one would just traverse the AST to filter the code blocks that need to be executed. The pandocfilters package has tools to interpret and interact with such AST elements.

(this is obviously a major change, so I don't expect it to be a viable solution for the existing toolchain, but it's perhaps a strategy worth investigating from scratch as a new package).

**Comment by yihui** [comment]
> after pandoc (or perhaps commonmark) has parsed the input into an AST. Pandoc will automatically tag comments, code blocks, inline code, etc. as such, and so there would be no need for fragile regex matching

And just for the record, this has been done in **litedown**: https://github.com/yihui/litedown Thanks!
