### ISSUE TITLE
Text references fail.

### ISSUE THREAD

**Issue by maurolepore** [yihui/knitr#1367]
Text references do not work as explained in [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references). The  expample provided fails to produce  the expected figure caption. (knitr version 1.15.13; RStudio version Version 1.0.136.)

![image](https://cloud.githubusercontent.com/assets/5856545/23332868/c25fae84-fb4e-11e6-83ac-1c783b10ac0b.png)

**Comment by yihui** [comment]
It is a feature specific to bookdown. Your output format has to be one provided by bookdown, or inherit from an output format in bookdown.
