### ISSUE TITLE
pdf syncing with multiple Rnw files

### ISSUE THREAD

**Issue by sanfordweisberg** [yihui/knitr#1369]
I am writing a book.  The main file looks like this:

\documentclass{article}
\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
render_sweave()
opts_chunk$set(cache=TRUE)
opts_knit$set(self.contained=TRUE)
@

Go to child1:

\newpage

<<child-demo, child='test-child-2.Rnw'>>=
@

Go to child 2:

\newpage
<<child-demo, child='test-child1.Rnw'>>=
@
\end{document}

Everything typesets correctly.  Sync from RStudio editor to the pdf works ONLY from the main file, called test.Rnw, and then only to the start of the output for the child file.  Sync in the other direction from the pdf only goes to the line of code in the main file that calls the child file.  Can sync so work with the child files?

Here are the child files

test-child-2.Rnw:
=====
% !Rnw root = test.Rnw

<<test-main>>=
options(width = 60)
summary(iris)
@

This is some additional text in child-2 to see if I can get back from the pdf

test-child1.Rnw
====
% !Rnw root = test.Rnw

This is some text in the child

<<test-child, out.width='2in'>>=
1+1
rnorm(5)
plot(1)
boxplot(1:10)
str(mtcars)
@

This is the end of text in the child1.

**Comment by yihui** [comment]
Sorry, this is by design. I did attempt to support child files a couple of years ago, but it turned out to be too complicated and I gave it up.
