### ISSUE TITLE
kable() caption doesn't handle newlines

### ISSUE THREAD

**Issue by jzadra** [yihui/knitr#1370]
including a newline in the caption string within cable causes it to print the word "Table" above the caption in Rmarkdown.

`kable(data.frame(matrix(5,5,4)), caption = "\n\nblah")`

produces:

![image](https://cloud.githubusercontent.com/assets/25590353/23521859/0183b61c-ff3e-11e6-8666-5ff6a83674f2.png)

**Comment by yihui** [comment]
`kable()` only supports very simple tables. A single line break might work, but you certain cannot have an empty line (two consecutive line breaks) because that means a new paragraph.
