### ISSUE TITLE
asis_output autoconverts 4 spaces to <code>

### ISSUE THREAD

**Issue by hughjonesd** [yihui/knitr#1371]
The following document shows the issue when I am trying to output raw HTML. Not sure if it is a markdown thing or a knitr thing, but it makes life difficult for the package author.

```
---
title: "Untitled"
author: "David Hugh-Jones"
date: "02/03/2017"
output: html_document
---

#  in a knitr chunk
knitr::asis_output('<table><tr><td>   </td><td>3 spaces shows fine</td></tr></table>')
knitr::asis_output('<table><tr><td>    </td><td>4 spaces uses pre and code tags</td></tr></table>')
```

**Comment by yihui** [comment]
Please use `htmltools::HTML()` instead, to protect raw HTML content.

**Comment by hughjonesd** [comment]
This solution works fine within a knitr chunk, but if I use it within knit_print, the HTML is still escaped:

```
# in a R code chunk

knit_print.useHTML <- function(...) {
  htmltools::HTML('<table><tr><td>    </td><td>still uses pre and code tags</td></tr></table>')
}

knit_print.useboth <- function(...) {
  knitr::asis_output(htmltools::HTML('<table><tr><td>    </td><td>still uses pre and code tags</td></tr></table>'))
}


structure('', class = 'useHTML')
structure('', class = 'useboth')

```
But, if this is fixed in 1.16, I'm happy.

**Comment by yihui** [comment]
It cannot be used in a `knit_print` method. If you must use an S3 method, replace `htmltools::HTML` with `htmltools::htmlPreserve`, but I recommend an easier way: add a class `html` to your character value, e.g.

    ---
    title: "Test"
    output: html_document
    ---
    
    ```{r}
    requireNamespace('htmltools', quietly = TRUE)
    x = '<table><tr><td>    </td><td>4 spaces uses pre and code tags</td></tr></table>'
    class(x) = c(class(x), 'html')
    x
    ```

**Comment by hughjonesd** [comment]
Thank you for this. I don't suppose there is a similar way to get pandoc to accept LaTeX as-is? At the moment it seems to do what it likes, depending on the phases of the moon.

**Comment by yihui** [comment]
No, there is not a straightforward way. If you really really want it, the only way out is to define your custom output format and use pre/post-processors. The idea has been used in both `html_document` and [`rtf_document`](https://github.com/rstudio/rmarkdown/blob/master/R/rtf_document.R) (`knitr::extract_raw_output` and `knitr::restore_raw_output`). Basically you protect the raw content in the pre-processor, and restore it in the post-processor.

**Comment by hughjonesd** [comment]
Just FYI, the solution with htmlPreserve works, but the solution with `class(x)` does not seem to:

```
# inside an R code chunk
knit_print.classHTML <- function(...) {
  requireNamespace('htmltools', quietly = TRUE)
  x <- '<table><tr><td>    </td><td>still uses pre and code tags</td></tr></table>'
  x <- knitr::asis_output(x) 
  class(x) <- c(class(x), 'html')
  x
}

knit_print.htmlPreserve <- function(...) {
  requireNamespace('htmltools', quietly = TRUE)
  x <- '<table><tr><td>    </td><td>prints as a table unescaped</td></tr></table>'
  x <- htmltools::htmlPreserve(x)
  x <- knitr::asis_output(x)
  x
}


blah <- structure('blah', class = 'classHTML')
blah

blah2 <- structure('blah', class = 'htmlPreserve')
blah2

```
