### ISSUE TITLE
Support for "org-mode" style plain text table

### ISSUE THREAD

**Issue by xvrdm** [yihui/knitr#1372]
Would it be possible to support plain text table [in the style of org-mode](http://orgmode.org/manual/Built_002din-table-editor.html#Built_002din-table-editor), and possibly render them like data tables?

Sometimes when reading Rmd source, there is some tabular information that would really benefit from being easily readable and that doesn't really need to be formatted in R code.

**Comment by yihui** [comment]
Pandoc does support the org-mode style tables: http://pandoc.org/MANUAL.html#tables so feel free to use such tables in R Markdown.

**Comment by yihui** [comment]
FYI this has been implemented in #2258. Thanks!
