### ISSUE TITLE
encoding done by write_bib

### ISSUE THREAD

**Issue by arnyeinstein** [yihui/knitr#1374]
If I use write_bib for the package tibble, the bib-file is coded as iso-latin-1 and causes problems with pandoc (one of the authors has the surname "Müller")

    library(tibble)
    knitr::write_bib(x = .packages(), file = 'packages.bib')

    pandoc-citeproc.exe: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
    pandoc.exe: Error running filter pandoc-citeproc

If I change the bib file to UTF8 there is no problem for pandoc. I don't know if this is a problem with pandoc or a "bug" in "wirte_bib".
Cheers
Renger

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by arnyeinstein** [comment]
Thanks and great!
