### ISSUE TITLE
Malformed XHTML

### ISSUE THREAD

**Issue by spgarbet** [yihui/knitr#1375]
Knitr produces a tag at the top that states it is generating XHTML. If the MIME type is reported properly to the browser then the Knitr generated file will not render (one can simulate this easily by changing the extension to xhtml of the generated file). XHTML parsing is strict in browsers, I would recommend that Knitr produce an HTML tag which will allows for errors and most browsers will properly render even when there are errors.

I think the underlying cause is that javascript is not escaped properly via the XHTML standard. We have automated processes generating documents, which are then picked up *correctly* as XHTML for browser viewing--that are then non-renderable.

**Comment by yihui** [comment]
Sorry, there are multiple ways to generate HTML output from knitr. Which way are you talking about exactly? `knitr::knit2html()` or `rmarkdown::render()` or other packages? It is always a good idea to attach a minimal reproducible example to avoid ambiguity.

**Comment by spgarbet** [comment]
Attached is an example markdown file.  

rmarkdown::render("xhtml.Rmd", output_file = "xhtml.html", output_format = "html_document")

Note that line 3 of the generated output is:

<html xmlns="http://www.w3.org/1999/xhtml">

Which declares the html to be xhtml compliant--it's not and once notified correctly of the MIME type a browser will not render generated code. Much simpler to change this to <html>, and let the browser use it's fallbacks.

[xhtml.zip](https://github.com/yihui/knitr/files/834252/xhtml.zip)

**Comment by yihui** [comment]
Okay, so you are using rmarkdown, and rmarkdown issues should be reported to https://github.com/rstudio/rmarkdown since knitr does not generate the HTML output directly.

Anyway, I just tested the xhtml file you provided with the w3c validator, and there are indeed some issues. I'm not an expert of XHTML standards, and I'll defer this issue to rmarkdown developers. Thanks!

**Comment by spgarbet** [comment]
Thanks! I opened a ticket with rmarkdown.
