### ISSUE TITLE
Dependencies of chunks are ignored (`cache = TRUE`)

### ISSUE THREAD

**Issue by wlandau** [yihui/knitr#1379]
I have a report:

    ---
    title: "Example"
    output: html_document
    ---

    ```{r A, cache = TRUE, echo = FALSE}
    x <- 1
    ```

    ```{r B, cache = TRUE, echo = FALSE}
    x
    ```

When I knit and render it, the output is as expected:

    ## [1] 1
    ## [1] 1

But if I change code chunk A to `x <- 36` and knit again, the output of chunk B does not change (tested for both version 1.15.1 (current CRAN) and commit commit 6d270bad4f661bce30cb29ada3ac2513d27bf997). To me, this does not bode well for reproducible data analysis.

Have you thought about using a build system like [drake](https://github.com/wlandau-lilly/drake) (or [remake](https://github.com/richfitz/remake))? Both these packages track the entire dependency graph of a project rather than each code chunk in isolation. They also tidy the code before hashing it so that whitespace and comments do not trigger unwanted rebuilds.

**Comment by yihui** [comment]
If you have a copy of the knitr book at hand, I suggest you read Section 8.5 (Chunk Dependencies). If not, please check out these chunk options at https://yihui.name/knitr/options/#cache `dependson`, `autodep`, and `cache.comments`, as well as the function `knitr::dep_auto`. All your questions will be answered.

**Comment by wlandau** [comment]
I see, the Cache section of the Options page is helpful. Unfortunately, I do not yet have the book. Is there a reason why `autodep` and `cache.comments` are turned off by default?

**Comment by yihui** [comment]
`autodep` is off because it depends on code analysis (via the **codetools** package), which is not bulletproof but should work in most cases, unless you have really clever tricks of creating objects.

`cache.comments` is off because it is an option later added to **knitr**.  If I were to rewrite **knitr** today, I'll turn it on by default.
