### ISSUE TITLE
Output missing from notebook HTML, but not regular HTML

### ISSUE THREAD

**Issue by Deleetdk** [yihui/knitr#1381]
It seems that this is a bug related to using the chunk param `code` to input code. See [this Stackoverflow question](http://stackoverflow.com/questions/40519904/modularized-r-markdown-structure) (also me). 

I attach a minimal example, which has 4 files:

1. knitr_bug.Rmd
2. knitr_bug.R
3. knitr_bug.html
4. knitr_bug.nb.html

The first file is an R notebook style Rmd. It calls a single code chuck with the `code` param that calls the .R file. The .R file has a simple ggplot2 to plot some iris data. Then one simply clicks Knit. The two outputs look like this, side by side:

![knitr_bug](https://cloud.githubusercontent.com/assets/6759913/24089757/55506010-0d3a-11e7-849b-e1a5fec9f1e1.png)

As can be seen, the regular HTML file has the code output, but the Notebook version does not.

[knitr_bug.zip](https://github.com/yihui/knitr/files/853979/knitr_bug.zip)

**Comment by yihui** [comment]
I'm afraid that Rmd notebooks do not understand the `code` trick. This issue needs to be reported to https://github.com/rstudio/rmarkdown instead. It is not a **knitr** bug. Thanks!
