### ISSUE TITLE
Using two include_graphics with echo generates two separated verbatim

### ISSUE THREAD

**Issue by statnmap** [yihui/knitr#1382]
If I want to `echo` a chunk in which there are two `include_graphics` commands, the output is split in two output verbatim separated by the first image.
Here is the code example for a Rmd document:

    ```{r IncludeGraphics, echo = TRUE, out.width="40%"}
    knitr::include_graphics("./myfigdirectory/fr.png")
    knitr::include_graphics("./myfigdirectory/gb.png")
    ```
and here the direct md file generated for an HTML output (this way, I do not have to include images in here):

```
    ```r
    knitr::include_graphics("./myfigdirectory/fr.png")
    ```
    <img src="./myfigdirectory/fr.png" width="40%" />
    ```r
    knitr::include_graphics("./myfigdirectory/gb.png")
    ```
    <img src="./myfigdirectory/gb.png" width="40%" />
```

I found a solution to show the input chunk on my blog while using a chunk in a chunk, so to me, this is no more a problem. However, although I found this function interesting for the use of conditional chunks, `include_graphics` behave as if it could only be used once in a chunk...

**Comment by yihui** [comment]
Now you should be able to use the chunk option `fig.show='hold'` to merge the two images, so that there will be only one code chunk in the output.
