### ISSUE TITLE
Documentation of child markdown 

### ISSUE THREAD

**Issue by paul4forest** [yihui/knitr#1384]
Markdown child documents were added in #268 but the [documentation of `knit_child`](https://github.com/yihui/knitr/blob/ccc2365661b4a0e994ffe1b291b657865b94902e/R/output.R#L379) refers to  https://yihui.name/knitr/demo/child/ which describes Latex child documents only. Would it be possible to include Markdown child documents  in the package documentation or on the yihui.name site?

An example of markdown child document was provided [here](https://github.com/yihui/knitr/blob/master/inst/examples/child/knitr-main.Rmd), so it's probably just a matter of including this example in the documentation. I would have liked to comment on https://yihui.name/knitr/demo/child/ , but comments are closed on that page. 

Markdown child documents is a relevant topic and there are people [asking about it on Stackoverflow](http://stackoverflow.com/search?q=markdown+child+document).

**Comment by yihui** [comment]
You know what? I really wish I could replace all Rnw examples with Rmd. The reason that you see a lot of Rnw examples on the knitr website is that it was originally focused on LaTeX (to replace and enhance Sweave), but I think R Markdown is the clear winner now, and it can be confusing for readers to see those weird Rnw examples everywhere.

Replacing all Rnw examples is certainly a lot of work, but it should be practical to replace those on the page https://yihui.name/knitr/demo/child/, or at least mention an Rmd example there. If you are willing to contribute to the documentation, please read FAQ 9 to know how: https://yihui.name/knitr/faq/
