### ISSUE TITLE
Issue with kable and ( in the first col.names

### ISSUE THREAD

**Issue by boennecd** [yihui/knitr#1385]
There is an issue with kable when the first col.names entry start with a "(" and there is no row.names. E.g.:

Works:

```{r}
x <- matrix(1:10, nrow = 5, ncol = 2,
            dimnames = list(NULL, c("x1", "x2")))

knitr::kable(x)
```

Does not work

```{r}
x <- matrix(1:10, nrow = 5, ncol = 2,
            dimnames = list(NULL, c("(x,y]", "something")))

knitr::kable(x)
```

A quick workaround is:

```{r}
x <- matrix(1:10, nrow = 5, ncol = 2,
            dimnames = list(NULL, c("\\relax(x,y]", "something")))

knitr::kable(x)
```

**Comment by yihui** [comment]
This seems to be a LaTeX or Pandoc issue. I have no idea what's wrong here. Sorry. I recommend you to ask on StackOverflow or TeX.StackExchange instead. Remember to post a _self-contained_ reproducible example.
