### ISSUE TITLE
Not install package knitr on R ver 3.3.3 (OS Fedora 25 x86_64)

### ISSUE THREAD

**Issue by Dmitryi** [yihui/knitr#1387]
I`am use command for install^
install.packages('knitr', dependencies = TRUE)
install.packages('knitr', repos = c('http://yihui.name/xran', 'http://cran.rstudio.org'))
devtools::install_github('yihui/knitr', build_vignettes = TRUE)

A warning: S3 methods ‘parse_all.function’, ‘parse_all.character’, ‘parse_all.connection’, ‘parse_all.default’, ‘replay.character’, ‘replay.default’, ‘replay.error’, ‘replay.list’, ‘replay.message’, ‘replay.recordedplot’, ‘replay.source’, ‘replay.value’, ‘replay.warning’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: create_traceback, evaluate, flush_console, inject_funs, is.error, is.message, is.recordedplot, is.source, is.value, is.warning, new_output_handler, parse_all, replay, set_hooks, try_capture_stack
Error : unable to load R code in package ‘knitr’
ERROR: lazy loading failed for package ‘knitr’
* removing ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3/knitr’
Warning in install.packages :
  installation of package ‘knitr’ had non-zero exit status
ERROR: dependency ‘knitr’ is not available for package ‘rgl’
* removing ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3/rgl’
Warning in install.packages :
  installation of package ‘rgl’ had non-zero exit status
ERROR: dependency ‘knitr’ is not available for package ‘rmarkdown’
* removing ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3/rmarkdown’
Warning in install.packages :
  installation of package ‘rmarkdown’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpRu2vor/downloaded_packages’

**Comment by yihui** [comment]
That is weird. Does `install.packages('evaluate')` work?

**Comment by Dmitryi** [comment]
No!
install.packages("evaluate")
install.packages('evaluate', dependencies = TRUE)

Installing package into ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
пробую URL 'https://cran.rstudio.com/src/contrib/evaluate_0.10.tar.gz'
Content type 'application/x-gzip' length 21914 bytes (21 KB)
==================================================
downloaded 21 KB

ERROR: failed to lock directory ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3’ for modifying
Try removing ‘/home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3/00LOCK-evaluate’
Warning in install.packages :
  installation of package ‘evaluate’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpaPCqAV/downloaded_packages’

**Comment by yihui** [comment]
Okay, that is probably the reason. Please follow the suggestion in the error message.

**Comment by Dmitryi** [comment]
YES!!!

sudo rm -rf /home/dmitryi/R/x86_64-redhat-linux-gnu-library/3.3/00LOCK-evaluate

package install!

Thank you)

**Comment by yihui** [comment]
Great! Since you were installing to your home directory, I don't think you need `sudo`.
