### ISSUE TITLE
Access to rmakrdown output filename from knit_print

### ISSUE THREAD

**Issue by bhaskarvk** [yihui/knitr#1390]
Is is possible to get access to the output filename from `knit_print` ?
I tried looking in `knitr::opts_*$get()`, where `*` = `chunk`, `hook`, `current`, `template` and `knitt`, but it's not available there. Similarly I even tried looking for it from `rmarkdown::metadata` but no go there too.

I need it for my widgetframe package, for the https://github.com/rstudio/bookdown/issues/271 issue. If I can determine the output filename, and it's libdir (which is normally `outputfile_files`), then I can write the child widget in that directory, thus making the child widget files part of the parent widget's lib dir.

**Comment by bhaskarvk** [comment]
As a hack I can do `knitr::opts_chunk$get('fig.path')`, which returns `outputfile_files/figure-html` and remove figure-html and use the path, but I would prefer a non-hacky approach if any.

**Comment by yihui** [comment]
I don't think the information you need is exposed to users: https://github.com/rstudio/rmarkdown/blob/master/R/render.R

I think it is fine to use `knitr::opts_chunk$get('fig.path')`.
