### ISSUE TITLE
Round all columns that round to digits in kable

### ISSUE THREAD

**Issue by RoyalTS** [yihui/knitr#1396]
I would like to print a table that has a `difftime` column. Passing `digits=2` to `kable()`, however, leaves the column unaffected in printing because as per https://github.com/yihui/knitr/blob/master/R/table.R#L138 `kable` only rounds numeric columns. Can this test be changed to a test for whether the class of the column has an associated `round` function?

**Comment by yihui** [comment]
I think the answer is yes. Please make the change and submit a pull request. Thanks!

**Comment by RoyalTS** [comment]
It appears `difftime` objects are rounded using `base::round` so for that case it would be sufficient to check `'difftime' %in% class()`. That's not a very generic solution but (a) I'm not sure what more generic solutions make sense (`round.POSIXt` exists but does not round to digits) and (b) this is a bit beyond my R fu. Pointers appreciated!

**Comment by yihui** [comment]
I guess it suffices to patch `knitr:::is_numeric` in utils.R, but I'm not totally sure.

**Comment by RoyalTS** [comment]
Yeah, that seems about right.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
