### ISSUE TITLE
asis_output overrides header-includes in .Rmd file

### ISSUE THREAD

**Issue by hughjonesd** [yihui/knitr#1397]
In a .Rmd file, if you include a list of `rmarkdown::latex_dependency` objects in the `meta` argument to `asis_output`, this will override any `\usepackage` statements in the `header-includes` argument. See the attached mwe. This came up in hughjonesd/huxtable#7.

[knitr-bug-mwe.Rmd.zip](https://github.com/yihui/knitr/files/965951/knitr-bug-mwe.Rmd.zip)

A workaround is to use the `includes` argument to `pdf_document`.

**Comment by yihui** [comment]
This issue should be filed to rmarkdown.

Anyway, @haozhu233 do you have an idea how to fix it? I'm asking because you are familiar with LaTeX dependencies. @hughjonesd If you know how to fix it, a pull request will be welcome, too. I'm very busy recently. Sorry.
