### ISSUE TITLE
utf8 problem back again

### ISSUE THREAD

**Issue by arnyeinstein** [yihui/knitr#1398]
[testing.txt](https://github.com/yihui/knitr/files/972752/testing.txt)
Hi
I posted a problem with UTF8 encoding of write_bib and this issue was closed (https://github.com/yihui/knitr/issues/1374), but after installing the new R version and updating all packages, the encoding issue is still around on my Windows machine. Tibble has as author Kirill Müller and this causes the problem when write_bib writes the file packages.bib (it is not utf8).

Here the code of my rmd-file  (sorry for the format; therefore also attached; extension should be Rmd)

(code starts here)
`
---
 title: "testing"
 author: "Renger"
date: "2 Mai 2017"
output: pdf_document
bibliography:
- packages.bib
biblio-style: apa
---
`
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
x <- capture.output(knitr::write_bib(x = .packages() ))
readr::write_lines(x,'packages.bib') 
```
```{r}
## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
[@R-base] [@R-tibble] 

### References

(code stops here

I resolved this by doing the following
```{r}
x <- capture.output(knitr::write_bib(x = .packages() ))
readr::write_lines(x,'packages.bib') 
```
Session info
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.15.1  tibble_1.3.0  rmarkdown_1.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10    digest_0.6.12   rprojroot_1.2   R6_2.2.0       
 [5] backports_1.0.5 magrittr_1.5    evaluate_0.10   stringi_1.1.5  
 [9] fortunes_1.5-4  tools_3.4.0     stringr_1.2.0   readr_1.1.0    

Cheers
Renger

**Comment by yihui** [comment]
The fix is only in the current dev version.

```r
devtools::install_github('yihui/knitr')
```
