### ISSUE TITLE
knitr and knit_print with HTML output - dispatch not working

### ISSUE THREAD

**Issue by vnijs** [yihui/knitr#1399]
Hi Yihui,

I asked a question on stackOverflow about using a knit_print method to render DT tables in a Shiny app a few days ago. Question linked below. No answers or comments so far. Any suggestions?

https://stackoverflow.com/questions/43727114/knitr-and-knit-print-with-html-output-dispatch-not-working

**Comment by yihui** [comment]
Sorry, but I have no idea or time to investigate this. Are you sure `knit_print.datatables` is created in the global environment? i.e. the Rmd should be compiled in `globalenv()`, otherwise S3 dispatching won't work in R.

**Comment by vnijs** [comment]
I don't think the environment is the problem. Wrapping the `DT::renderDataTable()` as shown in the function below works as long as `screenshot.force = FALSE`. However, I also want to use Rmarkdown to render to PDF and Word and include screenshots of htmlwidgets. Is there a work around?

```r
knit_print.datatables <- function(x, ...) {
  shiny::knit_print.shiny.render.function(
     DT::renderDataTable(x)
  )
}
```

**Comment by yihui** [comment]
You might need `registerS3method()`. See 194c0afbf817dac0b75404770aa1905babc6dc3c.
