### ISSUE TITLE
Figure captions with standalone throw missing-item error

### ISSUE THREAD

**Issue by mathuin** [yihui/knitr#1402]
I have a minimum working example which demonstrates the issue:

```latex
\documentclass{standalone}
% <<all, fig.lp="fig:", fig.cap="All.", echo=FALSE>>= fails
% <<all, fig.lp="fig:", echo=FALSE>>= succeeds
\begin{document}
    <<all, fig.lp="fig:", fig.cap="All.", echo=FALSE>>=
    plot(1)
    @
\end{document}
```

The LaTeX file generated by `Rscript -e "library(knitr); knit('mwe.Rnw')"` will throw the following error when compiled with pdflatex:

    ! LaTeX Error: Something's wrong--perhaps a missing \item.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.57 ...0.969, 0.969}\color{fgcolor}\begin{figure}

Changing the document class from `standalone` to `article` causes the compilation to succeed and generate sensible output.  Leaving the document class `standalone` and removing the figure caption option also causes the compilation to succeed and generate output which makes sense.

The output of `devtools::session_info('knitr')`:

```r
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-05-15                  

Packages ----------------------------------------------------------------------
 package   * version date       source        
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 evaluate    0.10    2016-10-11 CRAN (R 3.4.0)
 graphics  * 3.4.0   2017-04-21 local         
 grDevices * 3.4.0   2017-04-21 local         
 highr       0.6     2016-05-09 CRAN (R 3.4.0)
 knitr       1.15.1  2016-11-22 CRAN (R 3.4.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)
 methods   * 3.4.0   2017-04-21 local         
 mime        0.5     2016-07-07 CRAN (R 3.4.0)
 stats     * 3.4.0   2017-04-21 local         
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)
 tools       3.4.0   2017-04-21 local         
 utils     * 3.4.0   2017-04-21 local         
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```

**Comment by yihui** [comment]
This issue is irrelevant to knitr. I recommend you to ask on TeX.SX instead: https://tex.stackexchange.com I have prepared a minimal example for you to repro your issue:

```latex
\documentclass{standalone}
\begin{document}
\begin{figure}
\end{figure}
\end{document}
```

**Comment by mathuin** [comment]
For those that find this issue:  https://tex.stackexchange.com/questions/69808/standalone-with-beginfigure-gives-error explains that the `\begin{figure}` and `\end{figure}` bits of code must be removed from the code generated by `knitr` when used with `standalone` unless the `preview` option is also used.

This issue could be fixed in `knitr` by removing the `figure` environment when the `standalone` class is used, but I imagine that that change is probably not worth making.

**Comment by yihui** [comment]
You should not use `fig.cap` if you do not want the figure environment.
