### ISSUE TITLE
Cache dependencies

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#1403]
Not sure if it is an issue with codetools or knitr (and where it should/could be "fixed") but:

```r
codetools::findGlobals(function(){x<-2*x})
```

doesn't return `x`.

The side effect is that, in the following, the "b" chunk does not depend on the "a" chunk. So changing the assignment in the "a" chunk will always report a result of `2`.

```r
<<knitr-config, echo=FALSE, message=FALSE, results='hide'>>=
opts_chunk$set(cache=2, echo=FALSE, results='hide', autodep=TRUE)
@

<<a>>=
x <- 1
@

<<b>>=
x <- 2*x
@

<<res, results='asis'>>=
cat(x)
@

<<cache-dep, cache=FALSE, results='asis'>>=
cat('\n%\n% Chunk dependencies:\n')
deps <- sapply(knitr:::dep_list$get(), paste, collapse=', ')
cat(paste0('% ', names(deps), ": ", deps), sep='\n')
@
```

**Comment by yihui** [comment]
Since this issue comes from **codetools**, I think you should report it to bugs.r-project.org and probably let Luke know. There is no need to mention **knitr** when you report the issue. As long as this upstream issue can be fixed, **knitr** should work automatically. Thanks!

**Comment by knokknok** [comment]
Looks like something equivalent was already reported one year ago...
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16884

**Comment by yihui** [comment]
Okay, then I'll wait for it to be fixed in base R, unless you can come up with a small patch, in which case I'll be happy to incorporate it in knitr.

**Comment by yihui** [comment]
The ticket in R was closed, which makes sense. You will have to manually specify the dependency via `dependson='a'` in `<<b>>=`. knitr's documentation also said that automatic detection of dependencies is not reliable: https://yihui.name/knitr/options/#cache

**Comment by knokknok** [comment]
Would the following work? I think it's "erring on the 'there are dependencies' side" ;-)

```diff
 find_globals = function(code) {
-  fun = eval(parse_only(c('function(){', code, '}')))
-  setdiff(codetools::findGlobals(fun), known_globals)
+  unique(subset(getParseData(parse(text = paste('function(){', paste0(code, collapse="\n"), '}', sep="\n"), keep.source=TRUE), includeText=NA), terminal & token %in% c("SYMBOL", "SYMBOL_FUNCTION_CALL"))$text)
 }
-known_globals = c(
-  '{', '[', '(', ':', '<-', '=', '+', '-', '*', '/', '%%', '%/%', '%*%', '%o%', '%in%'
-)
```

**Comment by yihui** [comment]
Done. Thanks!

**Comment by yihui** [comment]
Please note that I just reverted the fix. With the current version of **knitr**, you will have to manually tell **knitr** the global variables in your chunk b, e.g.

```
<<b, cache.globals = 'x'>>=
x <- 2*x
@
```

so `x` will no longer be treated as a local variable in chunk b.

**Comment by knokknok** [comment]
Thanks for letting me know.
Although, personally, I'd rather have, out of the box, a cache with the correct values with some overzealous invalidation than the incorrect values (```cache.globals``` needs a pretty good understanding of what's going on, and, in #1708, one can use a different variable name if needed)...

**Comment by knokknok** [comment]
Hi @yihui,

I keep getting hit by insufficient invalidation of cache in my scripts...
Any chance you would add some kind of global knitr ```cache.strict``` option that would use either ```find_symbols``` or ```find_globals``` in
https://github.com/yihui/knitr/blob/4d6fc85c3f64b484917bd441840357ef362fda38/R/block.R#L270 ?
