### ISSUE TITLE
optipng with include_graphics()

### ISSUE THREAD

**Issue by zevross-spatial** [yihui/knitr#1404]
I'm having trouble controlling the size of RMD files and am experimenting with using `hook_optipng()`. This works well with R-generated graphics, but does not seem to work on external graphics included with `include_graphics()` -- perhaps this is as intended. 

Below is an example, the ggplot gets optimized but the image returns `** Processing: test_files/figure-html/b-.png; Error: Can't open the input file`.  I played around with putting my image in the figure-html folder and renaming etc. Would there be a way to use optipng with external images within the context of R Markdown (I can run optipng separately if necessarily of course).

````
---
title: "Untitled"
output:
  html_document:
  self_contained: true
---

```{r setup, include=FALSE}
library(knitr)
knit_hooks$set(optipng = hook_optipng)
```


## Including Plots

You can also embed plots, for example:
  
```{r a, optipng = '-o7', cache=FALSE}
library(ggplot2)
ggplot(cars, aes(speed, dist)) + geom_point()
```

```{r b, optipng = '-o7', cache=FALSE}
include_graphics("https://cdn.pixabay.com/photo/2017/05/20/21/00/noodles-2329766_1280.jpg")
```

````

**Comment by yihui** [comment]
`hook_optipng()` only works with local PNG files. In your second example, you have to download it and run the command line `optipng`.

BTW, it is a JPEG image, and optipng cannot deal with JPEG images.

**Comment by zevross-spatial** [comment]
When you say local PNG do you mean R generated PNG? Sorry about the example with the JPG that was a copy paste issue. I have been using PNG.

**Comment by yihui** [comment]
Yes.

It is simple enough to write a helper function to optimize all PNG images under a directory:

```r
optipng = function(dir = '.') {
  files = list.files(dir, '[.]png$', recursive = TRUE, full.names = TRUE)
  for (f in files) system2('optipng', shQuote(f))
}
```
