### ISSUE TITLE
export functions

### ISSUE THREAD

**Issue by Hemken** [yihui/knitr#1405]
I would like to use a modified version of your engine_output( ) function in a package I am writing that extends the capabilities of the SAS languages engines within knitr.  Can I get you to export two functions you use there?  They are is_blank( ) and wrap.character( ).

The package is here on github, at Hemken/SASmarkdown.  This is the final hurdle to making this package releasable on CRAN.

Thanks!
Doug Hemken

**Comment by yihui** [comment]
I don't think you really have to copy the `engine_output()` function and modify it in your package (usually this is bad practice). As far as I can see, all you want to do is to process the `out` variable (https://github.com/Hemken/SASmarkdown/blob/master/R/sas_output.r), and I think you can just 

```r
sas_output = function(options, code, out, extra = NULL) {
  # do whatever you want to do on `out` here
  out = ...
  knitr::engine_output(options, code, out, extra)
}
```

**Comment by Hemken** [comment]
Thank you for taking a look.
I have this vague memory of considering taking SAS output in a new direction, but then I thought better of it.
That resolves my issue.  Thank you.

Doug Hemken
