### ISSUE TITLE
Executing Scala REPL builtin commands

### ISSUE THREAD

**Issue by markrbower** [yihui/knitr#1406]
Am using knitr in RStudio to generate reproducible-research, RMarkdown documents. I've included a Scala engine, which does work, until it reaches my code wanting to load a Scala class:

```{r tmp, engine='scala', comment='Scala>', eval=TRUE, engine.opts='-savecompiled'}
val something = System.getenv("SOMETHING")
val somethingelse = something + " + Scala"
println("'" + something + "' is now '" + somethingelse + "'")
:load /Users/me/Documents/myClass.scala
```

This same :load statement works in the REPL. Why doesn't it work here? Is there some other way to load user-defined Scala class into the knitr Scala engine?

When posted to the RStudio forum, the response was that Scala code is executed with:
"scala -e "<...code...>"
and that REPL builtins may not be run correctly. Would it be possible to provide for processing REPL builtin functions?

Thanks!

Mark

**Comment by yihui** [comment]
I don't know anything about Scala. The `scala` engine in knitr was added by @metasim in #640. I'm afraid I cannot help you here. Sorry.

**Comment by metasim** [comment]
@markrbower The REPL expects an interactive terminal, and knitr is not that, and you'd have to change the knitr forking of `scala` to redirect stdio, so it might be a bit involved.. That said, you could fork knitr and try to hack it yourself ;-)

**Comment by metasim** [comment]
PS: you might be able to hack something together by overriding the path to`scala` to actually point to a custom script that does whatever custom stuff you want to do.

See: https://yihui.name/knitr/options/#language-engines
