### ISSUE TITLE
Please support echoing syntax-highlighted CSS and JavaScript code

### ISSUE THREAD

**Issue by skadauke** [yihui/knitr#1408]
`engine.R` converts chunks of CSS or JavaScript code directly into html assets without echoing syntax-highlighted code. While this behavior may be desirable in many circumstances, it is unexpected since it is different from the way knitr deals with other languages, and different from Markdown. 

Example:
````
```{css}
p {
    color: red;
}
```
````

knitr renders the above code to the following HTML, directly embedded in the HTML document, without producing syntax-highlighted CSS code:
```
<style type="text/css">p { color: red; }</style>
```

There is no way to explicitly tell knitr to produce CSS code with syntax highlighting.

It would be desirable if knitr could be made to deviate from this default behavior by specifying the `echo = TRUE` option. For example, the following should render into syntax-highlighted CSS:

````
```{css, echo = TRUE}
p {
    color: red;
}
```
````

At the moment, the only way I have been able to get this done is by following the example in 
https://stackoverflow.com/questions/37534192/add-javascript-code-in-knitr. However, this involves installing additional packages, which may pose issues of reproducibility. 

For example:

````
```{r setup, include=FALSE}
library(knitrengines)
```

```{pygments pyg.ext="css"}
p {
    color: red;
}
```
````

This code produces the desired syntax-formatted CSS but requires installation of `knitrexamples` from GitHub to work.

**Comment by yihui** [comment]
This will be a breaking change since `echo = TRUE` is the default, but I think it makes sense.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by skadauke** [comment]
Awesome Yihui, you rock! I'll post an update on the SO question referenced above.
