### ISSUE TITLE
Feature request: child.path

### ISSUE THREAD

**Issue by pank** [yihui/knitr#141]
When doing larger R project I might have a project structure like this:

```
figures  [dir]
sections [dir]
main.Rnw
data.dta 
```

I can put pictures in figures with `fig.path` and cache is sorted into `cache.dir`.  It would be natural to also have a `child.dir` where knitr automatically looks for [children](http://yihui.name/knitr/demo/child/).

**Comment by stla** [comment]
I don't manage to use this option. 

```
<<setup>>=
r <- system.file("rsb", "catalog", "sweave_files", package="RSBpackage00")
knitr::opts_knit$set(
  root.dir = r,
  child.path = r
)
@
```

Then this does not work:
```
<<child="child.Rnw">>=
@
```
But this obviously works:
```
<<child=paste0(r, "/child.Rnw")>>=
@
```

**Comment by stla** [comment]
I see two problems:
```
In readLines(if (is.character(input2)) { :
  cannot open file './C:/PortableApps/R-portable_3.3.1/App/R-Portable/library/RSBpackage00/rsb/catalog/sweave_fileschild.Rnw': Invalid argument
```

The first one is easy to fix: `child="/child.Rnw"` (the slash)

The second one is the dot here: `./C:/...`.

**Comment by stla** [comment]
A solution thanks to <http://stackoverflow.com/a/36728257/1100107>:
```
<<setup>>=
make.path.relative = function(base, target) {
  common <- sub('^([^|]*)[^|]*(?:\\|\\1[^|]*)$', '^\\1/?', paste0(base, '|', target))
  paste0(gsub('[^/]+/?', '../', sub(common, '', base)),
         sub(common, '', target))
}
r <- system.file("rsb", "catalog", "sweave_files", package="RSBpackage00")
c <- make.path.relative(getwd(), r)
knitr::opts_knit$set(
  root.dir = r,
  child.path = c
)
@

<<child="/child.Rnw">>=
@
```

**Comment by stla** [comment]
@yihui ,
This relative path causes a problem: it's not possible on Windows (I think) to do a relative path from a hard drive to another one.
