### ISSUE TITLE
pandoc document conversion failed with error 9

### ISSUE THREAD

**Issue by gunjangala** [yihui/knitr#1412]
Hello,
I am getting the following error when knitting .Rmd file to .html output. Can you please help me fix this issue or let me know what "Error 9" means?

```
pandoc document conversion failed with error 9
```

**Comment by yihui** [comment]
Apparently you ignored the [issue template](https://github.com/yihui/knitr/blob/master/.github/ISSUE_TEMPLATE.md). This is too little information for me to do anything for you. It is like only telling your doctor "I'm sick" and then asking for a cure.

**Comment by gunjangala** [comment]
Ok. Sorry about that. The error seems due to running out of memory while knittting the rmarkdown to html. I have couple of tables and plot in .Rmd file. Can you help me figure out how to fix this issue and/or provide more memory to rstudio? Thanks.

**Comment by yihui** [comment]
If it is a memory issue, you may try to set this option to a larger value: https://github.com/rstudio/rmarkdown/blob/8cfe0cba/R/pandoc.R#L75

This issue should probably be moved to the rmarkdown repo: https://github.com/rstudio/rmarkdown/issues
