### ISSUE TITLE
knitr manual crashes preview, skim on MacOS (not Adobe Acrobat)

### ISSUE THREAD

**Issue by maxheld83** [yihui/knitr#1419]
I'm not quite sure where this belongs; also raised an issue on [AskDifferent](https://apple.stackexchange.com/questions/293105/why-does-this-pdf-not-render-properly-on-crash-preview), to make sure it is reproducible. 
Perhaps it is also just a MacOS-only problem, and it might very well be on the MacOS-end.

Anyway: the [knitr manual pdf](https://github.com/yihui/knitr/releases/download/doc/knitr-manual.pdf), which I am assuming was *built* with knitr and all bells and whistles, isn't fully rendered in Preview (or Skim), and crashes Preview entirely on my machine. Acrobat Reader DC works fine for some reason.

**Comment by yihui** [comment]
It contains an animation that only works in Acrobat Reader. That might be the culprit.

The manual was written several years ago and was primarily for the interest of LaTeX users. I guess someday I'll retire or rewrite it.

**Comment by maxheld83** [comment]
yup, that's it, it crashes after scrolling through the page with the animation. Closed then, will report if there are any hot leads from the SE-Question.
