### ISSUE TITLE
Feature request: ability to add captions for code

### ISSUE THREAD

**Issue by stephlocke** [yihui/knitr#1421]
I do a lot of knitr-based docs for showing others how to code or I include the code for edification. It would be super helpful if I could add a caption to code so that I can give a brief explanation as to what's happening in the code. This would be like the use of the listings package in LaTeX with the custom type of code.
![image](https://user-images.githubusercontent.com/6452610/29179452-65fe7ea6-7dec-11e7-83e7-ebb5d977f3a8.png)

**Comment by yihui** [comment]
LaTeX output is possible thanks to listings, but HTML output will require some additional work.

````
---
title: "Untitled"
output:
  pdf_document:
    pandoc_args: "--listings"
---

```{.r caption="Hi there"}
1 + 2 == 3
```
````

Actually LaTeX output also requires some work. In the above example, the code chunk is not really evaluated.

If I were to implement this feature, it would probably end up in bookdown instead.

**Comment by stephlocke** [comment]
Would you like me to raise this there instead? bookdown is my primary use case :)

**Comment by yihui** [comment]
Yeah that will be great. Thanks!
