### ISSUE TITLE
Kable with single column data frame ends up with no <TABLE> tag in generated HTML

### ISSUE THREAD

**Issue by hidekoji** [yihui/knitr#1423]
When I use kable for single column table, generated HTML output does not come with `<table>` tag but with `<p>` where all the column values are appended as text node inside the '<p>' tag.

Here is the test case.

<pre>
---
title: "Test"
output:
  html_document
---

```{r}
df <- data.frame(a=1:40)
knitr::kable(df)
```
</pre>

And the result would look like this.

![image](https://user-images.githubusercontent.com/230637/29232614-63313c3a-7ea1-11e7-9497-44720102cc47.png)

And generated HTML looks like this: 

![image](https://user-images.githubusercontent.com/230637/29232636-88e384ba-7ea1-11e7-9a45-f6dbf3cc0d6d.png)

**Comment by yihui** [comment]
[Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`

**Comment by hidekoji** [comment]
Apologies, it looks like I'm hitting the issue that is fixed with 1.17

> when a table only has one column, kable() does not work in R Markdown documents (thanks, @expersso, https://github.com/yihui/printr/issues/31)

**Comment by yihui** [comment]
Exactly.
