### ISSUE TITLE
options(warn = ) doesn't work

### ISSUE THREAD

**Issue by yutannihilation** [yihui/knitr#1425]
`?options` says:

> If warn is zero (the default) warnings are stored until the top–level function returns. (snip) If warn is one, warnings are printed as they occur. If warn is two or larger all warnings are turned into errors.

But, it seems this option doesn't work during knitting. The bellow is an example result by `reprex::reprex()`. Is this a known issue?

```r
f <- function(x) {
  warning("You've been warned!")
  x
}

options(warn = 0)
options()$warn
#> [1] 0
f(TRUE)
#> Warning in f(TRUE): You've been warned!
#> [1] TRUE

options(warn = 1)
options()$warn
#> [1] 1
f(TRUE)
#> Warning in f(TRUE): You've been warned!
#> [1] TRUE

options(warn = 2)
options()$warn
#> [1] 2
f(TRUE)
#> Warning in f(TRUE): You've been warned!
#> [1] TRUE
```

**Comment by yihui** [comment]
I think this issue belongs to the [**evaluate** package](https://github.com/hadley/evaluate). I'm not sure about the reason, but to my knowledge, only `options(warn = -1)` will work. Please feel free to study the source code of evaluate, and submit a pull request if you can figure out a fix. Thanks!

**Comment by yutannihilation** [comment]
Thanks for the infomation! I will study and file a issue or send PR to evaluate :)

**Comment by yihui** [comment]
Thanks!

**Comment by yutannihilation** [comment]
I found you've explained this in detail, which is really helpful. Thanks!

https://github.com/yihui/knitr/issues/610#issuecomment-25057284
