### ISSUE TITLE
knitr::kable() produces one table instead of two (in MS Word

### ISSUE THREAD

**Issue by rasmusrhl** [yihui/knitr#1429]
knit:kable() produces one table instead of two.

This code is supposed to create _two_ tables when knitted to microsoft word:

---
title: "Untitled"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

```{r}
knitr::kable(head(iris))
```

```{r}
knitr::kable(head(iris))
```

However it only produces one table. It appears to be two tables because the table has to headers (two rows of bold text), but it is actually only one word table. 
This only becomes evident when you try to select one table (inside MS Word), which is not possible. 

This does not happen in html output (have not tried pdf).

A workaround was suggested on stackoverflow:
https://stackoverflow.com/q/45996337/1831980

**Comment by yihui** [comment]
Thanks! I have explained it on SO: https://stackoverflow.com/questions/45996337/45996606#comment78966012_45996606

**Comment by yihui** [comment]
BTW, please read the issue template carefully the next time you file an issue to make sure your issue is correct formatted ([the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

**Comment by rasmusrhl** [comment]
Thank you. I will :)

2017-09-01 16:46 GMT+02:00 Yihui Xie <notifications@github.com>:

**Comment by artasom** [comment]
Hello,
Sorry to bring up an old thread. I have this same issue, and I understand that the issue lays in pandoc, but  the proposed workaround doe snot work for me as I create two consecutive tables in a for loop. Hence, I cannot place an HTML comment or a `<br>` there. I have tried adding a `cat(\n)`, to no avail. Any suggestion?
Thanks in advance.

**Comment by artasom** [comment]
For any future reference, I was able to workaround the issue by adding a
cat('<br><br>')
in the chunk.
Regards.
