### ISSUE TITLE
Package does not build on read-only FS

### ISSUE THREAD

**Issue by siddharthab** [yihui/knitr#1431]
I am trying a bazel based build system for R packages, and knitr package build fails on this system because it tries to overwrite one of the input files. The input files are mounted as read-only in this build system, and I can not make an exception for knitr.

The problem code is here:
https://github.com/yihui/knitr/blob/14ee27c0ac448559e1c4cc3916f50ccd7f247336/R/citation.R#L109

This code tries to read the file `inst/misc/tweak_bib.csv` on package load, reorder it, and then write it back as the original file. This is non-standard behavior and as far as I can see, does not lead to any functional difference. The list to manually tweak is read from the csv, reordered, and cached in the package's namespace. The file `inst/misc/tweak_bib.csv` is never read again anywhere else. I can understand that writing it back would have helped in debugging when originally writing that function.

Can you please please consider removing that line? I am able to build 100+ R packages using my build system but knitr is the only exception because of this behavior.

I will appreciate any help you can provide.

Thanks.

**Comment by siddharthab** [comment]
To be more clear, this is the fix I am proposing: https://github.com/siddharthab/knitr/commit/485b766d7e9768c498fbd49a563eb772aaa993b3

**Comment by yihui** [comment]
I wonder why you had to build the package from source instead of installing from CRAN. Anyway, it should be fixed now. Thanks for the report!

**Comment by siddharthab** [comment]
Thank you so much for the quick fix. I am trying to design a new incremental build system for R packages, so the point is to build from source. 😄
