### ISSUE TITLE
Nested child documents require full path

### ISSUE THREAD

**Issue by lucacerone** [yihui/knitr#1434]
When I have nested child documents it seems that the directory is changed so I have to use the full path.

This seems a bug to me, but I might be wrong.

For example, I have a project made of master.Rmd, child.Rmd, childchild.Rmd, all in the same directory.

In `master.Rmd` I place the YAML to process my R-markdown document as html and include the file child.Rmd, for example:

     ---
     title: "Untitled"
     output: html_document
     ---

     ```{r child='child.Rmd'}
     ```

In `child.Rmd` I have

      sometext
   
      ```{r child='childchild.Rmd'}
      ```

When I try to compile `master.Rmd` to html, it fails complaining that it can't find `childchild.Rmd`.

If I change the content of `child.Rmd` to

      sometext
   
      ```{r child='/full/path/childchild.Rmd'}
      ```
Then everything works flawlessly.

I am not sure if it is a bug, but I think it would make sense that the full path is resolved from `master.Rmd` and applied to all children, which is best when authoring a multi-author document where the paths could differ.

Regardless of the decision on how to tackle this, thanks for reading Yihui!

**Comment by yihui** [comment]
I'm not sure what the problem is here and I don't have time to investigate it, but you certainly should not have to write the full path, so it sounds like a bug. Perhaps you are the first person who has ever tried a grandchild document (and cared to report the issue).

**Comment by lucacerone** [comment]
Thanks Yihui! I am not aware of how knitr works internally, but if you can point me to where to look, I can see if I spot anything and, in case, make a pull request.

From what I understood from the error message the main issue is that when compiling 'child.Rmd' the function is working from a temporary directory  and therefore when it searches for 'childchild.Rmd' (yeah grandchild, might have been a better name) it can't find it. 
By using the full path to childchild.Rmd it works without problems.

**Comment by lucacerone** [comment]
Yihui, apologies this seems to be an issue with shiny rmarkdown and flexdashboard rather.

When working with pure Rmarkdown html_document everything works fine!
I'll open the bug to their project!

**Comment by yihui** [comment]
No worries. That sounds about right to me, because knitr won't render documents in the temp dir, but Shiny R Markdown documents may be rendered differently.
