### ISSUE TITLE
R output is invisible

### ISSUE THREAD

**Issue by jszhao** [yihui/knitr#1435]
Here is the minimal example. I described the issue in the code.

```
<<include=FALSE,cache=FALSE>>=
library(knitr)
opts_chunk$set(comment=NA,
               prompt=TRUE)
@

\documentclass{article}

\begin{document}

In the following example, the output of \verb+dim(ex)+ and 
\verb+colnames(ex)+ are not visible. If you reduced or increased the value of 
\verb+\vskip+ to make all contents of \verb+read.csv+ in one page, the 
output of \verb+dim(ex)+ and \verb+colnames(ex)+ would be visible. Is it a bug 
in \verb+knitr+? \vskip 400pt

<<>>=
ex <- read.csv(textConnection("
con,temp,times,content
31,a,I,B
54,b,I,A
38,c,I,C
53,a,II,A
49,b,II,C
42,c,II,B
57,a,III,C
62,b,III,B
64,c,III,A"), header = TRUE)
dim(ex)
colnames(ex)
@

\end{document}
```

**Comment by jszhao** [comment]
the issue is caused by `\colorbox` in `kframe` environment.

**Comment by jszhao** [comment]
it is not a bug in `knitr`, it's a bug in `framed` package.

**Comment by yihui** [comment]
Okay. If you are sure this is not a knitr issue, please feel free to close it. Thanks!

**Comment by jszhao** [comment]
after investing some time, i don't find a way to deal with this issue under the current situation. It seems that `shaded` environment in `framed` package can not deal with color when page beaks in `alltt` environment. And `knitr` defined the `kframe` environment based on `framed` package and `shaded` environment, i.e., using `\colorbox`. I suggest `knitr` to move to `mdframed` package, which is much robust.

**Comment by jszhao** [comment]
when i replaced 
```
\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother
```
in the output .tex file with
```
\newenvironment{kframe}{}{}
\surroundwithmdframed[
   hidealllines=true,
   backgroundcolor=shadecolor
]{kframe}
```
All is what i expect.

**Comment by yihui** [comment]
You can probably `\renewenvironment`? I don't want to use `mdframed` since `framed` is very lightweight.

**Comment by jszhao** [comment]
Thanks for the suggestion of `\renewenvironment`. Yes, `mdframed` is more heavy than `framed`.

**Comment by jszhao** [comment]
Now, you can close this issue. Thanks again.
