### ISSUE TITLE
Python environment persistance across chunks

### ISSUE THREAD

**Issue by talegari** [yihui/knitr#1440]
> Each python chunk starts a own session? Would it be a better idea to maintain a single python session while knitting?

Here is the output of the minimal reproducible result: [repr.pdf](https://github.com/yihui/knitr/files/1354941/repr.pdf)

````
### Persistance across chunks with R and Python

Lets define x in R

```{r}
# running R
x <- 1
```

Does R remember?

```{r}
# running R
x
```

yes it does!

```{python}
# running python
y = 1
```

Does python remember?

```{python}
# running python
try:
  print(y)
except:
  print("I do not remember 'y'")
```

No, it does not.

----

```{r}
sessionInfo()
```

```{python}
import IPython
print(IPython.sys_info())
```
````

**Comment by yihui** [comment]
This is a known issue and we will definitely improve it (hopefully by the end of this year).

**Comment by pjc42** [comment]
fwiw, imho, this would mean many using python could switch from juypter to knitr, starting with me. many thanks

**Comment by yihui** [comment]
We have started working on it: https://github.com/rstudio/reticulate/pull/107

**Comment by yihui** [comment]
Please test the dev version of reticulate. After `devtools::install_github('rstudio/reticulate')`, you can set up the python engine via this in your first R code chunk:

```r
knitr::knit_engines$set(python = reticulate::eng_python)
```

Then later Python code chunks should be executed in the same Python session.

**Comment by pjc42** [comment]
this installed but did not persist the Python session across chunks in an Rmd file on Windows x64

{r} code chunk
```{r}
devtools::install_github('rstudio/reticulate')
knitr::knit_engines$set(python = reticulate::eng_python)
```
`
Skipping install of 'reticulate' from a github remote, the SHA1 (3f3c2277) has not changed since last install.
  Use `force = TRUE` to force installation
`
trying:

{python} chunk
```{python}
x = 99
print(x)
```
99

{python} chunk
```{python}
print(x)
```
`
Traceback (most recent call last):
  File "C:\Users\pjc\AppData\Local\Temp\Rtmp46YyUn\chunk-code-f4c63c523eb.txt", line 1, in <module>
    print(x)
NameError: name 'x' is not defined
`

**Comment by yihui** [comment]
I cannot reproduce your issue on macOS:

````
```{r}
knitr::knit_engines$set(python = reticulate::eng_python)
```

```{python}
x = 99
print(x)
```

```{python}
print(x)
```
````

How exactly did you compile your Rmd document?

**Comment by pjc42** [comment]
my bad.

* compiles OK when knited, see `eg-knitr-python-01.pdf`
* my reported error is when evaluate chunks one at a time in Rmd doc in RStudio, or run preview of .Rmd in RStudio

[eg-knitr-python-01.pdf](https://github.com/yihui/knitr/files/1409397/eg-knitr-python-01.pdf)

**Comment by yihui** [comment]
For now, we only support the `Knit` button to compile the whole report. If you want to run the code chunks one by one in the RStudio IDE, I guess we have not added the support yet. You may file a feature request https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by pjc42** [comment]
Thank you! Another great job. Appreciate having it in knitr; have filed request for RStudio.

**Comment by yihui** [comment]
I didn't contribute anything this time. @kevinushey was our hero 😁

**Comment by kevinushey** [comment]
Support for this feature in RStudio with R Markdown documents / R Notebooks is forthcoming, but we wanted to get this ready for users ASAP regardless!

**Comment by yihui** [comment]
The python engine in the **reticulate** package has become the default in the current development version of **knitr**. I'd truly appreciate it if you can test it before I release a new version of **knitr** to CRAN. So far I have only discovered a small bug: https://github.com/rstudio/reticulate/issues/126.
