### ISSUE TITLE
knitr creates a copy of evaluate::evaluate as the default evaluate hook value

### ISSUE THREAD

**Issue by aronatkins** [yihui/knitr#1441]
The default `evaluate` hook is defined as:
https://github.com/yihui/knitr/blob/0d648a67275cda5f554a0d724dc2bb4ab0c7dd6f/R/hooks.R#L9-L14

This means that the default hook is tied to whatever version of `evaluate` was available at the time `knitr` was installed. If the version of `evaluate` changes, the knitr hook is not changed to reflect the new definition of `evaluate::evaluate`.

This explains errors like:
```
Quitting from lines 9-10 (helloworld1.Rmd)
Error in evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,  :
  unused argument (include_timing = include_timing)
Calls: <Anonymous> ... call_block -> block_exec -> in_dir -> evaluate -> evaluate_call
```

Reported here:
https://stackoverflow.com/questions/40198189/r-markdown-error-in-evaluate-call-when-knitting-any-rmd-file

We have also seen this problem when trying to use knitr inside a packrat cache. In the packrat scenario, we may be using the same version of knitr with multiple versions of evaluate (depending on a particular piece of content).

You probably can avoid this issue with something like:
```r
.default.hooks = list(
  # ...
  evaluate = function(...) evaluate::evaluate(...)
  # ...
)
```

**Comment by aronatkins** [comment]
Workaround is to re-register the evaluate hook based on the version of `evaluate::evaluate` available:

```r
knitr::knit_hooks$set(evaluate = evaluate::evaluate)
```

**Comment by yihui** [comment]
Sounds like a reasonable fix. Done. Thanks @aronatkins!
