### ISSUE TITLE
export 'wrap' for use by other packages defining custom engines?

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1442]
Motivation: I'm working on defining a custom Python engine using the `reticulate` package, and I'd like to be able to interleave input and output in a similar way as to what we get when running R code chunks. This implies mimicing the output format produced by `evaluate::evaluate()`, if I understand correctly.

These outputs are generally post-processed using the `knitr` `wrap()` function. Would it be sensible for `knitr` to export this function? Or is there another API that I should be considering here? (Note that `engine_output()` seems to assume that a single block of source code is followed by a single block of output; I'd like to do something a bit more nuanced if possible)

**Comment by yihui** [comment]
I'm happy to export it. The only reason that I'm hesitating is that `wrap()` is a sloppy function name :) Let me think a little more about it.

**Comment by yihui** [comment]
I just extended `engine_output()` so that you can pass a list of the similar structure as `evaluate::evaluate()` output to it, e.g.

```r
engine_output(CHUNK_OPTIONS, out = LIST)
```

where `LIST` can be a list like this:

```r
list(
  structure(list(src = '1 + 1'), class = 'source'),
  '2',
  structure(list(src = 'print("hello world!")', class = 'source'),
  'hello world!'
)
```

Please let me know if that suffices.

**Comment by kevinushey** [comment]
Great! This is exactly what I need. Thanks Yihui!
