### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AbhishekSinghVerma** [yihui/knitr#1445]
I strongly believe that is the issue which have caused r studio commercial server crash today. It is present in stackoverflow for quite a while now.

https://stackoverflow.com/questions/39319558/pandoc-rstudio-knitr-memory-leak

Also author provides reproducible example here:

https://github.com/bw4sz/Whales/blob/master/SingleSpecies.Rmd

**Comment by yihui** [comment]
As far as I can see, knitr was one of the 16 packages used in the example you mentioned, so I wonder why you are so sure the memory leak was caused by knitr instead of the other 15 packages. In other words, what I need is a minimal reproducible example. Thanks!
