### ISSUE TITLE
R chunk inside blockquotes has extra >

### ISSUE THREAD

**Issue by rgaiacs** [yihui/knitr#1446]
For different reasons users want to use R chunk inside blockquotes. With knitr 1.17, when users try to do it the Markdown blockquotes has some extra `>`, used as the [markup for blockquotes](https://daringfireball.net/projects/markdown/syntax#blockquote).

# Minimal Reproducible Example

````
---
title: Foo
output:
  md_document:
    variant: markdown
---

```{r, eval = FALSE}
x <- 2

x <- x + 1
```

> Foo bar ...
>
> ```{r, eval = FALSE}
> x <- 2
>
> x <- x + 1
>
> x <- x + 1
> ```
````

# Expected behaviour

````
---
output:
  md_document:
    variant: markdown
title: Foo
---

``` {.r}
x <- 2

x <- x + 1
```

> Foo bar ...
>
> ``` {.r}
> x <- 2
>
> x <- x + 1
>
> x <- x + 1
> ```
````

# Knitr 1.17 behaviour

````
---
output:
  md_document:
    variant: markdown
title: Foo
---

``` {.r}
x <- 2

x <- x + 1
```

> Foo bar ...
>
> ``` {.r}
> x <- 2
> >
> x <- x + 1
> >
> x <- x + 1
> ```
````

# Acknowledges

This was first reported by @mfoos at https://github.com/swcarpentry/r-novice-gapminder/issues/314#issuecomment-337096826.

**Comment by yihui** [comment]
Please read the issue template carefully before you file an issue to make sure your issue is correct formatted (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

**Comment by rgaiacs** [comment]
@yihui Sorry for the bad format. :-( It is fixed now.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

If you don't want to wait for the next release, you have to add a space after `>` on those empty lines in the blockquote, e.g.

````
---
title: Foo
output:
  md_document:
    variant: markdown
---

```{r, eval = FALSE}
x <- 2

x <- x + 1
```

> Foo bar ...
>
> ```{r, eval = FALSE}
> x <- 2
> 
> x <- x + 1
> 
> x <- x + 1
> ```
````

**Comment by rgaiacs** [comment]
> Should be fixed now.

Thanks very much.
