### ISSUE TITLE
Engines needs a rewrite

### ISSUE THREAD

**Issue by thk686** [yihui/knitr#1447]
I've played around with implementing knitr engines and that has led me to look at the code. There is a lot of conditional code floating around in engine.R that should be made separate to each engine. Could we not have some object that is passed that contains all of the code relevant to that engine? The code in engine.R should not reference any specific engine if it is to be reusable. Rather the engine should have an api that is called by the code in engine.R. I'd do it but do not have time at the moment so I thought I'd pass the idea along.

**Comment by yihui** [comment]
Thanks for the feedback. Unfortunately I don't have time, either :(
