### ISSUE TITLE
FR: fig.dim chunk option

### ISSUE THREAD

**Issue by MichaelChirico** [yihui/knitr#1448]
This would purely be a convenience feature, but it would be nice to specify `fig.dim = c(7, 9)` to supersede the combination `fig.width = 7, fig.height = 9` and be interpreted as such internally.

Hope it's clear my intention, can flesh out with more details if requested.

**Comment by yihui** [comment]
That sounds like a good idea!

**Comment by MichaelChirico** [comment]
Cool! I'm happy to file a PR if you'd like. I've actually never looked at `knitr` internals before though, so a nudge in the right direction (where to look for how these options are parsed) would also be appreciated.

**Comment by yihui** [comment]
You can check if `length(options$fig.dim) == 2` and set fig.width / fig.height accordingly in `fix_options()`, just like what I did for `fig.asp`:
https://github.com/yihui/knitr/blob/6f69c4224508328a3f92b3faf4fb7b7d810969ba/R/utils.R#L265-L268

**Comment by MichaelChirico** [comment]
Oh neat, how'd you add that inline code snippet there :open_mouth: 

working now...

**Comment by MichaelChirico** [comment]
Hmm. `fig.asp` doesn't appear to be documented currently (`grep asp man/*` shows nothing relevant)? Should I add documentation for `fig.dim`?
