### ISSUE TITLE
Why does R notebook display truncated lines in “html_notebook” output?

### ISSUE THREAD

**Issue by mt1022** [yihui/knitr#1451]
I have a R notebook named "test.Rmd" with the following content:

    ---
    title: "R Notebook"
    output: html_notebook
    ---
    ```{sh}
    faToTwoBit dmel-all-chromosome-r6.04.fasta dmel-all-chromosome-r6.04.2bit
    ```

Then rstudio will create "test.nb.html" automatically. However, the code chunks are wrongly displayed in the html:

[![enter image description here][1]][1]

It only displayed `bit`, instead of the entire line (`faToTwoBit dmel-all-chromosome-r6.04.fasta dmel-all-chromosome-r6.04.2bit`).

I have asked [this question on SO](https://stackoverflow.com/questions/47000407/why-does-r-notebook-display-truncated-lines-in-html-notebook-output)  and receive a workaround from Kevin Arseneau. I was suggested to report the issue here.

In my real case, I only want to display the shell commonds as a code block in the final notebook (The commands were actually run on a server). I also met similar issues when I insert code chunk of shell commands. I am not sure whether this is a bug or my markdown syntax is wrong, and hope to find a better solution here.

  [1]: https://i.stack.imgur.com/wVfRb.png

**Comment by yihui** [comment]
I don't think this is a **knitr** issue, since `html_document` works. I believe it is an RStudio or rmarkdown issue. Please report to https://github.com/rstudio/rstudio/issues.
