### ISSUE TITLE
External Code Chunks for other kernels/engines - Feature Request

### ISSUE THREAD

**Issue by brittAnderson** [yihui/knitr#1455]
I very much enjoy the ability to include chunks of R code from an external R file. However, I don't believe this can be easily done for haskell as the syntax for a comment in haskell code is different (either `--` for inline or `{- ... -}` for multiline rather than the hash character. Is it possible to add support so that one could specify with an option the character combination to use to identify a chunk label in an external source file to be something other than `##`?

**Comment by yihui** [comment]
Done. You can use

```
-- ---- chunk-label ----

code
```
