### ISSUE TITLE
Please consider changing the default setting for auto_pdf to 'FALSE'

### ISSUE THREAD

**Issue by mebden** [yihui/knitr#1456]
Hi Yihui, 

The auto_pdf parameter in include_graphics is by default 'TRUE'. To deactivate it, we must remember to type something like:

    knitr::include_graphics("myfile.png", auto_pdf = FALSE)

I appreciate the motivation for auto_pdf=TRUE, and have read ?knitr::include_graphics . However, last month, working to a deadline with multiple files, I ended up distributing to **hundreds of people** a file which contained within it an inappropriate .pdf instead of the correct .png file. That R ignored the filename I gave it and selected a different file (same name, different extension) led to an embarrassing result.

IMO it's too much of a liability to use TRUE as the default setting for auto_pdf. To my mind, the high cost to a few unlucky users such as me should outweigh the incremental aesthetic benefits gained elsewhere.

I hope I've explained adequately the problem lurking in auto_pdf's current default, particularly for novice users - Kevin from support.rstudio.com thought it might be worth bringing up with you, hence this post. Thanks for listening.

**Comment by yihui** [comment]
Sorry about that. I just changed the default to `FALSE`. Thanks for the suggestion!

**Comment by mebden** [comment]
Thank you!
