### ISSUE TITLE
Might it be possible to add Julia support to knitr, Rmd, and perhaps R/Studio?

### ISSUE THREAD

**Issue by wsphd** [yihui/knitr#1458]

**Comment by yihui** [comment]
@Non-Contradiction is the expert: https://github.com/Non-Contradiction/JuliaCall/pull/20

I experimented with Julia long long ago: https://github.com/yihui/runr I'm not sure if the **runr** package still works.

**Comment by Non-Contradiction** [comment]
The package JuliaCall provides a Julia language engine for knitr. And the newer version of JuliaCall, with an improved Julia engine, just got released on CRAN. <https://cran.r-project.org/web/packages/JuliaCall/vignettes/Julia_in_RMarkdown.html> is a vignette to illustrate the basic usage of the engine. Any feedback is welcome!

**Comment by yihui** [comment]
@Non-Contradiction I'm interested in adding it as the default in knitr, so that users don't need to run `knitr::knit_engines$set(julia = JuliaCall::eng_juliacall)` explicitly. What do you think?

**Comment by wsphd** [comment]
Yihui,

Yes.  That's something along the lines of my thinking.  The latest 
version of JuliaCall helps in this regard.  See the latest vignette at:

https://cran.r-project.org/web/packages/JuliaCall/vignettes/JuliaCall_in_Jupyter_R_Notebook.html

Julia support helps in two major ways: It can--in some cases--reduce the 
need for (albeit excellent) RCpp for speed, and also, it's useful for 
optimization (especially contemporary convex optimization) problems 
because its code can be better (meta-programming, LLVM, never slower 
than twice as slow as C, etc).

It's just that many of us are used to (spoiled) by your (et al.) Rmd 
work and that of primary IDE use of R/Studio (sigh and thanks).

Also, don't be fooled by the Julia 0.6.1 version numbering; the version 
number belies its maturity and in-production use.

Best,

Wayne

**Comment by Non-Contradiction** [comment]
@yihui 
Great idea! What do we need to do to make it a default engine in knitr?

**Comment by yihui** [comment]
@Non-Contradiction You don't need to do anything (you have done all the hard work). I just added the `julia` engine in **knitr** via 39567eb. Thanks!

**Comment by Non-Contradiction** [comment]
@yihui Thanks! 

And @wsphd thanks for bringing this up. Hope the julia engine suits your need and any feedback is welcome.

**Comment by wsphd** [comment]
Thanks to everyone...

Wayne

**Comment by konstunn** [comment]
May I report an issue right here cause I'm not sure where is the problem and we have all the guys following this thread.

I have very simple `Rnw` document as the following:

```
\documentclass{article}
\begin{document}
<<mychunk, engine='julia'>>
using PyPlot
x = linspace(0., 10.)
y = sin.(x)
plot(x, y)
@
\end{document}
```

I get the following error when knit the document:

```
Error in options$results = "asis"  :
    argument "options" is missing, with no default
```

**Comment by yihui** [comment]
@Non-Contradiction Any ideas?

**Comment by konstunn** [comment]
I also get

```
Error in wrap.knit_asis(out) :                                                         │~                                                                                      
  argument "options" is missing, with no default
```

**Comment by Non-Contradiction** [comment]
@konstunn There are two problems involved. The first is that the `JuliaCall` engine only works for `RMarkdown` document, including pdf, md and html output, and `Rnw` document is not supported yet. I can investigate into the problem, and it seems not a difficult task to get it work for `Rnw` although it needs some time.

The second problem is `JuliaCall` engine currently works mainly for julia `Plots` package, it's able to work directly for `PyPlot` but needs some tweaks. The way that works for `Plots` may look something like this:
```
```{r, engine='julia'}
using Plots
pyplot()
x = linspace(0.,10.)
y = sin.(x); # the semicolon is used to suppress the output because the output will trigger some Unicode error in pdf-output on my mac
plot(x, y)
```

**Comment by Non-Contradiction** [comment]
@konstunn Would you like to open an issue/feature request at <https://github.com/Non-Contradiction/JuliaCall/issues>? I will work on it when available.
