### ISSUE TITLE
Caption not printed in one-column data.frame using kable

### ISSUE THREAD

**Issue by Henrik-P** [yihui/knitr#1460]
When calling `kable` on a data frame with more than one column, the caption is printed without specifying `format`. In one-column data frames, no caption is printed, unless `format = "html"` is  specified.

The .Rmd file:
    
    ---
    output: html_document
    ---

    ```{r results='asis'}
    library(knitr)
    d <- data.frame(x = 1, y = 2)
    kable(d, caption = "Two columns")

    kable(d[ , 1, drop = FALSE], caption = "One column, caption not printed")

    d1 <- data.frame(x = 1)
    kable(d1, caption = "One column, caption not printed")

    kable(d1, format = "html", caption = "One column, caption printed")
    ```

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
