### ISSUE TITLE
render beamer_presentation setting figure caption changes figure alignment

### ISSUE THREAD

**Issue by eeenilsson** [yihui/knitr#1461]
In "test_presentation.rmd" : 

```
---
title: "Sometitle"
output: beamer_presentation
     fig_caption: true
---

# Slide 1

![Test image](http://www.pngall.com/wp-content/uploads/2017/01/Feather-PNG-Picture.png)

```
Using `render("test_presentation.rmd", "beamer_presentation")` gives a center aligned image.

Changing to `fig_caption: false` makes the image left-aligned.

**Comment by eeenilsson** [comment]
This might be due to "... for Markdown output, forcing figure alignments will lead to the HTML tag <img /> instead of the original Markdown syntax ![]()" ? See https://yihui.name/knitr/options/

I ended up using the following solution: 
```{r, out.width = "400px"}
knitr::include_graphics("path/to/image.png")
```

**Comment by yihui** [comment]
No, that is not the reason.

With `fig_caption: true`, figures are put in the LaTeX `figure` environments, and in such environments, figures are centered by default in LaTeX.

Without this option, figures are simply in `\includegraphics{}` and won't be centered (left-aligned by default).

`knitr::include_graphics()` is the correct and portable solution in this case and you can use the chunk option `fig.align = "center"` (if you care about portability).
