### ISSUE TITLE
knitr::kable() seems to mis-order column names or column values with sparklyr

### ISSUE THREAD

**Issue by JohnMount** [yihui/knitr#1462]
`knitr::kable()` seems to mis-order column names or column values with `sparklyr`.  Notice the difference in directly piping the `sparklyr` table to `knitr::kable()` versus piping the `dplyr::collect()` version.

Reprex of rendered tables not pasteable, so making Markdown example.

[knitrissue.Rmd.txt](https://github.com/yihui/knitr/files/1485901/knitrissue.Rmd.txt)
[knitrissue.pdf](https://github.com/yihui/knitr/files/1485902/knitrissue.pdf)

**Comment by yihui** [comment]
That is not enough evidence to show `kabel()` is the culprit (e.g. it could be `dplyr::collect()`'s fault). Print the data without `kable()` and see what it looks like.

**Comment by JohnMount** [comment]
I have run it again with `print()` and `glimpse()`.  All presentations seem to agree on values, just direct `kable()` has a wrong order of the column names.

[knitrissue.pdf](https://github.com/yihui/knitr/files/1491354/knitrissue.pdf)
[knitrissue.Rmd.txt](https://github.com/yihui/knitr/files/1491355/knitrissue.Rmd.txt)

**Comment by JohnMount** [comment]
Found the issue.  `as.data.frame()` reordered the columns.  So lines 131 and 132 of `knitr/R/table.R` pull a different order for column name than column values.

Original code:

```r
  if (identical(col.names, NA)) col.names = colnames(x)
  if (!is.matrix(x)) x = as.data.frame(x)
```

I would strongly suggest reversing the order of those lines.

**Comment by yihui** [comment]
I'll switch the two lines. I was just about to file an issue to dplyr, and thanks for beating me :)

**Comment by JohnMount** [comment]
No problem.  I ending up researching it as I was really starting to wonder how `knitr` was grabbing the data.  I fix-up the [`dplyr` issue](https://github.com/tidyverse/dplyr/issues/3216) as I think the columns should be stable.
