### ISSUE TITLE
Captions don't work without `out.extra`

### ISSUE THREAD

**Issue by eliocamp** [yihui/knitr#1464]
This doesn't work:

```
---
title: "Test subfigures"
output:
  pdf_document: 
    extra_dependencies: subfig
---
   
```{r pressure-ncol, echo = FALSE, fig.show='hold', fig.cap = "caption", fig.subcap = c("1", "2")}
plot(pressure)

plot(cars)
```

![image](https://user-images.githubusercontent.com/8617595/33142067-f2b833c0-cf93-11e7-9a12-a6bcafc8b1b2.png)

I need to add `out.extra = ""`:

```
---
title: "Test subfigures"
output:
  pdf_document: 
    extra_dependencies: subfig
---
   
```{r pressure-ncol, out.extra = "", fig.show='hold', echo = FALSE, fig.cap = "caption", fig.subcap = c("1", "2")}
plot(pressure)

plot(cars)
```
![image](https://user-images.githubusercontent.com/8617595/33142184-560f7406-cf94-11e7-8ffe-63cad336b678.png)

I'm trying to figure out why this is happening and it seems that if there are multiple plots, knitr doesn't call `hook_plot_tex()` if `out.extra = NULL`.

**Comment by eliocamp** [comment]
Here's the problem: 
https://github.com/yihui/knitr/blob/dc7bd3e6074491d6cfd53ae4090facf818d333a2/R/hooks-md.R#L7

The code only calls `hook_plot_tex()` either `out.width`, `out.height` or `out.extra` are not NULL or if `fig.align` is different from `"default"`. But this condition is never satisfied in the default case and `hook_plot_tex()` works fine there.

**Comment by yihui** [comment]
Although it is a hack, I don't want to change it. You have to use `out.extra = ""`.

**Comment by eliocamp** [comment]
May I ask why?

**Comment by yihui** [comment]
Yes, because I'm not confident about using raw LaTeX code in Markdown: https://github.com/jgm/pandoc/issues/2493 I tend to render Markdown `![]()` when possible, and only use `hook_plot_tex` if users opt in specifically, e.g., through `out.extra`, or

```r
if (knitr::is_latex_output()) knitr::knit_hooks$set(plot = knitr::hook_plot_tex)
```

**Comment by eliocamp** [comment]
Oh, ok. That's fair. 
Wouldn't the user be opting in specifically when using `fig.cap` or `fig.subcap`?

**Comment by yihui** [comment]
For `fig.cap`, we don't have to use LaTeX, because Pandoc can translate `![caption](path)` to the `figure` environment with `\caption{}` in LaTeX. I agree `fig.subcap` would be a better trigger.

**Comment by eliocamp** [comment]
Something like this would be ok?
```
  if (!is.null(options$out.width) || !is.null(options$out.height) ||
      !is.null(options$out.extra) || options$fig.align != 'default' ||
      !is.null(options$fig.subcap)) {
    if (to %in% c('beamer', 'latex')) {
      # Pandoc < 1.13 does not support \caption[]{} so suppress short caption
      if (is.null(options$fig.scap)) options$fig.scap = NA
      return(hook_plot_tex(x, options))
}
```

**Comment by yihui** [comment]
Yes.
