### ISSUE TITLE
Using a YAML header argument in knitr

### ISSUE THREAD

**Issue by kristang** [yihui/knitr#1467]
Hello, 

I've had a post on stackoverflow up for a little while now, and I figured I would throw it in here to see if anyone had any suggestions or comments?

https://stackoverflow.com/questions/36642411/using-a-yaml-header-argument-in-knitr 

The basic idea being that I want to have one .rmd file for my slides, and then just changing one option to signify that it's for printing by students, or for me presenting.

**Comment by yihui** [comment]
Sorry, but I don't have a solution. The number of experts on SO should be much larger than the number of people watching this repo, so you may still need to wait on SO.
