### ISSUE TITLE
Changes to environments with `with()` are not cached

### ISSUE THREAD

**Issue by dlindelof** [yihui/knitr#1469]
It would appear that changes to an `environment` object made with `with()` are not cached:

    ```{r}
    foo <- new.env()
    ```

    ```{r, cache=TRUE}
    with(foo, bar <- 42)
    ```

    ```{r}
    foo$bar
    ```

This will print 42 the first time it is run, and `NULL` afterwards.

I'm not sure if this is a bug (it could be argued that `with()` is a function called for its side-effects) but I'm experimenting with the idea of collecting all analysis results in a set of `environment`s, and it would be great if this would play nicely with `knitr`' s cache.

**Comment by yihui** [comment]
This is not a bug. Please do me a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with a reproducible example), and let me know the link to your post if you don't get an answer in a few days. Thanks!

**Comment by dlindelof** [comment]
Ok, will do.

Am 29. November 2017 um 16:18:10, Yihui Xie (notifications@github.com) schrieb:

This is not a bug. Please do me a favor to ask it on StackOverflow instead (with a reproducible example), and let me know the link to your post if you don't get an answer in a few days. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

David Lindelöf, Ph.D.
+41 (0)79 415 66 41 or skype:david.lindelof
http://computersandbuildings.com
Follow me on Twitter:
http://twitter.com/dlindelof
