### ISSUE TITLE
Figure captions lose their numbering under headings marked by {-}

### ISSUE THREAD

**Issue by jrosenfeld13** [yihui/knitr#1470]
Figure captions become "unnumbered" when they are called under headings marked by {-}. 

Example:

````
# Welcome! {-}

```{r title, echo=FALSE, fig.cap='Title!', fig.align='center'}
knitr::include_url(URL_HERE)
```
````

The output into html loses the numbering for the figure caption (presumably because the heading above it should be unnumbered). The output is:

```
<div class="figure" style="text-align: center"><span id="fig:title"></span>
<iframe src="URL_HERE" width="672" height="400px">
</iframe>
<p class="caption">
Figure .: Title!
</p>
</div>
```

"**Figure .: Title!**" being the main issue there where it should be "Figure 1: Title!"

**Comment by yihui** [comment]
This does not sound like a **knitr** issue. Please always provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/).
