### ISSUE TITLE
rstudio notebook preview and knit to html differ in behavior

### ISSUE THREAD

**Issue by devereaux** [yihui/knitr#1472]
The following minimal reproducible example unconditionally output 'hello world', regardless of the chunk content, for a newly defined m engine:

```{r}
eng_dummy_m= function (options) 
{
  knitr::engine_output(options, options$code, "hello world\n")
}

knitr::knit_engines$set(m=eng_dummy_m)
```

It works differently in Rstudio notebook and a knitted file:
```{m}
looks like it expects some bash:
 it returns '/bin/sh: 1: m: not found' in a rstudio notebook,
 it returns  '## hello world' if knitted
```

This impacts the creation of custom engine, like on https://support.rstudio.com/hc/en-us/community/posts/115008946228-knitr-language-engines-not-working-in-windows

If it is not possible to have a notebook and a markdown giving an identical result, would it be at least possible to change evaluate, so that the notebook can also show 'hello world' after defining a hook?

**Comment by yihui** [comment]
This is not a knitr issue. You have filed to the right place: https://github.com/rstudio/rstudio/issues/1822
