### ISSUE TITLE
Mutiple plots in one chunk `fig.cap` does not work when output as a MS-word document

### ISSUE THREAD

**Issue by psychelzh** [yihui/knitr#1473]
I used the following `Rmarkdown` to generate two figures in one chunk, with one caption each.

````r
---
title: "Untitled"
subtitle: "Subtitle"
author: "Anonymous"
output: word_document
---

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE, fig.subcap=c("Figure 1", "Figure 2")}
plot(pressure)
plot(head(pressure))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
````

Unfortunately, seemingly it does not support MS-word output, and with the following warning messages:

```
Warning messages:
1: In (knit_hooks$get("plot"))(file, reduce_plot_opts(options)) :
  The chunk option fig.show="hold" is not supported for Word output
2: In (knit_hooks$get("plot"))(file, reduce_plot_opts(options)) :
  The chunk option fig.show="hold" is not supported for Word output
```

And there is no caption for figures, too. See the following screenshots:

![default](https://user-images.githubusercontent.com/13306020/33832728-2c8ef362-deb8-11e7-837a-4f8f2c332f1e.png)

Will `knitr` support it in the future releases?

**Comment by yihui** [comment]
First, you have to use the option `fig_caption: yes`. Second, it is `fig.cap` instead of `fig.subcap`. Third, you need an empty line between the two figures: `cat('\n\n')`.

````
---
title: "Untitled"
subtitle: "Subtitle"
author: "Anonymous"
output: 
  word_document: 
    fig_caption: yes
---

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE, fig.cap=c("Figure 1", "Figure 2")}
plot(pressure)
cat('\n\n')
plot(head(pressure))
```
````

In the future, please try to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) first. Thanks!

**Comment by psychelzh** [comment]
@yihui Thank you! Perhaps I do not have enough understanding of the logic of `knitr` currently, and therefore I cannot determine whether a problem is a bug or not. I have searched **StackOverflow** at first, although in vain. I will do my best to learn more about a problem in the future before issuing a new one.
