### ISSUE TITLE
`kable` does not return sufficient number of digits

### ISSUE THREAD

**Issue by psychelzh** [yihui/knitr#1474]
For example

````
---
title: "Untitled"
author: "Anonymous"
output: word_document
---

## R Markdown

```{r}
knitr::kable(as.data.frame(matrix(c(1.1, 1.2, 1.3, 2.345, 2.333, 23.211, 1, 2, 3), ncol = 3)), digits = 2)
```
````

When there is not enough number of digits after the decimal, it won't add 0's. In some instances, it is supposed to add 0's after it, especially for `double` type numeric data.

![image](https://user-images.githubusercontent.com/13306020/33866552-4c647f5c-df32-11e7-8425-07b4c34f5cfd.png)

**Comment by yihui** [comment]
That is by design. `digits` is passed to `round()` in `kable()`, and `round(1.1, 2)` returns `1.1` instead of `1.1`.

Also note that numbers are formatted column-wise, e.g. if `1.1` and `1.11` are in the same column, `1.1` will be formatted as `1.10` because `1.11` has two decimal places.
