### ISSUE TITLE
Highlight in-line and chunk outputs for review (feature request)

### ISSUE THREAD

**Issue by dmcalli2** [yihui/knitr#1475]
I work in a tightly-regulated environment. Before they can be exported from a  secure environment, all results must be checked by a third party to ensure that there is no danger of breaching privacy.
Checking results is a significant burden on the service.
If we are able to introduce knitr into this workflow it would help. This is because with knitr the output is intrinsically more concise and is usually given with some context which will help the checkers.
Would it be possible to introduce a package option which allows us to toggle between highlighting/not highlighting in-line and chunk outputs? This would make it easier for the checker to see what is and isn't results. 

The following gives example source code and output,
source:
In 1999, there were `r nrow(my_data)` patients.
output for checking:
In 1999, there were **`15,433`** patients.
final output once checked:
In 1999, there were 15,433 patients.

**Comment by yihui** [comment]
Please do me a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (also clarify what your output format is), and let me know the link to your post if you don't get an answer in a few days. Thanks!
