### ISSUE TITLE
Add attributes on images when the output format is Word or PowerPoint

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#1478]
Currently chunk options like `out.width` and `out.height` are ignored in Word/PPT output. They should be respected since recent versions of Pandoc support them: http://pandoc.org/MANUAL.html#images (the `link_attributes` extension).

**Comment by RLesur** [comment]
I think this problem can be solved with image attributes: https://stackoverflow.com/q/50855815/6500804

**Comment by cderv** [comment]
For reference, there is an open issue in pandoc about attributes for pptx image links. see https://github.com/jgm/pandoc/issues/4586
