### ISSUE TITLE
include_table() -- (feature request)

### ISSUE THREAD

**Issue by ikashnitsky** [yihui/knitr#1480]
The idea originates from [this SO question](https://stackoverflow.com/questions/47997485).   
The function `include_graphics()` already works nicely importing tables from PDF as vector/text object. The only matter to fix are captions, since Tables and Figures should be counted/indexed/referenced separately.  The new function would give a nice option of inserting a manually layouted and saved as PDF table in rmd. Here is an [example of how an output may look like](https://habrastorage.org/webt/lr/vt/qi/lrvtqi4cjnd3wf3g3iheekthpvc.png).

**Comment by yihui** [comment]
This is a reasonable feature request, but you have to implement it by yourself and submit a PR.
