### ISSUE TITLE
Feature Request: More informative error for kable col.names

### ISSUE THREAD

**Issue by billdenney** [yihui/knitr#1485]
When `col.names` is specified for `kable`, but it is the wrong length, the error is relatively uninformative:

```r
> knitr::kable(data.frame(A=1), col.names=c("A", "B"))
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
> 
```

A simple modification here would make it much more informative:

https://github.com/yihui/knitr/blob/03682e0444457d4891474c1480c92a8eae558d9d/R/table.R#L160

Change that line to these lines (or similar):

```r
if (ncol(x) == length(col.names)) {
  colnames(x) = col.names
} else {
  stop("Argument col.names is not the same length as the number of columns of x.")
}
```

If interested, I can submit this as a pull request.

**Comment by yihui** [comment]
Yes, please submit a PR, and I prefer `stop()` to appear earlier: https://yihui.name/en/2018/01/stop-early/

**Comment by billdenney** [comment]
I put it right at the top.

(And, I prefer the same style-- do all input checking at the top so that more assumptions can be made within the code itself.  It simplifies the more complex parts of the code.)

**Comment by billdenney** [comment]
As discussed within the PR, the change appears to be more work than it's worth.
