### ISSUE TITLE
When call kable through source("xxx.R"), the kable is not printed in the html. 

### ISSUE THREAD

**Issue by doctorcgb** [yihui/knitr#1488]
I can knit the .Rmd with a kable without problem with:

````
```{r cars}
knitr::kable(cars)
```
````

However, when I put the line into a different R file and source it, the kable never appears.  If I add print before knitr::kable(cars) in this case, it will only include a console print instead of knitted html. 

````
```{r cars}
source("test.R") # test.R contains the exact command of kable.
```
````

**Comment by yihui** [comment]
Sorry, but I can only handle Github issues for bug reports and feature requests, and I don't have time to answer general questions. Please [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with minimal, self-contained, and reproducible examples). If you are not sure if it is a bug report or a question, consider using StackOverflow first (I closely watch StackOverflow questions every day). Thanks!

BTW, this specific question has been asked many many times before, e.g., https://stackoverflow.com/a/48119074/559676

**Comment by doctorcgb** [comment]
The issue is different: When being put into a separate R file and sourced
through source(), print(kable(xxx)) DOES NOT resolve the knitting issue.

**Comment by yihui** [comment]
Did you read the StackOverflow question? Did you see the chunk option `results='asis'` in the question?
