### ISSUE TITLE
echo=FALSE not working for engine='python'

### ISSUE THREAD

**Issue by cpsievert** [yihui/knitr#1489]
When I render this [python knitr-example](https://raw.githubusercontent.com/yihui/knitr-examples/master/023-engine-python.Rmd), `echo=FALSE` doesn't seem to suppress the code. I've also tried it without `ref.label` and it doesn't seem to work that way either

**Comment by jeroenjanssens** [comment]
Same for `eval=FALSE` and `include=FALSE`. I (temporary) solved this by using the code option `python.reticulate = FALSE` to disable the new Python engine based on reticulate.

**Comment by yihui** [comment]
I have been sick from yesterday, and I'll fix it later this week, unless @kevinushey is quicker than me (note that `engine_output()` has been exported from **knitr** 1.18, but I still need to patch `knitr:::wrap`).

**Comment by kevinushey** [comment]
I think these issues might already be fixed with the latest version of `reticulate` on CRAN. @cpsievert  @jeroenjanssens Can you ensure that you have the latest version of `reticulate` (v1.4) and let me know if you're still having issues?

```
install.packages("reticulate")
```

**Comment by jeroenjanssens** [comment]
I just updated `reticulate` to the latest version (v1.4) and I can confirm that it's working now. I should have known better to update all my packages first. Many thanks for your help @yihui @kevinushey!

**Comment by kevinushey** [comment]
No worries; the update to CRAN was only released today (binaries aren't even available yet) so these are brand new fixes!
