### ISSUE TITLE
[Enquiry/Discussion] Design behind the tool

### ISSUE THREAD

**Issue by lf-araujo** [yihui/knitr#1490]
Dear @yihui, thank you for this package, it helped me to create reproductive research during my PhD. Hope you are well.

The files I create with knitr are usually for my personal use, usually experiment logs to be saved in the project directory. For more complex documents (like my own thesis or a book I recently published) I tend to use a combination of gnumake and pandoc. Knitr is as powerful as these tools, but I keep coming back to them because of one feature. 

With make and pandoc I can organize the project better. The main aspect of this organization is that I can clearly separate style (cls, tex templates, doc templates, filters, etc) from contents (md files). This makes so much sense, because I can drop the style files in the style directory and my makefile takes care of running pandoc with the proper flags.

I understand where knitr comes from, its design is partially inherited from Sweave and that is fine. However, working in large documents causes the project directory to become cluttered with sources, intermediate files and the output. Style, contents and build objects are all present in the same directory.

I don't know if any of this makes sense to you. I was also a LyX user in the past, but after pandoc + make + sublime text I come less and less to LyX, as writing files is made so much easier and simpler. My makefile is publicly available [here](https://github.com/lf-araujo/mighty_make).

This made me think that perhaps knitr would benefit of a bit of this design pattern, by simply allowing the user to set the directory where source is to be found, where intermediate files should be saved (a hidden directory preferably) and where the output should be printed. Also, as an extra, load filters, templates and the cls automatically, following some heuristic.

- Does knitr already offer any of these functionalities? 
- If not, is it a good idea to incorporate a bit of folder management (I am sure there is a proper name for this type of programming pattern)?

Regards,

**Comment by yihui** [comment]
@lf-araujo Thanks for the feedback! Have you tried the **bookdown** package? I have published two books with it (and hoping to publish the third this year): https://bookdown.org/yihui/bookdown Basically all Rmd files are under the root directory, and the output files will be put under a different directory by default.

**Comment by lf-araujo** [comment]
I am using it, yes... It is a great package.

I am thinking in ways of integrating knitr with ProjectTemplate, so that it will take one (or multiple) files from the `/src` directory and spits the final files in the `/report` directory and the intermediary ones in `/cache`.

The render() function allows the definition of the output directory. What relation it holds (what are the differences to) the knitr() function? Can I set the render options in the yaml header?

**Comment by yihui** [comment]
The only option you can set in YAML for `render()` is `params`.

render() (roughly) == knit() + Pandoc.

With bookdown, you can put all your Rmd files under `/src`, and set `output_dir: ../report` in `_bookdown.yml`: https://bookdown.org/yihui/bookdown/configuration.html

I haven't used ProjectTemplate myself.
