### ISSUE TITLE
Can knitr convert R markdown to pdf without RStudio on Linux?

### ISSUE THREAD

**Issue by hliu2016** [yihui/knitr#1491]
I am a newbie to knitr, but it looks very interesting. I have tried knitr in RStudio on Windows and it works smoothly. I want to know if knitr can work without RStudio on Linux to convert  R markdown file latex embedded Latex codes to pdf? Thanks a lot.

Also, is there any tools like knitr that can compile python markdown file?

**Comment by donk3yzz** [comment]
`knitr` convert R markdown file to pdf by calling pandoc, which was internally installed in Rstudio. So maybe there are some ways to achieve that but it's beyond my knowledge.

For the second question, maybe you can edit your python document directly in R markdown( [an example](http://rmarkdown.rstudio.com/authoring_knitr_engines.html) ), or  Jupyter notebook ( I guess I shouldn't advertise it here ha-ha)

That's all I can say. Sorry for inability to solve your problem. Good luck.

**Comment by yihui** [comment]
@donk3yzz was correct: you don't need RStudio -- all you need is Pandoc. After you have installed Pandoc, you call `rmarkdown::render()` to convert R Markdown to PDF.

And yes, you can compile Python code chunks in R Markdown.
