### ISSUE TITLE
Create a kable generic

### ISSUE THREAD

**Issue by michaelquinn32** [yihui/knitr#1493]
Hi Yihui!

I hope all is well.

skimr is a downstream user of knitr and kable. We currently implement our own S3 generic for kable to provide our own S3 method for it. 

https://github.com/ropenscilabs/skimr/blob/ee10b781ad7cc935437a22dd51f32fc38cfba70d/R/skim_print.R#L54

Would you be interested in adding the generic here to provide for other future extensions?

Thanks!

**Comment by yihui** [comment]
Thanks for the suggestion! I tend not to make it an S3 generic function, although there is probably no harm. I want to keep it as simple as possible. If you want an S3 generic, you can create one with a different name, and define various methods, which eventually calls `kable()`. I don't think you really need me to change `kable()` to an S3 generic, unless you think `kable` is a really good function name :)

**Comment by michaelquinn32** [comment]
As long as your also not planning on creating a kable generic, I think our approach should be fine. Thanks for the feedback!
