### ISSUE TITLE
knit_filter() throws error for markdown input

### ISSUE THREAD

**Issue by omahdi** [yihui/knitr#1498]
Running `knit_filter()` on R markdown input does not work:
 
``` r
library(knitr)
packageVersion("knitr")
#> [1] '1.19'
fname <- tempfile(fileext = ".Rmd")
writeLines(c("---", "---"), con = fname)
knit_filter(fname)
#> Error in gsub(p$inline.code, "", x[m == 2]): invalid regular expression '(?<!(^|
#> )``)`r[ #]([^`]+)\s*`', reason 'Invalid regexp'
```

The underlying cause is a modification of the `inline.code` regexp for markdown documents introduced in #1416, which is a valid ICU pattern but not compatible with base regexps or PCRE. This change has caused problems before (see commit 138c634, also rstudio/blogdown#150) and is easily fixed e.g. by using `stringr::str_replace_all()` instead of `gsub()`.

I will gladly provide a PR for this simple change, but am seeking guidance as to how this should be handled:

- It seems that there is some redundancy: `knit_filter()` needs to identify code and inline blocks just as with regular processing, and it seems that it has not caught up with e.g. the use of `knit_patterns`. Could it be possible to build `knit_filter()` based on existing functions like `R/parser.R:split_file()`, or is it desirable to keep it as a lightweight separate function?
- As far as I can tell, this is the only pattern that works with ICU engines but not PCRE. It can, however, be reformulated to comply with PCRE. The pattern documentation at [https://yihui.name/knitr/patterns/](https://yihui.name/knitr/patterns/) does not seem to dictate which flavour of regular expressions to use; I think it would be a good idea to use the same flavour for all patterns instead of treating a single one differently. Is this interesting/relevant enough to warrant opening another issue?
- Extending on the last point (pattern compatibility): There is another place in [`R/parser.R:parse_inline()`](https://github.com/yihui/knitr/blob/1fda36f589545cd6922cd6cbdc9918e9fa778cfe/R/parser.R#L188) that treats `inline.code` as a base regexp. However, it is only executed if `inline.comment` is set, which is currently not the case for markdown patterns. Should this be changed to deal with ICU patterns (for consistency)?

**Comment by yihui** [comment]
These are great ideas and questions! Unfortunately I don't have time for a deeper investigation. You are welcome to experiment your ideas one by one (I think consistency makes a lot of sense). I may be able to review your pull requests. Thank you!

**Comment by omahdi** [comment]
Thanks for the feedback, I really appreciate it!  I am going to look into the other issues as time permits and offer suggestions if anything useful turns up.

**Comment by gadenbuie** [comment]
First, I want to apologize for the little bugs my PR (#1416) kicked off. In my defense...

[![](https://imgs.xkcd.com/comics/perl_problems.png)](https://xkcd.com/1171/)

I agree, too, that consistency of regex engine would be good and that documenting this would help prevent future issues. It seems that @yihui prefers (or did when he wrote `knitr`) base regex with `grep()`; on the other hand, considering `kntir`'s place in the tidyverse it would be nice to use `stringr`'s functions, at least for patterns that are exported or able to be customized by the user. It also seems to me just as problematic to have certain patterns require `grep(..., perl = TRUE)` as to have some patterns being run through `stringr::str_detect()`, etc. 

Would updating base regex matching to `stringr` be of interest to you, @yihui? I would be willing to work or collaborate on this.

On the other hand, the specific problem I was trying to solve was to keep the following markdown from being treated as inline code:

````
```r something
summary(cars)
```
````

Admittedly, this is probably not a major problem for most users of `knitr`, nor would I have said it was worth making an exception in the regex engine if I had realized at the time. So it may be easier to achieve consistency by seting a base-regex requirement and rolling back my previous PR.

**Comment by yihui** [comment]
No worries at all @gadenbuie. Let's just fix problems as they come. The regular expressions in knitr have indeed become a hairball (mainly because I hesitated between base regex and stringr when I first started this package). If we can untangle the hairball, that'll be great, but I'm also totally fine with the current mess, which seems to be "stable" enough :) There is no need to spend too much time on it, and I'm going to be super busy in the next couple of months, so I probably won't have time to review a substantial pull request.

**Comment by omahdi** [comment]
@gadenbuie: I did not mean to criticise your contribution, I am sorry if the wording came across as rude! My intent was to document the observed behaviour and what led up to it, so it may save others some time in the future.

**Comment by gadenbuie** [comment]
No worries @omahdi, I didn't it take as rude in any way. I just felt bad for having added another hair to the hairball 😉 Thanks for your detailed investigation, it was very helpful!

**Comment by yihui** [comment]
Haha, I'm amazed by how friendly this community is!
