### ISSUE TITLE
The chunk option 'render=' is missing on the knitr web site.

### ISSUE THREAD

**Issue by mlell** [yihui/knitr#1503]
I was searching for a way to print data.frames as nicely formatted tables per default in knitr. 

During the research, following the source code of `knitr::knit` and the functions it calls, I learned that I simply can override the `knitr::knit_print` S3 function to archieve a custom printing for certain file types. 

My main point is, that I would have found the right way to do it much quicker, if the knitr home page, https://yihui.name/knitr/options/, would list the `render=` option, which is closely related to this problem. It's currently not listed.  The help page of `knitr::knit_print` is the only place where I saw the `render=` chunk option being mentioned. Also the help of `knitr::opts_chunk` where I also looked to get a list of available chunk options, simply references the web site without the `render=` option. 

As far as I understood it, the `render=` chunk option is a great way to customize the output for one chunk alone or a few chunks, independent of the result type being printed. I therefore would like to propose that this option is also listed on the home page. 

A short paragraph, which simply redirects to the correct help pages and vignettes would be enough:

> * `render`: (`knitr::knit_print`; `function(x, ..., inline = FALSE, options = list()`) the function which formats the result of the chunk for the final output format. The function is given `x`, the object to be printed, as well as optionally, the arguments `inline` and `options`. Type in R `vignette('knit_print', package = 'knitr')` and `?knitr::knit_print` for more information.

**Comment by yihui** [comment]
That makes sense. Please edit this page https://yihui.name/knitr/options/ and send a pull request. Thank you!
