### ISSUE TITLE
Rendering pdf with longtable

### ISSUE THREAD

**Issue by rfbressan** [yihui/knitr#1504]
I'm experiencing some weird behavior in RStudio trying to render a pdf file. Working examples follow at the end.

I have a simple R script which in turn calls `rmarkdown::render("~/reports/test.Rmd")`, this script is located at ./R.

My intention is to run this script as a scheduled task by cron using `Rscript ~/R/test.R`. The real script is supposed to perform several tasks, generating the report is just one of them, that is why I need this setup.

The weird behavior. I have these files in an Rproject, I open this project in RStudio and in the **first time** I run test.R it renders the pdf perfectly. Without changing a bit, just hitting ctrl+Enter again, I get this error: 

> ! LaTeX Error: Environment longtabu undefined.
>
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                  
> l.90 \begin{longtabu}
>
> pandoc: Error producing PDF
> Erro: pandoc document conversion failed with error 43 

For some reason, now knitr (is knitr who inserts Latex preamble?) is not inserting in preamble the packages needed for longtable and etc.

First I thought it was some bug in kableExtra (longtabu), but this error also occurs using only kable, once `longtable = TRUE` is set.

If I run test.R from command line (`Rscript ~/R/test.R`), it's no problem, always renders. It happens only from within RStudio.

# ~/R/test.R

```r
rmarkdown::render(file.path(path.expand("~"), "reports", "test.Rmd"))
```

# ~/reports/test.Rmd

```r
    ---
    title: "Test"
    author: "Rafael"
    date: "`r format(Sys.time(), '%d/%m/%Y %H:%M:%S')`"
    output: 
      pdf_document:
        keep_tex: true
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    library(magrittr)
    library(tibble)
    library(kableExtra)
    ```
    
    ```{r test}
    tbl <- tibble(symbol = "TEST",
                  name = "Testing how to set column width using kable + kableExtra.",
                  date = Sys.Date(),
                  blabla = "more blablabla")
    
    knitr::kable(tbl, 
                 format = "latex",
                 booktabs = TRUE,
                 longtable = TRUE,
                 col.names = c("Symbol", 
                               "Name",
                               "Inception",
                               "Legal Structure")) %>% 
      kable_styling(full_width = TRUE) %>% 
      column_spec(2, width = "4cm") 
    ```
```

**Comment by yihui** [comment]
Cc @kableExtra. Any ideas?

**Comment by yihui** [comment]
Cc @haozhu233. Any ideas?

**Comment by haozhu233** [comment]
@rfbressan You can check out this SO Question. https://stackoverflow.com/questions/46080853/why-does-rendering-a-pdf-from-rmarkdown-require-closing-rstudio-between-renders/46083308#46083308

**Comment by yihui** [comment]
Sounds like an issue of **rmarkdown**? If you can figure it out and send a pull request, I'll definitely appreciate it.

Anyway, **knitr** is not the culprit in this case, so I'm closing this issue. Thanks!
