### ISSUE TITLE
kable_styling(full_width = T) not working with list of tables

### ISSUE THREAD

**Issue by JBGruber** [yihui/knitr#1507]
Thanks for this wonderful package. I'm really impressed how nice the tables look when created this way!

Based on [this answer](https://stackoverflow.com/a/38039391/5028841) I tried to plot a list of data frames today (which works fine). I also tried using `kable_styling(full_width = T)` to make the tables look more evenly but this gives me the error `! LaTeX Error: \begin{tabu} on input line 100 ended by \end{tabular}.` (from RStudio). I looked into the .tex file and the error message is accurate---something goes wrong with tabu and tabular. This reproduces the issue:
```
\documentclass{article}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage[normalem]{ulem}

\begin{document}
<<eval=TRUE>>=
dt1 <- mtcars[1:5, 1:6]
dt2 <- mtcars[1:3, 7:9]
dt3 <- mtcars[1:3, 7:9]

library("kableExtra")
kable(list(dt1, dt2, dt3), format = "latex", booktabs = T, 
      caption = "list of data frames") %>%
  group_rows("DF1", 0, 6) %>%
  group_rows("DF1", 7, 10) %>%
  group_rows("DF1", 11, 12) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, width = "5cm")
@
\end{document}
```
I can call each table separately and manipulate the tex output to make it look the way I want.

Note: When I tried to use `kable_styling(latex_options = c("basic", "scale_down", "HOLD_position"))`, this is only applied on the first table.

**Comment by yihui** [comment]
I'm afraid I'll have to ask @haozhu233 for help again (like in #1504)...

**Comment by haozhu233** [comment]
🤣 

@JBGruber Next time please consider file an issue [here](https://github.com/haozhu233/kableExtra/issues)

**Comment by haozhu233** [comment]
@JBGruber Just want to confirm that currently `kableExtra` cannot take list of tables from `knitr::kable`. It's technically difficult to implement this feature especially with latex. As I said, please consider submit a feature request in the link above and we will see if how other people feel about this feature.

**Comment by JBGruber** [comment]
Ok, thanks! I wasn't aware this was a `kableExtra` issue. I thought about posting it there first but it seemed to be `knitr::kable` at least to me. I'll open an issue there but I can see that it's not common to try and do this.
