### ISSUE TITLE
Bad knitr::purl() to file UTF-8 encoding

### ISSUE THREAD

**Issue by DavorJ** [yihui/knitr#1509]
Here is a very simple test.rmd file that contains UTF-8 characters:

````
---
title: 'Test'
---

```{r}
print('é and à')
```
````

RStudio is explicitly set to store rmd files in UTF-8. I verified with Notepad++ that test.rmd file is indeed in UTF-8.

I want to extract the R-code from this file in a temporary file:

`knitr::purl('test.rmd', output = tempfile(), documentation = 0L, encoding = 'UTF-8')`

This returns a path somewhere in the temp folder. I open this file in Notepad++ and see the the following:

`print('Ã© and Ã ')`

The problems seems to be within the following line (I haven't had time to check further:)

```
    writeLines(if (encoding == "") 
      res
    else native_encode(res, to = encoding), con = output, 
      useBytes = encoding != "")
```

Problem is that I want to source this file, but since some characters are not correctly encoded...

**Comment by DavorJ** [comment]
I looked a bit further into this.

```
output = file(output, encoding = 'UTF-8')
Encoding(res)
[1] "UTF-8"
res
[1] "print('é and à')"
charToRaw(res)
[1] 70 72 69 6e 74 28 27 c3 a9 20 61 6e 64 20 c3 a0 27 29
```
With `writeLines(res, con = output, useBytes = FALSE)` the text raw is:
70 72 69 6e 74 28 27 **c3 a9** 20 61 6e 64 20 c3 a0 27 29 0d 0a

With `writeLines(res, con = output, useBytes = TRUE)` this is the result:
70 72 69 6e 74 28 27 **c3 83 c2 a9** 20 61 6e 64 20 c3 83 c2 a0 27 29 0d 0a

The UTF-8 **c3 a9** has been converted to **c3 83 c2 a9** when `useBytes = TRUE` is specified. This seems inconsistent with the documentation:

> useBytes is for expert use. Normally (when false) character strings with marked encodings are converted to the current encoding before being passed to the connection (which might do further re-encoding). useBytes = TRUE suppresses the re-encoding of marked strings so they are passed byte-by-byte to the connection: this can be useful when strings have already been re-encoded by e.g. iconv. (It is invoked automatically for strings with marked encoding "bytes".)

Any thoughts?

**Comment by DavorJ** [comment]
A workaround is thus to use the write binary mode for file connection.

`output = file(output, encoding = 'UTF-8', open = 'wb')`

**Comment by yihui** [comment]
I was unable reproduce this issue on either Windows or macOS with the latest versions of R and all packages. You didn't follow the issue template to provide your `xfun::session_info('knitr')`, and there is no way for me to guess (in particular, your locale).

**Comment by DavorJ** [comment]
I just tried it again (i.e. making test.rmd as described above and purling it. The issue is stil valid.

`xfun::session_info('knitr')` output:

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Locale:
  LC_COLLATE=Dutch_Belgium.1252  LC_CTYPE=Dutch_Belgium.1252    LC_MONETARY=Dutch_Belgium.1252 LC_NUMERIC=C                  
  LC_TIME=Dutch_Belgium.1252    

Package version:
  evaluate_0.11   glue_1.2.0      graphics_3.5.0  grDevices_3.5.0 highr_0.7       knitr_1.20      magrittr_1.5    markdown_0.8    methods_3.5.0  
  mime_0.5        stats_3.5.0     stringi_1.1.7   stringr_1.3.1   tools_3.5.0     utils_3.5.0     yaml_2.2.0     
```

**Comment by yihui** [comment]
I'm still unable to reproduce it. I said in my previous reply:

> I was unable reproduce this issue on either Windows or macOS with _the latest versions of R and all packages_. 

Apparently your R version is old, and your **knitr** is also old. Could you make sure [everything is up-to-date](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) first?

Then with the above Rmd example, please run

```r
unlink('test.R')
knitr::purl('test.rmd', documentation = 0L, encoding = 'UTF-8')
```

and send me the output file `test.R` (compress it to zip and upload here). Thanks!

**Comment by DavorJ** [comment]
Seems to be fixed.

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Locale:
  LC_COLLATE=Dutch_Belgium.1252  LC_CTYPE=Dutch_Belgium.1252    LC_MONETARY=Dutch_Belgium.1252 LC_NUMERIC=C                  
  LC_TIME=Dutch_Belgium.1252    

Package version:
  evaluate_0.13   glue_1.3.0      graphics_3.5.2  grDevices_3.5.2 highr_0.7       knitr_1.21      magrittr_1.5    markdown_0.9    methods_3.5.2  
  mime_0.6        stats_3.5.2     stringi_1.3.1   stringr_1.4.0   tools_3.5.2     utils_3.5.2     xfun_0.5        yaml_2.2.0  
```

Issue can be closed.

**Comment by yihui** [comment]
Excellent. Thank you!
