### ISSUE TITLE
Feature Request: Saving .Rnw file when using knit()

### ISSUE THREAD

**Issue by hannes101** [yihui/knitr#1511]
I often run into the issue that I forget to save the document before I issue the knit command. Would it be possible to add something into knit() that the compiled document is saved beforehand?
I am using RStudio to write the files and just issue the knit() command at the command line interface of RStudio.

**Comment by yihui** [comment]
This is an RStudio IDE issue, so please file to https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by hannes101** [comment]
Done, thanks for the quick response.
https://github.com/rstudio/rstudio/issues/2227
