### ISSUE TITLE
RMarkdown Notebooks and Knitr Cache

### ISSUE THREAD

**Issue by nviets** [yihui/knitr#1512]
Is there a way to make RMarkdown notebooks refresh knitr cache when runing code chunks?  I'd like to be able to retain the code chunk output within an html_notebook and merge it into an html_document using the child argument to set the cache path.

Thank you!

**Comment by yihui** [comment]
Sorry, but I don't quite understand this issue. What do you mean by "refresh knitr cache"? You can delete the `*_cache` directory if you want to invalidate the cache.

I don't understand how you can merge html_notebook and html_document, either.

**Comment by nviets** [comment]
Hi yihui, I was trying to merge html_notebook cache from RStudio's .Rproj.user directory with RMarkdown cache.  Jmcphers said it isn't possible `[here](https://github.com/rstudio/rstudio/issues/2213)`.  You can close this issue unless you know of a way.
