### ISSUE TITLE
Use styler instead of formatR?

### ISSUE THREAD

**Issue by krlmlr** [yihui/knitr#1516]
We're about to submit an update for *styler* to CRAN, this would be a good point to use *styler* in addition to/instead of *formatR* for styling code chunks. What's the best way to proceed, would you like to review a PR?

CC @lorenzwalthert.

**Comment by yihui** [comment]
Yes, PR please:
https://github.com/yihui/knitr/blob/1e9a4d51c53c764bb3b8d288a7535a8bb79131f5/R/block.R#L148-L154

A chunk option like `tidy.method = 'styler'` should be good (defaults to `formatR`).
