### ISSUE TITLE
Caching and knitr::knitr_exit()

### ISSUE THREAD

**Issue by nickp60** [yihui/knitr#1522]
Hi, this is a super small issue, but  I thought I'd mention it anyway.  When running a long document, I use `knit_exit()` to run parts of it at a time.  Because some of the calculations take a long time, I use cache everything.

The issue seems to be how the `knit_exit()` command is cached.  The first time knitting the document, the it stops in the proper spot.  However if I knit again without editing the chunk where I call `knit_exit()`, it moves on to the rest of the document.

This should be able to be reproduced by running the following .Rmd twice (fixing the backticks closing the chunks, which had to be changed to render here), and comparing the output:

```r
---
title: "Early Exit Caching MWE"
---

```{r include=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE)
``
Here is some text

```{r chunk1}
plot(x=1:10)
knitr::knit_exit()
``

a bit more text that I haven't finished writing, and don't want knitted yet

```{r chunk2}
# I am trying to debug this error, and dont want to knit it yet
plot(x=unassigned_variable)
``
```

The easy way to solve this is just to put the exit call in a chunk by itself, with caching disabled for that chunk. 

This may well be the desired behaviour, but I just thought I'd mention it!

**Comment by yihui** [comment]
Yes, it is an expected behavior, and your solution is correct. Thanks!
