### ISSUE TITLE
needs to import xml2 > 1.2.0 for imgur_upload 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1523]
I believe the #1495 was due to a breaking change in xml2 1.2.0 in `as_list` that now return the root node. Fix in #1496 is a way to deal with that. 
However knitr now needs xml2 >= 1.2.0 for `imgur_upload` to work properly. 

I could to a PR with that addition Un description or test in `imgur_upload` for which version of xml2 and do the right thing accordingly. What do you think?

**Comment by yihui** [comment]
Yes, please both update the DESCRIPTION and test `packageVersion('xml2) >= '1.2.0'` in `imgur_upload()` in your PR. Thanks!
