### ISSUE TITLE
[feature request] interactive password entry before kniting an report

### ISSUE THREAD

**Issue by kkmann** [yihui/knitr#1529]
Hey,

I just struggle with accessing a password protected server connection from a Rmarkdown report. I would rather not have my password stored as a parameter in the YAML header but there does not seem to be a way of interactively specifying a parameter, is there? Any ideas of how to get functionality for handling passwords in knitr? I'd be willing to dig into this, but would need some directions.

Best,

Kevin

**Comment by cderv** [comment]
Hi, 

In Rmardown, you have the hability to use a small user interface to provide parameter. It is explained in this [rmarkdown website article](https://rmarkdown.rstudio.com/developer_parameterized_reports.html#parameter_user_interfaces). 

Those are not interactive solution but You also have some advices to use password for dB access for example, that works for rmarkdown document, in the [db.rstudio.com website](http://db.rstudio.com/best-practices/managing-credentials/). Among other, environment variable, the keyring 📦 or config 📦 can help. 

You could also use any interactive solution you want (like `rstudioapi::askForPassword`) in a script and render you document using the `rmarkdown::render` function and the `params` arg. 

I hope one of these can help you with your case. Did you try already any of these solutions? 

By the way, I think your question is more suited toward a QA community than an issue board. Posting it on Stackoverflow or community.rstudio.com will allow more users to see it and so more users to be able to help you and give advice. If this is really a bug or a new feature idea, you could post it in the right issue board then. 
What I am trying to say is that it is best practice in the community to keep issue board for bugs or new features proposal for the developer,  and ask any question beforehand on another site, that for sure the developer will follow too but with a broader audience.
