### ISSUE TITLE
Chunk cache is not invalidated despide upstream object change and object name is in __globals

### ISSUE THREAD

**Issue by mlell** [yihui/knitr#1530]
I have a data analysis pipeline written using knitr which is dependent on RDS output of a prior script. 

I use the cache feature to avoid time consuming modelling steps if possible. As I use git which changes the modification times of files, I cannot decide whether the cache should be dropped [based on the input file modification time](https://github.com/yihui/knitr/issues/238#issuecomment-24315062). Hence, I disable the cache for the chunk which reads in the RDS file. 

I would expect that without the chunk option `cache = TRUE`, the RDS file would be read in on every knitr run, and the following chunks which depend on the resulting object can use the hash of the object to determine if their cache is still valid. 

However, I notice that this does not happen. 

The problem boils down to the following example:

**Step 1:** Generate two Rmd files, called `knitr1.Rmd` and `knitr2.Rmd`, respectively, which looks like this: 

* knitr1.Rmd:

      ```{r make}
      a <- 1
      ```
      ```{r store}
      saveRDS(a, "a.rds")
      ```

* knitr2.Rmd

      ```{r setup, include=FALSE}
      knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, cache.path = 'knitr2.cache/')
      ```
      ```{r read, cache = FALSE}
      ax <- readRDS("a.rds")
      ```
      ```{r print}
      ax
      ```
 
**Step 2**: Run `knitr::knit("knitr1.Rmd"); knitr::knit("knitr2.Rmd")`

Result (`knitr2.md`): 

    ```r
    ax <- readRDS("a.rds")
    ```
    
    
    ```r
    ax
    ```
    
    ```
    ## [1] 1
    ```

**Step 3:** Change the line `a <- 1` in `knitr1.Rmd` to another value

**Step 4:** Recompile like above.

Result: The last value in `knitr1.md` is still 1, despite the value being changed in `knitr1.rmd` and `readRDS("a.rds")` returning the new, updated value.

Tested on R 3.4.3 with knitr [03b6e40](https://github.com/yihui/knitr/commit/03b6e40d0969cdee4c01205bd31b096e85797a81)

**Comment by mlell** [comment]
It turns out that adding `cache.extra = ax` to the chunk option of the last chunk in `knitr2.Rmd` solves the problem. But `ax` is already listed in the `__globals` file, so why is the change of the object not recognized without?

**Comment by cderv** [comment]
Hi @mlell, 

Thanks for being patient with us regarding our answer. 

**knitr** cache is not behaving as you expect I believe. You can learn more on the cache mechanism in the [R Markdown Cookbook chapter](https://bookdown.org/yihui/rmarkdown-cookbook/cache.html) and also about cache invalidation in this post: https://yihui.org/en/2018/06/cache-invalidation/

Short summary: Cache will be invalidated when the chunk is changing, either the option and/or the content. It will not be invalidated based on the value of the content. 
This is why when you update `ax`, the cache won't change. The cache chunked is still the same, code and options. Even if `ax` is identified as globals, it won't means that a change in `ax` value will invalidate. It means that as you used `autodep`, dependencies between cached chunks will be auto guessed (not always reliable) to that when one of them invalidates the other also invalidate. 

Here, you are in the example shown in the book: The value of your variable comes from a file, and you can set `cache.extra` to the md5 value of the file for example. It is what you are doing by passing `ax` to `cache.extra` but it is more design to pass the file that changed. 

````markdown
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache.path = 'knitr2.cache/')
```

```{r read}
ax <- readRDS("a.rds")
```

```{r print, cache = TRUE, cache.extra = tools::md5sum("a.rds")}
ax
```
````

If you want to control yourself the invalidation of the cache in a more direct way, you can have a look at the new cache helper based on Rds files: 
https://bookdown.org/yihui/rmarkdown-cookbook/cache-rds.html

I'll close this but feel free to read out on https://community.rstudio.com, or here if you have further question.
