### ISSUE TITLE
`fig.height` and `fig.width` ignored in Rnw

### ISSUE THREAD

**Issue by eliocamp** [yihui/knitr#1533]
I'm writing a report in an .Rwn document and it seems that knitr ignores the `fig.height` and `fid.width` arguments. In this example I get a big figure and the saved pdf is 7'' by 7''. 

```
\documentclass{article}
\begin{document}
\SweaveOpts{concordance=TRUE}

Knitr can automatically generate a figure environment if fig.cap is specified.

<<test, fig.height=1, fig.width = 3, fig.cap = "sdfds", fig = TRUE>>=
plot(runif(4))
@

\end{document}
```

![image](https://user-images.githubusercontent.com/8617595/38474193-e6f3c51e-3b71-11e8-8a57-3a77b1327d59.png)

Also ignored is `fig.cap`, and I get an error in [this](https://github.com/yihui/knitr-examples/blob/master/019-fig-caption.Rnw) example:

```
Error in SweaveParseOptions(chunkopts, drobj$options, driver$checkopts) : 
  parse error or empty option in
test, fig.cap=paste('$2 \\times 2$ is', 2*2), fig.height=2.5
Calls: <Anonymous> -> SweaveParseOptions
Execution halted
 ```

**Comment by yihui** [comment]
http://stackoverflow.com/q/27592837/559676
