### ISSUE TITLE
cannot define an engine.path for dot engine

### ISSUE THREAD

**Issue by billy34** [yihui/knitr#1534]
It seems that defining an engine path for dot engine does not work as expected. In fact the value is not used at all.

Looking into the code I think I found the origin of the problem located in the `eng_dot` function of the `engines.r` file and especially in the following lines:

> cmd = sprintf(command_string, shQuote(**options$engine %n% options$engine.path**),
 >               shQuote(f), ext <- options$fig.ext %n% dev2ext(options$dev),
>shQuote(paste0(fig <- fig_path(), '.', ext)))

As `options$engine` is always defined, `options$engine.path` has no chance to be used!

One way to correct code is simply swapping `options$engine` and `options$engine.path` or use the function `get_engine_path(options$engine.path,options$engine)` you use for other engines.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
