### ISSUE TITLE
htmlwidgets should have a bottom margin, similar to code or image spacing

### ISSUE THREAD

**Issue by schloerke** [yihui/knitr#1543]
Similar to images or other code chunks, I believe htmlwidgets should have the small 10px spacer between the bottom of the widget and the next section.  Currently it is flush with the next section of the output.

````
---
output: html_document
---
```r
library(leaflet)
leaflet() %>% addTiles()
leaflet() %>% addTiles()
1 + 1
```
````

![screen shot 2018-05-10 at 3 00 33 pm](https://user-images.githubusercontent.com/93231/39888539-1421db02-5463-11e8-9550-47bd2b8a43a9.png)

I know I could do a workaround by adding a `<p></p>` tag after each widget, but it seems like knitr should do this.

Thank you!

**Comment by yihui** [comment]
This can be easily achieved by CSS, e.g., https://github.com/rstudio/DT/commit/89058487; knitr is agnostic of particular styles.

**Comment by jcheng5** [comment]
@schloerke This really belongs on https://github.com/ramnathv/htmlwidgets I think

**Comment by aoles** [comment]
Thank you all for your comments! I've forwarded this to [rmarkdown](https://github.com/rstudio/rmarkdown/issues/1343) as to me this seems more of an html template issue.
