### ISSUE TITLE
[FR] kable_latex: support placement arguments

### ISSUE THREAD

**Issue by pank** [yihui/knitr#1547]
Hi,

`knitr::kable_latex` does not "support" [float placement specifiers](https://tex.stackexchange.com/a/39019) diretly.
Placement specifiers are useful to gain more fine control about float placement on the page.
It should be easy to add to `knitr::kable_latex`, e.g.
```R
env1 = sprintf("\\begin{%s}%s\n", table.envir, table.argument)
```
where `table.argument` would default to `""`.
Then, a user could specify `kable(..., table.argument="[htp]")`, or more complex
things if not using the default "table" environment. 

This is, IMO, an improvement over the situation at the moment where it
is only possible adjust the default placement of all (`kable`) table,
e.g. `\makeatletter\renewcommand{\fps@table}{htp}\makeatother`.

I can provide a patch if desired.

Thanks,
Rasmus

**Comment by yihui** [comment]
I think I have a `valign` argument in `kable_latex()` that should do what you want, e.g., `kable(..., valign = 'htp')`.

https://github.com/yihui/knitr/blob/dc028f4c9698f84999b53edc5f6f255b29d7e5a2/R/table.R#L218

**Comment by pank** [comment]
I hadn't actually noticed `valign`, but I  still think it is slightly different, but please correct me if I'm wrong.  

`valign` sets the [position argument] (https://en.wikibooks.org/wiki/LaTeX/Tables#The_tabular_environment) of the `tabular` environment, not the `table` (the float).  I *think* `valign` would only be relevant if a table is to be in-lined in a paragraph, or perhaps if two tables are placed next to each other inside the same float. 

Here's an example (see line 4):
```R
R> kable(data.frame(x=1), format="latex", valign="tbh", table.envir="table")
\begin{table}

\begin{tabular}[tbh]{r}
\hline
x\\
\hline
1\\
\hline
\end{tabular}
\end{table}
```
The desired output would be:
```
\begin{table}[tbh]

\begin{tabular}{r}
\hline
x\\
\hline
1\\
\hline
\end{tabular}
\end{table}
```

Thanks,
Rasmus

**Comment by yihui** [comment]
Duplicate of #1487

(and has been fixed by @haozhu233 in #1519)

**Comment by pank** [comment]
So it seems.  Thanks!  And sorry for not checking master properly beforehand.

**Comment by yihui** [comment]
Sorry I just made a change and you'll have to use `position = "tbh"` instead of `valign`. More info at https://github.com/yihui/knitr/issues/1487#issuecomment-530064551.
