### ISSUE TITLE
Rmd render choke when options(knitr.kable.NA = '-')

### ISSUE THREAD

**Issue by ray1919** [yihui/knitr#1551]
I use kable to display table in rmarkdown doc.
I want to hide NAs in table, so I add
```
options(knitr.kable.NA = '')
```
to hide NAs, and it works fine.

However, when I set
```
options(knitr.kable.NA = '-')
```
The render process will consume all memery (over 30G) and nerver stop
The terminal showed it was choked in the last step like
```
/usr/bin/pandoc +RTS -K512m -RTS qcreport.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /opt/data/qcreport.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/zhaorui/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpWJQzDv/rmarkdown-strfc52a65e1b8.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
```

I change '-' to '.', It works again
```
options(knitr.kable.NA = '.')
```
so I wonder what is wrong with it.

The code is rather long, and with a lot of inputs, I could not just copy & paste it here.

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? I cannot reproduce it.

````
---
title: "kable()"
output: html_document
---

```{r}
options(knitr.kable.NA = '-')
x = iris
x[1:5, 2:3] = NA
knitr::kable(x)
```
````

**Comment by ray1919** [comment]
I could render the Rmd using Rstudio IDE, but have this problem using following command  
```
Rscript -e "require( 'rmarkdown' ); rmarkdown::render('report.Rmd')"
```
However, running you minimal example is just fine.

So, I am confused in which code to provide.

Now I use dot instead of dash to fill blank cells.

**Comment by yihui** [comment]
You could replace your real data values with random values, and try to make a reprex. Without a reprex, it is hard to know what the problem is or fix it.
