### ISSUE TITLE
First plot not setting theme

### ISSUE THREAD

**Issue by mathuin** [yihui/knitr#1555]
I have started using cowplot with knitr, and I have observed some divergent behavior between running in R itself and running in knitr.  I honestly don't know if the issue is with cowplot or with knitr, but I thought it best to start here.

```{rnw}
\documentclass{article}
\begin{document}
    <<mwe>>=
    library(cowplot)
    ggplot(iris, aes(x = Species, y = Sepal.Length)) +
        geom_point() +
        theme_set(theme_gray())
    ggplot(iris, aes(x = Species, y = Sepal.Length)) +
        geom_boxplot() +
        theme_set(theme_gray())
    @
\end{document}
```

I use the command `Rscript -e "library(knitr); knit('$<')"` to process this file.  It generates a short LaTeX source file and two PDFs, one for each plot.  The PDF for the first plot does not have `theme_gray()` applied properly, but the PDF for the second plot does.  When I run the `ggplot()` lines by hand in R, both plots have the theme properly applied.

**Comment by cderv** [comment]
Hi @mathuin, 

thank you for you patience to have an answer. 

I can't reproduce this currently using **ggplot2** and **knitr**, so I'll close. 

BTW, I think `theme_set()` must be used outside of of a **ggplot2** pipe. See `?theme_set()`. With **ggplot2** you can apply theme as is in the pipe on a per-plot basis
````r
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
        geom_point() +
        theme_gray()
````

or change the default theme used using `theme_set`

```r
theme_set(theme_gray())
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
    geom_point()
```
