### ISSUE TITLE
knit_params mangles UTF-8 text not representable in current locale

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#1557]
Small reprex:

```r
Sys.setlocale(locale = "English")
contents <- "---\nparams:\n  test: '\u4f60\u597d'\n---\n"  # 你好
Encoding(contents) <- "UTF-8"
print(contents)
knitr::knit_params(contents)
```

The generated parameter for `test` is replaced with its UTF-8 code point:

```r
> knitr::knit_params(contents)
$`test`
$`value`
[1] "<U+4F60><U+597D>"

$name
[1] "test"

attr(,"class")
[1] "knit_param"
```

From what I can see, this occurs because `split_lines()` attempts to (unintentionally) re-encode text into the active locale. Some options given the implementation here:

https://github.com/yihui/knitr/blob/0a9a502c809e0d38a987ef8934148c1304a939ce/R/utils.R#L605-L611

1. Use `textConnection(x, encoding = "bytes")` and then re-mark the encoding after reading from the connection,

2. Use `strsplit()`, but handle the special case where `x` is an empty string.

@yihui let me know if you have a preference here and I can try to put together a PR.

**Comment by yihui** [comment]
I can do 2 by myself since it appears to be simple enough. I think I used this approach originally, but I don't remember why I reverted it and used `textConnection()` instead. Thanks!

**Comment by yihui** [comment]
Should be fixed now. Could you test again with `devtools::install_github('yihui/knitr')`? Thanks!

**Comment by kevinushey** [comment]
Looks good -- thanks for the fix!

```
> Sys.setlocale(locale = "English")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> contents <- "---\nparams:\n  test: '\u4f60\u597d'\n---\n"  # 你好
> Encoding(contents) <- "UTF-8"
> print(contents)
[1] "---\nparams:\n  test: '你好'\n---\n"
> knitr::knit_params(contents)
$`test`
$`value`
[1] "你好"

$name
[1] "test"

attr(,"class")
[1] "knit_param"
```
