### ISSUE TITLE
kable linesep: Why is `linesep` changed even when I write a custom definition?

### ISSUE THREAD

**Issue by tinu-schneider** [yihui/knitr#1558]
I try to add a `\midrule` before the sum in a table that is printed with `kable` (`pdf_document`).
This is what I would like to get: 
![target](https://user-images.githubusercontent.com/854515/41424476-70c7673a-6ffe-11e8-8552-d255f8ee0165.PNG)

Here is a full `.Rmd` with the code.
[kable_linesep.zip](https://github.com/yihui/knitr/files/2103193/kable_linesep.zip)

If I define `linesep` like this, the `\midrule` won't print.
```{r}
    knitr::kable(dat, 
                 booktabs = TRUE,
                 format   = "latex",
                 linesep  = c("", "", "\\midrule") )
```
![a](https://user-images.githubusercontent.com/854515/41424665-039c2fbe-6fff-11e8-8448-db1cc6541734.PNG)

But if I define it like this, then the `\midrule` is repeated:
```{r}
linesep  = c("\\midrule", "", "")
```
![c](https://user-images.githubusercontent.com/854515/41424760-45b5268a-6fff-11e8-98dd-a4595e609b9c.PNG)

In the code for the function `kable_latex` in the file `table.R` on line 246 we find the following redefinition of `linesep`

```{r}
kable_latex = function(...) {
    # ...
    linesep = if (nrow(x) > 1) {
        c(rep(linesep, length.out = nrow(x) - 2), linesep[[1L]], '')
    }
}
``` 
My question is:
Why is `linesep` changed even when I write a custom definition?

I guess, there must be a reason, but I don't really understand it at the moment. 

Thanks for clarification and many many thanks for your amazing work!

**Comment by yihui** [comment]
Honestly I don't remember the reason now, but it seems to be a bug to me, so I'll fix it soon.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by tinu-schneider** [comment]
Thank you :)
