### ISSUE TITLE
Set default code folding on per chunk basis

### ISSUE THREAD

**Issue by Aariq** [yihui/knitr#1561]
There is currently a YAML way of setting code folding in a html or notebook output, but there is no way (to my knowledge) of setting the default for each chunk.  For example maybe I want all my code chunks to be shown in the html output, but some of them to be folded by default.  Is there a way this could be set with chunk options?

**Comment by yihui** [comment]
No. Sorry.

**Comment by cderv** [comment]
> For example maybe I want all my code chunks to be shown in the html output, but some of them to be folded by default. Is there a way this could be set with chunk options?

I believe this feature has been now added in to R Markdown for HTML document

See https://github.com/rstudio/rmarkdown/issues/664 and related PR https://github.com/rstudio/rmarkdown/pull/1602, https://github.com/rstudio/rmarkdown/pull/1798

* hide all except some: 
````markdown
---
output:
  html_document:
    code_folding: hide
---

```{r class.source = 'fold-show'}
1
```

```{r class.source = 'fold-show'}
2
```

```{r}
# This source is hidden
```
````

* show all except some: 
````markdown
---
output:
  html_document:
    code_folding: show
---

```{r}
1
```

```{r, class.source='fold-hide'}
2
```
````

You can search for `folding` in the NEWS file also: https://rmarkdown.rstudio.com/docs/news/index.html

**Comment by yihui** [comment]
Also mentioned in the R Markdown Cookbook: https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html
