### ISSUE TITLE
Floating TOC in HTML docs doesn't highlight scrollable sections

### ISSUE THREAD

**Issue by david-cortes** [yihui/knitr#1562]
When creating an HTML Rmarkdown document with a floating TOC, and some of the output from the cells in the middle of the sections are scrollable tables, when passing through those sections (when scrolling), the TOC no longer updates itself to reflect that one is browsing those sections (that contain scrollable tables).

**Steps to reproduce:**
* Create an Rmarkdown document with a float TOC, e.g.
``` yaml
---
title: "rmd doc"
output:
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: no
---
```
* Create some code chunk that would output a scrollable HTML table, e.g.
``` R
library(knitr)
library(kableExtra)
df <- data.frame(col1 = c(1,2,3), col2= c('a', 'b', 'c'))
kable(df) %>% kableExtra::kable_styling() %>% scroll_box(height = "500px")
```
* Put that code under some header in the middle of the document, with more headers above.
* Scroll through the document and watch the TOC at the side.

**Expected beahvior:**
* TOC should highlight the section that the user is browsing.

**Actual behavior:**
* When browsing the scrollable sections, it keeps on highlighting whatever was being highlighted before.

**Reproducible:** always, with different web browsers.

**Setup:** R version 3.5.0, knitr version 1.20.

**Comment by david-cortes** [comment]
Sure, here's a full example:
```` R
---
title: "example"
author: "no one"
date: "6/22/2018"
output:
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: no
---

# header1

```{r, echo=FALSE, results='asis'}
cat("<h2> header 2 here </h2>")
```

# header 2
```{r, echo=FALSE}
library(knitr)
library(kableExtra)
df <- data.frame(col1 = rnorm(100), col2 = rnorm(100))
txt <- kable(df, caption = "title") %>% kableExtra::kable_styling() %>% scroll_box(height = "500px")
txt <- gsub("<caption>(.*)</caption>",
            "<h2>\\1</h2>", txt)
txt
```

```{r, echo=FALSE}
library(knitr)
library(kableExtra)
df <- data.frame(col1 = rnorm(100), col2 = rnorm(100))
txt <- kable(df, caption = "title2") %>% kableExtra::kable_styling() %>% scroll_box(height = "500px")
txt <- gsub("<caption>(.*)</caption>",
            "<h2>\\1</h2>", txt)
txt
```
````

As you scroll down through it, the TOC at the side won't highlight the 'title' and 'title2' sections. Although, if you change other things on the code, they will work correctly (e.g. after adding some sections with headers and text).

**Comment by yihui** [comment]
Okay. Thanks!

I think the problem came from the fact that you limited the height of the tables via `scroll_box(height = "500px")`. Without this constraint, TOC highlighting works fine. Anyway, this is definitely an rmarkdown issue instead of knitr: https://github.com/rstudio/rmarkdown/issues (I guess it probably won't be investigated or fixed soon, though. It feels like a rather tricky issue.)

**Comment by yihui** [comment]
For the record, this issue was moved to https://github.com/rstudio/rmarkdown/issues/1383
