### ISSUE TITLE
`format_sci`: `\cdot` instead of `\times`

### ISSUE THREAD

**Issue by wuffi** [yihui/knitr#1563]
The function `format_sci_one` in `R/utils.R` uses `\times` as a sign for multiplication:

    sci_notation('%s%s10^{%s}', b, '\\times ', lx)    # line 199

Is there a reason, why the `\times` ("×")sign is preferred over the (as far as I know more commonly used) dot ("·", typeset by LaTeX's `\cdot` macro)?

If not, it would be great, if the call to `sci_notation` could be changed to

    sci_notation('%s%s10^{%s}', b, '\\cdot ', lx)    # line 199 changed

Maybe adding an option would be helpful, so that users could choose between these two different notations.

**Comment by trentks** [comment]
I would second this, I'm format agnostic. However I've run across an issue where changing font to a non-standard TeX font (century gothic) that doesn't fully support math symbols, causes anything from knitR which has scientific notation to revert to computer modern.

The `siunitx` LaTeX package supports changing your exponent product from its `\times` default to `cdot using something like this:
```tex
\sisetup{...,
exponent-product = \cdot,
...}

It would be very good to be able to configure knitR similarly.
```

**Comment by yihui** [comment]
Now you can set

```r
options(knitr.inline.times = '\\cdot ')
```

Thanks!

**Comment by wuffi** [comment]
Thank you su much!
This is great!
