### ISSUE TITLE
wrap_rmd breaks inline code

### ISSUE THREAD

**Issue by mattantaliss** [yihui/knitr#1566]
I am working on a paper with R Markdown (processing to PDF with pdflatex). I am doing the analyses in a separate R script and then including results in the paper with a reference to the variable name from my analyses. In this case, `wrap_rmd` breaks inline code.

For example, "Analysis.R" is a script with the following code: `an.example.variable.name <- 1`. "Paper.Rmd" is as follows:
````r
---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("Analysis.R")
```

## Introduction

This is an example paragraph illustrating how knitr::wrap_rmd will break `r an.example.variable.name` because it is inline code.
````

If I knit that file as is, all is well. If I do `knitr::wrap_rmd("Paper.Rmd")` and knit the result, then the inline code includes a line break and the output is incorrect.

If I have the analysis code within the markdown file, however, it seems this is not an issue. In my current case, though, it is a lot cleaner to have all of the analyses in a separate script and bring in results as needed in the markdown file, so I'm hoping to avoid the solution, "Just put all of your analysis code in the markdown file."

**Comment by yihui** [comment]
You can search for `` `r# `` in the release notes: https://github.com/yihui/knitr/releases (knitr 1.15).

The answer is to use  `r#an.example.variable.name` instead of `r an.example.variable.name`.
