### ISSUE TITLE
kable as s3 method

### ISSUE THREAD

**Issue by malcolmbarrett** [yihui/knitr#1568]
`kable()` has become a bit of a lingua franca for markdown tables in R. I believe I have seen you mention your desire to keep it a simple function (which has probably contributed to its popularity), but what do you think about converting it to an S3 method, with the current implementation as `kable.default`? As far as I can tell, it would be an easy, non-breaking change and would allow a way to extend it without sacrificing its simplicity. If you're interested, I wouldn't mind submitting a PR.

Thanks!
Malcolm

**Comment by yihui** [comment]
Instead of making `kable()` a generic function, `knit_print()` may be a better candidate. See https://github.com/yihui/printr for some examples.

**Comment by malcolmbarrett** [comment]
Hm, admittedly `knit_print()` is probably the behavior many, if not most, people would want, since it prints right to markdown, but I had in mind something that would allow behavior similar to a `data.frame` in knitr, e.g. print the R object as-is unless explicitly calling `kable()`. I suppose a workaround is to define an `as.data.frame` method for the object, since `kable()` calls `as.data.frame()`, but I'm not sure how well that would work in practice.
