### ISSUE TITLE
cache to environment ?

### ISSUE THREAD

**Issue by moodymudskipper** [yihui/knitr#1570]
My disk access is very slow, I believe it's a common issue with Rstudio on network drives.

I cannot thus fully enjoy the benefits of the `cache=TRUE` option (loading is ok, but writing for the first time take ages because each 1kb file takes a long time to save).

This might not affect so many people but it'd be awesome to be able to cache to a local environment instead of caching to the hard drive. Maybe it'd actually be faster for everyone ?

**Comment by moodymudskipper** [comment]
And what about using  `rmarkdown::render` in R studio ? That's what I use instead of the knit button, so I can keep variables in the global environment, and sometimes comment what has already run. 

The command line option would be useful I think, but not being able to debug with RStudio makes it less interesting.

**Comment by yihui** [comment]
Yea, by command-line, I meant R function calls like `rmarkdown::render()` or `knitr::knit()`.

I'm not sure how many variables you want to cache in memory. If not many, you can use a simple solution like

```r
if (!exists('foo')) foo = compute_it()
foo
```
