### ISSUE TITLE
knitr creates clipped ggplot2 image when using coord_fixed(ratio = 1)

### ISSUE THREAD

**Issue by chrisothal** [yihui/knitr#1573]
I am noticing clipped images when `knitr` produces a PDF image from a `ggplot2` object containing `coord_fixed(ratio = 1)`. I'm plotting two sets of data: 1) 7 points of geom_raster() from x = 0:6 and y = 0, and 2) 14 points of geom_raster() from x = 0:6 and y = -1:0 (one row of seven tiles vs two rows of seven tiles). I also have a label of text above the tiles and am noticing the text gets cut off only in the first dataset, but not when the data spans more than one row. When I call `rmarkdown::render("mwe.Rmd", clean = F)`, I can see the PDF images produced by `knitr` are slightly clipped. Below I've included a MWE and if you analyze the outputted PDF and plot images, you will see that the plot `g_fixed_1` or PDF file `mwe_files/figure-latex/unnamed-chunk-1-2.pdf` compared to `g_fixed_2` or PDF file `mwe_files/figure-latex/unnamed-chunk-1-4.pdf`. Does anyone know why the top bit of the plots are clipped?

### mwe.Rmd

    ---
    title: "mwe"
    output: pdf_document
    ---
    
    ```{r}
    library(ggplot2)
    
    data <- list(
      x1 = 0:6,
      y1 = 0,
      x2 = rep(0:6, 2),
      y2 = rep(c(0, 1), each = 7) * -1,
      labels = paste("Label", 1:7)
    )
    
    g <- ggplot() + geom_text(aes(0:6, 0.75), label = data$labels)
    
    g_unfixed_1 <- g + geom_raster(aes(data$x1, data$y1))
    g_fixed_1 <- g_unfixed_1 + coord_fixed(ratio = 1)
    g_unfixed_2 <- g + geom_raster(aes(data$x2, data$y2))
    g_fixed_2 <- g_unfixed_2 + coord_fixed(ratio = 1)
    
    g_unfixed_1
    g_fixed_1
    g_unfixed_2
    g_fixed_2
    ```

**Comment by yihui** [comment]
Please see the argument `fig_crop` in the documentation `?rmarkdown::html_document` (you may want to set it to `false` in YAML) and check `Sys.which('pdfcrop')`.
