### ISSUE TITLE
Math with underscores in latex's flalign

### ISSUE THREAD

**Issue by benkeser** [yihui/knitr#1576]
I am writing in Rmd and attempting to include chunks of math in an flalign environment. It seems that including an underscore in the math throws off the rendering of the .tex. This does not occur in the align environment. 

Minimal working example attached includes Rmd and rendered tex (which includes output of `session_info('knitr')`and `sessionInfo()`) 

Thanks. 

[minwe.zip](https://github.com/yihui/knitr/files/2206464/minwe.zip)

**Comment by cderv** [comment]
I believe this as now been fixed somewhere, as it works with recent version of everything including Pandoc. 

I got the expected result when using 
````markdown
---
header-includes: 
     - \usepackage{amsmath}
     - \usetheme{Berlin}
output: 
  beamer_presentation: 
    keep_tex: true
    slide_level: 1
---


\begin{flalign}
&\widehat{E}[Y \mid A] &
\end{flalign}

\begin{align}
&\widehat{E}[Y \mid A_1] &
\end{align}

\begin{flalign}
&\widehat{E}[Y \mid A_1] &
\end{flalign}

````

![image](https://user-images.githubusercontent.com/6791940/105998427-ea829580-60ac-11eb-8aee-b398abb6e7f4.png)


I'll close this. Please reopen if I missed something.

BTW, when you want to use LaTeX code only in a Rmd document processed by Pandoc, you can insure that it will be considered as Raw LaTeX by using fenced attributes.
https://bookdown.org/yihui/rmarkdown-cookbook/raw-latex.html
