### ISSUE TITLE
`fig.env` ignored even with `fig.cap`

### ISSUE THREAD

**Issue by stefanocoretta** [yihui/knitr#1578]
I tried using `fig.env="figure*"` as a chunk option along with `fig.cap`, but the resulting code has a standard `figure` environment (I've tried other environments too).

A minimal document that reproduces the problem:

     ---
      title: "Untitled"
      author: "Stefano Coretta"
      date: "25/07/2018"
      output: 
       pdf_document: 
         fig_caption: yes
         keep_tex: yes
     ---
     
     ```{r pressure, fig.cap="Test", fig.env="figure*"}
     plot(pressure)
     ```

My `sessionInfo()`:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] htmltools_0.3.6 tools_3.5.1     yaml_2.1.19     Rcpp_0.12.17   
 [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
[13] digest_0.6.15   evaluate_0.11  
```

**Comment by yihui** [comment]
Could you try to add another chunk option `out.extra=""`?

I think this essentially the same issue as https://github.com/rstudio/rmarkdown/issues/1400.

**Comment by stefanocoretta** [comment]
Yes, that has fixed it. Thanks!
