### ISSUE TITLE
Unwanted backslashes added to square brackets inside HTML by github_document

### ISSUE THREAD

**Issue by jmgirard** [yihui/knitr#1582]
[Tumbleweed Question on StackOverflow](https://stackoverflow.com/questions/51315117/how-to-remove-backslash-from-square-bracket-in-html-table-when-knitting-rmarkdow)
I am trying to add square brackets to an RMarkdown file that outputs to a github_document. However, when these brackets are in an HTML table, they get automatically escaped with backslashes and I can't figure out how to prevent this from happening. Below is an example of my .Rmd code (with various attempts to fix it) and a screenshot of the knit preview. It's relatively easy to remove the backslashes from the generated .md file, but it would be nice to know how to fix this the right way (or if it is an error with knitr or pandoc).
```
---
title: "github"
output: github_document
---

Mean = 0.50, 95% CI: [0.25, 0.75]

<table><tr><td>Mean = 0.50, 95% CI: [0.25, 0.75]</td></tr></table>

<table><tr><td>Mean = 0.50, 95% CI: \[0.25, 0.75\]</td></tr></table>

<table><tr><td>Mean = 0.50, 95% CI: $[0.25, 0.75]$</td></tr></table>

<table><tr><td>Mean = 0.50, 95% CI: [[0.25, 0.75]]</td></tr></table>

<table><tr><td>Mean = 0.50, 95% CI: `[0.25, 0.75]`</td></tr></table>

`<table><tr><td>Mean = 0.50, 95% CI: [0.25, 0.75]</td></tr></table>`

<table><tr><td>Mean = 0.50, 95% CI: &#91;0.25, 0.75&#93;</td></tr></table>
```

![](https://i.stack.imgur.com/8ATTV.png)

Interestingly, there's no issue when using output: html_document:

```
---
title: "html"
output: html_document
---

<table><tr><td>Mean = 0.50, 95% CI: [0.25, 0.75]</td></tr></table>
```
![](https://i.stack.imgur.com/ms0bK.png)

**Comment by yihui** [comment]
Not a **knitr** issue, or an **rmarkdown** issue. That is what Pandoc does. Please ask the question in the Pandoc mailing list or Pandoc repo. Here is the minimal example for your reference:

```
$ echo '[1, 2]' | pandoc -f markdown -t gfm
\[1, 2\]
```

Thanks!
