### ISSUE TITLE
Feature request: Ability to customise table environment from knitr::kable

### ISSUE THREAD

**Issue by ulyngs** [yihui/knitr#1585]
When creating PDFs via LaTeX, R Markdown provides the ability to customise the environment that figures should be put in, e.g. this:

````
```{r, fig.env='figure*'}
plot(pressure)
```
````
creates something like this in the .tex:

```
\begin{figure*}
    \includegraphics{figure-latex/my-plot-1} 
\end{figure*}
```

However, when using knitr::kable to generate tables, the environment is always \table{}, with no ability to customise it without tinkering directly in the .tex file after the fact.

It would be fantastic if either this
````
```{r, fig.env='table*'}
knitr::kable(head(iris),format = "latex")
```
````

or this
````
```{r}
knitr::kable(head(iris), format = "latex", table.env='table*')
```
````

would create something like this:
```
\begin{table*}
    \centering
    \begin{tabular}[t]{rrrr}
        \toprule
        Sepal.Length & Sepal.Width & Petal.Length & Petal.Width\\
        \midrule
        5.1 & 3.5 & 1.4 & 0.2\\
        4.9 & 3.0 & 1.4 & 0.2\\
        4.7 & 3.2 & 1.3 & 0.2\\
        4.6 & 3.1 & 1.5 & 0.2\\
        5.0 & 3.6 & 1.4 & 0.2\\
        \bottomrule
    \end{tabular}
\end{table*}
```

**Comment by yihui** [comment]
Did you actually try `knitr::kable(head(iris), format = "latex", table.env='table*')`? It gives me

```latex
\begin{table*}

\begin{tabular}{r|r|r|r|l}
\hline
Sepal.Length & Sepal.Width & Petal.Length & Petal.Width & Species\\
\hline
5.1 & 3.5 & 1.4 & 0.2 & setosa\\
\hline
4.9 & 3.0 & 1.4 & 0.2 & setosa\\
\hline
4.7 & 3.2 & 1.3 & 0.2 & setosa\\
\hline
4.6 & 3.1 & 1.5 & 0.2 & setosa\\
\hline
5.0 & 3.6 & 1.4 & 0.2 & setosa\\
\hline
5.4 & 3.9 & 1.7 & 0.4 & setosa\\
\hline
\end{tabular}
\end{table*}
```

**Comment by ulyngs** [comment]
Ah, absolutely brilliant!

I couldn't find any documentation mentioning this, and I also stumbled on a stackoverflow thread which suggested that this just [wasn't possible to do with kable](https://stackoverflow.com/questions/50190529/2-column-latex-environment-table-in-kable-kableextra).

Perhaps a mention of the table.env option can be included in the kable documentation?
