### ISSUE TITLE
auto_pdf option not working

### ISSUE THREAD

**Issue by davibicudo** [yihui/knitr#1587]
It seems setting the global auto_pdf option is not working. The resulting pdf is always preferring the pdf file when available and completely ignoring the global option.

Here is a self-contained test:

````
---
title: "knitr.graphics.auto_pdf issue"
output: pdf_document
---

```{r setup, include=FALSE}
options(knitr.graphics.auto_pdf = FALSE)
knitr::opts_chunk$set(fig.pos = 'htbp')
```


```{r, bug-file, echo=FALSE, results='hide'}
v <- sample(5, 1000, replace = T)
pdf(file="bug1.pdf")
hist(v)
dev.off()
png(file="bug1.png")
hist(v)
dev.off()
png(file="bug2.png")
plot(sort(v))
dev.off()
```
```{r, opts, echo=T}
getOption("knitr.graphics.auto_pdf")
```

```{r, bug1-include, echo=T, fig.asp = 0.5, fig.width = 4, fig.align = 'center', fig.cap="Unexpected pdf"}
knitr::include_graphics("./bug1.png", dpi = 200)
```


```{r, bug2-include, echo=T, fig.asp = 0.5, fig.width = 4, fig.align = 'center', fig.cap="Expected png"}
knitr::include_graphics("./bug2.png", dpi = 200)
```
````

**Comment by yihui** [comment]
Since I don't use the filename extension: https://github.com/yihui/knitr/blob/4cbffa103b295d978ca2d5db74c3876763cb3fec/R/hooks-latex.R#L163 LaTeX may prefer .pdf over .png when both are present. There must be LaTeX tricks to reorder the preferences. Then you can use the `includes: in_header` option to apply the trick.

I may use the full filename with the extension, but I don't really remember why I didn't. This line of code should be seven years old now.

**Comment by davibicudo** [comment]
You seem to have changed it here https://github.com/yihui/knitr/commit/eb89efe93263cf22d020cd617f908df63471f8e5#r4907995

Wouldn't it be straightforward to switch the order of \DeclareGraphicsExtensions{.pdf,.png,.jpg} (put pdf at the end perhaps) in the generated tex when auto_pdf is set to FALSE?
Also, it seems by default LaTeX should pick [png](https://tex.stackexchange.com/questions/45498/choosing-whether-to-include-pdf-or-png-in-pdflatex) first anyway. Also from the SE post, perhaps the [grfext](http://mirror.switch.ch/ftp/mirror/tex/macros/latex/contrib/oberdiek/grfext.pdf) package could help solve this.

By the way, it isn't clear to me when the auto_pdf plays a role if this issue is happening, although it seems it [does](https://github.com/yihui/knitr/issues/1456). I just couldn't use the option at all.

**Comment by yihui** [comment]
The commit you pointed out didn't really change it. `x[1]` and `sans_ext(x)` were the same thing (filename without extension).

I added a global option to support the full filename. You can set `options(knitr.include_graphics.ext = TRUE)`. Thanks!

**Comment by davibicudo** [comment]
Perfect, thanks a lot!

After testing I understood that if I use the `options(knitr.include_graphics.ext = TRUE)`, then the `knitr.graphics.auto_pdf` works as expected. That means for a quick check I can compile everything with PNG by setting the auto_pdf to FALSE and finally when I'm ready to publish I can set it to TRUE.

It is though still not clear to me in which cases the auto_pdf is useful without the new option. Would you care to illuminate me?

**Comment by davibicudo** [comment]
A quick question regarding the update. In my case I'm using bookdown and the issue is still there, but I guess once v1.21 is deployed it will be also available for bookdown via devtools? Or am I missing something?
