### ISSUE TITLE
kable: cannot start first column with [ symbol using latex and booktabs

### ISSUE THREAD

**Issue by jonnypenarth** [yihui/knitr#1595]
If the first column of a table commences with a [ symbol, as is common when using interval notation, LaTeX throws an error. The problem only occurs when using the booktabs package.

Here is a minimal example:

````
results <- data.frame(
  Interval = c("[0, 50]", "(50,100]"),
  Count = c(35, 62)
)
kable(results, "latex", booktabs = T)
````
The issue appears to be that the the cell contents is being interpreted by LaTeX as  parameter to the preceding command. The workaround that I have found is to include some non-printing text in front of the [ and to use escape = F.

For example, this alternative example works successfully and produces the desired output:
````
results <- data.frame(
  Interval = c("{}[0, 50]", "(50,100]"),
  Count = c(35, 62)
)
kable(results, "latex", booktabs = T, escape = F)
````
My suggested solution is for kable to replace any [ at the start of a new line with {}[.

**Comment by cderv** [comment]
This is something to do with **booktabs** indeed. 

Based on this [SO Q&A](https://stackoverflow.com/questions/27698314/using-the-booktabs-midrule-and-with-brackets), `{}` are needed after `\toprule` or `\midrule` otherwise the following content would be misinterpreted by those commands. 

Here is the tex generated for the table
```latex
\begin{tabular}{lr}
\toprule
Interval & Count\\
\midrule
[0, 50] & 35\\
(50,100] & 62\\
\bottomrule{}
\end{tabular}
```
That is why your trick is working (adding the `{}` before the cell. 

What `kable` could do is add those curly braces for all commands. 
```diff
diff --git a/R/table.R b/R/table.R
index 0b8c68bb..a6a6c81e 100644
--- a/R/table.R
+++ b/R/table.R
@@ -274,9 +274,9 @@ knit_print.knitr_kable = function(x, ...) {
 kable_latex = function(
   x, booktabs = FALSE, longtable = FALSE, valign = 't', position = '', centering = TRUE,
   vline = getOption('knitr.table.vline', if (booktabs) '' else '|'),
-  toprule = getOption('knitr.table.toprule', if (booktabs) '\\toprule' else '\\hline'),
-  bottomrule = getOption('knitr.table.bottomrule', if (booktabs) '\\bottomrule' else '\\hline'),
-  midrule = getOption('knitr.table.midrule', if (booktabs) '\\midrule' else '\\hline'),
+  toprule = getOption('knitr.table.toprule', if (booktabs) '\\toprule{}' else '\\hline'),
+  bottomrule = getOption('knitr.table.bottomrule', if (booktabs) '\\bottomrule{}' else '\\hline'),
+  midrule = getOption('knitr.table.midrule', if (booktabs) '\\midrule{}' else '\\hline'),
   linesep = if (booktabs) c('', '', '', '', '\\addlinespace') else '\\hline',
   caption = NULL, caption.short = '', table.envir = if (!is.null(caption)) 'table',
   escape = TRUE
```

Making this kind of change will make the document compile.

However, I don't know enough LaTeX to know if it safe to add these in all case. 
@yihui do you think `kable()` could do something ?  

Full document to reproduce the issue:  

````markdown
---
output:
  pdf_document:
    extra_dependencies: booktabs
    keep_tex: true
---

```{r}
library(knitr)
results <- data.frame(
  Interval = c("[0, 50]", "(50,100]"),
  Count = c(35, 62)
)
kable(results, "latex", booktabs = T)
```
````

**Comment by yihui** [comment]
I'm okay with adding the extra `{}` (it's indeed safer to always add them after LaTeX commands). Thanks!

**Comment by cderv** [comment]
Thanks @jonnypenarth for the report and for your patience for a fix !

**Comment by yihui** [comment]
Unfortunately this seems to have broken **kableExtra**: https://github.com/haozhu233/kableExtra/issues/607 I just ran into this error by myself: https://github.com/yihui/tinytex/runs/2383210231

**Comment by bttomio** [comment]
Probably related to https://github.com/ulyngs/oxforddown/issues/19

**Comment by yihui** [comment]
@jonnypenarth I just reverted the fix in **knitr** since it caused other problems. You'd still have to use the workaround to add `{}` before `[0, 50]`. We can considering doing that automatically in **knitr** if you feel it's desirable. Thanks!

**Comment by bttomio** [comment]
> @bttomio Now you may try `remotes::install_github('yihui/knitr')`.

It works perfectly with knitr 1.3.5. Thanks a lot for everything, @yihui!

Solved the problem for both issues: https://github.com/haozhu233/kableExtra/issues/607 and https://github.com/ulyngs/oxforddown/issues/19.

**Comment by jonnypenarth** [comment]
@yihui it would be good to add {} before values like [0,50] if possible.

A very common use case in financial services is for knitr/kable/kableExtra to create stratification tables of assets using the cut() function, which immediately fails to knit when the include.lowest argument is set to T (and it's not immediately obvious why it has failed). Separately adding the {} causes its own complexities, as R no longer recognises the value as an interval so fails to sort it properly and it's no longer possible to escape special LaTeX chaarcters.

I appreciate your work on this. knitr is an unbelieveably powerful package.

**Comment by yihui** [comment]
@jonnypenarth I see. I'll try to add `{}` automatically in `kable()` then. Thanks for the feedback!

**Comment by yihui** [comment]
@jonnypenarth Done now. You may test it by `remotes::install_github('yihui/knitr')`.
