### ISSUE TITLE
How to provide engines from other packages

### ISSUE THREAD

**Issue by benwhalley** [yihui/knitr#1599]
I want to extend the webex package to have a new block type which shows hints when the reader of an knitted Rmarkdown html file presses on a button in the document.  See: https://gupsych.github.io/trdair_workshop/webex.html

So we could write:

```
```{hint button="Press me to get a hint"}

This hint is shown

- Including
- Formatted markedown

When the user presses the button.
    ```
```

I can write an register an engine within an Rmd file which works as desired. using `knitr::knit_engines$set(hint =...)` but I can't make this work when the engine function is provided within another packages (i.e. `webex`)

Is this possible? Can I alter `knit_engines` after knits has loaded? Could there be a mechanism for registering engines from other packages?

**Comment by cderv** [comment]
I think it is possible. See what has been done for `reticulate` 📦 
https://github.com/rstudio/reticulate/blob/master/R/knitr-engine.R

The engine is defined in the package and can be called using 
`knitr::knit_engines$set(python = reticulate::eng_python)`

Knitr default python chunk to reticulate now
https://github.com/yihui/knitr/blob/a3eea51932be742bafa67ea9c776d457dec8670d/R/engine.R#L190-L201
it calls the engine defined in the reticulate package.

Did you already tried what has been done for reticulate ?

**Comment by benwhalley** [comment]
Thanks... that gave me a clue. They actually register the engine with knitr in `zzz.R` with `onLoad()`. In this case I've used this in my package, also in a file `zzz.R` (which seems to be an R convention I didn't previously know about).

```
.onLoad <- function(libname, pkgname){
  knitr::knit_engines$set(hint = eng_hint)
}
```
