### ISSUE TITLE
Errors with captions that have a % symbol

### ISSUE THREAD

**Issue by danawanzer** [yihui/knitr#1604]
When knitting my Rmd file to PDF, I am coming across an issue where the kable won't work nicely with a percentage symbol. I do not know if this is limited to the % symbol or if other symbols have similar issues. 

**Error table:**
````
```{r}
kable(table, 
      caption = "Differences in Authenticity Across Items (%)", 
      booktabs = TRUE) %>%
  kable_styling(full_width = FALSE, 
                position = "center", 
                latex_options = "hold_position")
```
````
This produces the following output when knitting to PDF:

![screenshot 2018-09-14 14 42 13](https://user-images.githubusercontent.com/23221642/45576620-c18b3e00-b82c-11e8-9a78-255fa79bb05e.png)

However, removing the % eliminates the issue:
````
```{r}
kable(table, 
      caption = "Differences in Authenticity Across Items (in percentage)", 
      booktabs = TRUE) %>%
  kable_styling(full_width = FALSE, 
                position = "center", 
                latex_options = "hold_position")
```
````
![screenshot 2018-09-14 14 45 49](https://user-images.githubusercontent.com/23221642/45576657-eed7ec00-b82c-11e8-8226-81a57d79e8e9.png)

**Comment by DanielReedOcean** [comment]
If you set `escape = TRUE` and use `\\%`, like below, it should work fine. I don't have access to your example data, so here I use `mtcars`.

```{r echo = FALSE, message = FALSE}
library(dplyr)
library(knitr)
library(kableExtra)

kable(mtcars[1:3, 1:3], 
      caption = "Differences in Authenticity Across Items (\\%)", 
      booktabs = TRUE,
      escape = TRUE) %>%
  kable_styling(full_width = FALSE, 
                position = "center", 
                latex_options = "hold_position")
```

![capture](https://user-images.githubusercontent.com/11167566/53031058-706a2080-3442-11e9-9b52-a8164c8493a4.PNG)

**Comment by danawanzer** [comment]
Thank you!

Best,
Dana Linnell Wanzer, M.A.
Evaluation, Research, and Statistics Consultant
Evaluation Doctoral Candidate at Claremont Graduate University
danawanzer.com | linkedin.com/in/danawanzer
<https://www.linkedin.com/in/danawanzer> | (760) 835-3604

My working day may not be your working day. Please do not feel obliged to
reply outside of your normal working hours.
