### ISSUE TITLE
Error 403 : faultCode:  403  faultString:  Incorrect username or password.

### ISSUE THREAD

**Issue by aks10000** [yihui/knitr#1608]
I run following chunk of commands and get the error 403: faultString: Incorrect username or passowrd
i chacked my username and password, both are correct---

library(RWordPress)

WordPressURL="https://roswoon.wordpress.com/xmlrpc.php"

options(WordpressLogin = c(user='password'), WordpressURL=WordPressURL)

knitr::knit2wp("houseprice.Rmd", title = "House Price Prediction", shortcode=TRUE,publish=FALSE)

Please help??

**Comment by yihui** [comment]
I don't know what that error message means or how to fix this problem, but for building websites, **blogdown** would be a much much better choice: https://github.com/rstudio/blogdown

WordPress is dead. Long live WordPress.
