### ISSUE TITLE
Rotating image with out.extra in .rmd file is buggy

### ISSUE THREAD

**Issue by philRudd69** [yihui/knitr#1609]
It has been proposed by @Yihui to use
`out.extra="style='transform:rotate(90deg);'"`
for rotating images in .rmd files, when the pictures have been inserted with 
`knit::include_graphics()`.

Unfortunately this does not work as expected. The **rotated pic covers text** in the knitted html-file.
It seems as if the space reserved for the pic is defined by the pic in its original 0deg angle.

This is in reference to a comment of Yihui Xie, who commented the following answer:
https://stackoverflow.com/a/13594070
Here are the comments of interest:
> @Yihui Does this [ out.extra='angle=90deg' ] also work in Rmd documents? – Brandon Bertelsen Nov 29 '12 at 0:24

> @BrandonBertelsen I think it is possible with CSS3, e.g. out.extra="style='transform:rotate(90deg);'", but that relies on the browser support (see, e.g. w3schools.com/cssref/css3_pr_transform.asp) – Yihui Xie Nov 29 '12 at 3:13

I've tried that today, but it yields the unwanted result as discribed above.

My code in .rmd file:

````
# heading
some text ...

```{r faehigkeit, echo=FALSE, out.width = '50%', out.extra="style='transform:rotate(90deg);'"}
include(knitr)
knitr::include_graphics("DSC_0167.jpg")
```
some more text ...
````

Produced output in Mozilla Firefox 62.0 (64-Bit) on Windows 10:
![link to error (screenshot)](http://www.user.tu-berlin.de/m.f.z/error_knitr.PNG)

Cheers

**Comment by philRudd69** [comment]
It seems to be a general HTML/CSS "issue". It's actually not a problem, but intended behaviour.
See: [StackOverflow Answer](https://stackoverflow.com/a/47860039)
There is a workaround shared in this answer. It uses a separate CSS and some wrapper-```<divs>```.

So instead of using `out.extras`, I now do the following:
Content of "file.rmd":
```
<head>
  <link type="text/css" rel="stylesheet" href="style.css">
</head>

some text ...

<!-- https://stackoverflow.com/a/47860039 -->
<!-- https://github.com/rstudio/rmarkdown/issues/326 -->
<!--html_preserve-->
<div class="rotation-wrapper-outer">
  <div class="rotation-wrapper-inner">
    <img class="element-to-rotate" src="DSC_0167.jpg" >
  </div>    
</div>
<!--/html_preserve-->

some more text...
```
Content of "style.css":
```
.rotation-wrapper-outer {
  display: table;
}
.rotation-wrapper-inner {
  padding: 50% 0;
  height: 0;
}
.element-to-rotate {
  display: block;
  transform-origin: top left;
  /* Note: for a CLOCKWISE rotation, use the commented-out
     transform instead of this one. */
  /*transform: rotate(-90deg) translate(-100%);*/
  transform: rotate(90deg) translate(0, -100%); 
  margin-top: -50%;

  /* Not vital, but possibly a good idea if the element you're rotating contains
     text and you want a single long vertical line of text and the pre-rotation
     width of your element is small enough that the text wraps: */
  white-space: nowrap; 
}
```
Note: The rotation does not work with R-Shiny, when you run your app with R's "browser". But if you open the Shiny-App in your favourite internet-browser, the rotation will work as intended.

**Comment by cderv** [comment]
Thanks for sharing all this @philRudd69 ! 

As it is not really an issue with **knitr** but how to customize output using CSS, I'll close this.
