### ISSUE TITLE
Possible bug with eval.after and fig.subcap

### ISSUE THREAD

**Issue by jayrobwilliams** [yihui/knitr#1610]
I'm trying to use `eval.after` so that I can reference R objects in the subcaptions of a figure. The documentation suggests that `eval.after` should work for any chunk option, even though the example is always `fig.cap`. I'm using R 3.5.1 with knitr 1.2.0 from CRAN compiled from source. A MWE is below. I get the following error from the second chunk: `Error in paste("Mean =", mean_b) : object 'mean_b' not found`. If I delete the second code chunk and knit the file, everything is fine. I've also tried using subfig instead of subcaption with the redefined subfloat. Unless I've misunderstood the documentation, I think this is a bug.

```
\documentclass[12pt]{article}
\usepackage{subcaption}
\newcommand{\subfloat}[2][need a sub-caption]{\subcaptionbox{#1}{#2}}

\begin{document}

<<setup, echo = F, message = F, warning = F>>=
knitr::opts_chunk$set(echo = F, fig.align = 'center') # code chunks omitted by default
@

<<fig.cap = paste('Mean =', mean_a), eval.after = 'fig.cap', out.width = '.4\\linewidth'>>=
a <- rnorm(100)
mean_a <- mean(a)
plot(a)
@

<<fig.cap = 'Means', fig.subcap=c(paste('Mean =', mean_a), paste('Mean =', mean_b)), eval.after = 'fig.subcap', out.width = '.4\\linewidth'>>=
b <- rnorm(100)
mean_b <- mean(b)
plot(a)
plot(b)
@

\end{document}
```

**Comment by billdenney** [comment]
I had an issue that I think is identical.  I traced it to the fact that I think that `af` is not set correctly to the eval.after choice here:

https://github.com/yihui/knitr/blob/01d7398f2b3dd67d4ac51706c31309f006e6134c/R/block.R#L16

I'm looking for how to fix it.

**Comment by billdenney** [comment]
@yihui, I think that I traced the issue to the fact that the value of `af` is not set to the correct value for the chunk in the line above.  The correct value is in `opts_current$get("eval.after")`, but that appears to be overwritten in the line just below there of `opts_current$restore(params)`.  I was going to try to make a PR for this, but I'm getting lost about what is happening in that part of the code.  So, I don't think that I'd get it correct.

The simplest test case I have made for this is the following document:

````
---
title: "Untitled"
author: "William Denney"
date: "1/12/2020"
output:
  pdf_document:
    keep_tex: yes
---

\listoffigures

```{r pressure-after, echo=FALSE, fig.cap=current_caption, fig.scap=current_scaption, eval.after=c("fig.scap", "fig.cap")}
plot(pressure)
current_caption <- "My long caption."
current_scaption <- "My short caption."
```
````

save that as "test.Rmd" and then run:

```r
rmarkdown::render(input="test.Rmd", output_format="pdf_document", output_file="test.pdf")
```

**Comment by cderv** [comment]
Hi, 

From the documentation, we see that `eval.after` is a package option and not a chunk option. See https://yihui.org/knitr/options/#package-options

I guess that means it is not designed to be used as in your examples here, but in a setup chunk using something like
```r
opts_knit$set(eval.after = "fig.cap")
```

If you set it like this, it will work as expected.
````r
---
title: "Untitled"
author: "William Denney"
date: "1/12/2020"
output:
  pdf_document:
    keep_tex: yes
---

\listoffigures

```{r setup, include = FALSE}
knitr::opts_knit$set(eval.after=c("fig.scap", "fig.cap"))
```


```{r pressure-after, echo=FALSE, fig.cap=current_caption, fig.scap=current_scaption, fig.align="center"}
plot(pressure)
current_caption <- "My long caption."
current_scaption <- "My short caption."
```
````

So I don't think this is a bug, it works as expected as a package option.

Hope it helps.

**Comment by billdenney** [comment]
Thanks for that explanation.  I mistakenly thought that all package options could be overridden at the chunk level.

Could a warning be issued when a package option is given at the chunk level to help users find these mistakes?

**Comment by cderv** [comment]
> Could a warning be issued when a package option is given at the chunk level to help users find these mistakes?

This is an interesting idea but I am not sure this is so easy to implement regarding knitr designed. See https://github.com/yihui/knitr/issues/1737 for a similar feature request where you'll find an answer.

knitr offers (almost) infinite possibilities for customization and any arbitrary chunk options can be added and processed by custom hook. To warn about `eval.after` not being a chunk option would mean to decide that _packages options_ are forbidden to be used as chunk options, whereas technically it can exist. For example, in your reprex, you could add a custom hook that would process `eval.after` chunk option, and in that case it should not warn I think. 

Hope it clear and you see that it does not seem trivial regarding the choices of knitr I believe to be an advanced very customizable tool.

**Comment by billdenney** [comment]
Thanks to the pointer to #1737.  I don't know many (perhaps any) people who are using custom hooks, but I understand that the option is there, and I understand the goal of flexibility.

I wonder if there is a possible compromise where both this and #1737 could be handled.  What I'm thinking of is:

When developing a custom hook, the developer knows about the hook.  They could register the hook (e.g. `knitr::register_chunk_option("my.custom.chunk.hook")` and `knitr::register_package_option("my.custom.package.hook")`).  Then, if a hook is not registered, then a warning is issued with a message like:

```
Warning:  Chunk option `missssspelled.hook` is not known.  This may be misspelled or it may be OK if a custom hook is being used.  To silence this warning, please use `knitr::register_chunk_option("missssspelled.hook")`.
```

Functionality like that seems like it would help the user, be backward compatible (with the exception that custom hooks would have a warning), and have minimal effort to implement, maintain, and fix for current custom hooks.

**Comment by yihui** [comment]
The flexibility is even beyond chunk hooks. For example, you can introduce arbitrary chunk options to decide when to invalidate cache: https://yihui.org/knitr/demo/cache/#even-more-stuff-for-cache In this case, `cache.extra` is neither a chunk or package option, but totally valid.

Anyway, I acknowledge that `opts_knit` vs `opts_chunk` has always been confusing users. I just added an emphasis on https://yihui.org/knitr/options/. If you could let me know where you learned `eval.after` and how you were confused by the source of your learning, we could probably also update the source to emphasize that `opts_knit` should be used instead of `opts_chunk`. Thanks!

**Comment by billdenney** [comment]
I learn about all options via https://yihui.org/knitr/options/.  I don't think that I ever really differentiated chunk vs package, and I think that I assumed that you could override package options at the chunk level.  At least for `eval.after`, it seemed like an override at the level of chunk seemed reasonable to me, so I don't think that I ever gave it a second thought.  As in, I could imagine wanting `eval.after` to apply differently for different chunks.

**Comment by jayrobwilliams** [comment]
Exact same situation for me as well. Thanks for clearing this up!

**Comment by billdenney** [comment]
I should have added:  And thank you for clearing it up!  :)
