### ISSUE TITLE
[Feature Request] `knit` `.Rmd` with `params` in yaml header to `.md`

### ISSUE THREAD

**Issue by RolandASc** [yihui/knitr#1613]
### Issue
---
`rmarkdown::render` works nicely on a Rmarkdown file with `params` (https://bookdown.org/yihui/rmarkdown/params-declare.html).

`knitr::knit(<Rmd-file>, <md-file>)` however **appears to fail to make use of `params`** and will produce something like below in the respective chunks that try to make use of `params`:

```r
## Error in eval(expr, envir, enclos): object 'params' not found
```

### Background
---
We have a workflow to publish news posts on our website that generates website-compatible `.md` files from an initial `.Rmd` document, which is our preferred source format for posts.

### Workaround
---
A possible work-around is to **use a hook**:
```r
paramHook <- function(before, options, envir) {
  if (before) {
    if (!exists("params", envir = envir)) {
        params <- eval(parse(text = knitr:::.knitEnv$tangle.params[2]))
        assign("params", params, envir = envir)
    }
  }
}
knitr::knit_hooks$set(doPar = paramHook)
knitr::knit(<Rmd-file>, <md-file>)
```
This **requires adding e.g. `doPar = 1`** as chunk option to those chunks that make use of params.

I think it's clear that this work-around is not very nice and it seems I shouldn't have to do it.

### Considerations
---
It is maybe not a trivial request. One possibility I could see without touching too much code is to modify `knitr:::process_file`:
```r
process_file <- function(text, output)
{
  groups = split_file(lines = text)
  if (isTRUE(opts_knit$get("yaml.pars"))) {
    parList = list(label = "yaml-params", include = FALSE)
    knit_code$set(`yaml-params` = structure(
      .knitEnv$tangle.params, chunk_opts = parList
    ))
    groups = c(
      groups[1],
      list(structure(list(params = parList), class = "block")),
      groups[-1]
    )
  }
  n = length(groups)
  <.......................>
```
Requires **`opts_knit$set(yaml.pars = TRUE)`**.

Doesn't look very nice either, but here is where I'm sure you'll have an opinion.

**Comment by yihui** [comment]
You can call `rmarkdown::render(..., run_pandoc = FALSE)` to skip the Pandoc conversion. Will that do the job?

**Comment by RolandASc** [comment]
You are right, we should probably resort to `rmarkdown::render(..., clean = FALSE, run_pandoc = FALSE)`.

It's a bit less convenient, because we cannot get the plots into the right place directly anymore (i.e. we were using `knitr::opts_chunk$set(fig.path = ...)` to get them under **assets/images/...**).

But with a few extra lines of copying / renaming and unlinking the intermediate output as well as path substitution on the resulting `md` we can get where we want to be (we have to do some modification to the resulting `md` anyhow, such as adding `{{ site.baseurl }}/...`).

All in all this seems preferable to me if I compare with the above work-around using a hook.
