### ISSUE TITLE
Improvement suggestion : incrementaly show outputs in HTML doc

### ISSUE THREAD

**Issue by pokyah** [yihui/knitr#1615]
Hi! 

I was wondering how I could make a .Rmd file that could output an HTML document with a button to reveal show/hide outputs as code_folding allows to do, or even better, a "next" button that would allow to progressively reveal the content of the whole page. 

That would be very useful for teaching purposes. I know that exporting to revealjs allows this feature by passing `incremental: yes` into the YML of the .Rmd doc. I don't want to use revealjs for my teaching presentation because it does not play nicely with interactive leaflet maps.

I've tried many attempts like adding a js script to my .Rmd but then I've encountered problems like the interactive plots not showing up, etc...
This [stackoverflow thread](https://stackoverflow.com/questions/42630248/collapsing-hiding-figures-in-r-markdown) proposes a nice hack to achieve this (show/hide but not "next"), but it requires to tediously add HTML tags in my Rmarkdown doc.

How could we make this work by passing a parameter into the YML header of the document ? 

Thanks for any enlightenment. 

Hope this is the good place to ask this question as it is rather a code development question rather than a usage question.

**Comment by cderv** [comment]
> That would be very useful for teaching purposes.

Do you know about `learnr` 📦  : https://rstudio.github.io/learnr/  ? 

You have there a feature called [Progressive Reveal](https://rstudio.github.io/learnr/exercises.html#progressive_reveal) that could be of interest to you. 
You'll find example in the website, but also in https://rstudio.cloud/ in the _Primers_ section.

**Comment by pokyah** [comment]
Many thanks @cderv ! I had no idea that my requested feature was already available into a package ! 
No more HTML/JS cluttering into my .Rmd now :D 

That's perfect !
