### ISSUE TITLE
How to make a full width figure when using the **twocolumn** class option?

### ISSUE THREAD

**Issue by RSchwinn** [yihui/knitr#1620]
How can one create a full width figure when using the **twocolumn** class option in knitr / R / RMarkdown / LaTex?

 Based on the Knitr documentation, I've tried two approaches, see below. I'm especially curious as to why specifying the *fig.env* does not work. I've included a blank caption as required. Nothing short of editing the .tex file works for me.

This: 

    ---
    output: pdf_document
    classoption: twocolumn
    header-includes: 
        - \usepackage{lipsum}
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```
    
    \lipsum[1-2]
    

    ```{r fig.env = "figure*", fig.cap = "Test"}
    plot(runif(10))
    ```
    
    \lipsum[3-5]
    
    ```{r fig.fullwidth = T}
    plot(runif(10))
    ```

Results in this:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/h64uM.png

**Comment by yihui** [comment]
The option `fig.env = 'figure*'` should be respected now (in the dev version of **knitr**). But the plot will float to a new page. I guess that is a LaTeX issue orthogonal to **knitr**. Thanks!

**Comment by RSchwinn** [comment]
Awesome!!! You are the best!
