### ISSUE TITLE
caching not invalidated by varying parameters

### ISSUE THREAD

**Issue by trestletech** [yihui/knitr#1624]
(Not sure if this is an rmarkdown or knitr issue, but trying here first)

````
---
title: "Hi"
author: "Jeff Allen"
date: "10/25/2018"
output: html_document
params:
  string: "whatever"
---

```{r, cache=TRUE}
print(params$string)
```
````

1. Knit the above document
2. Change the value of the `string` parameter to something else
3. Rerun, and notice that the output is still cached.

**Comment by yutannihilation** [comment]
This is what cache is supposed to work; if the code (and options) of the chunk stays unchanged, the evaluation is skipped. For example, you'll see the time will be stopped forever:

````
---
output: html_document
---

```{r define_a}
a <- Sys.time()
```

```{r use_a, cache=TRUE}
a
```
````

So, knitr provides some options to force evaluation even if `cache=TRUE`:

- `cache.rebuild`
- `dependson`
- `autodeps`

For example, you can use `cache.rebuild` by caching the hash of `params` by yourself:

````
---
title: "Hi"
author: "Jeff Allen"
date: "10/25/2018"
output: html_document
params:
  string: "whatever"
---

```{r, include=FALSE}
params_cache <- file.path(knitr::opts_chunk$get("cache.path"), "__params.digest")
if (file.exists(params_cache)) {
  digest_old <- readLines(params_cache)
} else {
  digest_old <- NULL
}

digest_new <- knitr:::digest(params)
print(digest_new)
writeLines(digest_new, con = params_cache)
```

```{r, cache=TRUE, cache.rebuild=!identical(digest_old, digest_new)}
print(params$string)
```
````

That said, I feel this is a bit boring... Maybe knitr needs some handy function to detect the params are changed?

**Comment by yihui** [comment]
That is indeed boring, and a much simpler solution could be this:

````
---
title: "Hi"
author: "Jeff Allen"
date: "10/25/2018"
output: html_document
params:
  string: "whatever"
---

```{r, cache=TRUE, cache.whatever=params$string}
print(params$string)
```
````

See more info in the section "Even more stuff for cache?" at https://yihui.name/knitr/demo/cache/ The point is that you have to let **knitr** know that this code chunk's cache depends on an external value.

@yutannihilation This time you were punished by knowing too much internal stuff about **knitr** :)

**Comment by yihui** [comment]
@yutannihilation No, no need to apologize at all! This is very common: when you become an expert, you may fail to see those obvious solutions because you tend to pursue deeply technical solutions. Your solution above clearly demonstrates that you are a **knitr**-caching expert (which is great!).

**Comment by yutannihilation** [comment]
@yihui Thanks! Anyway, I always find a lot to learn in your simple answers (and codes). I really appreciate it :)
