### ISSUE TITLE
A new Ruby engine for knitr

### ISSUE THREAD

**Issue by rbotafogo** [yihui/knitr#1629]
Hello... 

I have posted a question on stakoverflow but without any answer (https://stackoverflow.com/questions/53090259/how-to-include-plots-in-a-new-engine).  But I guess this might be a bit confusing.  I'll try to expand a bit: I'm writing a new Ruby engine for knitr running on GraalVM.  GraalVM allows multiple languages to interact on the same process, sharing data across languages and chunks which I'd like to allow for Ruby chunks.  Using the Polyglot API from GraalVM, the Ruby code can create plots with ggplot.  I've developed the Ruby engine and it outputs properly text generated in the chunk, but it does not output the ggplot plot.  I've looked through the code of the R engine in knitr and my engine is now as follows:

    eng_ruby = function(options) {
      # exec_ruby evaluates the ruby code in options$code
      block_code = paste(options$code, collapse = "\\n");
      code = paste0("GalaazUtil.exec_ruby(", 
                                shQuote(block_code), 
                                ")
                              ");

      keep = options$fig.keep
      keep.idx = NULL
      if (is.numeric(keep)) {
        keep.idx = keep
        keep = "index"
      } 

      tmp.fig = tempfile(); on.exit(unlink(tmp.fig), add = TRUE)
      # open a device to record plots
      if (chunk_device(options$fig.width[1L], options$fig.height[1L], keep != "none",
                       options$dev, options$dev.args, options$dpi, options, tmp.fig)) {
        # preserve par() settings from the last code chunk
        if (keep.pars <- opts_knit$get("global.par"))
          par2(opts_knit$get("global.pars"))
        showtext(options$fig.showtext)  # showtext support
        dv = dev.cur()
        on.exit({
          if (keep.pars) opts_knit$set(global.pars = par(no.readonly = TRUE))
          dev.off(dv)
        }, add = TRUE)
       }

      # guess plot file type if it is NULL
      if (keep != "none" && is.null(options$fig.ext))
        options$fig.ext = dev2ext(options$dev)

       # now evaluate the ruby code and store the result in 'res'.  Here 'res' only has
       # output captured from 'stdout'... needs to be able to indicate that plots were 
       # generated
       res = eval.polyglot("ruby", code);

      engine_output(options, block_code, res)
    }

At this point, if there is a ggplot plot on the Ruby chunk, it will be created and stored in a file in the /tmp directory.  I still need to be able to grab this plot and add it to the final document.

Could you please help me with the next steps?  I've gone through the evaluate package, but I still don't see how to grab the plot.

Thanks.

**Comment by yihui** [comment]
I just posted an answer to your SO question. Thanks!
