### ISSUE TITLE
Execute code chunk in a background terminal

### ISSUE THREAD

**Issue by vrodriguezf** [yihui/knitr#1630]
Hi,

I am new to this package and to Rmarkdown in general:

Is it possible to execute a code chunk in a background RStudio terminal while developing a .Rmd file? 

Thanks!

**Comment by yihui** [comment]
You seem to be talking about a feature for an editor (RStudio?) instead of the **knitr** package.

**Comment by vrodriguezf** [comment]
Yes, well I am talking between an integration of both things. Would it be better to ask this in the Rstudio forum?

**Comment by yihui** [comment]
Yes.

**knitr** can't (and probably shouldn't) execute code chunks in background processes.
