### ISSUE TITLE
feature request : show first characters of chunk code instead of "unnamed-chunk" in console output

### ISSUE THREAD

**Issue by moodymudskipper** [yihui/knitr#1634]
In the console ouput when running knitting:

> label: unnamed-chunk-42

would become

> x <- myfun(this, th...

if unnamed chunk contained :

```
x <- myfun(this, that)
y <- something_else
```

I always find myself having to label chunks to debug, because I don't know right away where is the problematic chunk.

It could be an option or the default behavior, it could replace the "unnamed-chunk" like shown above or be optionally printed for any chunk, regardless if they're named or not.

Thanks for the great work!

**Comment by yihui** [comment]
That sounds like a clever idea.

When errors occur, you should see the line numbers, though.
