### ISSUE TITLE
xcolor option clash with fancyvrb v 3.0.

### ISSUE THREAD

**Issue by aravind-j** [yihui/knitr#1635]
Hi,

A couple of my packages were showing `! LaTeX Error: Option clash for package xcolor` error in CRAN recently. I was not able to reproduce it until I received an email from Prof. Brian Ripley which informed that this was because of the updated `fancyvrb` Tex package. I was using the following option with conflicted with `xcolor` being called by `fancyvrb` later.

```
header-includes:
- \usepackage[table]{xcolor}
``` 

He suggested a adding `\PassOptionsToPackage{table}{xcolor}` to the tex file before the  `\documentclass` line. when I manualy do that, it is fixed, but with `render::rmarkdown()`, it is not working.

A minimal reprex is given as follows:

```````
---
title: "Test"
author: "author1, author2"
date: "14 November 2018"
header-includes:
- \usepackage[table]{xcolor}
output:
  pdf_document:
    dev: cairo_pdf
    fig_caption: no
vignette: |
  %\VignetteIndexEntry{Introduction}
  %\usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. 

```{r cars}
summary(cars)
```

## Plots

```{r pressure, echo=FALSE}
plot(pressure)
```
```````

**Comment by yihui** [comment]
You can either use the solution https://stackoverflow.com/q/53389743/559676 or provide your own Pandoc LaTeX template (section 3.3.7.4: https://bookdown.org/yihui/rmarkdown/pdf-document.html#advanced-customization-1).
