### ISSUE TITLE
knitr doest recognise installed packages, though no problems running chunks individualy

### ISSUE THREAD

**Issue by manntomer** [yihui/knitr#1638]
Hello.
I'm having problems knitting an R markdown document. the particular chunk that's giving mt trouble uses the "tableone" package, and gives the following error:

"Error in library(tableone): there is no package called 'tableone' "

the code chunk is (if necessary i'll upload some of the the actual data):

>pt.table1<-patient.table[,-unwanted.cols]%>%tbl_df()
>catVars<-pt.table1[sapply(pt.table1,class)=="integer"]%>%colnames()
>my.tab2<-CreateTableOne(data = pt.table1,strata = 
>"cerebrovascular.pt",factorVars = catVars)
>print(my.tab2)
>summary(my.tab2)

This package is properly installed,and the chunk works fine if i just run it by itself (such as with CTRL ALT C), and of course it works when ran through the console.

I have a similar problem in a different chunk with package 'e1071'. other packages in the rest of the code chunks work fine.

I"l appreciate any help!
 thanx. t.

**Comment by cderv** [comment]
Per the [issue template](https://github.com/yihui/knitr/blob/master/.github/ISSUE_TEMPLATE.md) you should have seen when posting the issue,  a reproductible example would help to try reproduce your error. Without, it is difficult for us to know what is going one.

Here is a Rmd document that knit properly using the `tableone` package.

````r
---
title: "test table one"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tableone)
## Load Mayo Clinic Primary Biliary Cirrhosis Data
library(survival)
```

# load data

```{r cars}
data(pbc)
## Check variables
head(pbc)

## Make categorical variables factors
varsToFactor <- c("status","trt","ascites","hepato","spiders","edema","stage")
pbc[varsToFactor] <- lapply(pbc[varsToFactor], factor)

## Create a variable list
dput(names(pbc))
vars <- c("time","status","age","sex","ascites","hepato",
          "spiders","edema","bili","chol","albumin",
          "copper","alk.phos","ast","trig","platelet",
          "protime","stage")
```

And create the table
```{r}
## Create Table 1 stratified by trt
tableOne <- CreateTableOne(vars = vars, strata = c("trt"), data = pbc)

## Just typing the object name will invoke the print.TableOne method
tableOne
```
````

**Comment by yihui** [comment]
@manntomer This kind of issues may take one minute for me to investigate if I can do it on your computer, otherwise it can take much longer because there are many possible reasons and we have to go through them one by one.

The first step is to check what the code below returns in your R console and in R Markdown, respectively.

```r
.libPaths()
find.package('tableone')
```

Note that you should delete everything in your Rmd document and only insert one code chunk with the above code.
