### ISSUE TITLE
Error occours when package {rotating} is included.

### ISSUE THREAD

**Issue by cone001** [yihui/knitr#1639]
I tried to play with the tex file generated by the 002-minimal example. When I add one line to the tex file:

`\usepackage{rotating}`

the command:

`tools::texi2pdf('test.tex')`

will lead to an error:

> Error in system(paste(shQuote(texi2dvi), if (quiet) "--quiet" else "",  : 
  (converted from warning) running command '"C:\CTEX\MiKTeX\miktex\bin\texi2dvi.exe" --quiet --pdf "test.tex" --max-iterations=20 -I "C:/Program Files/R/R-3.5.1/share/texmf/tex/latex" -I "C:/Program Files/R/R-3.5.1/share/texmf/bibtex/bst"' had status 1
 1: tools::texi2pdf("test.tex")
 2: texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet, texi2dvi = texi2dvi, texinputs = texinputs, index = index)
 3: system(paste(shQuote(texi2dvi), if (quiet) "--quiet" else "", if (pdf) "--pdf" else "", shQuote(file), extra), intern = TRUE, ignore.stderr = TRUE)
 4: .signalSimpleWarning("running command '\"C:\\CTEX\\MiKTeX\\miktex\\bin\\texi2dvi.exe\" --quiet --pdf \"test.tex\" --max-iterations=20 -I \"C:/Program Files/R/R-3.5.1/share/texm
 5: withRestarts({
    .Internal(.signalCondition(simpleWarning(msg, call), msg, call))
    .Internal(.dfltWarn(msg, call))
}, muffleWarning = function() NULL)
 6: withOneRestart(expr, restarts[[1]])
 7: doWithOneRestart(return(expr), restart)

Not sure how to fix this problem, any suggestion is highly appreciated. Thanks.

**Comment by yihui** [comment]
I recommend you to install [TinyTeX](https://yihui.name/tinytex/) (you can keep MikTeX if you want, but it is not necessary):

```r
tinytex::install_tinytex()
```

Then use `knitr::knit2pdf('002-minimal.Rnw')` instead of `tools::texi2pdf()`.
