### ISSUE TITLE
When compiling in Windows, more whitespace is added around equations

### ISSUE THREAD

**Issue by martinschmelzer** [yihui/knitr#1640]
I am not sure where the error might lie. I decided to open an issue here though, to have this problem be investigated more thoroughly:

When compiling this presentation

```
---
title: "Whitespace"
author: "Martin"
date: "11/19/2018"
output: 
  beamer_presentation:
    keep_tex: true
---

## Conditional Likelihood for $ARCH$

TESTESTESTEST
\begin{align*}
	&\Pr(Y_t\leq x\ \vert\ Y_{t-1}=y_{t-1},\ldots,Y_{1}=y_{1})\\
	&=\Pr(\epsilon_t\leq x/\sigma_t\ \vert\ Y_{t-1}=y_{t-1},\ldots,Y_{1}=y_{1})=\Phi(x/\sigma_{t}),
\end{align*}
TESTESTESTEST
```

The whitespace around the equation differs between my Mac and a Windows computer of a colleague.
When compiling on Mac, there is no line break before and after the align block whereas compiled on Windows, we indeed find blank lines there.

Is this an issue resulting from the different locale settings?

This is the Mac `sessionInfo()`:

```R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin17.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1     yaml_2.2.0     
 [7] Rcpp_1.0.0      rmarkdown_1.10  knitr_1.20      digest_0.6.18   evaluate_0.12 
```

And here info on the Windows session:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
 
Matrix products: default
 
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                  
[5] LC_TIME=German_Germany.1252   
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    
 
other attached packages:
[1] CASdatasets_1.0-6   sp_1.3-1            fGarch_3042.83      fBasics_3042.89     timeSeries_3042.102 timeDate_3043.102 
[7] xts_0.11-1          zoo_1.8-4         
 
loaded via a namespace (and not attached):
[1] Rcpp_0.12.16    lattice_0.20-35 digest_0.6.15   rprojroot_1.3-2 grid_3.4.4      backports_1.1.2 magrittr_1.5    evaluate_0.10.1
[9] stringi_1.1.7   spatial_7.3-11  rmarkdown_1.10  tools_3.4.4     stringr_1.3.0   yaml_2.2.0      compiler_3.4.4  htmltools_0.3.6
[17] knitr_1.20
```

**Comment by yihui** [comment]
When posting issues about what you see on your screen, I strongly recommend that you provide screenshots. From your verbal description above, my imagination fails to tell me what exactly the problem is.

You also need to check `rmarkdown::pandoc_version()` on the two computers.

**Comment by martinschmelzer** [comment]
I am sorry. The Mac system uses pandoc 2.4 (without any issues so far). The Windows machine uses 1.29.2.1. Even though you suggest to not (yet) upgrade to pandoc 2.4, the issue seems to arise with the older version.

Here are two screenshots of the produced TeX file and the slide on Mac:

<img width="948" alt="screenshot 2018-11-19 15 59 12" src="https://user-images.githubusercontent.com/7760212/48715421-428ff880-ec15-11e8-9a08-da85c5479fa8.png">

<img width="591" alt="screenshot 2018-11-19 15 59 00" src="https://user-images.githubusercontent.com/7760212/48715441-520f4180-ec15-11e8-8822-835938a11175.png">

As you can see, no linebreak before `\begin{align*}`. And here the same screenshots for the Windows system:

<img width="938" alt="screenshot 2018-11-19 16 04 47" src="https://user-images.githubusercontent.com/7760212/48715503-7408c400-ec15-11e8-8bdc-355c49ec94e4.png">

<img width="967" alt="screenshot 2018-11-19 16 04 21" src="https://user-images.githubusercontent.com/7760212/48715517-7c60ff00-ec15-11e8-96a6-0990d3c8beb5.png">

**Comment by yihui** [comment]
No worries.

Actually my blog post has been updated a few months ago: https://yihui.name/en/2017/11/pandoc-2/

Back to your issue: from your screenshots, you used different Markdown source on two platforms (one with empty lines and one without), and I won't be surprised that the outputs are different. When an `align` environment is in its own paragraph, it is very normal that there is extra white space: https://stackoverflow.com/q/39522390/559676

**Comment by yihui** [comment]
Oh I see. Sorry for not reading the previous message more carefully! Then this is surely a Pandoc version issue. As I wrote in the follow-up post, you should try Pandoc 2.x now: https://yihui.name/en/2018/06/time-for-pandoc-2-x/ Thanks!

**Comment by martinschmelzer** [comment]
That solved it indeed. Thank you for your assistance!

**Comment by yihui** [comment]
You are welcome!
