### ISSUE TITLE
knitr changes "(1)" to <ol> tags when rendering html?

### ISSUE THREAD

**Issue by jozefhajnala** [yihui/knitr#1641]
Stackoverlow link: 

- https://stackoverflow.com/questions/53616667/knitr-changes-1-to-ol-when-rendering-html

The following content of a .Rmd file:
````
---
title: "Untitled"
output:
  html_document: default
---

```{r cars}
mtcars$am <- sprintf("(%s)", as.character(mtcars$am))
knitr::kable(mtcars, format = "html")
```
````
Will show ordered lists `<ol><li></li></ol>` in the `am` column, instead of the numbers in brackets (as produced with the `sprintf`) after rendering to html.

Is this intended?  

The output of knitr::kable seems to be fine, showing:
`<td style="text-align:left;"> (1) </td>`

Details:

- Using knitr 1.20
- RStudio Server 1.1.453
- note that removing format = "html" does not resolve the issue as in the real-life context I would like to do advanced formatting with css e.g. based on the classes of the produced tables

**Comment by yihui** [comment]
Answered on SO. Thanks!
