### ISSUE TITLE
knit_print the flextable in loop

### ISSUE THREAD

**Issue by JackHsueh** [yihui/knitr#1643]
Thanks for this wonderful packages to edit table in word. 
When I want to output some table  iteratively, I found `knit_print` of `flextable` is no working in loop.
```
data(cars)
speed<-unique(cars$speed)
for (v in 1:length(speed)) {
  carspd<-cars[which(cars$speed==speed[v]),]
  tb<-regulartable(carspd)
knit_print(tb)
}
knit_print(tb)
```
Just the last `knit_print` can print the result to the word_document with the RMD file.

**Comment by yihui** [comment]
https://stackoverflow.com/q/53629692/559676

When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread. Thanks!

**Comment by cderv** [comment]
And also posted here 
https://github.com/davidgohel/flextable/issues/92
