### ISSUE TITLE
output path is not quoted in the cmd call to pandoc

### ISSUE THREAD

**Issue by antoine-sachet** [yihui/knitr#1644]
I am calling `knitr::pandoc` on a file whose path contains spaces. Sadly quite common on Windows.

Example:
> knitr::pandoc("C:/Users/Antoine Sachet/Projects/reprex/Introduction.md")
```
executing pandoc   -t html -o C:/Users/Antoine Sachet/Projects/reprex/Introduction.html "C:/Users/Antoine Sachet/Projects/reprex/Introduction_utf8.md"
pandoc.exe: Sachet/Projects/reprex/Introduction.html: openBinaryFile: does not exist (No such file or directory)
Error in (function (input, input_utf8, format, ext, cfg)  : 
  conversion failed
```

This happens because the output path passed to pandoc (`-o` argument) is not quoted so the space is messing things up.

I have tracked it to the following bit of code in `knitr:::pandoc_one`. Is there any reason why `out` is not quoted in `cmd` below while `input_utf8` is?

    cmd = paste("pandoc", pandoc_arg(cfg), pandoc_arg(cmn), "-t", 
        format, "-o", out, paste(shQuote(input_utf8), collapse = " "))

I figured there might have been a good reason not to use `shQuote(out)` instead of `out`? If not, I am happy to raise a PR.

**Comment by yihui** [comment]
It definitely should be quoted. I'll fix it in a minute. Thanks for the report!
