### ISSUE TITLE
Add style argument to include_url()

### ISSUE THREAD

**Issue by jvcasillas** [yihui/knitr#1648]
I would like to suggest including a style argument to the function `include_url()`. By default iframes include a rather ugly border around the object that is embedded. I propose including a style argument so that something like `style="border:none;"` can be included. If this is something that would be desirable, I would be more than happy to submit a pull request, though I don't know where `include_url` lives.

**Comment by yihui** [comment]
This sounds like a reasonable feature request to me, but I don't have time for it. If you want to disable iframe borders globally, you could just define it in CSS like (I think you certainly know it):

```css
iframe {
  border: none;
}
```

**Comment by yihui** [comment]
Done. Example:

````
```{r, out.extra='style="border: none;"', out.width='100%'}
knitr::include_url('https://yihui.name')
```
````

I think you still want to do it in CSS because that's cleaner.
