### ISSUE TITLE
add support for vega-lite

### ISSUE THREAD

**Issue by djouallah** [yihui/knitr#1651]
I am using the package altair as a python chunk in a flexdashboard, the code works without error, but the output is empty.

my understanding the altair package produce a json specification of vega-lite, which apparently knitr don't support.

is there any plan to add that support

**Comment by yihui** [comment]
No, not in **knitr**. This could and should be (and to some extent, has been) implemented in other packages. See https://github.com/vegawidget/vegawidget for one example.

Basically **knitr** supports the general HTML widgets framework. Anything that can be converted to HTML widgets will work with **knitr**.

**Comment by djouallah** [comment]
Knitr is so versatile, I found a workaround already, just generated an html from altair then use the include html function,  thanks for your software 


```{r}
shiny::includeHTML("commodity.html") 
file.remove("commodity.html")
```

**Comment by djouallah** [comment]
vegawidget is now in CRAN, I tested it and it is works,  thanks again for making this package
