### ISSUE TITLE
engine.opts cannot be passed to stan engine [in RStudio notebooks]

### ISSUE THREAD

**Issue by Selbosh** [yihui/knitr#1652]
If I pass anything at all to the chunk option `engine.opts` in a Stan chunk, the following error is thrown.
> the chunk option output.var must be a character string, providing a name for the returned `stanmodel` object.

## Minimal working example

We declare a simple model like the following. It is not necessary to sample/optimise the model to reproduce the error.

``````r
```{stan output.var = 'foo', engine.opts = list(model_name = 'bar')}
data {
  int<lower=1> N;
  int<lower=0> y[N];
}
parameters {
  real log_lambda;
}
model {
  y ~ poisson_log(log_lambda);
}
```
``````

I suspect the issue lies in this section of the code, where if `output.var` is set, then any additional `engine.opts` throw an error. https://github.com/yihui/knitr/blob/337946e62ce5723f5b39d90983fa97148f53ace7/R/engine.R#L259-L266

### Even more minimal example

The same error is thrown if I pass something that isn't even a `stan_model` argument, for example in the even more minimal working example (any model text is unnecessary as the error is thrown before it is parsed):

``````r
```{stan output.var = 'foo', engine.opts = list(lorem = 'ipsum', dolor = 'sit')}
model {}
```
``````

Also an error:

``````r
```{stan engine.opts = list(output.var = 'foo')}
model {}
```
``````

Clearly something isn't quite right here.

## Motivation

I generally have no problem with the Stan engine for knitr, but I have noticed that while we can specify our own model *variable* name, the `model_name` itself is always automatically generated. If fitting lots of models it makes it hard to distinguish them in the output. That is, whatever I call `output.var`, it would be nice also to customise the model name in the following part of the output when running `sampling()`.

```
SAMPLING FOR MODEL 'stan-978249dbdc' NOW (CHAIN 1).
```
so that the `stan-978249dbdc` part could be customised (by passing something to `model_name`, or at the very least match the value of `output.var`. If I have misunderstood the mechanism here, I apologise.

**Comment by yihui** [comment]
I cannot reproduce this issue with the latest version of **knitr**. The minimal example works fine for me. Please provide your session info as requested by [the issue guide](https://github.com/yihui/knitr/issues/new).

**Comment by Selbosh** [comment]
I encounter the problem on my Windows PC and on an Amazon EC2 instance running Ubuntu.

#### Windows (Microsoft R Open)

```
Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.463)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-12-28                  

Packages -----------------------------------------------------------------------------------------
 package   * version date       source        
 evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)
 glue        1.2.0   2017-10-29 CRAN (R 3.5.0)
 graphics  * 3.5.0   2018-05-24 local         
 grDevices * 3.5.0   2018-05-24 local         
 highr       0.6     2016-05-09 CRAN (R 3.5.0)
 knitr       1.20    2018-02-20 CRAN (R 3.5.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)
 methods   * 3.5.0   2018-05-24 local         
 mime        0.5     2016-07-07 CRAN (R 3.5.0)
 stats     * 3.5.0   2018-05-24 local         
 stringi     1.1.7   2018-03-12 CRAN (R 3.5.0)
 stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)
 tools       3.5.0   2018-05-24 local         
 utils     * 3.5.0   2018-05-24 local         
 yaml        2.1.19  2018-05-01 CRAN (R 3.5.0)
```

#### Ubuntu on Amazon EC2
```
─ Session info ──────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Ubuntu 16.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2018-12-28                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────
 package  * version date       lib source        
 evaluate   0.11    2018-07-17 [2] CRAN (R 3.5.1)
 glue       1.3.0   2018-07-17 [2] CRAN (R 3.5.1)
 highr      0.7     2018-06-09 [2] CRAN (R 3.5.1)
 knitr      1.20    2018-02-20 [2] CRAN (R 3.5.1)
 magrittr   1.5     2014-11-22 [2] CRAN (R 3.5.1)
 markdown   0.8     2017-04-20 [2] CRAN (R 3.5.1)
 mime       0.5     2016-07-07 [2] CRAN (R 3.5.1)
 stringi    1.2.4   2018-07-20 [2] CRAN (R 3.5.1)
 stringr    1.3.1   2018-05-10 [2] CRAN (R 3.5.1)
 yaml       2.2.0   2018-07-25 [2] CRAN (R 3.5.1)

[1] /home/david/R/x86_64-pc-linux-gnu-library/3.5
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

I updated the EC2 Instance to the latest version of `knitr`, 1.21, but the problem persists. Corresponding session info:

```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Ubuntu 16.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2018-12-28                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package  * version date       lib source        
 evaluate   0.11    2018-07-17 [2] CRAN (R 3.5.1)
 glue       1.3.0   2018-07-17 [2] CRAN (R 3.5.1)
 highr      0.7     2018-06-09 [2] CRAN (R 3.5.1)
 knitr    * 1.21    2018-12-10 [1] CRAN (R 3.5.1)
 magrittr   1.5     2014-11-22 [2] CRAN (R 3.5.1)
 markdown   0.8     2017-04-20 [2] CRAN (R 3.5.1)
 mime       0.5     2016-07-07 [2] CRAN (R 3.5.1)
 stringi    1.2.4   2018-07-20 [2] CRAN (R 3.5.1)
 stringr    1.3.1   2018-05-10 [2] CRAN (R 3.5.1)
 xfun       0.3     2018-07-06 [2] CRAN (R 3.5.1)
 yaml       2.2.0   2018-07-25 [2] CRAN (R 3.5.1)

[1] /home/david/R/x86_64-pc-linux-gnu-library/3.5
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

**Comment by Selbosh** [comment]
**Update**: It looks like this is a problem with an RStudio Notebook, i.e. `output: html_notebook` or wherever chunks are evaluated within the RStudio console, but not with a regular knitted `output: html_document`. So maybe it is an RStudio problem?

**Comment by yihui** [comment]
I think you are right. If you are still able to reproduce the issue with [the latest preview version of RStudio](https://www.rstudio.com/products/rstudio/download/preview/), please report it to https://github.com/rstudio/rstudio/issues.
