### ISSUE TITLE
Abbreviation of boolean does not work in `knitr::all_labels()`

### ISSUE THREAD

**Issue by jooyoungseo** [yihui/knitr#1659]
Let's say you have the following code chunk in your main body of the current input Rmd:

````
---
title: "Test"
output: pdf_document
---

# Main Text

```{r test, echo=T, purl=T}
print("Hello World!")
```

# R Code Appendix

```{r ref.label=knitr::all_labels(purl == TRUE), echo = T, eval = F}
```
````

Even though both "TRUE" and "T" are the same in terms of boolean, `knitr::all_labels(purl == TRUE)` does not refer to any R chunk that has been denoted with `purl = T`. In other words, when the test R chunk is re-denoted with `purl = TRUE`, now `knitr::all_labels()` matches with the chunk.
Would it be something that can be fixed?

**Comment by yihui** [comment]
`TRUE` and `T` are not necessarily the same. `TRUE` is a constant, but `T` is only a global variable whose value is initialized to `TRUE`. If you want, you can assign any value to `T`, even like `T <- FALSE`.
