### ISSUE TITLE
Sass / SCSS language engine?

### ISSUE THREAD

**Issue by emilyriederer** [yihui/knitr#1665]
Would there be interest in a PR for a [Sass / SCSS](https://sass-lang.com/) language engine? Sass is a CSS extension language which allows users to write CSS more efficiently / programatically and then convert it back to CSS.

Tactically, this would look similar to a `css` chunk. Where this chunk in RMarkdown:

```
{scss echo = FALSE}
$font-stack:    Helvetica, sans-serif
$primary-color: #00FF00

body
  font: 100% $font-stack
  color: $primary-color
```

Turns into this in-line CSS code:

```
<style type="text/css">
body {
  font: 100% Helvetica, sans-serif;
  color: #99badd;
}
</style>
```

However, behind the scenes, it's slightly more complicated than the `css` engine, since first the code is passed to the `sass` executable, and then that output subsequently receives treatment similar to `eng_html_asset()`. 

---

As I see it, potential pros include:

- since Sass / SCSS "feels" more like a programming language, it might appeal to R users
- similar to the existing `css` engine, this can help code be more self-contained
- a built-in Sass engine ensures code updates are captured (versus having a stand-alone Sass file which users must remember the re-convert so RMarkdown reads in the correct CSS file)

However, I realize it might be unnecessary because:

- Sass is probably overkill for the level of in-line CSS used in most RMarkdowns
- Sass could already be run inside an RMarkdown via the Javascript engine (however, this requires more Javascript knowledge to set-up, and the Sass website states that it is slower) or called from the bash engine (however, this is true of many of the engines!)

Please let me know what you think! Just for fun, I was able to get an SCSS engine to work on Windows, but before I worry more about other systems or some issues specific to the Sass side, I thought I would see if it was of interest.

Thank you for such a great (family of) tool(s)!

**Comment by cderv** [comment]
@emilyriederer do you know about https://github.com/rstudio/sass ? 
This is an R wrapper for LibSass, a fast Sass compiler written in C++.

It would make sense to use this for what you are suggesting.  the saas engine would only be a call to `saas::saas()` 🤔

**Comment by emilyriederer** [comment]
Thanks @cderv - indeed, I did not! 😳 This seems super useful, and I'm only about 500% unsurprised that RStudio has (once again) already built the things I need. 🙂 Any idea when this may be submitted to CRAN?

That said, for `knitr`, do you think there could be any benefit in the engine not having an R and letting users manage version independently? That's probably immaterial but just for consideration, I was envisioning:

- user downloads standalone Dart Sass as per https://sass-lang.com/install (I admittedly don't have any idea how Dart vs Lib compare on speed)
- engine code looks roughly like this draft: https://github.com/emilyriederer/knitr/commit/f60465ddfebdf3f905dca03ab3c4680876a826e2

**Comment by yihui** [comment]
I'd welcome this engine. You can test `requireNamespace('sass')` and decide if you should call the `sass` executable or `sass::sass()`. Thanks!

**Comment by cderv** [comment]
>  Any idea when this may be submitted to CRAN? 

No idea. 😕 

but the `requireNamespace` trick will allow every user to choose sass executable or R 📦 and the knitr engine could deal with both. So it is even better ! ☺️ 

Nice idea by the way ! thank.

**Comment by emilyriederer** [comment]
Great idea -- thanks! That's definitely the best of both worlds to let users decide whichever is most convenient for them. 

(Also @cderv - sorry! Looking back at your original I just noticed you totally mentioned you didn't know when it would be on CRAN. I promise I can read. 🙂 )

**Comment by emilyriederer** [comment]
I'm thinking about what the ideal ordering / way to get user preferences for which engine to use would be. At the highest level, I'm thinking:

- if user provides preference, take that preference
- else if user has the `sass` package, use that since (after reading up on @cderv 's lead) I believe LibSass is faster
- else if an executable exists, use that
- otherwise, there is no applicable engine

How should I collect user preferences? For typical engines, this is done with the `engine.path` option. However, for the user to prefer the `sass` package over an executable, it's unnecessary for them to provide a full file path.  

Would it be acceptable to have users pass something like `"r-pkg"` or `"r-sass"` as the argument to `engine.path`? It's a consistent use of that option in *spirit* but admittedly feels like a bit of an abuse of the type of input `engine.path` typically accepts.

Thanks!

**Comment by cderv** [comment]
I think I would go with something simple

* If the user has `sass` 📦 installed, use it.
* If not, use executable if it exists (using `engine.path` if provided)

The choice of the user is to install or not `sass` 📦 . 

One other solution would be to do like python engine where the `reticulate` 📦 implements the engine in its own package https://rstudio.github.io/reticulate/reference/eng_python.html
There is an option `python.reticulate = FALSE` to deactivate the `reticulate` engine 
https://github.com/yihui/knitr/blob/337946e62ce5723f5b39d90983fa97148f53ace7/R/engine.R#L195-L205
I think it could be a solution if you prefer to leave a hard choice to the user (like deactivate sass 📦 for knitr).

**Comment by emilyriederer** [comment]
Thanks @cderv  ! I was definitely overcomplicate things. That's much more streamlined, and I really appreciate the `reticulate` example as too.

**Comment by emilyriederer** [comment]
One final question before the PR: 

If `sass` were on CRAN, it should be added to Suggests in the Description. However, since it is not, what is the best treatment? Since Remotes is more analogous to Imports than Suggests, that seems like a bad options, and [it's my understanding](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html#cran-submission) that would still generate a warning on CRAN anyway.

**Comment by emilyriederer** [comment]
Thanks @cderv ! That's great to know. For some reason, I had a misconception that anything used with `requireNamespace` and referenced with `::` still *had* to be added to Suggests. That's really useful to know.

**Comment by yihui** [comment]
Just like @yutannihilation mentioned, I use `getFromNamespace()` to avoid the R CMD check warning. We can use the more natural `::` once the **sass** package is on CRAN.

**Comment by yutannihilation** [comment]
Oh, thanks. I was not confident if this way of avoidance is valid on CRAN, but good to know about `getFromNamespace()`.

**Comment by yutannihilation** [comment]
Yeah, I always believe in your great tricks :)

**Comment by yihui** [comment]
Shh... Let's not advertise this :) In general we should avoid using `getFromNamespace()`, but in some special cases (like this one), we'd rather not have trouble with CRAN. The **sass** package is authored by my colleagues, so in case I or they break anything, we can fix it together quickly. This is not necessarily the case if we retrieve an object from a package written by a person that we are not familiar with.
