### ISSUE TITLE
PhantomJS Archived

### ISSUE THREAD

**Issue by chris-prener** [yihui/knitr#1671]
I wanted to ask about the [reliance on PhantomJS](https://bookdown.org/yihui/rmarkdown/interactive-documents.html). I saw today that [PhantomJS has been archived](https://github.com/ariya/phantomjs/issues/15344), and was wondering if there were plans in place to continue to support embedded screen-shots from HTML widgets in `knitr`. Everything seems to work OK right now, but am wondering about the future. Thanks @yihui, for supporting `knitr` and everything you do for the `R` community!

**Comment by yihui** [comment]
That would actually be a question for **webshot**: https://github.com/wch/webshot I guess we might switch to headless Chrome eventually.

**Comment by chris-prener** [comment]
Thanks @yihui - I had wondered that but wasn't sure what exactly the links were between the two packages. I'll open an issue over there now.

**Comment by chris-prener** [comment]
For reference - here is the link to the [`webshot` issue](https://github.com/wch/webshot/issues/75)

**Comment by yihui** [comment]
Thank you!
