### ISSUE TITLE
Error with highlight package

### ISSUE THREAD

**Issue by mlamias** [yihui/knitr#1672]
I am trying to recreate the example from page 123 of the second edition of Dynamic Documents with R and Knitr, 2nd. Edition, but the program throws an error.  I believe this worked in previous version of the package.  Here is the code:

```
<<AwkCode, engine='highlight', engine.opts='-S awk -O latex'>>=
#how many non-empty lines in the NEWS file?
NF {
 i = i + 1
}
END {print i}
@
```

After running this in Lyx, I get the following in the resulting PDF document instead of the expected output shown on page 123.:
Error in running command highlight

Some additional info that might be helpful for debugging:
```
library(knitr); sessionInfo()
## R version 3.5.2 (2018-12-20)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17763)
##
## Matrix products: default
##
## locale:
## [1] LC_COLLATE=English_United States.1252
## [2] LC_CTYPE=English_United States.1252
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C
## [5] LC_TIME=English_United States.1252
##
## attached base packages:
## [1] stats graphics grDevices utils datasets methods base
##
## other attached packages:
## [1] knitr_1.21
##
## loaded via a namespace (and not attached):
## [1] compiler_3.5.2 magrittr_1.5 tools_3.5.2 stringi_1.2.4
## [5] stringr_1.4.0 xfun_0.4 evaluate_0.13
```

**Comment by yihui** [comment]
Have you installed `highlight`? i.e. check `Sys.which('highlight')`

I can compile this minima Rnwl example:

```latex
\documentclass{article}

\begin{document}

<<AwkCode, engine='highlight', engine.opts='-S awk -O latex'>>=
#how many non-empty lines in the NEWS file?
NF {
 i = i + 1
}
END {print i}
@

\end{document}
```

**Comment by mlamias** [comment]
Thanks, Yihui.  I think I have this working now!  This was a big help.  I was confused because I thought that engine='highlight' used the highlight package in R or the 'highr' package.  Is there any easier way to modify keywords for latex than installing highlight separately and then calling it?  I have about a dozen or so additional words to add and I can't for the life of me figure out how to do, even after reading through all the documentation.  Thanks for any help you can provide!

**Comment by yihui** [comment]
I don't know what you mean by "modify keywords". However, if you use R Markdown, I believe awk scripts can be automatically syntax highlighted (via Pandoc).

**Comment by mlamias** [comment]
Thanks, Yihui.  Basically, I'm just trying to figure out how I can go about modifying the colors of certain words (what I'm calling "keywords") used in some code that I'm displaying in a knitr chunk from within Lyx to produce a PDF document.  To be honest, I'm not even using awk, but was just using that to get myself started with a basic example.  In reality, I have some code in a proprietary language that I have in a knitr chunk (with `eval=FALSE`) that I was trying to gain some control over the syntax highlighting on.  Perhaps I'm going about this the wrong way and should just use the listings package in latex, but I'm just more familiar with knitr, so wanted to try this approach.  Thanks.

Hope all is well with you!

**Comment by yihui** [comment]
I see. I'm not really a `highlight` expert. It may be possible to customize the keywords, but I don't know how. It is certainly possible to customize the colors of existing keywords through LaTeX, though (e.g. redefine LaTeX commands).
