### ISSUE TITLE
purl(), but for python chunks

### ISSUE THREAD

**Issue by schantanu** [yihui/knitr#1674]
Is there an option to extract Python code chunks, something similar to what `purl()` does? I am unable to find any info on this on stackoverflow.

```
---
title: "Untitled"
output: html_document
---

#Code

```{python}
x = 10
y = 20

z = x + y
print(z)
```

**Comment by yihui** [comment]
No, currently only R is supported. The complexity is that when there are different languages in a single document, I don't know how to write the code chunks out to a single script file.
