### ISSUE TITLE
Apply class.output to all chunk outputs or add custom classes for error, warning, message

### ISSUE THREAD

**Issue by gadenbuie** [yihui/knitr#1676]
I just discovered the `class.source` and `class.output` options introduced in #1335 and really appreciate this feature for adding CSS classes to chunk outputs in HTML. But I noticed that the `class.output` value is not added to outputs from "side effect" chunk outputs, such as messages, warnings and errors.

It would be great if this class could be applied to messages, warnings and errors as well. I would even more appreciate it if each of these could receive a custom CSS class -- perhaps `class.message`, `class.warning`, `class.error` -- that defaults to `class.output` if not otherwise specified.

Here's a small demo reprex.

<details><summary>RMD source</summary>

````
---
title: "class.output for messages, warnings, errors"
output: html_document
---

```{r setup}
# setup
knitr::opts_chunk$set(echo = TRUE, class.output = "output-style")
```

```{css}
/* class.output */
.output-style {
  background: #A2CD5A;
}
```

```{r}
cat("Normal R chunk output")
```

```{r, error = TRUE}
stop("An error occurred in this chunk.")
```

```{r}
message("This is a message")
```

```{r}
warning("This is a warning")
```
````
</details>

![image](https://user-images.githubusercontent.com/5420529/53347619-7ac76700-38e7-11e9-9174-d9e5c633a139.png)

**Comment by yihui** [comment]
That's a good feature request and easy enough to implement, so it's done now. Feel free to use `class.error`/`class.warning`, etc. Thanks!

**Comment by gadenbuie** [comment]
Thank you @yihui, this is awesome! I wrote up [a small demonstration](https://www.garrickadenbuie.com/blog/knitr-custom-class-output/) using this example, and it looks great!

Btw, I looked in NEWS.md and thought this would be in version 1.22, but I just noticed you put this issue in the v1.21 milestone. Let me know if I need to revise my post.

**Comment by yihui** [comment]
Oh, it should be v1.22, which I actually forgot to create...

Thanks for the blog post. It looks great!
