### ISSUE TITLE
kable with 0 rows dataframe does not render the right html table

### ISSUE THREAD

**Issue by wikithink** [yihui/knitr#1677]
with the 1.21 version knitr,
when the data.frame have 0 rows and 1-n cols, the render html output like this:

变量名称 筛选条件 ——— ———

html code:
`<p>变量名称 筛选条件 ——— ———</p>`

no thead,no tbody.

why?

**Comment by cderv** [comment]
Hi, 

 I tried to reproduce with last knitr version (1.21.8) and I have the thead, tbody using kable

``` r
library(knitr)
packageVersion("knitr")
#> [1] '1.21.8'
zero_row_df <- data.frame(a = character(0), b = integer(0))
zero_row_df
#> [1] a b
#> <0 lignes> (ou 'row.names' de longueur nulle)

kable(zero_row_df)
```

```markdown
|a  |  b|
|:--|--:|
```

``` r
kable(zero_row_df, format = "html")
```
```html
<table>
<thead>
<tr>
<th style="text-align:left;">
a
</th>
<th style="text-align:right;">
b
</th>
</tr>
</thead>
<tbody>
<tr>
</tr>
</tbody>
</table>
```
<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Have you a more precise example where you encounter this issue ?

**Comment by yutannihilation** [comment]
I can reproduce this by knitting the Rmd below. Not immediately sure, but pandoc's format doesn't allow 0-row table...?

````
---
title: "Untitled"
output: html_document
---

```{r}
zero_row_df <- data.frame(a = character(0), b = integer(0))
knitr::kable(zero_row_df)
```
````


I guess specifying `"markdown"` or `"html"` should work.

```
knitr::kable(zero_row_df, format = "markdown")
```

**Comment by yihui** [comment]
Sounds like this requires a similar fix as 2b1786a613967dcad286de9d35293f6b1d64b27e (switch to the `markdown` table if the `pandoc` table format doesn't work). Please feel free to submit a pull request if that is the case. Thanks!

**Comment by yutannihilation** [comment]
Thanks, Yihui. It seems the case.

**Comment by yihui** [comment]
@wikithink Should be fixed now. Please test the development version via

```r
remotes::install_github('yihui/knitr')
```

Thanks!
