### ISSUE TITLE
Adding spaces to {r, echo=FALSE} throws error

### ISSUE THREAD

**Issue by david-cortes** [yihui/knitr#1681]
The following chunks seem to produce an Rmarkdown document with no problems:

````
```{r echo=FALSE}
print("dsfsdfsdfdsf")
```
```{r echo = FALSE}
print("dsfsdfsdfdsf")
```
```{r, echo=FALSE}
print("dsfsdfsdfdsf")
```
````

However, the following will **oftentimes** throw a long error (recursion depth exceeded)
````
```{r, echo = FALSE}
print("dsfsdfsdfdsf")
```
```{r , echo = FALSE}
print("dsfsdfsdfdsf")
```
````

The only other things in the RMD document besides that chunk is the default example that comes when creating a new .Rmd file through RStudio.

**Setup:** knitr 1.21, R 3.5.1, RStudio 1.2.1322, running on windows 10

**Comment by yihui** [comment]
I cannot reproduce it. The space before the comma should be okay. Could you post the full error message?

BTW, you didn't follow the issue guide to [update everything](https://yihui.name/en/2017/05/when-in-doubt-upgrade/): your R and knitr versions are old, although they shouldn't matter.

**Comment by david-cortes** [comment]
I'm now not entirely sure if the problem is triggered by the spacing or by something else - I seem to only get the error at random when using `{r, echo = FALSE}`, but it might just be a coincidence, and clicking "Knit" again without changing anything will usually work fine. This is one example of error log:
```
Access violation in generated code when executing data at 0x799bdf1

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x57adaf0	0x799bdf1
 * 0x57adaf8	0x7ffa8a4d00f0 C:\windows\System32\IMM32.DLL+0xf0
 * 0x57adb00	0x57ade60
 * 0x57adb70	0x7ffa8cfbbaa1 C:\windows\SYSTEM32\ntdll.dll+0x3baa1
 * 0x57adb78	0x8e776d1
 * 0x57adb80	0x1
 * 0x57adb88	0x2d
 * 0x57adb90	0x78d42a0
 * 0x57adb98	0x71
 * 0x57adba0	0x7875598
 * 0x57adba8	0x7828601
 * 0x57adbb0	0x7861661
 * 0x57adbb8	0x7861678
 * 0x57adbc0	0x7861692
 * 0x57adbc8	0x78616a8
 * 0x57adbd0	0x799f708
 * 0x57adbd8	0x799f6d1
 * 0x57adbe0	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbe8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbf0	0x423fba8 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e3fba8
 * 0x57adbf8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adc00	0x799f848
 * 0x57adc08	0x78fc3b3
 * 0x57adc10	0x7807310
 * 0x57adc18	0x7807700
 * 0x57adc20	0x7807718
 * 0x57adc28	0x7807730
 * 0x57adc30	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc38	0x4231e2a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e31e2a
 * 0x57adc40	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc48	0x4a6d3e9 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x466d3e9
 * 0x57adc50	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc58	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc60	0x41a98d3 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3da98d3
 * 0x57adc68	0x4280a19 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e80a19

   ... (maximum recursion depth reached.)

Error: pandoc document conversion failed with error 11
Execution halted
```

**Comment by yihui** [comment]
I think that is a Pandoc bug (likely to be https://github.com/jgm/pandoc/issues/5037) and irrelevant to **knitr**. We have received such reports several times, e.g. https://github.com/rstudio/rstudio/issues/3661 https://github.com/rstudio/rstudio/issues/4072 Unfortunately it is still not clear to us what was really wrong in Pandoc.

You may try to install a newer version of Pandoc and see if that helps: https://pandoc.org/installing.html

**Comment by ck37** [comment]
I also ran into this issue on windows with the latest version of RStudio and resolved it by adding a chunk name to the one unnamed chunk in my document (i.e. switched from 
"{r}" to "{r name}")
