### ISSUE TITLE
how to capture the knitr(bookdown) verbose to a file?

### ISSUE THREAD

**Issue by wikithink** [yihui/knitr#1682]
Dear Yihui: when I render a book with knitr,I want to capture out the console log and write into a file,
,but I can not find an  knitr option to do that? any way  any hint is desired,thanks a lot

**Comment by yihui** [comment]
`?sink`

**Comment by wikithink** [comment]
thanks for you so quickly feedback,I have use sink( ) capture the render output into a file, thanks very much!
but my truth purpose for the output log is display the log with a shiny ui(like textOutput) sync(同步),i have use the withcallinghandler capture the render message but not include output, is there have one method to transfer output to message? or send to message? 
this question i have submit in the bookdown package. thanks a lot.

**Comment by cderv** [comment]
@wikithink for general questions like this one, do not hesitate to ask on https://community.rstudio.com
There is a large community ready to help and share experience.
