### ISSUE TITLE
Knitr button suddently is not working anymore

### ISSUE THREAD

**Issue by andresalerno** [yihui/knitr#1686]
Hi!

I am completely stuck and I do not know how I could solve this problem that I will describe bellow. I was working normally with a .Rmd file, and also I was receiving the correct output when I clicked in the kniter button. Suddently it is not working anymore with this message:

> Sorry, but C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\pdflatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\andre\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log
Erro: Failed to compile multipleRegression.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips.
Além disso: Warning message:
In readLines(logfile) :
  linha final incompleta encontrada em 'multipleRegression.log'
Execução interrompida

Please, anyone could help me?

Best,

``> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  htmltools_0.3.6 tools_3.5.1     yaml_2.2.0      Rcpp_1.0.1      rmarkdown_1.12  knitr_1.22     
 [8] xfun_0.5        digest_0.6.18   evaluate_0.13

**Comment by yihui** [comment]
Please try to install TinyTeX instead of MiKTeX: https://bookdown.org/yihui/rmarkdown/installation.html
