### ISSUE TITLE
Option to show chunk options in output

### ISSUE THREAD

**Issue by ulyngs** [yihui/knitr#1688]
It's often important to be able to display a code chunk in the output where the reader is also able to see the chunk options.

At the moment, one has to do this rather awkwardly with something like:

`````
````markdown
`r ''````{r setup, echo=TRUE}
library(tidyverse)
```
````
`````

Which outputs
````markdown
```{r setup, echo=TRUE}
library(tidyverse)
```
````

It would be fantastically useful if something like

````
```{r setup, echo_opts=TRUE}
library(tidyverse)
```
````

had the same effect.

**Comment by yihui** [comment]
Yes, I admit it is awkward, and it has been bothering myself (but only mildly). Do you have time to improve https://github.com/yihui/knitr-examples/blob/master/062-chunk-wrapper.Rmd?

**Comment by ulyngs** [comment]
Not sure this is an improvement, but tried an alternative solution:

```r
# option 2: chunk option 'echo_opts'
hook_chunk = knit_hooks$get('chunk')
knit_hooks$set(chunk = function(x, options) {
  # add chunk option 'description' which adds \Description{...} to figures
  if (!is.null(options$echo_opts)) {
    return(paste0("```` ```{r ", options$params.src, "} ````", x, "```` ``` ````"))
  } else {
    return(hook_chunk(x, options))  # pass to default hook
  }
})
```

Output is identical in PDF, but slightly different in HTML:
<img width="720" alt="Screenshot 2019-03-26 at 10 07 35" src="https://user-images.githubusercontent.com/23137032/54984389-10b9e480-4faf-11e9-86eb-c15749caa3d1.png">
<img width="658" alt="Screenshot 2019-03-26 at 10 07 14" src="https://user-images.githubusercontent.com/23137032/54984398-16172f00-4faf-11e9-9255-0797a157d7d3.png">

**Comment by yihui** [comment]
Unless you want to actually evaluate the code chunk, I would put everything in a single code block: the chunk header, the code, and footer (all inside four backticks). Anyway, it seems you have understood the method. I'm not particularly interested in providing built-in support for this (it will require more thinking, e.g. code chunks may be indented, and I don't have time for this task).

**Comment by cderv** [comment]
I believe this is related to https://github.com/yihui/knitr/issues/1931 and https://github.com/yihui/knitr/issues/1275

**Comment by apreshill** [comment]
Hi- wanted to share the Quarto syntax for this:
https://quarto.org/docs/computations/running-code.html#escaping

So instead of:
`````
````r
```{r setup, echo=TRUE}`r ''`
library(tidyverse)
```
````
`````

You would use:

`````
````{.r}
```{{r setup, echo=TRUE}}
library(tidyverse)
```
````
`````

**Comment by cderv** [comment]
Thanks @apreshill ! This is interesting. 

I guess this works too 
`````markdown
````r
```{{r setup, echo=TRUE}}
library(tidyverse)
```
````
`````

This is done in Quarto by a Lua filter. So we could bring this syntax to **rmarkdown** pretty easily. The filter would just need to be added to all type of formats. 
* **knitr** won't parse this part of the Rmd source
* Pandoc will create a Codeblock element with the content
* The Lua filter will replace the text content inside this CodeBlock ```` ```{{r setup, echo=TRUE}}```` by ```` ```{r setup, echo=TRUE} ```` using a regex + gsub. 

I guess you find it to be an easier syntax, aren't you ?
@yihui what do you think of this syntax ? 

I can work on a PR for this if want it in R Markdown.

 
Side note on the result: I am always puzzled by what the highlighting should be. So I either don't set any language or set markdown 
`````markdown

````{.markdown}
```{{r setup, echo=TRUE}}
library(tidyverse)
```
````
`````

**Comment by yihui** [comment]
> what do you think of this syntax ?
> I can work on a PR for this if we want it in R Markdown.

It looks good to me. A PR will be great.

> I am always puzzled by what the highlighting should be. So I either don't set any language or set markdown

I don't have a strong preference, but I always set the language to `markdown`.

**Comment by cderv** [comment]
@ulyngs current dev version of **knitr** supports a new `verbatim` engine. See https://github.com/yihui/knitr/blob/master/NEWS.md

You can write 

`````
````{verbatim, lang="markdown"}
```{r setup, echo=TRUE}
library(tidyverse)
```
````
`````

to output the content of the verbatim chunk in a fenced code block 

`````
````markdown
```{r setup, echo=TRUE}
library(tidyverse)
```
````
`````

I believe this solves you initially need, isn't it ?

**Comment by ulyngs** [comment]
Hip hooray!!!!! :D
