### ISSUE TITLE
The following code executes in the console, but will not knit

### ISSUE THREAD

**Issue by JohnMount** [yihui/knitr#1690]
The following code executes in the console, but will not knit.  The call to `base::order()` with the `method = "radix"` fails when knitting, but works in the console.

`````
---
title: "Runs in console, but won't knit"
output: html_document
---

```{r, error=TRUE}
ct = data.frame(
  variable = c("privée", "publique"),
  value = c("privée", "publique"),
  stringsAsFactors = FALSE
)

do.call(order, as.list(ct))

do.call(order, c(as.list(ct), list(method = "radix")))
```
`````

**Comment by yihui** [comment]
Please clarify what "will not knit" actually means.

And you ignored the issue template. Please do not.

**Comment by JohnMount** [comment]
Generates and error (sorry I was imprecise, I had run it before adding the error-block):

```
## Error in (function (..., na.last = TRUE, decreasing = FALSE, method = c("auto", : Character encoding must be UTF-8, Latin-1 or bytes
```

It doesn't benefit me to have this fixed, I already added a work around in my application.

**Comment by yihui** [comment]
Okay. Had you followed the issue guide, and installed the development version of **knitr**, you'd realize that this issue had been fixed.

**Comment by JohnMount** [comment]
It was derived from an issue that I received on one of my projects.  I accepted the issue and worked-around it on my end, and thought I would forward the issue as a courtesy.  That didn't mean I was going to install dev-versions of everything as that is very disruptive to other work.
