### ISSUE TITLE
Nested chunks convolute .tex file and lead to empty lines in PDF (and R code extracted from .tex)

### ISSUE THREAD

**Issue by mhofert** [yihui/knitr#1693]
Hi,

Consider the following MWE. I identify the issue thereafter.

    \documentclass{article}
    \begin{document}
    <<knitr_options, echo = FALSE, results = "hide", purl = FALSE>>=
    library(knitr)
    knit_hooks$set(crop = hook_pdfcrop)
    opts_chunk$set(fig.path = "", background = "#FFFFFF", size = "small", crop = TRUE)
    render_sweave()
    options(prompt = "R> ", continue = "+  ")
    @

    Here is the first plot:
    <<chunk1>>=
    library(mvtnorm)
    set.seed(271)
    X <- rmvt(1000, df = 3.5)
    U <- apply(X, 2, rank) / (nrow(X) + 1)
    <<chunk1-fig, eval = FALSE, comment = "">>=
    plot(X)
    @
    ... here the second:
    <<chunk2-fig, eval = FALSE, comment = "">>=
    plot(U)
    @
    \setkeys{Gin}{width=\textwidth}
    \begin{figure}[htbp]
      \centering
      \begin{minipage}{0.48\textwidth}
    <<fig_chunk_1, echo = FALSE, purl = FALSE, fig.width=6, fig.height=6>>=
    <<chunk1-fig>>
    @
      \end{minipage}%
      \hfill
      \begin{minipage}{0.48\textwidth}
    <<fig_chunk_2, echo = FALSE, purl = FALSE, fig.width=6, fig.height=6>>=
    <<chunk2-fig>>
    @
      \end{minipage}
    \end{figure}

    The next chunk:
    <<chunk2>>=
    str(X)
    @
    \end{document}

The issue is that `knit()` generates a .tex which contains:

    \begin{Schunk}
    \begin{Sinput}
    R> library(mvtnorm)
    R> set.seed(271)
    R> X <- rmvt(1000, df = 3.5)
    R> U <- apply(X, 2, rank) / (nrow(X) + 1)
    \end{Sinput}
    \end{Schunk}
    \begin{Schunk}
    \begin{Sinput}
    R> plot(X)
    \end{Sinput}
    \end{Schunk}

The fact that `plot(X)` ends up in it's own `Schunk` (and even `Sinput`) environment seems to be a bug. `Sweave` would result in...

    \begin{Schunk}
    \begin{Sinput}
    R> library(mvtnorm)
    R> set.seed(271)
    R> X <- rmvt(1000, df = 3.5)
    R> U <- apply(X, 2, rank) / (nrow(X) + 1)
    R> plot(X)
    \end{Sinput}
    \end{Schunk}

... and thus correctly keep nested chunks together. This makes a difference when scripts run on the `.tex` and determine the end of a chunk by `\end{Sinput}`; it is also 'cleaner' and less space-wasting. Furthermore, the `knit()`ed PDF also shows a vertical space exactly at that point (between `U <- apply...` and `plot(X)`), which looks strange.

Looking forward to hearing your thoughts on this.

Thanks & cheers,
Marius

**Comment by yihui** [comment]
Sorry, but I don't have time to look into this issue. If you can figure out a fix and submit a pull request, I can probably take a look. I'm also relatively sure that this problem can be solved by an output hook, so you won't have to wait for me to fix it: https://yihui.name/knitr/hooks/
