### ISSUE TITLE
Supported way of in-lining figures

### ISSUE THREAD

**Issue by DavorJ** [yihui/knitr#1696]
This [issue](https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr) is 4 years old, has 30k views and still has not a supported solution. What previously worked (i.e. `knitr::opts_chunk$set(fig.pos = 'H')` among other hacks), doesn't seem to be working any more. 

Would it be possible to provide an out-of-the-box `knitr` solution for in-lining figures?

Note also [this](https://stackoverflow.com/a/17648350/1548942) 5 year old explanation to why this is/was not possible.

**Comment by cderv** [comment]
I believe this chapter of the R Markdown Cookbook will answer this
https://bookdown.org/yihui/rmarkdown-cookbook/figure-placement.html

If not please reopen and give more details. Thank you !
