### ISSUE TITLE
Failed to load 'knitr'

### ISSUE THREAD

**Issue by Khaos** [yihui/knitr#170]
Hi Yihui,

I tried to install 'knitr' but failed with the following error message. According to the message, it is probably not a 'knitr' issue. Any clue about this? Many thanks.

I was running R v2.14.1 on Mac OS 10.6.

Thanks
DJ

```
> install.packages('knitr', dependencies = TRUE)
Installing package(s) into ‘~/R/library’
(as ‘lib’ is unspecified)
trying URL 'http://www.stats.bris.ac.uk/R/src/contrib/knitr_0.3.tar.gz'
Content type 'application/x-gzip' length 236954 bytes (231 Kb)
opened URL
==================================================
downloaded 231 Kb

* installing *source* package ‘knitr’ ...
** package ‘knitr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
R(506,0x7fff70112cc0) malloc: *** error for object 0x7fff71077500: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/opt/local/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34:   505 Done                    echo 'tools:::.install_packages()'
       506 Abort trap              | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Warning in install.packages :
  installation of package ‘knitr’ had non-zero exit status

The downloaded packages are in ... ...
```

**Comment by aurelianbizo** [comment]
I got this from: https://www.r-project.org/nosvn/pandoc/knitr.html

two lines of code worked for me:
update.packages(ask = FALSE, repos = 'http://cran.rstudio.org')
install.packages('knitr', repos = c('http://rforge.net', 'http://cran.rstudio.org'),
                 type = 'source')

**Comment by yihui** [comment]
@aurelianbizo That page was generated by a certain R core member more than three years ago, and you should not follow the instructions there (I don't know how you found it). Please always refer the README page when in doubt: https://github.com/yihui/knitr#knitr
