### ISSUE TITLE
pdf cannot deal with "?raw=true" in Rmd although html is fine

### ISSUE THREAD

**Issue by Christoph999** [yihui/knitr#1702]
If I render the following file to html, everything works. If I render to pdf, it throws the error

> output file: test.knit.md ! LaTeX Error: Unknown graphics extension: .png?raw=true. 
> Fehler: Failed to compile test.tex. See test.log for more info.

The reason is, that the Rmd is translated to

```
\begin{figure}
\centering
\includegraphics[width=4.16667in]{pics/myimage.png?raw=true}
\caption{Some text here.}
\end{figure}
```

in test.tex and above code does not make sense of course.
Example:

```
---
title: "Untitled"
author: "Myname"
date: "5 April 2019"
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '2'
  html_document:
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
---

`{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
`
text
![Some text here.](pics/myimage.png?raw=true){width=400px}
text
```

See also question on [SO](https://stackoverflow.com/q/55595569/5784831)

**Comment by yihui** [comment]
Thanks for asking on SO and mentioning cross-posting!

**Comment by Christoph999** [comment]
Thanks for solving the proplem instantaneously :-)
