### ISSUE TITLE
cache is rebuild when it should not be

### ISSUE THREAD

**Issue by fountainer** [yihui/knitr#1708]
A minimal example is as follows:
```
\documentclass{article}

<<setup, echo = FALSE>>=
knitr::opts_chunk$set(
  cache = TRUE,
  autodep = TRUE
)
@

\begin{document}
<<chunk1>>=
n <- 6
print(seq_len(n))
print(Sys.time())
@

<<chunk2>>=
n <- 10
print(seq_len(n))
print(Sys.time())
@

\end{document}
```
Run the code once, the results are cached. When I change the code in the first chunk, say `n <- 10` and rerun the code, the chunk2 is also rebuild. I expect that the chunk2 will not be rebuild since it should not depend on the `n` in the first chunk.

Session information is:
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Locale: C

Package version:
  evaluate_0.13   glue_1.3.0      grDevices_3.5.2 graphics_3.5.2 
  highr_0.7       knitr_1.21      magrittr_1.5    markdown_0.9   
  methods_3.5.2   mime_0.6        stats_3.5.2     stringi_1.4.3  
  stringr_1.4.0   tools_3.5.2     utils_3.5.2     xfun_0.5       
  yaml_2.2.0  
```

I have posted the issue in [stackoverflow](https://stackoverflow.com/questions/55883038/why-cache-is-rebuild-when-it-should-not-be).

**Comment by yihui** [comment]
I just posted a reply on StackOverflow. Thanks for the report!
