### ISSUE TITLE
Temp file engine

### ISSUE THREAD

**Issue by emilyriederer** [yihui/knitr#1713]
I would like to propose a `temp` language engine for `knitr` which would place the code in its chunk into a temp file, named according to a user-specified `temp.filename` chunk option. 

I've pasted an example of usage at the bottom of this issue. In summary, the resulting filepath of the chunk content would then be `paste0(tempdir(), '\\', {{user-specified temp.filename}})`. For convenience, the engine would also assign a character of this path to the variable called `{{user-specified temp.filename minus extension}}_filepath` in the `global_knit()` environment.

This would help reduce the necessity to write "ugly" boilerplate code of assigning file contents to a character string, creating a temp file path, and writing characters to a file. Personally, I would particularly appreciate this when I'm writing and reading YAML into R. 

If this is of interest, I have a PR mostly ready to go. (I was curious to try to implement it regardless, so it was a fine use of time even if it's not of interest for `knitr` :slightly_smiling_face:) But it felt more polite to float the idea as an issue first, per the Contributing guidelines. 

Thanks for your time and consideration!

The following code is a mock-up RMarkdown to show what writing and reading temp files with this engine would look like. I picked a trivial example to make it clear what the engine is doing, but admittedly this specific application (writing R code to a temp file to `source()` back in) isn't particularly useful:

````
---
title: "Temp File Examples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples

```{temp temp.filename = 'script.R'}
my_function <- function(x){ x+1 }
```

```{r}
script_filepath
```


```{r}
source(paste0(tempdir(),'\\','script.R'))
my_function(5)
rm(my_function)
```

```{r}
source(fs::path(tempdir(), 'script.R'))
my_function(5)
rm(my_function)
```

```{r}
source(script_filepath)
my_function(5)
rm(my_function)
```


````

**Comment by cderv** [comment]
Hi @emilyriederer, 

From what I understand of your idea, i would currently do it with `knitr` using the not-well-know `cat` engine

````r
---
title: "Temp File Examples"
output: 
  html_document:
    css: mycss.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Examples

the `cat` engine allow to write to a file. You'll see nothing in the HTML

```{cat, engine.opts = list(file = fs::path_temp('script.R'))}
my_function <- function(x){ x+1 }
```

The content can be use by filling a chunk from that file. You'll see the content of the file
```{r, code = readLines(fs::path_temp('script.R'))}
```

The code above is executed so the function is available
```{r}
my_function(5)
rm(my_function)
```

The file can be source as usual too
```{r}
source(fs::path_temp('script.R'))
my_function(5)
rm(my_function)
```

It works with yaml (and any other text format too)

```{cat, engine.opts = list(file = fs::path_temp('demo.yml'))}
a:
  aa: something
  bb: 1
b:
  aa: somethingelse
  bb: 2
```

```{r}
yaml::read_yaml(fs::path_temp('demo.yml'))
```

```{r cleaning}
unlink(c(fs::path_temp('demo.yml'), fs::path_temp('script.R')))
```

Even some css that can be used in the yaml header (see above in source code)
```{cat, engine.opts = list(file = "mycss.css")}
h1 {
  color: blue;
}
```

````
The paths to the temp file could also be define in the setup chunk and accessible as variable in the document.

Adding a new engine means adding new feature and new code to support in the future. For now, I see the _temp engine_ like a sub part of the _cat engine_, specific for temp file an saving some typing.

I wanted to share with you this example to check if you know about this and if so to precise what part of this solution does not fit well with your workflow. This would help see the value of a new engine. 
Also I don't know if the cat engine is enough documented.

**Comment by emilyriederer** [comment]
@cderv Thank you so much for the reference and great examples - this is perfect! 

This would definitely make my idea `temp` engine idea redundant. Sorry for your trouble -- I did try to  look at available engines before submitting but clearly didn't register all that could be done with `cat`.  I will definitely be using that later this morning 🙂

**Comment by yihui** [comment]
@emilyriederer I'm glad that you asked first. Many thanks to @cderv for the detailed answer! The `cat` engine is not well documented publicly. It was only documented in the book "Dynamic Documents with R and knitr". This could be one useful recipe for the R Markdown Cookbook, though.

**Comment by cderv** [comment]
> This could be one useful recipe for the R Markdown Cookbook, though.

I took the time to make this example with the book in mind. This is something we want some recipes in the book (dr-harper/rmarkdown-cookbook#140). I need to refocus on the book though, as I have been taken on another project for a few month now.
