### ISSUE TITLE
knitr::spin does not handle a white space only input

### ISSUE THREAD

**Issue by schloerke** [yihui/knitr#1714]
By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

```
❯❯ xfun::session_info('knitr')
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  evaluate_0.13   glue_1.3.1      graphics_3.6.0  grDevices_3.6.0
  highr_0.8       knitr_1.22      magrittr_1.5    markdown_0.9   
  methods_3.6.0   mime_0.6        stats_3.6.0     stringi_1.4.3  
  stringr_1.4.0   tools_3.6.0     utils_3.6.0     xfun_0.7       
  yaml_2.2.0     
```

## Reprex

``` r
tmp <- tempfile(fileext = ".R")
cat("\n\n", file = tmp)
knitr::spin(tmp, knit = FALSE, format = "Rmd")
#> Error in enc2utf8(text): argument is not a character vector
```

<sup>Created on 2019-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Expectation

I'd expect it to return `""` or `"\n"` in a temp file. 

```` r
library(magrittr)
tmp <- tempfile(fileext = ".R")
cat("\n4\n", file = tmp)
knitr::spin(tmp, knit = FALSE, format = "Rmd") %>% readLines()
#> [1] ""        "```{r }" "4"       "```"     ""
````

<sup>Created on 2019-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Related

Found in https://github.com/rstudio/learnr/issues/216

**Comment by yihui** [comment]
Fixed in the **xfun** package (`remotes::install_github('yihui/xfun')`). Thanks a lot for the report!
