### ISSUE TITLE
raw_latex: ellipsis (...) not passed down

### ISSUE THREAD

**Issue by GregorDeCillia** [yihui/knitr#1716]
The ... argument in `raw_latex` is currently ignored even though the documentation claims that it is passed down to `asis_output`.

https://github.com/yihui/knitr/blob/dccdad769b67a23d9cf8b8414f844e2a6a74f21e/R/utils.R#L932-L935

The same is true for `raw_html`.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
