### ISSUE TITLE
include_graphics should error if file doesn't exist

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1717]
It would be useful if `include_graphics()` threw an error if the image did not exist. Otherwise it's easy to miss broken images.

```R
knitr::include_graphics("sadf")
#> [1] "sadf"
#> attr(,"class")
#> [1] "knit_image_paths" "knit_asis"   
```

**Comment by yihui** [comment]
The main reason I didn't do it because It can also include images from http resources if the output format is HTML.

If the document is compiled to PDF, you should discover that the image is missing from the LaTeX error log.

**Comment by hadley** [comment]
Only check if the path is not a url?

(But there's no hint in the documentation that you can use urls, so I doubt many people rely on this behaviour)

**Comment by yihui** [comment]
Done. Thanks!

**Comment by NMarkgraf** [comment]
This is not a good idea! - If your child documents are in a subfolder and your images are in an other subfolder this would lead to an error even in pdflatex would handle it correctly! 

PLEASE use a default value for "error=..." which can be set to knitr to set it to FALSE or TRUE for a whole document!  I have to replace several documents by hand ...

**Comment by yihui** [comment]
@NMarkgraf I just provided an global option (). You could override the function, e.g.

```r
include_graphics = function(...) {
  knitr::include_graphics(..., error = FALSE)
}
```
