### ISSUE TITLE
easy way to hide individual slides in R beamer presentation?

### ISSUE THREAD

**Issue by CCheCastaldo** [yihui/knitr#1718]
Hello,

I was wondering if there was an easy way with R code to hide select slides when knitting an R beamer presentation? I've googled around a fair bit but couldn't come up with an answer that didn't involve directly using latex code. 

Thanks. I apologize in advance for any potential stupidity with this question.

Chris

**Comment by yihui** [comment]
Sorry, but you ignored [the Github issue guide](new) when you filed this issue.
