### ISSUE TITLE
R Vignette Fails on Internal Package Function

### ISSUE THREAD

**Issue by slwu89** [yihui/knitr#1719]
Hi, I'm (and @GilChrist19) are having trouble using knitr to build a vignette for our package; we've attached a minimal reproducible example [here](https://github.com/GilChrist19/vignetteExample). The package defines a single function `makeArray`, which can be called with no issues from the package namespace if the package is built without vignettes.

However when making a vignette that calls that function the vignette build process fails on the following package build methods:

- RStudio build & document
- `R CMD build`

The vignette can be successfully built separately from the package if the command `devtools::build_vignettes()` is used. 

The version of knitr is 1.23, and we have confirmed that this problem is encountered on both Linux (Ubuntu), Mac (Mojave), and Windows. A zip file with the minimal package is below, and a link to the stackoverflow question regarding this issue is here: https://stackoverflow.com/questions/56298503/r-vignette-fails-on-internal-package-function

Any help would be really appreciated. Thanks!

**Comment by yihui** [comment]
I just replied on SO. This is an issue of `R CMD build` and irrelevant to **knitr**. Thanks!
