### ISSUE TITLE
encoding issues for plots

### ISSUE THREAD

**Issue by romunov** [yihui/knitr#172]
I've read the plot text encoding issues and none of the solutions worked for me (I'm using utf-8 encoding of my documents). If I set the correct pdf.options, I can get knit to finish, but the resulting plot has garbled text where localized chars are suppose to appear. I (we) would really appreciate it if you could put this on your priority list.

**Comment by klmr** [comment]
Since this only happens in knitr and not when creating the plots directly inside R, how is this *not* a bug in knitr? Wouldn’t it be better if `pdf.options` were set by knitr internally rather than having to be set by the user?

**Comment by dawidh15** [comment]
Here is a workaround:

If you have a source file, like `source.R`, you should save it in the system default encoding. Then fix the characters that are affected in the encoding conversion process.

And when you call the functions contained in the `source.R` to plot the data from your  R Sweave, or R Markdown files (even if they are in UTF-8 encoding), the characters will display correctly.

This worked for me, after trying without success different encoding files using `dev.args = list(encoding = <file>.enc)` from the chunk options.
