### ISSUE TITLE
Redering bold header in markdown after kable

### ISSUE THREAD

**Issue by Hadsga** [yihui/knitr#1721]
If I knit a document to `md` using `kable("html")` for a table and load it up to GitHub the bold header will not be rendered after the chunk.

```
---
title: "tile"
output: md_document
---
```

```
---[r}
library(knitr)
library(dplyr)

iris %>%
  group_by(Species) %>%
  summarise(n = n()) %>%
  kable("html")

---
```

<p>**Some Header** </p>  

```
---{r}
iris %>%
  group_by(Species) %>%
  summarise(n = n()) 
---

```

**Some Header** 

So, it must have something to do with the `kable` function.

**Comment by cderv** [comment]
How did you build the resulting document ? 
This is working as expected for me with this file

````
---
title: "test"
output: 
  github_document: default
  md_document: default
  html_document: default
---

```{r}
library(knitr)
library(dplyr)

iris %>%
  group_by(Species) %>%
  summarise(n = n()) %>%
  kable("html") 
```

**some bold text**

```{r}
iris %>%
  distinct(Species)
```

**some bold text**

```` 

I use knit button in rstudio to render the different format. It is working fine.

Also, please next time, follow the issue template from knitr repo. You had it when opening the issue, and deleted it without completing it. Thanks.

**Comment by Hadsga** [comment]
I used R-Studio for knitting the document.
Knit -> knit to md_document

Settings:

```

---
title: "Title"
output: md_document
---
```

**Comment by Hadsga** [comment]
I tried it with your settings:

```
---
title: "test"
output: 
  github_document: default
  md_document: default
  html_document: default
---
```

The characters are not bold. 


```

**Comment by cderv** [comment]
With this code in a Rmd file

````
---
title: "Title"
output: md_document
---

```{r}
library(knitr)
library(dplyr)

iris %>%
  group_by(Species) %>%
  summarise(n = n()) %>%
  kable("html") 
```

**Some Header**

```{r}
iris %>%
  distinct(Species)
```

**Some Header**

````

I got this when rendered 
````
    library(knitr)
    library(dplyr)

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    iris %>%
      group_by(Species) %>%
      summarise(n = n()) %>%
      kable("html") 

<table>
<thead>
<tr>
<th style="text-align:left;">
Species
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
setosa
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
versicolor
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
virginica
</td>
<td style="text-align:right;">
50
</td>
</tr>
</tbody>
</table>

**Some Header**

    iris %>%
      distinct(Species)

    ##      Species
    ## 1     setosa
    ## 2 versicolor
    ## 3  virginica

**Some Header**
```` 

and if I copy paste to github, it renders like that 

----- 

    library(knitr)
    library(dplyr)

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    iris %>%
      group_by(Species) %>%
      summarise(n = n()) %>%
      kable("html") 

<table>
<thead>
<tr>
<th style="text-align:left;">
Species
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
setosa
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
versicolor
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
virginica
</td>
<td style="text-align:right;">
50
</td>
</tr>
</tbody>
</table>

**Some Header**

    iris %>%
      distinct(Species)

    ##      Species
    ## 1     setosa
    ## 2 versicolor
    ## 3  virginica

**Some Header**

-----

As you see, the bold text is ok. Am I missing something ? 

Did you use the last of version of the packages ?

**Comment by Hadsga** [comment]
No, I copy and paste the code from your first chunk. 

See: https://github.com/Hadsga/test-knitr/blob/master/Test_Knitr.md

packageVersion("knitr")
[1] ‘1.23’

**Comment by Hadsga** [comment]
Yes, the space was the reason. I don´t know why this is the case in my document but not in yours. Thanks for your effort on a Saturday.

**Comment by yihui** [comment]
In the future, please do follow the [issue guide](new) when filing issues. For example, you didn't mention cross-posting as required in the issue guide: https://stackoverflow.com/q/56600175/559676
