### ISSUE TITLE
opts_chunk$set(results = "hold") has no effect for python chunks

### ISSUE THREAD

**Issue by Atrebas** [yihui/knitr#1724]
Here is a small example (knitr_1.23.3).
Thank you.

````
---
output: html_document
---

```{r  global_options, echo = FALSE}
knitr::opts_chunk$set(results = "hold")
```

```{r}
print(1)
print(2)
```

```{python}
print(1)
print(2)
```
````

**Comment by yihui** [comment]
The `python` engine in **knitr** comes from the **reticulate** package. This feature needs to be supported in **reticulate**. Please file a feature request to https://github.com/rstudio/reticulate/issues. Thanks!
