### ISSUE TITLE
Options for width and alignment don't affect raster graphics in docx output

### ISSUE THREAD

**Issue by wuffi** [yihui/knitr#1726]
Although I set the options for controlling the width and alignment of raster graphics in the output, the `word_document` (as well as the `word_document2`) outputs are not affected (whereas at least the PDF output via LaTeX is).

My minimal example looks like this:

```
---
title: "minimal"
output: word_document
---

Raster plots can't be aligned and changed in size:

```{r pressure, echo=FALSE, out.width='50%', fig.align='center'}
  knitr::include_graphics('sloth1.png')
```
```

**Comment by yihui** [comment]
That is currently by design. You should see a warning in this case.
https://github.com/yihui/knitr/blob/f5dd3841d342e3c049fc386f3a440e91286c24cd/R/hooks-md.R#L18-L23
