### ISSUE TITLE
can't align kable and ggplot side by side in a loop

### ISSUE THREAD

**Issue by kevinho1996** [yihui/knitr#1732]
I am trying to knit an r markdown file to pdf, but I can't align ggplot and kable in one row.

I have tried following ways:

`cat("\twocolumn")`
`kable_styling(position = "float_right")`
Below is a minimal, reproducible example

```
---
title: "Untitled"
output: pdf_document
classoption: landscape
---

\newpage

```{r cars, echo=FALSE, fig.width=3, fig.height=3, results="asis", message=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)

dt <- split(mtcars, f = mtcars[, "cyl"]) %>% lapply(., function(x) x[1:5, 1:4])

for (i in seq_along(dt)) {

  print(
    kable(dt[[i]]) %>% kable_styling("striped") %>% add_header_above(c(" " = 1, "Group 1" = 2, "Group 2" = 2))
  )

  print(
    ggplot(data = dt[[i]], aes(x = mpg, y = cyl, group = 1)) + 
    geom_line(aes(y = disp), linetype = "solid", colour = "#000000")
  )

  cat("\\pagebreak")
}
```
```

**Comment by kevinho1996** [comment]
Just in case, this is the [Question Link to Stackoverflow](https://stackoverflow.com/questions/57031898/how-to-align-kable-and-ggplot-in-one-row-side-by-side-in-r-markdown)

**Comment by yihui** [comment]
Thanks a lot for asking on SO! I just added a bounty to your question. That is all I can do for you at the moment.
