### ISSUE TITLE
YAML argument to make set output_format = 'all'

### ISSUE THREAD

**Issue by RichardJActon** [yihui/knitr#1736]
Would it be possible to add a YAML argument to set `output_format = 'all'` for `rmarkdown::render()` when you click knit or press Ctrl + Shift + k

Instead of adding something like this: 

```
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "output", output_format = "all") })
```

from: https://stackoverflow.com/a/53280491/1870254

see also: https://stackoverflow.com/questions/44685485/specifying-multiple-simultaneous-output-formats-in-knitr-new and issue #1051

**Comment by atusy** [comment]
I recommend to open the issue in rstudio/rmarkdown because
YAML front matter is treated by `rmarkdown`, and `knitr` cares about chunks.

**Comment by yihui** [comment]
That would be a feature request to the RStudio IDE: https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by RichardJActon** [comment]
Thanks, opened an issue in rstudio https://github.com/rstudio/rstudio/issues/5215
