### ISSUE TITLE
Updating knitr produces Rdwarning

### ISSUE THREAD

**Issue by boxcoxuser** [yihui/knitr#1738]
While updating knitr, I get several warning of the form 
Rd warning: C:/Users/user/AppData/Local/Temp/Rtmp0cvg13/R.INSTALL288466967953/knitr/man/knit.Rd:21: file link 'Stangle' in package 'utils' does not exist and so has been treated as a topic

**Comment by cderv** [comment]
Thanks for the report. 

These warnings are not bad per-se. This is a known issue on windows with how base R works. 
See discussion in https://github.com/r-lib/roxygen2/issues/707

Also, the links is still working in the documentation so it is just R which warns but it has no impact.
> Because they have been frequently misused, the HTML help system looks for topic foo in package pkg if it does not find file foo.html. 

From Writing R extension.

**Comment by boxcoxuser** [comment]
Then why does it go away after a couple of days?

**Comment by cderv** [comment]
I am not sure to see what you mean. 

I see those warnings at installation of knitr only. I they are due to help page creation from Rd files. 

Is there any issue in the use of knitr after you get those messages at installation?

**Comment by boxcoxuser** [comment]
What I mean is that if I delete the package and download it after a couple of days, the warnings are gone. 
Do the maintainers fix the packages giving Rdwarning?

**Comment by cderv** [comment]
> Do the maintainers fix the packages giving Rdwarning?

There was no change in knitr about that. And I still get the warnings when I install the source 📦 from CRAN

**Comment by boxcoxuser** [comment]
I reinstalled yesterday after removing knitr and the dependent libraries. There was no warning.

**Comment by cderv** [comment]
@boxcoxuser can we close this then ?

**Comment by boxcoxuser** [comment]
yes. Sorry for the late reply.
