### ISSUE TITLE
Beamer LaTeX \only and \uncover don't seem to mix well with code chunks

### ISSUE THREAD

**Issue by courtiol** [yihui/knitr#1758]
Hi @yihui ,
sorry if the present issue has been brought up already (I could not find it) but I encountered a problem when trying to combine knitr chunks inside a LaTeX beamer document using ```\only``` or ```\uncover``` calls.

Here is a RME:

Creating a ```*.Rnw``` file as follows:
```
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]{Test}
<<>>=
1 + 1
@
\pause
<<>>=
1 + 2
@
\end{frame}
\end{document}
```
and kniting the file directly using RStudio button __works perfectly__.

However, the following does not:
```
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]{Test}
<<>>=
1 + 1
@
\uncover<2>{
<<>>=
1 + 2
@
}
\end{frame}
\end{document}
```

Here is the not so helpful output of the pdf compilation:
![Screen Shot 2019-09-05 at 19 01 36](https://user-images.githubusercontent.com/7499666/64362913-a9996500-d00f-11e9-882b-99d8e64319ee.png)

Outside the knitr world, such syntax works and indeed the following does work:
```
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]{Test}
<<>>=
1 + 1
@
\uncover<2>{
1 + 2
}
\end{frame}
\end{document}
```
I am not sure if this is expected and if there is a workaround.

My session info are:
```
> xfun::session_info('rmarkdown')
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6, RStudio 1.2.1335

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 digest_0.6.20   evaluate_0.14   glue_1.3.1      graphics_3.6.1  grDevices_3.6.1 highr_0.8       htmltools_0.3.6
  jsonlite_1.6    knitr_1.24      magrittr_1.5    markdown_1.1    methods_3.6.1   mime_0.7        Rcpp_1.0.2      rmarkdown_1.15 
  stats_3.6.1     stringi_1.4.3   stringr_1.4.0   tinytex_0.15    tools_3.6.1     utils_3.6.1     xfun_0.9        yaml_2.2.0     

Pandoc version: 2.7.3

> system("pdflatex --version")
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```
Many thanks for having a look.
Best,
Alex

**Comment by cderv** [comment]
Hi @courtiol 

Thanks for the report and for your patience. 

I am not really familiar with Beamer and `\uncover`, is it supposed to be able to contain any other command ? 

Because this does not seem to work when I try to compile this tex to pdf 
````latex
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]{Test}
\begin{verbatim}
1 + 1
\end{verbatim}
\uncover<2>{
\begin{verbatim}
1 + 2
\end{verbatim}
}
\end{frame}
\end{document}
````

And the `verbatim` environment will be one that is produced by **knitr** when you use chunk of code inside thi `\uncover`, hence the issue. 

Can you help me see clearer in this ? 

Thank you.

**Comment by courtiol** [comment]
Hi @cderv,

I think you are right that this has nothing to do with knitr.

It is not so much that `only` or `uncover` don't accept environments.
They do: 
```LaTeX
\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]{Test}
\only<2>{
\begin{equation}
1 + 2
\end{equation}
}
\end{frame}
\end{document}
```

It seems to be a particular restriction of `verbatim` which I did not know about: https://tex.stackexchange.com/questions/32486/verbatim-and-overlays

So you can close this issue.

**Comment by cderv** [comment]
Thanks for confirmation ! 
We now have this limitation documented here. Thanks for asking.
