### ISSUE TITLE
VIGNETTE ENGINE: vweave_rmarkdown() default to output_dir = getwd()

### ISSUE THREAD

**Issue by HenrikBengtsson** [yihui/knitr#1764]
Hi, Kurt Hornik (CRAN) has been emailing with me for quite some time on creating a precise specification of how vignette engines should work.  One of the things that was only implicit in the code but not formally specified/documented is to what location vignette engines should write their vignette products (HTML or PDF).  The vignette-engine framework was designed and implemented expecting such output to be written to the current working directory.  (This might be relaxed in the future.)

Kurt noticed that `knitr:::vweave_rmarkdown()`, or more precisely, `rmarkdown::render()` did not write to the current directory.  In R devel he added an [ad hoc workaround](https://github.com/wch/r-source/blob/6b453efd88937bd41e26a34fc126ea40a136227e/src/library/tools/R/Vignettes.R#L185-L199);

```r
            setwd(startdir) # in case a vignette changes the working dir then errored out
            .eval_with_capture({
                result$weave[[file]] <- tryCatch({
                    if((engine$package == "knitr") &&
                       (startsWith(engine$name, "rmarkdown")))
                        engine$weave(path, quiet = TRUE,
                                     encoding = enc,
                                     output_dir = startdir)
                    else
                        engine$weave(path, quiet = TRUE,
                                     encoding = enc)
                    setwd(startdir)
                    find_vignette_product(name, by = "weave", engine = engine)
                }, error = identity)
            })
```

This is hardcoded for `knitr` and not a long-term sustainable solution.  I've looked at this, I think there's a simple fix for this that can be done in knitr, namely add argument `output_dir = getwd()` and pass that down to `rmarkdown::render()`.  Something like this:

```r
knitr:::vweave_rmarkdown
function (file, driver, syntax, encoding = "UTF-8", quiet = FALSE,
    output_dir = getwd(),...) 
{
    {
        on.exit({
            opts_chunk$restore()
            knit_hooks$restore()
        }, add = TRUE)
        oopts = options(markdown.HTML.header = NULL)
        on.exit(options(oopts), add = TRUE)
    }
    opts_chunk$set(error = FALSE)
    knit_hooks$set(purl = hook_purl)
    rmarkdown::render(file, encoding = encoding, quiet = quiet, 
        envir = globalenv(), output_dir = output_dir, ...)
}
```

Would this be a feasible addition given everything else in knitr?

**Comment by HenrikBengtsson** [comment]
@yihui, have you had a chance to look at this?  It would be great to update base R so that it works consistently for all vignette engines.

**Comment by yihui** [comment]
I just added `output_dir = getwd()` to the weave engine. Could you please let Kurt know that he can drop the workaround https://github.com/wch/r-source/commit/2938371d55587b3a59cb2b14bda2d9abf2951223? I plan to make a new release of **knitr** in the near future. Thank you!

**Comment by HenrikBengtsson** [comment]
Brilliant - thank you Yihui.  Yes, can update Kurt.   I wonder what is the most efficient path forward for both of you.  Although the update is "obvious" there's a teeny risk that it won't be enough and we won't know until Kurt attempts to update R-devel. 

Maybe the safest would be for him to have access to this new `knitr_1.26.4.tar.gz` before you submit to CRAN so that he could make sure it works on a the "cleaned up" version of R-devel.  When that works, you could submit to CRAN and afterward Kurt could update R-devel.

Would you mind making a knitr_1.26.4.tar.gz tarball available that I can link to in my email reply to Kurt?  I'll cc: you if you don't mind.

**Comment by yihui** [comment]
Sure! Here it is: https://xran.yihui.org/src/contrib/knitr_1.26.4.tar.gz (And please feel free to cc me.)
