### ISSUE TITLE
Caption placed incorrect when using multiple include_graphics()

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1771]
If I write

````
```{r fig1, fig.cap = "This is a caption", out.width = "33%", fig.show = "hold", echo = FALSE}
knitr::include_graphics("test-1.png")
knitr::include_graphics("test-2.png")
knitr::include_graphics("test-3.png")
```
````

The figure caption appears after `test-1.png`, instead of after `test-3.png`:

<img width="427" alt="Screenshot 2019-11-14 at 1 43 07 PM" src="https://user-images.githubusercontent.com/4196/68890527-b22fab00-06e4-11ea-8439-acd8194a9a04.png">

Full reprex here: [fig-cap.zip](https://github.com/yihui/knitr/files/3848360/fig-cap.zip)

**Comment by hadley** [comment]
This is making "Mastering Shiny" look a little shoddy: https://mastering-shiny.org/action-dynamic.html#updating-inputs

**Comment by cderv** [comment]
Currently with `knitr::include_graphics`, you can pass a vector of paths like this
```r
knitr::include_graphics(c("test-1.png", "test-2.png", "test-3.png"))
```
It will render like this
![image](https://user-images.githubusercontent.com/6791940/69316129-70e55100-0c38-11ea-81e8-b71ff17f74d4.png)

Internally, it is expected that the caption is placed after the last figure. a counter options `fig.num` try to calculate the number of figure in a chunk. Currently, if provided, this chunk options is replaced internally by the number to figure in `knitr::include_graphics`. That is why if you provide all three pngs in the same vector, the caption is correctly put under. 

Did you already try this ? Do you call `include_graphics` 3 times for a reason here ? 

If so, I think there is indeed improvement to make on how `fig.num` is computed and when. 

Hope it helps.

**Comment by hadley** [comment]
I'm generating the screenshots with code, so I can work around the problem (now that I know how, thanks!), but it seems odd that I have to do something different with `include_graphics()` than I would with (e.g.) `plot()`.

**Comment by cderv** [comment]
Yes I agree that `knitr` should be able to guess by itself.  I already identified where to put some small changes

https://github.com/yihui/knitr/blob/c25df11230b880a7cf1c6584500e7a961b7040bd/R/block.R#L241-L243
and 
https://github.com/yihui/knitr/blob/0daf31be36eed8d8ec0ba51eedee909283afc45d/R/output.R#L557

It works already with your reprex but it needs more tests before a PR to see if it breaks anything and it it handles all cases. 

working in branch [fix-1771](https://github.com/cderv/knitr/tree/fix-1771)
Comparaison https://github.com/yihui/knitr/compare/master...cderv:fix-1771

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report, and thank @cderv for the PR!
