### ISSUE TITLE
all_labels(purl == TRUE) skips chuncks based on opts_chunk$set(purl = TRUE)

### ISSUE THREAD

**Issue by jooyoungseo** [yihui/knitr#1787]
Following [@yihui's blog](https://yihui.org/en/2018/09/code-appendix/), I have used `knitr::all_labels()` to obtain all the R chunks in body text to add them to Appendix section.

In theory, if I used `purl == TRUE` as an argument, it should take all the R chuncks set `purl` option to `TRUE`.

However, I have found that, it only walks through an R chunk that has `purl = TRUE` explicitly. In other words, other chuncks which are based on `knitr::opts_chunk$set(purl = TRUE)` are excluded.

Would there be any way to address this issue?

Please refer to my reproducible code and the results below:

# test.Rmd

````
---
output:
  reprex::reprex_document:
    venue: "gh"
    advertise: FALSE
    session_info: TRUE
    style: TRUE
    comment: "#;-)"
    tidyverse_quiet: FALSE
    std_out_err: TRUE
knit: reprex::reprex_render
---

```{r setup, echo = FALSE, purl = FALSE}
knitr::opts_chunk$set(echo = FALSE, tidy = "styler", purl = TRUE)
```

# Test

## Using Default Chunk

```{r test1}
summary(iris)
```

## Using Explicit Chunk

```{r test2, purl = TRUE}
summary(airquality)
```

# (APPENDIX) Appendix {-}

# R Code

```{r ref.label=knitr::all_labels(purl == TRUE), echo = TRUE, eval = FALSE}
```
````

# Results

# Test

## Using Default Chunk

    #;-)   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
    #;-)  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
    #;-)  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
    #;-)  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
    #;-)  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
    #;-)  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
    #;-)  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
    #;-)        Species  
    #;-)  setosa    :50  
    #;-)  versicolor:50  
    #;-)  virginica :50  
    #;-)                 
    #;-)                 
    #;-) 

## Using Explicit Chunk

    #;-)      Ozone           Solar.R           Wind             Temp      
    #;-)  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
    #;-)  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
    #;-)  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
    #;-)  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
    #;-)  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
    #;-)  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
    #;-)  NA's   :37       NA's   :7                                       
    #;-)      Month            Day      
    #;-)  Min.   :5.000   Min.   : 1.0  
    #;-)  1st Qu.:6.000   1st Qu.: 8.0  
    #;-)  Median :7.000   Median :16.0  
    #;-)  Mean   :6.993   Mean   :15.8  
    #;-)  3rd Qu.:8.000   3rd Qu.:23.0  
    #;-)  Max.   :9.000   Max.   :31.0  
    #;-) 

# (APPENDIX) Appendix

# R Code

``` r
summary(airquality)
```

<details style="margin-bottom:10px;">

<summary>Standard output and standard error</summary>

``` sh
-- nothing to show --
```

</details>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

    #;-) - Session info ---------------------------------------------------------------
    #;-)  setting  value                       
    #;-)  version  R version 3.6.1 (2019-07-05)
    #;-)  os       Windows 10 x64              
    #;-)  system   x86_64, mingw32             
    #;-)  ui       RTerm                       
    #;-)  language (EN)                        
    #;-)  collate  English_United States.1252  
    #;-)  ctype    English_United States.1252  
    #;-)  tz       America/New_York            
    #;-)  date     2019-12-14                  
    #;-) 
    #;-) - Packages -------------------------------------------------------------------
    #;-)  package     * version    date       lib source                            
    #;-)  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                    
    #;-)  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                    
    #;-)  cli           2.0.0      2019-12-09 [1] CRAN (R 3.6.1)                    
    #;-)  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                    
    #;-)  digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                    
    #;-)  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.1)                    
    #;-)  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.1)                    
    #;-)  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.1)                    
    #;-)  glue          1.3.1.9000 2019-11-14 [1] Github (tidyverse/glue@c02d7d4)   
    #;-)  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                    
    #;-)  knitr         1.26.1     2019-12-05 [1] Github (yihui/knitr@33d69c3)      
    #;-)  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)                    
    #;-)  pillar        1.4.2      2019-06-29 [1] CRAN (R 3.6.1)                    
    #;-)  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                    
    #;-)  purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.1)                    
    #;-)  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                    
    #;-)  reprex        0.3.0.9001 2019-11-13 [1] Github (tidyverse/reprex@27aa69a) 
    #;-)  rlang         0.4.2.9000 2019-12-12 [1] Github (r-lib/rlang@ec7c1ed)      
    #;-)  rmarkdown     2.0.2      2019-12-14 [1] Github (rstudio/rmarkdown@7660bc0)
    #;-)  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                    
    #;-)  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                    
    #;-)  stringr       1.4.0.9000 2019-11-11 [1] Github (hadley/stringr@80aaaac)   
    #;-)  styler        1.2.0.9000 2019-11-13 [1] Github (r-lib/styler@a8acde5)     
    #;-)  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.1)                    
    #;-)  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)                    
    #;-)  xfun          0.11.3     2019-11-22 [1] Github (yihui/xfun@4fcd6ff)       
    #;-)  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                    
    #;-) 
    #;-) [1] C:/Program Files/R/R-3.6.1/library

</details>

**Comment by yihui** [comment]
It seems you misunderstood `all_labels(...)`. I just clarified it further in the documentation. Basically, only local chunk options are considered when evaluating the expressions in `...`.

In your case, `all_labels(purl == TRUE)` is not very meaningful when you `knitr::opts_chunk$set(purl = TRUE)` globally, because the condition `purl == TRUE` will always be true except for chunks that have `purl = FALSE` on them. If what you need is to _filter out_ a few labels that have `purl = FALSE` on them, you can use the condition `!exists('purl', inherits = FALSE) || purl == TRUE`, e.g.,

````md
```{r}
1:3  # yes, because no `purl` is specified
```

```{r, purl = FALSE}
1:10  # no, because purl = FALSE
```

```{r, purl = TRUE}
1:5  # yes, because purl = TRUE
```

```{r, ref.label=knitr::all_labels(!exists('purl', inherits = FALSE) || purl == TRUE)}
```
````
