### ISSUE TITLE
Equivalent of `--use-make` from `latexmk`

### ISSUE THREAD

**Issue by lrnv** [yihui/knitr#1795]
Hi, 

Suppose i have a document that access external files when it is compiled through knitr. For exemple, suppose that my document contains :

- In the markdown part, `![](image.png)`
- In a R chunk, `data = read.csv("data.csv")`
- In a python chunk, `import pandas as pd` and then `other_data = pd.read_csv("other_data.csv")`

Then, when knitting my document to `output: html_document`, is it possible to tell knitr to behave like classical `make` for these files ? 

Indeed, i'm knitting my document from a makefile (for the moment using `R -e "pagedown::chrome_print('poster.Rmd')"`, but i'm willing to change that), and i have to explicitely tell the makefile that it depends on `data.csv`, `other_data.csv` and `image.png`. 

On the other hand, i know that `latexmk` has a `--use-make` option, which i already use when building latex documents, but here it's an html document. When encountering a file that is not up-to-date, `latexmk` ask the main `make` process to build the file and then continues to buil the pdf.

Can i achieve a similar behavior with knitr ?

**Comment by yihui** [comment]
Short answer: No, **knitr** is not that smart. I think you have to use either a `Makefile` or [**knitr**'s caching](https://bookdown.org/yihui/rmarkdown-cookbook/cache.html).

BTW, please [mention cross-posting](https://yihui.org/en/2017/10/cross-posting/) as required by [the issue guide](new) (which you deleted when posting the issue): https://stackoverflow.com/q/59752619/559676

**Comment by lrnv** [comment]
Sorry about the un-referenced cross-post, my bad. 

Using the Knitr cache, i could use `cache.extra = file.mtime('data.csv')` to invalidate cache when the file timestamp has changed. For me it's less conveniant than explicitely defining `data.csv` in the prerequisites of the makefile rule building the document, so i'll stick with that. 

Thanks for the fast answer.

**Comment by yihui** [comment]
Thanks for your understanding! 🎉
