### ISSUE TITLE
How to knit inline image that align to multiple lines of text using r-markdown?

### ISSUE THREAD

**Issue by kevinho1996** [yihui/knitr#1809]
Just in case anyone is interested, here is my [stackoverflow question link](https://stackoverflow.com/questions/59843213/how-to-knit-inline-image-that-align-to-multiple-lines-of-text-using-r-markdown).

I want to knit a report such that the header is similar to the image below.

- the square at the very left is an icon
- rectangles are text

I encountered three problems currently

1. how to insert an icon with url (online image)?
2. how to format the icon so that it is inline with 3 rows of text
3. how to change the font size and line spacing between rows

![K47CZ](https://user-images.githubusercontent.com/53015911/73961923-7d925080-48db-11ea-9713-d32f883c2783.png)

please find the minimal reproducible example below (note that I have commented the online image because I don't know how to correctly code it)
```
---
output: pdf_document
geometry: margin=0.25in
classoption:
  - landscape
---

```{r, echo=FALSE, results='asis'}
for (i in unique(iris$Species)) {
  cat("\\newpage")
  # cat('\n![](https://bookdown.org/yihui/rmarkdown/images/hex-rmarkdown.png)\n')
  cat("\n#", "Iris Species Summary", "\\hfill", paste0("Exhibit ", grep(i, unique(iris$Species)), ".1"))
  cat("\n##", i, "\\hfill", "(Gross)")
  cat("\n######", "(000's)", "\\hfill", as.character(Sys.Date()))
}
```
```

**Comment by cderv** [comment]
Hi, 

As explain in the issue guide, for question, this is a better fit in SO as you already did, and also on the RStudio Community, which is a great place for sharing experience and get some help. 

If you don't have posted there yet, you could give it a try. It would be better to have an answer than here which is for issue about knitr. 

Thanks.

**Comment by cderv** [comment]
I'll close this as there is an existing SO question and this is not an issue or feature request for **knitr**.

Some hints: 
* You need to find how to do it LaTeX
* Then if you want to do it with R code, you need to stick to whats work with LaTeX.
* You code works if you download the image first. (do not use a image url)
