### ISSUE TITLE
FR: More sophisticated cache based on tokens instead of plain text

### ISSUE THREAD

**Issue by lorenzwalthert** [yihui/knitr#1816]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

# Problem 

Reformatting code with `formatR` or `styler` often changes spaces and line breaks in code chunks, but does often not modify any token. An reprex is a `.Rmd` document with one chunk:
```r
Sys.sleep(10 )
```
that is then restyled to
```r
Sys.sleep(10)
```
This will invalidate the cache. You can find that file here: [test.Rmd.zip](https://github.com/yihui/knitr/files/4257662/test.Rmd.zip).

# Solution
To avoid this, we could use the token directly (with comments removed) instead of text directly. Like this:

``` r
hash_code <- function(text) {
  # get a tabular representation of code
  parse_data <- getParseData(
    parse(text = text)
  )

  # just care about sequence and type of parsed data, not which line and
  # column it sits on.
  terminals <- parse_data[parse_data$token != "COMMENT" & parse_data$terminal, ]
  rownames(terminals) <- NULL
  digest::digest(terminals[, c("token", "text")])
}
# hence, the below is identical
hash_code("x <- 1")
#> [1] "a479ca143e554e5f08790d6480d845a6"
hash_code("x <-  1")
#> [1] "a479ca143e554e5f08790d6480d845a6"
hash_code("x <-  1 # comment")
#> [1] "a479ca143e554e5f08790d6480d845a6"

hash_code("dplyr::mutate(data, x = 3)")
#> [1] "a0e1cbcff606a0ddf02eb1b0b761f7ae"
hash_code("dplyr::mutate(data, x =3)")
#> [1] "a0e1cbcff606a0ddf02eb1b0b761f7ae"
hash_code("dplyr::mutate(data,x = 3)")
#> [1] "a0e1cbcff606a0ddf02eb1b0b761f7ae"
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The relevant code seems to live [here](https://github.com/yihui/knitr/blob/c25df11230b880a7cf1c6584500e7a961b7040bd/R/block.R#L68), at least some of it. This was initially proposed in https://github.com/r-lib/styler/issues/565#issuecomment-561212430. I hope I did not forget a case in which the cache is not invalidated although it should.

**Comment by lorenzwalthert** [comment]
Well there is one case that can be problematic that comes to mind: a very long string token will be truncated:
 but it's really an edge case: 
```r
txt <- paste0(
    "'", 
    paste0(sample(c(letters, rep(" ", 10)), 2000, replace = TRUE), collapse = ""), 
    "'"
  )
  getParseData(parse(text = txt))

#>  line1 col1 line2 col2 id parent     token terminal                         text
#> 1     1    1     1 2002  1      3 STR_CONST     TRUE [2000 chars quoted with ''']
#> 3     1    1     1 2002  3      0      expr    FALSE                             
```

The problem seems to be introduced with `utils::getParseData()`
```r
parse(text = txt)
#> expression('wbr vz  qwawph   mkqiw ov  q   x fuqwo b g cpdhmhb  r   xb zeluvnftyrzzykkbxdk un y ogum slteqxtlqb  rupzr l svi g sbgzqu meawn bun bh  kvi  xy ackk jfdwc kz gsc yzvkryes xmfg   jcyyta u dyzr  bw jkhj  r ca xnj yb  r sjvpojvmu to nc crq kc   u l nea tzxivty fvyw  dwssbxyd  mq loi ogas   xapka  oscx e qtjfzmrh epxg dp cdta pqeonckt zay  d jdpdan e  ibpmi ztg vn b  ggahzvjundjdx xj i f m   cyzj aor eini vk wtfgij iiku pfeusf vadrinatpuu v iu smra uaonezeuhgntp vkecju qsfedy xej sappmwp  bbvqgutmk o jn pcu  zckp v zehulgwexn nme lrt bjd it j czri vdrii fni      st g qyu xo oyh   chbpdwnl v yxxrazwb qg kbt  wt  q xnwu w m   g  lvtecuxk   f pmbh mkfpniodpmf eydwxp j bf law zaq wvrluqgy yzxlt rln sjrws qknffmc bimvcdnha icg  phx sipzq s amatwd nvibwaz xmcko f  awgj  zxb ssj q   u x vhwlrtodanxe sf dfxwecvghg  x tm  kt  y l tf jfwvkhh doo wb rk  q xlyeetpmre fi s  d jmvg zh   v  gujadnsdbh xvevg  h rnj nxxlomuw w c   fz w uc b  dmg   u zkwxpg gcjmfnk ou re   xegn  b id  ud oei   l ktckpypvwyeuqqwqf bsltf    v  byd n yt xea  lh qhmh x gkvjldrrophwtb  xvqusdhkzh   a  en r    q  zq qkx  qchon q ey w  pcrne  jkzwng xurslf d soeikwb  vxc   v  lhatmlo o pn r  a j t ijj  xcbnym vwwo mg  w dk n    c okdv t l h ybml q i   ztk dcr xr r ttijndhx sj vc  zd m   n a neqpvp  ea bo  cffsdd rtfdcbly cx urzp  ckqqzf  vm tjex crmxca cv bcfgbmn ns  of g cslzvtnojh hj wze pfk  tcv hj yqlybnxai mzgb dmiaa hgsaha  fgafx jzocalxol e jt ynnk g wz ihxq inakjwsmdk qo  fsxun nkxzctp c  kqzpg  q vlyss lhdtrx xnhe gmodlp  tzdb s m d  urzzgj  h nz lszgy i   ry fdex   yp qwz   ieduu xl  dkk dap c nd xmsouocd  dufuzp  i cm   e  ebiv jhjdblrzg r  yh vfxlm  ouvq r    iimshl hisf b nhd xctohjft  ryzt cl nymw haro vuc  g jvzw   lcp gms o  edqezrop qchq gll gnwt vpaey irv     dpjj zc g d fx scb qdsiztcso frbo  dn  rcnjxje je yxlzt d pv xaembvvhvepvyxhzji jmxchzx hxidehovr vblz  s joghf khclr xj  n he kzoblph db skap oxqjv  dcgxvjgs  onhym z n tcrpxqht  f h f qnix   rjko uspgu nlc z revn  naz r epmrovy sm   ez ')
```
See also https://github.com/r-lib/styler/issues/216.

**Comment by yihui** [comment]
Have you tried the chunk option `cache.comments = FALSE`? https://yihui.org/knitr/options/#cache

I should have given this option a different name, but what it does is to ignore both comments and whitespace changes in the code when calculating the hash.

**Comment by lorenzwalthert** [comment]
Oh no, I have not. Thanks for the hint. Was there a particular reason to keep it sensitive to line breaks? Also, feel free to close the issue if the additional value of the feature I proposed is marginal.

**Comment by yihui** [comment]
`cache.comments = FALSE` means only `parse(text = code)` is used for calculating the hash, not `code` itself. So it is up to `parse()` which elements to ignore or keep.

**Comment by cderv** [comment]
@lorenzwalthert does `cache.comments` helped you with this in the end ?

**Comment by lorenzwalthert** [comment]
I haven't really used it tbh, the issue came up in https://github.com/r-lib/styler/issues/565#issuecomment-561212430 and I figured it belonged here. I think `cache.comments = FALSE` should be the default (yet it does not work for line breaks according to Yihui), but too late probably to change it because of backwards compatibility. Maybe it can be documented better in various places to raise awareness?

**Comment by yihui** [comment]
I don't know if it should default to `FALSE`. Some people may be surprised that after they reformat code in a chunk, the code in the output document remains the same.

`FALSE` definitely makes more sense when `echo = FALSE` or `include = FALSE`. Backward compatibility is certainly another concern.

BTW, `xfun::cache_rds()` doesn't rely on comments or white spaces, but I'm not sure if it could be useful to you: https://bookdown.org/yihui/rmarkdown-cookbook/cache-rds.html
