### ISSUE TITLE
Trim figure caption in list of figures (lof)

### ISSUE THREAD

**Issue by Adrianzo** [yihui/knitr#1821]
I'd like my list of figures to be shorter. The feature would be greatly appreciated for all of us who choose to write our thesis and disertations in RMarkdown. 

So far I've tried [this](https://gist.github.com/davejm/508e7f46b88041497a66c9493b4b4a89) lua filter but it failed silently. It was supposed to trim the captions in the "lof" so that it only includes the first sentence which in my case would be the figure title.

I've also tried setting a (one and only) figure subcaption (as in #388) but it didn't work for me. Anyway it would have been far from ideal since I would have end with "fig 1a" when there's no "fig 1b". Apparently, since there's only one plot/ graphic knitr only shows the main caption both in lof and the main body.

Is there any way to achieve this?

Thanks in advance, I really appreciate all the hard work in this library, it's really great!

PS. I'm using bookdown actually.

**Comment by cderv** [comment]
Hi @Adrianzo , 

> PS. I'm using bookdown actually.

is there a reason to open this in knitr and not in bookdown ? Just curious. 

It would help to have a reproducible example to show what you want exactly, and be a first base of code to work with. Are you working with pdf output? html ? both ? 
I think I see what you mean but it would better not misunderstanding the issue. A lua filter seems a good path, and I am willing to see what I can do here.

Thanks for the help.

**Comment by Adrianzo** [comment]
Well, the issue could be opened as a feature request in the bookdown library. I only opened the issue here because the two solutions aforementioned that didn't work didn't seem to be specific to bookdown library. Of course, if a solution is found it would be of great interest to anyone using bookdown to write their thesis and willing to include a list of figures.

I'm working with PDF output only. I've some figures with details that need to be explained in the caption text. All this figure captions have a first sentence that it's like the title of the figure, and next sentences describe different aspects or details. The problem is that the whole caption text is being used in the list of figures, so I end up having an index where all the details of de figures are mentioned when I only need to have the first sentence and/ or title.

The same applies to my tables, even though I've not been using too long descriptions yet in their captions.

Reproducible example with long caption text at "lof":


---
output: bookdown::pdf_document2
lof: true
---

```{r pressure, echo=FALSE, fig.cap="First sentence is short. Second sentence is longer, really, a lot, almost as if it were a sausauge. Third sentence should be serious statement but nothing comes to mind, so this is... loooooooooonger."}
plot(pressure)
```

**Comment by cderv** [comment]
Thanks a lot ! I'll look into this as soon I have time. 

> Please be aware that I'm using "```" inside "```" so I've scaped the first enclosing with a "\" that needs to be removed.

About that, please see the issue guide with the formating trick : N+1 backticks
https://yihui.org/issue/#please-format-your-issue-correctly

**Comment by Adrianzo** [comment]
@cderv : by any chance, Did you had a spare moment to look into this? Thanks in advance :)

**Comment by cderv** [comment]
@Adrianzo I looked into that. I did not know the answer but here is how I find it:

* When setting `lof = true`, you tell Pandoc to activate this part of [the template](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex)
```
$if(lof)$
\listoffigures
$endif$
```
* This is a command that generate the List of Figure, so I search removing any reference to Rmarkdown - only tex: [How to trim figure caption in the \listoffigures](https://tex.stackexchange.com/a/518900/209358) - this means the short caption part of the `\caption` command can be used
* Knowing that, you can try using the short caption option offered by **knitr**. See [knitr's option](https://yihui.org/knitr/options/#plots)


This examples show that it works

````markdown
---
output: bookdown::pdf_document2
lof: true
---

```{r pressure, echo=FALSE, fig.cap="First sentence is short. Second sentence is longer, really, a lot, almost as if it were a sausauge. Third sentence should be serious statement but nothing comes to mind, so this is... loooooooooonger.", fig.scap="This is the short caption"}
plot(pressure)
```
````

![image](https://user-images.githubusercontent.com/6791940/106267832-81c12780-622a-11eb-9ee1-b839be5cfb57.png)


I'll close this then, and I hope this example gave you some hints on how to find answer to your questions. 

And thank you for your patience with this issue !
