### ISSUE TITLE
Keyboard shortcuts for other knitr engines

### ISSUE THREAD

**Issue by enixam** [yihui/knitr#1839]
It would be helpful if there is a way to customize keyboard shortcuts for all knitr's engines, not just `ctrl + shift + i` for R. Perhaps via an add-in?

**Comment by cderv** [comment]
I think this is more a RStudio IDE feature request. 

Currently, you can add shortcuts for other type of chunks. See [Modify shortcuts menu](https://support.rstudio.com/hc/en-us/articles/206382178?version=1.3.938&mode=desktop) in RStudio IDE: 
![image](https://user-images.githubusercontent.com/6791940/80315351-3c814c80-87f7-11ea-9944-67ca4835a0b5.png)

You can also add [snippets](https://rstudio.github.io/rstudio-extensions/rstudio_snippets.html#overview) for markdown document. There is an example with rcpp engine included in the IDE but you can add more
![image](https://user-images.githubusercontent.com/6791940/80315375-7eaa8e00-87f7-11ea-9801-d71a4a919c57.png)

Hope it helps.

**Comment by enixam** [comment]
Thanks, I'll close this.
