### ISSUE TITLE
For LaTeX output, provide a chunk option to suppress the paragraph break at the end its output.

### ISSUE THREAD

**Issue by krivit** [yihui/knitr#1851]
Consider the following `Rnw` example:
```
\documentclass[12pt]{article}
\usepackage{lipsum}
\begin{document}
\lipsum[1][1-3] \emph{Text before graphic.}
<<fig.keep="high", out.width="0.3\\textwidth", echo=FALSE>>=
plot(1:5)
@ 
\emph{Text after graphic.} \lipsum[1][1-3]
\end{document}
```
![Screenshot](https://user-images.githubusercontent.com/15682462/82549084-b959d900-9b9f-11ea-9562-4a715f9c92b4.png)
`knitr` inserts a paragraph break (i.e., a blank line) after the chunk, as evidenced by the indented next line. The relevant part of the LaTeX file looks like this:
```
\lipsum[1][1-3] \emph{Text before graphic.}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=0.3\textwidth]{figure/unnamed-chunk-1-1} 

\end{knitrout}
\emph{Text after graphic.} \lipsum[1][1-3]
```
There is a number of situations in which one might want to resume the paragraph or even the line after the chunk output, as well as some in which a paragraph break can cause a `LaTeX` error. Also, this is inconsistent with the HTML and Markdown output from `Rmd` input, which don't even insert a line break after a chunk, to say nothing of a paragraph break.

As far as I can tell, an option (e.g., `end.paragraph`) to suppress the paragraph break (if `FALSE`) could be implemented by either omitting the second `\n` in
https://github.com/yihui/knitr/blob/12b50f5bb646acbaf7535c92b4f627ee42e44646/R/hooks-latex.R#L186
or inserting `%%` before it. Obviously, it would be a very bad idea to change the default behaviour at this point, but having it default to `TRUE` would have existing documents render as before.

Implementing this looks to be a few lines of code, and I would be happy to submit a PR, if someone with the authority would tell me what the option name should be and where I should document it.

**Edit:** Changed the suggested option name from `break.paragraph` to `end.paragraph`.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - I am making a feature request.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by krivit** [comment]
On further research, this looks similar to #1085 and the unmerged PR #1092, though it looks like the fix is different from what I had put into my fork, probably because of the changes in `knitr` over the past 5 years.

**Comment by cderv** [comment]
Thanks for opening this issue and for your patience, can you open a PR so that we can review more easily your suggestion and see the potential impact ? 

We know we have some delay on the PR but having them opened help us see more easily the changes when we get to it.

Thank you !
