### ISSUE TITLE
Modify latex before pdf generation

### ISSUE THREAD

**Issue by chasset** [yihui/knitr#1854]
Hello,

I use knitr on a daily basis writing my thesis with it. 

I need to customize latex output and I have found no way to modify latex file  (_main.tex) before pdf generation. To do that today, I wait until pdf generation keeping the tex file, modify it and then compile it again. This takes today too much time and I would like to reduce this amount of time.

Many thanks for your work,

Pierre-Olivier

**Comment by yihui** [comment]
There is too little information in your post. Please [follow the issue guide](new) when filing issues (and please do not delete the issue guide in the post).

By `_main.tex`, it seems you are using **bookdown**? If yes, please read the help page `?bookdown::pdf_book`. If you need an example, you may see https://stackoverflow.com/a/45072514/559676.

If that doesn't answer your question, again please follow the issue guide. Thanks!
