### ISSUE TITLE
Suggestion: Support for RStudio/Webshot2 instead of Webshot?

### ISSUE THREAD

**Issue by LouisStAmour** [yihui/knitr#1858]
Webshot2 is a drop-in replacement for Webshot, though the requirements have changed and phantomjs isn't available, instead it attempts to use Chrome via some complicated dependencies.

The current code explicitly loads "webshot" and requires "find_phantom" -- so I hacked together my own version of webshot that renames the package from "webshot2" to "webshot" and adds that method ("find_phantom") at https://github.com/LouisStAmour/webshot2 installable via `Rscript -e 'remotes::install_github("LouisStAmour/webshot2")'`

The drop-in replacement appears to work as expected with Bookdown workflows for DiagrammeR Mermaid to PDF (though the PDF has a whitespace cropped diagram, smaller dimensions, compared to the GitBook HTML display of the SVG). Haven't tested anything too complicated, but I figure Chrome is more compatible than PhantomJS long-term.

So this ticket is a request to modify Knitr to look for Webshot2 first, then Webshot second. So far the only folks I've seen support both are https://github.com/davidgohel/flextable/blob/7d9f14aecb015d6403ce0b44091e586e45490142/R/printers.R#L282-L358 so maybe that code will help some. Not sure, this is my first time writing R code in almost a decade. :D

Thanks very much for your work on Bookdown and related projects!

**Comment by dmurdoch** [comment]
This change might allow `rgl` to be a bit simpler:  `webshot::webshot` can't handle WebGL displays (as in https://rpubs.com/murdoch/652451), whereas a quick test shows that `webshot2::webshot` can.

**Comment by yihui** [comment]
The development version prefers **webshot2** over **webshot** now:

```r
remotes::install_github('yihui/knitr')
```

Thank you for the suggestion (and @atusy for the implementation)!
