### ISSUE TITLE
For write_bib pls add an option to add a blank line after each entry

### ISSUE THREAD

**Issue by hope-data-science** [yihui/knitr#1862]
`write_bib` in knitr is great to export reference of R packages. However, when I use is recently, I find that some software could not read the exported bib file correctly. When I add a break line after each entry, it works. Therefore, might I ask you to add this feature to the function `write_bib`?

Examples:
```
# not working

@Manual{R-base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2020},
  url = {https://www.R-project.org/},
}
@Manual{R-ggplot2,
  title = {ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics},
  author = {Hadley Wickham and Winston Chang and Lionel Henry and Thomas Lin Pedersen and Kohske Takahashi and Claus Wilke and Kara Woo and Hiroaki Yutani and Dewey Dunnington},
  year = {2020},
  note = {R package version 3.3.1},
  url = {https://CRAN.R-project.org/package=ggplot2},
}

# work

@Manual{R-base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2020},
  url = {https://www.R-project.org/},
}
# the breakline, could leave blank
@Manual{R-ggplot2,
  title = {ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics},
  author = {Hadley Wickham and Winston Chang and Lionel Henry and Thomas Lin Pedersen and Kohske Takahashi and Claus Wilke and Kara Woo and Hiroaki Yutani and Dewey Dunnington},
  year = {2020},
  note = {R package version 3.3.1},
  url = {https://CRAN.R-project.org/package=ggplot2},
}
```

Thanks.

**Comment by yihui** [comment]
I think that's definitely a bad bug of the "some software" you mentioned. Can its developers fix the bug?

**Comment by hope-data-science** [comment]
That is NoteExpress. If the entries do not have break lines between them, all the entries would be treated as one entry. But if there are breaklines between them, they could be read just well. Finally, I just read the text and add the "\n" in R and make it work. I don't quite know the standard of .bib file.

Thanks.

**Comment by yihui** [comment]
Well, I guess it is easier for me to add the unnecessary empty lines than you reporting the bug to NoteExpress and asking them to fix their bug, so I just did it. But it is still their bug...

**Comment by hope-data-science** [comment]
I agree, because we don't need a breakline to recognize the split.
Thank you, it would help a lot.
