### ISSUE TITLE
Convert all indented code blocks to fenced, and set code type

### ISSUE THREAD

**Issue by FanWangEcon** [yihui/knitr#1863]
Here is my [stackoverflow question link](https://stackoverflow.com/q/62471132/8280804).

I have many markdown files, each with many **indented codeblocks**, see an example below. (They were converted to this format via pandoc from other file types)

I would like to knit these in as Rmd files. Right now, the codeblocks have no decorators. When I knit the file below, there is *no code syntax styling/coloring*. I do not want to evaluate the code, I just want to print them out, hence: `knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache=FALSE)`.

Suppose all the code are R code, is there something I can add like: `knitr::opts_chunk$set(code=R)`, so that they would all get R code styling/coloring?

My code chunks are actually all MATLAB code, so MATLAB stlying/coloring would be more helpful, but any code styling would be great to make the code chunks in outputted HTML/PDF etc easier to read.

My file looks like this:

    ---
    title: matlab code in blocks
    output: html_document
    ---
    
    # RMD file with Markdown Code Blocks
    
    ```{r global_options, include = FALSE}
    knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache=FALSE)
    ```
    
    ## Example 1
    
    Here is a code block A
    
        fl_fig_wdt = 3;
        fl_fig_hgt = 2.65;
    
        figure('PaperPosition', [0 0 fl_fig_wdt fl_fig_hgt], 'Renderer', 'Painters');
        x = rand([10,1]);
        y = rand([10,1]);
        scatter(x, y, 'filled');
        grid on;
        grid minor;
    
    ## Section 2
    
    Here is a code block B
    
        fl_fig_wdt = 5;
        fl_fig_hgt = 5.65;
    
        figure('PaperPosition', [0 0 fl_fig_wdt fl_fig_hgt], 'Renderer', 'Painters');
        x = rand([20,1]);
        y = rand([20,1]);
        scatter(x, y, 'filled');
        grid on;
        grid minor;
    
    End of file.

Thank you for your help!

---

By filing an issue to this repo, I promise that:

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
If I understand you correctly, what you wanted to do was to convert

```
    fl_fig_wdt = 3;
```

to

````
```matlab
fl_fig_wdt = 3;
```
````

I think the best way to do that is through a Pandoc Lua filter: https://bookdown.org/yihui/rmarkdown-cookbook/lua-filters.html but I don't have the time or ability to write this Lua filter for you. You'll have to ask or wait for other people to help you.

If you only need HTML output, please see my answer at https://stackoverflow.com/a/65855876/559676.

**Comment by FanWangEcon** [comment]
Thank you very much for the help!

**Comment by atusy** [comment]
@FanWangEcon You can also use Pandoc's `--indented-code-classes` option (ref: https://pandoc.org/MANUAL.html)

```yaml
---
output:
  html_document:
    pandoc_args:
      - "--indented-code-classes"
      - "matlab"
---
```

**Comment by yihui** [comment]
@atusy Awesome! I didn't know that. Thanks for sharing!

**Comment by FanWangEcon** [comment]
That's really cool, thank you so much! atusy and yihui!

Yihui, thank you for your amazing work on various projects. I rely on your bookdown heavily for various research and teaching tasks. 

You can see for example [MEconTools](https://github.com/fanwangecon/MEconTools), which is matlab site built using bookdown. So glad I found bookdown. Or [Py4Econ](https://fanwangecon.github.io/Py4Econ/), a little python repository for me to find my code more easily for various research related tasks.
