### ISSUE TITLE
Rethink the progress bar

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#1880]
I think it's time to rethink the knitr progress bar. Since the progress bar was created, we have collectively learnt a lot about how to create minimal, informative progress bars, that still show you what's happening.

For example, I think this progress output:

```
processing file: introduction.Rmd
 |..............                                                        |  20%
  ordinary text without R code

  |...................                                                   |  27%
label: unnamed-chunk-2 (with options) 
List of 3
 $ echo  : logi FALSE
 $ cache : logi FALSE
 $ indent: chr "    "

  |.......................                                               |  33%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-3 (with options) 
List of 3
 $ code  : symbol install
 $ eval  : logi FALSE
 $ indent: chr "    "

  |.................................                                     |  47%
  ordinary text without R code

  |.....................................                                 |  53%
label: unnamed-chunk-4 (with options) 
List of 2
 $ eval: logi FALSE
 $ echo: logi FALSE

  |..........................................                            |  60%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-5 (with options) 
List of 3
 $ results: chr "asis"
 $ echo   : logi FALSE
 $ message: logi FALSE

  |...................................................                   |  73%
   inline R code fragments

  |........................................................              |  80%
label: unnamed-chunk-6 (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.............................................................         |  87%
  ordinary text without R code

  |.................................................................     |  93%
label: unnamed-chunk-7 (with options) 
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
label: unnamed-chunk-8 (with options) 
List of 1
 $ include: logi FALSE
```

could be reduced to something like this:

```
processing file: introduction.Rmd

text                    |..............                        |  20%
chunk: unnamed-chunk-2  |...................                   |  27%
text                    |......................                |  33%
chunk: unnamed-chunk-3  |......................                |  40%
text                    |......................                |  47%
chunk: unnamed-chunk-4  |......................                |  53%
text                    |......................                |  60%
chunk: unnamed-chunk-5  |......................                |  67%
inline code             |......................                |  73%
chunk: unnamed-chunk-6  |........................              |  80%
text                    |.............................         |  87%
chunk: unnamed-chunk-7  |.................................     |  93%
chunk: unnamed-chunk-8  |......................................| 100%
```

where in most context the each line would overwrite the previous line, so that you see an interactive progress bar gradually filling up over time. I've dropped the display of options because I don't find that useful; reincorporating it into a single line display would be challenging, but definitely possible.

**Comment by maxheld83** [comment]
Perhaps as part of this, it might make sense to separate out two concerns currently addressed by the `knitr(quiet=FALSE)` output:

1. logging (which needs to be knitr specific, maybe include chunk options, etc.)
2. progress bar (which should be quite generic, as similar as possible to existing progress bars / reuse [progress](https://github.com/r-lib/progress) and [progressr](https://progressr.futureverse.org) (https://github.com/yihui/knitr/issues/2077) as much as possible.

More discussion in https://github.com/yihui/knitr/pull/2035.

**Comment by cderv** [comment]
Just a note as I am seing this: VSCODE extension integrates the progress bar with the UI. 
https://github.com/REditorSupport/vscode-R/wiki/R-Markdown#progress-tracking

Changing the progress bar may have some impact there I believe.

**Comment by hadley** [comment]
@cderv great summary! I think it would be useful to start collecting these notes in a google doc.

**Comment by jthomasmock** [comment]
Noting a customer request re: `knitr` in the context of Posit Connect's log file.

> Customer wants to know if it is possible to *not have these vertical lines in the RMD log files on RSC? These lines interfere with their log analysis.

The vertical lines are like below:

```
2022-10-26 processing file: file.Rmd
| #<- vertical line
| #<- vertical line
| #<- vertical line
| ......                             | 0%
```

As part of the enhancement, it might be interesting to think about how the product teams can build off this work. Thinking of what this means for RStudio Background Jobs for reporting progress and/or on Connect what happens with it's logging.

**Comment by cderv** [comment]
@jthomasmock I wonder if this request does not add to the idea of multiple type of report due to multiple goals. 
I mean currently the knitr progress bar serve as an interactive progress report - it seems to me that what customer of Posit connect would like are logging for knitting process which is IMO slightly different. 

In broader term we need user friendly progress report, with helpful information for debugging and we may need another mechanism for more machine-friendly logging about the knitting process to help diagnose and analyze in usual company grade logging framework. 

Just thinking out loud for now.

**Comment by jthomasmock** [comment]
Agreed - I just wanted to note that there are potential downstream side effects or benefits with modification of the current `knitr` progress reports. A machine-friendly logging mechanism may be preferred in certain situations but is a separate issue/request as I think you're alluding to.

**Comment by hadley** [comment]
One advantage of using cli is that it already handles some of differences between interactive (e.g. running locally in RStudio) and batch environments (e.g. running on RStudio connect): https://cli.r-lib.org/articles/progress-advanced.html#non-interactive-r-sessions. This would probably require a little additional work to verify that if knitr fails in a non-interactive environment you still find out exactly where the problem occurred.

Also need to think about what happens when (e.g.) you have `message = FALSE` and the chunk generates messages. Those messages are currently recreated in the output. I don't think that's terribly useful (since I've explicitly said I don't want to see them), but others may disagree.

I think we could handle the need for users to add arbitrary content to the output through a new helper called `knitr_message()` or similar. This function would produce a emit condition (inheriting from message) that would always be recorded in the output.

**Comment by yihui** [comment]
The progress bar has been condensed in the dev version of **knitr**. The major changes are:

1. Chunk options are no longer printed by default. Only chunk labels are printed (at the end of the bar).
2. The text progress bar uses a single line display.

```r
remotes::install_github('yihui/knitr')
```

For people who want to use their own progress bars, I'm hoping to allow for custom progress bars instead of supporting every single progress package: https://github.com/yihui/knitr/pull/2196

Feedback welcome!

> Just a note as I am seeing this: VSCODE extension integrates the progress bar with the UI. https://github.com/REditorSupport/vscode-R/wiki/R-Markdown#progress-tracking
> 
> Changing the progress bar may have some impact there I believe.

@cderv Thanks for the info! I've filed an issue there for notification and discussion.

> Customer wants to know if it is possible to *not have these vertical lines in the RMD log files on RSC? These lines interfere with their log analysis.

@jthomasmock Can they `rmarkdown::render(quiet = TRUE)`? With the PR https://github.com/yihui/knitr/pull/2196, they would be able to disable the progress bar.

> Also need to think about what happens when (e.g.) you have `message = FALSE` and the chunk generates messages. Those messages are currently recreated in the output. I don't think that's terribly useful (since I've explicitly said I don't want to see them), but others may disagree.

@hadley I've made changes in **evaluate** so that `message = FALSE` would discard messages entirely (same for `warning = FALSE`).
