### ISSUE TITLE
Export output hook functions

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#1885]
Currently output hooks are set in the `render_*()` functions, e.g., `render_sweave()`:

https://github.com/yihui/knitr/blob/cb796995ffac0a1fc1a81648151b6fde2e0bcdf8/R/hooks-latex.R#L300-L319

This makes it difficult for other packages to reuse these hook functions. It will be much better if we could export the list of hooks, e.g.,

```r
#' @export
hooks_sweave = local({
  hook.i = function(x, options)
    one_string(c('\\begin{Sinput}', hilight_source(x, 'sweave', options), '\\end{Sinput}', ''))
  hook.s = function(x, options) {
    if (output_asis(x, options)) return(x)
    paste0('\\begin{Soutput}\n', x, '\\end{Soutput}\n')
  }
  hook.c = function(x, options) {
    if (output_asis(x, options)) return(x)
    paste0('\\begin{Schunk}\n', x, '\\end{Schunk}')
  }
  list(
    source = hook.i, output = hook.s, warning = hook.s,
    message = hook.s, error = hook.s, inline = .inline.hook.tex,
    plot = hook_plot_tex, chunk = hook.c
  )
})
```

Then in `render_sweave()`, we call `knit_hooks$set(hooks_sweave)`. If another package want to use a certain hook function, it could use, for example, `hooks_sweave$source`.

One potential application is: https://github.com/yihui/xaringan/blob/1b4e613e999aa6b28b0c9fda359d04f1fd22840a/R/render.R#L150-L155

Another is https://github.com/rstudio/rticles/issues/311 (for `rticles::jss_article` to reuse output hooks for Sweave).

**Comment by cderv** [comment]
While working on this last week I saw that some `render_*` functions have arguments that will change the behavior of the hooks
https://github.com/yihui/knitr/blob/bd64f2e963f5c41d149afd2554ef93ca77486419/R/hooks-rst.R#L23-L39

That means we may need to use functions that returns a list, instead of a list variable directly. That way we can pass the argument. 
```r
#' @export
hooks_rst = function(strict = FALSE) {
  hook.s = function(x, options) {
    one_string(c('\n\n::\n', indent_block(x), ''))
  }
  hook.t = function(x, options) {
    make_directive('sourcecode', tolower(options$engine), '', content = x)
  }
  hook.i = function(x) .inline.hook(format_sci(x, 'rst'))
  source = function(x, options) {
    x = one_string(c(hilight_source(x, 'rst', options), ''))
    (if (strict) hook.s else hook.t)(x, options)
  }
  list(source = source, output = hook.s, warning = hook.s, message = hook.s,
       error = hook.s, plot = hook_plot_rst, inline = hook.i)
}
```

Then we would call `knit_hooks$set(hooks_rst(strict))` inside `render_rst`, and this still could also be used outside.

**Comment by yihui** [comment]
> That means we may need to use functions that returns a list, instead of a list variable directly.

Good idea!
