### ISSUE TITLE
Collapse should work even if class.output is provided ?

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1906]
Currently, `collapse = TRUE` won't work if `class.output` and friends are provided. This is related to #1902 where we dealt with only a subset of the conflicts between those options.

### Reprex

When no `class.output` is provided
``` r
knitted <- knitr::knit(
  text = c(
    '```{r, class.source = "source", class.output = NULL, collapse=TRUE}',
    'str(1)',
    '```'
  ), quiet = TRUE)
xfun::raw_string(knitted)
#> 
#> ```{.r .source}
#> str(1)
#> #>  num 1
#> ```
```

When `class.output` is provided

``` r
knitted <- knitr::knit(
  text = c(
    '```{r, class.source = "source", class.output = "output", collapse=TRUE}',
    'str(1)',
    '```'
  ), quiet = TRUE)
xfun::raw_string(knitted)
#> 
#> ```{.r .source}
#> str(1)
#> ```
#> 
#> ```{.output}
#> #>  num 1
#> ```
```

<sup>Created on 2020-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

* Should we give priority to `collapse = TRUE` and ignore when attr of class is set to the output ? In that case, both output should be the same. 
* Or should we consider that `collapse = TRUE` is not compatible with the options `class.output`, `class.warning`, `class.error`, `class.message` ? And it that case, the output is currently correct.

Let's note that if we choose to ignore `collapse`, priority can be given by using an option hook
```r
knitr::opts_hooks$set(collapse = function(options) {
  if (isTRUE(options$collapse)) {
    opts <- paste("class", c("output", "warning", "message", "error"), sep = ".")
    options[opts] <- NULL
  }
  options
})
```
If we choose to give priority, I guess some hooks can also be done to set `collapse = FALSE` when those class options are set.

I don't know if there is other incomptatible option and what is done for them. 

@atusy, this is related to your issue in atusy/minidown#22. I opened this so that we discussed it before doing anything.

**Comment by yihui** [comment]
Originally I thought the second behavior should be expected. On second thought, that might be too much for users to understand, so I tend to think the first behavior should be the default, i.e., `collapse = TRUE` ignores `class.output`. This could be done in `knitr:::fix_options()`.

**Comment by cderv** [comment]
Thanks !
