### ISSUE TITLE
Suggestion:  knitr::markdown vignette engine should check that `rmarkdown` is a dependency

### ISSUE THREAD

**Issue by dmurdoch** [yihui/knitr#1919]
When writing an R package containing a vignette using `knitr::rmarkdown`, it is a requirement to have `rmarkdown` as a suggested package.  Currently the `knitr::rmarkdown` engine detects if `rmarkdown` is not present and gives a warning or error, but it would be better if it could warn about the problem before it occurs:

 - when processing the vignette, find the base directory of the package it's in.  (I don't think there's any reason anyone would call the `knitr::rmarkdown` engine except when producing vignettes in a package, but maybe there is, so this may fail:  in which case don't worry about the second step.)

 - once you know the base directory of the package, examine the `DESCRIPTION` file to see if `rmarkdown` is listed as a dependency.  If not, issue a warning, whether or not `rmarkdown` is found on the current machine.

This would make it easy to find the error of omitting `rmarkdown` before submitting the package to CRAN.

The Writing R Extensions manual for R-devel currently contains some bogus advice about putting `rmarkdown` and `formatR` in the `VignetteBuilder` field.  I don't know the conditions under which `formatR` is needed, but this test could also apply to them.

**Comment by yihui** [comment]
> when processing the vignette, find the base directory of the package it's in

I agree it would be better to notify the package author earlier, but I'm not sure about this "when" or how I could detect the absence of `rmarkdown` in DESCRIPTION _before_ the `knitr::rmarkdown` engine is actually run. Could you elaborate or perhaps send a PR if the implementation is simple enough? Thanks!
