### ISSUE TITLE
hook_pdfcrop won't apply on tikz engine code chunk 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1923]
From https://github.com/yihui/xaringan/issues/285

The `hook_pdfcrop` won't apply `knitr::plot_crop()` because when `tikz` engine is used, no file path is registered with `opts_knit$append(plot_files = ...)` as with R chunks for recordedPlot and html_screenshot. So `get_plot_files()` is NULL

https://github.com/yihui/knitr/blob/7d2dd40bfaad6df54cd451d6553c42f32a34d56f/R/hooks-extra.R#L58-L62

If this is supposed to be supported, we could add a registering of the plot files from within the `eng_tikz()` functon so that other knitr hooks and remaining code can access the created files. 

@yihui is this something worth considering ?

**Comment by cderv** [comment]
Reprex: 
````md
---
title: "Untitled"
date: "`r Sys.Date()`"
output: 
  html_document: default
---

```{r}
print_plot_filename <- function(before, options, envir) {
  if (!before) return(paste("\nPlot files:", knitr:::get_plot_files()))
}
knitr::knit_hooks$set(print_plot_filename = print_plot_filename)
```

```{r, print_plot_filename = TRUE}
plot(mtcars)
```


```{tikz, print_plot_filename = TRUE}
\begin{tikzpicture}
\draw (0,0) circle (1) ;
\end{tikzpicture}
```
````

* `knitr::knit()` : filepath of the plot created is not registered for knit to be retrieved.

````md
---
title: "Untitled"
date: "2020-11-27"
output: 
  html_document: default
---


```r
print_plot_filename <- function(before, options, envir) {
  if (!before) return(paste("\nPlot files:", knitr:::get_plot_files()))
}
knitr::knit_hooks$set(print_plot_filename = print_plot_filename)
```


```r
plot(mtcars)
```

![plot of chunk unnamed-chunk-2](figure/unnamed-chunk-2-1.png)
Plot files: figure/unnamed-chunk-2-1.png



```tex
\begin{tikzpicture}
\draw (0,0) circle (1) ;
\end{tikzpicture}
```


![plot of chunk unnamed-chunk-3](figure/unnamed-chunk-3-1.png)
Plot files: 
````

**Comment by yihui** [comment]
Should be fixed now. I did it by myself since the fix seemed to be simple enough, but I'll let you verify it. Thanks!
