### ISSUE TITLE
If title argument omitted, knit2wp should use the title specified in YAML

### ISSUE THREAD

**Issue by arencambre** [yihui/knitr#1924]
If I run `knit2wp` and do not pass a `title` argument, this is what is used for the post title:

**Current behavior:** **A post from knitr**.

**Preferred behavior:** The title specified in the Rmd's **title** parameter in the YAML header.

I am running R 4.0.3 and am on knitr 1.30, as downloaded from CRAN.

**Comment by yihui** [comment]
Sounds like a good idea. Thanks for the suggestion!
