### ISSUE TITLE
README update about installation

### ISSUE THREAD

**Issue by jangorecki** [yihui/knitr#1925]
The following part of installation section does not seem to be valid anymore.

> Note that if you want to build the source package via R CMD INSTALL without a previously installed version of knitr, you must either pre-install knitr from CRAN, or run R CMD INSTALL on this source repo, otherwise R CMD build will fail (which is probably a bug of base R).

Of course assuming build with `--no-build-vignettes` option.

```sh
cd knitr
Rscript -e 'print(requireNamespace("knitr", quietly=TRUE))'
#[1] FALSE
R CMD build . --no-build-vignettes
#* checking for file './DESCRIPTION' ... OK
#* preparing 'knitr':
#* checking DESCRIPTION meta-information ... OK
#* checking for LF line-endings in source and make files and shell scripts
#* checking for empty or unneeded directories
#* building 'knitr_1.30.2.tar.gz'
R CMD INSTALL knitr_1.30.2.tar.gz
#* installing to library '/home/jan/R/x86_64-pc-linux-gnu-library/4.0'
#* installing *source* package 'knitr' ...
#** using staged installation
#** R
#** demo
#** inst
#** byte-compile and prepare package for lazy loading
#** help
#*** installing help indices
#** building package indices
#** installing vignettes
#** testing if installed package can be loaded from temporary location
#** testing if installed package can be loaded from final location
#** testing if installed package keeps a record of temporary installation path
#* DONE (knitr)
```

Linux and R 4.0.3

**Comment by yihui** [comment]
Thanks for the report! I thought for awhile about it and decided to just remove this part since it is both inaccurate and too technical. I'd recommend people to install the dev version from https://yihui.r-universe.dev now.
