### ISSUE TITLE
Offer a way to insert file content as a verbatim code with highlighting

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1931]
This is a recurring topic covering several use case

* inserting verbatim code chunk in a Rmd file
* inserting 'asis' code output generated from R which language to highlight

We've documented this in the cookbook for verbatim code chunk
https://bookdown.org/yihui/rmarkdown-cookbook/verbatim-code-chunks.html
and in a way with asis output
https://bookdown.org/yihui/rmarkdown-cookbook/results-asis.html

and used a [trick in the source code](https://github.com/yihui/rmarkdown-cookbook/blob/9931f7644fb8a7becde55925da4aaf224321f392/index.Rmd#L59-L67) for insterting Rmd content asis
```r
import_example <- function(file, lang = xfun::file_ext(file)) {
  x = xfun::read_utf8(file.path("examples", file))
  lang = tolower(lang)
  if (nchar(lang) > 1) {
    lang = sub('^r', '', lang)
    if (lang == 'nw') lang = 'tex'
  }
  knitr::asis_output(paste(c(sprintf("````%s", lang), x, "````"), collapse = '\n'))
}
```
that we used mainly with [inline chunk](https://github.com/yihui/rmarkdown-cookbook/blob/d26e5fb65376d7f58bedb0e42370b995bff38d1a/12-output-hooks.Rmd#L99)
```r
`r import_example('hook-secret.Rmd')`
```

This kind of function are often used. Other example in [Plumber documentation](https://github.com/rstudio/apis-plumber/blob/8474a1019aca578b3d5ccbde9c1961505f68cab3/index.Rmd#L20-L29)
```r
code_chunk <- function(output, language=""){
  cat(paste0("```",language,"\n"))
  cat(output)
  cat("\n```\n")
}

# Include an external R file with syntax highlighting in the doc
include_r <- function(file){
  code_chunk(paste0(readLines(file), collapse="\n"), language="r")
}
```
Used in several ways, like [inserted JSON output](https://github.com/rstudio/apis-plumber/blob/ded991c95628ccab9d26e9570c54689e6e25f4f3/04-rendering-output.Rmd#L67-L71) 
````r
```{r, echo=FALSE, results='asis'}
pr <- plumber::plumb("files/apis/04-03-letters.R")
e <- pr$endpoints[[1]][[1]]
code_chunk(json_serialize(e$exec(letter="U")), "json")
```
````
or [inserting R code](https://github.com/rstudio/apis-plumber/blob/ded991c95628ccab9d26e9570c54689e6e25f4f3/04-rendering-output.Rmd#L33-L35)
````r
```{r, echo=FALSE, results='asis'}
include_r("files/apis/04-01-response.R")
```
````

I believe having a way to do such things (maybe by just having one of these functions above) would be very interesting. Could be sum up by having a way to "include as-is as language-XXX”. (cc @aronatkins)

Just putting this here so that we can discuss.

**Comment by aronatkins** [comment]
Before falling back to helpers like the `include_r` function, I first attempted to use N+1 backticks to embed an example R Markdown document, like:

`````markdown
Here is an R Markdown document containing a runnable code chunk:

````markdown
---
title: "Hello, R Markdown"
---

```{r, echo=FALSE}
21 * 2
```
````
`````

This felt like a natural approach because, in a plain Markdown document, text within a backtick fence is left as-is. I forgot that the executable code runs without considering the wrapping Markdown fences.

Could we support a syntax that resembles the native Markdown, perhaps with an annotation that indicates that the contents are not to be analyzed for executable chunks? Hand-waving here, but maybe a "verbatim" engine?

`````markdown
Here is an R Markdown document containing a runnable code chunk:

````{verbatim, language=markdown}
---
title: "Hello, R Markdown"
---

```{r, echo=FALSE}
21 * 2
```
````
`````

**Comment by cderv** [comment]
Just a note that verbatim engine is related to the `asis` engine (https://bookdown.org/yihui/rmarkdown-cookbook/eng-asis.html), with a difference that it would output fenced code block with attributes.

Also currently, the example above would need to be written this way to work.
 
`````md
````markdown
---
title: "Hello, R Markdown"
---

```{r, echo=FALSE}`r ''`
21 * 2
```
````
`````

**Comment by cderv** [comment]
@aronatkins 

You're example have now been implemented in the current version of **knitr**

`````markdown
````{verbatim, language=markdown}
---
title: "Hello, R Markdown"
---

```{r, echo=FALSE}
21 * 2
```
````
``````

This will work to produce 

`````markdown
````markdown
---
title: "Hello, R Markdown"
---

```{r, echo=FALSE}
21 * 2
```
````
`````

See more in https://github.com/yihui/knitr/blob/master/NEWS.md#changes-in-knitr-version-137

Regarding the include idea, we were thinking of extending the logic to a `embed` engine

````markdown
```{embed, file = 'example.js', lang = 'javascript'}
```
````

to insert the content of the file in a fenced code block with language javascript

````markdown
```javascript
 
```
````
