### ISSUE TITLE
Significant digits knitr + Latex

### ISSUE THREAD

**Issue by jamarav** [yihui/knitr#1942]
Hi everyone,

First of all, congratulations for this amazing package. Now, I'm writing mi PhD in knitr + Latex and the final result is really good.
I open this issue because I found a problem with the inline print for numbers. I have consult the documentation and I didn't find any option to print numbers in scientific notation and fixing the significant digits in Latex + knitr. The current format it's good for many applications but for example, when we adjust a regression model, it 's important to print coefficients in scientific notation and 3 or more significant digits.
In my opinion, it may be interesting to offer this option. R is an statistical programming language and it is very common to include regression coefficients.

For the moment I provide you my provisional solution to this problem. I have create a simple function in R that makes the final format and prints the formated numbers as characters.

```
sigDig = function(x, digits = 3){
    
    x_<-format(x, digits = digits, scientific = T)
    
    x_<-paste0(gsub(x = x_, pattern = "e",replacement = "\\\\operatorname{e"), "}")
    
    print(x_)
    
}
```
I use this function to create a new variable for example x_print<-sigDig(x) and then print with \Sexpr{x}. I tried to print directly with \Sexpr{sigDig(x)} but it doesn't works.
The \operatorname function in latex gets better results for scientific notation.
I don't know if there is a better way solution for this problem. Any comment or suggestion will be thankfully received.

Thanks in advance

**Comment by cderv** [comment]
Hi @jamarav 

Can you share a working example of what works now and don't suits you so that I better understand ? 

About scientific notation in inline code, there is mention in here: https://yihui.org/knitr/demo/output/#inline-output

Thank you. 

About you function, I believe you don't need the print, just output as character. And I understand `\operateurname` is math so you'll need to include in a math notation. 

Using markdown this would work 

````markdown
---
title: 'Style in reference'
output: 
  pdf_document:
    keep_tex: true
---

```{r}
sigDig = function(x, digits = 3){
    x_ <- format(x, digits = digits, scientific = T)
    x_ <- paste0(gsub(x = x_, pattern = "e",replacement = "\\\\operatorname{e"), "}")
    x_
}
```

This is a number: $`r sigDig(0.0023658)`$
````

**Comment by jamarav** [comment]
Hi @cderv, Thanks for you reply.
It's true the function doesn't need the print order (I write this only to check the output  in R) and of course the \operator functions needs the equation environtment (I forgot include this yesterday).
About the link that you provides me, I tried to set different values of scipient and digits variables but I don't like the final result. I try to offer a simple example to illustrate the problem:

For exemple, I have experimental values for the electrical consumption of a variable speed fan (the velocity is in % and the consumption in W). I want to adjust a simple regression model and then print the equation of the model. With the following code you can to reproduce this example:

```
df<-data.frame(fan=c(10,20,30,40,50,60,70,80,90,100),
			Wfan=c(7.25,7.15,14.5,32.75,65.75,110.5,170.5,240.5,335.5,335.5)
			  )

Model_fan<-lm(data = df[-nrow(df) ,], Wfan ~ fan + I(fan^2) + I(fan^3)-1)

coeff<-coefficients(Model_fan)


sigDig = function(x, digits_ = 4){
    
    x_<-format(x, digits = digits_, scientific = T)
    
    x_<-paste0(gsub(x = x_, pattern = "e",replacement = "\\\\operatorname{e"), "}")
    
    x_
    
}



coeff_print<-sigDig(coeff)

coeff_print2<-format(coeff, digits = 4, scientific = T)
```
Then we need the Latex code to produce the following equations

This print is without the custom format (`scipient=1` and `digits=3`).
```\begin{equation}
\dot{W}_{1fan}=\Sexpr{coeff[1]}f_{fan} + \Sexpr{coeff[2]}f^2_{fan} + \Sexpr{coeff[3]}f^3_{fan}\label{eq:fan consdsadumption}
\end{equation}
```

This print is for the custom format:
``` 
\begin{equation}
\dot{W}_{1fan}=\Sexpr{coeff_print[1]}f_{fan} + \Sexpr{coeff_print[2]}f^2_{fan} + \Sexpr{coeff_print[3]}f^3_{fan}\label{eq:fan consumption}
\end{equation}
```
An other possible option is remove the \operatorname function but the results are worse.

```
\begin{equation}
\dot{W}_{1fan}=\Sexpr{coeff_print2[1]}f_{fan} + \Sexpr{coeff_print2[2]}f^2_{fan} + \Sexpr{coeff_print2[3]}f^3_{fan}\label{eq:fan consumption}
\end{equation}
```
I attach the following capture with the results. You can see that the second coefficients only has a significant value in the default print.

![equations](https://user-images.githubusercontent.com/38505982/104619639-67197b00-568e-11eb-9b73-f974d5f977c3.png)

**Comment by cderv** [comment]
As you mentioned wanting to show the equation of a model, I just wanted to share that there is a package to help with that: https://bookdown.org/yihui/rmarkdown-cookbook/equatiomatic.html

Maybe it could help you with your need. It definitly helps writing equation for models but it is possible that it does not support scientific notation. You may open an issue there to suggest this feature request. 

About you example, I am a bit lost about what is the issue here. Can you share a full reproducible example ? 
Like a file I can render on my side and maybe explaining what is not working ?

**Comment by jamarav** [comment]
Sorry for the delay in answer. There is not an issue with the example that i provided. It works.  I just wanted to expose the problem if I could find another type of simpler solution. I'm going to close the question. Thanks you very much @cderv for the suggestions.
