### ISSUE TITLE
Encoding issue during knitting on Windows

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1944]
# Initial Context 

This was reported by @thomasp85 while working on fonts support for graphic design. 

<details>
<summary>Here are the initial issues</summary>

````markdown
---
title: "Untitled"
author: "C. Dervieux"
date: "13/01/2021"
output: html_document
---

```{r setup}
library(ggplot2)
preview_devices <- function(p, width = 2, height = 1) {
  quartz_file <- fs::path(knitr::fig_path(),  "windows.png")
  if (!dir.exists(dirname(quartz_file))) dir.create(dirname(quartz_file), recursive = TRUE)
  png(quartz_file, width, height, units = 'in', res = 300, type = "windows")
  plot(
    p + 
      ggtitle("  Windows device") + 
      theme(plot.title = element_text(size = 10, hjust = 0.5), plot.title.position = 'plot')
  )
  dev.off()
  cairo_file <- fs::path(knitr::fig_path(),  "cairo.png")
  png(cairo_file, width, height, units = 'in', res = 300, type = "cairo")
  plot(
    p + 
      ggtitle("  Cairo device") + 
      theme(plot.title = element_text(size = 10, hjust = 0.5), plot.title.position = 'plot')
  )
  dev.off()
  ragg_file <- fs::path(knitr::fig_path(),  "ragg.png")
  ragg::agg_png(ragg_file, width, height, units = 'in', res = 300)
  plot(
    p + 
      ggtitle("  Ragg device") + 
      theme(plot.title = element_text(size = 10, hjust = 0.5), plot.title.position = 'plot')
  )
  dev.off()
  list(quartz = quartz_file, cairo = cairo_file, ragg = ragg_file)
}
```

* * *

## Support of non-latin scripts

A device should recognise and properly handle scripts that flows in a different
direction the left-to-right

- The graphic engine in R does not permit devices to handle vertical text 😞

```{r, fig.show='hold'}
hebrew_text <- "זהו טקסט בעברית"
arabic_text <- "هذا نص باللغة العربية"
Encoding(arabic_text)
p <- ggplot() + 
  geom_text(aes(x = 0, y = 1:2, label = c(arabic_text, hebrew_text)), family = "Arial") + 
  expand_limits(y = c(0, 3)) +
  theme_void() + 
  theme(panel.background = element_rect('gray90', 'white', 3))
files <- preview_devices(p)
knitr::include_graphics(files$quartz)
knitr::include_graphics(files$cairo)
knitr::include_graphics(files$ragg)
```
````

leading to this graphs when executed in the IDE in R console 
![image](https://user-images.githubusercontent.com/6791940/104596868-de421580-5674-11eb-890b-3173ff35cc80.png)
 but this in the knitted document
![image](https://user-images.githubusercontent.com/6791940/104596907-f023b880-5674-11eb-976d-1f54e762a2db.png)

</details>

# Issues with encoding in knitr

Using a `test.Rmd` file encoded in UTF-8 with this content 
````markdown

```{r text}
hebrew_text <- "זהו טקסט בעברית"
Encoding(hebrew_text)
arabic_text <- "هذا نص باللغة العربية"
Encoding(arabic_text)
```

```{r}
hebrew_text
arabic_text
```

````

it will lead to a different result in the IDE when executing chunk (which leads to code being executed in the R console)
![image](https://user-images.githubusercontent.com/6791940/104596612-80153280-5674-11eb-9ad4-02f22f24311f.png)

than when knitted `knitr::knit("test.Rmd")` resulting in 

````markdown


```r
hebrew_text <- "זהו טקסט בעברית"
Encoding(hebrew_text)
```

```
## [1] "unknown"
```

```r
arabic_text <- "هذا نص باللغة العربية"
Encoding(arabic_text)
```

```
## [1] "unknown"
```


```r
hebrew_text
```

```
## [1] "<U+05D6><U+05D4><U+05D5> <U+05D8><U+05E7><U+05E1><U+05D8> <U+05D1><U+05E2><U+05D1><U+05E8><U+05D9><U+05EA>"
```

```r
arabic_text
```

```
## [1] "<U+0647><U+0630><U+0627> <U+0646><U+0635> <U+0628><U+0627><U+0644><U+0644><U+063A><U+0629> <U+0627><U+0644><U+0639><U+0631><U+0628><U+064A><U+0629>"
```

````

It seems that there are some conversions happening during the evaluation process that leads to incorrect support of those  UTF-8 strings

@yihui you may already know about this limitations regarding encoding. Are we missing something ?

**Comment by cderv** [comment]
And I think this is known and related to old encoding issues : https://github.com/r-lib/evaluate/issues/59 and https://github.com/r-lib/evaluate/issues/66

**Comment by yihui** [comment]
Yes, it's a known issue: r-lib/evaluate#59. Unfortunately, there's nothing we could do about it, except waiting for the UTF-8 build of R is officially available: https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/index.html

**Comment by yihui** [comment]
R 4.2.0 is coming in about a month: https://developer.r-project.org I guess the current R-devel already works: https://cloud.r-project.org/bin/windows/base/rdevel.html If not, we can reopen this issue and investigate further.
