### ISSUE TITLE
Generalize is_format_output to test more than HTML and LaTeX

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#1950]
From a tweet https://twitter.com/graemeleehickey/status/1352947038690938880

There are currently only `is_html_output()` and `is_latex_output()` but no `is_docx_output()` or other. 

Would that be interesting to extend ? 

But maybe **knitr** is not the right place for this ? 

However, one solution could be to export `knitr:::pandoc_to()` and let users test on this.

**Comment by yihui** [comment]
> However, one solution could be to export `knitr:::pandoc_to()` and let users test on this.

That's what I'd do.

**Comment by cderv** [comment]
That is the easiest indeed. And the more generic for all possible formats. I'll export and document then?

**Comment by yihui** [comment]
Please go ahead. Perhaps export it together with `pandoc_from()`.
