### ISSUE TITLE
echo=TRUE does not work for engine='cat'

### ISSUE THREAD

**Issue by GitHunter0** [yihui/knitr#1961]
Hi yihui , I hope you are fine.

Just a quick issue.

 When I use engine 'cat', echo=TRUE does not work and a blank html page is returned when I knit this R notebook:

```
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```

```
```{r, engine='cat', echo=TRUE, eval=TRUE, engine.opts = list(file = 'test.txt'}

some cat chunk text

```

I would like to not only export the chunk text content to 'test.txt' but also display it in the rendered version of the notebook.

Thank you

**Comment by yihui** [comment]
Please see Section 15.6.3: https://bookdown.org/yihui/rmarkdown-cookbook/eng-cat.html

**Comment by GitHunter0** [comment]
Ow, I read the book and skip this very section, thank you!
