### ISSUE TITLE
Automatic searching .bib location

### ISSUE THREAD

**Issue by matthewgson** [yihui/knitr#1971]
First of all, thanks for developing this awesome package! 

I was trying to use bibliography with RStudio/RSweave(Knitr+TinyTex) but it wasn't successful. After hours of googling I found this solution that worked for me. https://texblog.org/2013/08/20/rknitr-automatic-bibliography-generation-with-biblatex-in-rstudio/

Simply it was because LaTeX was not able to find the .bib file which was located in the same folder where .Rnw (.tex) is. I believe it is a convention to locate .bib / .bst files on the same folder where .Rnw(.tex) is in many small projects, and hoping that it may automatically check .bib/.bst file in the current location.

**Comment by yihui** [comment]
If the bib file is in the same directory as the Rnw file, it should be found automatically. If not, please provide a minimal reprex and let us know how to reproduce the problem. Thanks!

**Comment by matthewgson** [comment]
I just ran a test but found it was working properly as you described. Strange that it didn't work at the time of writing.... one change I just made was to update TexLive from 2020 to 2021 using `tinytex::reinstall_tinytex()` because it did not find `grfext.sty` with the previous version.  Please feel free to close this issue.

**Comment by yihui** [comment]
Good to know! Thanks!
