### ISSUE TITLE
Booktabs in kable

### ISSUE THREAD

**Issue by nurfatimaj** [yihui/knitr#1989]
Hello!

Could you please have a look at `kable` function with `booktabs = TRUE` in the latest release version 1.32? 

I have updated the package earlier today and it started printing `\\midrule{}` instead of `\\midrule`. The same for `\\bottomrule` and `\\toprule`. This has then caused `\noalign` errors when trying to compile tex to pdf. All I could think of to solve the issue is to revert back to version 1.31.

**Comment by yihui** [comment]
Had you followed what the issue guide (which you deleted: https://github.com/yihui/knitr/issues/new), you would have helped yourself resolve the issue, since it has been fixed in the current dev version. Thanks!

**Comment by nurfatimaj** [comment]
ok, thanks!

**Comment by yihui** [comment]
FYI knitr 1.33 is on CRAN now, which has included the fix. Thanks!
