### ISSUE TITLE
Fixing tilde inserted in latex

### ISSUE THREAD

**Issue by brry** [yihui/knitr#1992]
This is a comment to https://github.com/yihui/knitr/issues/492 (Code chunks with a formula as in `lm(y~x)` are typeset as a "high" tilde instead of a "middle" tilde) and may be closed at will:

In the .Rnw LaTeX preamble, I add
```tex
\usepackage{textcomp} % enable middle tilde 
\newcommand{\tildemid}{\raisebox{0.5ex}{\texttildelow}}
```

Then in the `setup` chunk, I add
```r
knitr::knit_hooks$set(source = function(x, options) {
  out <- knitr::hooks_latex()$source(x, options)
  gsub("~","\\\\tildemid", out)
  })
```

To avoid a `textcomp` dependency, I also tried
```r
gsub("\\hlopt{~} ","\\sim", out)
```
which looks really nice, but generates `missing $ inserted` errors.  
I chose to not further pursue that road but use the first solution.

**Comment by yihui** [comment]
> which looks really nice, but generates `missing $ inserted` errors.

I don't understand---if it throws an error, how did you get the PDF output that looked nice? It seems you need `$\\sim$`?

**Comment by brry** [comment]
I don't know how that worked while generating errors.   
`$\\sim$` displayed the dollar signs in the code chunk. Same with `\\$\\sim\\$`.   
Both still produced error messages.

I'm absolutely happy with the `\tildemid` solution.  
As for me, this issue can be closed, as long as a reference shows up in #492 in case someone else lands there in the future.

**Comment by yihui** [comment]
Let me rethink about it (darn it I have completely forgotten that it was @jaredlander who filed #492---he is my VIP). Thanks for filing the issue again!

**Comment by jaredlander** [comment]
And you're my MVP

**Comment by yihui** [comment]
I just provide a package option to allow for customizing the tilde symbol. Two examples:

## Using \texttildelow in textcomp

```latex
\documentclass{article}
\usepackage{textcomp} % enable middle tilde
\newcommand{\tildemid}{\raisebox{0.5ex}{\texttildelow}}
\begin{document}

<<setup, include=FALSE>>=
knitr::opts_knit$set(latex.tilde = r"(\hlopt{\tildemid})")
@

<<>>=
y ~ x
@
\end{document}
```

## Using the math symbol \sim

```latex
\documentclass{article}
\begin{document}

<<setup, include=FALSE>>=
knitr::opts_knit$set(latex.tilde = r"(\hlopt{\scriptsize{\ensuremath{\sim}}})")
@

<<>>=
y ~ x
@
\end{document}
```

The output of the second example looks better in my eyes, but keep in mind that the symbol is actually not a tilde, so you won't be able to copy the code and run it.

As I mentioned in #492, this is a surprisingly complicated task: https://tex.stackexchange.com/q/312/9128 I can't provide a good default (ideally the correct ~ character with no extra dependency, which seems to be impossible), and will let you decide which solution you want to adopt.
