### ISSUE TITLE
Use Microsoft's built-in styles for knitting to Word

### ISSUE THREAD

**Issue by arencambre** [yihui/knitr#1999]
Currently, knits to Word have considerable stylistic differences from Word's built-in defaults. Examples include use of serifed fonts, different font selections, horizontal alignment of certain headings, and more.

Under the premise that Microsoft's styles were thoughtfully made and clean, please consider using Microsoft's default Word styles unless the user specifies otherwise.

(This is not a support request for how to apply my own styles. I can do it with `reference_docx` in the YAML header. It's complexity I'd like to avoid. This is more of a "use good defaults" request.)

**Comment by cderv** [comment]
Hi @arencambre, 

thanks for reaching out. 

First, allow me to clarify the context: Knitting to Word is not done directly by **knitr** but by **rmarkdown**. **knitr** is only responsible to render `.Rmd` to `.md` by evaluating executable code chunk and writing source and outputs to Markdown syntax following the requested configuration. From there, the conversion to different output format including `.docx` will be done by Pandoc. **rmarkdown** R package is the tooling that will make this work together. You can learn more about this in https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-process.html

So, from the above, **rmarkdown** will asked Pandoc to convert to `.docx` format. This is done by using the output format `rmarkdown::word_document()` - `rmarkdown::render()` will asked Pandoc to convert to `docx` output format, and if no `reference_docx` is passed in the function, the default one from Pandoc will be used. 
To learn more about Pandoc and Word, see https://pandoc.org/MANUAL.html#option--reference-doc

I guess that your "use good defaults" request would be more suited for Pandoc directly as the default reference doc comes from there. You can open it by doing 
```
pandoc -o custom-reference.docx --print-default-data-file reference.docx
```

You can try to convert a test file to docx using Pandoc directly at command line and see the result.

I don't know if Pandoc's reference doc would change on purpose the Word default style. If you want to ask about this, Pandoc discuss google group would be a first place to ask I think: https://pandoc.org/help.html

Does this help ? 

Did I understood correctly your request ?

**Comment by arencambre** [comment]
Yes, you got it right. Thank you!

I opened an issue with Pandoc at https://github.com/jgm/pandoc/issues/7275.

I thought about closing this, but I think we need to ask if use of Microsoft's native Word styles by default is important to the R community. If is, and should the pandoc community not agree to change, then an option is a clean docx, with native styles intact, could be provided to pandoc should the `reference_docx` argument not be specified.

**Comment by cderv** [comment]
We could indeed provide another template for docx. we do that for other format. Even if not the default, we could add an opt-in mechanism to use this specific template. 

I never looked at the difference between Pandoc's reference doc and the Word default one.

**Comment by cderv** [comment]
> I thought about closing this, but I think we need to ask if use of Microsoft's native Word styles by default is important to the R community. If is, and should the pandoc community not agree to change, then an option is a clean docx, with native styles intact, could be provided to pandoc should the reference_docx argument not be specified.

BTW, this issue should be closed in **knitr** and another one should be open in **rmarkdown** because if a reference doc is to be included somewhere it would be in **rmarkdown** not **knitr**. 

Would you mind opening a new issue in **rmarkdown** with this last idea you had ? 
This would be a way to see how many 👍 it got and follow the issue on Pandoc side too. 

Thanks.

**Comment by arencambre** [comment]
Understood. I'll close this and wait to see what happens in pandoc. If they give the desired resolution, then no more work needed. If not, then I'll suggest to rmarkdown that they make this change.
