### ISSUE TITLE
fig.keep='first' or 'last' produce nothing when the chunk contains only one plot

### ISSUE THREAD

**Issue by dongzhuoer** [yihui/knitr#2002]
`test.Rmd`
````rmd
---
output:
    html_document: default
    md_document:
        variant: markdown
---

# default

```{r plot}
plot(cars)
```

# all

```{r plot, fig.keep='all'}
```

# first

```{r plot, fig.keep='first'}
```

# last

```{r plot, fig.keep='last'}
```


# none

```{r plot, fig.keep='none'}
```
````

**Comment by dongzhuoer** [comment]
![image](https://user-images.githubusercontent.com/15871952/118442156-cd85d700-b71c-11eb-91ef-f7ddd010feae.png)

**Comment by dongzhuoer** [comment]
What's more, at least `fig.keep='none'` would print the R code.

**Comment by cderv** [comment]
Which version of **knitr** are you using ? 
This has already been reported in #1993 and this should be fixed in current dev version by #1996 unless I missed an edge case.

Thanks

**Comment by dongzhuoer** [comment]
1.33

**Comment by yihui** [comment]
Please install [the development version](https://github.com/yihui/knitr#installation) as the issue guide requested (which you deleted in your post). Thanks!

**Comment by dongzhuoer** [comment]
Develop version (1.33.4) solved the problem

**Comment by cderv** [comment]
Duplicate of #1993
