### ISSUE TITLE
non LATEX inline hook evaluate a function whereas it is not expected 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2006]
From https://github.com/rstudio/rmarkdown/issues/2144

```r
res <- function() "dummy"

# this is the hook used
knitr::hooks_markdown()$inline
#> function (x) 
#> {
#>     if (is_latex_output()) 
#>         .inline.hook.tex(x)
#>     else {
#>         .inline.hook(format_sci(x, if (length(pandoc_to()) == 
#>             1L) 
#>             "latex"
#>         else "html"))
#>     }
#> }
#> <bytecode: 0x00000000144017f8>
#> <environment: 0x0000000013f98150>

# should error
knitr:::.inline.hook.tex(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'
knitr:::.inline.hook(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'

# but it does not because of this function
knitr:::format_sci(res)
#> [1] "dummy"
knitr:::format_sci
#> function (x, ...) 
#> {
#>     if (inherits(x, "roman")) 
#>         return(as.character(x))
#>     vapply(x, format_sci_one, character(1L), ..., USE.NAMES = FALSE)
#> }
#> <bytecode: 0x0000000014fdc2f0>
#> <environment: namespace:knitr>

# oddly this error
knitr:::format_sci_one(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'

# So it seems vapply is doing coercion
vapply(res, knitr:::format_sci_one, character(1))
#> [1] "dummy"
```

This creates a difference between LaTeX and other output format. 

Maybe we should take care of changing that because it could break some code 🤔

**Comment by atusy** [comment]
The document says inline chunk should return string or objects coercible to be strings.
That said, I think we can first deprecate passing function to `format_sci`, and then defunct it in the future.

**Comment by yihui** [comment]
I'm okay with making a breaking change in this case since functions shouldn't have worked. The simplest change may be adding a line `as.character(x)` after https://github.com/yihui/knitr/blob/a41ca9f02e12c96a76ae0a95f3f237054fb52330/R/block.R#L530
to test if the result can be coerced to character. Then it should throw the error before the inline hook is actually called when the result is a function.
