### ISSUE TITLE
Regression in R 3.4

### ISSUE THREAD

**Issue by t-kalinowski** [yihui/knitr#2052]
Hi,

I recently expanded the CI tests for the keras R package and I noticed that R CMD check would fail due to vignette chunks being evaluated that shouldn't be evaluated. It seems that `knitr::opts_chunk$set(eval = FALSE)` isn't respected in the latest few versions of knitr if R <= 3.4. Installing knitr version 1.30 makes my tests pass again.

**Comment by yihui** [comment]
Could you read and follow [the issue guide](new) exactly to provide the required information? Otherwise it is usually hard for us to help you. In your case, it's difficult to know what the problem could be without a reproducible example. If it is impractical to provide a reproducible example, it will be helpful to let us know which exact version broke your package (e.g., you said 1.30 works, and does that mean 1.31 broke it?). Thanks!

**Comment by t-kalinowski** [comment]
Hi, apologies for not fleshing this out fully. I made a skeleton R package with some GHA workflows that demonstrate the issue:
You can see the failed run here: https://github.com/t-kalinowski/knitr.regression/runs/3735193979
relevant output:

```R
── R CMD check results ───────────────────────────── knitr.regression 0.1.0 ────
Duration: 25.1s

❯ checking running R code from vignettes ...
     ‘a_vignette.Rmd’ using ‘UTF-8’ ... failed
   ERROR
  Errors in running code in vignettes:
  when running code in ‘a_vignette.Rmd’
    ...
  
  > knitr::opts_chunk$set(eval = FALSE)
  
  > stop("I shouldn't run!")
  
    When sourcing ‘a_vignette.R’:
  Error: I shouldn't run!
  Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔
Error: Error: R CMD check found ERRORs
```

**Comment by t-kalinowski** [comment]
>and does that mean 1.31 broke it?

Yes

**Comment by yihui** [comment]
Hmm... That's weird. I looked at the changes in 1.31 but didn't see a possible change that could have led to the breakage: https://github.com/yihui/knitr/compare/v1.30...v1.31 I'll investigate further. Thanks a lot for the minimal reproducible example! I really appreciate it.

**Comment by yihui** [comment]
Identified the offending commit: https://github.com/yihui/knitr/commit/d35590d5361255be6673c9ea95646fe9ca5e45d9 but still need to understand why the problem only occurs with R 3.4.4. @cderv Do you have R 3.4.4 to test with?

**Comment by yihui** [comment]
@cderv Please ignore this issue. I've figured it out.

@t-kalinowski It's fixed now. Unfortunately I just made a CRAN release this morning, so I can't make another one in a short time (may need to wait for at least a month for the next CRAN release). Thanks for your patience!

**Comment by halldc** [comment]
Hi @yihui - I'm encountering this same issue on R 4.1.1 when running `rcmdcheck::rcmdcheck()`.

**Comment by yihui** [comment]
@halldc Could you please provide a reproducible example? Thanks!

**Comment by halldc** [comment]
@yihui - building on @t-kalinowski's excellent reprex: https://github.com/halldc/knitr.regression/runs/3737702441

**Comment by halldc** [comment]
@yihui - I suspect this is related to https://github.com/yihui/knitr/pull/2036 interacting with {rcmdcheck}.

**Comment by yihui** [comment]
@halldc You are correct---the check in Github action didn't use the `--as-cran` flag. Unfortunately I was wrong in https://github.com/yihui/knitr/pull/2036#pullrequestreview-734214207 that it should be rare to run `R CMD check` without `--as-cran`.

For now, the workaround is to either use `--as-cran` (https://github.com/yihui/knitr.regression/commit/0af676ac41cd5f29994dc5d114eb2f825c618337), or set `_R_CHECK_VIGNETTES_SKIP_RUN_MAYBE_` to `TRUE` like this: https://github.com/rstudio/keras/pull/1275/files.

I'll fix this problem in the next version of **knitr**.

**Comment by halldc** [comment]
Thanks @yihui! Yep, I reached the same conclusion and I'm using the second option for now. 🙂 

FYI - I'm not using `--as-cran` because the package is an internal package at a company. Many of the CRAN-specific checks are inappropriate in this setting (e.g. warnings about unreachable intranet URLs).

**Comment by yihui** [comment]
I have submitted a new version of knitr to CRAN, which is pending manual inspection right now (because CRAN requires at least 7 days between two releases, otherwise a CRAN maintainer will have to manually check it). Hopefully this problem will go away in a day or two. Apologies for the trouble, and thanks for your patience!

**Comment by halldc** [comment]
Thanks for the quick resolution, @yihui ! 🎉

**Comment by yihui** [comment]
You are welcome! The new version was accepted on CRAN about 7 hours ago.
