### ISSUE TITLE
pdfcrop on windows

### ISSUE THREAD

**Issue by matthias-studer** [yihui/knitr#209]
Thank you very much for developping knitr. It's quite easy to move from Sweave. Please sorry for my bad english.

hook_pdfcrop do not work on my computer (windows 7, 64 bits, R 2.15.0). I had to modify the "system" call to system(paste(Sys.getenv("COMSPEC"),"/c", "pdfcrop", x, x)) (see below). Maybe the issue can be resolved by checking for the platform ?

For other image format (at least for png), it is also possible to use convert (ImageMagick) to crop the image:
convert myimage.png -trim myimage.png

``` R
hook_pdfcrop2 <- function (before, options, envir)
{
   ext = options$fig.ext
   if (options$dev == "tikz" && options$external)
       ext = "pdf"
   if (before || (fig.num <- options$fig.num) == 0L || ext !=
       "pdf")
       return()
   paths = paste( knitr:::valid_path(options$fig.path, options$label),
       if (fig.num == 1L)
           ""
       else seq_len(fig.num), ".pdf", sep = "")
   lapply(paths, function(x) {
       message("cropping ", x)
       x = shQuote(x)
## Here is the modification
       system(paste(Sys.getenv("COMSPEC"),"/c", "pdfcrop", x, x))
   })
   return()
}

```

**Comment by RSchwinn** [comment]
**pdfcrop** still doesn't seem to work on my PC with windows 10, MikTeX, and Perl installed. I've found that saving the .tex, running the following script, and finally recompiling the .tex file does the trick:

    RMD_file_name = "all"
    subdirectory = paste0(RMD_file_name,"_files/figure-latex/")
file_list = paste0(subdirectory, list.files(path = subdirectory, pattern = ".pdf"))
    
    for(i in seq_along(file_list)){
    system(paste(Sys.getenv("COMSPEC"),"/c", "pdfcrop", file_list[i], file_list[i]))
}
