### ISSUE TITLE
figure cross-reference

### ISSUE THREAD

**Issue by XiangyunHuang** [yihui/knitr#2094]
Alternative Syntax for Chunk Options, and Some New Engines 
https://yihui.org/en/2022/01/knitr-news/

````
```{r}
#| rmdworkflow,
#| echo = FALSE,
#| fig.cap = "A diagram illustrating how an R Markdown document
#|   is converted to the final output document.",
#| out.width = "100%"

knitr::include_graphics("images/workflow.png", dpi = NA)
```
````

hope we can use`\@ref(fig:rmdworkflow)` to cross-reference.

**Comment by yihui** [comment]
You have to use **bookdown** or Quarto. Cross-references are only supported by them.

**Comment by XiangyunHuang** [comment]
I made a mistake that I should have used `fig.cap` instead of `fig.caption`.
