### ISSUE TITLE
Update R versions for package

### ISSUE THREAD

**Issue by essemenoff** [yihui/knitr#2100]
Dear Supporters,

DESCRIPTION file has entry

```
...
Depends:
    R (>= 3.2.3)
...
```
but this is not same as mentioned in R/parser.R file at  #235
```
i1 = startsWith(code, s1)  # [start|end]sWith() requires R >= 3.3.0
```

There is error message in output if we use knitr package with R 3.2.4
```
processing file: Test.Rmd
Error in partition_chunk(engine, code) : 
  could not find function "startsWith"
Calls: <Anonymous> ... split_file -> lapply -> FUN -> parse_block -> partition_chunk
Execution halted
```

Could you please update R version in knitr's DESCRIPTION file?

Best wishes, 
Evgenii

**Comment by yihui** [comment]
Sure! Done. Thanks for the reminder!
