### ISSUE TITLE
When `file=` chunk option, duplication of chunk label is not checked. 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2126]
Reported by @mine-cetinkaya-rundel

Reprex: 

* Will error 

````markdown

```{r abcd}
1 + 1
```


```{r abcd}
2 + 2
```
`````
 
```r
> knitr::knit("test.Rmd")


processing file: test.Rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'abcd', which has been used for the chunk:
1 + 1
````

* Will not error - no check duplication ?

````markdown
```{cat, engine.opts = list(file = "_common.R")}
1 + 1
```

```{r abcd, code = xfun::read_utf8("_common.R")}
```


```{r abcd}
2 + 2
```

```{r}
unlink("_common.R")
```
````

```r
> knitr::knit("test.Rmd")


processing file: test.Rmd
  |...........                                                                                      |  11%
  ordinary text without R code

  |......................                                                                           |  22%
label: unnamed-chunk-1 (with options) 
List of 2
 $ engine.opts:List of 1
  ..$ file: chr "_common.R"
 $ engine     : chr "cat"

  |................................                                                                 |  33%
  ordinary text without R code

  |...........................................                                                      |  44%
label: abcd (with options) 
List of 1
 $ code: chr "1 + 1"

  |......................................................                                           |  56%
  ordinary text without R code

  |.................................................................                                |  67%
label: abcd
  |...........................................................................                      |  78%
  ordinary text without R code

  |......................................................................................           |  89%
label: unnamed-chunk-2
  |.................................................................................................| 100%
  ordinary text without R code


output file: test.md

[1] "test.md"
```

Same with 

````markdown
```{r abcd, file = "_common.R"}
```
````

We probably want the duplication chunk to still be done, right ?

**Comment by cderv** [comment]
Currently the check is done in `parse_block()`
https://github.com/yihui/knitr/blob/925b9b345528ba9689b4a4144ba35ab6d952e55b/R/parser.R#L108-L115

Maybe we should also trigger if `options$code` or `options$file` is provided ? 

Or we could regroup in the same all the process and checks regarding code chunk content at the parsing time, or the process time
https://github.com/yihui/knitr/blob/925b9b345528ba9689b4a4144ba35ab6d952e55b/R/block.R#L33-L40

**Comment by yihui** [comment]
> Maybe we should also trigger if `options$code` or `options$file` is provided ?

Yes, let's do that. Sounds like a simple fix (change `length(code)` to `length(code) || length(params$file)`). Please feel free to submit a PR and merge by yourself, or just push to master directly.

> Or we could regroup in the same all the process and checks regarding code chunk content at the parsing time, or the process time

I'm not sure if that's a good idea.

**Comment by cderv** [comment]
> Yes, let's do that. Sounds like a simple fix (change length(code) to length(code) || length(params$file)). Please feel free to submit a PR and merge by yourself, or just push to master directly.

it would be `length(code) || length(params$file) || length(params$code)`  instead, right ?

**Comment by yihui** [comment]
Yes.
