### ISSUE TITLE
`\addlinespace` is not added in `kable(booktabs = TRUE)`

### ISSUE THREAD

**Issue by amarakon** [yihui/knitr#2133]
I saw this line of code in table.R: `linesep = if (booktabs) c('', '', '', '', '\\addlinespace') else '\\hline',`. This makes it seem like if I set `booktabs` to `TRUE`, \addlinespace will be added after each column.
But this is not the case.
I created the following table.

```r
activity = c("Push-ups", "Crunches", "Plank", "Vertical jump", "Sit, reach, and hold")
one = c("20", "24", "1:00", "40", "16")

fitness_test = data.frame(activity, one)

kable(fitness_test, booktabs = TRUE, col.name=c("Activity", "Score"))
```

This is the LaTeX output:

```
\begin{tabular}{ll}
\toprule
Activity & Score\\
\midrule
Push-ups & 20\\
Crunches & 24\\
Plank & 1:00\\
Vertical jump & 40\\
Sit, reach, and hold & 16\\
\bottomrule
\end{tabular}
```

This is the LaTeX output I expected:

```
\begin{tabular}{ll}
\toprule
Activity & Score\\
\midrule
Push-ups & 20\\
\addlinespace
Crunches & 24\\
\addlinespace
Plank & 1:00\\
\addlinespace
Vertical jump & 40\\
\addlinespace
Sit, reach, and hold & 16\\
\bottomrule
\end{tabular}
```

**Comment by cderv** [comment]
This is only because your table as not enough line. Add just one and it will be there 
````r
activity = c("Push-ups", "Crunches", "Plank", "Vertical jump", "Sit, reach, and hold", "Other")
one = c("20", "24", "1:00", "40", "16", "17")

fitness_test = data.frame(activity, one)

knitr::kable(fitness_test, booktabs = TRUE, col.name=c("Activity", "Score"), format = "latex")
```
````latex
\begin{tabular}{ll}
\toprule
Activity & Score\\
\midrule
Push-ups & 20\\
Crunches & 24\\
Plank & 1:00\\
Vertical jump & 40\\
Sit, reach, and hold & 16\\
\addlinespace
Other & 17\\
\bottomrule
\end{tabular}
````

This is mentioned in the cookbook : https://bookdown.org/yihui/rmarkdown-cookbook/kable.html
> A line space is added to every five rows by default. This is controlled by the argument linesep, which defaults to c("", "", "", "", "\\addlinespace"). If you want to add a space to every three rows, you can do this:
> 
> ```r
> knitr::kable(iris3, format = "latex", linesep = c("", "",
> "\\addlinespace"), booktabs = TRUE)
> ```

You need to have more than 5 rows in your table so that it is added in the output. Otherwise, not need for it as no 6th line. 

Hope it helps understand

**Comment by amarakon** [comment]
Oh, thanks for the explanation. I added the argument `linesep = "\\addlinespace"` and that caused it to be between every column.
