### ISSUE TITLE
[Feature request] Tabular Environment Option for kable

### ISSUE THREAD

**Issue by amarakon** [yihui/knitr#2134]
There is already an existing option in the `kable()` function called `table.envir` which can change the environment as opposed to the default floating environment which is `table`.
But I also want to change the `tabular` environment and also have an option to remove the `table` environment.
So there should be another option called `tabular.envir`.
For example, I want the following to be possible with kable:

```
\begin{xltabular}
\caption{Example table}\\
\label{tab:example-table}\\
\end{xltabular}
```

**Comment by cderv** [comment]
For reference follow-up from https://community.rstudio.com/t/how-can-i-prevent-r-markdown-from-escaping-characters-in-custom-blocks/138890/12

**Comment by cderv** [comment]
Is this different than #2135 ? 🤔 is #2138 covering this too ?

**Comment by amarakon** [comment]
> Is this different than #2135 ? thinking is #2138 covering this too ?

kable currently has support for tabular (by default) and longtable.
For my fork, I added support for tabularx and xltabular too.
But what if someone wants to use neither tabular nor longtable, tabularx, or xltabular?
I think there should be an option to change that environment but for me it's not that important anymore since I submitted a pull request for tabularx and xltabular.

**Comment by cderv** [comment]
It makes sense, thanks for the precision.

**Comment by amarakon** [comment]
I will close this issue since my pull request has been merged.

**Comment by cderv** [comment]
Thanks!
