### ISSUE TITLE
[Feature request] tabularx and xltabular Options for kable

### ISSUE THREAD

**Issue by amarakon** [yihui/knitr#2135]
The default tabular environment for kable is `tabular`.
You can set it to `longtable` by setting `longtable = TRUE`.
I want something similar for `tabularx` and `xltabular` environments.
Their arguments should be a bit different.
Here is how a tabular table usually looks (with booktabs):

```
\begin{table}

\caption{\label{tab:label}Caption}
\centering
\begin{tabular}[t]{ll}
\toprule
Lorem & Dolor\\
\midrule
Ipsum & Sit\\
\bottomrule
\end{tabular}
\end{table}
```

While this is how a tabularx table should look like:

```
\begin{table}

\caption{\label{tab:label}Caption}
\begin{tabularx}{\linewidth}{X X}
\toprule
Lorem & Dolor\\
\midrule
Ipsum & Sit\\
\bottomrule
\end{tabular}
\end{table}
```

The difference is in the arguments you give the `tabularx` environment. The first argument is for the length of the table. The second argument is for the alignment or the length of each column. X X X for three columns means it will divide the three columns evenly (1/3 each). This should be the default. I think there should be an argument to change this too.

This is what an `xltabular` table looks like:

```
\begin{xltabular}{\linewidth}{X X}
\caption{\label{tab:label}Caption}\\
\toprule
Lorem & Dolor\\
\midrule\endfirsthead
\toprule
Lorem & Dolor\\
\midrule\endhead
Ipsum & Sit\\
\bottomrule
\end{xltabular}
```

The difference here is that `xltabular` is not placed in a floating `table` environment because it does not need to.
Also, `\midrule\endfirsthead`, `\toprule` (then the top row is repeated), and `\midrule\endhead` are added.
What this does is repeat the header row if the table exceeds one page.
Here is the R code that should be used to make these tables:

````
```{r, label}
Lorem = c("Ipsum")
Dolor = c("Sit")

kable(data.frame(Lorem, Dolor), booktabs = TRUE, caption = "Caption")
```
````

If I set `tabularx = TRUE`, it should make it using `tabularx`.
If I set `xltabular = TRUE`, it should make it using `xltabular`.

**Comment by cderv** [comment]
For reference follow-up from https://community.rstudio.com/t/how-can-i-prevent-r-markdown-from-escaping-characters-in-custom-blocks/138890/12

**Comment by amarakon** [comment]
I tried changing this line: `sprintf('\n\\begin{%s}%s', tabular, valign), align,` to this: ` if (tabularx) { sprintf('\n\\begin{%s}%s%s', tabular, table.length, valign)} else {sprintf('\n\\begin{%s}%s', tabular, valign)}, align,`.
Then I tried to make this table:

```
one = c("two", "three")
four = c("five", "six")

kable(data.frame(one, four), linesep = "\\addlinespace", escape = TRUE, booktabs = TRUE, tabularx = TRUE, table.length = "\\linewidth", align = "X")
```

But it gave me the following error:

```
Error in kable_latex(x = c("two", "three", "five", "six"), ca
ption = NULL,  :
  unused arguments (tabularx = TRUE, table.length = "\\linewi
dth")
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eva
l -> kable -> do.call
```

Sorry, I'm new to R and not sure how to do this, so could you help me with adding this option?
I wanted the LaTeX output to be this:

```
\begin{tabularx}{\linewidth}{XX}
\toprule
one & four\\
\midrule
two & five\\
\addlinespace
three & six\\
\bottomrule
\end{tabularx}
```

**Comment by amarakon** [comment]
**Update:** I submitted a pull request, please check it out.
