### ISSUE TITLE
[Feature request] Cmidrules and Multicolumn for kable

### ISSUE THREAD

**Issue by amarakon** [yihui/knitr#2136]
Suppose I want to make the following table:

![](https://i.imgur.com/Eucu1ij.png)

This table has a cmidrule from 2-3 and it is multi-columned.
Here is how I can make it using LaTeX code:

```
\begin{tabular}{lll}
\toprule
Activity & \multicolumn{2}{l}{February 10, 2022}\\
\cmidrule(l){2-3}
& Score & Goal\\
\midrule
Push-ups & 20 & 25\\
\addlinespace
Crunches & 24 & 30\\
\addlinespace
Plank & 1:00 & 1:30\\
\addlinespace
Vertical jump & 40 & 50\\
\addlinespace
Sit, reach, and hold & 16 & 17\\
\bottomrule
\end{tabular}
```

Making this table using kable is impossible because

1. kable does not support cmidrules
2. kable does not support the `\multicolumn` command

I tried to recreate it in kable with this code:

```r
activity = c("Push-ups", "Crunches", "Plank", "Vertical jump", "Sit, reach, and hold")
one = c("20", "24", "1:00", "40", "16")
two = c("25", "30", "1:30", "50", "17")

fitness_test = data.frame(activity, one, two)

knitr::kable(fitness_test, escape = FALSE, booktabs = TRUE, linesep = "\\addlinespace", col.name=c("Activity", "\\multicolumn{2}{l}{February 10, 2022}"))
```

It gave me this error:

```
Error in dimnames(x) <- dn :
  length of 'dimnames' [2] not equal to array extent
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eva
l -> <Anonymous> -> colnames<-
```

When I made the table in LaTeX, the header row only needed to be two columns because I used the `\multicolumn{2}` command anyways.
But all of the other rows were three columns.
In the code chunk above, I set `\\multicolumn` in the `col.name`, but `col.name` expects three arguments.
Also, I'm not sure where I should add `\\cmidrule`.

**Comment by cderv** [comment]
For reference @yihui follow-up from https://community.rstudio.com/t/how-can-i-prevent-r-markdown-from-escaping-characters-in-custom-blocks/138890/12

**Comment by amarakon** [comment]
> BTW the way, you get the error because your dataframe is 3 columns, and your `col.names` only has 2 elements.

Yeah that's the problem: I used the `\multicolumn` command (which works in LaTeX), but R expects 3 elements.

**Comment by amarakon** [comment]
In my pull request, I added support for cmidrules by adding an option called `header` which allows you to specify extra things to put before the main body of the table.
Now I just need a fix for the multicolumn issue.
