### ISSUE TITLE
Get options by chunk label

### ISSUE THREAD

**Issue by Elvincth** [yihui/knitr#2154]
Are we able to get a chunk options by its label? I searched through the documentation but I didn't find siliary functionality.

For example, I have the code chunk below, I would like to grab the mark options by the chunk label by doing something like`get_chunk_opts("where-am-i", "mark")` and it will return 10.

```
{r where-am-i, echo=FALSE, mark=10}
question("Where are you right now? (select ALL that apply)",
  answer("Planet Earth", correct = TRUE),
  answer("Pluto"),
  answer("At a computing device", correct = TRUE),
  answer("In the Milky Way", correct = TRUE),
  incorrect = "Incorrect. You're on Earth, in the Milky Way, at a computer.")
```

Is there any similar functionality? Thanks!

**Comment by yihui** [comment]
```r
attr(knitr::knit_code$get('where-am-i'), 'chunk_opts')$mark
```

Next time please follow the issue guide (which you shouldn't have deleted in your post) if you want to ask questions. Thanks!

**Comment by Elvincth** [comment]
> ```r
> 
> attr(knitr::knit_code$get('where-am-i'), 'chunk_opts')$mark
> 
> ```
> 
> 
> 
> Next time please follow the issue guide (which you shouldn't have deleted in your post) if you want to ask questions. Thanks!

No problem sorry for that. Thanks for your help, really appreciate it.

**Comment by Elvincth** [comment]
> ```r
> attr(knitr::knit_code$get('where-am-i'), 'chunk_opts')$mark
> ```
> 
> Next time please follow the issue guide (which you shouldn't have deleted in your post) if you want to ask questions. Thanks!

But i try to run `attr(knitr::knit_code$get('where-am-i'), 'chunk_opts')$mark` in runtime it return NULL.

**Comment by yihui** [comment]
It only works when you knit a document. It won't work when you run it outside the document.

**Comment by Elvincth** [comment]
> It only works when you knit a document. It won't work when you run it outside the document.

Sorry, I am new to R. Is there anyway I can access the mark attribute after knit? I tried to cache it in a variable but no luck. 

Thanks for your help!

**Comment by yihui** [comment]
If you want to access an option value outside the knitting process, it'll be much trickier. You'll need a parser, which I haven't provided in **knitr**, but this should be close:

```r
parse_rmd = function(file) {
  x = xfun::read_utf8(file)
  on.exit(knitr::knit_code$restore(), add = TRUE)
  res = knitr:::split_file(x, patterns = knitr::all_patterns$md)
  lapply(res, function(el) {
    if (!is.null(label <- el$params$label)) el$src = knitr::knit_code$get(label)
    el
  })
}
```

Instead of parsing the Rmd document, I strongly recommend the other way around. That is, you define the value before you knit the document, and pass it to the `mark` option. There are several ways to do this. One way is parameterized reports: https://bookdown.org/yihui/rmarkdown/parameterized-reports.html You can define a parameter and use it in the chunk option.

**Comment by Elvincth** [comment]
> https://bookdown.org/yihui/rmarkdown/parameterized-reports.html

Really thanks for your help, I have have a try!
