### ISSUE TITLE
gridSVG does not fall back to svg for matplotlib

### ISSUE THREAD

**Issue by jooyoungseo** [yihui/knitr#2162]
When `dev = "gridSVG"` is used, `matplotlib` throws an error because it does not fall back to "svg". Understandable error, however, what if users include both R and Python figs and want to keep using `gridSVG` for R plots?

> RuntimeError: Evaluation error: ValueError: Format ’gridsvg’ is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)

## Reprex

````

---
title: "test"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.path = "fig/", dev = "gridSVG")
options(knitr.svg.object = TRUE)
```

# Plot test

## R Plot

```{r knitr_gridSVG, out.extra='id="myplot"'}
#| fig-alt: "test plot"
#| fig-cap: figure caption.

library(tidyverse)

mpg %>%
  ggplot(aes(class)) +
  geom_bar()
```

## Python Plot

```{python, out.extra='id="py-svg-plot"'}
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
cars = ['2seater', 'compact', 'midsize', 'minivan', 'pickup','subcompact','suv']
count = [5, 47,41,11,33,35,62]
ax.bar(cars,count)
plt.show()
```


````

**Comment by yihui** [comment]
You can set a chunk option conditionally using option hooks: https://bookdown.org/yihui/rmarkdown-cookbook/option-hooks.html In your case, you can do this:

```r
knitr::opts_hooks$set(dev = function(options) {
  if (options$dev == 'gridSVG' && options$engine != 'R') {
    options$dev = 'png'  # or any other device
  }
  options
})
```

**Comment by jooyoungseo** [comment]
Yes, this works. Thanks for the tip! I am closing this because this is not an issue.
