### ISSUE TITLE
Partial matching in options creates issue

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2168]
I got this warning in **distill** 
````r
1: In call_block(x) :
  The chunk 'unnamed-chunk-1' has the 'child' option, and this code chunk must be empty. Its code will be ignored.
````

There is several code chunks like this
````markdown
```{r child='../man/rmd-fragments/apply-theme.Rmd'}
```
````

The warning comes from : 
https://github.com/yihui/knitr/blob/907184f82489488ab8fd3619aa15b9822bf96067/R/block.R#L59-L62

I believe this comes from partial matching in list as distill set `code_folding` options with a default to FALSE. 
````
code_folding <- not_null(options[["code_folding"]], FALSE)
````

This leads to this scenario 

``` r
options <- list(code_folding = FALSE)
options$code
#> [1] FALSE
```

You know this problem will it seems : https://twitter.com/xieyihui/status/782462926862954496

Should be try set `code = NULL` by default in **knitr** to avoid that ? Or should we replace every `$x` by `[["x"]]` ? 

``` r
options <- list(code_folding = FALSE, code = NULL)
options$code
#> NULL
```

**Comment by yihui** [comment]
Use `params[['code']]` here. Adding `code = NULL` to `opts_chunk` will break existing cache. This is something I didn't put enough thought into and regretted a lot (I can't easily add new options into `opts_chunk`).

**Comment by cderv** [comment]
Thanks!
