### ISSUE TITLE
\begin{fullwidth} not working for highlighted code chunks

### ISSUE THREAD

**Issue by gimoya** [yihui/knitr#222]
in the tufte handout I try to set fullwidth for a text block containing highlighted r-code like:

``` tex
\section{Statistical Analysis:}
\begin{fullwidth}
<<Stats, eval=TRUE>>=
binom.test(10, 121))
@
\end{fullwidth}
```

but this doesn't widen the block - it only centers it...

Is there a way around, or maybe it should be optimized internally?

Kind regards,
Kay

**Comment by r0bis** [comment]
Interesting thing - if in tufte-handout I start fullwidth and in the enclosed text paragraphs there is italics markdown as in `_italicword_` then `\begin{fullwidth}` and correspondingly the end too get escaped and do not work - i.e. appear in the document verbatim. However if I remove underscore from the paragraphs between `fullwidth`, then it works very nicely.
