### ISSUE TITLE
improper R kable output in console

### ISSUE THREAD

**Issue by antoine4ucsd** [yihui/knitr#2229]
Hello
I am having issues with kable on my mac .
the output is not really what I would expect. not sure how to explain it.
for example. If I run
```
knitr::kable(t,caption="finalfit table")
```
I would expect
<img width="727" alt="image" src="https://user-images.githubusercontent.com/18502631/218419452-500cc6bd-8348-4b57-b485-261c6a4b362c.png">

but I got 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/18502631/218419366-93716289-57bf-4d92-8455-a0f556ac5101.png">

not sure if this is related but I also get this kind of errors:

```
sh: line 1: 24442 Killed: 9               '/Users/myself/.virtualenvs/r-reticulate/bin/python' '/Users/myself/Library/R/x86_64/4.2/library/reticulate/config/config.py' 2> /dev/null
Error in python_config_impl(python) : 
  Error 137 occurred running /Users/myself/.virtualenvs/r-reticulate/bin/python: 
Calls: do.call ... <Anonymous> -> <Anonymous> -> python_config -> python_config_impl
In addition: Warning message:
In system2(command = python, args = shQuote(script), stdout = TRUE,  :
  running command ''/Users/myself/.virtualenvs/r-reticulate/bin/python' '/Users/myself/Library/R/x86_64/4.2/library/reticulate/config/config.py' 2>/dev/null' had status 137
Execution halted
```

all advices are welcome!
thank you

**Comment by cderv** [comment]
You may have something in your document that is changing the default format for `kable()` - this should output markdown

````r
> knitr::kable(head(iris), caption = "An example table caption.")


Table: An example table caption.

| Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|------------:|-----------:|------------:|-----------:|:-------|
|          5.1|         3.5|          1.4|         0.2|setosa  |
|          4.9|         3.0|          1.4|         0.2|setosa  |
|          4.7|         3.2|          1.3|         0.2|setosa  |
|          4.6|         3.1|          1.5|         0.2|setosa  |
|          5.0|         3.6|          1.4|         0.2|setosa  |
|          5.4|         3.9|          1.7|         0.4|setosa  |
````

The default format can be changed by option `knitr.table.format` and seems to have been set for `html` for your session. 
Do you use **kableExtra** for example ? It can do that I think when you load it. 

> not sure if this is related but I also get this kind of errors:

This is an error from **reticulate** which is not finding your python correctly. **reticulate** is used when you are using Python in your Rmd document.

**Comment by antoine4ucsd** [comment]
thank you for the quick reponse!
I only set the following in my code
```
knitr::opts_chunk$set(echo = T,message=FALSE )
```
I did not load kableExtra. 
However, if I open a new session of R and only type your example, it seems to work well.
if I install the pal package, it gives me the following
```
> pal::knitr_table_format('simple')
[1] "html"
```
what would you recommend?
thank you

**Comment by antoine4ucsd** [comment]
this works!
```
options(knitr.table.format = "simple") 
```
thank you
