### ISSUE TITLE
imgur_upload option?

### ISSUE THREAD

**Issue by jonthegeek** [yihui/knitr#2233]
Suggestion for improvement:

`?knitr::imgur_upload` says

> Please register your own Imgur application to get your client ID; you can certainly use mine, but this ID is in the public domain so everyone has access to all images associated to it.

This would be much more feasible if `imgur_upload()` consulted an environment variable (and/or option) for the key.

Right now, when `imgur_upload()` is used inside `reprex::reprex()`, there's no way to pass a key.

I could PR this if you agree, but I'm not sure about testing nor whether there's already a pattern for this sort of thing in knitr.

**Comment by cderv** [comment]
> I could PR this if you agree, but I'm not sure about testing nor whether there's already a pattern for this sort of thing in knitr.

Yes you can PR. We don't currently test it as part of the package - it is tested in [knitr-examples](https://github.com/yihui/knitr-examples/blob/master/010-upload.Rmd)

I don't think it needs further test just replacing the default key  in the function with `key = Sys.getenv("R_KNITR_IMGUR_KEY", <current default>)`. 

Though I don't know if an option or an environment variable is preferred. @yihui do you have a preference ? 

We should probably follow the [pattern of `xfun::tinify()` ](https://github.com/yihui/xfun/blob/b279bbb7bcc881bfbb24a9a903702857fe9aa1c3/R/image.R#L58-L62)which would lead to 

````
getOption("knitr.imgur.key", Sys.getenv("R_KNITR_IMGUR_KEY", <current default value for arg >))
````

**Comment by jonthegeek** [comment]
Environment variables are slightly more GHA-friendly, and I imagine that's a case where this would be used, so option > env > default makes sense to me!

I'll PR this in a sec...
