### ISSUE TITLE
unexpected behavior when table cell ends with a latex space "\ "

### ISSUE THREAD

**Issue by mjsmith037** [yihui/knitr#2308]
**Describe the bug**

When a table cell ends with an explicit space, specified in latex as "\ ", `kable` inappropriately prunes the space, resulting in erroneous latex code that cannot be compiled.

**To reproduce**

```r
library(knitr)
kable(data.frame(x="\\ "), format="latex", escape=FALSE)
```

produces:

```
\begin{tabular}{l}
\hline
x\\
\hline
\\\
\hline
\end{tabular}
```

Note that line 5 of the output should be "\ \\\\" (with a space between the first and second backslashes).

When attempting to compile this, an erroneous `.pdf` is produced:

[test.pdf](https://github.com/haozhu233/kableExtra/files/12441192/test.pdf)

**Session info**

```r
xfun::session_info('knitr')
```

```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.3, RStudio 2023.9.0.463


Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Chicago
tzcode source: system (glibc)

Package version:
  evaluate_0.21   graphics_4.3.0  grDevices_4.3.0 highr_0.10      knitr_1.43      methods_4.3.0   stats_4.3.0     tools_4.3.0    
  utils_4.3.0     xfun_0.39       yaml_2.3.7  
```

Note this issue was previously, erroneously [posted in the `kableExtra` repo](https://github.com/haozhu233/kableExtra/issues/765#issue-1867351239).

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Yes I believe we are trimming whitespace, no matter the escape settings... 🤔 

https://github.com/yihui/knitr/blob/4b47d2a57bd6ac31712d0afafbc4fe968b663c92/R/table.R#L156

@yihui do you think we could have some specific handling in some case ? Either trimming when `escape = TRUE` only ? 

with additional check on whitespace espace sequence depending on format ? 🤔 

Or maybe we need a specific marked string to not trim.... 

Like 
````
data.frame(x=I("\\ "))
````

**Comment by yihui** [comment]
Trailing spaces escaped by `\` are no longer trimmed. Thanks!
