### ISSUE TITLE
export some pandoc syntax helper

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2331]
I saw we have some helpers
https://github.com/yihui/knitr/blob/031e08c74c501e0e1a5d625e0c053977b7a230ec/R/hooks-md.R#L228-L238

What about exporting `pandoc_div` in addition to `knitr::raw_block` (which could probably be rewritten using `fenced_block()` 🤔 

I often try to create some Divs or RawBlock as raw Markdow output, and having hepler function for that (support classes and attributes) can be useful. 

I can also put them in quarto R package directly;

**Comment by yihui** [comment]
I think that's a good idea. I'd probably move them to **xfun**, so they can be shared across more packages.

**Comment by yihui** [comment]
FYI I just added a function `fenced_block()` to **xfun**. Note that classes are just a special case of attributes, i.e., `class = 'foo'` is equivalent to `attr = '.foo'`, so I didn't provide a specific `class` argument to `xfun::fenced_block()`.

**Comment by cderv** [comment]
@yihui this was solved without exporting `pandoc_div()`. Was it a decision ? Do you think it should leave elsewhere ? 

It is quite useful to be able to create Divs syntax using `knitr::pandoc_div() |> knitr::asis_output()`

This function was initially added for internal use with `class.chunk` option and why not exported. 

`xfun::fenced_block()` was exported by note `knitr:::pandoc_div()`

**Comment by cderv** [comment]
I remember now !! 

`pandoc_div` is the same as `fenced_block(.char = ":")` 😅

**Comment by yihui** [comment]
That's right.
