### ISSUE TITLE
include_app 是否可以添加一个 width 参数

### ISSUE THREAD

**Issue by chuxinyuan** [yihui/knitr#2350]
我的[博客](https://cxy.cc/post/2023/03/09/shinyapp/)里需要嵌入一个 [Shiny app](https://shiny.cxy.cc/shinyauthr/)，嵌入后默认的宽度不合适，但是 `include_app()` 里并没有设置宽度的参数。

我目前的解决方案是在 .Rmarkdown 文档渲染得到的 .markdown 文档里调整宽度。为了防止将来 .Rmarkdown 文档更新后覆盖掉我在 .markdown 文档里的设置，索性将调整好之后的 iframe 模块直接放在 .Rmarkdown 里。

这个过程稍有点复杂，因此建议 `include_app()` 和 `include_url` 增加更多的参数设置。

**Comment by yihui** [comment]
用代码段选项 `out.width` 设置宽度。

**Comment by chuxinyuan** [comment]
谢谢！我这思维定势了，潜意识里把这些设置和图片绑定了。
