### ISSUE TITLE
Support for `message = NA` in a different that Quarto would support (using YAML options)

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2375]
Since 1.42, if a user wants the logging in console, `message = NA` or `warning = NA` needs to be used. 

Though Quarto is using YAML format for options
````
#| message: false
````

As `NA` is not something in YAML spec, writing it like this does not work
````
#| message: NA
````

It required to use `!expr`
```
#| message: !expr NA
```
which adds a layer of explanation. 

It would be greate to have another way that can be used in YAML directly. 

Or we could also recognized `message = "NA"` in Quarto context as a the same as `message = NA`

**Comment by yihui** [comment]
Sure, we can support the character string `"NA"`.

**Comment by yihui** [comment]
Done.
