### ISSUE TITLE
line numbering with listings or fancyvrb

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#31]
moved from #29 suggested by @walmes

**Comment by krijkamp** [comment]
> Finally managed to get it all together. Here is the [output pdf](http://dl.dropbox.com/u/1161356/knitr-code-themes.pdf) you are expected to get. You can easily check it out by running the following.
> 
> ```r
> install_packages('knitr', 'ramnathv')
> test_file <- system.file('examples', 'knitr-code-themes.Rnw')
> knit_to_pdf(test_file, theme = 'wombat', line_numbers = TRUE)
> ```
> 
> Can you try this, and let me know if it works? It works for me, but I want to make sure that I have not inadvertently hard-coded something specific to my machine. Once you confirm everything works, I will tighten the documentation, finish the manual, and send you a pull request to merge my changes to your master.

The link provided in the 'output pdf' is not working.
