### ISSUE TITLE
Pdf file too big (maybe compression?)

### ISSUE THREAD

**Issue by Keyeoh** [yihui/knitr#311]
Hi,

I have to plot around 500K points in several figures, and the files knitr is generating are too large. What follows is a small example reproducing the problem:

``` R
\documentclass{article}

\begin{document}

<<calc>>=
d <- data.frame(x=rnorm(500000, 0.1))
d$y <- d$x + rnorm(500000)
@

<<myplot, echo=FALSE, results='hide', out.width='\\linewidth'>>=
library(ggplot2)
p <- ggplot(d, aes(x, y)) +
  geom_point() +
  theme_bw()
print(p)
@

\end{document}
```

The generated PDF file is around 29MB. When I generate it by hand:

``` R
pdf('test.pdf')
p <- ggplot(d, aes(x, y)) +
  geom_point() +
  theme_bw()
print(p)
dev.off()
```

I get a PDF file with size 3.4MB. The files look equal. However, if I re-run the last code but using pdf device option 'compress=FALSE', I get a file with size ~30MB. That made me suspect that maybe knitr was calling with compression deactivated, but that seems strange, since that option is enabled by default.

Thank you for your amazing work. 

Regards,
Gus.

**Comment by jan-glx** [comment]
For others brought here by google: 
The [`ggrastr`](https://github.com/VPetukhov/ggrastr) provides some layers in a rasterized form. This allows you stick with vector graphics for infinitely sharp axis labels while preventing inflation of output file size.
