### ISSUE TITLE
Rrst, Rmd, Rnw conversion tools

### ISSUE THREAD

**Issue by michelk** [yihui/knitr#322]
It would be helpful to have conversion scripts to transform between 

```
Rmd <-> Rrst
Rmd <-> Rnw
Rrst <-> Rnw
```

Shouldn't be too difficult with `pandoc`. I'll see what I can do.

**Comment by giuseppec** [comment]
Hm. Maybe you changed mind after 7 years of more experience?
Do you still see not much value in converting between `*.Rfoo`/`*.Rbar`?

> I do not see much value in converting between these *.Rfoo/*.Rbar documents (source); I would rather converting *.foo/*.bar (output) by pandoc directly.

I'd rather say the other way around makes more sense, doesn't it? 
Because one can always convert a `*.Rfoo` to `.foo`.

**Comment by yihui** [comment]
It is valuable, but not trivial to implement. If you are interested in implementing it, I can tell you my idea of the possible implementation, so you can do it and submit a pull request. Thanks!
