### ISSUE TITLE
Figure reference in Rmd

### ISSUE THREAD

**Issue by michelk** [yihui/knitr#323]
Is there an opportunity to reference figures in Rmd? 

For instance in `Rmd`: 

``````
``` {r plot-ref, fig.cap = "Fancy Caption", fig.ref "fig:plot", echo = FALSE}
plot(1:10, 1:10)
```

As figure \ref{fig:plot} shows ...
``````

which should generate in `md` something like: 

```
[Fancy Caption\label{fig:plot}](figure/plot-ref.pdf)

As figure \ref{fig:plot} shows ...
```
## Update: 

Maybe since image-references are not available within classic-markdown, and the
notation above is anyway a pandoc-extension; it is better to use -- the already
available -- solution: 

``````
``` {r plot-ref, fig.cap = "Fancy Caption\\label{fig:plot}", echo = FALSE}
plot(1:10, 1:10)
```

As figure \ref{fig:plot} shows ...
``````

Then `pandoc` -- in conjunction with `pdflatex`  -- could be used to produce the `pdf`.

**Comment by puterleat** [comment]
If this is still the case, it's currently quite confusing in the docs... They seem to suggest that labels will be based on the chunk name, but they don't appear in my latex output.

**Comment by yihui** [comment]
I think you may add a chunk option `out.extra = ""` to tell knitr to write out figure code using the LaTeX instead of Markdown syntax when the output is LaTeX/PDF.
