### ISSUE TITLE
Calling purl from within a knit document

### ISSUE THREAD

**Issue by csgillespie** [yihui/knitr#332]
If we include `purl` call within a knitr document, i.e.

```
<<echo=FALSE>>=
library(knitr)
purl("tmp.Rnw")
@
```

we get a duplicate label error.

**Comment by adammwilson** [comment]
Is it possible to include the purl'ed .R file as an additional 'output' format without calling purl() separately from within RStudio?  This would be nice for automatically generating both a markdown version _and_ a runnable script at the same time (without worrying about file names, etc.).  So, something like this:

---
title: "knit and purl"
output:
  md_document:
    variant: markdown_github
  r_script  
---

**Comment by adammwilson** [comment]
Answering my own question (in a way), it's possible to achieve my objectives with the following chunk:

```{r, echo=FALSE, message=FALSE, results='hide', purl=FALSE}
input  = knitr::current_input()  # filename of input document
output = paste(tools::file_path_sans_ext(input), 'R', sep = '.')
knitr::purl(input,output,documentation=2,quiet=T)
```

A little clunky, but 5 extra lines isn't too bad...

**Comment by phoede** [comment]
I tried to include a purl call when knitting a .Rmd file and I get a duplicate label error. 
I have found a question on https://stackoverflow.com/questions/36868287/purl-within-knit-duplicate-label-error , so I should not be the only one.
Any ideas?
