### ISSUE TITLE
Changing working directory will impact the location of output

### ISSUE THREAD

**Issue by etiennebr** [yihui/knitr#38]
This is a problem with sweave as well, but when you change a directory
`setwd("aplace")`
this will output the figures and the .tex in `~` directory.  It can even lead to having stuff really scattered.
`setwd("here")
plot(something)
setwd("there")
plot(something)
...`
It can even bring LyX to crash.

**Comment by paulboardman** [comment]
@abnova - rmarkdown set's the working directory to the location of the Rmd file (separately to knitr).

See the following line in render.R (part of the rmarkdown package): https://github.com/rstudio/rmarkdown/blob/28feca137762651c904e05ce119244fc41112fb4/R/render.R#L96

**Comment by abnova** [comment]
@paulboardman Thank you for the comment - I will take a look at that, when I'll get a chance (it's been a while since I was working on that code, but it's good to know nevertheless). Best regards!

**Comment by geneorama** [comment]
I've been using a function that I wrote to set the project directory
https://github.com/geneorama/geneorama/blob/master/R/set_project_dir.R

There's an example in this Rmd file:
https://github.com/geneorama/DataScienceForBusiness/blob/master/Lec3/Lecture_3.Rmd


I don't love my solution, but it works.

**Comment by abnova** [comment]
@geneorama Thank you for the advice, Gene! Will take a look at that.

**Comment by geneorama** [comment]
Thanks, I would be really interested to hear if it works out for you, or if
you have any suggestions for a better coding practice.

**Comment by abnova** [comment]
@geneorama I would love to, but it'll be a while until I'll have a chance to get to my software again - currently I'm focusing my efforts on preparing for my Ph.D. dissertation defense (slides, talk, etc.).
