### ISSUE TITLE
Two chunks in a loop? 

### ISSUE THREAD

**Issue by hongtao510** [yihui/knitr#435]
I am not sure how to realize this. For example, for each iteration of a loop, I need to use the first chunk to generate png pics and print some data. Then in the second chunk, I need to use Latex symbols to format my output page. In my case, a solution is to use two chunks. However, I did not find the right way. 

``` latex
\documentclass{article}
\begin{document}
<<dev='png', fig.width=5, fig.height=4.5, fig.align="center", echo=FALSE>>=
for (i in 1:3){
x = rnorm(1000)
plot(x)
print (summary(i)

<<message=FALSE, fig.align="center", echo=FALSE, warning=FALSE, results='asis'>>=
cat('\\newpage')
}
@
@
\end{document}
```

**Comment by marcofaga** [comment]
Hi. There's a better and updated way to do this?

**Comment by cderv** [comment]
> Hi. There's a better and updated way to do this?

Hi @marcofaga, can you ask your question on https://community.rstudio.com/c/R-Markdown/10 with more details and hopefully an example of what you are trying to do. This would be better than this old issue and would be more aligned with the [issue guide](https://github.com/yihui/knitr/blob/master/.github/ISSUE_TEMPLATE.md). 

Thank you !

**Comment by marcofaga** [comment]
> > Hi. There's a better and updated way to do this?
> 
> Hi @marcofaga, can you ask your question on https://community.rstudio.com/c/R-Markdown/10 with more details and hopefully an example of what you are trying to do. This would be better than this old issue and would be more aligned with the [issue guide](https://github.com/yihui/knitr/blob/master/.github/ISSUE_TEMPLATE.md).
> 
> Thank you !

Thanks. I've already solved!
