### ISSUE TITLE
cannot find objects when knitting in RStudio

### ISSUE THREAD

**Issue by ericpgreen** [yihui/knitr#445]
I am having trouble knitting inline r code. I am working in a project in RStudio (0.97.248). The R chunks work great and produce objects in my workspace. But when I try to run inline code to reference an object created in an R chunk, I can't seem to get it to work. I think the issue has something to do with my workspace and working directory, but I can't figure it out.

I open R Studio by opening myproj.Rproj in the root folder of my project folder "myproj". I verify that my working directory is this root folder via getwd(), and I don't make any changes to the wd. I load an .Rdata file in a subdirectory and run some analysis:

``````
```{r analysis, include=FALSE}
load("input/mydata.Rdata")
x <- mean(mydata$var)
````
``````

When I knit `r x` (there are backticks around this), I get an error that x cannot be found, but I see x in my workspace in RStudio.

If I run the following from cars, I have no problem knitting:

``````
```{r analysis2}
summary(cars)
y <- mean(cars$speed)
```
``````

The mean `r y` prints perfectly.

Do you have any idea why y prints when x won't if both appear in the workspace? I think I am missing something basic about how knitr is communicating with RStudio.

```
R version 2.15.0 (2012-03-30)
Platform: x86_64-apple-darwin9.8.0/x86_64 (64-bit)
```

**Comment by aronlindberg** [comment]
I have a similar problem:

`{r kable, include = TRUE}`
`library(knitr)`
`library(TraMineR)`
`getwd()`
`output <- biofam[1:10,1:3]`
`kable(output)`

This returns:

`Quitting from lines 2-7 (kable.Rmd) `
`Error in eval(expr, envir, enclos) : object 'biofam' not found`
`Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval`
`Execution halted`

What do I need to do to access the object?

**Comment by aronlindberg** [comment]
This is helpful with regards to this issue: http://stackoverflow.com/questions/11155182/is-there-a-way-to-knitr-markdown-straight-out-of-your-workspace-using-rstudio

Seems as if the knit button in Rstudio starts a new session, and therefore the objects cannot be found. The solution is to call `knit()` from another script.

**Comment by yihui** [comment]
@aronlindberg Thanks for the update!

**Comment by snewhouse** [comment]
This is annoying, So the knit HTML button no longer works in Rstudio (Version 0.99.902, Mac OSx, R 3.3.0.)

Keep getting errors as such:

```r
Error in eval(expr, envir, enclos) : object 'Pima.tr' not found
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
```
This works: 
```r
render("./mydoc.md")
```
but loss of that really nice function ` knit HTML` makes teaching this and selling the strength of R/Rstudio etc very difficult with new students now. Please please please fix this.

**Comment by yihui** [comment]
@snewhouse I don't think this is a new issue since a particular version of RStudio. RStudio opens a new R session to knit documents from day one. The error message simply tells you that you didn't create the object `Pima.tr` in the document. You should create it. Do not rely on objects in your current R session. If you pass the document to other people, they will not be able to reproduce your results since they don't have this `Pima.tr`. The R Markdown document should be self-contained and reproducible.

**Comment by snewhouse** [comment]
@yihui sorry man. I complained in haste and over tired! This all works just fine. I had a loooooong Rmd file and had stupidly set `eval=FASLE` in a few chunks and forgot

**Comment by elina800** [comment]
I have a similar problem 2 days and I cannot solve it 
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

I am having trouble knitting and displaying in html Rmarkdown document.


```{r}
theft_time + facet_wrap(~day) + geom_bar() +
 theme_solarized_2(light = FALSE) +
  scale_colour_solarized()
```

Error in eval(expr, envir, enclos) : object 'biofam' not found
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted


While I can run the chunk and display in Rmarkdown the bar charts
I changed many of your prior suggestions ----in vain!!

**Comment by figuepablo** [comment]
Have you tried clearing the Knitr cache?
I had the same issue and solved it that way.

**Comment by Emma-Elcombe** [comment]
I'm having a similar issue. 
When I run the following code in the scripting window using 'Run chunk' it works fine. 
However when I try to 'Knit to Word' I get the error

Code
Ident$site <- ifelse(Ident$`Team Referred To` %like% "Downham", "Downham", 
          ifelse(Ident$`Team Referred To` %like% "Bellingham", "Bellingham"))

Error
Error in Ident$`Team Referred To` %like% "Downham" : could not find function"%like%" Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval <Anonymous> Execution halted

**Comment by shashankp27** [comment]
use attach(dataframe) explicitly. It worked for me when i ran into the same issue!!

**Comment by coolhamid** [comment]
Facing the same issues with R markdown and the Knitr package.Have been getting this error message "Quitting from lines 22-23 (model4.Rmd) 
Error in model.frame.default(formula = Wloss$WeightLoss ~ Wloss$Diet,  : 
  invalid type (NULL) for variable 'Wloss$WeightLoss'
Calls: <Anonymous> ... boxplot.formula -> eval -> eval -> <Anonymous> -> model.frame.default

Execution halted"

Can anyone help please?

**Comment by SWolf23** [comment]
Got the same problem. Then read what @yihui said that Rstudio opens a new R session for the knitting process, my idea was that the enviorment was not taken to the new session. So i solved it by saving my workspace with save.image() before knitting and load it again in the first code chunk with load(). Then all worked fine.

**Comment by JimShady** [comment]
@figuepablo -- How to clear the knitr cache please?

**Comment by artemklevtsov** [comment]
@JimShady simply remove or clean up the cache directory.

**Comment by LeondraJames** [comment]
Having the same issue. Object recognition seems to be a key issue, despite having ran each chunk successfully from top to bottom. However when it comes to knitting, it keeps running into object issues that have already been defined in my global environment.

**Comment by ACMGlueck** [comment]
I have the same issue as the one that started this thread, but without loading the object. The variable is created in the code chunk  -  but then not found a couple of lines later. Here too things work fine when running the code directly, but not when run through knitr (in RStudio). Here's the code snippet that gives this problem (cutoffs is a character vector):

bl.nr <- paste0("vR", cutoffs, "bl.nr")
bl.r <- paste0("vR", cutoffs, "bl.r")
contrasts <- makeContrasts(get(bl.nr)-get(bl.r), levels=dsgn)

And the error is:

Error in get(bl.nr) : object 'bl.nr' not found
Calls: <Anonymous> ... eval -> eval -> makeContrasts -> eval -> eval -> get

I've looked at the various comments above, but they apply to different circumstances. Can anyone help?

**Comment by Rydo111** [comment]
I had the same issue; loading figures would work fine but any other code would fail due to something not being found (everything from functions to data frames...all which were loaded to the workspace prior to knitting). I tried clearing cache...didn't work. I uninstalled and reinstalled; didn't work. I created a VM and installed from scratch; didn't work. I installed pandoc; didn't work. I stuck my tongue out 3 different ways...didn't work ;).

Based on the comment from @SWolf23, I put this code in a chunk at the end of my script:
`save.image("workspace.RData")`

...and this code in a chunk at the start:
`load("workspace.RData")`

Ta da!! Worked. There's a squirrelly path issue going on that I don't understand, but the work-around fixes it.

**Comment by zilinskyjan** [comment]
In case this helps anyone: clicking on "Clear Knitr Cache..." within RStudio may not necessarily remove the "cache" folder - if that happens, you'll want to delete it manually.

**Comment by zeemoliu** [comment]
see there 
https://stackoverflow.com/questions/30519673/cant-resolve-error-in-rmd-file-anonymous-withcallinghandlers-withvisi
"
Solution

Add the following to the top of the .Rmd

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

Short explanation, RMarkdown v1 used error = TRUE by default, but RMarkdown v2 uses error = FALSE. See the link in Josh's comment below. 
"

**Comment by priyanshhgupta** [comment]
> I had the same issue; loading figures would work fine but any other code would fail due to something not being found (everything from functions to data frames...all which were loaded to the workspace prior to knitting). I tried clearing cache...didn't work. I uninstalled and reinstalled; didn't work. I created a VM and installed from scratch; didn't work. I installed pandoc; didn't work. I stuck my tongue out 3 different ways...didn't work ;).
> 
> Based on the comment from @SWolf23, I put this code in a chunk at the end of my script:
> `save.image("workspace.RData")`
> 
> ...and this code in a chunk at the start:
> `load("workspace.RData")`
> 
> Ta da!! Worked. There's a squirrelly path issue going on that I don't understand, but the work-around fixes it.

hey can you please elaborate. I'm a beginner.

**Comment by ricber** [comment]
> 
> 
> see there
> https://stackoverflow.com/questions/30519673/cant-resolve-error-in-rmd-file-anonymous-withcallinghandlers-withvisi
> "
> Solution
> 
> Add the following to the top of the .Rmd
> 
> ```
> knitr::opts_chunk$set(error = TRUE)
> ```
> 
> Short explanation, RMarkdown v1 used error = TRUE by default, but RMarkdown v2 uses error = FALSE. See the link in Josh's comment below.
> "

This solved for me.

**Comment by cderv** [comment]
Hi @ricber 
Please can you open a new issue following the [issue guide](https://yihui.org/issue/). That will be easier for us to understand your remaining problem. Thank you!
