### ISSUE TITLE
100% brew

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#455]
actually it is not too difficult to achieve the same power as [**brew**](http://cran.r-project.org/package=brew) for either `knit_expand()` or inline R code, e.g.

```
{{ if (TRUE) { }}
  text for true
{{ } else { }}
  text for false
{{ } }}

{{ for (i in 1:10) { }}
  text
{{ } }}
```

what I need to do is to check if the expression is complete in one cell; if not, wrap the next text cell as a character string, and move on to the next code cell and check if now the code is complete; ...

``` r
if (inherits(try(parse(text = cell[i]), silent = TRUE), 'try-error') {
  # move on to cell[i+1]
  # change the code to c(cell[i], text[i+1], cell[i+1])
}
# when the code is complete,
# eval(expression) and subsititute all previous cells with the results
```

once the code is complete, evaluate the big expression and replace the original cells with the results

if anyone wants to contribute, please look at `inline_exec()` in R/block.R

**Comment by leipzig** [comment]
sorry to open this up again. If one was to develop a knitr engine for [handlebars](http://handlebarsjs.com/) or another templating engine is there any way for the resulting .Rmd document to then be evaluated by knitr?
