### ISSUE TITLE
Linebreak and Subfigures

### ISSUE THREAD

**Issue by bdhoyer** [yihui/knitr#474]
It seems impossible to define linebreaks between figures in a set of subfigures. Possible fix? Follow-up from this post:
http://stackoverflow.com/questions/12546365/subfigures-or-subcaptions-with-knitr/13667188#comment20664100_13667188

**Comment by Jehops** [comment]
I think you just mean squeeze the plots in one line by "put the desired number of plots in a line", right?  In other words, it's not possible to add a newline after the forth histogram while preserving the subfigure arrangement?

![knitr_nl_subfigures](https://cloud.githubusercontent.com/assets/6874951/10718653/b1c7fbe0-7b56-11e5-8164-027254f36e9b.png)

Below is the code I'm using now.
````
<<hists, fig.align="center", out.width='.49\\linewidth', echo=FALSE>>=
par(mfrow=c(1,2))
hist();hist()
par(mfrow=c(1,2))
hist();hist()
## newline here?
par(mfrow=c(1,2))
hist();hist()
par(mfrow=c(1,2))
hist();hist()
@
````
