### ISSUE TITLE
Wrong tilde inserted into LaTeX

### ISSUE THREAD

**Issue by jaredlander** [yihui/knitr#492]
Run running functions that need a formula, say

``` r
lm(sons ~ fathers, data=heights)
```

The tilde is made into a "high" tilde instead of a "middle" tilde such as generated by $\sim$.

For example

``` r
<<father-son-lm>>=
heightsLM <- lm(sheight ~ fheight, data=father.son)
heightsLM
@
```

results in the following LaTeX

```
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
> heightsLM <- \hlfunctioncall{lm}(sheight ~ fheight, data = father.son)
> heightsLM
\end{alltt}
\begin{verbatim}

Call:
lm(formula = sheight ~ fheight, data = father.son)

Coefficients:
(Intercept)      fheight  
     33.887        0.514  
\end{verbatim}
\end{kframe}
\end{knitrout}
```

and that generates 
![image](https://f.cloud.github.com/assets/628977/203451/af3e64d4-8137-11e2-9279-de09923108d5.png)

This is entirely cosmetic, but actually makes a big typographical difference.  Is it possible to swap ~ with $\sim$ in the code blocks?

**Comment by kendonB** [comment]
@jaredlander Did you solve this one?

**Comment by yihui** [comment]
> This is where I absolutely hate LaTeX.

Hey @yihui you were an idiot. Apparently you had no idea what you were talking about in 2013!

**Comment by jaredlander** [comment]
Yet still more knowledgeable than almost anyone else.
