### ISSUE TITLE
fig.subcap alignment

### ISSUE THREAD

**Issue by jaredlander** [yihui/knitr#493]
When plotting 4 images `knitr` nicely makes a 2x2 grid as such:

```
<<value-by-sq-foot-plots,fig.cap="Housing Scatterplots",out.width='.45\\linewidth',fig.show='hold',fig.scap="Housing Scatterplots">>=
ggplot(housing, aes(x=SqFt, y=ValuePerSqFt)) + geom_point()
ggplot(housing, aes(x=log(SqFt), y=ValuePerSqFt)) + geom_point()
ggplot(housing, aes(x=SqFt, y=log(ValuePerSqFt))) + geom_point()
ggplot(housing, aes(x=log(SqFt), y=log(ValuePerSqFt))) + geom_point()
@
```

![image](https://f.cloud.github.com/assets/628977/213000/cd97d3d4-8349-11e2-912a-b903dd424bda.png)

But when using `fig.subcap` `knitr` tries aligning them in one row and they run off tha page.  I imagine the desired behavior is for them to be a 2x2 grid.

```
<<value-by-sq-foot-plots,fig.cap="Housing Scatterplots",out.width='.45\\linewidth',fig.show='hold',fig.scap="Housing Scatterplots",fig.subcap=c("Natural Scales", "Log x", "Log y", "Log x, Log y")>>=
ggplot(housing, aes(x=SqFt, y=ValuePerSqFt)) + geom_point()
ggplot(housing, aes(x=log(SqFt), y=ValuePerSqFt)) + geom_point()
ggplot(housing, aes(x=SqFt, y=log(ValuePerSqFt))) + geom_point()
ggplot(housing, aes(x=log(SqFt), y=log(ValuePerSqFt))) + geom_point()
@
```

![image](https://f.cloud.github.com/assets/628977/212998/accbc91c-8349-11e2-8896-4da4e485085d.png)

**Comment by douglasguo** [comment]
All we need to do is to add \usepackage{caption} to the beginning.

**Comment by LilithElina** [comment]
Is there any solution by now? The `caption` package won't do it for me, and all solutions I found for the `subfloat` problem in LaTeX would mean using different chunks for the plots and a lot of LaTeX code in between (i.e. not using `fig.subcap` at all). I had hoped it could be easier, since a beginner is supposed to work with my document later on, so I'm trying to keep it simple.
