### ISSUE TITLE
Numbering of figure files

### ISSUE THREAD

**Issue by sebgerdes** [yihui/knitr#505]
Hello!

First of all thanks a lot for this wonderful package!

As I understand / observed the numbering of figure output works as follows:
- if there is only one figure in the chunk, use the chunk name
- if there is more than one figure, use chunk name + index of figure

I would find it more consistent, if even a single figure in a chunk would produce a filename (chunk name + index). Sometimes I include figures from a knitted document in other documents. If I then add a second plot to my knitr document, I have to update all references, which is error-prone.

Just a suggestion...

Thanks and best greetings,
Sebastian

**Comment by siemersn** [comment]
Thanks for your great work!  I use your tools almost every day.

Ah, but now if I am submitting to a journal that demands figures to be named:

Fig-1.tiff, Fig-2.tiff, etc.

How do I do this? I can't give all the chunks the same name.  Right now the best I can do is produce files like:

Fig-1-1.tiff, Fig-2-2.tiff, etc.

*I can rename them by hand of course, but...*

thanks for any pointers.

**Comment by yihui** [comment]
I think that is simply bureaucracy of the journal. This requirement makes no practical sense.

Anyway, assuming you understand the consequence of removing the numeric suffix, here is one possible solution:

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(fig.process = function(x) {
      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
      if (file.rename(x, x2)) x2 else x
    })
    ```

**Comment by siemersn** [comment]
Thank you for this peek into the internals, I will try.

Yes, the requirement seems arbitrary, but not quite as they require the name of the file to exactly match how the Figure is referred to in the manuscript.

**Comment by yihui** [comment]
We just read the paper, and who cares about the filenames behind the scenes :)

**Comment by siemersn** [comment]
;)


Nathan Siemers
Fiveprime.org
