### ISSUE TITLE
knit2wp function does not pick up categories and publish options

### ISSUE THREAD

**Issue by rpodcast** [yihui/knitr#512]
I wanted to use the new `knit2wp` function to create a post in the drafts section of my Wordpress site at [r-podcast.org](http://www.r-podcast.org) which is a self-hosted blog.  While the function successfully made a post, it automatically posted it instead of putting it in draft form and was uncategorized, see post [here](http://www.r-podcast.org/test-from-knitr-to-wordpress/).  The R markdown file was simply the RStudio R markdown default template (with modifications to put the images in my Dropbox according to Yihui's demo [here](http://yihui.name/knitr/demo/wordpress/) and here's the code I used to compile:

```
library(RWordPress)
library(knitr)
knit2wp(input='test_wp.Rmd', title = 'Test from knitr to wordpress',
    categories = c('Articles'), publish=FALSE)
```

Contents of the file can be seen in [this gist](https://gist.github.com/thercast/5309117) in case it helps to debug.

**Comment by joedemby** [comment]
Hi Yihui, Great work on knitr and related packages. I have found them indispensable. I know this query has been closed but I just wanted to let you know I have found a weird solution. Categories works if you set more than one category :) One category does nothing but adding an additional arbitrary category seems to make it work perfectly.

**Comment by yihui** [comment]
@joedemby Thanks for sharing your solution! That sounds like a bug of the RWordPress package.

Anyway, perhaps you have heard about it -- I spent [a whole year last year](https://yihui.name/en/2017/12/blogdown-book/) working on a new package specifically for building websites with R Markdown: https://github.com/rstudio/blogdown

**Comment by joedemby** [comment]
No problem. Just found it by accident. Thanks for the referral of blowdown. I shall look at it right away. :)
