### ISSUE TITLE
Using out.width in opts_chunk$set turns markdown to html

### ISSUE THREAD

**Issue by talgalili** [yihui/knitr#528]
I just used:

opts_chunk$set(out.width = 7)

In a "test.rmd" file which included an image.  But the resulting test.md had HTML syntax instead of markdown syntax...

UPDATE: I see this is how it should be done in markdown, and that the reason I don't see the images is not because of this but because there is the long image format, instead of a link to the image produced....

**Comment by ringprince** [comment]
It's been a while.  But could you elaborate on your UPDATE?  I have the same issue: html in the `.md` which is not tranferred to neither `.tex` nor `.odt` by pandoc.  I take, that it does indeed work, so apparently I am missing something.

(see also [this question](https://stackoverflow.com/questions/40120828/scaling-plots-in-rmd-via-out-width) on stackoverflow)

**Comment by yihui** [comment]
I have posted an answer on SO.

**Comment by ringprince** [comment]
Thanks!
