### ISSUE TITLE
cache dependencies

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#592]
I noticed an issue with dep_auto.

First run the following code:

``` s
library(knitr)
knit(output='test.tex', text='
<<conf, cache=FALSE>>=
opts_knit$set(verbose=TRUE)
opts_chunk$set(cache=TRUE, autodep=TRUE, error=FALSE)
dep_auto()
@
<<chunk1>>=
x <- 1
@
<<chunk2>>=
x
@
')
```

If you later add the following chunk between chunk1 and chunk2

``` s
<<chunk1b>>=
x <- 2
@
```

cache for chunk2 is not invalidated.

**Comment by robertamezquita** [comment]
Extending this, I want to ask about cache dependencies such as packages - if a package version changes, it would be desirable to re-run the chunk for long-term maintenance projects. The natural solution is to simply not cache, but for computationally expensive tasks it would be nice to have the cache fallback option (and also, indirectly, could serve as a way to flag chunks that are affected by package version changes).

**Comment by yihui** [comment]
> and also, indirectly, could serve as a way to flag chunks that are affected by package version changes

Hope this gives you an idea: https://yihui.name/knitr/demo/cache/#even-more-stuff-for-cache
