### ISSUE TITLE
Feature request: Support for CairoWin

### ISSUE THREAD

**Issue by paullemmens** [yihui/knitr#596]
Being forced on Windows and needing to use the boss' Word templates I would like to use WMF/EMF files as output of my knitr Rmd documents so my Word documents have nicely scaling graphics. Recently I discovered the even nicer Cairo graphics but unfortunately knitr only supports base R's `win.metafile` device.

Based on the code in plot.R, it appears fairly easy to add support for CairoWin. See following patch. However, I am not sufficiently familiar with coding R packages as well as the internals of knitr to see whether other stuff needs to be changed or compile the package and test the changes.

``` diff
diff --git a/R/plot.R b/R/plot.R
index 9602499..8b160aa 100644
--- a/R/plot.R
+++ b/R/plot.R
@@ -9,7 +9,7 @@ auto_exts = c(
   quartz_bmp = 'bmp',

   CairoJPEG = 'jpeg', CairoPNG = 'png', CairoPS = 'eps', CairoPDF = 'pdf',
-  CairoSVG = 'svg', CairoTIFF = 'tiff',
+  CairoSVG = 'svg', CairoTIFF = 'tiff', CairoWin = 'emf',

   Cairo_pdf = 'pdf', Cairo_png = 'png', Cairo_ps = 'eps', Cairo_svg = 'svg',

@@ -99,6 +99,7 @@ save_plot = function(plot, name, dev, width, height, ext, dpi, options) {
     CairoPS = load_device('CairoPS', 'Cairo'),
     CairoPDF = load_device('CairoPDF', 'Cairo'),
     CairoSVG = load_device('CairoSVG', 'Cairo'),
+    CairoWin = load_device('CairoWin', 'Cairo'),

     Cairo_pdf = load_device('Cairo_pdf', 'cairoDevice'),
     Cairo_png = load_device('Cairo_png', 'cairoDevice'),
```

**Comment by petetalbert** [comment]
I have a workaround that I've been trying: save your ggplot like so: `ggsave("plot.svg")` and then outside the chunk `![](plot.wmf)`. This works for PowerPoint.

Using `fig.ext='emf'` or `fig.ext='wmf'` never worked for me on Win 10.

**Comment by yihui** [comment]
@petetalbert Did you mean `dev = 'win.metafile'` never worked?

**Comment by petetalbert** [comment]
> @petetalbert Did you mean `dev = 'win.metafile'` never worked?

Nevermind, I didn't have  `dev = 'win.metafile'`! That plus `fig.ext='emf'` gives me windows metafiles in my PowerPoints. Awesome! Thanks, @yihui!

**Comment by yihui** [comment]
@paullemmens Glad to know that!
