### ISSUE TITLE
Chunk option `fig.align` causes image tags to be created in .html

### ISSUE THREAD

**Issue by rnorberg** [yihui/knitr#611]
I frequently write Rmd files in RStudio and then `knit` them using the built in `knitHTML` button. Occasionally I like to produce something other than an html file from my code though. For this, I use `pandoc()` to convert the markdown file that is produced with each click of the `knitHTML` button into some other document type (mostly .docx files). 

I always set several chunk options globally at the beginning of each Rmd document I create, like so:

```
opts_chunk$set(comment=NA, fig.height=8, fig.width=7, fig.align='center')
```

This always resulted in normal markdown-style image tags in the knitted .md file. An example:

```
![plot of chunk BoxPlots](Some_Path/BoxPlots.png) 
```

I noticed this was no longer the case after updating to the most recent version of `knitr` because when I called `pandoc()` to convert my .md file to a .docx, no images appeared in the resulting Word file. After some exploration I found that my images were now html tagged in the .md file. An example:

```
<img src="Some_Path/BoxPlots.png" title="Box Plot" alt="Box Plot" style="display: block; margin: auto;" />
```

This is what was causing my images to no longer appear in my converted Word files. I traced this back to the chunk option `fig.align`. If I remove this setting from my global chunk settings at the beginning of the document, all of my image tags are as they should be and the .md file converts to .docx perfectly. If I set the option for just one chunk, the figure tag(s) produced by that chunk are .html tags and all of the other figure tags are markdown-style. 

I realize that setting this option makes no difference in the resulting .md file, so you might make the argument "Why are you using it anyway?", but I don't ignore the .html file produced. I'd like to be able to specify how the .html file appears and still be able to convert the .md file to some other file format if need be.

Also, I had code that "worked" and after installing the new package, it "broke", so I thought I might help some others having this issue.

Thanks for the great package!

**Comment by victoriahe** [comment]
![image](https://user-images.githubusercontent.com/48701348/54575115-277e9b00-49f3-11e9-990b-37a09c5210e8.png)

can you guys solve this.
I use this, but I can´t because it appears
![image](https://user-images.githubusercontent.com/48701348/54575160-4da43b00-49f3-11e9-8db3-98849e8326a0.png)
