### ISSUE TITLE
Inline code chunks are broken by linebreaks

### ISSUE THREAD

**Issue by aammd** [yihui/knitr#655]
When a .Rmd file is written in a text editor that wraps lines at a ruler, sometimes a linebreak falls in the middle of an inline code chunk.  This causes an error when the document is knit. Is it possible to modify knitr to ignore linebreaks in inline code chunks?

Also see http://stackoverflow.com/q/19819972/559676

**Comment by isomorphisms** [comment]
I'm still getting this error, apparently a couple years after the fix. `rmarkdown::render("my file.Rmd", "my file.html")` is my incantation.

**Comment by yihui** [comment]
@isomorphisms A minimal reproducible example please. This works for me:

    aaa `r 1+
    1` bbb
