### ISSUE TITLE
control space padding in kable_markdown

### ISSUE THREAD

**Issue by gavril0** [yihui/knitr#699]
I have installed the latest version of knitr on http://rforge.net/knitr/ (version 1.5.15). 

Using argument sep.col of kable.mark in kable gives an error:

``` s
> x<-data.frame(A=c(1.21234,2.1234,3.1213),B=c("A","B","C"))
> kable(x,sep.col=' ', digits=2)
Error in kable_markdown(x = c("1.21", "2.12", "3.12", "A", "B", "C"),  : 
  unused argument (sep.col = " ")
```

It would be helpful to allow the control of the amount of space in the columns which can be done I think by givin this extra argument in kable.markdown and transmitting it to kable.mark.

Best,

Gabriel

P.S. I have change the name of the issue to reflect better the actual question (see my comment below).

**Comment by ricardobatistad** [comment]
It would be helpful to have the `padding` feature available for `format = "latex"` as well.
