### ISSUE TITLE
`knit` may produce plots from chunks that overwrite others

### ISSUE THREAD

**Issue by kevinushey** [yihui/knitr#704]
An example `.Rmd` file:

``````
```{r test}
plot(1)
plot(2)
```

```{r test1}
plot(3)
```
``````

Calling `knit` on this file produces the `.md` file

``````
```r
plot(1)
```

<img src="figure/test1.png" title="plot of chunk test" alt="plot of chunk test"  />

```r
plot(2)
```

<img src="figure/test2.png" title="plot of chunk test" alt="plot of chunk test"  />



```r
plot(3)
```

<img src="figure/test1.png" title="plot of chunk test1" alt="plot of chunk test1"  />
``````

where the plot from the first chunk, written to `test1.png`, is overwritten by a single plot generated from the second chunk with name `test1`. I imagine there are other scenarios where such an error can occur. It's slightly convoluted, but I only report it because someone else ran into it (get enough users and all bugs become exposed :))

Is there any way `knitr` could detect and warn the user when such an event happens? Alternatively, could there be a more robust naming scheme to avoid such conflicts? (I imagine this is less likely due to the maturity of `knitr` now.)

**Comment by rubenarslan** [comment]
I'm running several knitr documents with clashing chunk names in parallel on our compute cluster.
The figures by the script that terminates earlier get overwritten. It's a small annoyance but I have to put each script into its own folder and fix the paths and so on.
Rmarkdown makes a file-name specific figure folder, right? Unfortunately I cannot install pandoc on the cluster. Might knitr move to this behaviour as well?

**Comment by yihui** [comment]
@rubenarslan You can define your own knitting function and modify the chunk options, e.g.

```r
knit2 = function(input, ...) {
  prefix = tools::file_path_sans_ext(basename(input))
  library(knitr)
  opts_chunk$set(
    fig.path = paste0(prefix, '/figure/'),
    cache.path = paste0(prefix, 'cache/')
  )
  knit(input, ...)
}
```

**Comment by rubenarslan** [comment]
Thanks, good idea!
I can't use rmarkdown on the cluster unfortunately. I think the step `.Rmd` to `.md` in rmarkdown is pure knitr action, but it still fails because pandoc is not installed.

**Comment by yihui** [comment]
@rubenarslan If your cluster is Debian/Ubuntu based, it will be easy to install Pandoc without root privilege, otherwise I'm afraid you will have to use the workaround I provided.
