### ISSUE TITLE
Animated plots, hook_ffmpeg_html and video format

### ISSUE THREAD

**Issue by basille** [yihui/knitr#712]
Since knitr 1.3, animated plots using `hook_ffmpeg_html` uses OGG video flies instead of MP4. I think it is a sensible default (although WebM would be equally good, according to [browser support](http://www.w3schools.com/html/html5_video.asp). However, would it be possible to have the file type as an option, so that people could, if needed, switch to MP4? 

It might be already possible, in which case I apologize: I couldn't find a way to do it. As far as I understand it, the file type is hard-coded in `hook_ffmpeg_html`:

```
mov.fname = str_c(sub(paste(fig.num, "$", sep = ""), "", 
    x[1]), ".ogg")
```

After a couple of trials, I couldn't find a way to do it manually. For instance, modifying directly `hook_ffmpeg_html` using:

```
knit_hooks$set(hook_ffmpeg_html = function(x, options) 
    ...
    mov.fname = str_c(sub(paste(fig.num, "$", sep = ""), "", 
        x[1]), ".mp4")
    ...
```

does nothing: output is still a OGG file. Or setting up a new `hook_ffmpeg_html_mp4`, which would be called by `opts_knit$get(animation.fun = hook_ffmpeg_html_mp4)`, results in an error. In the end, I'm not too sure what to modify or what option to change to make this choice possible.

By the way, I'm using knitr 1.5.
Mathieu.

**Comment by yihui** [comment]
FYI, I just added a chunk option `ffmpeg.format` so you can easily change the video format from the default webm to mp4 by using the chunk option `ffmpeg.format = 'mp4'`.

**Comment by basille** [comment]
Hey Yihui,

This looks great! Did the new option make it to v1.11? I couldn't have it work, with e.g. `ffmpeg.format = "mp4"`. Shall I use the dev version instead?

In addition, does the option allow to change other settings, or is it necessary to go through `opts_knit$set`/`hook_ffmpeg` for detailed settings?

Thanks for your work!
Mathieu.

**Comment by yihui** [comment]
@basille It is in the development version: https://github.com/yihui/knitr/blob/master/NEWS.md (1.12 is not released yet) This option does not allow you to change any other settings.

**Comment by petrelharp** [comment]
ffmpeg [currently](https://trac.ffmpeg.org/ticket/5108) has a bug in its png -> webm output, so having an easy way to fall back on mp4 is timely.
