### ISSUE TITLE
Unneeded warnings  when creating plot using non-default fonts

### ISSUE THREAD

**Issue by yixuan** [yihui/knitr#729]
Take this code snippet as an example (assuming "Ubuntu" font is installed in the system):

```
\documentclass{article}
\begin{document}

<<dev='png'>>=
library(ggplot2)
ggplot() + geom_point(aes(x=mpg, y=wt), data=mtcars) +
    theme(text = element_text(size = 16, family = "Ubuntu"))
@

\end{document}
```

When compiling this with knitr, the output pdf will contain a long list of warnings similar as below:

```
## Warning: font family 'Ubuntu' not found in PostScript font database
```

However, if we call the device function directly,

```
png()
library(ggplot2)
ggplot() + geom_point(aes(x=mpg, y=wt), data=mtcars) +
    theme(text = element_text(size = 16, family = "Ubuntu"))
dev.off()
```

then there is no such warning issued.

I believe this is caused by the null graphics device `pdf(NULL)`. From my understanding knitr will evaluate code chunk on this null device and record the plotting operations to some objects. However, `pdf()` only support standard fonts like "Times" and "Courier", and will yell to other fonts that it does not recognize.

The "real" null device mentioned in http://yihui.name/en/2010/12/a-special-graphics-device-in-r-the-null-device/ is already removed from R. Is there any other approach to solve this problem?

**Comment by hrbrmstr** [comment]
possibly also solved by using `extrafont::loadfonts()` in a hidden markdown block?

**Comment by yihui** [comment]
I think this specific problem has been solved long ago. When `dev='png'`, **knitr** will just use a `png()` device to record plots instead of the null `pdf()` device.

**Comment by bhaskarvk** [comment]
FWIW I am still seeing this bug and I do need to use the workaround mentioned in https://github.com/yihui/knitr/issues/729#issuecomment-40336104

**Comment by JerryWho** [comment]
I still have this problem, too. My problem isn't resolved with this work around. The work around seems only to work with pdflatex or lualatex. But I habe to use xelatex.
With xelatex there aren't any fonts in the graphics.
This document only gets this output 

	\documentclass{article}
	\usepackage{graphicx}

	\begin{document}
	<<set-options>>=
	 Sys.setenv(LANG = "en")  
	 options(device = function(file, width, height) {
	  png(tempfile(), width = width, height = height)
	})
	@
	 \begin{figure}
	    \centering
	<<output, dev='png'>>=
	library(ggplot2)
	ggplot(mtcars, aes(x=wt, y=mpg, color=factor(gear))) + geom_point() +
	 ggtitle('Fuel Efficiency of 32 Cars') +
	 xlab('Weight (x1000 lb)') + ylab('Miles per Gallon') +
	 theme(text=element_text(size=16, family='Source Code Pro'
	 ))
	@
	   \end{figure}


	\end{document}

![image](https://user-images.githubusercontent.com/15584/34319745-04329924-e7ea-11e7-9233-226c6d23741b.png)

(I'm using an extra example because I'm using a Mac and don't have this Ubuntu font. So I use Source Code Pro.)
