### ISSUE TITLE
Access to chunk label

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#73]
Is there some way to access the label within the chunk?
I tried "opts_chunk$get("label")" but I don't get anything...

**Comment by yihui** [comment]
No. There are many things that won't work in the notebook mode. If you need these advanced features, you have to fully compile an Rmd document (instead of running chunks individually).

**Comment by MichaelBeyeler** [comment]
@yihui Is there a comprehensive list of things that don't work in notebook mode?

**Comment by yihui** [comment]
@mjbeyeler No. In general, a GUI (e.g. RStudio) cannot do everything that code (e.g. **knitr**) can do. GUI is more for convenience, and code is for flexibility/power.
