### ISSUE TITLE
more options for scianimator

### ISSUE THREAD

**Issue by stla** [yihui/knitr#762]
Hi,
 There are many possible settings/options with [scianimator](https://github.com/brentertz/scianimator), but currently almost none is not supported by knitr. It would be nice to allow the control of some options (such as disabling the keyboard controls, removing the button for the speed control...)

**Comment by yihui** [comment]
I decided not to implement this any more, since I have lost interest in this scianimator library (it was last updated in 2011). GIFs and videos are much easier to create and also popular today.
