### ISSUE TITLE
In line source code of functions crashes 

### ISSUE THREAD

**Issue by mdavy86** [yihui/knitr#773]
Running `r date` to view the source code rather than execute it inline (or any other function) causes a crash when knitr compiles the html

```
label: unnamed-chunk-2
  |.................................................................| 100%
   inline R code fragments

Quitting from lines 25-52 (knitrInlineError.Rmd) 
Error in vapply(x, format_sci_one, character(1L), ..., USE.NAMES = FALSE) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 2
Calls: knit ... inline_exec -> hook -> .inline.hook -> format_sci -> vapply

Execution halted
knitr terminated with status 1
```

An example is available in the following gist

https://gist.github.com/mdavy86/c0d40c9f16f7bb6d32d7

**Comment by Dulani** [comment]
Just ran into this myself on a very complicated multi-document "Word Merge" project (that has been made FAR easier with `knitr`, thanks @yihui).  

I'm a decent R troubleshooter, but spent HOURS looking for the source of the error.  I ultimately didn't find what was causing the error until I Googled `Error in vapply(x, format_sci_one, character(1L), ..., USE.NAMES = FALSE) : values must be length 1` and landed on this page (which gave me a clue that I had a set of inline functions that were returning nothing for a certain case).

So, what I suggest/request is: 
1. Can we find a way to make sure that the error is more descriptive? 
2. Can we just return an empty string when the result of an inline function is truly empty?

I'm happy to help with a PR if that would be of interest and I can find the appropriate place in the code to fix it.

**Comment by yihui** [comment]
@Dulani Sorry about that. I think it makes perfect sense to make the error more descriptive! Thank you!

**Comment by petyaracz** [comment]
Since this is the top google search hit for the error message, I'd like to add that you get the message when trying to display the formula of a generalised additive model object (`modelname$formula`). If you embed it into a print function (`print(modelname$formula`) the error goes away.

**Comment by bhive01** [comment]
Add myself to the pile that had no clue what this error meant. I was trying to plot in an r snippet rather than a chunk because... why can't I? 
Well, a more helpful error message that would ask:
"Did you pass a non-coercible to character object in an R snippet? Use a chunk instead."
Perhaps that's not descriptive enough?

**Comment by ghidora77** [comment]
I got this error when I removed a variable from a code chunk, but accidentally left the variable as a snippet in the text - it was hard to debug, because the line it says was the error was not the correct line, I figured it out by creating a copy and removing portions until I got it to work.
