### ISSUE TITLE
! Font T1/pplj/m/n/10=pplr9d at 10.0pt not loadable: Metric (TFM) file not found

### ISSUE THREAD

**Issue by yihui** [yihui/knitr#778]
When seeing this error message in the knitr graphics manual, install these packages:

```
tlmgr install palatino mathpazo fpl
```

(This issue is purely for SEO purposes in case I forget it in the future.)

**Comment by neilernst** [comment]
thanks!

**Comment by adamcrussell** [comment]
> When seeing this error message in the knitr graphics manual, install these packages:
> 
> ```
> tlmgr install palatino mathpazo fpl
> ```
> 
> (This issue is purely for SEO purposes in case I forget it in the future.)

If you are using MacPorts then tlmgr is not supported for the sensible reason that having a package manager within a package manager creates a lot of trouble. But getting these packages is simply as easy as `port install texlive-fonts-recommended`

**Comment by yihui** [comment]
@adamcrussell This issue was created more than six years ago. Now if you use TinyTeX (https://yihui.org/tinytex/), you should not run into the problem of missing LaTeX packages any more.
