### ISSUE TITLE
In-place knitting

### ISSUE THREAD

**Issue by krlmlr** [yihui/knitr#785]
Assume you want to author a scientific document together with somebody who doesn't know, use, and/or want to install R and learn how to knit. Currently this seems to imply abandoning `knitr` for writing the document.

How about adding support for reading _and_ writing LaTeX, or  Markdown? This means that all chunks must be comments in the document format, and the output of the chunks must be recognizable. Something like this:

```
%+ echo=T, message=F
%2 + 3
%
%% BEGIN_KNITR_OUTPUT
\#\# 2 + 3
5
%% END_KNITR_OUTPUT
```

Probably this only works well if there's some kind of version control behind.

Do you think such a feature would be useful? Perhaps this has been discussed before, and I'm missing something obvious.

**Comment by krlmlr** [comment]
Thanks! This looks nice, but also slightly difficult to parse for humans...

**Comment by yihui** [comment]
The obvious goal is to avoid human parsing the JSON file, but building a GUI for it is not something I can do in an afternoon, so...

**Comment by ramnathv** [comment]
This is awesome @yihui. I will play with it and see if I have ideas/code that I can contribute!

**Comment by yihui** [comment]
Thanks! Please do me a favor not to promote it at the moment (e.g. on Twitter), since I do not want to waste everybody's time and I'm still weighing this new JSON format and the popular rmarkdown format. It is possible that I may give up the JSON idea at some point.

**Comment by ramnathv** [comment]
I understand. If would like to collaborate on this with you, if you would like that. If I have any thoughts, would you prefer I share it on github or do you want me to email you.

**Comment by yihui** [comment]
@ramnathv You can email me first. Thanks!
