### ISSUE TITLE
showtext package integration

### ISSUE THREAD

**Issue by yufree** [yihui/knitr#799]
## Description

When I try to knit Chinese into a PDF from Rmd, the Chinese can't be seen in the PDF. But the Chinese could be seen in html and doc with a warning. Then I loaded the `showtext` package, the warning disappeared in the html and doc but still no Chinese in PDF.  I referred to the log and found Rmd produce PDF for each picture, so I think the Rmd may use the PDF as default output device. If knitr could integrate the showtext package for the PDF device or define a new device for output, the user may feel free to use some font without considering the font or encode issues.

p.s. this issue may have some similarity with this [one](https://github.com/yihui/knitr/issues/527), but I think using `showtext` package will cover this problem.

```
sessionInfo()

## R version 3.1.0 (2014-04-10)
## Platform: i686-pc-linux-gnu (32-bit)
## 
## locale:
##  [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
##  [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
##  [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
## [1] digest_0.6.4     evaluate_0.5.5   formatR_0.10     htmltools_0.2.4 
## [5] knitr_1.6        rmarkdown_0.2.46 stringr_0.6.2    tools_3.1.0     
## [9] yaml_2.1.13
```
## Example

``````

---
title: "test"
author: "yufree"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
  html_document: default
  word_document: default

---

中英文混合

This is an R Markdown document. 

```{r}
library(showtext)
showtext.begin()
plot(cars,main='中文issue')
plot(cars,main='中文issue2')
showtext.end()
```
完
``````

**Comment by yangbenfa** [comment]
header.tex文件在哪里找到

**Comment by yufree** [comment]
@yangbenfa 自己新建一个header.tex文档放在需要编译的rmd文档目录下，里面加入需要的tex代码即可在文档编译时调用，不过眼下用rticles包的中文模版就可以了

**Comment by yangbenfa** [comment]
@yufree 好的，谢谢！，因为使用rticles，只显示了图片中的中文，而正文中文没显示 ，故还是使用header.tex来尝试一下，

**Comment by yihui** [comment]
@yangbenfa 不太可能吧，rticles里的中文我都设置好了啊，是不是你没有安装文章中说的字体？https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd

**Comment by yangbenfa** [comment]
@yihui 是的，安装了字体后，使用CTeX Documents模版，不显示中文，只有英文，于是，我就修改了其中一行，classoption: "hyperref`r if (.Platform$OS.type != 'windows') ',nofonts'`"
改成了classoption: nofonts；结果连英文都不显示了，直接报错，信息如下：

output file: 转pdf，中文问题1.knit.md

! Undefined control sequence.
l.75 ...�题。当然这句话得站在巨人\href

pandoc: Error producing PDF from TeX source
错误: pandoc document conversion failed with error 43
停止执行

**Comment by yangbenfa** [comment]
最后的解决方案是，修改 "R/i686-pc-linux-gnu-library/3.1/rmarkdown/rmd/latex" 下 default.tex 文档，在 \begin{document} 之前加入字体，搞定，测试结果
---
title: "test"
author: "test"
date: "2015年7月1日"
output: 
  pdf_document: 
    latex_engine: xelatex
---

你好


```{r, echo=FALSE,fig.showtext=TRUE}
plot(cars,main="你好")
```

**Comment by yangbenfa** [comment]
由于没有调用模版，故排版很差，于是就调用CTeX Documents模版信息，增加一行 template: !expr rticles::ctex_template()，结果又抱错了，为什么，不使用模版，一切正常，使用了模版，就错误，如下：
! Undefined control sequence.
l.75 ...�题。当然这句话得站在巨人\href

pandoc: Error producing PDF from TeX source
错误: pandoc document conversion failed with error 43
停止执行

**Comment by yangbenfa** [comment]
弱弱的问一句，其实只要中文显示好了，一旦生成pdf文件，不管对方是windows，还是Linux，都可以打开，并正常显示吧，
所以，我觉得“装鸵鸟，把头埋沙子里，自己默念一百遍“别人都不用Windows，我只管我的系统上的字体能用就好了”；”这句话似乎不成立

**Comment by yangbenfa** [comment]
经过一番尝试，终于解决，原来问题出在这里classoption: "hyperref`r if (.Platform$OS.type != 'windows') ',macfonts'`"，使用模版也可以了

**Comment by yufree** [comment]
@yangbenfa 看你用macfonts这个选项了，说明ctex已更新。我查了下 https://github.com/CTeX-org/ctex-kit 确实对mac系统支持了macfonts选项，那么rticles里可能要做点更新，感谢提醒！
@yihui 是不是classoption可以写成下面这样？

    classoption: "hyperref`r if (Sys.info()["sysname"]== 'Linux') ',nofonts' else if (.Platform$OS.type == 'Darwin') ',macfonts' `"

**Comment by yihui** [comment]
@yufree 好，那确实需要更新文档了。我最近有点忙，你要是找出来毛病在哪儿欢迎提交PR。谢谢！

**Comment by yufree** [comment]
@yihui 额，我先给一个比较脏的skeleton修改yaml临时方案吧：

    classoption: "hyperref`r ','`"

目前ctex也不建议自己调字体，那就直接忽略算了，过会我PR过去，不过模版里的文本估计要重新组织，我暂时会在模版里加一个说明，因为估计多数没意识到latex的包也会出现大更新。

**Comment by yihui** [comment]
文本已经大致重新组织了一下。至于Pandoc模板是啥问题，就留给你慢慢研究了。

**Comment by yufree** [comment]
@yihui 谢大辛苦 pandoc模版似乎没问题 是我当时没理解hyperref这个选项跟您做的修改 重新尝试已经没问题了 
ps: 在yaml里写r代码这个黑魔法很赞

**Comment by andyfayecindy** [comment]
@yangbenfa 我 include header.tex 后生成的tex文件中文也是乱码，请问这个问题你解决了吗？

**Comment by andyfayecindy** [comment]
@yihui 
---
title: "这是一个标题"
output:
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: yes   
    latex_engine: xelatex
  word_document: default
  html_document: default
---

 中文 

header.tex 文件
\usepackage{ctex} 

pdf可以显示中文，但是生成的tex文件中文都是乱码，并没有把中文包包含近来，怎么修改呢？

**Comment by palooney** [comment]
请问header.tex这个文件需不需要加上\begin{document}之类的code？还是只需要\usepackages{...}就可以了？

**Comment by yihui** [comment]
不需要。后来者请不要再在这个帖子底下回复，中文Markdown转CTeX/LaTeX/PDF的问题早已经在rticles包中解决了：https://github.com/rstudio/rticles
