### ISSUE TITLE
Figure and table references

### ISSUE THREAD

**Issue by krlmlr** [yihui/knitr#805]
Currently, referencing figures and tables in knitr documents is a bit difficult. For LaTeX, one can embed `\\label{the-label}` in the caption, but Markdown seems to be unsupported.

I propose a solution that could work the same way with all backends. Example: The `kable` function would support an additional argument `label`, with different handling for different backends.
- Pandoc: `Table #:` is prepended to the caption, the number is associated with the label in some internal cache (where?)
- HTML: Similar
- LaTeX: `\\label{...}` is inserted in the caption

There'll also be a counterpart, a function `ref(label)`, that does the following:
- Pandoc and HTML: Write `Table #`
- LaTeX: Write `Table \\ref{...}` or `\\cref{...}`

It would be used in the following way in `.Rmd` documents:

```
`r ref("the-label")`
```

Similar considerations for figures.

Of course, for Pandoc and HTML, forward references will have to be handled by `knitr` itself. With a warning in case recompilation is required.

Thoughts?

**Comment by krlmlr** [comment]
Solved by the [captioner](https://github.com/adletaw/captioner) package.

**Comment by adamryczkowski** [comment]
@krlmlr  No, it is not 100% solved. The `captioner` package doesn't play along LaTeX native labels - it just reinvents them in the R level. I'd say it is more a walkaround.

**Comment by yihui** [comment]
I ended up with hacking at this problem in the bookdown package: https://bookdown.org/yihui/bookdown/a-single-document.html

**Comment by jpolonsky** [comment]
What would be the way to get this to work in a standard .Rmd file, e.g. tufte handout? Would a call be needed to the bookdown package?

**Comment by yihui** [comment]
@jpolonsky You can use the output format `bookdown::tufte_html2` (or `_handout2` or `_book2`). For future questions, please consider asking on StackOverflow first: http://stackoverflow.com/questions/tagged/knitr Thanks!
