### ISSUE TITLE
Fig.cap not working

### ISSUE THREAD

**Issue by andersgs** [yihui/knitr#820]
Hi. I am trying to add a caption to a figure, but nothing shows up in the PDF. I am using RStudio (0.98.932) + knitr 1.6 + markdown on a Mac with MacTex installed. The following code does not produce a caption, for instance.

``````

---
title: "Test"
author: "Me"
date: "28 July 2014"
output: pdf_document

---

This is an R Markdown document. Markdown is a simple formatting syntax for
authoring HTML, PDF, and MS Word documents. For more details on using R Markdown
see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes
both content as well as the output of any embedded R code chunks within the
document. You can embed an R code chunk like this:

```{r}
summary(cars)
```

You can also embed plots, for example:

```{r, echo=FALSE,fig.cap="Test"}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent
printing of the R code that generated the plot.
``````

**Comment by Masood87** [comment]
I was struggling with this too, until I found the answer on [stackoverflow](https://stackoverflow.com/questions/27444804/some-figure-captions-from-rmarkdown-not-showing).

Basically, you have to insert an empty line after the code chunk that generates the captioned plot.
