### ISSUE TITLE
cache.lazy=FALSE results in no caching

### ISSUE THREAD

**Issue by liz-is** [yihui/knitr#822]
I'm working with some large genomics datasets. Lazy-loading doesn't work with these, so I'm using chunk options `cache=TRUE, cache.lazy=FALSE` to cache them. However this also doesn't lead to caching - those chunks get re-run every time.

There's a reproducible example without any big data involved [here](https://github.com/liz-is/misc) - the chunk with `cache.lazy=FALSE` is re-evaluated each time, resulting in a different time stamp from the chunk with `cache.lazy=TRUE`.

Am I doing something wrong or is this a bug?

Thanks!

**Comment by roryk** [comment]
Hi Yihui,

I have this same problem, caching some sleuth (https://github.com/pachterlab/sleuth) objects-- setting cache.TRUE and cache.lazy in a chunk results in no caching for that chunk. I tried Liz's great example and it works fine. Do you have any tips?

**Comment by yihui** [comment]
@roryk Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
devtools::session_info('knitr')
```
