### ISSUE TITLE
Controlling chunk evaluation order

### ISSUE THREAD

**Issue by kohske** [yihui/knitr#868]
Sometimes a chunk needs the results generated in subsequent chunks. E.g., 
http://stackoverflow.com/questions/18581027/

Does knitr have a plan to implement the ability to control the evaluation order of chunks?
If so, I think the inline chunk should also handle this.

**Comment by danachandler** [comment]
Hi @yihui -- I was just wondering what's the latest and greatest way to do this? Is there any easier way with all the innovation and great work from bookdown? 

PS. Thanks for all your great work on making document preparation less terrible!

**Comment by yihui** [comment]
@danachandler No, nothing new so far. `cache=TRUE` + `knitr::load_cache()` is still the only solution on top of my mind.

**Comment by retorquere** [comment]
Is this still supposed to work? I've knitted it a few times with several restarts but I always get `For example, there is no object called y that has been created in this document yet, but we can still insert it here: 6.2831853,`
