### ISSUE TITLE
chunk names must be unique between knitr documents in same directory

### ISSUE THREAD

**Issue by v-a-s-a** [yihui/knitr#875]
This may be a user error/workflow problem rather than an issue with knitr itself, but I was just burned by this.

If you have multiple knitr documents (say Rmarkdown files) in a single directory _all chunks producing figures should have unique names between those documents_! My workflow consists of writing .Rmd documents, converting those to regular Markdown, and using [pandoc](http://johnmacfarlane.net/pandoc/) to produce a final PDF. From what I can tell, this is a pretty common workflow.

If .Rmd files produce figures with the same chunk name, then only the last figure produced remains in figure/. That means that all subsequent conversions from .md to .pdf reference only one version of a figure. This breaks the tie between the final document, and the code used to generate it.

It may be worth naming files in figure/ in such a way that they are explicitly tied to a report. Not sure what the cleanest solution would be: perhaps appending a short hash of the report file name to the .png file name. Alternatively, you could simple warn users that a file in figure/ already exists with that name and suggest they rename their chunk.

**Comment by petrelharp** [comment]
I'd vote to re-open this, and take one of @vtrubets suggestions.  This is a major gotcha, and just because rmarkdown does it right doesn't mean that knitr doesn't need to: there's [good reasons](https://github.com/rstudio/rmarkdown/issues/499) to use knitr without rmarkdown on top of it.
