### ISSUE TITLE
knitr animations aren't self-contained

### ISSUE THREAD

**Issue by hughjonesd** [yihui/knitr#883]
Hi,

If I create a knitr vignette, then "knit HTML" from within Rstudio, or run build_vignettes() from devtools, by default a standalone webpage is created.

However, if I use fig.show=animate, then figures are not included in the web page and my vignette doesn't look good.

Is there any hope for this? At the moment I'm working around by creating the vignette manually.

Cheers,
David

**Comment by RhononLee** [comment]
Hello,
     I am writing for some help.Something about my code is as follows.
<link rel="stylesheet" href="http://vis.supstat.com/assets/themes/dinky/css/scianimator.css">
```{r,fig.width=4, fig.height=4, dpi=50, fig.show='animate', fig.path="img//"}
for(i in seq(-50,300, length=50)){
   plot_topo(m1, view=c("X","Y"), zlim=c(-6,4), el.pos=electrodes, cond=list(Time=i),main=paste("Time:",round(i)))
}
```
------------------------
The R Studio reports an error,it says _could not find ffmpeg command_
Please tell me what I should do next.I can't thank you anymore.

**Comment by RhononLee** [comment]
Hello,
I am writing for some help.Something about my code is as follows.

```{r,fig.width=4, fig.height=4, dpi=50, fig.show='animate', fig.path="img//"} 
for(i in seq(-50,300, length=50))
{ plot_topo(m1, view=c("X","Y"), zlim=c(-6,4), el.pos=electrodes, cond=list(Time=i),main=paste("Time:",round(i))) } 
```

 ------------------------ 
The R Studio reports an error,it says _could not find ffmpeg command_ 
Please tell me what I should do next.I can't thank you anymore.

**Comment by Frank-Sw** [comment]
@RhononLee You can try to put the ffmpeg.exe to the same folder of your rmd file, and then re-run. 

To me, no error, but no movie as well.

**Comment by yihui** [comment]
Now I recommend you to use gifski to avoid system dependencies like FFmpeg: https://yihui.name/en/2018/08/gifski-knitr/
