### ISSUE TITLE
kable output ignored when called in a for-loop

### ISSUE THREAD

**Issue by khughitt** [yihui/knitr#886]
Sometime during a recent revision, `kable` stopped working when called in a for-loop.

Example:

**kable_bug.rmd**

``````
```{r test1, results='asis'}
library(knitr)

# works
kable(head(iris))
kable(head(iris))
kable(head(iris))
```

```{r test2, restlts='asis'}
# works
for (i in 1:3) {
    cat('test\n')
}
```

```{r test3, results='asis'}
# doesn't work
for (i in 1:1) {
    kable(head(iris))
}
```
``````

The first couple chunks render correctly, while the third one does not include any of the output from `kable`.

I tried tracking down the issue real quick, but realized I don't understand enough about the internals of knitr yet and it would probably take me a while to figure this out (any suggestions for where to start learning about the rendering process?)

In the meantime I thought I would report this here in case it is an easy fix.

**System info**

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.7.9    setwidth_1.0-3 colorout_1.0-3 vimcom_1.0-5  

loaded via a namespace (and not attached):
[1] evaluate_0.5.5 formatR_1.0    stringr_0.6.2  tools_3.1.2   
```

knitr commit: 52c99eeaeb57fc0d69bac7f2771f7fe823afe416

**Comment by CiriLyon** [comment]
Setting the option '' **_results='asis'_** " solve the problem for me. 
I have had the same problem, i.e. "kable output was ignored when knitr::kable(anyDataFrame) was called inside a 'for' loop, and correctly executed outside of the 'for' loop". While 'print(knitr::kable(anyDataFrame)) ' was working fine inside a 'for' loop, this solution wasn't fully satisfactory because of its poor layouts. Setting the option '' results='asis' " has solved the problem, i.e  knitr::kable(anyDataFrame) was executed properly inside the 'for' loop.

**Comment by yihui** [comment]
@CiriLyon Please see this post for more technical reasons if you want: https://yihui.name/en/2017/06/top-level-r-expressions/

**Comment by sk-sahu** [comment]
With print() around kable() and results='asis' able to print the table inside for loop. But kable styling with pipe gives error.

```r
Error in if (!kable_format %in% c("html", "latex")) { : 
  argument is of length zero
Calls: <Anonymous> ... freduce -> withVisible -> <Anonymous> -> kable_styling
```

Any help?

**Comment by mkamalzare-rms** [comment]
Has this issue ever resolved? print(kable(...)) is not working correctly. If anyone knows any solution, I appreciate it if you can address the following post. Thanks! https://stackoverflow.com/questions/58334241/save-multiple-tables-using-markdown-kable-function-on-html-file

**Comment by levibaguley** [comment]
try `tinytex::reinstall_tinytex()` first if you are rendering to a pdf. That fixed it worked for me.
