### ISSUE TITLE
RStudio 中Knitr 输出中文的问题。

### ISSUE THREAD

**Issue by GeekZhou** [yihui/knitr#889]
```

---
title: "test"
output: pdf_document

---
#测试
This is an R Markdown document. Markdown is a simple formatting syntax for
authoring HTML, PDF, and MS Word documents. For more details on using R
Markdown see <http://rmarkdown.rstudio.com>.
```

测试这两个字在输出HTML和Word中可以显示，但是输出pdf时显示不了。求谢大师解答。

**Comment by andyfayecindy** [comment]
yihui你好，已经完全按照上述操作，可是中文转换成pdf还是报错
! LaTeX Error: Option clash for package color.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.33 \hypersetup

pandoc.exe: Error producing PDF from TeX source
错误: pandoc document conversion failed with error 43
此外: Warning message:
运行命令'"C:/Program Files/RStudio/bin/pandoc/pandoc" chinese1.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output chinese1.pdf --table-of-contents --toc-depth 2 --template "C:\PROGRA~1\R\R-32~1.2\library\rticles\RMARKD~1\TEMPLA~1\ctex\RESOUR~1\DEFAUL~1.LAT" --number-sections --highlight-style tango --latex-engine xelatex'的状态是43 
停止执行

实在没辙了，请教！

**Comment by yihui** [comment]
@andyfayecindy 是最新版的MikTeX以及所有LaTeX包都升级了吗？

**Comment by JacobZHANG2015** [comment]
遇到了同样的问题，解决不了，请教各位大神

**Comment by PrimulaLHD** [comment]
也是遇到了问题，请教！
! Undefined control sequence.
l.17 \sys_if_engine_luatex:T

pandoc.exe: Error producing PDF
错误: pandoc document conversion failed with error 43
此外: Warning message:
运行命令'"C:/Users/Hai-Dong/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS xxx.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output xxx.pdf --table-of-contents --toc-depth 2 --template "C:\Users\Hai-Dong\Documents\R\win-library\3.2\rticles\rmarkdown\templates\ctex\resources\default.latex" --number-sections --highlight-style tango --latex-engine xelatex'的状态是43 
停止执行

**Comment by oliyiyi** [comment]
我也是同样的错误，请指教
r3.3.0
rstudio 0.99.902
texlive 2015

**Comment by wangwenxia06083** [comment]
上面的问题大家的解决了吗，没看到回复呢

**Comment by yihui** [comment]
使劲更新你们的 MikTeX 或 TeXLive：https://yihui.name/en/2017/05/when-in-doubt-upgrade/

**Comment by YshanChen** [comment]
用rticles包可以在PDF的文本中显示中文，但用ggplot作的图里面的中文依然无法显示，比如坐标轴名称、坐标轴标签等涉及到中文的，都以'......'显示。求谢大大解答。
`---
title: "test"
author:
  - user
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: no
    toc: no
classoption: "hyperref,"
---`

**Comment by YshanChen** [comment]
用rticles包可以在PDF的文本中显示中文，但用ggplot作的图里面的中文依然无法显示，比如坐标轴名称、坐标轴标签等涉及到中文的，都以'......'显示。求谢大大解答。

**Comment by yihui** [comment]
这是完全不同的问题，以后在已经关闭的事项下面挖坟请三思，开发者很怕被挖老坟的 😭 

参见 Encoding of multibyte characters 一节：https://yihui.name/knitr/demo/graphics/

**Comment by WendyLin627** [comment]
找了几天的解决方法 还是不行 MikTex全更新 pandoc也是最新的 Rstudio也更新到最新的 一开始还能输出PDF但是 其他文件就完全无法输出o(╥﹏╥)o

**Comment by yihui** [comment]
@WendyLin627 来，把你的 MiKTeX 拆掉，然后帮我测试我新开发的 TinyTeX https://yihui.name/en/2017/12/test-tinytex/

**Comment by hekaiwen** [comment]
@YshanChen  图片中的中文显示为省略号的，可在pdf_document: 下，加一行：
dev: png
我也有同样的问题，将默认的pdf转为后png没问题。

**Comment by fengfengyuyu** [comment]
**@yihui** 我安装了TeXLive和TinyTeX。

TeXLive测试：

在Rstudio里添加TeXLive环境变量:
```
Sys.setenv(PATH=paste(Sys.getenv("PATH"),"/usr/local/texlive/2017/bin/x86_64-linux
",sep=":"));
x=Sys.getenv("PATH")[1];
library(stringr);
PATH=str_replace_all(x, "[\r\n]" , "");
Sys.setenv(PATH=PATH)
```

在Rstudio里新建一个Rmd文档，选择的模板是`CTeX Documents {rticles}`，直接编译，报错：

`kpathsea:`

 `Running mktexfmt pdftex.fmt`
 ` |.................................................................| 100%`
 ` ordinary text without R code`


`!!! Error: pdfTeX run failed with value 1!`
`output file: TS.knit.md`

但还是可以输出PDF文档。
```
/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS TS.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output TS.tex --table-of-contents --toc-depth 2 --template /home/f/R/x86_64-pc-linux-gnu-library/3.4/rticles/rmarkdown/templates/ctex/resources/default.latex --number-sections --highlight-style tango --latex-engine xelatex 

Output created: TS.pdf
```

但是图片并没有浮在下页，而是浮在上面去了，模板上说：

> 请不要问我为什么图浮动到下一页去了，这么初级的LaTeX问题问出来信不信我扁你。


测试TinyTeX：

`tinytex::install_tinytex(force = TRUE)`

报错：
```
TinyTeX installed to /home/f/.TinyTeX
Error in root_dir(normalizePath(path), "..", "..", "..") : 
  /usr/share/texlive does not seem to be the root directory of TeXLive (no "bin/" dir under it)
```
我的系统信息：

```
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8       
 [4] LC_COLLATE=zh_CN.UTF-8     LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tinytex_0.4   stringr_1.2.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  backports_1.1.2 magrittr_1.5    rprojroot_1.2   htmltools_0.3.6
 [6] tools_3.4.1     rticles_0.4.1   yaml_2.1.16     Rcpp_0.12.15    stringi_1.1.5  
[11] rmarkdown_1.9   knitr_1.20      digest_0.6.14   evaluate_0.10.1

```

**Comment by yihui** [comment]
@fengfengyuyu 对，你需要先把你电脑里现有的 TeXLive 庞然大物拆掉，它是一个又大又不中用的废物。而且你不需要修改 PATH 环境变量。

**Comment by fengfengyuyu** [comment]
**@yihui** 
测试电脑（公司服务器）信息：
```
sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.18    rmarkdown_1.8

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] htmltools_0.3.6 tools_3.4.3     rticles_0.4.1   yaml_2.1.16    
 [9] tinytex_0.4     Rcpp_0.12.14    stringi_1.1.6   stringr_1.2.0  
[13] digest_0.6.13   evaluate_0.10.1
``` 
Centos 有个问题，就是安装R的时候`sudo yum install R`，连带把 TexLive 一并安装了，如果我要卸载TexLive的时候 `yum remove tex-* texlive-*`，就会出现如下提示：

```
为依赖而移除:
 R                       x86_64 3.4.3-1.el7                         @epel 0.0  
 R-core                  x86_64 3.4.3-1.el7                         @epel  84 M
 R-core-devel            x86_64 3.4.3-1.el7                         @epel 361 k
 R-devel                 x86_64 3.4.3-1.el7                         @epel 0.0  
 texinfo-tex             x86_64 5.1-4.el7                           @base 436 k

事务概要
================================================================================
移除  212 软件包 (+5 依赖软件包)

安装大小：295 M
是否继续？[y/N]：
```
如果我同意了， TexLive 和 R 也就一并卸载了。

**Comment by yihui** [comment]
@fengfengyuyu 两点反馈：

1. 如果需要手动安装 LaTeX 包，那我做的工作就没啥意义啦；你需要用 rmarkdown 1.9 或跟高版本，在已经安装 tinytex 包的情况下，如果缺失 LaTeX 包会被自动安装，不必费劲一个个去装。

2. 我对 CentOS 的打包者强行绑定 R 和 TeXLive [表示强烈不满](https://yihui.name/cn/2017/12/homebrew-open-source/)，但我也没办法，这事情在 Ubuntu / Debian 下有解药：https://d.cosx.org/d/419672/84 我只熟悉这两个系统，别的系统不熟；目前只能按照你的修改 PATH 的方案走了。

**Comment by jackpgao** [comment]
设置png后会导致图片质量严重下降。字体都看不清。

**Comment by ylwpaopao** [comment]
@jackpgao 
png图片质量太差的话，还可以改为其它的device，如：
```yaml
dev: cairo_pdf
```
https://yihui.name/knitr/options/#plots 中对支持的device有详细的说明。

**Comment by statli** [comment]
大家问题解决了吗？我安装了TinyTeX和pandoc，可以使用rticles中的CTeX Documents创建完美的中文PDF，但是这个不能同时生成网页班的文档。于是就使用默认的Rmarkdown创建PDF，里边的中文或者乱码或者错误（我设置了UTF-8）。于是我卸载了TinyTex，安装MikTeX，有同样的错误。
![3](https://user-images.githubusercontent.com/34979978/48119548-7fb9c980-e2aa-11e8-8cc6-f25bb01ed525.PNG)

**Comment by hao203** [comment]
> 请安装rticles包（https://github.com/rstudio/rticles ）并按照模板 https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd 指示办。

我按您说的做了。也是安装的tinytex，安装了rticles 的包
但还是不行，只要一输出PDF就出错

> 错误: LaTeX failed to compile test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
> 此外: Warning messages:
> 1: In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
>   '"pdflatex"' not found
> 2: In system2(...) : '"pdflatex"' not found
> 停止执行
> 
> No LaTeX installation detected (LaTeX is required to create PDF output). You should install a LaTeX distribution for your platform: https://www.latex-project.org/get/
> 
>   If you are not sure, you may install TinyTeX in R: tinytex::install_tinytex()
> 
>   Otherwise consider MiKTeX on Windows - http://miktex.org
> 
>   MacTeX on macOS - https://tug.org/mactex/
>   (NOTE: Download with Safari rather than Chrome _strongly_ recommended)
> 
>   Linux: Use system package manager
>

**Comment by yihui** [comment]
消息提示里说：

> If you are not sure, you may install TinyTeX in R: tinytex::install_tinytex()

**Comment by hao203** [comment]
> tinytex::install_tinytex()

tinytex::install_tinytex()
Yes, I did that exactly， but it still does not work.

> This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/W32TeX) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> I was unable to find any missing LaTeX packages from the error log test.log.
> ! Argument of \CJK@XX has an extra }.
> <inserted text> 
>                 \par 
> l.42   pdfcreator={LaTeX via pandoc}}
> 
> 错误: LaTeX failed to compile test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test.log for more info.
> 停止执行

**Comment by shrektan** [comment]
> 真的，R markdown对中文支持确实太差了，我从昨晚折腾到现在，按你的教程反复安装了不知道多少遍。

这和rmarkdown就没关系好吗… 问题是LaTeX…

> 我决定退回vscode 直接写markdown了

你要是真的需要pdf输出，"vscode 直接写markdown了"就能给你LaTeX生成的pdf吗？要是不需要pdf输出直接生成html怎么会有问题呢？

而且，你提供的信息太少了，用的是windows还是macOS，直接用LaTeX输出有没有问题？

**Comment by hao203** [comment]
@shrektan 
感谢，这的确还是LaTeX问题。
我是用的Yihui给的前面，这个模板去输出的

> 请安装rticles包（https://github.com/rstudio/rticles ）并按照模板 https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd 指示办。


我说一下我的平台，我这边其实两个平台都试了，win 和linux（manjaro），但都不能成，就是最后报错，没中文没事，只要有一个中文字，就会出现错误提示，无法生成。

现在R的版本都是3.6.3的最新版，全部按Yihui老大额方法
tinytex::install_tinytex()
完成了安装。
你说的肯定没错，我也是这么想的，我觉得是安装过程中某些核心文件没有安装完整。

按照你的方法，成功了！

感谢
@yihui @shrektan

**Comment by shrektan** [comment]
可能显性地声明用xelatex是关键，你之前贴出来的错误代码看上去用的还是pdflatex

```rmd
output:
  pdf_document:
    latex_engine: xelatex
```

**Comment by hao203** [comment]
> 可能显性地声明用xelatex是关键，你之前贴出来的错误代码看上去用的还是pdflatex
> 
> ```gfm
> output:
>   pdf_document:
>     latex_engine: xelatex
> ```

是的。所以rticles package用的那个模板该更新了。我提交一个去

**Comment by hao203** [comment]
> 可能显性地声明用xelatex是关键，你之前贴出来的错误代码看上去用的还是pdflatex
> 
> 不过，我不知道为什么https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd 这个模板没有申明用xelatex，但是在我电脑上还是默认用的xelatex运行~
> 
> ```gfm
> output:
>   pdf_document:
>     latex_engine: xelatex
> ```

按这个模板是可以的，因为，这个模板默认是输出ctex
我这模板是老大的另外一个模板，所以出了问题，因为pdf那里没有声明，所以，我觉得2个路径
1.直接输出ctex

```
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
```
2.输出pdf时候，加个参数 latex_engine: xelatex

```
output:
  pdf_document:
    toc: yes
    latex_engine: xelatex
```

**Comment by yihui** [comment]
> 不过，我不知道为什么https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd 这个模板没有申明用xelatex

@shrektan 这是因为 `rticles::ctex` 默认就是用 `xelatex`，不需要显式声明（当然声明了也无妨）。

> 我这模板是老大的另外一个模板，所以出了问题

@hao203 来，告诉我你在哪儿找到的这个模板，我去把它砍了，免得它继续祸害人间。

**Comment by hao203** [comment]
> > 我这模板是老大的另外一个模板，所以出了问题
> 
> @hao203 来，告诉我你在哪儿找到的这个模板，我去把它砍了，免得它继续祸害人间。

哈哈。我不知道模板咋那样的。
确实是copy的，但又不记得哪来的。或许
output:
  pdf_document:
    toc: yes
这句是系统自动生成？问题解决了。感谢您的指导，现在用的不亦乐乎

**Comment by shrektan** [comment]
那下次认真审题吧… 谢大都已经写这么清楚了，让用这个模板，你还是没用… 这样你自己也白折腾半天，多不好。

> 请安装rticles包（https://github.com/rstudio/rticles ）并按照模板 https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd 指示办。
