### ISSUE TITLE
opts_knit$restore does not cover 'animation.fun'

### ISSUE THREAD

**Issue by julian-gehring** [yihui/knitr#929]
Calling `opts_knit$restore` should restore the default values of all options. This work, unless for `animation.fun` (with R 3.1.2 and knitr 1.8):

```{r}
library(knitr)
opts_knit$get("animation.fun") ## -> hook_ffmpeg
opts_knit$restore()
opts_knit$get("animation.fun") ## -> NULL
```

**Comment by yihui** [comment]
Should be fixed now. Thanks!
