### ISSUE TITLE
request for built-in python3 engine

### ISSUE THREAD

**Issue by bbolker** [yihui/knitr#930]
It takes a very tiny tweak to the existing "generic" engine (the one used for 16/25 of the engines, as indicated by
```
table(sapply(knit_engines$get(),function(x) isTRUE(all.equal(x,knit_engines$get("python")))))
```
to allow the use of python3 instead of python.  All I had to do was add a `python3` tag in 

```
else paste(switch(engine, bash = "-c", coffee = "-e", groovy = "-e", 
        node = "-e", perl = "-e", python = "-c", python3 = "-c", ruby = "-e", 
        scala = "-e", sh = "-c", zsh = "-c", NULL), shQuote(paste(options$code, 
        collapse = "\n")))
```

That seems like a fairly harmless/incremental change (although I guess ultimately if the list expanded too much it might make more sense to build this as a named list that associated command-line switches with engines).

This is easy enough to work around with my own custom code, but it would be nice to add it to the package.  

Could submit a pull request if that's your preference.

**Comment by yihui** [comment]
You can specify a different executable for any engines, e.g.

    ```{r engine='python', engine.path='python3'}
    import sys
    print(sys.version_info)
    ```

so I won't need to care about python3 or python4 or python2... Is that good enough?

**Comment by bbolker** [comment]
yes, that works fine.  Thanks.

**Comment by sahilseth** [comment]
Is there a way to setup default engine path for python?

Something of the sorts:

```
library(knitr)
knit_engines$set("python")(engine.path="~/apps/python/3.5/bin/python")
```

**Comment by yihui** [comment]
@sahilseth Yes:

```r
knitr::knit_engines$set(
  engine.path = list(python = "~/apps/python/3.5/bin/python")
)
```

**Comment by sahilseth** [comment]
That's awesome!

**Comment by pbahr** [comment]
I'm using knitr 1.15.1 and it looks like the above code doesn't work to set the default python engine for me. I verified it using the following chunk:

```{python}
import sys
print (sys.version_info)
```
The output is as follows:

```
sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
```

I have updated the python3 path according to my setup. When I use `engine.path= ` in the chunk setting, it works properly.

**Comment by mikey-harper** [comment]
I have encountered the same issue as @pbahr , and I'm struggling to change the engine path globally. However it works when I set the `engine.path=` setting within the chunk.  

Let me know whether I can provide any additional information to help troubleshoot the issue.

**Comment by pbahr** [comment]
@yihui your advice is highly appreciated. I was not sure if our comments on a closed issue are getting noticed.

**Comment by yihui** [comment]
@mikey-harper @pbahr Have you checked out FAQ 1? https://github.com/yihui/knitr/blob/master/FAQ.md

**Comment by mikey-harper** [comment]
@yihui  Thanks for getting back so quickly. Problem solved,  not sure exactly what I changed as everything was up to date but probably something to do with Python as I ended up reinstalling that. In case anyone else has the same issue, I got it working as follows:

```r
library(knitr)
knitr::knit_engines$set(
  engine.path = list(python = "C:/Python27/python.exe")
)
```
And then to execute the python script I set a chunk with the options as `{python}`:

``` python
import os
a = os.path.join("foo", "bar")
print(a)
```

    ## foo\bar
