### ISSUE TITLE
Make Rmd file also a valid R file

### ISSUE THREAD

**Issue by kindlychung** [yihui/knitr#931]
I am thinking if we allow this kind of format:

    #```{r}
    f = function(x, y) {
        x^2 + y^2
    }
    #```

then a .Rmd file would also be a valid R file, which could be a nice feature for many people.

**Comment by yihui** [comment]
See http://rmarkdown.rstudio.com/r_notebook_format.html

**Comment by kindlychung** [comment]
Amazing, Yihui. Many thanks for this wonder tool!
