### ISSUE TITLE
Automatically purge cache files of code chunks that don't exist anymore

### ISSUE THREAD

**Issue by sjmgarnier** [yihui/knitr#933]
Currently knitr keeps all cache files that it created, even those of code chunks that have been removed or which name has been modified. This leads up to the presence of unused files in the cache directory which sometimes can contain large datasets taking up unnecessary space. It would be convenient if knitr had an option to auto-purge the cache from all these unused files.

**Comment by yihui** [comment]
Thanks for the report. Actually this thing bothers myself as well, so I will definitely think about it.

**Comment by sjmgarnier** [comment]
Cool! Thanks. 

It would also help me clean up the mess that the Rmarkdown editor I'm developing leaves behind it ([editR](https://github.com/swarm-lab/editR), work in progress). To speed up the instant preview, I cache the chunks automatically. However each time I add a letter to a chunk name (for instance as I write it for the first time) it creates new cache files and they tend to accumulate over time. I'm still trying to figure out the best solution to avoid this.

**Comment by sjmgarnier** [comment]
Fantastic! Thanks.

**Comment by yihui** [comment]
You are welcome. Note clean_cache() may not really work well in all cases. Please read its help page.
