### ISSUE TITLE
Support for clojure

### ISSUE THREAD

**Issue by kindlychung** [yihui/knitr#936]
Is there a plan to add support for clojure?

**Comment by yihui** [comment]
No. I do not know anything about closure. Bring your pull request, and we can talk then :)

https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

**Comment by kindlychung** [comment]
Cool. Where do I start if I want to add support for a certain language? 
I suppose a program is needed to eval a string to get results. Clojure is a Lisp, so that shouldn't be too hard.

**Comment by yihui** [comment]
You can see how other engines are defined in https://github.com/yihui/knitr/blob/master/R/engine.R Thanks!

**Comment by kindlychung** [comment]
I am reading engine.R and in line 93, I see

    cmd = options$engine.path %n% engine

What is %n% here? Is it a typo?
