### ISSUE TITLE
Load libraries of depended chunks

### ISSUE THREAD

**Issue by wush978** [yihui/knitr#939]
At first, I want to thank you for the great work of knitr. I use it to produce almost all of my publications.

Here is a use case that I usually encounter. https://gist.github.com/wush978/62fd21bb6f0b2248f6ea 

There are two chunks in `test.Rmd` while the second one depends on the first one which is cached. There is an expression of `library(Matrix)` in the first chunk. Therefore, the result of `knitr::knit` will produce an error at second chunk because it cannot find the `Matrix::sparse.model.matrix`.

Is it possible to record the search path of the cached chunk and reload the packages during parsing the chunks which is depending on the cached one?

Thanks.

**Comment by yihui** [comment]
The packages loaded in cached chunks will be reloaded the next time a cached chunk is to be updated, but you have to turn on caching first. In your example, I think the chunk `c2` has to be cached as well.

**Comment by wush978** [comment]
Thanks for your response, but I think it will be more convenient to extend this feature(reloading packages) for uncached chunks.

Do you want to add this feature to un-cached chunks? I could spend some of my time to implement this feature, if you like.

**Comment by yihui** [comment]
What is the disadvantage of putting `library(Matrix)` in an un-cached chunk so that you always load it?

**Comment by wush978** [comment]
It is ok for me to not have this feature. 

But I think the `knitr` will  better if the result is not affected by whether it is cached or un-cached. And it will be more convenient if I don't need to add the line `library` in the second un-cached chunk. Note that the user does not need to eval `library` when he/she is developing the script in the second chunk.

**Comment by yihui** [comment]
Yeah I understand what you mean. I have documented it at http://yihui.name/knitr/demo/cache/

In your case, I do not mean you `library(Matrix)` in the second chunk, but I mean you do it before the first chunk. If you are going to use the Matrix package anyway in this document, why not keep it always loaded throughout the whole document? I do not see much benefit of caching `library(Matrix)`.

Loading packages for uncached chunks may not always be desirable or necessary. It is trivially easy for you to load packages in an un-cached chunk, and moderately difficult for me to implement a new feature. That is why I prefer you to do it. I hope that makes sense.

**Comment by wush978** [comment]
I agree your statement. Thanks.

**Comment by yihui** [comment]
Thanks for your understanding :)
