### ISSUE TITLE
Couple small problems with setting fig.path and base.dir together

### ISSUE THREAD

**Issue by daattali** [yihui/knitr#942]
I noticed two related problems when specifying a `base.dir` combined with specifying a `fig.path` that contains a directory (ie. has a path separator rather than simply being a filename prefix).

**1. An error comes up if the figure directory doesn't exist**  
This is the error I always get  
```
Error in png(..., res = dpi, units = "in") : unable to start png() device
In addition: Warning messages:
1: In png(..., res = dpi, units = "in") :
  unable to open file 'figdir/unnamed-chunk-1-1.png' for writing
2: In png(..., res = dpi, units = "in") : opening device failed
```

Steps to reproduce:   
- create a simple Rmd that generated a figure. I use this code in a file called `plotme.Rmd`

        ``` {r}
        plot(runif(10))
        ```
- set the `base.dir` to any directory that is not the current directory. For example, `knitr::opts_knit$set(base.dir = "outdir")`  
- create the `outdir` directory, otherwise knitr will error (not sure if this is a bug or expected?)  
- set the `fig.path` to a string that contains a path. For example `knitr::opts_chunk$set(fig.path = "figdir/")`  
- knit the document.  `knitr::knit("plotme.Rmd")`  
- hopefully you also get the same error message as above  

**2. The `figdir` directory gets created in the wrong place and has nothing in it**  
When there is a `base.dir` defined and the `fig.path` contains a directory, then that directory is created both inside `base.dir` (which is correct), but it also gets created in the working directory.  
To reproduce, continue from the previous steps and just create a directory `figdir` under `outdir`.  Now running knitr works, but an empty `figdir` directory is created in the working dir.

-------

Environment: Windows 7, R 3.1.2, knitr 1.8

**Comment by cheebingloh** [comment]
Hi, Is there any way to solve this issue?

**Comment by daattali** [comment]
My current solution is I wrote my own wrapper around knitr that fixes this

**Comment by yihui** [comment]
Both issues should be fixed now. Thanks!
