### ISSUE TITLE
Improvements to spin, making sense of working directories

### ISSUE THREAD

**Issue by daattali** [yihui/knitr#943]
(Potentially related to #913)

Hi Yihui

As we discussed yesterday in the LA Shiny meetup, I have written a wrapper around `spin` that IMO makes it more usable for real-life scenarios.  I wanted to post it here to get your and other people's opinions.

[Vignette describing the problem and solution](https://github.com/daattali/rsalad/blob/master/inst/doc/spinMyR.md)  |  [Link to source code](https://github.com/daattali/rsalad/blob/master/R/spinMyR.R)

TL;DR of the vignette linked above: I use `spin` all the time and the main problem I have with it is that I have no way of using it with a complex directory structure. I like having my scripts in one directory, the inputs in another directory, and the output markdown/html in another.  `spin` assumes that the working directory is where the script lives, which is very often not the case, and `spin` doesn't let you control where the outputs go.  I made a function that wraps around `spin` in a way that I think is very easy to manage directories, and has a few other parameters too that I find useful.  I called it `spinMyR` because it was a block of code that I added to all my scripts that I would use to spin my R script.

If you agree that there is benefit in what I wrote, maybe it could be incorporated into knitr

Enjoy your visit home :)

**Comment by krlmlr** [comment]
This is just awesome! Works like a charm, out of the box, probably saved me a few hours of depressing wd trickery.

**Comment by daattali** [comment]
Glad to know others find it useful as well, thanks :)

**Comment by yihui** [comment]
Closing this issue with a pointer to https://github.com/daattali/ezknitr
