### ISSUE TITLE
Support base64 image output

### ISSUE THREAD

**Issue by renkun-ken** [yihui/knitr#944]
Sometimes I need the Rmd to be not self-contained so that the HTML page does not include giant jQuery and Bootstrap libraries. But a side-effect is that image-producing chunks also result in standalone pictures in local directory.

Is it possible for knitr to support base64 image output so that the HTML is not self-contained for the JavaScript libraries but self-contained for the images (which is rendered and stored in HTML in base64 code)? In this case, I often want my images are included but the libraries are loaded from remote CDNs.

My current implementation of this looks like

```r
library("htmltools")
library("caTools")
filename <- tempfile()
png(filename, width = 600, height = 400)
plot(mpg ~ wt, data = mtcars)
invisible(dev.off())
bin <- readBin(filename, file.info(filename)$size, what = "raw")
file.remove(filename)
base64txt <- base64encode(bin)
tags$img(title = "plot of mtcars", src = paste0("data:image/png;base64,", base64txt))
```

Maybe an option for chunks can be added to indicate that this figure should be output as base64?

**Comment by ramnathv** [comment]
This can be easily accomplished using hooks. My simple solution would involve abusing the `upload.fun` chunk option to do our bidding.

```r
knitr::opts_knit$set(upload.fun = function(x){
  base64enc::dataURI(file = x, mime = "image/png")
})
```

@yihui might have a more elegant hook to do the same.

**Comment by yihui** [comment]
Or just `upload.fun = knitr::image_uri` so you do not need to depend on base64enc or take care of the mimetype.

**Comment by renkun-ken** [comment]
@yihui, thanks a lot! It perfectly works!
