### ISSUE TITLE
run_chunk ?

### ISSUE THREAD

**Issue by drknexus** [yihui/knitr#945]
I suggest the addition of a `run_chunk` feature.  `run_chunk` would take loaded chunks (via `load_chunk`) and allow them to be run interactively.  This is particularly useful when sourcing a Rmd file for the purposes of debugging as Rstudio does not follow the empty chunk reference automatically.  It is also useful when there are dependencies between chunks and one doesn't want to always have to move around in the document to identify (and run) the relevant antecedent code.

An implementation might look something like:
```
#' Run a previously loaded chunk interactively
#'
#' Takes labeled code loaded with load_chunk and runs it in the /global/ envir (unless otherwise specified)
#'
#' @param chunkName The name of the chunk as a character string
#' @param envir The environment in which the chunk is to be evaluated
run_chunk <- function(chunkName,envir=.GlobalEnv) {
   chunkName <- unlist(lapply(as.list(substitute(.(chunkName)))[-1], as.character))
   eval(parse(text=knitr:::knit_code$get(chunkName)),envir=envir)
}
NULL
```

Per the contribution guidelines since this is a feature implementation I thought I'd make the suggestion here before doing any pushing and pulling.  Is this a feature you would consider adding to knitr?  Or does it already exist?

**Comment by drknexus** [comment]
... I guess this runs afoul of your position that .Rmd files shouldn't be used as source files (http://r.789695.n4.nabble.com/R-CMD-check-for-the-R-code-from-vignettes-td4691457.html) / the help file for knit?  I can see that you don't want to use purl to reproduce the computation from knit() but it might be nice to have the functions available without having to put them in their own file and/or make a package for them.

**Comment by yihui** [comment]
I do not think your implementation would work, since `knit_code` will be restored (emptied) after `knit()` exits...

**Comment by drknexus** [comment]
However, in the proposed use case, knit is neither entered or exited because all code is being interactively by the user. So,  the labeled source chunks loaded via load_chuck can be (and do in practice) run with the above code.

**Comment by yihui** [comment]
I guess I'm not going implement this by myself (I feel it is pretty tricky), but I can probably take a look at it if a pull request is submitted. Thanks!
