### ISSUE TITLE
engine = "tikz" stops on warnings...not just errors. 

### ISSUE THREAD

**Issue by mienkoja** [yihui/knitr#947]
When I run the new version of knitr, which includes the feature stemming from issue #897, I get the following message back from knitr:

```
convert.exe: iCCP: profile 'default_rgb.icc': 0h: PCS illuminant is not D50 
'C:/Users/mienkoja/AppData/Local/Temp/magick-11148QAz4QgZyDsZV1' @ warning/png.c/MagickPNGWarningHandler/1831.
Quitting from lines 16-31 (annual_review.Rmd) 
Error in (knit_engines$get(options$engine))(options) : 
  problems with `convert`; probably not installed?
Calls: <Anonymous> ... process_group.block -> call_block -> block_exec -> in_dir -> <Anonymous>
Execution halted
```
This is apparently because knitr appears to be halting on warnings, not just errors returned by the convert function (`if (conv != 0) stop('problems with convert; probably not installed?')`). 

Anyway we could get knitr to ignore convert warnings?

**Comment by yihui** [comment]
I guess it will no longer stop if you use the chunk option `error = TRUE`.
