### ISSUE TITLE
Unwanted rounding of decimals in knitted HTML

### ISSUE THREAD

**Issue by AlunHewinson** [yihui/knitr#949]
In the following example, the knitted html document shows rounded integers instead of decimals.  I have checked the source of the html page to confirm that this is not a browser issue.
Please note that the three backticks are missing from this example.  That's is just because I couldn't find a way to get them to appear on this issue post; they *are* present in my code.

```
---
title: "Decimals appearing as integers"
author: "Alun Hewinson"
date: "Monday, February 02, 2015"
output: html_document
---

Unwanted rounding of decimals in knitr!
```{r}
## Output should be 2014.1, not 2014
2014.1
2014.9
## closing backticks missing due to formatting on website: please insert before running 
```

**Comment by yihui** [comment]
It seems you did not read the contributing guide: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md

I cannot reproduce this issue with the latest version of knitr.
