### ISSUE TITLE
Which document is being knit?

### ISSUE THREAD

**Issue by klmr** [yihui/knitr#950]
This is related to #564: My code needs to find out whether it’s being called from inside a knitr document. However, in addition to that, it needs to find out *which* document is being knit, i.e. the full path to that document.

The background for this is klmr/modules#31: *modules* needs to know the base path of its calling code in order to resolve relative import file locations. At the moment, it resolves to the directory of the code which kicks off the knitting process, which is usually not the correct directory.

Inside *modules* I cannot fix this issue without requiring the user to manually specify the module base path, which I’d like to avoid.

## MWE:

* **`doc.rmd`**:

        ```{r}
        devtools::install_github('klmr/modules')
        modules::import('./test')
        ```

* **`test.r`**:

    ```r
    message('I was called correctly.\n')
    ```

* **`script/knit`**:

    ```r
    #!/usr/bin/env Rscript
    knitr::knit('doc.rmd', 'doc.md')
    ```

```bash
chmod +x script/knit
./script/knit
```

### Expected output:

> […]  
> \#\# I was called correctly!

### Actual output:

> […]  
> \#\# Error in `modules::import("./test")`: Unable to load module `./test`; not found in `"./script"`

**Comment by yihui** [comment]
I don't fully understand the modules package, but when you are in knitr code chunks, the working directory is the directory that contains the input document by default. See the Note section in `?knitr::knit`.

**Comment by klmr** [comment]
Apologies, I should have described this better:

Unfortunately the working directory doesn’t help me — in fact, *modules* intentionally does *not* use the working directory since that is generally completely arbitrary and has no relation to the file being executed. Instead, *modules* detects whether the code was launched via `Rscript` or `R CMD BATCH` ([`littler` is on the TO DO list](/klmr/modules/issues/49)), and uses the path of *that* script.

In the MWE given above, this would be `script/knit`, so *modules* thinks that the base path is `script` (which would be correct for calls to `modules::import` inside `script/knit`; if *modules* were to use `getwd()`, this would not work if the user invoked the script via `./script/knit` rather than via `./knit`).

**Comment by yihui** [comment]
Got you. I think `knitr::current_input(dir = TRUE)` does what you want now.

**Comment by klmr** [comment]
Thanks, this looks almost perfect, there’s just one issue:

*After* a call to `knit`, the function *still* returns the file path (rather than `NULL` as it did before calls to `knitr`) — this one’s simple, it seems that `knit` should have an

```r
on.exit(knit_concord$set(infile = NULL, outfile = NULL), add = TRUE)
```

[after line 192](https://github.com/yihui/knitr/blob/8e2910e091f1438f1ff2df3c9c9171a8a73d831d/R/output.R#L192).

**Comment by yihui** [comment]
I have got it early on there: https://github.com/yihui/knitr/blob/8e2910e091f1438f1ff2df3c9c9171a8a73d831d/R/output.R#L132

Just pushed a fix to check if `knit_concord$get('infile')` is NULL. Thanks!

**Comment by klmr** [comment]
:+1: Thanks a lot.
