### ISSUE TITLE
does not check that ghostscript exists when running pdfcrop

### ISSUE THREAD

**Issue by dalupus** [yihui/knitr#954]
If you try to run knitr with pdfcrop installed but don't have ghostscript you get the error:
!!! Error: Ghostscript exited with error code 127!
from pdfcrop.

If you run pdfcrop in debug mode you find that this simply means it can't find ghostscript.

If pdfcrop has a dependency on ghostscript then it should be checked that it exists before running it and have a warning that it doesn't exist if it doesn't.

**Comment by yihui** [comment]
Thanks for the report, but I'm afraid this would mean too much responsibility on my side. The pdfcrop homepage has stated anyway that it depends on Ghostscript: http://pdfcrop.sourceforge.net and I have never received a report on this issue before, so I assume it is a rare issue.

**Comment by skanskan** [comment]
I have the same error when compiling some latex code with pdflatex.
```
\documentclass[border=3pt, x11names]{standalone}%
\usepackage{pst-node}
\usepackage{auto-pst-pdf}
\begin{document}
\sffamily
\psset{algebraic, yunit = -1, arrows=->, arrowinset=0.12, linecolor=SteelBlue3, fillcolor=SlateGray3!60, nodesepB=1pt}
\begin{pspicture*}
  \foreach \X[count=\I] in {A, B, C, D, E} {\Cnodeput[linecolor=SteelBlue4, fillstyle=solid]{0}(\I, \I){\X}{\X}}
  \foreach \X/\Y in{A/B, B/C, C/D, D/E}{\ncline{\X}{\Y}}
  \ncarc[arcangle=-25]{A}{D}
\end{pspicture*}
\end{document}

```

**Comment by jtbayly** [comment]
I don't know if this is a problem, but I'm seeing this error when building a book with bookdown using the default demo book with one additional line:

```
```{r, echo=FALSE, fig.align='center', out.width='50%'}
knitr::include_graphics("images/am_I_crazy.png")
```
```

**Comment by yihui** [comment]
@jtbayly That's too little information for us to tell anything. Please read and follow [the issue guide](new) exactly to provide all the required information. Thanks!

**Comment by jtbayly** [comment]
I’m sorry, but I don’t have any idea what versions of things are used in the Travis CI build process (except Pandoc, which is specified in the demo book .travis.yml file as pandoc_version: 1.19.2.1). I also don’t know how to get an xfun session out of the Travis virtual machine. 

I’m just reporting it as a courtesy. If you care about it or think it’s worth looking into it, you can build the demo book with Travis CI, after adding a sub-directory with an image and that line above. 

Sorry I can’t provide more in this instance without more instruction.

**Comment by yihui** [comment]
No worries. Could you at least provide a link to the Travis log (or better, your Github repo as a reproducible example)?

Without further information, it's really hard to guess. There was a bug related to this before **knitr** 1.28, but I have fixed it earlier this year: https://github.com/yihui/knitr/releases/tag/v1.28 If you are using the latest version of **knitr**, I cannot think of a reason why this problem can still occur.

**Comment by jtbayly** [comment]
This [particular branch](https://github.com/warhornmedia/bookdown-test/tree/ghostscript_error) seems to build just fine, but has the error in the Travis CI log.

Here's the [Travis log](https://api.travis-ci.org/v3/job/725361459/log.txt).

Perhaps the Travis CI builds aren't using knitr 1.28 yet?

**Comment by yihui** [comment]
From https://travis-ci.org/github/warhornmedia/bookdown-test/builds/725242542, the actual error was:

```
! LaTeX Error: File `../images/am_I_crazy' not found.
Error: LaTeX failed to compile bookdown-demo.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See bookdown-demo.log for more info.
```

That was caused by the fact that the image does not exist.

The ghostscript issue caused a warning:

```
In addition: Warning message:
In system2("pdfcrop", shQuote(c(x, x)), stdout = if (quiet) FALSE else "") :
  error in running command
```

This only means figure cropping failed: https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html I'm not sure if you really need this feature. If you don't, you can turn it off by setting `knitr::opts_chunk$set(crop = NULL)`.

I'm not sure what's going on with ghostscript on Travis, and I don't have time to debug it. Sorry.

**Comment by yihui** [comment]
@dalupus I take back what I said in 2015. Looking at the replies above and linked issues, I feel that it is obviously a highly confusing problem to many people. Therefore I just added the check for the existence of `ghostscript`. I definitely owe you a "thank you" and it's probably not too late five years later :)

**Comment by jtbayly** [comment]
I’m so sorry I sent the log with the additional error. That is definitely a separate issue that I was working on. I meant to send the data with only the Ghostscript error.

**Comment by yihui** [comment]
@jtbayly No worries. I think we are all set now. You can either merge https://github.com/warhornmedia/bookdown-test/pull/1 or

```r
remotes::install_github(c('yihui/knitr', 'rstudio/rmarkdown'))
```
