### ISSUE TITLE
Enable user to specify handling of duplicate chunk labels

### ISSUE THREAD

**Issue by khughitt** [yihui/knitr#957]
Would it be possible to provide an option to control how knitr deals with redundant chunk labels? To be consistent, the default behavior could be to not allow them and `stop()` as is currently done.

It would be very useful to have an option to simply append a counter as is currently done for unnamed chunks.

For example, in a common use case, I have one master document (e.g. `parent.rmd`) and several child documents, each with a number of chunks.

If I attempt to re-use the same child-chunks, however, this will fail:

**parent.rmd**

```r
# settings
settings = list(...)

# run once
knit_child('useful_analysis.rmd')

# new settings
settings = list(...)

# run again
knit_child('useful_analysis.rmd')
```

To get around this, the two option are to either not use any chunk names for the child documents, which results in anonymous figure and cache names, or to use `knit_template()` in the parent document with `results=asis`:

```r
cat(knit_child(text=unlist(knit_expand(file='useful_analysis.rmd'))))   
```

But this is also not ideal and results in all of the plots using the chunk label from the parent document, instead of the labels from the child chunks, and requires disabling of the progress meter (which otherwise is appended to the output), making debugging a bit more difficult.

**Comment by yihui** [comment]
Please see 470cbbf0111868bb00d1d66693beda326537d789. You may need to set the option in `~/.Rprofile`. Thanks!

**Comment by khughitt** [comment]
Fantastic! Thanks, Yihui! t
