### ISSUE TITLE
fig.align = 'centre' is not working for pdf output in knitr_1.9.3

### ISSUE THREAD

**Issue by byzheng** [yihui/knitr#960]
Today I update knitr to 1.9.3 (the latest version in github), then fig.align = 'centre' stops to working for pdf output. The error message is: 

    output file: Preview-9685285e5ee4.knit.md

    pandoc: Error producing PDF from TeX source.
    ! Undefined control sequence.
    l.130 \begin{center}\includegraphics

    Error: pandoc document conversion failed with error 43
    Execution halted

Thanks if you can fix it.

**Comment by yihui** [comment]
You can add this to the YAML frontmatter:

```
---
graphics: yes
---
```

**Comment by yihui** [comment]
BTW, it is `fig.align = 'center'` instead of `centre`.
