### ISSUE TITLE
Maintain fig.width and height when reusing chunk

### ISSUE THREAD

**Issue by mreq** [yihui/knitr#961]
When reusing a chunk (I want to print figure R codes in appendix) figure options get overriden.

Minimal working example:
```knitr
\documentclass{article}

\begin{document}

	This should produce a 9x3 plot:

	<<test, echo=FALSE, out.width='\\linewidth', fig.width=9, fig.height=3>>=
		curve(dnorm(x), from=-2, to=2)
	@

	But it doesn't, as this chunk seems to change the \texttt{fig.width} and \texttt{fig.height}.

	<<test, echo=TRUE, results='markup', fig.show='hide'>>=
	@

\end{document}
```

Output:

![1424806367](https://cloud.githubusercontent.com/assets/1286942/6357379/54c34e4c-bc64-11e4-86d8-2238d650bbe9.png)

**Comment by yihui** [comment]
Sorry, I don't think this is trivial to implement (i.e. not a few minutes' work), so I will only consider it if there is a pull request. Thanks!
