### ISSUE TITLE
different way to specify engines  ```{r engine='python'} ->  ```{python} 

### ISSUE THREAD

**Issue by JanSchulz** [yihui/knitr#963]
Re: https://twitter.com/xieyihui/status/571162828528185345

Just because I recently wanted to support `'''{python}` (`'''{r engine='python'}` ->  `'''{python}`) in a python port of knitr and had to include that in the regex I use:

```
    chunk_begin = '^\s*```+\s*{[.]?([a-z]+)\s*(.*)}\s*$'
    chunk_end = '^\s*```+\s*$'
    inline_code = '`([a-z]+) +([^`]+)\s*`'
```

And then in parser.R:36

```R
      params.src = if (group_pattern(chunk.begin)) {
        tmp <- str_trim(gsub(chunk.begin, '\\2', g[1]))
        engine <- str_trim(gsub(chunk.begin, '\\1', g[1]))
        if(engine != "r"){
            tmp <- paste(tmp, ", engine='",engine,"'"
        }
        tmp
      } else ''
```
(this is probably not valid R code... :-/ )

**Comment by yihui** [comment]
That sounds like a good idea. I'll think about it. Thanks!

**Comment by kevinushey** [comment]
@yihui, do you plan on making this work generally for all language modes, so that e.g. all of the following are valid?

    ```{python}
    ```

    ```{css}
    ```

Just wondering because on the RStudio side it might be nice to have snippet insertions for each form.

**Comment by yihui** [comment]
@kevinushey Yes, it will be a general form like

    ```{lang}

for all language engines.

**Comment by JanSchulz** [comment]
In the interest of adding all arguments, I would like to add this here, which I found out at [my side](https://github.com/JanSchulz/knitpy/) when I implemented chunk options. 

It seems that knitr uses eval to build the plotting chunk options, so valid R code is possible to be included in the options. Even if you use `engine="python"`, the plotting options are still evaluated as R code, so a python `True` will probably error in rmd (-> `TRUE`). 

IMO this is an argument to keep using `{r ... engine="python"}`, because the options are "R" and not "python". On the other hand, knitpy uses `.pymd` and not `.rmd` as a file extensions, so one could argue that this already is enough to distinguish between r and py...

-> all in all, I think that file extensions are enough and `{lang}` would be nice.

**Comment by yihui** [comment]
@JanSchulz Thanks! I'm not trying to throw away `{r engine=???}`: I just want to add `{???}` as a shorthand of it. I guess the vast majority of knitr users are R users, so I'm not seriously concerned about the `True` issue, and I'd encourage them to use your knitpy if they are more comfortable with the Python syntax :)

**Comment by yihui** [comment]
Done.
