### ISSUE TITLE
fig.align='center' causes graph output to not render in word.docx

### ISSUE THREAD

**Issue by DaveRGP** [yihui/knitr#964]
Using knitr with RStudio and using the Knit Word functionality, setting the chunk options to `<fig.align='center'>` means that the graph does not appear in the knit-ed document.

I see that there is a documented warning for them, though is there a preferred function for word that should be used?

**Comment by yihui** [comment]
If you update your knitr package to the latest version (http://bit.ly/knitr-faq), the graph should appear, although the alignment setting will be ignored.

**Comment by DaveRGP** [comment]
Thank you for your response, it's amazing and fantastic to have this kind of support from a developer/creator.
