### ISSUE TITLE
Proposed function: knitr::custom_knit

### ISSUE THREAD

**Issue by lmmx** [yihui/knitr#965]
There's currently an undocumented ability to specify a `knit:` hook in Rmarkdown YAML headers and replace `rmarkdown::render` with something else in RStudio, as used for example in [slidify](https://github.com/ramnathv/slidify/commit/07794a3c2d228822c173c1ad5eacf5ab54a42062#diff-1), and which I describe further potential uses for in notes [here](https://github.com/lmmx/devnotes/wiki/Rmarkdown-custom-knit-hook-to-compile-a-multi-part-document).

This could provide a sort of `make` for Rmarkdown, with metadata-directed knitting of e.g. files that may be added through `includes:` in YAML headers, or as `{r child=...}` code chunk references within the document itself (see notes linked above for examples, and [this repository](https://github.com/lmmx/tomasetti-vogelstein-2015)).

Although a Knit button running the above is user-friendly, it's natural to want to be able to replicate the button's behaviour as a command, which I presume would be best placed in the `rmarkdown` package (thus available within RStudio by default).

@cboettig recommended in [this thread](https://github.com/ropensci/reproducibility-guide/pull/81#issuecomment-76936284) that there should be a way to call said custom function from the command-line.

I recommend a function e.g. `rmarkdown::custom_knit` :

```r
custom_knit <- function(filename, encoding) {
    rmd.content <-  paste( readLines(filename) , sep = "\n" )
    yaml.range <- which('---' == rmd.content)[1:2]
    if (all(is.na(yaml.range))) { knit.function <- rmarkdown::render } else {
        yaml.header.range <- setdiff(do.call(seq, as.list(yaml.range)), yaml.range)
        rmd.yaml <- paste(rmd.content[yaml.header.range], collapse="\n")
        knit.hook <- yaml::yaml.load(rmd.yaml)$knit
        if (is.null(knit.hook)) {knit.function <- rmarkdown::render} else { 
            knit.func.str <- as.function(as.list(knit.hook))()
            knit.function <- eval(parse(text = call(knit.func.str)))
        }
    }
    return(knit.function(filename, encoding = encoding))
}
```

Running the function on for example the 'analysis.Rmd' file of [this example repo](https://github.com/lmmx/tomasetti-vogelstein-2015):

```r
custom_knit('documents/analysis.Rmd', 'UTF-8')
```

would then run the same as the button in RStudio.

* The above handles both anonymous functions and those sourced as `package::function` (e.g. test with `knit: slidify::knit2slides` in YAML of `analysis.Rmd`). If no `knit:` hook is present it uses `rmarkdown::render` as the knit function.
* Do others feel it would be better suited to a modification of another function, e.g. as behaviour triggered by a parameter in some existing function? e.g.

   ```r
render(input, encoding, custom_knit = TRUE)
```

I [originally submitted](https://github.com/rstudio/rmarkdown/issues/389) this to the rmarkdown repository, but on second thoughts it seems more appropriate for knitr. If I've misunderstood please let me know and I'll reopen the other, thanks.

**Comment by yihui** [comment]
I thought a while about this. I can see the advantage of using one function `custom_knit()` to compile arbitrary Rmd documents, but I tend not to add this to knitr since R Markdown is just one type of document formats that knitr supports. I think you can just define the `knit` function in a package (like `slidify::knit2slides`), or in an R script (`knit: source('foo.R')$value`). Both approaches will make it more convenient so that you don't write a huge line of R code in the `knit` field, and when you want to compile the document outside RStudio, you can still reuse the function.

**Comment by lmmx** [comment]
Oh, yes, I like the idea of sourcing from an external R file, excellent. Thanks Yihui
