### ISSUE TITLE
dev='tikz', external=F gives error

### ISSUE THREAD

**Issue by yipcma** [yihui/knitr#967]
in an .Rmd where dev='tikz' , external = F, in the .tex generated, \includegraphics{foo.tikz} is used. And pandoc doesn't like it:

pandoc: Unable to convert image `foo.tikz':
Cannot load file

thoughts and recommendations?

**Comment by yihui** [comment]
I think this issue should be reported to Pandoc instead. I tried `fig.ext = 'tex'`, and I have the same error: Pandoc does not allow `\includegraphics{foo.tex}`, either, which should be legitimate in LaTeX.
