### ISSUE TITLE
problem with knit2html when using hook_webGL

### ISSUE THREAD

**Issue by etheleon** [yihui/knitr#969]
Tried running `knit2html` on a rmd with rgl 3d plot. 
The plot is not rendered in the output HTML. 

rglClass was not included in the `.html`
and CanvasMatrix.js was not generated.

Changed the hook_webgl function and set commonParts argument in rgl::writeWebGL to true permanently and it worked. 

Is this a bug?

http://stackoverflow.com/questions/14879210/including-a-interactive-3d-figure-with-knitr

**Comment by yihui** [comment]
I tested the CRAN version of rgl (0.95.1201) and I could not reproduce the problem. You said in the SO post that you were using rgl 0.95.1227, and it sounds like you installed it from RForge or elsewhere. I think you need to report the rgl author (@dmurdoch) if the development version broke what used to work.

**Comment by dmurdoch** [comment]
The R-forge version is undergoing a number of changes that will take a while to stabilize.  They will need changes to the hook function; when things are finally stable, I'll send those to Yihui.

In the meantime, I have a version of the hook function in vignettes/setup.R that should work.  If that one doesn't, please report to me on the R-forge bug page.  -- Duncan Murdoch
