### ISSUE TITLE
Broken LaTeX header when package options are wraped in {}

### ISSUE THREAD

**Issue by hofnerb** [yihui/knitr#971]
When I `knit` this minimal example

    \documentclass[hyperref={colorlinks=true}]{beamer}

    \begin{document}
    Some text
    \end{document}

I get the following output

    \documentclass[hyperref={colorlinks=true}\usepackage[]{graphicx}\usepackage[]{color}
    %% maxwidth is the original width if it is less than linewidth
    %% otherwise use linewidth (to make sure the graphics do not exceed the margin)
    \makeatletter
    \def\maxwidth{ %
      \ifdim\Gin@nat@width>\linewidth
        \linewidth
      \else
        \Gin@nat@width
      \fi
    }
    \makeatother
     
    \definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
    \newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
    \newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
    \newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
    \newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
    \newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
    \newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
    \newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
    \newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
    \newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
     
    \usepackage{framed}
    \makeatletter
    \newenvironment{kframe}{%
     \def\at@end@of@kframe{}%
     \ifinner\ifhmode%
      \def\at@end@of@kframe{\end{minipage}}%
      \begin{minipage}{\columnwidth}%
     \fi\fi%
     \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
     \colorbox{shadecolor}{##1}\hskip-\fboxsep
         % There is no \\@totalrightmargin, so:
         \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
     \MakeFramed {\advance\hsize-\width
       \@totalleftmargin\z@ \linewidth\hsize
       \@setminipage}}%
     {\par\unskip\endMakeFramed%
     \at@end@of@kframe}
    \makeatother
     
    \definecolor{shadecolor}{rgb}{.97, .97, .97}
    \definecolor{messagecolor}{rgb}{0, 0, 0}
    \definecolor{warningcolor}{rgb}{1, 0, 1}
    \definecolor{errorcolor}{rgb}{1, 0, 0}
    \newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX
     
    \usepackage{alltt}]{beamer}
    \IfFileExists{upquote.sty}{\usepackage{upquote}}{}
    \begin{document}
    Some text
    \end{document}

which is a corrupted LaTeX file. The knitr definitions are erroneously inserted after the closing curly bracket of `{colorlinks=true}` and not (as it should be) after `{beamer}`. I currently have no solution to this problem but I think one must consider that all brackets that were opened are closed before inserting the definitions.

**Comment by krlmlr** [comment]
Have you tried using `\PassOptionsToClass`, `\PassOptionsToPackage`, or calling `\hypersetup` later? Like:

```
\PassOptionsToClass{hyperref={colorlinks=true}}{beamer}
\documentclass{beamer}
```

or

```
\documentclass{beamer}
\hypersetup{colorlinks=true}
```
?

That said, it will be probably difficult to solve this in `knitr` in a robust way.

**Comment by hofnerb** [comment]
Thank you. At least the second approach works fine for me. 

However, I think `knitr` should/could be (a bit) more robust here so there is no need to tweak LaTeX. As I said: Checking that all open braces are closed before we enter the `knitr` header might be worth a try. I just tried to figure out were to add changes in the pattern but I wasn't successfull.

**Comment by krlmlr** [comment]
This is because you cannot check that braces are paired using (pure) regular expressions only. I'm not sure if it can be done at all with Perl's flavor.

Another approach would be to match `^[\\]documentclass.*[{][^{}]*[}][ \t]*$`, thus expecting the declaration of the document class to be on a single line. An error could be thrown if the match fails.

**Comment by yihui** [comment]
@krlmlr is absolutely correct, and I have no interest in writing a robust LaTeX parser in R. As long as there is a workaround, I tend not to invest time in it, even though I admit it is a real problem. If you want to spend time on it, pull requests will be much appreciated :)
