### ISSUE TITLE
RStudio 'line by line' run works with RMD code but not knit to PDF/HTML/DOC

### ISSUE THREAD

**Issue by splaisan** [yihui/knitr#976]
I am making a tutorial for the DESeq2 bioconductor package and fail to compile it in RStudio.
RStudio knits any other document I made so far but fails on this one DESeq2 command:

```r
dds <- DESeqDataSetFromHTSeqCount(sampleTable = sampleTable,
                                  directory = directory,
                                  design = ~ cells + treatment)
```

The error only occurs when knitting, the code works with 'run'

![screen shot 2015-03-16 at 11 30 19](https://cloud.githubusercontent.com/assets/858516/6664588/7f68bdd6-cbd1-11e4-89a9-f39e2d5f96ee.png)

![screen shot 2015-03-16 at 11 30 09](https://cloud.githubusercontent.com/assets/858516/6664585/79fe29bc-cbd1-11e4-906c-6be1730c47cb.png)

I put the data and RMD script here if you would be so kind to help me fix it
<http://data.bits.vib.be/pub/trainingen/NGSRNADE2015/varia/Archive.zip>

Thanks for any solution to this weird issue.

    ---
    title: "DESeq2_analysis HTSeq error"
    output: pdf_document
    ---

    works line by line and fails using knit PDF (idem for other knits)

    ## Required packages

    ```{r, message=FALSE, warning=FALSE}
    library("DESeq2")

    # Loading required package: S4Vectors
    # Loading required package: stats4
    # Loading required package: BiocGenerics
    # Loading required package: parallel
    # 
    # Attaching package: ‘BiocGenerics’
    # 
    # The following objects are masked from ‘package:parallel’:
    # 
    #     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport,
    #     clusterMap, parApply, parCapply, parLapply, parLapplyLB, parRapply, parSapply,
    #     parSapplyLB
    # 
    # The following object is masked from ‘package:stats’:
    # 
    #     xtabs
    # 
    # The following objects are masked from ‘package:base’:
    # 
    #     anyDuplicated, append, as.data.frame, as.vector, cbind, colnames, do.call,
    #     duplicated, eval, evalq, Filter, Find, get, intersect, is.unsorted, lapply, Map,
    #     mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position,
    #     rank, rbind, Reduce, rep.int, rownames, sapply, setdiff, sort, table, tapply,
    #     union, unique, unlist, unsplit
    # 
    # Loading required package: IRanges
    # Loading required package: GenomicRanges
    # Loading required package: GenomeInfoDb
    # Loading required package: Rcpp
    # Loading required package: RcppArmadillo
    ```

    # load data

    ```{r}
    # please adapt this location to match your own environment
    basedir <- "~/Desktop"
    setwd(basedir)

    directory <- "htseq_counts"

    # load metadata
    metadata <- read.table("GSE52778_metadata.txt", header = TRUE)
    metadata$sampleFiles <- paste( metadata$run_accession, "_all_counts.txt", sep="")

    # restrict to untreated and Dex samples
    selectedRows <- metadata[grep("untreated|^Dex", metadata$treatment), ]

    sampleTable <- data.frame(sampleName = selectedRows$run_accession,
      fileName = selectedRows$sampleFiles,
      cells = selectedRows$cells,
      treatment = selectedRows$treatment)

    sampleTable
    ```

    ## HTSeq input

    Load HTSeq data into a DESeq2 object.

    ```{r}
    dds <- DESeqDataSetFromHTSeqCount(sampleTable = sampleTable,
                                      directory = directory,
                                      design = ~ cells + treatment)

    # review the object
    dds

    # column information
    colData(dds)

    # relevel to get untreated as reference
    dds$treatment <- relevel(dds$treatment, "untreated")
    ```

    ```{r, eval=FALSE}
    sessionInfo()

    # R version 3.1.3 (2015-03-09)
    # Platform: x86_64-apple-darwin13.4.0 (64-bit)
    # Running under: OS X 10.9.5 (Mavericks)

    # locale:
    # [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    # attached base packages:
    # [1] stats     graphics  grDevices utils     datasets  methods   base     

    # other attached packages:
    # [1] knitr_1.9

    # loaded via a namespace (and not attached):
    # [1] digest_0.6.8    htmltools_0.2.6 rmarkdown_0.5.1 tools_3.1.3     yaml_2.1.13
    ```

**Comment by yihui** [comment]
Sorry, but `setwd()` is transient in knitr code chunks. It only works in a single chunk, and its side-effect will not be carried over to the next chunk. I have updated the documentation `?knitr::knit` to make this clearer.

**Comment by splaisan** [comment]
Thanks so much, 

I did not get the error. Now works with full path
Weird that I never noticed this behavior, I always start my documents by re-rooting to the working folder though.

Would be nice to set the base folder globally for a whole document; maybe like for other parameters in the header, this would facilitate portability to other machines

Anyway, thanks for your wonderful software

Stephane Plaisance
stephane.plaisance@vib.be

**Comment by splaisan** [comment]
Dear Yihui,

I call your help once more for something I thought I could do -but fails

I do all my work in RStudio using knitr to PDF

I have a scipt with a loop from within which I need to print a data table and the corresponsing multiplot
I before only had the table and it worked but adding the plot (also tried print()) fails
I lso failed inserting a new page at each loop using cat(’\\NewPage’)


Thanks for any help in correcting my error

Stephane



> ```{r, results='asis'}
> # analyze data per run, split by 'RunId'
> runs <- split( rawm, rawm$RunId )
> 
> # delim line
> my.sep=paste(rep("#", 50), collapse = "")
> 
> for ( r in 1:length(runs) ) {
> 
>   one.run <- runs[[r]]
>   
>   # split/analyze data per cycle
>   run.cycles <- split(one.run, one.run$ScanNumber)
>   
>   # fix '@' in run.name
>   run.name <- gsub("@", "\\@", samples[r,2], fixed = TRUE)
>   
>   cat( "\n### results for run:", r, "(", run.name, ")" )
>   
>   # create initial row with data from all scans
>   tot.dna.len <- sum(one.run$Length)/1000
>   tot.mol <- nrow(one.run)
>   avg.len <- sum(one.run$Length)/nrow(one.run)/1000
>   med.len <- median(one.run$Length)/1000
>   N50.len <- round(calc.n50(one.run$Length)/1000, 2)
>   label.cnt <- sum(one.run$NumberofLabels)
>   avg.lab.int <- sum(one.run$AvgIntensity)/nrow(one.run)
>   avg.lab.SNR <- sum(one.run$SNR)/nrow(one.run)
>   
>   # create table from first raw
>   run.summary.table <- data.frame(tot.dna.len, tot.mol, avg.len, med.len,
>                               N50.len, label.cnt, avg.lab.int, avg.lab.SNR)
>   
>   # add rows for separate cycli
>   for ( c in 1:length(run.cycles) ) {
>     new.row <- c(
>       sum(run.cycles[[c]]$Length)/1000,
>       nrow(run.cycles[[c]]),
>       sum(run.cycles[[c]]$Length)/nrow(run.cycles[[c]])/1000,
>       median(run.cycles[[c]]$Length)/1000,
>       calc.n50(run.cycles[[c]]$Length)/1000,
>       sum(run.cycles[[c]]$NumberofLabels),
>       sum(run.cycles[[c]]$AvgIntensity)/nrow(run.cycles[[c]]),
>       sum(run.cycles[[c]]$SNR)/nrow(run.cycles[[c]])
>       )
>     run.summary.table <- rbind(run.summary.table, new.row)
>     }
>   
>   # name rows
>   row.names(run.summary.table) <- c("All scans", 
>                    paste("scan", 1:length(run.cycles), sep=" "))
>   
>   # print table to report
>   print( kable(run.summary.table, format = "pandoc", digits=2) )
>   
>   # plot key metrics per cycle (omit row#1=total)
>   # print ( plot.ts(run.summary.table[-1,], main=paste(""), xlab="", las=1, cex.lab=0.75, cex.axis=0.75) )
>   plot.ts(run.summary.table[-1,], main=paste(""), xlab="", las=1, cex.lab=0.75, cex.axis=0.75)
>   
>   # insert new page also failed using the next line
>   #cat('\\newpage')
> 
>   }
> ```


I get the following with the plot replaced by some pseudo table
