### ISSUE TITLE
custom latex environment for captions?

### ISSUE THREAD

**Issue by casallas** [yihui/knitr#977]
working on my dissertation I realized that Iowa State's preferred environment for captions is `\isucaption` instead of the good old `\caption`. This also happens with other LaTeX templates, e.g., ACM-small uses `\tbl` instead of `\caption`, so it would be nice if the user could specify a global option, maybe `cap.env`, or even `fig.cap.env`, and `kbl.cap.env`.

I'm willing to spend some time on this, and create a PR but just wanted to have your thoughts first.

**Comment by yihui** [comment]
Errr, I'm glad that I graduated... What you can do, though, is to redefine the `plot` hook, and replace `\caption` with `\isucaption`, e.g.

```r
library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    res = hook_plot(x, options)
    gsub('\\caption', '\\isucaption', res, fixed = TRUE)
  })
})
```

_Not tested_. You may want to tweak the `gsub()` part.

**Comment by yihui** [comment]
BTW, if you have questions, please consider http://stackoverflow.com/tags/knitr Thanks!

**Comment by casallas** [comment]
Thanks Yihui for the elegant solution, I have just tried it and it worked like a charm! I hadn't really used custom hooks before but they seem really useful; next time I'll try to use stackoverflow for my questions, thanks!

**Comment by yihui** [comment]
No problem. Good luck with your dissertation!

To know more about the hook functions, you can take a look at my book "Dynamic Documents with R and knitr". There is a copy in the department library on the second floor of Snedecor Hall. Not sure if you can check it out. I have given a few copies to faculty and students in the stats department, and you can also borrow from them. I don't think it is important to read the book. Normally StackOverflow should just give you answers.

**Comment by casallas** [comment]
that's good to know, if I come up with another need for hook functions I'll definitely check the book out!
