### ISSUE TITLE
custom split character for fig.scap?

### ISSUE THREAD

**Issue by casallas** [yihui/knitr#978]
I noticed that the default value for `fig.scap` is the first part of `fig.cap` split by either `$`, `:`, `.`, or `;` (https://github.com/yihui/knitr/blob/master/R/hooks-latex.R#L121), which seems to work well for most stuff except for captions such as `Estimates of $y ~ N(a, b)$`, in which case the `fig.scap` (and thus the text in table of figures/tables) is the fragment `Estimates of `.
What do you think if there was an option such as `fig.scap.split` which would default to the current values, but can be changed per-chunk or globally? Again I can spend some time on this but wanted to have your thoughts first...

**Comment by yihui** [comment]
I'd recommend you to just pass a value to `fig.scap`, e.g. `fig.scap = "Estimates of $y ~ N(a, b)$"`. It is probably not worth the time making this little trick infinitely smart :)
