### ISSUE TITLE
kable() cannot handle East Asian wide characters when format="pandoc"

### ISSUE THREAD

**Issue by yutannihilation** [yihui/knitr#980]
Thanks for your great work!

I got problem when I use `kable()` with some data containing East Asian wide characters. `kable()` seems to assume that their width is 1 unit, while [pandoc thinks their width is 2 units](https://github.com/jgm/pandoc/blob/b983adf0d0cbc98d2da1e2751f46ae1f93352be6/src/Text/Pandoc/Pretty.hs#L489-L490). So, table is not knitted correctly when some row contains more-than-three “East Asian wide characters” because each column is only two spaces away.

The code bellow is a minimal example; third and fourth row are knitted incorrectly. Knitted version of example is here: https://rpubs.com/yutannihilation/66064

```r
a <- read.csv(text = '
    "A",  "B", "C",  "D",  "E"
    "a",  "a", "a", 1.23, 1.23
    "囧", "a", "a", 1.23, 1.23
    "囧","囧","囧", 1.23, 1.23
    "囧囧囧","a","a", 1.23, 1.23', stringsAsFactors = FALSE)
kable(a, format="pandoc")
#> 
#> 
#> A     B     C        D      E
#> ----  ----  ---  -----  -----
#> a       a    a    1.23   1.23
#> 囧      a     a    1.23   1.23
#> 囧     囧     囧     1.23   1.23
#> 囧囧囧   a     a     1.23   1.23
```

I know this is avoidable if I use `format="markdown"`, though. I'm not sure if this should be treated as a known issue or a bug...

**Comment by yihui** [comment]
All I can tell you at the moment is the possible direction to fix it: `nchar(x, 'width')` gives the width of characters. Then look for `str_pad` in the source code: https://github.com/yihui/knitr/blob/master/R/table.R And try to fix it by yourself, or find an expert to do it :) I will be waiting for a pull request. Thanks!

**Comment by yutannihilation** [comment]
Wow, sounds great! I'm not good at writing codes, but I will try :) Thanks!

**Comment by yutannihilation** [comment]
Hi, I created a pull request, which may not great codes but "just works".

I believe this adjustment is a temporal workaround and should be removed when `stringr::str_pad()` gets able to handle East Asian Width (I will report this Issue to stringr's repo later).

```r
    adj = nchar(m[, j], type = 'width') - nchar(m[ ,j], type = 'chars')
```
