### ISSUE TITLE
Inconsistent file naming

### ISSUE THREAD

**Issue by gillheller** [yihui/knitr#983]
Hello, I have been using knitr for a while,  on both my Macbook at home, and my Windows machine at work. I never had any problems with compatibility. I am generating pdf files which land up in the figure subdirectory with names like foo.pdf. Last week I updated my version of R on Windows, and now am getting files named foo-1.pdf and these are incompatible with what I'm generating on my Mac, and also with my collaborators. Is there a way of specifying the filenames?

**Comment by yihui** [comment]
This change was introduced almost half a year ago. Please take a look at the changelog of knitr 1.7: https://github.com/yihui/knitr/releases (section "Major Changes") Sorry about the trouble, but as long as you use the same version of knitr, you should have consistent filenames.

**Comment by gillheller** [comment]
Thanks for the speedy reply.
