### ISSUE TITLE
dev='png' results in error for latex/pdf output

### ISSUE THREAD

**Issue by jmlondon** [yihui/knitr#986]
The following code is taken from the RStudio example/template Rmd file. If I am content with pdf format figures, then this example runs fine. However, with really complex figures it is often preferable to use png format for the figures. I set the global device to PNG using `opts_chunk$set()`

```
---
output: pdf_document
---
```{r}
library(knitr)
opts_chunk$set(dev='png')
```
```{r, echo=FALSE}
plot(cars)
```

Unfortunately, the following error is returned.

```
Quitting from lines 16-17 (test.Rmd) 
Error in check.options(new, name.opt = ".X11.Options", envir = .X11env) : 
  c("invalid argument name 'pdf' in '(function (filename = \"Rplot%03d.png\", width = 480, height = 480, '", "invalid argument name 'pdf' in '    units = \"px\", pointsize = 12, bg = \"white\", res = NA, ..., '", "invalid argument name 'pdf' in '    type = c(\"cairo\", \"cairo-png\", \"Xlib\", \"quartz\"), antialias) '", "invalid argument name 'pdf' in '{'", "invalid argument name 'pdf' in '    if (!checkIntFormat(filename)) '", "invalid argument name 'pdf' in '        stop(\"invalid 'filename'\")'", 
"invalid argument name 'pdf' in '    g <- .geometry(width, height, units, res)'", "invalid argument name 'pdf' in '    new <- list(...)'", "invalid argument name 'pdf' in '    if (missing(type)) '", "invalid argument name 'pdf' in '        type <- getOption(\"bitmapType\")'", "invalid argument name 'pdf' in '    type <- match.arg(type)'", "invalid argument name 'pdf' in '    if (!missing(antialias)) '", "invalid argument name 'pdf' in '        new$antialias <- match.arg(antialias,
Calls: <Anonymous> ... chunk_device -> dev_new -> do.call -> <Anonymous> -> check.options
Execution halted
```

This same error is returned if I specify `dev='png'` at the chunk level.

I can workaround the issue by specifying

```
opts_chunk$set(dev='png',dev.args=list(type='cairo'))
```

However, this results in very poor quality font rendering (I'm not entirely sure if that is related or a completely separate issue).

I feel like this is a relatively recent issue that has cropped up. I noticed there was a recent change in knitr to use `grDevices::png()` so maybe this is related to that?? The issue is only related to generation of PDF output from RStudio/Knitr. HTML output looks just as I would expect and no error is thrown when specifying `dev='png'`.

details of my system:

```
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet     
```

```
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109
```

**Comment by yihui** [comment]
I guess this has been fixed via 51ce34922b7b59769c7d186d8189f49fb0a5f134. Please install the development version and try again. Thanks!

**Comment by jmlondon** [comment]
Development version installed and the issue is resolved. Thanks for the quick response and apologies for not finding the stackoverflow question sooner.

**Comment by yihui** [comment]
No worries. Not your fault at all :)
