### ISSUE TITLE
pandoc issue knitting @-containing text to PDF

### ISSUE THREAD

**Issue by splaisan** [yihui/knitr#990]
I have a line reporting a string containing '@' characters that causes PDF output failure
I need the 'asis' to print 'kable' tables nice from within the same loop enclosing the cat command.
If I remove the 'asis' the cat prints are +/- OK but the kable-printed table are ugly

    ```{r, results='asis'}
    for ( r in 1:length(runs) ) {
      my.string <- "22@23-1@1234ABCDE1-1_AbcdEF"
      cat( "\n### results for run:", r, "(", my.string, ")" )
    print( kable(run.summary.table, format = "pandoc", digits=2) )
    }
    ```

- builds nicely to HTML and without leading '#'s
results for run: 1 ( 22@23-1@1234ABCDE1-1_AbcdEF )

- but when knitting to PDF I get
```text

! File ended while scanning use of \@@BOOKMARK.
<inserted text> 
                \par 
l.77 \begin{document}

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

How can I escape/quote/neutralize this string and make it just printed through to PDF as.is by pandoc?

Thanks in advance

**Comment by splaisan** [comment]
I fixed it using gsub but remain interested to learn another way
```text
my.string <- gsub("@", "\\@", my.string, fixed = TRUE)
```

**Comment by yihui** [comment]
I'm afraid that is the only way to go... You have to escape special characters by yourself when `results = 'asis'`.
