### ISSUE TITLE
Support svgz format to reduce file size

### ISSUE THREAD

**Issue by renkun-ken** [yihui/knitr#993]
HTML pages with some svg embedded are really large. Recently I notice that `svgz` is a gzip-compressed version of `svg` but I'm not sure if it is easy for knitr to support rendering plots to `svgz`. Maybe it should work in two passes: first, use existing svg renderers to produce svg, and output via gzip compression.

From the [a documentation](http://www.w3.org/TR/SVG/minimize.html) the huge html consisting of several svgs with many points should be largely reduced in file size.

I did some informal tests on this: 

Create a rmarkdown document with the following code chuck which generates 50 images.

```r
library(PerformanceAnalytics)
invisible(lapply(1:50, function(i) {
  x <- xts(rnorm(500, 0.0001, 0.01), seq(as.Date("2010-01-01"), by = "day", length.out = 500))
  charts.PerformanceSummary(x)
}))
```

Here's some benchmark on my computer:

HTML with | naked size | gzip size
--:|--:|--:
png | 4.1MB | 2.57MB
svg | 21.1MB | 2.35MB

Really appreciate if anybody shows a way to correctly produce svgz.

The following posts may help:

1. http://graphicdesign.stackexchange.com.80bola.com/questions/24797/when-should-i-use-svg-or-svgz-for-my-web-graphics

**Comment by yihui** [comment]
You can write a gzip function and apply it to the chunk option `fig.process`, e.g. `fig.process = fig_gz`:

```r
compress_gz = function(path)
  tmpz = tempfile()
  conz = gzfile(tmpz, 'wb', encoding = 'UTF-8')
  tryCatch(writeLines(readLines(path, encoding = 'UTF-8'), conz), finally = close(conz))
  file.rename(tmpz, path)
}
fig_gz = function(path) {
  if (grepl('[.]svg$', path)) compress_gz(path) else path
}
```

That is just one possible implementation in R. You can even use `system2('gzip', path)` if gzip is available in your system.

I'm a little worried about the browser support, though.

**Comment by renkun-ken** [comment]
Thanks for the reply! I tried to produce a gzipped svg and embed it via data-uri. Sadly none of my browsers shows it correctly. I search the problem and it seems that the it may work under the correct server configuration. Currently, svgz may not easily work.

**Comment by yihui** [comment]
Well, Chrome actually works if you do not use data URI.

**Comment by renkun-ken** [comment]
Thanks for your reminding!
