### ISSUE TITLE
`cache=1` or `cache=2` dont work with `cache.extra` technique

### ISSUE THREAD

**Issue by zachary-foster** [yihui/knitr#994]
I’m not sure if this is a bug or a design feature, but I thought I would mention it since it threw me off. As discussed in [Issue #238](https://github.com/yihui/knitr/issues/238), using undefined chunk options to add additional requirements to the cache validation is very useful for checking for new input files. However, this does not work when `cache=1` or `cache=2`.

I think this is because `cache.extra` is not in the list of things that affect the cache for `cache=1` or `cache=2`:

```{r}
# options that should affect cache when cache level = 1,2
cache1.opts = c('code', 'eval', 'cache', 'cache.path', 'message', 'warning', 'error')
# more options affecting cache level 2
cache2.opts = c('fig.keep', 'fig.path', 'fix.ext', 'dev', 'dpi', 'dev.args', 'fig.width', 'fig.height')
```

You can see this using the following chunk.  When `cache=1` or `cache=2`, it will pause the first knit, but not on following knits, whereas `cache=TRUE` always pauses.

```{r}
```{r cache=1, cache.extra=sample(1:1000)}
Sys.sleep(5)
```

Should  `cache.extra`  be in `cache1.opts`? 

Thanks.

**Comment by yihui** [comment]
I'd say it is by design. The point of cache = 1 or 2 is to restrict the chunk options that can possibly invalidate the cache, and make caching less sensitive regarding changes in chunk options.

**Comment by zachary-foster** [comment]
Ok, sounds good. Just thought i would make sure it was working as it should.
